import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from"react";

export type Language="hu"|"en";
type Dictionary=Record<string,string>;
type LanguageContextValue={language:Language;locale:string;setLanguage:(language:Language)=>void;t:(key:string,fallback?:string)=>string};

const STORAGE_KEY="kleo_language";

const HU:Dictionary={
 "language.hu":"Magyar","language.en":"English",
 "common.search":"Keresés","common.filter":"Szűrés","common.reset":"Alaphelyzet","common.refresh":"Frissítés","common.loading":"Betöltés…","common.details":"Részletek","common.all":"Mind","common.results":"találat","common.restore":"Visszaállítás","common.archive":"Lomtárba helyezés","common.cancel":"Mégse","common.reason":"Indoklás","common.close":"Bezárás","common.save":"Mentés","common.saving":"Mentés…","common.active":"Aktív","common.inactive":"Inaktív","common.edit":"Szerkesztés","common.choose":"Válasszon","common.none":"Nincs megadva","common.export":"Export",
 "shell.dashboard":"Irányítópult","shell.finance":"Pénzügy","shell.inventory":"Raktár és készlet","shell.services":"Szolgáltatások","shell.products":"Termékek","shell.notifications":"Értesítési központ","shell.permissions":"Jogosultságok és hozzáférések","shell.audit":"Audit és rendszeresemény-napló","shell.chat":"Munkatársi chat felügyelet","shell.location":"Telephely","shell.all_locations":"Minden telephely","shell.quick_search":"Gyorskeresés…","shell.logout":"Kijelentkezés","shell.vir":"Kleoszalon VIR","shell.staff":"Kleoszalon munkatársi felület","shell.language":"Nyelv",
 "login.title":"Kleoszalon Belépés","login.tagline":"Modern szépségszalon-hálózat prémium szolgáltatásokkal, átlátható foglalási rendszerrel és professzionális munkatársakkal – mindezt egyetlen felületen kezelve.","login.subtitle":"Egyetlen belépési felület ügyfeleknek, munkatársaknak és adminisztrátoroknak. A rendszer automatikusan a megfelelő jogosultságot és telephelyet használja.","login.identifier":"E-mail vagy felhasználónév","login.identifier_placeholder":"E-mail cím vagy felhasználónév","login.password":"Jelszó","login.submit":"Belépés","login.loading":"Belépés…","login.forgot":"Elfelejtett jelszó?","login.register_intro":"Új ügyfél vagy?","login.register":"Ügyfél regisztráció","login.idle":"Biztonsági okból 5 perc tétlenség után automatikusan kijelentkeztettünk. A folytatáshoz jelentkezz be újra.","login.required":"Add meg az e-mail címedet vagy felhasználónevedet és a jelszavadat.","login.unexpected":"Váratlan hiba történt a bejelentkezés során.","login.persist_error":"Nem sikerült elmenteni a belépési adatokat.","login.show_password":"Jelszó megjelenítése","login.hide_password":"Jelszó elrejtése",
 "staff.eyebrow":"CSAPAT ÉS HR","staff.title":"Munkatársak listája","staff.description":"Munkakörönként csoportosított munkatársi törzs, HR- és béradatokkal.","staff.positions_title":"Munkakörök","staff.positions_description":"Munkakörök és alap bérezési paraméterek.","staff.add":"Hozzáadás","staff.active_count":"Aktív munkatárs","staff.position_groups":"Munkakörcsoport","staff.location_count":"Használt telephely","staff.monthly_total":"Havi alapbér összesen","staff.search":"Keresés név, e-mail, telefon, munkakör vagy telephely alapján…","staff.position":"Munkakör","staff.all_positions":"Összes","staff.location":"Telephely","staff.all_locations":"Összes telephely","staff.employment_type":"Alkalmazás formája","staff.monthly_wage":"Havi alapbér","staff.hourly_wage":"Óradíj","staff.commission":"Jutalék","staff.status":"Státusz","staff.include_inactive":"Inaktívak is","staff.found":"Találat","staff.empty":"Nincs a szűrésnek megfelelő munkatárs.","staff.expand":"Kibontás","staff.collapse":"Összecsukás","staff.professional":"Szakember","staff.no_qualification":"Nincs megadva végzettség","staff.no_location":"Nincs telephely","staff.new_title":"Új munkatárs","staff.edit_title":"Munkatárs szerkesztése","staff.modal_description":"Személyes, foglalkoztatási és bérezési adatok.","staff.full_name":"Teljes név *","staff.email":"E-mail","staff.phone":"Telefonszám","staff.qualification":"Végzettség","staff.active_employee":"Aktív munkatárs","staff.saved":"A munkatárs adatai frissültek.","staff.created":"Az új munkatárs létrejött.","staff.base_monthly":"Alap havibér","staff.no_description":"Nincs leírás megadva.","staff.people":"fő",
 "crm.eyebrow":"ÜGYFELEK ÉS CRM","crm.description":"Egységes vendégadatok, kezelési előzmények és személyre szabott kapcsolattartás.","crm.tab.list":"Ügyféltörzs","crm.tab.profiles":"Adatlapok és előzmények","crm.tab.forms":"Kérdőívek és nyilatkozatok","crm.tab.segments":"Címkék és szegmensek","crm.tab.import":"Import és duplikációk","crm.new_customer":"Új ügyfél","crm.import_altegio":"Altegio XLSX import","crm.importing":"Altegio import folyamatban…","crm.total":"Összes ügyfél","crm.active_guest":"Aktív vendég","crm.new_this_month":"Új ebben a hónapban","crm.with_no_show":"Meg nem jelenéssel","crm.search":"Keresés név, telefon, város, cím vagy címke alapján…","crm.all_status":"Minden állapot","crm.all_tags":"Minden címke","crm.customer":"Ügyfél","crm.contact":"Kapcsolat","crm.activity":"Aktivitás","crm.no_match":"Nincs a szűrésnek megfelelő ügyfél.","crm.no_tag":"Nincs címke","crm.no_email":"Nincs e-mail","crm.visits":"látogatás","crm.last":"Utolsó","crm.no_show":"no-show","crm.segments_title":"Címkék és ügyfélszegmensek","crm.segments_desc":"A címkék az adatlapokon azonnal hozzárendelhetők.","crm.new_tag":"Új címke","crm.assigned":"hozzárendelt ügyfél","crm.forms_title":"Kérdőívek és nyilatkozatok","crm.forms_desc":"Egészségügyi állapotfelmérők és adatkezelési hozzájárulások.","crm.new_template":"Új sablon","crm.questionnaire":"KÉRDŐÍV","crm.consent":"NYILATKOZAT","crm.no_description":"Nincs leírás.","crm.completions":"kitöltés","crm.import_title":"Altegio ügyfélimport","crm.import_desc":"Az Altegio rendszerből exportált XLSX ügyfélfájlt töltsd fel. A kategóriák ügyfélcímkékké válnak, a rendszer telefonszám/e-mail alapján frissíti a már meglévő vendéget.","crm.import_select":"Altegio XLSX kiválasztása","crm.duplicates":"Lehetséges duplikációk","crm.duplicates_desc":"Azonos e-mail-cím vagy telefonszám alapján.","crm.no_duplicates":"Nem találtunk összevonandó rekordot.","crm.saved":"Ügyféladatok mentve.","crm.created":"Új ügyfél létrehozva.","crm.note_saved":"Megjegyzés rögzítve.","crm.tag_created":"Új címke létrehozva.","crm.template_created":"Dokumentumsablon létrehozva.",
 "audit.eyebrow":"BEÁLLÍTÁSOK ÉS ADMINISZTRÁCIÓ","audit.title":"Audit és rendszeresemény-napló","audit.description":"Pénzügyi, HR-, készlet-, CRM-, jogosultsági és adminisztratív változások egységes, visszakereshető története.","audit.today":"Mai események","audit.last7":"Utolsó 7 nap","audit.finance":"Pénzügy","audit.inventory":"Raktár","audit.hr":"HR","audit.admin":"Admin","audit.deletes":"Törlések / inaktiválások","audit.search":"Keresés felhasználó, objektum vagy azonosító alapján…","audit.module":"Minden modul","audit.action":"Minden művelet","audit.empty":"Nincs a feltételeknek megfelelő auditbejegyzés.","audit.export":"CSV export",
 "recycle.eyebrow":"BEÁLLÍTÁSOK ÉS ADMINISZTRÁCIÓ","recycle.title":"Lomtár és visszaállítás","recycle.description":"Inaktivált üzleti törzsadatok központi, auditált kezelése fizikai adattörlés nélkül.","recycle.entity":"Minden adattípus","recycle.search":"Keresés név, kód, e-mail vagy törlési indok alapján…","recycle.deleted_at":"Lomtárba helyezve","recycle.deleted_by":"Módosította","recycle.reason":"Indok","recycle.empty":"A kiválasztott feltételekkel nincs visszaállítható rekord.","recycle.confirm":"Biztosan visszaállítod ezt a rekordot?","recycle.restored":"A rekord sikeresen visszaállt.","recycle.load_error":"A lomtár nem tölthető be.","recycle.restore_error":"A visszaállítás nem sikerült."
};

const EN:Dictionary={
 "language.hu":"Magyar","language.en":"English",
 "common.search":"Search","common.filter":"Filter","common.reset":"Reset","common.refresh":"Refresh","common.loading":"Loading…","common.details":"Details","common.all":"All","common.results":"results","common.restore":"Restore","common.archive":"Move to recycle bin","common.cancel":"Cancel","common.reason":"Reason","common.close":"Close","common.save":"Save","common.saving":"Saving…","common.active":"Active","common.inactive":"Inactive","common.edit":"Edit","common.choose":"Choose","common.none":"Not specified","common.export":"Export",
 "shell.dashboard":"Dashboard","shell.finance":"Finance","shell.inventory":"Inventory","shell.services":"Services","shell.products":"Products","shell.notifications":"Notification center","shell.permissions":"Permissions and access","shell.audit":"Audit and system event log","shell.chat":"Staff chat supervision","shell.location":"Location","shell.all_locations":"All locations","shell.quick_search":"Quick search…","shell.logout":"Sign out","shell.vir":"Kleoszalon ERP","shell.staff":"Kleoszalon staff workspace","shell.language":"Language",
 "login.title":"Kleoszalon Sign in","login.tagline":"A modern beauty salon network with premium services, transparent booking and professional staff – managed in one workspace.","login.subtitle":"One sign-in for customers, staff and administrators. The system automatically applies the appropriate role and location.","login.identifier":"Email or username","login.identifier_placeholder":"Email address or username","login.password":"Password","login.submit":"Sign in","login.loading":"Signing in…","login.forgot":"Forgot password?","login.register_intro":"New customer?","login.register":"Customer registration","login.idle":"For security, you were automatically signed out after 5 minutes of inactivity. Sign in again to continue.","login.required":"Enter your email address or username and password.","login.unexpected":"An unexpected error occurred while signing in.","login.persist_error":"The sign-in data could not be saved.","login.show_password":"Show password","login.hide_password":"Hide password",
 "staff.eyebrow":"TEAM & HR","staff.title":"Staff list","staff.description":"Staff master data grouped by position, including HR and compensation data.","staff.positions_title":"Positions","staff.positions_description":"Positions and base compensation parameters.","staff.add":"Add","staff.active_count":"Active staff","staff.position_groups":"Position groups","staff.location_count":"Locations in use","staff.monthly_total":"Total monthly base pay","staff.search":"Search by name, email, phone, position or location…","staff.position":"Position","staff.all_positions":"All","staff.location":"Location","staff.all_locations":"All locations","staff.employment_type":"Employment type","staff.monthly_wage":"Monthly base pay","staff.hourly_wage":"Hourly rate","staff.commission":"Commission","staff.status":"Status","staff.include_inactive":"Include inactive","staff.found":"Results","staff.empty":"No staff member matches the selected filters.","staff.expand":"Expand","staff.collapse":"Collapse","staff.professional":"Professional","staff.no_qualification":"No qualification specified","staff.no_location":"No location","staff.new_title":"New staff member","staff.edit_title":"Edit staff member","staff.modal_description":"Personal, employment and compensation details.","staff.full_name":"Full name *","staff.email":"Email","staff.phone":"Phone","staff.qualification":"Qualification","staff.active_employee":"Active staff member","staff.saved":"Staff details updated.","staff.created":"New staff member created.","staff.base_monthly":"Base monthly pay","staff.no_description":"No description provided.","staff.people":"people",
 "crm.eyebrow":"CUSTOMERS & CRM","crm.description":"Unified customer data, treatment history and personalized communication.","crm.tab.list":"Customer master","crm.tab.profiles":"Profiles & history","crm.tab.forms":"Questionnaires & consents","crm.tab.segments":"Tags & segments","crm.tab.import":"Import & duplicates","crm.new_customer":"New customer","crm.import_altegio":"Altegio XLSX import","crm.importing":"Importing Altegio data…","crm.total":"Total customers","crm.active_guest":"Active customers","crm.new_this_month":"New this month","crm.with_no_show":"With no-show","crm.search":"Search by name, phone, city, address or tag…","crm.all_status":"All statuses","crm.all_tags":"All tags","crm.customer":"Customer","crm.contact":"Contact","crm.activity":"Activity","crm.no_match":"No customer matches the selected filters.","crm.no_tag":"No tag","crm.no_email":"No email","crm.visits":"visits","crm.last":"Last","crm.no_show":"no-show","crm.segments_title":"Tags and customer segments","crm.segments_desc":"Tags can be assigned immediately on customer profiles.","crm.new_tag":"New tag","crm.assigned":"assigned customers","crm.forms_title":"Questionnaires and consents","crm.forms_desc":"Health questionnaires and data-processing consents.","crm.new_template":"New template","crm.questionnaire":"QUESTIONNAIRE","crm.consent":"CONSENT","crm.no_description":"No description.","crm.completions":"completions","crm.import_title":"Altegio customer import","crm.import_desc":"Upload the XLSX customer file exported from Altegio. Categories become customer tags and existing customers are updated by phone number or email.","crm.import_select":"Select Altegio XLSX","crm.duplicates":"Possible duplicates","crm.duplicates_desc":"Based on matching email address or phone number.","crm.no_duplicates":"No records requiring merge were found.","crm.saved":"Customer details saved.","crm.created":"New customer created.","crm.note_saved":"Note saved.","crm.tag_created":"New tag created.","crm.template_created":"Document template created.",
 "audit.eyebrow":"SETTINGS AND ADMINISTRATION","audit.title":"Audit and system event log","audit.description":"A unified, searchable history of finance, HR, inventory, CRM, permissions and administrative changes.","audit.today":"Events today","audit.last7":"Last 7 days","audit.finance":"Finance","audit.inventory":"Inventory","audit.hr":"HR","audit.admin":"Administration","audit.deletes":"Deletes / deactivations","audit.search":"Search by user, object or identifier…","audit.module":"All modules","audit.action":"All actions","audit.empty":"No audit entries match the selected filters.","audit.export":"Export CSV",
 "recycle.eyebrow":"SETTINGS AND ADMINISTRATION","recycle.title":"Recycle bin and restore","recycle.description":"Central, audited management of inactive business master data without physical record deletion.","recycle.entity":"All data types","recycle.search":"Search by name, code, email or deletion reason…","recycle.deleted_at":"Archived at","recycle.deleted_by":"Changed by","recycle.reason":"Reason","recycle.empty":"No restorable records match the selected filters.","recycle.confirm":"Restore this record?","recycle.restored":"The record was restored successfully.","recycle.load_error":"The recycle bin could not be loaded.","recycle.restore_error":"Restore failed."
};

const MENU_EN:Record<string,string>={
 "Irányítópult":"Dashboard","Időpontfoglalás":"Book appointment","Saját munkalapjaim":"My work orders","Saját beosztás":"My schedule","Saját munkalapok":"My work orders","Check listák":"Checklists","Munkatársi chat":"Staff chat","Időpontok és beosztás":"Appointments & schedule","Időpontnaptár":"Appointment calendar","Munkalapok":"Work orders","Munkaidő és beosztás":"Working time & schedule","Jelenlét":"Attendance","Ügyfelek és CRM":"Customers & CRM","Ügyfelek":"Customers","Munkatársak":"Staff","Raktár és készlet":"Inventory","Készlet":"Stock","Termékek":"Products","Beszerzés":"Procurement","Időpontok és jelenlét":"Appointments & attendance","Naptár és időpontok":"Calendar & appointments","Hűség, bérletek és ajándékkártyák":"Loyalty, passes & gift cards","Csapat és HR":"Team & HR","Pénzügyek":"Finance","Pénzügyi áttekintés":"Finance overview","Statisztika és VIR":"Analytics & ERP","Tudásbázis":"Knowledge base","Webshop és értékesítés":"Webshop & sales","Törzsadatok":"Master data","Központi törzsadatok":"Central master data","Felhasználói csoportok":"User groups","Felhasználók":"Users","Szolgáltatási kategóriák":"Service categories","Szolgáltatások":"Services","Szakember–szolgáltatás beállítások":"Professional–service settings","Terméktípusok":"Product types","Termékcsoportok":"Product groups","Alkategóriák":"Subcategories","Eszköztípusok":"Equipment types","Eszközök":"Equipment","Munkakörök":"Positions","Részlegek":"Departments","Szabadságtípusok":"Leave types","Kedvezménytörzs":"Discount master","Fizetési módok":"Payment methods","ÁFA típusok":"VAT types","Telephelyek":"Locations","Ártípusok":"Price types","Raktárak":"Warehouses","Mértékegységek":"Units","Vendégszámlák":"Guest accounts","Bérletek és ajándékkártyák":"Passes & gift cards","Vendégszámla tranzakció típusok":"Guest account transaction types","Felhasználói mezők":"User fields","Partnerek / Beszállítók":"Partners / Suppliers","Készletmozgás-típusok":"Inventory movement types","Pénzügyi tranzakciótípusok":"Financial transaction types","Beállítások és adminisztráció":"Settings & administration","Jogosultságok":"Permissions","Kijelző admin":"Signage admin","Kijelző kinézet":"Signage appearance","Kiosk admin":"Kiosk admin","Mobil app szerkesztő":"Mobile app editor","NAV Online Számla":"NAV Online Invoice"
};

const dictionaries:Record<Language,Dictionary>={hu:HU,en:EN};
const LanguageContext=createContext<LanguageContextValue>({language:"hu",locale:"hu-HU",setLanguage:()=>undefined,t:(key,fallback)=>fallback||key});

function initialLanguage():Language{
 try{const stored=localStorage.getItem(STORAGE_KEY);if(stored==="hu"||stored==="en")return stored;}catch{}
 return typeof navigator!=="undefined"&&navigator.language?.toLowerCase().startsWith("en")?"en":"hu";
}

export function translateMenuLabel(label:string,language:Language){return language==="en"?(MENU_EN[label]||label):label;}

export function LanguageProvider({children}:{children:React.ReactNode}){
 const[language,setLanguageState]=useState<Language>(initialLanguage);
 const dictionary=useMemo(()=>dictionaries[language],[language]);
 const setLanguage=useCallback((next:Language)=>setLanguageState(next),[]);
 const t=useCallback((key:string,fallback?:string)=>dictionary[key]??fallback??key,[dictionary]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,language)}catch{}document.documentElement.lang=language;},[language]);
 const value=useMemo(()=>({language,locale:language==="en"?"en-GB":"hu-HU",setLanguage,t}),[language,setLanguage,t]);
 return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(){return useContext(LanguageContext);}
