import React,{useCallback,useEffect,useMemo,useState}from"react";
import{Boxes,CheckCircle2,Plus,Sparkles,Trash2,UsersRound,X}from"lucide-react";
import api from"../../api/api";
import{useCurrentUser}from"../../hooks/useCurrentUser";
import"./AdvancedBookingLauncher.css";

type Item={id:string;name?:string|null;full_name?:string|null;title?:string|null;location_id?:string|null;duration_minutes?:number|string|null;base_price?:number|string|null;list_price?:number|string|null;promo_price?:number|string|null};
type BookingResource={id:string;name:string;resource_group:string;resource_type:string;active:boolean;future_allocations?:number};
type Requirement={resource_group:string;quantity:number;note?:string|null};
type ServiceLine={key:string;service_id:string;employee_id:string};
const display=(x?:Item|null)=>x?.full_name||x?.name||x?.title||x?.id||"";
const arr=<T,>(x:any):T[]=>Array.isArray(x)?x:Array.isArray(x?.data)?x.data:Array.isArray(x?.items)?x.items:[];
const roleList=(raw:any)=>{if(Array.isArray(raw))return raw.map(String).map(x=>x.toLowerCase());try{const a=JSON.parse(String(raw||""));if(Array.isArray(a))return a.map(String).map(x=>x.toLowerCase())}catch{}return String(raw||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean)};
const MANAGERS=new Set(["admin","administrator","rendszergazda","superadmin","super_admin","location_manager","salon_manager","szalonvezető","szalonvezeto","üzletvezető","uzletvezeto","store_manager","branch_manager"]);
const errorText=(e:any)=>String(e?.response?.data?.error||e?.response?.data?.message||e?.message||"A művelet nem sikerült.");
const localDate=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const newKey=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export default function AdvancedBookingLauncher(){
 const{user}=useCurrentUser() as any;
 const[open,setOpen]=useState(false),[tab,setTab]=useState<"booking"|"resources">("booking"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[locations,setLocations]=useState<Item[]>([]),[employees,setEmployees]=useState<Item[]>([]),[clients,setClients]=useState<Item[]>([]),[services,setServices]=useState<Item[]>([]),[resources,setResources]=useState<BookingResource[]>([]);
 const[locationId,setLocationId]=useState(String(user?.location_id||"")),[clientId,setClientId]=useState(""),[date,setDate]=useState(localDate()),[time,setTime]=useState("09:00"),[mode,setMode]=useState<"sequential"|"parallel">("parallel"),[notes,setNotes]=useState("");
 const[lines,setLines]=useState<ServiceLine[]>([{key:newKey(),service_id:"",employee_id:""},{key:newKey(),service_id:"",employee_id:""}]);
 const[requirements,setRequirements]=useState<Record<string,Requirement[]>>({}),[preferred,setPreferred]=useState<Record<string,string>>({}),[plan,setPlan]=useState<any>(null);
 const[resourceName,setResourceName]=useState(""),[resourceGroup,setResourceGroup]=useState(""),[resourceType,setResourceType]=useState("room");
 const[configService,setConfigService]=useState(""),[configRequirements,setConfigRequirements]=useState<Requirement[]>([]);
 const canManage=useMemo(()=>roleList(user?.role).some(x=>MANAGERS.has(x)),[user?.role]);
 const prefix="/transactions/booking-operations/advanced";
 const employeesAtLocation=useMemo(()=>employees.filter(e=>!locationId||!e.location_id||String(e.location_id)===locationId),[employees,locationId]);
 const activeLines=useMemo(()=>lines.filter(x=>x.service_id&&x.employee_id),[lines]);

 const loadResources=useCallback(async(loc:string)=>{if(!loc)return setResources([]);try{const r=await api.get("/transactions/booking-operations/advanced/resources",{params:{location_id:loc}});setResources(arr<BookingResource>(r.data))}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{if(!open)return;setError("");void Promise.all([api.get("/locations"),api.get("/employees"),api.get("/clients"),api.get("/services")]).then(([l,e,c,s])=>{setLocations(arr<Item>(l.data));setEmployees(arr<Item>(e.data));setClients(arr<Item>(c.data));setServices(arr<Item>(s.data));const initial=String(user?.location_id||arr<Item>(l.data)[0]?.id||"");setLocationId(x=>x||initial);if(initial)void loadResources(initial)}).catch(e=>setError(errorText(e)))},[open,user?.location_id,loadResources]);
 useEffect(()=>{if(open&&locationId)void loadResources(locationId)},[locationId,open,loadResources]);
 useEffect(()=>{if(!open)return;const ids=[...new Set(lines.map(x=>x.service_id).filter(Boolean))];for(const id of ids)if(requirements[id]===undefined)void api.get(`${prefix}/service-resources/${id}`).then(r=>setRequirements(cur=>({...cur,[id]:arr<Requirement>(r.data)}))).catch(()=>setRequirements(cur=>({...cur,[id]:[]})))},[lines,open,requirements]);
 useEffect(()=>{setPlan(null)},[locationId,clientId,date,time,mode,lines,preferred]);

 const payload=()=>({location_id:locationId,client_id:clientId,start_time:new Date(`${date}T${time}:00`).toISOString(),booking_mode:mode,notes,services:activeLines.map(line=>({service_id:line.service_id,employee_id:line.employee_id,resource_ids:Object.entries(preferred).filter(([key])=>key.startsWith(`${line.key}|`)).map(([,id])=>id).filter(Boolean)}))});
 const check=async()=>{if(!locationId||!date||!time||!activeLines.length){setError("Telephely, időpont és legalább egy teljes szolgáltatás/munkatárs sor kötelező.");return}setBusy(true);setError("");try{const r=await api.post(`${prefix}/availability`,payload());setPlan(r.data)}catch(e:any){setPlan(e?.response?.data||null);setError(errorText(e))}finally{setBusy(false)}};
 const createBooking=async()=>{if(!clientId){setError("Válasszon vendéget.");return}setBusy(true);setError("");try{const r=await api.post(`${prefix}/appointments`,payload());setPlan(r.data);setOpen(false);window.location.reload()}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const addLine=()=>setLines(cur=>[...cur,{key:newKey(),service_id:"",employee_id:""}]);
 const patchLine=(key:string,patch:Partial<ServiceLine>)=>setLines(cur=>cur.map(x=>x.key===key?{...x,...patch}:x));
 const removeLine=(key:string)=>setLines(cur=>cur.length<=1?cur:cur.filter(x=>x.key!==key));
 const resourcesFor=(group:string)=>resources.filter(r=>r.active&&r.resource_group===group);

 const createResource=async()=>{if(!resourceName.trim()||!resourceGroup.trim()){setError("Az erőforrás neve és csoportja kötelező.");return}setBusy(true);try{await api.post(`${prefix}/resources`,{location_id:locationId,name:resourceName,resource_group:resourceGroup,resource_type:resourceType});setResourceName("");await loadResources(locationId)}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const loadConfig=async(serviceId:string)=>{setConfigService(serviceId);if(!serviceId)return setConfigRequirements([]);try{const r=await api.get(`${prefix}/service-resources/${serviceId}`);setConfigRequirements(arr<Requirement>(r.data).map(x=>({...x,quantity:Number(x.quantity||1)})))}catch(e){setError(errorText(e))}};
 const saveConfig=async()=>{if(!configService)return;setBusy(true);try{const r=await api.put(`${prefix}/service-resources/${configService}`,{requirements:configRequirements});const next=arr<Requirement>(r.data?.requirements);setConfigRequirements(next);setRequirements(cur=>({...cur,[configService]:next}));setError("")}catch(e){setError(errorText(e))}finally{setBusy(false)}};

 return<>
  <button className="advanced-booking-launcher" onClick={()=>setOpen(true)} title="Több szakemberes és erőforrásos foglalás"><UsersRound size={18}/><span>4Hands / erőforrás</span></button>
  {open&&<div className="advanced-booking-overlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="advanced-booking-modal" role="dialog" aria-modal="true">
   <header><div><span><Sparkles size={15}/> ALTEGIO-PARITÁS</span><h2>4Hands és erőforrás-foglalás</h2><p>Több szakember, kezelőhelyiség és eszköz egyetlen ütközésvizsgálattal.</p></div><button onClick={()=>setOpen(false)} aria-label="Bezárás"><X/></button></header>
   <nav><button className={tab==="booking"?"active":""} onClick={()=>setTab("booking")}><UsersRound size={16}/> Foglalás</button>{canManage&&<button className={tab==="resources"?"active":""} onClick={()=>setTab("resources")}><Boxes size={16}/> Erőforrások</button>}</nav>
   {error&&<div className="advanced-booking-error">{error}</div>}
   {tab==="booking"?<div className="advanced-booking-body">
    <div className="advanced-grid four"><label>Telephely<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Válasszon</option>{locations.map(x=><option key={x.id} value={x.id}>{display(x)}</option>)}</select></label><label>Vendég<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Válasszon vendéget</option>{clients.map(x=><option key={x.id} value={x.id}>{display(x)}</option>)}</select></label><label>Dátum<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Kezdés<input type="time" step={900} value={time} onChange={e=>setTime(e.target.value)}/></label></div>
    <div className="advanced-mode"><button className={mode==="sequential"?"active":""} onClick={()=>setMode("sequential")}><b>Szekvenciális</b><small>Szolgáltatások egymás után</small></button><button className={mode==="parallel"?"active":""} onClick={()=>setMode("parallel")}><b>4Hands / párhuzamos</b><small>Több szakember egyszerre</small></button></div>
    <div className="advanced-lines"><div className="advanced-lines-title"><div><b>Szolgáltatások és szakemberek</b><small>A 4Hands módban minden sor ugyanakkor indul.</small></div><button onClick={addLine}><Plus size={15}/> Sor hozzáadása</button></div>{lines.map((line,index)=>{const reqs=requirements[line.service_id]||[];return<article key={line.key}><span className="line-index">{index+1}</span><label>Szolgáltatás<select value={line.service_id} onChange={e=>patchLine(line.key,{service_id:e.target.value})}><option value="">Válasszon</option>{services.map(x=><option key={x.id} value={x.id}>{display(x)} · {Number(x.duration_minutes||30)} perc</option>)}</select></label><label>Szakember<select value={line.employee_id} onChange={e=>patchLine(line.key,{employee_id:e.target.value})}><option value="">Válasszon</option>{employeesAtLocation.map(x=><option key={x.id} value={x.id}>{display(x)}</option>)}</select></label><button className="line-trash" onClick={()=>removeLine(line.key)} aria-label="Sor törlése"><Trash2 size={16}/></button>{reqs.length>0&&<div className="resource-requirements"><strong><Boxes size={14}/> Kötelező erőforrás</strong>{reqs.map(req=><label key={req.resource_group}>{req.resource_group} × {req.quantity}<select value={preferred[`${line.key}|${req.resource_group}`]||""} onChange={e=>setPreferred(cur=>({...cur,[`${line.key}|${req.resource_group}`]:e.target.value}))}><option value="">Automatikus kiosztás</option>{resourcesFor(req.resource_group).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>)}</div>}</article>})}</div>
    <label>Megjegyzés<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Belső megjegyzés..."/></label>
    {plan&&<div className={`advanced-plan ${plan.ok?"ok":"bad"}`}><div>{plan.ok?<CheckCircle2/>:<X/>}<div><b>{plan.ok?"Foglalható":"Ütközés található"}</b><small>{plan.duration_minutes?`${plan.duration_minutes} perc · ${plan.services?.length||0} szolgáltatás`:"Módosítsa a kijelölt erőforrásokat vagy időpontot."}</small></div></div>{Array.isArray(plan.conflicts)&&plan.conflicts.map((c:any,i:number)=><p key={i}>{c.message}</p>)}{Array.isArray(plan.resource_allocations)&&plan.resource_allocations.length>0&&<p>{plan.resource_allocations.length} erőforrás automatikusan lefoglalható.</p>}</div>}
    <footer><button onClick={()=>setOpen(false)}>Mégse</button><button onClick={check} disabled={busy}>Ütközésvizsgálat</button><button className="primary" onClick={createBooking} disabled={busy||!plan?.ok||!clientId}>{busy?"Feldolgozás…":"4Hands foglalás létrehozása"}</button></footer>
   </div>:<div className="advanced-booking-body resources-tab">
    <section><h3>Szalon erőforrásai</h3><p>Kezelőhelyiség, szék, gép vagy bármely egyszerre csak egy foglaláshoz használható eszköz.</p><div className="advanced-grid four"><label>Név<input value={resourceName} onChange={e=>setResourceName(e.target.value)} placeholder="pl. Lézer 1"/></label><label>Csoport<input value={resourceGroup} onChange={e=>setResourceGroup(e.target.value)} placeholder="pl. lezer"/></label><label>Típus<select value={resourceType} onChange={e=>setResourceType(e.target.value)}><option value="room">Helyiség</option><option value="device">Gép / eszköz</option><option value="chair">Szék / ágy</option><option value="table">Asztal</option><option value="other">Egyéb</option></select></label><button className="resource-create" onClick={createResource} disabled={busy}><Plus size={15}/> Létrehozás</button></div><div className="resource-list">{resources.map(r=><article key={r.id}><Boxes size={18}/><div><b>{r.name}</b><small>{r.resource_group} · {r.resource_type} · jövőbeni foglalások: {r.future_allocations||0}</small></div><span className={r.active?"active":"inactive"}>{r.active?"Aktív":"Inaktív"}</span></article>)}</div></section>
    <section><h3>Szolgáltatás erőforrásigénye</h3><p>Állítsa be, hogy a szolgáltatás mely erőforráscsoportból hány darabot igényel.</p><label>Szolgáltatás<select value={configService} onChange={e=>void loadConfig(e.target.value)}><option value="">Válasszon</option>{services.map(x=><option key={x.id} value={x.id}>{display(x)}</option>)}</select></label>{configService&&<div className="requirement-editor">{configRequirements.map((r,i)=><div key={i}><input value={r.resource_group} onChange={e=>setConfigRequirements(cur=>cur.map((x,j)=>j===i?{...x,resource_group:e.target.value}:x))} placeholder="csoport"/><input type="number" min={1} max={20} value={r.quantity} onChange={e=>setConfigRequirements(cur=>cur.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/><button onClick={()=>setConfigRequirements(cur=>cur.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}<button onClick={()=>setConfigRequirements(cur=>[...cur,{resource_group:"",quantity:1}])}><Plus size={15}/> Igény hozzáadása</button><button className="primary" onClick={saveConfig} disabled={busy}>Erőforrásigény mentése</button></div>}</section>
   </div>}
  </section></div>}
 </>;
}
