import React,{useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,BellRing,Mail,MessageSquareText,Play,RefreshCw,Save,ShieldAlert}from"lucide-react";
import api from"../../api/api";
import"./BookingNotificationAutomation.css";

type Location={id:string;name:string};
type Settings={email_channel_enabled:boolean;sms_channel_enabled:boolean;confirmation_enabled:boolean;reminder_48h_enabled:boolean;reminder_24h_enabled:boolean;cancellation_enabled:boolean;waitlist_enabled:boolean;review_request_enabled:boolean;review_delay_hours:number};
type BoolSettingKey=Exclude<keyof Settings,"review_delay_hours">;
type QueueItem={id:string;channel:string;event_type:string;recipient:string;subject:string;status:string;scheduled_at:string;sent_at?:string|null;client_name?:string|null;location_name?:string|null};
type FailureCause={key:string;label:string;priority:"high"|"medium"|"low";recommended_action:string;count:number;percentage:number};
type FailureCount={key:string;count:number};
type FailureAnalysis={generated_at:string;total_failed:number;failed_last_24h:number;failed_last_7d:number;stale_older_than_7d:number;missing_error_text:number;oldest_failed_at?:string|null;newest_failed_at?:string|null;duplicate_candidates:number;provider_status:{email:{enabled:boolean;configured:boolean};sms:{enabled:boolean;configured:boolean;token_configured:boolean}};causes:FailureCause[];channels:FailureCount[];events:FailureCount[];locations:{location_id:string|null;label:string;count:number}[];top_errors:{message:string;count:number;percentage:number}[];safety:{bulk_requeue_allowed:boolean;message:string}};
const defaults:Settings={email_channel_enabled:true,sms_channel_enabled:false,confirmation_enabled:true,reminder_48h_enabled:true,reminder_24h_enabled:true,cancellation_enabled:true,waitlist_enabled:true,review_request_enabled:true,review_delay_hours:24};
const labels:Record<string,string>={booking_created:"Foglalási igény",booking_confirmed:"Visszaigazolás",booking_rescheduled:"Időpont-módosítás",booking_cancelled:"Lemondás",reminder_48h:"48 órás emlékeztető",reminder_24h:"24 órás emlékeztető",review_request:"Értékeléskérés"};
const channelLabel=(value:string)=>value==="email"?"E-mail":value==="sms"?"SMS":value;

export default function BookingNotificationAutomation({toast}:{toast?:(message:string)=>void}){
 const[locations,setLocations]=useState<Location[]>([]),[locationId,setLocationId]=useState("");
 const[settings,setSettings]=useState<Settings>(defaults),[queue,setQueue]=useState<QueueItem[]>([]);
 const[failureAnalysis,setFailureAnalysis]=useState<FailureAnalysis|null>(null),[analysisLoading,setAnalysisLoading]=useState(false),[analysisError,setAnalysisError]=useState("");
 const[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const loadLocations=async()=>{try{const r=await api.get("/locations");const rows=Array.isArray(r.data)?r.data:Array.isArray(r.data?.data)?r.data.data:[];setLocations(rows);setLocationId(v=>v||String(rows[0]?.id||localStorage.getItem("kleo_location_id")||""))}catch(e:any){setError(e?.response?.data?.error||e.message||"A telephelyek nem tölthetők be.")}};
 const loadFailureAnalysis=async()=>{setAnalysisLoading(true);setAnalysisError("");try{const r=await api.get("/transactions/booking-communications/failure-analysis",{params:{scope:"all"}});setFailureAnalysis(r.data||null)}catch(e:any){if(Number(e?.response?.status)===403)setFailureAnalysis(null);else setAnalysisError(e?.response?.data?.error||e.message||"A sikertelen értesítések elemzése nem tölthető be.")}finally{setAnalysisLoading(false)}};
 const load=useCallback(async()=>{if(!locationId)return;setLoading(true);setError("");try{const[s,q]=await Promise.all([api.get("/transactions/booking-communications/settings",{params:{location_id:locationId}}),api.get("/transactions/booking-communications/queue",{params:{location_id:locationId}})]);setSettings({...defaults,...(s.data||{})});setQueue(Array.isArray(q.data)?q.data:[])}catch(e:any){setError(e?.response?.data?.error||e.message||"Az értesítési automatizmusok nem tölthetők be.")}finally{setLoading(false)}},[locationId]);
 useEffect(()=>{void loadLocations();void loadFailureAnalysis()},[]);useEffect(()=>{void load()},[load]);
 const save=async()=>{if(!locationId)return;setSaving(true);setError("");try{await api.put("/transactions/booking-communications/settings",{location_id:locationId,...settings});toast?.("Értesítési szabályok mentve.");await load()}catch(e:any){setError(e?.response?.data?.error||e.message||"A beállítások nem menthetők.")}finally{setSaving(false)}};
 const process=async()=>{setLoading(true);try{const r=await api.post("/transactions/booking-communications/process");toast?.(`${Number(r.data?.processed||0)} üzenet feldolgozva.`);await Promise.all([load(),loadFailureAnalysis()])}catch(e:any){setError(e?.response?.data?.error||e.message||"A kommunikációs sor nem dolgozható fel.")}finally{setLoading(false)}};
 const counts=useMemo(()=>({pending:queue.filter(x=>x.status==="pending").length,sent:queue.filter(x=>x.status==="sent").length,failed:queue.filter(x=>x.status==="failed").length}),[queue]);
 const toggle=(key:BoolSettingKey)=>setSettings(s=>({...s,[key]:!s[key]}));
 const rules:[BoolSettingKey,string,string][]=[
  ["email_channel_enabled","E-mail csatorna","Foglalási üzenetek küldése a vendég e-mail címére."],
  ["sms_channel_enabled","SMS csatorna","SMS küldés a konfigurált SMS gateway-en keresztül, a vendég értesítési preferenciája szerint."],
  ["confirmation_enabled","Foglalás visszaigazolása","Azonnal a foglalás létrehozásakor vagy jóváhagyásakor."],
  ["reminder_48h_enabled","48 órás emlékeztető","Két nappal a vendég időpontja előtt."],
  ["reminder_24h_enabled","24 órás emlékeztető","Egy nappal az időpont előtt."],
  ["cancellation_enabled","Lemondás és áthelyezés","Azonnali tájékoztatás változás esetén."],
  ["waitlist_enabled","Várólista kommunikáció","Felszabaduló helyhez kapcsolódó vendégértesítés előkészítve."],
  ["review_request_enabled","Értékelés kérése","A látogatás teljesítése után automatikusan."],
 ];
 return <div className="booking-comms">
  <header className="booking-comms__toolbar"><div><span>AUTOMATIKUS VENDÉGKOMMUNIKÁCIÓ</span><h2>Foglalási értesítések</h2><p>Visszaigazolás, emlékeztető, lemondás és értékeléskérés e-mail/SMS kommunikációs sorból.</p></div><div><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Válasszon telephelyet</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button onClick={process} disabled={loading}><Play size={15}/> Sor futtatása</button><button className="primary" onClick={save} disabled={saving||!locationId}><Save size={15}/>{saving?"Mentés…":"Mentés"}</button></div></header>
  {error&&<div className="booking-comms__error">{error}</div>}
  {analysisError&&<div className="booking-comms__error">{analysisError}</div>}
  <section className="booking-comms__kpis"><article><BellRing/><b>{counts.pending}</b><span>ütemezve · kiválasztott telephely</span></article><article><Mail/><b>{counts.sent}</b><span>elküldve · legutóbbi 300</span></article><article><RefreshCw/><b>{failureAnalysis?.total_failed??counts.failed}</b><span>{failureAnalysis?"hibás · teljes rendszer":"hibás · legutóbbi 300"}</span></article></section>
  {analysisLoading&&!failureAnalysis?<section className="booking-comms__analysis"><p className="booking-comms__empty">Sikertelen értesítések ok szerinti elemzése…</p></section>:failureAnalysis&&<section className="booking-comms__analysis">
    <header><div><span>RENDSZERSZINTŰ ANOMÁLIAELEMZÉS</span><h3><ShieldAlert size={18}/> {failureAnalysis.total_failed} sikertelen foglalási értesítés</h3><p>Az összes telephely teljes hibás állománya, nem csak a kommunikációs sor legutóbbi 300 tétele.</p></div><button onClick={loadFailureAnalysis} disabled={analysisLoading}><RefreshCw size={14}/>{analysisLoading?"Elemzés…":"Okok újraelemzése"}</button></header>
    <div className="booking-comms__analysis-kpis"><article><b>{failureAnalysis.failed_last_24h}</b><span>új hiba · 24 óra</span></article><article><b>{failureAnalysis.failed_last_7d}</b><span>új hiba · 7 nap</span></article><article><b>{failureAnalysis.stale_older_than_7d}</b><span>7 napnál régebbi</span></article><article><b>{failureAnalysis.duplicate_candidates}</b><span>≤10 mp duplikációjelölt</span></article></div>
    <div className="booking-comms__provider-state"><span className={failureAnalysis.provider_status.email.enabled&&failureAnalysis.provider_status.email.configured?"ok":"bad"}><Mail size={13}/> E-mail: {failureAnalysis.provider_status.email.enabled?(failureAnalysis.provider_status.email.configured?"konfigurálva":"hiányos konfiguráció"):"letiltva"}</span><span className={!failureAnalysis.provider_status.sms.enabled||failureAnalysis.provider_status.sms.configured?"ok":"bad"}><MessageSquareText size={13}/> SMS: {failureAnalysis.provider_status.sms.enabled?(failureAnalysis.provider_status.sms.configured?"konfigurálva":"hiányos konfiguráció"):"letiltva"}</span></div>
    <div className="booking-comms__analysis-grid"><div><h4>Hibaokok</h4>{failureAnalysis.causes.length?failureAnalysis.causes.map(c=><article className={`booking-comms__cause priority-${c.priority}`} key={c.key}><div><b>{c.label}</b><span>{c.count} db · {c.percentage}%</span></div><div className="booking-comms__cause-bar"><i style={{width:`${Math.min(100,c.percentage)}%`}}/></div><small>{c.recommended_action}</small></article>):<p className="booking-comms__empty">Nincs sikertelen értesítés.</p>}</div>
      <div><h4>Csatorna / esemény</h4><div className="booking-comms__breakdown">{failureAnalysis.channels.map(x=><span key={x.key}><b>{channelLabel(x.key)}</b>{x.count} db</span>)}</div><div className="booking-comms__breakdown">{failureAnalysis.events.slice(0,7).map(x=><span key={x.key}><b>{labels[x.key]||x.key}</b>{x.count} db</span>)}</div><h4>Leggyakoribb nyers hibaminták</h4><div className="booking-comms__error-patterns">{failureAnalysis.top_errors.slice(0,6).map((x,i)=><span key={`${i}-${x.message}`}><b>{x.count} db · {x.percentage}%</b><small>{x.message}</small></span>)}</div></div>
    </div>
    <div className="booking-comms__safety"><AlertTriangle size={16}/><span><b>Nincs automatikus tömeges újraküldés.</b> {failureAnalysis.safety.message}</span></div>
    <footer>Elemzés frissítve: {new Date(failureAnalysis.generated_at).toLocaleString("hu-HU")}{failureAnalysis.oldest_failed_at?` · legrégebbi hiba: ${new Date(failureAnalysis.oldest_failed_at).toLocaleString("hu-HU")}`:""}</footer>
  </section>}
  <div className="booking-comms__grid"><section className="booking-comms__rules"><h3>Csatornák és automatikus szabályok</h3>{rules.map(([key,title,detail])=><div className="booking-comms__rule" key={String(key)}><span><b>{title}</b><small>{detail}</small></span><button className={settings[key]?"on":""} onClick={()=>toggle(key)}><i/></button></div>)}<label className="booking-comms__delay"><span>Értékeléskérés késleltetése</span><input type="number" min={0} max={168} value={settings.review_delay_hours} onChange={e=>setSettings(s=>({...s,review_delay_hours:Number(e.target.value||0)}))}/><em>óra</em></label></section>
  <section className="booking-comms__queue"><header><div><h3>Kommunikációs sor</h3><p>A legutóbbi 300 esemény, e-mail és SMS csatornával.</p></div><button onClick={load}><RefreshCw size={14}/> Frissítés</button></header>{loading&&!queue.length?<p className="booking-comms__empty">Betöltés…</p>:queue.length?queue.slice(0,80).map(item=><article key={item.id}><span className={`status-${item.status}`}>{item.status}</span><div><b>{item.channel==="sms"?<MessageSquareText size={12}/>:<Mail size={12}/>} {labels[item.event_type]||item.event_type}</b><small>{item.client_name||item.recipient} · {item.recipient}</small></div><time>{new Date(item.scheduled_at).toLocaleString("hu-HU")}</time></article>):<p className="booking-comms__empty">Még nincs kommunikációs esemény.</p>}</section></div>
 </div>;
}
