import React,{useEffect,useState}from"react";
import{Link}from"react-router-dom";
import{apiFetch}from"../../utils/api";

type Readiness={ready?:boolean;active_employees?:number;missing_contract?:number;missing_compensation?:number;unapproved_timesheets?:number;approved_timesheets?:number;approved_overtime_minutes?:number;pending_leave?:number;approved_paid_leave?:number;open_commissions?:number;included_commissions?:number;paid_commissions?:number;open_commission_base?:number|string;open_tips?:number|string;from?:string;to?:string};
const today=()=>new Date().toISOString().slice(0,10);const monthStart=()=>today().slice(0,8)+"01";
const huf=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const hrs=(v:any)=>`${(Number(v||0)/60).toLocaleString("hu-HU",{maximumFractionDigits:1})} ó`;
export default function HrPayrollReadinessPanel(){const[data,setData]=useState<Readiness|null>(null),[error,setError]=useState("");async function load(){setError("");try{setData(await apiFetch<Readiness>(`/api/payroll/readiness?from=${monthStart()}&to=${today()}`))}catch(e:any){setError(e?.message||"A HR számfejtési kontroll nem tölthető be.")}}useEffect(()=>{void load()},[]);if(error)return null;if(!data)return <section style={box}><div style={{padding:16}}>HR számfejtési kontroll betöltése…</div></section>;
 const blockers=Number(data.missing_contract||0)+Number(data.missing_compensation||0)+Number(data.unapproved_timesheets||0)+Number(data.pending_leave||0);
 return <section style={box}><div style={head}><div><div style={eyebrow}>HR / SZÁMFEJTÉSI KÉSZÜLTSÉG</div><h2 style={{margin:"4px 0 2px",fontSize:18}}>Havi HR és bérkontroll</h2><div style={{fontSize:12,color:"#74695f"}}>{data.from} – {data.to}</div></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span style={{...badge,background:data.ready?"#edf8f0":"#fff4e5",color:data.ready?"#1c6b39":"#9a5a00"}}>{data.ready?"Számfejtésre kész":`${blockers} kontrollpont nyitott`}</span><Link to="/modules/team/payroll" style={link}>Bérszámfejtés</Link><Link to="/modules/team/attendance" style={link}>Jelenlét</Link></div></div>
 <div style={grid}><Metric label="Aktív munkatárs" value={data.active_employees||0}/><Metric label="Hiányzó szerződés" value={data.missing_contract||0} warn/><Metric label="Hiányzó bércsomag" value={data.missing_compensation||0} warn/><Metric label="Jóváhagyatlan jelenlét" value={data.unapproved_timesheets||0} warn/><Metric label="Függő szabadság" value={data.pending_leave||0} warn/><Metric label="Jóváhagyott túlóra" value={hrs(data.approved_overtime_minutes)}/><Metric label="Nyitott jutalék" value={data.open_commissions||0}/><Metric label="Jutalékalap" value={huf(data.open_commission_base)}/><Metric label="Borravaló" value={huf(data.open_tips)}/></div></section>}
function Metric({label,value,warn}:{label:string;value:string|number;warn?:boolean}){const active=warn&&Number(value||0)>0;return <div style={{border:"1px solid #eee7df",borderRadius:12,padding:"10px 12px",background:active?"#fff8ed":"#fff"}}><div style={{fontSize:10,color:"#74695f",fontWeight:800,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:19,fontWeight:900,marginTop:4,color:active?"#9a5a00":"#2b2118"}}>{value}</div></div>}
const box:React.CSSProperties={margin:"0 24px 18px",border:"1px solid #e7e0d6",borderRadius:18,background:"#fff",overflow:"hidden"};const head:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,padding:"15px 18px",borderBottom:"1px solid #eee7df",flexWrap:"wrap"};const eyebrow:React.CSSProperties={fontSize:10,fontWeight:900,letterSpacing:.8,color:"#8a735c"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(135px,1fr))",gap:10,padding:14};const badge:React.CSSProperties={padding:"7px 10px",borderRadius:999,fontSize:11,fontWeight:900};const link:React.CSSProperties={textDecoration:"none",border:"1px solid #d8cec4",color:"#2b2118",borderRadius:9,padding:"8px 10px",fontSize:11,fontWeight:800};
