import React,{useEffect,useMemo,useState}from'react';
import{ExternalLink,RefreshCw}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{apiFetch}from'../../utils/api';

type Filter='all'|'new'|'open'|'completed'|'cancelled';
const statusHu=(s:any)=>({waiting:'Új',arrived:'Megérkezett',in_progress:'Folyamatban',completed:'Lezárt',cancelled:'Lemondott',no_show:'Nem jelent meg'}as any)[s]||s||'—';
const group=(x:any):Exclude<Filter,'all'>=>x?.status==='waiting'?'new':['arrived','in_progress'].includes(x?.status)?'open':x?.status==='completed'?'completed':'cancelled';

export default function WorkOrderDashboardWidget(){
 const nav=useNavigate();const[items,setItems]=useState<any[]>([]);const[scope,setScope]=useState<any>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[filter,setFilter]=useState<Filter>('new');
 async function load(){setLoading(true);setError('');try{const[list,summary]=await Promise.all([apiFetch<any[]>('/api/workorders'),apiFetch<any>('/api/workorders/dashboard/summary')]);setItems(Array.isArray(list)?list:[]);setScope(summary?.scope||null)}catch(e:any){setError(e?.message||'A munkalapok nem tölthetők be.')}finally{setLoading(false)}}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15000);const onFocus=()=>void load();window.addEventListener('focus',onFocus);return()=>{window.clearInterval(t);window.removeEventListener('focus',onFocus)}},[]);
 const counts=useMemo(()=>({all:items.length,new:items.filter(x=>group(x)==='new').length,open:items.filter(x=>group(x)==='open').length,completed:items.filter(x=>group(x)==='completed').length,cancelled:items.filter(x=>group(x)==='cancelled').length}),[items]);
 const visible=useMemo(()=>items.filter(x=>filter==='all'||group(x)===filter).slice(0,10),[items,filter]);
 const scopeText=scope?.kind==='all'?'Összes szalon':scope?.kind==='location'?'Saját szalon':scope?.kind==='employee'?'Saját munkalapok':'Saját ügyfélmunkalapok';
 return <section style={card}>
  <header style={head}><div><span style={kicker}>MUNKALAPOK · ÉLŐ</span><h2 style={{margin:'3px 0'}}>Munkalap állapot</h2><p style={muted}>{scopeText}. Az új időpontok, online foglalások és kiosk rendelések is itt jelennek meg.</p></div><div style={{display:'flex',gap:8}}><button onClick={()=>void load()} style={iconButton} aria-label="Munkalapok frissítése"><RefreshCw size={16} className={loading?'spin':''}/></button><button onClick={()=>nav('/workorders')} style={button}>Munkalapok <ExternalLink size={14}/></button></div></header>
  <div style={tabs}>{([['new','Új',counts.new],['open','Folyamatban',counts.open],['completed','Lezárt',counts.completed],['cancelled','Lemondott / no-show',counts.cancelled],['all','Összes',counts.all]]as any[]).map(([key,label,count])=><button key={key} onClick={()=>setFilter(key)} style={filter===key?activeTab:tab}><span>{label}</span><b>{count}</b></button>)}</div>
  {error?<div style={{padding:12,color:'#b42318'}}>{error}</div>:<div style={{marginTop:12}}>{visible.length?visible.map((x:any)=><button key={x.id} onClick={()=>nav(`/workorders/${x.id}`)} style={row}><span><b>{x.work_order_number||x.id}</b><small style={muted}>{x.location_name||'—'} · {x.client_name||'Vendég'} · {x.employee_name||'Nincs kiosztva'}</small></span><span style={{fontWeight:850,color:x.status==='waiting'?'#a15c00':x.status==='in_progress'?'#9b1765':'#475467'}}>{statusHu(x.status)}</span></button>):<div style={{padding:16,color:'#667085'}}>Ebben a csoportban nincs munkalap.</div>}</div>}
 </section>
}
const card:React.CSSProperties={background:'#fff',borderRadius:16,padding:18,boxShadow:'0 8px 24px rgba(48,36,25,.08)',margin:'16px 0'};const head:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center'};const kicker:React.CSSProperties={fontSize:11,letterSpacing:1.4,fontWeight:900,color:'#8a6d55'};const muted:React.CSSProperties={fontSize:12,color:'#74675d',margin:0,display:'block'};const tabs:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:8,marginTop:16};const tab:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'center',padding:'11px 13px',border:'1px solid #eadfd4',borderRadius:11,background:'#fff',color:'#574b40',fontWeight:800,cursor:'pointer'};const activeTab:React.CSSProperties={...tab,background:'#2b2118',color:'#fff',borderColor:'#2b2118'};const button:React.CSSProperties={display:'flex',alignItems:'center',gap:6,border:0,borderRadius:9,padding:'9px 12px',background:'#2b2118',color:'#fff',fontWeight:800,cursor:'pointer'};const iconButton:React.CSSProperties={...button,padding:'9px',background:'#f3ede6',color:'#2b2118'};const row:React.CSSProperties={width:'100%',display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,textAlign:'left',border:0,borderTop:'1px solid #eee8e2',background:'transparent',padding:'11px 2px',cursor:'pointer'};
