import React,{useEffect,useState}from'react';
import{BadgePercent,Gift,RefreshCw,TicketPercent,WalletCards}from'lucide-react';
import api from'../../api';

type Props={customerId:string};
const money=(v:any)=>`${Number(v||0).toLocaleString('hu-HU',{maximumFractionDigits:0})} Ft`;
const num=(v:any)=>Number(v||0).toLocaleString('hu-HU');
const date=(v:any)=>v?new Date(v).toLocaleDateString('hu-HU'):'—';

export default function ClientLoyaltyPanel({customerId}:Props){
 const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await api.get(`/api/transactions/loyalty-v4/customer/${encodeURIComponent(customerId)}`);setData(r.data)}catch(e:any){setError(e?.response?.data?.message||'A hűségadatok nem tölthetők be.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[customerId]);
 if(loading&&!data)return <section><h3>Hűség és wallet</h3><div className="crm-empty small">Hűségadatok betöltése…</div></section>;
 return <section><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8}}><h3>Hűség és wallet</h3><button type="button" onClick={()=>void load()} title="Hűségadatok frissítése" style={{border:0,background:'transparent',cursor:'pointer'}}><RefreshCw size={15}/></button></div>{error&&<div className="crm-error" style={{margin:'8px 0'}}>{error}</div>}{!data?.account?<div className="crm-empty small">Ehhez a vendéghez még nincs hűség-wallet. A Hűség / Vendég egyenlegek oldalon hozható létre.</div>:<><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8,marginBottom:12}}><Metric icon={<WalletCards size={16}/>} label="Egyenleg" value={money(data.account.balance)}/><Metric icon={<BadgePercent size={16}/>} label="Pont" value={num(data.account.points)}/><Metric icon={<TicketPercent size={16}/>} label="Aktív bérlet" value={num((data.passes||[]).filter((x:any)=>x.status==='active').length)}/><Metric icon={<Gift size={16}/>} label="Utalvány-egyenleg" value={money((data.vouchers||[]).filter((x:any)=>x.status==='active').reduce((s:number,x:any)=>s+Number(x.remaining_value||0),0))}/></div><MiniTable title="Bérletek" empty="Nincs bérlet." rows={(data.passes||[]).slice(0,5).map((x:any)=>[x.pass_type_name,`${(x.balances||[]).reduce((s:number,b:any)=>s+Number(b.remaining_quantity||0),0)} egység`,date(x.valid_until)])}/><MiniTable title="Ajándékutalványok" empty="Nincs utalvány." rows={(data.vouchers||[]).slice(0,5).map((x:any)=>[x.code,money(x.remaining_value),x.status])}/><MiniTable title="Kuponok" empty="Nincs vendéghez rendelt kupon." rows={(data.coupons||[]).slice(0,5).map((x:any)=>[x.code,x.campaign_name,date(x.valid_until)])}/><MiniTable title="Legutóbbi hűségtranzakciók" empty="Nincs hűségtranzakció." rows={(data.transactions||[]).slice(0,8).map((x:any)=>[date(x.created_at),x.transaction_type,Number(x.points||0)!==0?`${num(x.points)} pont`:money(x.amount)])}/></>}</section>
}
function Metric({icon,label,value}:{icon:any,label:string,value:string}){return <div style={{border:'1px solid #eee7dd',borderRadius:10,padding:10,display:'grid',gridTemplateColumns:'20px 1fr',gap:6,alignItems:'center',background:'#fffaf4'}}>{icon}<span style={{fontSize:11,color:'#7a6d62'}}>{label}</span><span/><b>{value}</b></div>}
function MiniTable({title,rows,empty}:{title:string,rows:string[][],empty:string}){return <div style={{marginTop:12}}><b style={{fontSize:12}}>{title}</b>{rows.length===0?<div className="crm-empty small" style={{padding:'8px 0'}}>{empty}</div>:<div style={{marginTop:6,borderTop:'1px solid #eee'}}>{rows.map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1.2fr 1fr .8fr',gap:6,padding:'7px 0',fontSize:11,borderBottom:'1px solid #f1ede8'}}>{r.map((v,j)=><span key={j}>{v||'—'}</span>)}</div>)}</div>}</div>}
