import React,{useEffect,useState}from"react";
import{Save,X}from"lucide-react";
import api from"../../api/api";
import"./CustomerSelfServiceModal.css";

type Profile={id:string;full_name:string;email:string;phone?:string|null;birth_date?:string|null;city?:string|null;address?:string|null;preferred_contact?:string|null;marketing_consent:boolean;location_name?:string|null;email_read_only?:boolean};

export default function CustomerProfileModal({onClose,onSaved}:{onClose:()=>void;onSaved?:()=>void}){
 const[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 useEffect(()=>{let active=true;api.get("/customer-portal/self-service/profile").then(r=>active&&setProfile(r.data)).catch(e=>active&&setError(e?.response?.data?.error||"A profil nem tölthető be.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const set=(key:keyof Profile,value:any)=>setProfile(p=>p?{...p,[key]:value}:p);
 const save=async()=>{if(!profile)return;setSaving(true);setError("");setSuccess("");try{const r=await api.patch("/customer-portal/self-service/profile",{full_name:profile.full_name,phone:profile.phone||"",birth_date:profile.birth_date||null,city:profile.city||"",address:profile.address||"",preferred_contact:profile.preferred_contact||"email",marketing_consent:Boolean(profile.marketing_consent)});setProfile(r.data);setSuccess("A profiladatok mentve.");onSaved?.()}catch(e:any){setError(e?.response?.data?.error||"A profiladatok nem menthetők.")}finally{setSaving(false)}};
 return <div className="cssm-overlay" role="dialog" aria-modal="true" aria-label="Saját profil szerkesztése"><section className="cssm-dialog"><header className="cssm-head"><div><span>SAJÁT CRM ADATLAP</span><h2>Profil és értesítések</h2></div><button onClick={onClose} aria-label="Bezárás"><X/></button></header><div className="cssm-body">{loading?<div className="cssm-empty">Profil betöltése…</div>:profile?<><div className="cssm-grid"><label className="cssm-field"><span>Név</span><input value={profile.full_name||""} onChange={e=>set("full_name",e.target.value)}/></label><label className="cssm-field"><span>E-mail</span><input value={profile.email||""} disabled title="A belépési azonosító miatt itt nem módosítható."/></label><label className="cssm-field"><span>Telefonszám</span><input value={profile.phone||""} onChange={e=>set("phone",e.target.value)} placeholder="+36…"/></label><label className="cssm-field"><span>Születési dátum</span><input type="date" value={String(profile.birth_date||"").slice(0,10)} onChange={e=>set("birth_date",e.target.value)}/></label><label className="cssm-field"><span>Város</span><input value={profile.city||""} onChange={e=>set("city",e.target.value)}/></label><label className="cssm-field"><span>Értesítési mód</span><select value={["email","sms","both"].includes(String(profile.preferred_contact))?String(profile.preferred_contact):"email"} onChange={e=>set("preferred_contact",e.target.value)}><option value="email">E-mail</option><option value="sms">SMS</option><option value="both">E-mail + SMS</option></select></label><label className="cssm-field full"><span>Cím</span><input value={profile.address||""} onChange={e=>set("address",e.target.value)}/></label></div><label className="cssm-check"><input type="checkbox" checked={Boolean(profile.marketing_consent)} onChange={e=>set("marketing_consent",e.target.checked)}/><span>Hozzájárulok a marketing célú megkeresésekhez. A foglalással kapcsolatos operatív értesítések ettől függetlenek.</span></label><div className="cssm-note">Az e-mail cím a belépett ügyfélfiók azonosítója, ezért ezen a felületen nem módosítható. E-mail-cím cseréjéhez a szalon segítsége szükséges.</div>{error&&<div className="cssm-error">{error}</div>}{success&&<div className="cssm-success">{success}</div>}<div className="cssm-actions"><button onClick={onClose}>Bezárás</button><button className="primary" onClick={save} disabled={saving}><Save size={15}/>{saving?"Mentés…":"Módosítások mentése"}</button></div></>:error?<div className="cssm-error">{error}</div>:null}</div></section></div>;
}
