import React,{useEffect,useMemo,useState}from"react";
import{Archive,Download,RefreshCw,ShieldCheck,Trash2,WalletCards,Boxes,Users,Settings2}from"lucide-react";
import api from"../api/api";
import{useCapabilities}from"../hooks/useCapabilities";
import LanguageSwitcher from"../components/LanguageSwitcher";
import UnifiedFilterToolbar from"../components/UnifiedFilterToolbar";
import{useLanguage}from"../i18n/LanguageProvider";
import ArchiveCenterPage from"./ArchiveCenterPage";
import"./AuditLogPage.css";

type Row={id:number;occurred_at:string;actor_key?:string;location_id?:string;module_key:string;entity_type:string;entity_id?:string;action:string;summary?:string;before_data?:any;after_data?:any};
type Summary={today:number;last_7_days:number;deletes:number;finance_events:number;inventory_events:number;hr_events:number;admin_events:number};
const labelsHu:Record<string,string>={finance:"Pénzügy",inventory:"Raktár",hr:"HR",administration:"Adminisztráció",system:"Rendszer",crm:"CRM",insert:"Létrehozás",update:"Módosítás",delete:"Törlés",soft_delete:"Inaktiválás",restore:"Visszaállítás",deactivate:"Inaktiválás"};
const labelsEn:Record<string,string>={finance:"Finance",inventory:"Inventory",hr:"HR",administration:"Administration",system:"System",crm:"CRM",insert:"Create",update:"Update",delete:"Delete",soft_delete:"Deactivate",restore:"Restore",deactivate:"Deactivate"};
export default function AuditLogPage(){const{language,locale,t}=useLanguage();const[view,setView]=useState<"audit"|"archive">("audit");const[rows,setRows]=useState<Row[]>([]);const[sum,setSum]=useState<Summary|null>(null);const[q,setQ]=useState("");const[module,setModule]=useState("");const[action,setAction]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const{menu}=useCapabilities();const canExport=menu("settings.audit","can_export");const label=language==="en"?labelsEn:labelsHu;
const params=()=>({q:q||undefined,module:module||undefined,action:action||undefined,limit:250});
const load=async()=>{setLoading(true);setError("");try{const[a,b]=await Promise.all([api.get("/transactions/audit",{params:params()}),api.get("/transactions/audit/summary")]);setRows(Array.isArray(a.data)?a.data:[]);setSum(b.data||null)}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||e?.message||"Audit load failed.")}finally{setLoading(false)}};
const exportCsv=async()=>{setError("");try{const r=await api.get("/transactions/audit/export.csv",{params:params(),responseType:"blob"});const url=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=url;a.download=`kleoszalon-audit-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e:any){setError(e?.response?.data?.error||"Audit export failed.")}};
useEffect(()=>{if(view==="audit")void load()},[view]);// eslint-disable-line react-hooks/exhaustive-deps
const cards=useMemo(()=>[{t:t("audit.today"),v:sum?.today||0,i:<ShieldCheck/>},{t:t("audit.last7"),v:sum?.last_7_days||0,i:<RefreshCw/>},{t:t("audit.finance"),v:sum?.finance_events||0,i:<WalletCards/>},{t:t("audit.inventory"),v:sum?.inventory_events||0,i:<Boxes/>},{t:t("audit.hr"),v:sum?.hr_events||0,i:<Users/>},{t:t("audit.admin"),v:sum?.admin_events||0,i:<Settings2/>},{t:t("audit.deletes"),v:sum?.deletes||0,i:<Trash2/>}], [sum,t]);
if(view==="archive")return <div><div style={{display:"flex",gap:8,padding:"16px 24px 0"}}><button onClick={()=>setView("audit")}><ShieldCheck size={16}/> {t("audit.title")}</button><button disabled><Archive size={16}/> {t("recycle.title")}</button></div><ArchiveCenterPage/></div>;
return <main className="audit-page"><header className="audit-hero"><div><span>{t("audit.eyebrow")}</span><h1>{t("audit.title")}</h1><p>{t("audit.description")}</p></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><LanguageSwitcher compact/><button onClick={()=>setView("archive")}><Archive size={16}/> {t("recycle.title")}</button>{canExport&&<button onClick={exportCsv}><Download size={16}/> {t("audit.export")}</button>}<button onClick={load} disabled={loading}><RefreshCw size={16} className={loading?"spin":""}/> {t("common.refresh")}</button></div></header><div className="audit-cards">{cards.map(c=><article key={c.t}><i>{c.i}</i><div><small>{c.t}</small><strong>{c.v.toLocaleString(locale)}</strong></div></article>)}</div><section className="audit-panel"><UnifiedFilterToolbar query={q} onQueryChange={setQ} placeholder={t("audit.search")} count={rows.length} onApply={load} onReset={()=>{setQ("");setModule("");setAction("")}} selects={[{key:"module",value:module,onChange:setModule,options:[{value:"",label:t("audit.module")},{value:"finance",label:label.finance},{value:"inventory",label:label.inventory},{value:"hr",label:"HR"},{value:"administration",label:label.administration},{value:"crm",label:"CRM"}]},{key:"action",value:action,onChange:setAction,options:[{value:"",label:t("audit.action")},{value:"insert",label:label.insert},{value:"update",label:label.update},{value:"delete",label:label.delete},{value:"soft_delete",label:label.soft_delete},{value:"restore",label:label.restore}]}]}/>{error&&<div className="audit-error">{error}</div>}<div className="audit-table-wrap"><table><thead><tr><th>{language==="en"?"Time":"Időpont"}</th><th>{language==="en"?"Module":"Modul"}</th><th>{language==="en"?"Action":"Művelet"}</th><th>{language==="en"?"Object":"Objektum"}</th><th>{language==="en"?"Identifier":"Azonosító"}</th><th>{language==="en"?"User":"Felhasználó"}</th><th>{language==="en"?"Location":"Telephely"}</th><th>{language==="en"?"Change":"Változás"}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.occurred_at).toLocaleString(locale)}</td><td><span className={`audit-pill m-${r.module_key}`}>{label[r.module_key]||r.module_key}</span></td><td><span className={`audit-pill a-${r.action}`}>{label[r.action]||r.action}</span></td><td>{r.entity_type}</td><td>{r.entity_id||"—"}</td><td>{r.actor_key||"System / DB"}</td><td>{r.location_id||"—"}</td><td><details><summary>{t("common.details")}</summary><pre>{JSON.stringify({before:r.before_data,after:r.after_data},null,2)}</pre></details></td></tr>)}{!rows.length&&!loading&&<tr><td colSpan={8} className="audit-empty">{t("audit.empty")}</td></tr>}</tbody></table></div></section></main>}
