import React, { useEffect, useMemo, useState } from "react";
import api from "../api/api";

type Catalog={locations:any[];services:any[];staff_levels:any[];employees:any[]};
const emptyCatalog:Catalog={locations:[],services:[],staff_levels:[],employees:[]};
const msg=(e:any)=>e?.response?.data?.error||e?.response?.data?.message||e?.message||"A művelet sikertelen.";
const money=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const today=()=>new Date().toISOString().slice(0,10);

const CSS=`
.b4a{padding:28px;max-width:1500px;margin:0 auto;color:#1d1714}.b4a *{box-sizing:border-box}.b4a header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:22px}.b4a header small{font-weight:900;letter-spacing:.12em;color:#b08a55}.b4a h1{margin:5px 0 0;font-size:32px}.b4a header p{max-width:760px;color:#766b64}.b4a-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0 22px}.b4a-tabs button,.b4a button{border:1px solid #ded5ce;background:#fff;border-radius:10px;padding:10px 13px;font-weight:750;cursor:pointer}.b4a-tabs button.on,.b4a button.primary{background:#1b1512;color:#fff;border-color:#1b1512}.b4a-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.b4a-card{background:#fff;border:1px solid #e5ddd6;border-radius:16px;padding:18px;box-shadow:0 10px 28px rgba(30,20,14,.04)}.b4a-card h2{margin:0 0 14px;font-size:19px}.b4a label{display:grid;gap:6px;font-size:11px;font-weight:800;color:#675f59;margin-bottom:10px}.b4a input,.b4a select{width:100%;height:42px;border:1px solid #ddd4cd;border-radius:9px;padding:0 10px;background:#fff}.b4a-table{overflow:auto;border:1px solid #e5ddd6;border-radius:14px;background:#fff}.b4a-row{display:grid;grid-template-columns:1.5fr 1.2fr 1fr 1fr 120px;min-width:850px;border-top:1px solid #eee7e1;align-items:center}.b4a-row:first-child{border-top:0}.b4a-row>div{padding:11px 12px;font-size:12px}.b4a-head{background:#f7f3ef;font-size:10px!important;font-weight:900;text-transform:uppercase}.b4a-note{padding:12px 14px;border-radius:10px;margin:10px 0;background:#f5f0eb}.b4a-note.err{background:#fff0f4;color:#8d174f}.b4a-note.ok{background:#eff9f4;color:#276449}.b4a-actions{display:flex;gap:8px;flex-wrap:wrap}.b4a-status{font-weight:800}.b4a-status.active{color:#238156}.b4a-status.inactive{color:#9c455a}@media(max-width:1000px){.b4a-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.b4a{padding:18px}.b4a-grid{grid-template-columns:1fr}.b4a header{align-items:flex-start;flex-direction:column}}
`;

export default function BookingV4AdminPage(){
  const [tab,setTab]=useState("prices"),[catalog,setCatalog]=useState<Catalog>(emptyCatalog),[prices,setPrices]=useState<any[]>([]),[coupons,setCoupons]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[offers,setOffers]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [priceForm,setPriceForm]=useState<any>({service_id:"",staff_level_id:"",location_id:"",price:""});
  const [couponForm,setCouponForm]=useState<any>({code:"",name:"",discount_type:"percent",discount_value:10,valid_from:"",valid_until:"",minimum_booking_value:"",exclude_last_minute:true});
  const [ruleForm,setRuleForm]=useState<any>({name:"Automatikus Last Minute",location_id:"",service_id:"",staff_level_id:"",free_capacity_threshold_percent:50,discount_percent:20,validity_hours:24,same_day_only:true});
  const [rebuildDate,setRebuildDate]=useState(today());

  async function load(){setBusy(true);setError("");try{const [c,p,cp,r,o]=await Promise.all([api.get("/admin/booking-v4/catalog"),api.get("/admin/booking-v4/prices"),api.get("/admin/booking-v4/coupons"),api.get("/admin/booking-v4/rules"),api.get("/admin/booking-v4/offers")]);setCatalog(c.data||emptyCatalog);setPrices(p.data?.prices||[]);setCoupons(cp.data?.coupons||[]);setRules(r.data?.rules||[]);setOffers(o.data?.offers||[]);}catch(e){setError(msg(e));}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  const activeOffers=useMemo(()=>offers.filter(x=>x.status==="active"),[offers]);

  async function savePrice(){setBusy(true);setError("");setNotice("");try{await api.post("/admin/booking-v4/prices",{...priceForm,location_id:priceForm.location_id||null,price:Number(priceForm.price)});setNotice("Az árszint elmentve.");setPriceForm({...priceForm,price:""});await load();}catch(e){setError(msg(e));}finally{setBusy(false)}}
  async function saveCoupon(){setBusy(true);setError("");setNotice("");try{await api.post("/admin/booking-v4/coupons",{...couponForm,discount_value:Number(couponForm.discount_value),minimum_booking_value:couponForm.minimum_booking_value?Number(couponForm.minimum_booking_value):null,valid_from:couponForm.valid_from||null,valid_until:couponForm.valid_until||null});setNotice("A kupon létrehozva.");setCouponForm({...couponForm,code:"",name:""});await load();}catch(e){setError(msg(e));}finally{setBusy(false)}}
  async function saveRule(){setBusy(true);setError("");setNotice("");try{await api.post("/admin/booking-v4/rules",{...ruleForm,location_id:ruleForm.location_id||null,service_id:ruleForm.service_id||null,staff_level_id:ruleForm.staff_level_id||null});setNotice("A Last Minute szabály elmentve.");await load();}catch(e){setError(msg(e));}finally{setBusy(false)}}
  async function rebuild(){setBusy(true);setError("");setNotice("");try{const r=await api.post("/admin/booking-v4/rebuild",{date:rebuildDate});setNotice(`${r.data?.generated||0} Last Minute ajánlat generálva.`);await load();}catch(e){setError(msg(e));}finally{setBusy(false)}}
  async function toggle(kind:"prices"|"coupons"|"rules",id:string,is_active:boolean){try{await api.patch(`/admin/booking-v4/${kind}/${id}`,{is_active:!is_active});await load();}catch(e){setError(msg(e));}}
  async function employeeLevel(employeeId:string,levelId:string){try{await api.patch(`/admin/booking-v4/employees/${employeeId}/staff-level`,{staff_level_id:levelId||null});await load();}catch(e){setError(msg(e));}}

  return <main className="b4a"><style>{CSS}</style>
    <header><div><small>VIR · BOOKING 4.0</small><h1>Foglalási kereskedelmi központ</h1><p>Szakemberszintek, Normál/TOP/Master árak, kuponkampányok és automatikus Last Minute kapacitásértékesítés egy helyen.</p></div><button onClick={()=>void load()} disabled={busy}>Frissítés</button></header>
    {error&&<div className="b4a-note err">{error}</div>}{notice&&<div className="b4a-note ok">{notice}</div>}
    <div className="b4a-grid"><div className="b4a-card"><h2>{catalog.services.length}</h2><span>aktív szolgáltatás</span></div><div className="b4a-card"><h2>{catalog.employees.length}</h2><span>aktív szakember</span></div><div className="b4a-card"><h2>{coupons.filter(x=>x.is_active).length}</h2><span>aktív kupon</span></div><div className="b4a-card"><h2>{activeOffers.length}</h2><span>aktív Last Minute ajánlat</span></div></div>
    <nav className="b4a-tabs">{[["prices","Árszintek"],["staff","Szakemberszintek"],["coupons","Kuponok"],["lastminute","Last Minute"]].map(([id,label])=><button key={id} className={tab===id?"on":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>

    {tab==="prices"&&<><section className="b4a-card"><h2>Normál / TOP / Master ár rögzítése</h2><div className="b4a-grid"><label>Szalon<select value={priceForm.location_id} onChange={e=>setPriceForm({...priceForm,location_id:e.target.value})}><option value="">Minden szalon / alapár</option>{catalog.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Szolgáltatás<select value={priceForm.service_id} onChange={e=>setPriceForm({...priceForm,service_id:e.target.value})}><option value="">Válassz</option>{catalog.services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Szakemberszint<select value={priceForm.staff_level_id} onChange={e=>setPriceForm({...priceForm,staff_level_id:e.target.value})}><option value="">Válassz</option>{catalog.staff_levels.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Ár (Ft)<input type="number" min="0" value={priceForm.price} onChange={e=>setPriceForm({...priceForm,price:e.target.value})}/></label></div><button className="primary" disabled={busy||!priceForm.service_id||!priceForm.staff_level_id||priceForm.price===""} onClick={()=>void savePrice()}>Ár mentése</button></section><section className="b4a-table" style={{marginTop:16}}><div className="b4a-row b4a-head"><div>Szolgáltatás</div><div>Szalon</div><div>Szint</div><div>Ár</div><div>Állapot</div></div>{prices.map(x=><div className="b4a-row" key={x.id}><div>{x.service_name}</div><div>{x.location_name||"Alapár"}</div><div>{x.staff_level_name}</div><div>{money(x.price)}</div><div><button onClick={()=>void toggle("prices",x.id,x.is_active)}>{x.is_active?"Aktív":"Inaktív"}</button></div></div>)}</section></>}

    {tab==="staff"&&<section className="b4a-card"><h2>Szakemberek besorolása</h2><div className="b4a-table"><div className="b4a-row b4a-head"><div>Munkatárs</div><div>Szalon</div><div>Jelenlegi szint</div><div>Új szint</div><div>Állapot</div></div>{catalog.employees.map(e=><div className="b4a-row" key={e.id}><div>{e.full_name}</div><div>{catalog.locations.find(l=>l.id===e.location_id)?.name||"Központi"}</div><div>{catalog.staff_levels.find(l=>l.id===e.booking_staff_level_id)?.name||"Nincs besorolva"}</div><div><select value={e.booking_staff_level_id||""} onChange={ev=>void employeeLevel(e.id,ev.target.value)}><option value="">Nincs</option>{catalog.staff_levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="b4a-status active">Aktív</div></div>)}</div></section>}

    {tab==="coupons"&&<><section className="b4a-card"><h2>Új kuponkampány</h2><div className="b4a-grid"><label>Kuponkód<input value={couponForm.code} onChange={e=>setCouponForm({...couponForm,code:e.target.value.toUpperCase()})}/></label><label>Megnevezés<input value={couponForm.name} onChange={e=>setCouponForm({...couponForm,name:e.target.value})}/></label><label>Kedvezmény típusa<select value={couponForm.discount_type} onChange={e=>setCouponForm({...couponForm,discount_type:e.target.value})}><option value="percent">Százalék</option><option value="fixed">Fix összeg</option></select></label><label>Kedvezmény<input type="number" value={couponForm.discount_value} onChange={e=>setCouponForm({...couponForm,discount_value:e.target.value})}/></label><label>Érvényes ettől<input type="datetime-local" value={couponForm.valid_from} onChange={e=>setCouponForm({...couponForm,valid_from:e.target.value})}/></label><label>Érvényes eddig<input type="datetime-local" value={couponForm.valid_until} onChange={e=>setCouponForm({...couponForm,valid_until:e.target.value})}/></label><label>Minimum foglalási érték<input type="number" value={couponForm.minimum_booking_value} onChange={e=>setCouponForm({...couponForm,minimum_booking_value:e.target.value})}/></label><label><span>Last Minute kizárása</span><select value={couponForm.exclude_last_minute?"yes":"no"} onChange={e=>setCouponForm({...couponForm,exclude_last_minute:e.target.value==="yes"})}><option value="yes">Igen</option><option value="no">Nem</option></select></label></div><button className="primary" disabled={busy||!couponForm.code||!couponForm.name} onClick={()=>void saveCoupon()}>Kupon létrehozása</button></section><section className="b4a-table" style={{marginTop:16}}><div className="b4a-row b4a-head"><div>Kód / név</div><div>Érvényesség</div><div>Kedvezmény</div><div>Minimum</div><div>Állapot</div></div>{coupons.map(x=><div className="b4a-row" key={x.id}><div><b>{x.code}</b><br/><small>{x.name}</small></div><div>{x.valid_until?new Date(x.valid_until).toLocaleDateString("hu-HU"):"Nincs lejárat"}</div><div>{x.discount_type==="percent"?`${x.discount_value}%`:money(x.discount_value)}</div><div>{x.minimum_booking_value?money(x.minimum_booking_value):"—"}</div><div><button onClick={()=>void toggle("coupons",x.id,x.is_active)}>{x.is_active?"Aktív":"Inaktív"}</button></div></div>)}</section></>}

    {tab==="lastminute"&&<><section className="b4a-card"><h2>Automatikus Last Minute szabály</h2><div className="b4a-grid"><label>Megnevezés<input value={ruleForm.name} onChange={e=>setRuleForm({...ruleForm,name:e.target.value})}/></label><label>Szalon<select value={ruleForm.location_id} onChange={e=>setRuleForm({...ruleForm,location_id:e.target.value})}><option value="">Válassz</option>{catalog.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Szolgáltatás<select value={ruleForm.service_id} onChange={e=>setRuleForm({...ruleForm,service_id:e.target.value})}><option value="">Válassz</option>{catalog.services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Szakemberszint<select value={ruleForm.staff_level_id} onChange={e=>setRuleForm({...ruleForm,staff_level_id:e.target.value})}><option value="">Minden szint</option>{catalog.staff_levels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Szabad kapacitás küszöb %<input type="number" value={ruleForm.free_capacity_threshold_percent} onChange={e=>setRuleForm({...ruleForm,free_capacity_threshold_percent:Number(e.target.value)})}/></label><label>Kedvezmény %<input type="number" value={ruleForm.discount_percent} onChange={e=>setRuleForm({...ruleForm,discount_percent:Number(e.target.value)})}/></label><label>Érvényesség (óra)<input type="number" value={ruleForm.validity_hours} onChange={e=>setRuleForm({...ruleForm,validity_hours:Number(e.target.value)})}/></label><label>Napi újragenerálás dátuma<input type="date" value={rebuildDate} onChange={e=>setRebuildDate(e.target.value)}/></label></div><div className="b4a-actions"><button className="primary" disabled={busy||!ruleForm.location_id||!ruleForm.service_id} onClick={()=>void saveRule()}>Szabály mentése</button><button disabled={busy} onClick={()=>void rebuild()}>Ajánlatok generálása</button></div></section><section className="b4a-table" style={{marginTop:16}}><div className="b4a-row b4a-head"><div>Szabály</div><div>Szalon</div><div>Szolgáltatás</div><div>Kedvezmény</div><div>Állapot</div></div>{rules.map(x=><div className="b4a-row" key={x.id}><div>{x.name}</div><div>{x.location_name||"—"}</div><div>{x.service_name||"—"}</div><div>{x.discount_percent}%</div><div><button onClick={()=>void toggle("rules",x.id,x.is_active)}>{x.is_active?"Aktív":"Inaktív"}</button></div></div>)}</section><section className="b4a-card" style={{marginTop:16}}><h2>Aktív ajánlatok ({activeOffers.length})</h2>{activeOffers.slice(0,20).map(x=><div key={x.id} style={{padding:"9px 0",borderTop:"1px solid #eee"}}><b>{x.service_name}</b> · {x.location_name} · {x.employee_name} · {new Date(x.start_time).toLocaleString("hu-HU")} · <strong>{money(x.offer_price)}</strong></div>)}</section></>}
  </main>;
}
