import React,{useEffect,useState}from"react";
import api from"../api/api";
import BookingV4AdminPage from"./BookingV4AdminPage";

type ChainItem={sequence_no:number;appointment_id:string;service_name:string;employee_name:string;start:string;end:string;appointment_status:string};
type Chain={id:string;status:string;location_name:string;client_name:string;phone?:string;email?:string;start_time:string;end_time:string;total_gap_minutes:number;created_at:string;items:ChainItem[]};
const hhmm=(v:string)=>new Date(v).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"});
const dt=(v:string)=>new Date(v).toLocaleString("hu-HU",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});
const CSS=`.b4chains{max-width:1500px;margin:0 auto;padding:0 28px 42px;color:#1d1714}.b4chains-head{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin:8px 0 15px}.b4chains-head h2{margin:0;font-size:23px}.b4chains-head p{margin:5px 0 0;color:#746a63;font-size:12px}.b4chains button{border:1px solid #ded5ce;background:#fff;border-radius:10px;padding:9px 12px;font-weight:750;cursor:pointer}.b4chains-list{display:grid;gap:12px}.b4chain{border:1px solid #e5ddd6;border-radius:16px;background:#fff;padding:16px;box-shadow:0 8px 24px rgba(30,20,14,.04)}.b4chain-top{display:grid;grid-template-columns:1.4fr 1fr 1fr auto;gap:12px;align-items:center}.b4chain-top small{display:block;color:#81756d;margin-top:3px}.b4chain-status{font-weight:850}.b4chain-status.active{color:#238156}.b4chain-steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(185px,1fr));gap:8px;margin-top:12px}.b4chain-step{background:#f8f4ef;border-radius:11px;padding:10px}.b4chain-step b,.b4chain-step span{display:block}.b4chain-step span{font-size:11px;color:#746a63;margin-top:3px}.b4chain-empty,.b4chain-error{padding:14px;border-radius:11px;background:#f6f0eb}.b4chain-error{background:#fff0f4;color:#8d174f}@media(max-width:800px){.b4chain-top{grid-template-columns:1fr 1fr}.b4chains{padding:0 18px 30px}}`;

export default function BookingV4AdminPageV2(){
 const[chains,setChains]=useState<Chain[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await api.get("/admin/booking-v4/chains?limit=100");setChains(r.data?.chains||[])}catch(e:any){setError(e?.response?.data?.error||e?.message||"A foglalási láncok nem tölthetők be.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 return <><BookingV4AdminPage/><section className="b4chains"><style>{CSS}</style><div className="b4chains-head"><div><h2>Több szakemberes foglalási láncok</h2><p>Booking 4.0 · egymáshoz optimalizált szolgáltatások és szakemberek operatív ellenőrzése.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Frissítés…":"Láncok frissítése"}</button></div>{error&&<div className="b4chain-error">{error}</div>}{!error&&!loading&&!chains.length&&<div className="b4chain-empty">Még nincs több szakemberes Booking 4.0 foglalási lánc.</div>}<div className="b4chains-list">{chains.map(c=><article className="b4chain" key={c.id}><div className="b4chain-top"><div><b>{c.client_name}</b><small>{c.phone||c.email||"Nincs elérhetőség"}</small></div><div><b>{c.location_name}</b><small>{dt(c.start_time)} – {hhmm(c.end_time)}</small></div><div><b>{c.items?.length||0} szolgáltatás</b><small>{Number(c.total_gap_minutes||0)} perc várakozás</small></div><div className={`b4chain-status ${c.status}`}>{c.status}</div></div><div className="b4chain-steps">{(c.items||[]).map(x=><div className="b4chain-step" key={x.appointment_id}><b>{x.sequence_no+1}. {x.service_name}</b><span>{hhmm(x.start)}–{hhmm(x.end)}</span><span>{x.employee_name}</span><span>Időpont: {x.appointment_status}</span></div>)}</div><small style={{display:"block",marginTop:10,color:"#8a7d74"}}>Láncazonosító: {c.id} · létrehozva: {dt(c.created_at)}</small></article>)}</div></section></>;
}
