import{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,CalendarClock,CheckCircle2,ChevronRight,ClipboardCheck,Play,RefreshCw,Save,ShieldCheck,Target,TimerReset,XCircle}from'lucide-react';
import{useNavigate}from'react-router-dom';
import api from'../api';
import'./BusinessContinuityGameDayPage.css';

const BASE='/api/transactions/notifications/gameday';
const statusHu:Record<string,string>={planned:'Tervezett',running:'Fut',verifying:'Verifikáció',completed:'Lezárt',cancelled:'Megszakítva'};
const stateHu:Record<string,string>={planned:'Tervezett',impacted:'Érintett',recovering:'Helyreállítás',restored:'Helyreállt',verified:'Verifikált'};
const fmt=(v:any)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const n=(v:any)=>Number(v||0);
const evidence=(description:string,source:string)=>description.trim()?{description:description.trim(),source}:{};

export default function BusinessContinuityGameDayPage(){
 const nav=useNavigate();const[summary,setSummary]=useState<any>(null),[templates,setTemplates]=useState<any[]>([]),[policies,setPolicies]=useState<any[]>([]),[drills,setDrills]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState('all');
 const[plan,setPlan]=useState({template_code:'backup_restore',title:'',objective:'Negyedéves üzletmenet-folytonossági helyreállítási gyakorlat',planned_start_at:new Date(Date.now()+86400000).toISOString().slice(0,16)});
 const[serviceDraft,setServiceDraft]=useState<Record<string,any>>({}),[stepEvidence,setStepEvidence]=useState<Record<string,string>>({});
 const[complete,setComplete]=useState({approver_key:'',note:'',evidence:''});const locationId=localStorage.getItem('kleo_location_id')||'';
 const query=useMemo(()=>{const p=new URLSearchParams();if(status!=='all')p.set('status',status);if(locationId)p.set('location_id',locationId);return p.toString()},[status,locationId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const loc=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const[a,b,c,d]=await Promise.all([api.get(`${BASE}/summary${loc}`),api.get(`${BASE}/templates`),api.get(`${BASE}/service-readiness`),api.get(`${BASE}/drills?${query}`)]);setSummary(a.data);setTemplates(b.data?.items||[]);setPolicies(c.data?.items||[]);setDrills(d.data?.items||[])}catch(e:any){setError(e?.response?.data?.message||'A GameDay központ nem tölthető be.')}finally{setLoading(false)}},[locationId,query]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const t=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(t)},[load]);
 async function open(id:string){try{const loc=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const r=await api.get(`${BASE}/drills/${id}${loc}`);setSelected(r.data);const d:Record<string,any>={};for(const s of r.data.services||[])d[s.service_key]={state:s.state,observed_rto_minutes:s.observed_rto_minutes??'',observed_rpo_minutes:s.observed_rpo_minutes??'',verification_note:s.verification_note||'',evidence:''};setServiceDraft(d)}catch(e:any){setError(e?.response?.data?.message||'A GameDay nem nyitható meg.')}}
 async function create(){if(plan.objective.trim().length<10){setError('A GameDay célja legalább 10 karakter legyen.');return}try{const r=await api.post(`${BASE}/drills`,{...plan,location_id:locationId||null});setNotice(`${r.data?.item?.drill_no||'GameDay'} megtervezve.`);await load();if(r.data?.item?.id)await open(r.data.item.id)}catch(e:any){setError(e?.response?.data?.message||'A GameDay nem hozható létre.')}}
 async function simple(path:string,message:string){if(!selected)return;try{const r=await api.post(`${BASE}/drills/${selected.item.id}/${path}`);setSelected(r.data);setNotice(message);await load()}catch(e:any){setError(e?.response?.data?.message||'A művelet nem hajtható végre.')}}
 async function saveService(s:any){if(!selected)return;const d=serviceDraft[s.service_key]||{};if(d.state==='verified'&&(String(d.verification_note||'').trim().length<10||String(d.evidence||'').trim().length<5)){setError('Verifikált szolgáltatáshoz jegyzet és evidence szükséges.');return}try{await api.patch(`${BASE}/drills/${selected.item.id}/services/${s.service_key}`,{state:d.state,observed_rto_minutes:d.observed_rto_minutes===''?null:Number(d.observed_rto_minutes),observed_rpo_minutes:d.observed_rpo_minutes===''?null:Number(d.observed_rpo_minutes),verification_note:d.verification_note,evidence:evidence(d.evidence||'','gameday-service')});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'A service mérés nem menthető.')}}
 async function step(s:any,next:string){if(!selected)return;const key=`${s.service_key}:${s.step_key}`,ev=(stepEvidence[key]||'').trim();if(next==='completed'&&ev.length<5){setError('Step lezárásához evidence szükséges.');return}try{await api.patch(`${BASE}/drills/${selected.item.id}/steps/${s.service_key}/${s.step_key}`,{status:next,evidence:evidence(ev,'gameday-runbook')});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'A runbook step nem menthető.')}}
 async function releaseInject(x:any){if(!selected)return;try{await api.post(`${BASE}/drills/${selected.item.id}/injects/${x.id}/release`);await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'Az inject nem adható ki.')}}
 async function ackInject(x:any){if(!selected)return;const note=window.prompt('Válasz / döntés az injectre (min. 10 karakter):','')||'',ev=window.prompt('Bizonyíték / evidence (min. 5 karakter):','')||'';if(note.trim().length<10||ev.trim().length<5)return;try{await api.post(`${BASE}/drills/${selected.item.id}/injects/${x.id}/ack`,{response_note:note,evidence:evidence(ev,'gameday-inject')});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'Az inject nem igazolható vissza.')}}
 async function finish(){if(!selected)return;if(complete.approver_key.trim().length<3||complete.note.trim().length<10||complete.evidence.trim().length<5){setError('Lezáráshoz független jóváhagyó, részletes megjegyzés és evidence szükséges.');return}if(!window.confirm('Lezárja a GameDay gyakorlatot és elkészíti a scorecardot?'))return;try{const r=await api.post(`${BASE}/drills/${selected.item.id}/complete`,{approver_key:complete.approver_key.trim(),note:complete.note.trim(),evidence:evidence(complete.evidence,'gameday-completion')});setSelected(r.data);setNotice(`GameDay lezárva: ${String(r.data?.scorecard?.result||'').toUpperCase()} · ${r.data?.scorecard?.score||0}/100.`);await load()}catch(e:any){setError(e?.response?.data?.message||'A GameDay nem zárható le.')}}
 async function actionStatus(a:any,next:string){if(!selected)return;let ev='';if(['completed','accepted'].includes(next)){ev=window.prompt('Javítóakció evidence:','')||'';if(ev.trim().length<5)return}try{await api.patch(`${BASE}/drills/${selected.item.id}/actions/${a.id}`,{status:next,evidence:evidence(ev,'gameday-action')});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'A javítóakció nem módosítható.')}}
 const item=selected?.item,stepsByService=useMemo(()=>{const m:Record<string,any[]>={};for(const x of selected?.steps||[])(m[x.service_key]||(m[x.service_key]=[])).push(x);return m},[selected]);
 return <div className="gd-page">
  <header className="gd-hero"><div><button onClick={()=>nav('/finance/exception-command-center/resilience')}><ChevronRight className="back"/> Resilience & Recovery</button><span>STATISZTIKA ÉS VIR · BUSINESS CONTINUITY EXERCISE</span><h1><ShieldCheck/> Üzletmenet-folytonossági GameDay</h1><p>Biztonságos szimuláció: RTO/RPO próba, recovery runbook, injectek, scorecard és bizonyítékos javítóprogram valódi szolgáltatás-leállítás nélkül.</p></div><div className="gd-safety"><ShieldCheck/><b>SIMULATION ONLY</b><span>A GameDay nem állít le éles szolgáltatást és nem generál valódi Major Incidentet.</span></div></header>
  {error&&<div className="gd-error"><AlertTriangle/>{error}</div>}{notice&&<div className="gd-notice"><CheckCircle2/>{notice}</div>}
  {summary&&<section className="gd-kpis"><article><CalendarClock/><div><small>Tervezett</small><b>{n(summary.planned)}</b></div></article><article className={n(summary.active)>0?'active':''}><Activity/><div><small>Aktív gyakorlat</small><b>{n(summary.active)}</b></div></article><article className={n(summary.overdue_services)>0?'danger':''}><TimerReset/><div><small>Lejárt service drill</small><b>{n(summary.overdue_services)}</b></div></article><article><Target/><div><small>90 nap átlag</small><b>{summary.avg_score_90d??'—'}</b></div></article><article><CheckCircle2/><div><small>90 nap PASS</small><b>{summary.pass_rate_90d==null?'—':`${summary.pass_rate_90d}%`}</b></div></article><article className={n(summary.open_actions)>0?'warning':''}><ClipboardCheck/><div><small>Nyitott javítóakció</small><b>{n(summary.open_actions)}</b></div></article></section>}
  <section className="gd-plan"><div><h2><CalendarClock/> Új GameDay tervezése</h2><select value={plan.template_code} onChange={e=>setPlan({...plan,template_code:e.target.value})}>{templates.map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select><input value={plan.title} onChange={e=>setPlan({...plan,title:e.target.value})} placeholder="Egyedi cím (opcionális)"/><input type="datetime-local" value={plan.planned_start_at} onChange={e=>setPlan({...plan,planned_start_at:e.target.value})}/><input value={plan.objective} onChange={e=>setPlan({...plan,objective:e.target.value})} placeholder="Gyakorlat célja…"/><button onClick={create}><CalendarClock/> GameDay létrehozása</button></div><div className="gd-readiness"><h3>Service drill readiness</h3>{policies.slice(0,8).map(p=><div key={p.service_key} className={p.readiness}><b>{p.name}</b><span>{p.criticality.toUpperCase()}</span><em>{p.readiness==='never'?'Még nincs PASS':p.readiness==='overdue'?'LEJÁRT':p.readiness==='due'?`${p.days_until_due} nap`:'OK'}</em></div>)}</div></section>
  <div className="gd-filter"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Minden GameDay</option>{Object.entries(statusHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={load} disabled={loading}><RefreshCw className={loading?'spin':''}/> Frissítés</button></div>
  <section className="gd-work"><aside><header><b>GameDay gyakorlatok</b><span>{drills.length}</span></header>{drills.map(d=><button key={d.id} className={`${selected?.item?.id===d.id?'selected':''} ${d.result||d.status}`} onClick={()=>open(d.id)}><div><strong>{d.drill_no}</strong><em>{statusHu[d.status]||d.status}</em></div><b>{d.title}</b><small>{fmt(d.planned_start_at)} · {d.location_id||'globális'}</small><footer><span>{d.verified_services}/{d.service_count} service</span>{d.overall_score!=null&&<strong>{d.overall_score}/100</strong>}</footer></button>)}{!loading&&!drills.length&&<div className="gd-empty">Nincs GameDay.</div>}</aside>
   <main>{!selected?<div className="gd-placeholder"><ShieldCheck/><h2>Válasszon gyakorlatot</h2><p>A részletes drill-runbook és scorecard itt kezelhető.</p></div>:<><header className="gd-detail-head"><div><span>{item.drill_no} · {statusHu[item.status]}</span><h2>{item.title}</h2><p>{item.objective}</p></div><div>{item.status==='planned'&&<button onClick={()=>simple('start','GameDay elindítva.')}><Play/> Indítás</button>}{item.status==='running'&&<button onClick={()=>simple('verification','Verifikáció megkezdve.')}><CheckCircle2/> Verifikáció</button>}</div></header>
    {item.status==='completed'&&<section className={`gd-score ${item.result}`}><div><Target/><span>GAME DAY SCORECARD</span><b>{item.overall_score}/100</b><strong>{String(item.result).toUpperCase()}</strong></div><p>Owner: {item.owner_key} · független approver: {item.approver_key}</p></section>}
    <section className="gd-injects"><h3>Szimulációs injectek</h3>{(selected.injects||[]).map((x:any)=><article key={x.id} className={`${x.severity} ${x.status}`}><span>#{x.sequence_no} · +{x.scheduled_offset_minutes} perc</span><div><b>{x.title}</b><small>{x.instruction}</small>{x.response_note&&<em>{x.response_note}</em>}</div>{x.status==='pending'&&item.status==='running'&&<button onClick={()=>releaseInject(x)}>Inject kiadása</button>}{x.status==='released'&&<button onClick={()=>ackInject(x)}>Kezelve + evidence</button>}{x.status==='acknowledged'&&<CheckCircle2/>}</article>)}</section>
    <section className="gd-services"><h3>Service recovery · RTO/RPO</h3>{(selected.services||[]).map((s:any)=>{const d=serviceDraft[s.service_key]||{},rtoBad=s.observed_rto_minutes!=null&&n(s.observed_rto_minutes)>n(s.target_rto_minutes),rpoBad=s.observed_rpo_minutes!=null&&n(s.observed_rpo_minutes)>n(s.target_rpo_minutes);return <article key={s.service_key} className={rtoBad||rpoBad?'breach':''}><header><div><b>{s.service_name}</b><small>{s.criticality.toUpperCase()}</small></div><div><span>RTO cél {s.target_rto_minutes}p</span><span>RPO cél {s.target_rpo_minutes}p</span></div></header><div className="gd-service-form"><select value={d.state||s.state} onChange={e=>setServiceDraft({...serviceDraft,[s.service_key]:{...d,state:e.target.value}})}>{Object.entries(stateHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input type="number" min="0" value={d.observed_rto_minutes??''} onChange={e=>setServiceDraft({...serviceDraft,[s.service_key]:{...d,observed_rto_minutes:e.target.value}})} placeholder="Mért RTO p"/><input type="number" min="0" value={d.observed_rpo_minutes??''} onChange={e=>setServiceDraft({...serviceDraft,[s.service_key]:{...d,observed_rpo_minutes:e.target.value}})} placeholder="Mért RPO p"/><input value={d.verification_note||''} onChange={e=>setServiceDraft({...serviceDraft,[s.service_key]:{...d,verification_note:e.target.value}})} placeholder="Verifikációs jegyzet"/><input value={d.evidence||''} onChange={e=>setServiceDraft({...serviceDraft,[s.service_key]:{...d,evidence:e.target.value}})} placeholder="Evidence"/><button onClick={()=>saveService(s)}><Save/> Mentés</button></div><div className="gd-runbook">{(stepsByService[s.service_key]||[]).map((x:any)=>{const key=`${x.service_key}:${x.step_key}`;return <div key={key} className={x.status}><span>{x.order_index}</span><div><b>{x.title}</b><small>{x.instruction}</small></div><em>{x.status}</em>{x.status!=='completed'&&item.status!=='completed'&&<><input value={stepEvidence[key]||''} onChange={e=>setStepEvidence({...stepEvidence,[key]:e.target.value})} placeholder="Step evidence"/><button onClick={()=>step(x,x.status==='pending'?'in_progress':'completed')}>{x.status==='pending'?'Indítás':'Lezárás'}</button></>}</div>})}</div></article>})}</section>
    {item.status==='verifying'&&<section className="gd-complete"><h3><ClipboardCheck/> Független lezárás és scorecard</h3><p>A jóváhagyó nem lehet azonos a drill ownerrel: <b>{item.owner_key}</b>.</p><input value={complete.approver_key} onChange={e=>setComplete({...complete,approver_key:e.target.value})} placeholder="Független approver e-mail / azonosító"/><input value={complete.note} onChange={e=>setComplete({...complete,note:e.target.value})} placeholder="Lezárási értékelés…"/><input value={complete.evidence} onChange={e=>setComplete({...complete,evidence:e.target.value})} placeholder="Lezárási evidence…"/><button onClick={finish}><CheckCircle2/> Scorecard és lezárás</button></section>}
    {!!selected.actions?.length&&<section className="gd-actions"><h3>Automatikus improvement actions</h3>{selected.actions.map((a:any)=><article key={a.id} className={a.priority}><span>{a.priority.toUpperCase()}</span><div><b>{a.title}</b><small>{a.description}</small></div><em>{a.status}</em>{a.status==='open'&&<button onClick={()=>actionStatus(a,'in_progress')}>Felvétel</button>}{a.status==='in_progress'&&<button onClick={()=>actionStatus(a,'completed')}>Lezárás</button>}{a.status==='completed'&&<button onClick={()=>actionStatus(a,'accepted')}>Elfogadás</button>}</article>)}</section>}
   </>}</main></section>
 </div>
}
