import React,{useCallback,useEffect,useMemo,useState}from"react";
import{ArrowLeft,CheckCircle2,GitMerge,History,Mail,MapPin,Phone,RefreshCw,ShieldCheck,UserCheck,Users,XCircle}from"lucide-react";
import{useNavigate}from"react-router-dom";
import withBase from"../utils/apiBase";
import"./ClientDuplicateReviewPage.css";

type Client={id:string;name:string;email?:string|null;phone?:string|null;location_id?:string|null;created_at?:string|null;visits?:number;spent?:number};
type Pair={pair_key:string;match_reasons:string[];client_a:Client;client_b:Client};
type Resolution={id:string;primary_client_id:string;duplicate_client_id:string;decision:"merged"|"dismissed";primary_name?:string|null;duplicate_name?:string|null;decided_by?:string|null;created_at:string};
type Payload={pending:Pair[];history:Resolution[];can_approve:boolean};
const token=()=>localStorage.getItem("token")||localStorage.getItem("kleo_token")||"";
const money=(v?:number)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
const dateTime=(v?:string|null)=>v?new Intl.DateTimeFormat("hu-HU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
async function api<T=any>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch(withBase(path),{...options,credentials:"include",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`,...(options.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||p.error||(p.detail?String(p.detail):`HTTP ${r.status}`));return p as T}
function Card({client,primary,onClick}:{client:Client;primary:boolean;onClick:()=>void}){return <button type="button" className={`dup-candidate ${primary?"primary":""}`} onClick={onClick}><span className="dup-radio">{primary?<UserCheck size={18}/>:<Users size={18}/>}</span><span className="dup-candidate-main"><span className="dup-candidate-title"><strong>{client.name}</strong>{primary&&<em>Megmaradó profil</em>}</span><span className="dup-contact"><Mail size={14}/>{client.email||"Nincs e-mail"}</span><span className="dup-contact"><Phone size={14}/>{client.phone||"Nincs telefonszám"}</span><span className="dup-contact"><MapPin size={14}/>{client.location_id||"Nincs telephely"}</span><span className="dup-candidate-meta"><span>{client.visits||0} látogatás</span><span>{money(client.spent)}</span><span>{dateTime(client.created_at)}</span></span></span></button>}
export default function ClientDuplicateReviewPage(){
 const navigate=useNavigate();const[data,setData]=useState<Payload>({pending:[],history:[],can_approve:false});const[loading,setLoading]=useState(true);const[working,setWorking]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[primary,setPrimary]=useState<Record<string,string>>({});const[notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const id=localStorage.getItem("kleo_location_id")||"";const p=await api<Payload>(`clients/duplicate-review${id?`?location_id=${encodeURIComponent(id)}`:""}`);setData(p);setPrimary(old=>{const n={...old};p.pending.forEach(x=>{if(!n[x.pair_key])n[x.pair_key]=x.client_a.id});return n})}catch(e:any){setError(e.message||"A duplikációs lista betöltése nem sikerült.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const summary=useMemo(()=>({pending:data.pending.length,merged:data.history.filter(x=>x.decision==="merged").length,dismissed:data.history.filter(x=>x.decision==="dismissed").length}),[data]);
 async function resolve(pair:Pair,decision:"merge"|"dismiss"){
  if(!data.can_approve)return;const keep=primary[pair.pair_key]||pair.client_a.id;const source=keep===pair.client_a.id?pair.client_b.id:pair.client_a.id;const note=notes[pair.pair_key]||null;
  if(decision==="merge"&&!window.confirm("Jóváhagyod az összevonást? A másodlagos profil audit célból megmarad, de inaktívvá válik."))return;
  setWorking(pair.pair_key);setError("");try{
   if(decision==="merge"){
    await api("clients/duplicates/merge-preview",{method:"POST",body:JSON.stringify({source_client_id:source,target_client_id:keep})});
    await api("clients/duplicates/merge",{method:"POST",body:JSON.stringify({source_client_id:source,target_client_id:keep,note})});
    await api("clients/duplicate-review/merged",{method:"POST",body:JSON.stringify({primary_client_id:keep,duplicate_client_id:source,note,location_id:localStorage.getItem("kleo_location_id")||null})});
   }else await api("clients/duplicate-review/dismiss",{method:"POST",body:JSON.stringify({primary_client_id:keep,duplicate_client_id:source,note,location_id:localStorage.getItem("kleo_location_id")||null})});
   setNotice(decision==="merge"?"Az ügyfélprofilok biztonságos összevonása megtörtént.":"A pár nem duplikációként lett rögzítve.");await load();
  }catch(e:any){setError(e.message||"A döntés mentése nem sikerült.")}finally{setWorking("")}
 }
 return <main className="duplicate-review-page"><header className="dup-hero"><div><button className="dup-back" onClick={()=>navigate("/modules/customers/clients")}><ArrowLeft size={16}/>Ügyfelek és CRM</button><p className="dup-eyebrow">ÜGYFELEK ÉS CRM · ADATMINŐSÉG</p><h1>Duplikációk jóváhagyása</h1><p>E-mail- és telefonszám-egyezések ellenőrzése a kanonikus, tranzakciós CRM összevonási folyamattal.</p></div><button className="dup-refresh" onClick={load} disabled={loading}><RefreshCw size={17} className={loading?"spin":""}/>{loading?"Betöltés…":"Frissítés"}</button></header>
 {error&&<div className="dup-alert error"><XCircle size={18}/>{error}</div>}{notice&&<div className="dup-alert success"><CheckCircle2 size={18}/>{notice}</div>}{!data.can_approve&&<div className="dup-alert info"><ShieldCheck size={18}/>Megtekintési jogosultságod van; döntést adminisztrátor vagy vezető hagyhat jóvá.</div>}
 <section className="dup-metrics"><article><GitMerge/><div><span>Jóváhagyásra vár</span><strong>{summary.pending}</strong></div></article><article><CheckCircle2/><div><span>Összevonva</span><strong>{summary.merged}</strong></div></article><article><XCircle/><div><span>Nem duplikáció</span><strong>{summary.dismissed}</strong></div></article><article><History/><div><span>Auditbejegyzés</span><strong>{data.history.length}</strong></div></article></section>
 <section className="dup-panel"><div className="dup-section-head"><div><h2>Jóváhagyási sor</h2><p>Válaszd ki a megmaradó profilt; az összevonás előtt a rendszer hatásvizsgálatot futtat.</p></div></div>{!loading&&!data.pending.length?<div className="dup-empty"><CheckCircle2 size={32}/><strong>Nincs feldolgozatlan duplikáció.</strong></div>:<div className="dup-list">{data.pending.map(pair=>{const selected=primary[pair.pair_key]||pair.client_a.id,busy=working===pair.pair_key;return <article className="dup-pair" key={pair.pair_key}><div className="dup-pair-head"><div><strong>Lehetséges duplikáció</strong><span>{pair.match_reasons.map(r=><em key={r}>{r==="email"?"E-mail egyezés":"Telefonszám egyezés"}</em>)}</span></div></div><div className="dup-candidates"><Card client={pair.client_a} primary={selected===pair.client_a.id} onClick={()=>setPrimary(v=>({...v,[pair.pair_key]:pair.client_a.id}))}/><div className="dup-merge-icon"><GitMerge size={20}/></div><Card client={pair.client_b} primary={selected===pair.client_b.id} onClick={()=>setPrimary(v=>({...v,[pair.pair_key]:pair.client_b.id}))}/></div><label className="dup-note"><span>Jóváhagyási megjegyzés</span><input value={notes[pair.pair_key]||""} onChange={e=>setNotes(v=>({...v,[pair.pair_key]:e.target.value}))}/></label><div className="dup-actions"><button className="dup-dismiss" disabled={!data.can_approve||busy} onClick={()=>resolve(pair,"dismiss")}><XCircle size={17}/>Nem duplikáció</button><button className="dup-approve" disabled={!data.can_approve||busy} onClick={()=>resolve(pair,"merge")}><GitMerge size={17}/>{busy?"Feldolgozás…":"Összevonás jóváhagyása"}</button></div></article>})}</div>}</section>
 <section className="dup-panel"><div className="dup-section-head"><div><h2>Döntési napló</h2><p>Visszakereshető audit a legutóbbi duplikációs döntésekről.</p></div></div>{!data.history.length?<div className="dup-empty">Még nincs duplikációs döntés.</div>:<div className="dup-history"><div className="dup-history-head"><span>Döntés</span><span>Megmaradó profil</span><span>Másodlagos profil</span><span>Döntéshozó</span><span>Időpont</span></div>{data.history.map(x=><div className="dup-history-row" key={x.id}><span><em className={x.decision}>{x.decision==="merged"?"Összevonva":"Nem duplikáció"}</em></span><span><strong>{x.primary_name||x.primary_client_id}</strong></span><span><strong>{x.duplicate_name||x.duplicate_client_id}</strong></span><span>{x.decided_by||"—"}</span><span>{dateTime(x.created_at)}</span></div>)}</div>}</section></main>
}
