import React, { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, ChevronRight, ClipboardList, Download, FileSpreadsheet, Mail, MapPin, Merge, MessageSquarePlus, Phone, Plus, RefreshCw, Search, Tag, Upload, UserRound, Users, X } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import withBase from "../utils/apiBase";
import ClientLoyaltyPanel from "./clients/ClientLoyaltyPanel";
import "./ClientsCRMPage.css";

type ClientTag={id:string;name:string;color:string};
type Client={id:string;name:string;phone?:string;email?:string;location_id?:string;location_name?:string;birth_date?:string;gender?:string;city?:string;address?:string;notes?:string;preferred_contact?:string;marketing_consent?:boolean;is_active:boolean;source?:string;created_at?:string;updated_at?:string;visits:number;no_shows:number;last_visit?:string;next_visit?:string;tags:ClientTag[]};
type Stats={total:number;active:number;new_this_month:number;with_no_show:number};
type FormTemplate={id:string;title:string;description?:string;form_type:string;is_active:boolean;response_count:number};
type Detail={client:any;appointments:any[];notes:any[];tags:ClientTag[];forms:any[];loyalty?:{tier_name?:string;color?:string;discount_percent?:number;paid_total?:number;visit_count?:number}|null;consents?:any[]};
type Duplicate={email_key?:string;phone_key?:string;clients:Array<{id:string;name:string;email?:string;phone?:string}>};
type AltegioImportResult={ok:boolean;rows:number;inserted:number;updated:number;skipped:number;tagged:number};

const token=()=>localStorage.getItem("token")||localStorage.getItem("kleo_token")||"";
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(withBase(path),{...options,credentials:"include",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`,...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok) throw new Error(payload.detail?`${payload.error||"Hiba"}: ${payload.detail}`:payload.error||`HTTP ${response.status}`);return payload;}
const fmtDate=(value?:string)=>value?new Intl.DateTimeFormat("hu-HU",{year:"numeric",month:"short",day:"numeric"}).format(new Date(value)):"—";
const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const groupKey=(name:string)=>{const c=(name||"").trim().charAt(0).toLocaleUpperCase("hu-HU");return /^[A-ZÁÉÍÓÖŐÚÜŰ]$/.test(c)?c:"#"};
const blankClient={name:"",phone:"",email:"",location_id:localStorage.getItem("kleo_location_id")||"",birth_date:"",gender:"",city:"",address:"",notes:"",preferred_contact:"phone",marketing_consent:false,email_consent:false,sms_consent:false,phone_consent:false,consent_source:"admin",privacy_notice_version:"2026-08",customer_type:"normal",barcode:"",source:"manual",is_active:true};
const tabs=[{key:"list",label:"Ügyféltörzs",icon:Users},{key:"profiles",label:"Adatlapok és előzmények",icon:UserRound},{key:"forms",label:"Kérdőívek és nyilatkozatok",icon:ClipboardList},{key:"segments",label:"Címkék és szegmensek",icon:Tag},{key:"import",label:"Import és duplikációk",icon:Merge}];

export default function ClientsCRMPage(){
const location=useLocation();const navigate=useNavigate();const view=location.pathname.split("/").filter(Boolean).pop()||"list";
const[clients,setClients]=useState<Client[]>([]);const[stats,setStats]=useState<Stats>({total:0,active:0,new_this_month:0,with_no_show:0});const[segments,setSegments]=useState<ClientTag[]>([]);const[forms,setForms]=useState<FormTemplate[]>([]);const[duplicates,setDuplicates]=useState<Duplicate[]>([]);const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[tagId,setTagId]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[editor,setEditor]=useState<any|null>(null);const[detail,setDetail]=useState<Detail|null>(null);const[detailLoading,setDetailLoading]=useState(false);const[note,setNote]=useState("");const[tagDialog,setTagDialog]=useState(false);const[formDialog,setFormDialog]=useState(false);const[toast,setToast]=useState("");const[importing,setImporting]=useState(false);const[openGroups,setOpenGroups]=useState<Record<string,boolean>>({});
const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(""),3500)};
const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({q:query,status});if(tagId)params.set("tag_id",tagId);const[list,s,t]=await Promise.all([api<Client[]>(`clients?${params}`),api<Stats>("clients/stats"),api<any[]>("clients/segments")]);setClients(list);setStats(s);setSegments(t);setOpenGroups({});if(view==="forms")setForms(await api<FormTemplate[]>("clients/forms"));if(view==="import")setDuplicates(await api<Duplicate[]>("clients/duplicates"));}catch(e:any){setError(e.message||"Nem sikerült betölteni az ügyfeleket.")}finally{setLoading(false)}},[query,status,tagId,view]);
useEffect(()=>{const timer=window.setTimeout(load,query?250:0);return()=>window.clearTimeout(timer)},[load,query]);
const groupedClients=useMemo(()=>{const map=new Map<string,Client[]>();for(const c of clients){const key=groupKey(c.name);if(!map.has(key))map.set(key,[]);map.get(key)!.push(c);}for(const arr of map.values())arr.sort((a,b)=>a.name.localeCompare(b.name,"hu-HU",{sensitivity:"base"}));return Array.from(map.entries()).sort(([a],[b])=>a.localeCompare(b,"hu-HU"));},[clients]);
const openDetail=async(id:string)=>{setDetailLoading(true);setError("");try{setDetail(await api<Detail>(`clients/${id}`))}catch(e:any){setError(e.message)}finally{setDetailLoading(false)}};
const saveClient=async(event:React.FormEvent)=>{event.preventDefault();try{const isEdit=Boolean(editor.id);const result=await api<{id:string}>(isEdit?`clients/${editor.id}`:"clients",{method:isEdit?"PATCH":"POST",body:JSON.stringify(editor)});setEditor(null);await load();notify(isEdit?"Ügyféladatok mentve.":"Új ügyfél létrehozva.");if(isEdit&&detail)openDetail(editor.id);else if(result.id&&view==="profiles")openDetail(result.id)}catch(e:any){setError(e.message)}};
const saveNote=async()=>{if(!detail||!note.trim())return;try{await api(`clients/${detail.client.id}/notes`,{method:"POST",body:JSON.stringify({note_text:note})});setNote("");await openDetail(detail.client.id);notify("Megjegyzés rögzítve.")}catch(e:any){setError(e.message)}};
const toggleTag=async(id:string)=>{if(!detail)return;const current=detail.tags.map(x=>x.id);const tag_ids=current.includes(id)?current.filter(x=>x!==id):[...current,id];try{await api(`clients/${detail.client.id}/tags`,{method:"PUT",body:JSON.stringify({tag_ids})});await openDetail(detail.client.id)}catch(e:any){setError(e.message)}};
const createTag=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const fd=new FormData(event.currentTarget);try{await api("clients/segments",{method:"POST",body:JSON.stringify({name:fd.get("name"),color:fd.get("color")})});setTagDialog(false);await load();notify("Új címke létrehozva.")}catch(e:any){setError(e.message)}};
const createForm=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const fd=new FormData(event.currentTarget);try{await api("clients/forms",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),form_type:fd.get("form_type")})});setFormDialog(false);await load();notify("Dokumentumsablon létrehozva.")}catch(e:any){setError(e.message)}};
const importAltegioXlsx=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;event.target.value="";if(!/\.xlsx$/i.test(file.name)){setError("Az Altegio ügyfélimporthoz .xlsx fájlt válassz.");return;}setImporting(true);setError("");try{const form=new FormData();form.append("file",file);const locationId=localStorage.getItem("kleo_location_id");if(locationId)form.append("location_id",locationId);const response=await fetch(withBase("clients/import-altegio-xlsx"),{method:"POST",credentials:"include",headers:{Authorization:`Bearer ${token()}`},body:form});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail?`${payload.error||"Importhiba"}: ${payload.detail}`:payload.error||`HTTP ${response.status}`);const result=payload as AltegioImportResult;await load();notify(`Altegio import kész: ${result.inserted} új, ${result.updated} frissített, ${result.skipped} kihagyott rekord.`);}catch(e:any){setError(e.message||"Az Altegio XLSX import nem sikerült.")}finally{setImporting(false)}};
const exportCsv=()=>{const rows=[["Név","Telefon","E-mail","Telephely","Látogatások"],...clients.map(c=>[c.name,c.phone||"",c.email||"",c.location_name||"",String(c.visits||0)])];const blob=new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="kleoszalon-ugyfelek.csv";a.click();URL.revokeObjectURL(a.href)};const currentTab=tabs.find(x=>x.key===view)||tabs[0];
return <main className="crm-page"><header className="crm-hero"><div><p className="crm-eyebrow">ÜGYFELEK ÉS CRM</p><h1>{currentTab.label}</h1><p>Egységes vendégadatok, kezelési előzmények és személyre szabott kapcsolattartás.</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}><label className="crm-secondary" style={{cursor:importing?"wait":"pointer",display:"inline-flex",alignItems:"center",gap:6,opacity:importing?.65:1}}><Upload size={17}/> {importing?"Altegio import folyamatban…":"Altegio XLSX import"}<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={importAltegioXlsx} disabled={importing} style={{display:"none"}}/></label><button className="crm-primary" onClick={()=>setEditor({...blankClient})}><Plus size={17}/> Új ügyfél</button></div></header><nav className="crm-tabs">{tabs.map(item=>{const Icon=item.icon;return <button key={item.key} className={view===item.key?"active":""} onClick={()=>navigate(`/modules/customers/${item.key}`)}><Icon size={16}/><span>{item.label}</span></button>})}</nav>{error&&<div className="crm-error"><span>{error}</span><button onClick={()=>setError("")}><X size={16}/></button></div>}<section className="crm-metrics"><article><Users/><div><span>Összes ügyfél</span><strong>{stats.total}</strong></div></article><article><Check/><div><span>Aktív vendég</span><strong>{stats.active}</strong></div></article><article><UserRound/><div><span>Új ebben a hónapban</span><strong>{stats.new_this_month}</strong></div></article><article><CalendarDays/><div><span>Meg nem jelenéssel</span><strong>{stats.with_no_show}</strong></div></article></section>
{(view==="list"||view==="profiles")&&<section className="crm-panel"><div className="crm-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Keresés név, telefon, város, cím vagy címke alapján…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Minden állapot</option><option value="active">Aktív</option><option value="inactive">Inaktív</option></select><select value={tagId} onChange={e=>setTagId(e.target.value)}><option value="">Minden címke</option>{segments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={load} aria-label="Frissítés"><RefreshCw size={16}/></button><button onClick={exportCsv}><Download size={16}/> Export</button></div><div className="crm-table"><div className="crm-table-head"><span>Ügyfél</span><span>Kapcsolat</span><span>Telephely</span><span>Aktivitás</span><span>Státusz</span><span/></div>{loading?<div className="crm-empty">Ügyféladatok betöltése…</div>:clients.length===0?<div className="crm-empty">Nincs a szűrésnek megfelelő ügyfél.</div>:groupedClients.map(([letter,items])=><div key={letter} className="crm-alpha-group"><button type="button" className="crm-alpha-header" onClick={()=>setOpenGroups(g=>({...g,[letter]:!g[letter]}))}><span>{openGroups[letter]?<ChevronDown size={17}/>:<ChevronRight size={17}/>}<b>{letter}</b><small>{items.length} ügyfél</small></span></button>{openGroups[letter]&&items.map(c=><button className="crm-row" key={c.id} onClick={()=>openDetail(c.id)}><span className="crm-person"><i>{initials(c.name)}</i><span><b>{c.name}</b><small>{c.tags?.map(t=>t.name).join(" · ")||"Nincs címke"}</small></span></span><span><b>{c.phone||"—"}</b><small>{c.email||"Nincs e-mail"}</small></span><span><b>{c.location_name||c.city||"Nincs megadva"}</b><small>{[c.city,c.address].filter(Boolean).join(" · ")||"—"}</small></span><span><b>{c.visits||0} látogatás</b><small>Utolsó: {fmtDate(c.last_visit)}</small></span><span><em className={c.is_active?"status-active":"status-inactive"}>{c.is_active?"Aktív":"Inaktív"}</em>{c.no_shows>0&&<small className="crm-warning">{c.no_shows} no-show</small>}</span><ChevronRight size={17}/></button>)}</div>)}</div></section>}
{view==="segments"&&<section className="crm-panel"><div className="crm-section-head"><div><h2>Címkék és ügyfélszegmensek</h2><p>A címkék az adatlapokon azonnal hozzárendelhetők.</p></div><button className="crm-secondary" onClick={()=>setTagDialog(true)}><Plus size={16}/> Új címke</button></div><div className="crm-card-grid">{segments.map((s:any)=><article className="crm-segment" key={s.id}><i style={{background:s.color}}/><div><h3>{s.name}</h3><p>{s.client_count||0} hozzárendelt ügyfél</p></div><strong>{s.client_count||0}</strong></article>)}</div></section>}
{view==="forms"&&<section className="crm-panel"><div className="crm-section-head"><div><h2>Kérdőívek és nyilatkozatok</h2><p>Egészségügyi állapotfelmérők és adatkezelési hozzájárulások.</p></div><button className="crm-secondary" onClick={()=>setFormDialog(true)}><Plus size={16}/> Új sablon</button></div><div className="crm-card-grid">{forms.map(f=><article className="crm-form-card" key={f.id}><div className="crm-form-icon"><ClipboardList size={20}/></div><div><span>{f.form_type==="consent"?"NYILATKOZAT":"KÉRDŐÍV"}</span><h3>{f.title}</h3><p>{f.description||"Nincs leírás."}</p><small>{f.response_count||0} kitöltés</small></div></article>)}</div></section>}
{view==="import"&&<section className="crm-import-grid"><article className="crm-panel crm-upload"><Upload size={30}/><h2>Altegio ügyfélimport</h2><p>Az Altegio rendszerből exportált <b>XLSX</b> ügyfélfájlt töltsd fel. A kategóriák ügyfélcímkékké válnak, a rendszer telefonszám/e-mail alapján frissíti a már meglévő vendéget.</p><label><FileSpreadsheet size={17}/> {importing?"Import folyamatban…":"Altegio XLSX kiválasztása"}<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={importAltegioXlsx} disabled={importing}/></label></article><article className="crm-panel"><div className="crm-section-head"><div><h2>Lehetséges duplikációk</h2><p>Azonos e-mail-cím vagy telefonszám alapján.</p></div><strong className="crm-duplicate-count">{duplicates.length}</strong></div>{duplicates.length===0?<div className="crm-empty">Nem találtunk összevonandó rekordot.</div>:duplicates.map((group,index)=><div className="crm-duplicate" key={index}><Merge size={18}/><div>{group.clients.map(c=><p key={c.id}><b>{c.name}</b> <span>{c.email||c.phone}</span></p>)}</div></div>)}</article></section>}
{(detail||detailLoading)&&<div className="crm-drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><aside className="crm-drawer">{detailLoading&&!detail?<div className="crm-empty">Adatlap betöltése…</div>:detail&&<><header><div className="crm-large-avatar">{initials(detail.client.display_name)}</div><div><p>ÜGYFÉLADATLAP</p><h2>{detail.client.display_name}</h2><span>{detail.client.location_name||"Nincs telephely"}</span></div><button onClick={()=>setDetail(null)}><X/></button></header><div className="crm-drawer-actions"><button onClick={()=>setEditor({id:detail.client.id,name:detail.client.display_name,phone:detail.client.phone||"",email:detail.client.email||"",location_id:detail.client.location_id||"",birth_date:detail.client.birth_date?.slice(0,10)||"",gender:detail.client.gender||"",city:detail.client.city||"",address:detail.client.address||"",notes:detail.client.notes||"",preferred_contact:detail.client.preferred_contact||"phone",marketing_consent:detail.client.marketing_consent,is_active:detail.client.is_active})}>Szerkesztés</button><a href={detail.client.phone?`tel:${detail.client.phone}`:undefined}><Phone size={15}/></a><a href={detail.client.email?`mailto:${detail.client.email}`:undefined}><Mail size={15}/></a></div><section className="crm-contact-grid"><div><Phone/><span>Telefon<b>{detail.client.phone||"—"}</b></span></div><div><Mail/><span>E-mail<b>{detail.client.email||"—"}</b></span></div><div><MapPin/><span>Cím<b>{[detail.client.city,detail.client.address].filter(Boolean).join(", ")||"—"}</b></span></div><div><CalendarDays/><span>Születési dátum<b>{fmtDate(detail.client.birth_date)}</b></span></div></section><ClientLoyaltyPanel customerId={String(detail.client.id)}/><section><h3>Címkék</h3><div className="crm-tag-picker">{segments.map(t=><button key={t.id} className={detail.tags.some(x=>x.id===t.id)?"selected":""} onClick={()=>toggleTag(t.id)} style={{"--tag-color":t.color} as React.CSSProperties}>{t.name}</button>)}</div></section><section><h3>Megjegyzések</h3><div className="crm-note-add"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Új belső megjegyzés…"/><button onClick={saveNote}><MessageSquarePlus size={16}/></button></div>{detail.notes.map(n=><article className="crm-note" key={n.id}><p>{n.note_text}</p><small>{n.created_by||"Rendszer"} · {fmtDate(n.created_at)}</small></article>)}</section><section><h3>Időpont- és kezelési előzmények</h3>{detail.appointments.length===0?<div className="crm-empty small">Nincs korábbi időpont.</div>:detail.appointments.map(a=><article className="crm-history" key={a.id}><i/><div><b>{a.title||"Szalon időpont"}</b><span>{a.employee_name||"Nincs munkatárs"} · {a.location_name||""}</span></div><time>{fmtDate(a.start_time)}</time><em>{a.status}</em></article>)}</section></>}</aside></div>}
{editor&&<div className="crm-modal-backdrop"><form className="crm-modal" onSubmit={saveClient}><header><div><p>{editor.id?"ÜGYFÉL SZERKESZTÉSE":"ÚJ ÜGYFÉL"}</p><h2>Személyes és kapcsolati adatok</h2></div><button type="button" onClick={()=>setEditor(null)}><X/></button></header><div className="crm-form-grid"><label className="wide">Teljes név *<input required value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label>Telefonszám<input value={editor.phone} onChange={e=>setEditor({...editor,phone:e.target.value})}/></label><label>E-mail<input type="email" value={editor.email} onChange={e=>setEditor({...editor,email:e.target.value})}/></label><label>Születési dátum<input type="date" value={editor.birth_date} onChange={e=>setEditor({...editor,birth_date:e.target.value})}/></label><label>Nem<select value={editor.gender} onChange={e=>setEditor({...editor,gender:e.target.value})}><option value="">Nincs megadva</option><option value="female">Nő</option><option value="male">Férfi</option><option value="other">Egyéb</option></select></label><label>Város<input value={editor.city||""} onChange={e=>setEditor({...editor,city:e.target.value})}/></label><label className="wide">Cím<input value={editor.address} onChange={e=>setEditor({...editor,address:e.target.value})}/></label><label>Elsődleges kapcsolat<select value={editor.preferred_contact} onChange={e=>setEditor({...editor,preferred_contact:e.target.value})}><option value="phone">Telefon</option><option value="email">E-mail</option><option value="sms">SMS</option></select></label><label className="check"><input type="checkbox" checked={editor.marketing_consent} onChange={e=>setEditor({...editor,marketing_consent:e.target.checked})}/> Marketinghozzájárulás</label><label className="wide">Belső megjegyzés<textarea value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})}/></label><label className="check"><input type="checkbox" checked={editor.is_active} onChange={e=>setEditor({...editor,is_active:e.target.checked})}/> Aktív ügyfél</label></div><footer><button type="button" onClick={()=>setEditor(null)}>Mégse</button><button className="crm-primary" type="submit"><Check size={16}/> Mentés</button></footer></form></div>}
{tagDialog&&<SimpleDialog title="Új ügyfélcímke" onClose={()=>setTagDialog(false)} onSubmit={createTag}><label>Címke neve<input name="name" required autoFocus/></label><label>Szín<input name="color" type="color" defaultValue="#7c5ce5"/></label></SimpleDialog>}{formDialog&&<SimpleDialog title="Új dokumentumsablon" onClose={()=>setFormDialog(false)} onSubmit={createForm}><label>Név<input name="title" required autoFocus/></label><label>Típus<select name="form_type"><option value="questionnaire">Kérdőív</option><option value="consent">Nyilatkozat</option></select></label><label>Leírás<textarea name="description"/></label></SimpleDialog>}{toast&&<div className="crm-toast"><Check size={16}/>{toast}</div>}</main>}
function SimpleDialog({title,onClose,onSubmit,children}:{title:string;onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;children:React.ReactNode}){return <div className="crm-modal-backdrop"><form className="crm-modal small-modal" onSubmit={onSubmit}><header><h2>{title}</h2><button type="button" onClick={onClose}><X/></button></header><div className="crm-form-grid one">{children}</div><footer><button type="button" onClick={onClose}>Mégse</button><button className="crm-primary" type="submit">Létrehozás</button></footer></form></div>}
