import React,{useEffect,useMemo,useState}from"react";
import axios from"axios";
import{Banknote,Bell,BrainCircuit,CalendarCheck2,Check,CheckCircle2,Clock3,Mail,MessageSquareText,MousePointerClick,PhoneCall,RefreshCw,Search,Send,ShieldCheck,Sparkles,TrendingUp,UserRoundCheck,UsersRound,WandSparkles,X}from"lucide-react";
import"./CustomerIntelligencePage.css";

const API_BASE=window.location.hostname==="localhost"||window.location.hostname==="127.0.0.1"?"http://localhost:5000/api":"https://kleoszalon-api-1.onrender.com/api";
type Recommendation={client_id:string;name:string;email?:string|null;phone?:string|null;visits:number;no_shows:number;last_visit?:string|null;next_visit?:string|null;lifetime_value:number;recency_days?:number|null;value_tier:"new"|"standard"|"loyal"|"vip";risk_level:"low"|"medium"|"high";action_code:string;action_title:string;action_reason:string;priority:number;suggested_channel:"email"|"sms"|"phone"|"in_app"|"none";marketing_allowed:boolean};
type Overview={ok:boolean;engine?:{version:string;explainable:boolean;automatic_sending:boolean};scope?:{tenant_id:string;tenant:string;location_id?:string|null};summary:{clients:number;high_priority:number;at_risk:number;vip:number;without_next_booking:number;marketing_blocked:number;potential_value:number};action_mix:Array<{action_code:string;title:string;count:number}>;rows:Recommendation[]};
type MarketingJob={id:string;client_id:string;action_code:string;channel:string;status:string;subject?:string|null;message:string;scheduled_at?:string|null;error?:string|null;created_at?:string};
type MarketingSettings={auto_dispatch:boolean;require_explicit_approval:boolean;default_channel:string;max_daily_dispatch:number};
type AttributionRow={action_code:string;channel:string;sent:number;conversions:number;expected_value:number;paid_revenue:number;conversion_rate_percent:number};
type AttributionSummary={period_days:number;sent_jobs:number;landed_jobs:number;attributed_bookings:number;expected_booking_value:number;paid_revenue:number;conversion_rate_percent:number;revenue_per_send:number;action_rows:AttributionRow[]};
type AutomationDraft={row:Recommendation;eventId:string;channel:"email"|"sms"|"push"|"callback";subject:string;message:string;scheduledAt:string;job?:MarketingJob|null;consent?:{allowed:boolean;reason?:string|null}|null};
const MARKETING_CODES=new Set(["FIRST_VISIT","WIN_BACK_60","REBOOK_30","VIP_RETENTION","BIRTHDAY_OFFER","CROSS_SELL","RELATIONSHIP_MAINTENANCE"]);
const auth=()=>{const token=localStorage.getItem("kleo_token")||localStorage.getItem("token");return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
const huf=(v:number)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
const date=(v?:string|null)=>v?new Intl.DateTimeFormat("hu-HU",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
const tier=(v:Recommendation["value_tier"])=>v==="vip"?"VIP":v==="loyal"?"Törzsvendég":v==="new"?"Új":"Normál";
const risk=(v:Recommendation["risk_level"])=>v==="high"?"Magas":v==="medium"?"Közepes":"Alacsony";
const channelLabel=(v:string)=>({email:"E-mail",sms:"SMS",phone:"Telefon",in_app:"VIR / személyes",none:"Nincs engedélyezett csatorna",push:"Push",callback:"Visszahívás"}[v]||v);
const jobStatus=(v:string)=>({draft:"Jóváhagyásra vár",approved:"Jóváhagyva",queued:"Küldésre kész",ready:"Visszahívásra kész",waiting_provider:"Push providerre vár",sent:"Elküldve",completed:"Lezárva",cancelled:"Törölve",failed:"Hibás",blocked:"Consent blokkolja"}[v]||v);

export default function CustomerIntelligencePage(){
 const[data,setData]=useState<Overview|null>(null),[jobs,setJobs]=useState<MarketingJob[]>([]),[settings,setSettings]=useState<MarketingSettings|null>(null),[attribution,setAttribution]=useState<AttributionSummary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[q,setQ]=useState(""),[onlyPriority,setOnlyPriority]=useState(false),[busy,setBusy]=useState(""),[automation,setAutomation]=useState<AutomationDraft|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const[o,j,s,a]=await Promise.all([axios.get(`${API_BASE}/clients/intelligence/overview?limit=500`,auth()),axios.get(`${API_BASE}/clients/intelligence/marketing/jobs`,auth()),axios.get(`${API_BASE}/clients/intelligence/marketing/settings`,auth()),axios.get(`${API_BASE}/clients/intelligence/attribution/summary?days=30`,auth()).catch(()=>({data:{summary:null}}))]);setData(o.data);setJobs(j.data?.rows||[]);setSettings(s.data?.settings||null);setAttribution(a.data?.summary||null)}catch(e:any){setError(e?.response?.data?.error||e?.message||"A Customer Intelligence nem tölthető be.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>{const needle=q.trim().toLowerCase();return(data?.rows||[]).filter(r=>(!onlyPriority||r.priority>=80)&&(!needle||r.name.toLowerCase().includes(needle)||(r.email||"").toLowerCase().includes(needle)||(r.phone||"").toLowerCase().includes(needle)||r.action_title.toLowerCase().includes(needle)))},[data,q,onlyPriority]);
 const record=async(row:Recommendation,status:"accepted"|"dismissed"|"completed")=>{setBusy(`${row.client_id}:${status}`);setError("");try{await axios.post(`${API_BASE}/clients/intelligence/actions`,{client_id:row.client_id,action_code:row.action_code,status,channel:row.suggested_channel},auth());setMessage(status==="accepted"?"Ajánlás elfogadva.":status==="completed"?"Ajánlás lezárva.":"Ajánlás elvetve.");await load()}catch(e:any){const changed=e?.response?.data?.code==="NBA_RECOMMENDATION_CHANGED";setError(changed?"Az ajánlás időközben megváltozott; a lista frissül.":e?.response?.data?.error||"A Next Best Action eseményt nem sikerült menteni.");if(changed)await load()}finally{setBusy("")}};
 const openAutomation=async(row:Recommendation)=>{setBusy(`${row.client_id}:automation`);setError("");setMessage("");try{const accepted=await axios.post(`${API_BASE}/clients/intelligence/actions`,{client_id:row.client_id,action_code:row.action_code,status:"accepted",channel:row.suggested_channel},auth());const preferred:AutomationDraft["channel"]=MARKETING_CODES.has(row.action_code)?(row.suggested_channel==="sms"?"sms":"email"):"callback";setAutomation({row,eventId:accepted.data.event.id,channel:preferred,subject:row.action_title,message:`Kedves ${row.name}! ${row.action_title}.`,scheduledAt:"",job:null,consent:null})}catch(e:any){setError(e?.response?.data?.error||"Az automatizálás nem indítható.")}finally{setBusy("")}};
 const createJob=async()=>{if(!automation)return;setBusy("automation-create");setError("");try{const r=await axios.post(`${API_BASE}/clients/intelligence/marketing/jobs`,{nba_event_id:automation.eventId,channel:automation.channel,subject:automation.subject,message:automation.message,scheduled_at:automation.scheduledAt||null},auth());setAutomation({...automation,job:r.data.job,consent:r.data.consent});setMessage(r.data?.consent?.allowed?"Marketing feladat létrejött; jóváhagyásra vár.":`A feladat létrejött, de blokkolt: ${r.data?.consent?.reason||"hozzájárulás hiányzik"}`);await load()}catch(e:any){setError(e?.response?.data?.error||"A marketing feladat nem hozható létre.")}finally{setBusy("")}};
 const jobAction=async(action:"approve"|"send"|"complete")=>{if(!automation?.job)return;setBusy(`automation-${action}`);setError("");try{const r=await axios.post(`${API_BASE}/clients/intelligence/marketing/jobs/${automation.job.id}/${action}`,{},auth());const job=r.data?.job||automation.job;setAutomation({...automation,job});setMessage(action==="approve"?`Jóváhagyva: ${jobStatus(job.status)}.`:action==="send"?`Küldési állapot: ${jobStatus(job.status)}.`:"Marketing feladat lezárva.");await load()}catch(e:any){setError(e?.response?.data?.error||"A marketing művelet nem hajtható végre.")}finally{setBusy("")}};
 if(loading&&!data)return <div className="ci-state"><RefreshCw className="ci-spin" size={22}/> Customer Intelligence betöltése…</div>;
 return <div className="ci-page">
  <header className="ci-hero"><div><div className="ci-kicker"><BrainCircuit size={18}/> Customer Intelligence v21</div><h1>NBA → Marketing → Foglalás → Bevétel</h1><p>Magyarázható ügyfélintelligencia zárt visszacsatolással: a marketing művelettől a tényleges online foglaláson át a munkalapon kifizetett bevételig.</p></div><button className="ci-refresh" onClick={()=>void load()}><RefreshCw size={17}/> Frissítés</button></header>
  {error&&<div className="ci-error">{error}</div>}{message&&<div className="ci-success"><CheckCircle2 size={17}/>{message}</div>}
  <section className="ci-cards"><article><UsersRound/><span>Elemzett vendég</span><strong>{data?.summary.clients||0}</strong></article><article><Sparkles/><span>Magas prioritás</span><strong>{data?.summary.high_priority||0}</strong></article><article><Clock3/><span>Magas lemorzsolódási kockázat</span><strong>{data?.summary.at_risk||0}</strong></article><article><UserRoundCheck/><span>VIP vendég</span><strong>{data?.summary.vip||0}</strong></article><article><ShieldCheck/><span>Marketing által blokkolt</span><strong>{data?.summary.marketing_blocked||0}</strong></article><article><BrainCircuit/><span>Becsült ügyfélérték</span><strong>{huf(data?.summary.potential_value||0)}</strong></article></section>
  <section className="ci-engine"><div><CheckCircle2 size={18}/><b>{data?.engine?.version||"nba-v1"}</b><span>magyarázható szabálymotor</span></div><div><ShieldCheck size={18}/><span>Automatikus küldés: <b>{settings?.auto_dispatch?"BE":"KI"}</b></span></div><div><CheckCircle2 size={18}/><span>Explicit jóváhagyás: <b>{settings?.require_explicit_approval===false?"KI":"BE"}</b></span></div><div><span>Napi limit: <b>{settings?.max_daily_dispatch||100}</b></span></div></section>
  {attribution&&<><section className="ci-job-panel"><div className="ci-job-head"><div><h2>Zárt marketing visszacsatolás · utolsó {attribution.period_days} nap</h2><p>A bevétel a tényleges <code>work_order_payments</code> tételekből származik; lemondott/no-show időpont nem számít konverziónak.</p></div><span>v21 attribution</span></div><section className="ci-cards"><article><Send/><span>Kiküldött NBA</span><strong>{attribution.sent_jobs}</strong></article><article><MousePointerClick/><span>Foglalási landing</span><strong>{attribution.landed_jobs}</strong></article><article><CalendarCheck2/><span>Attribútált foglalás</span><strong>{attribution.attributed_bookings}</strong></article><article><TrendingUp/><span>Konverzió</span><strong>{attribution.conversion_rate_percent.toLocaleString("hu-HU")}%</strong></article><article><Banknote/><span>Fizetett bevétel</span><strong>{huf(attribution.paid_revenue)}</strong></article><article><Banknote/><span>Bevétel / kiküldés</span><strong>{huf(attribution.revenue_per_send)}</strong></article></section></section>{attribution.action_rows?.length>0&&<div className="ci-table-wrap"><table className="ci-table"><thead><tr><th>NBA akció</th><th>Csatorna</th><th>Kiküldés</th><th>Foglalás</th><th>Konverzió</th><th>Foglalási érték</th><th>Fizetett bevétel</th></tr></thead><tbody>{attribution.action_rows.map(r=><tr key={`${r.action_code}:${r.channel}`}><td><b>{r.action_code}</b></td><td>{channelLabel(r.channel)}</td><td>{r.sent}</td><td>{r.conversions}</td><td>{r.conversion_rate_percent.toLocaleString("hu-HU")}%</td><td>{huf(r.expected_value)}</td><td><b>{huf(r.paid_revenue)}</b></td></tr>)}</tbody></table></div>}</>}
  <section className="ci-actionmix"><h2>Ajánlási mix</h2><div>{(data?.action_mix||[]).slice(0,8).map(x=><span key={x.action_code}><b>{x.count}</b> {x.title}</span>)}</div></section>
  <section className="ci-toolbar"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Vendég vagy ajánlás keresése…"/></label><button className={onlyPriority?"active":""} onClick={()=>setOnlyPriority(v=>!v)}><Sparkles size={16}/> Csak 80+ prioritás</button><span>{rows.length} találat</span></section>
  <div className="ci-table-wrap"><table className="ci-table"><thead><tr><th>Prioritás</th><th>Vendég</th><th>Érték / kockázat</th><th>Utolsó / következő</th><th>Next Best Action</th><th>Csatorna</th><th>Művelet</th></tr></thead><tbody>{rows.map(row=><tr key={row.client_id}><td><span className={`ci-priority p${row.priority>=80?"high":row.priority>=60?"mid":"low"}`}>{row.priority}</span></td><td><b>{row.name}</b><small>{row.visits} látogatás · {row.no_shows} no-show</small></td><td><b>{huf(row.lifetime_value)}</b><small>{tier(row.value_tier)} · {risk(row.risk_level)} kockázat</small></td><td><span>{date(row.last_visit)}</span><small>Következő: {date(row.next_visit)}</small></td><td className="ci-action-cell"><b>{row.action_title}</b><small>{row.action_reason}</small></td><td><span className={row.marketing_allowed?"ci-channel":"ci-channel blocked"}>{channelLabel(row.suggested_channel)}</span></td><td><div className="ci-buttons"><button title="Marketing automatika" className="automation" disabled={!!busy} onClick={()=>void openAutomation(row)}><WandSparkles size={15}/></button><button title="Elfogadom" disabled={!!busy} onClick={()=>void record(row,"accepted")}><Check size={15}/></button><button title="Elvégezve" disabled={!!busy} onClick={()=>void record(row,"completed")}><CheckCircle2 size={15}/></button><button title="Elvetem" disabled={!!busy} onClick={()=>void record(row,"dismissed")}><X size={15}/></button></div></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="ci-empty">Nincs a szűrésnek megfelelő ajánlás.</td></tr>}</tbody></table></div>
  <section className="ci-job-panel"><div className="ci-job-head"><div><h2>Marketing Automation sor</h2><p>Az NBA-ból létrehozott feladatok és kampány-attribúció.</p></div><span>{jobs.length} feladat</span></div><div className="ci-job-list">{jobs.slice(0,20).map(j=><div key={j.id}><span className={`ci-job-status ${j.status}`}>{jobStatus(j.status)}</span><strong>{j.action_code}</strong><span>{channelLabel(j.channel)}</span><small>{j.error||date(j.created_at)}</small></div>)}{!jobs.length&&<p>Még nincs NBA marketing feladat.</p>}</div></section>
  {automation&&<div className="ci-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAutomation(null)}}><div className="ci-modal"><div className="ci-modal-head"><div><span><WandSparkles size={17}/> NBA → Marketing Automation</span><h2>{automation.row.name}</h2><p>{automation.row.action_title}</p></div><button onClick={()=>setAutomation(null)}><X/></button></div><div className="ci-channel-grid"><button className={automation.channel==="email"?"active":""} onClick={()=>setAutomation({...automation,channel:"email"})}><Mail/>E-mail</button><button className={automation.channel==="sms"?"active":""} onClick={()=>setAutomation({...automation,channel:"sms"})}><MessageSquareText/>SMS</button><button className={automation.channel==="push"?"active":""} onClick={()=>setAutomation({...automation,channel:"push"})}><Bell/>Push</button><button className={automation.channel==="callback"?"active":""} onClick={()=>setAutomation({...automation,channel:"callback"})}><PhoneCall/>Visszahívás</button></div><label>Tárgy<input value={automation.subject} onChange={e=>setAutomation({...automation,subject:e.target.value})}/></label><label>Üzenet<textarea rows={5} value={automation.message} onChange={e=>setAutomation({...automation,message:e.target.value})}/></label><label>Ütemezés – opcionális<input type="datetime-local" value={automation.scheduledAt} onChange={e=>setAutomation({...automation,scheduledAt:e.target.value})}/></label>{automation.consent&&<div className={automation.consent.allowed?"ci-consent ok":"ci-consent blocked"}><ShieldCheck size={17}/>{automation.consent.allowed?"Consent ellenőrzés: rendben":automation.consent.reason||"A küldés blokkolt."}</div>}{automation.job&&<div className="ci-job-created"><b>{jobStatus(automation.job.status)}</b>{automation.job.error&&<span>{automation.job.error}</span>}</div>}<div className="ci-modal-actions">{!automation.job&&<button className="primary" disabled={!!busy} onClick={()=>void createJob()}><WandSparkles size={17}/> Feladat létrehozása</button>}{automation.job?.status==="draft"&&<button className="primary" disabled={!!busy} onClick={()=>void jobAction("approve")}><Check size={17}/> Jóváhagyás</button>}{["approved","queued"].includes(automation.job?.status||"")&&<button className="primary" disabled={!!busy} onClick={()=>void jobAction("send")}><Send size={17}/> Küldés most</button>}{["ready","sent","waiting_provider"].includes(automation.job?.status||"")&&<button className="primary" disabled={!!busy} onClick={()=>void jobAction("complete")}><CheckCircle2 size={17}/> Lezárás</button>}</div><small className="ci-modal-note">E-mail/SMS küldéskor a backend újra ellenőrzi a hozzájárulást. Push provider hiányában a feladat nem küldődik ki, hanem várakozó állapotba kerül.</small></div></div>}
 </div>;
}