import React,{useCallback,useEffect,useMemo,useState}from"react";
import{Award,CalendarDays,CalendarPlus,ChevronRight,Clock3,Gift,MapPin,Percent,Settings2,Sparkles,TicketCheck,WalletCards}from"lucide-react";
import{useNavigate}from"react-router-dom";
import api from"../api/api";
import WorkOrderDashboardWidget from"./dashboard/WorkOrderDashboardWidget";
import CustomerProfileModal from"./customer/CustomerProfileModal";
import CustomerAppointmentManageModal,{CustomerManagedAppointment}from"./customer/CustomerAppointmentManageModal";
import"./CustomerDashboardPage.css";

type Pass={id:string;pass_type_name:string;valid_until?:string|null;remaining_units:number|string;original_units:number|string;services?:Array<{service_name:string;remaining_quantity:number|string}>};
type Discount={campaign_id:string;name:string;discount_type:string;discount_value:number|string;valid_until?:string|null;code?:string|null};
type Promotion={kind:"discount"|"service"|string;title:string;discount_type?:string;discount_value?:number;valid_until?:string|null;code?:string|null;regular_price?:number;promo_price?:number;category_name?:string};
type Data={customer:{full_name:string;email?:string|null};account:{balance:number;points:number;card_identifier?:string|null};loyalty_program?:{tier_name?:string;color?:string;discount_percent?:number;paid_total?:number;amount_to_next_tier?:number};passes:Pass[];discounts:Discount[];promotions:Promotion[]};
const money=(v:unknown)=>`${Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:0})} Ft`;
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("hu-HU",{year:"numeric",month:"short",day:"numeric"}):"Nincs lejárat";
const datetime=(v:string)=>new Date(v).toLocaleString("hu-HU",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});

export default function CustomerDashboardPage(){
 const navigate=useNavigate();
 const[data,setData]=useState<Data|null>(null),[appointments,setAppointments]=useState<CustomerManagedAppointment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[profileOpen,setProfileOpen]=useState(false),[managed,setManaged]=useState<CustomerManagedAppointment|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[d,a]=await Promise.all([api.get<Data>("/customer-portal/dashboard"),api.get<CustomerManagedAppointment[]>("/customer-portal/self-service/appointments")]);setData(d.data);setAppointments(Array.isArray(a.data)?a.data:[])}catch(e:any){setError(e?.response?.data?.error||e?.message||"Az ügyféladatok nem tölthetők be.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const activePasses=data?.passes?.length||0,discountCount=data?.discounts?.length||0;
 const headline=useMemo(()=>data?.customer?.full_name?`Üdvözlünk, ${data.customer.full_name}!`:"Üdvözlünk!",[data?.customer?.full_name]);
 if(loading&&!data)return <main className="customer-dashboard"><div className="customer-loading">Ügyfélfiók betöltése…</div></main>;
 if(error&&!data)return <main className="customer-dashboard"><div className="customer-error">{error}</div></main>;
 if(!data)return null;
 return <main className="customer-dashboard">
  <header className="customer-hero"><div><span>SAJÁT ÜGYFÉLFIÓK</span><h1>{headline}</h1><p>Itt látod az egyenlegedet, bérleteidet, kedvezményeidet, időpontjaidat és a saját munkalapjaidat.</p></div><div className="customer-hero-actions"><button onClick={()=>setProfileOpen(true)}><Settings2/> Adataim és értesítéseim</button><button onClick={()=>navigate("/customer/booking")}><CalendarPlus/> Új bejelentkezés</button></div></header>
  {error&&<div className="customer-error-inline">{error}</div>}
  <WorkOrderDashboardWidget/>
  <section className="customer-kpis"><article><Award style={{color:data.loyalty_program?.color}}/><div><small>Törzsvásárlói szint</small><strong>{data.loyalty_program?.tier_name||"Normál"}</strong><span>{data.loyalty_program?.discount_percent?`${Number(data.loyalty_program.discount_percent)}% automatikus kedvezmény`:data.loyalty_program?.amount_to_next_tier?`${money(data.loyalty_program.amount_to_next_tier)} a következő szintig`:"Gyűjts látogatásokat"}</span></div></article><article><WalletCards/><div><small>Felhasználható egyenleg</small><strong>{money(data.account.balance)}</strong><span>{data.account.card_identifier||"Kleopátra ügyfélegyenleg"}</span></div></article><article><Sparkles/><div><small>Hűségpontok</small><strong>{Number(data.account.points||0).toLocaleString("hu-HU")}</strong><span>Aktuális pontállomány</span></div></article><article><TicketCheck/><div><small>Aktív bérletek</small><strong>{activePasses}</strong><span>{activePasses?"Felhasználható bérletek":"Nincs aktív bérlet"}</span></div></article><article><Percent/><div><small>Kedvezmények</small><strong>{discountCount}</strong><span>{discountCount?"Jelenleg elérhető":"Nincs aktív kedvezmény"}</span></div></article></section>
  <section className="customer-grid"><article className="customer-panel customer-next"><header><div><span>KÖVETKEZŐ IDŐPONTOK</span><h2>Bejelentkezéseim</h2></div><button onClick={()=>navigate("/customer/booking")}>Új időpont <ChevronRight/></button></header>{appointments.length?<div className="customer-appointment-list">{appointments.map(a=><div key={a.id}><CalendarDays/><div><b>{a.services?.length?a.services.map(s=>s.name).join(" + "):a.title}</b><span><Clock3/>{datetime(a.start_time)}{a.employee_name?` · ${a.employee_name}`:""}</span>{a.location_name&&<small><MapPin/>{a.location_name}</small>}</div><div className="customer-appointment-actions"><em>{a.status}</em><button onClick={()=>setManaged(a)}>Áthelyezés / lemondás</button></div></div>)}</div>:<div className="customer-empty">Nincs közelgő időpontod.</div>}</article><article className="customer-panel"><header><div><span>BÉRLETEK</span><h2>Aktív bérleteim</h2></div><Gift/></header>{data.passes?.length?<div className="customer-pass-list">{data.passes.map(p=><div key={p.id}><div><b>{p.pass_type_name}</b><span>Érvényes: {date(p.valid_until)}</span></div><strong>{Number(p.remaining_units||0).toLocaleString("hu-HU")}<small> / {Number(p.original_units||0).toLocaleString("hu-HU")} egység</small></strong>{p.services?.length?<p>{p.services.map(s=>`${s.service_name}: ${Number(s.remaining_quantity||0).toLocaleString("hu-HU")}`).join(" · ")}</p>:null}</div>)}</div>:<div className="customer-empty">Jelenleg nincs aktív bérleted.</div>}</article></section>
  <section className="customer-grid"><article className="customer-panel"><header><div><span>KEDVEZMÉNYEIM</span><h2>Aktív kedvezmények</h2></div><Percent/></header>{data.discounts?.length?<div className="customer-discount-list">{data.discounts.map(d=><div key={`${d.campaign_id}-${d.code||"global"}`}><span>{d.discount_type==="percent"?`${Number(d.discount_value)}%`:money(d.discount_value)}</span><div><b>{d.name}</b><small>{d.code?`Kód: ${d.code} · `:""}Érvényes: {date(d.valid_until)}</small></div></div>)}</div>:<div className="customer-empty">Nincs aktív személyes kedvezményed.</div>}</article><article className="customer-panel customer-promos"><header><div><span>AKTUÁLIS AKCIÓK</span><h2>Most érdemes kihasználni</h2></div><Sparkles/></header>{data.promotions?.length?<div className="customer-promo-scroll">{data.promotions.map((p,i)=><div key={`${p.kind}-${p.title}-${i}`}><b>{p.title}</b>{p.kind==="service"?<><strong>{money(p.promo_price)}</strong><small>{p.regular_price?`Eredeti ár: ${money(p.regular_price)}`:"Akciós szolgáltatás"}</small></>:<><strong>{p.discount_type==="percent"?`${Number(p.discount_value||0)}% kedvezmény`:money(p.discount_value)}</strong><small>{p.code?`Kód: ${p.code}`:`Érvényes: ${date(p.valid_until)}`}</small></>}</div>)}</div>:<div className="customer-empty">Jelenleg nincs kiemelt akció.</div>}</article></section>
  {profileOpen&&<CustomerProfileModal onClose={()=>setProfileOpen(false)} onSaved={()=>void load()}/>} {managed&&<CustomerAppointmentManageModal appointment={managed} onClose={()=>setManaged(null)} onChanged={()=>void load()}/>} 
 </main>;
}
