import React,{useEffect,useMemo,useState}from"react";
import{useNavigate,useParams}from"react-router-dom";
import{CalendarDays,ChevronLeft,ClipboardPlus,Settings2,UserRound}from"lucide-react";
import withBase from"../utils/apiBase";
import{apiFetch}from"../utils/api";
import{EmployeeDetailsCard}from"./EmployeeDetails";

type Employee={id:string;full_name?:string|null;email?:string|null;phone?:string|null;qualification?:string|null;location_id?:string|null;location_name?:string|null;position_name?:string|null;active?:boolean;photo_url?:string|null};
type Service={id:string;name:string;base_price?:number;price?:number;base_duration_minutes?:number;duration_minutes?:number};
type Appointment={id:string;employee_id?:string|null;client_name?:string|null;title?:string|null;start_time:string;end_time:string;status?:string|null;service_names?:string[]|null};
const token=()=>localStorage.getItem("kleo_token")||localStorage.getItem("token")||"";
const arr=<T,>(raw:any):T[]=>Array.isArray(raw)?raw:Array.isArray(raw?.items)?raw.items:Array.isArray(raw?.data)?raw.data:[];
const dateIso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export default function EmployeeWorkContextPage(){const{id}=useParams<{id:string}>();const navigate=useNavigate();const[employee,setEmployee]=useState<Employee|null>(null);const[services,setServices]=useState<Service[]>([]);const[appointments,setAppointments]=useState<Appointment[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[edit,setEdit]=useState(false);
 useEffect(()=>{if(!id)return;let alive=true;(async()=>{setLoading(true);setError("");try{const res=await fetch(withBase(`employees/${id}`),{headers:{Authorization:`Bearer ${token()}`},credentials:"include"});const emp=await res.json();if(!res.ok)throw new Error(emp?.error||"A munkatárs nem tölthető be.");if(!alive)return;setEmployee(emp);const end=new Date();end.setDate(end.getDate()+14);const tasks:Promise<any>[]=[apiFetch(`/api/timetable?from=${dateIso(new Date())}&to=${dateIso(end)}${emp.location_id?`&location_id=${encodeURIComponent(emp.location_id)}`:""}`)];if(emp.location_id)tasks.push(apiFetch(`/api/services-available?location_id=${encodeURIComponent(emp.location_id)}&employee_id=${encodeURIComponent(id)}`));const out=await Promise.allSettled(tasks);if(!alive)return;const tt=out[0].status==="fulfilled"?out[0].value:null;setAppointments(arr<Appointment>((tt as any)?.appointments).filter(a=>String(a.employee_id||"")===String(id)).sort((a,b)=>+new Date(a.start_time)-+new Date(b.start_time)));if(out[1]?.status==="fulfilled")setServices(arr<Service>((out[1] as PromiseFulfilledResult<any>).value?.services));}catch(e:any){if(alive)setError(e?.message||"A munkatárs operatív adatlapja nem tölthető be.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[id]);
 const activeAppointments=useMemo(()=>appointments.filter(a=>!["cancelled","canceled","no_show","completed"].includes(String(a.status||"").toLowerCase())),[appointments]);if(!id)return null;if(edit)return <EmployeeDetailsCard employeeId={id} onClose={()=>setEdit(false)}/>;if(loading)return <main style={{padding:24}}>Betöltés…</main>;if(error)return <main style={{padding:24}}><button onClick={()=>navigate(-1)}>← Vissza</button><p>{error}</p></main>;if(!employee)return null;
 return <main style={{padding:24,maxWidth:1450,margin:0}}><header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",marginBottom:18}}><div style={{display:"flex",gap:14,alignItems:"center"}}><button onClick={()=>navigate(-1)} style={{border:0,background:"transparent"}}><ChevronLeft/></button><div style={{width:58,height:58,borderRadius:"50%",overflow:"hidden",background:"#eee",display:"grid",placeItems:"center"}}>{employee.photo_url?<img src={employee.photo_url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<UserRound/>}</div><div><h1 style={{margin:0}}>{employee.full_name||"Munkatárs"}</h1><p style={{margin:"4px 0 0",color:"#666"}}>{employee.position_name||employee.qualification||"Munkatárs"} · {employee.location_name||"Szalon"}</p></div></div><button onClick={()=>setEdit(true)} style={{padding:"10px 14px",border:"1px solid #ddd",background:"white",borderRadius:10}}><Settings2 size={16}/> HR / jogosultságok</button></header>
 <section style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(320px,.8fr)",gap:16}}><article style={{border:"1px solid #e7e2e9",borderRadius:14,background:"white",overflow:"hidden"}}><header style={{padding:15,borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between"}}><div><b>Hozzárendelt szolgáltatások</b><small style={{display:"block",color:"#777"}}>Ezek választhatók a munkatárshoz foglaláskor és munkalapon.</small></div><span>{services.length} db</span></header><div style={{padding:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:9}}>{services.length?services.map(s=><div key={s.id} style={{padding:12,border:"1px solid #eee",borderRadius:10}}><strong>{s.name}</strong><small style={{display:"block",marginTop:5,color:"#777"}}>{Number(s.base_duration_minutes||s.duration_minutes||30)} perc · {Number(s.base_price||s.price||0).toLocaleString("hu-HU")} Ft</small></div>):<p style={{color:"#777"}}>Nincs külön szolgáltatás-hozzárendelés. A munkatárs törzsadatait ellenőrizni kell.</p>}</div></article>
 <aside style={{display:"grid",gap:12,alignContent:"start"}}><button onClick={()=>navigate(`/workorders/new?employee_id=${encodeURIComponent(id)}`)} style={{padding:16,textAlign:"left",border:0,borderRadius:12,background:"#765d85",color:"white"}}><ClipboardPlus/><strong style={{display:"block",marginTop:7}}>Új munkalap ezzel a munkatárssal</strong></button><button onClick={()=>navigate("/appointments/calendar")} style={{padding:16,textAlign:"left",border:"1px solid #ddd",borderRadius:12,background:"white"}}><CalendarDays/><strong style={{display:"block",marginTop:7}}>Naptár megnyitása</strong></button><div style={{padding:15,border:"1px solid #e7e2e9",borderRadius:12,background:"white"}}><b>Kapcsolat</b><div style={{marginTop:8,fontSize:13}}>{employee.phone||"—"}</div><div style={{fontSize:13}}>{employee.email||"—"}</div></div></aside></section>
 <section style={{marginTop:16,border:"1px solid #e7e2e9",borderRadius:14,background:"white",overflow:"hidden"}}><header style={{padding:15,borderBottom:"1px solid #eee"}}><b>Következő 14 nap időpontjai</b> · {activeAppointments.length} aktív</header>{activeAppointments.length?activeAppointments.slice(0,30).map(a=><div key={a.id} style={{display:"grid",gridTemplateColumns:"150px minmax(180px,1fr) minmax(180px,1fr) auto",gap:12,padding:"11px 15px",borderBottom:"1px solid #f2eff3",alignItems:"center"}}><b>{new Date(a.start_time).toLocaleString("hu-HU",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</b><span>{a.client_name||"Vendég"}</span><span>{a.service_names?.join(", ")||a.title||"Szolgáltatás"}</span><button onClick={()=>navigate(`/workorders/new?appointment_id=${encodeURIComponent(a.id)}`)} style={{padding:"7px 10px",border:"1px solid #ddd",borderRadius:9,background:"white"}}>Munkalap</button></div>):<div style={{padding:18,color:"#777"}}>Nincs következő időpont.</div>}</section></main>}
