import React,{useEffect,useState}from"react";
import axios from"axios";
import{BookOpenText,CalendarDays,CheckCircle2,Clock3,LogIn,MessageCircle,RefreshCw,UserRound,WalletCards}from"lucide-react";
import"./EmployeeMobileApp.css";
const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const token=()=>localStorage.getItem('kleo_token')||localStorage.getItem('token');
const cfg=()=>({withCredentials:true,headers:token()?{Authorization:`Bearer ${token()}`}:{}});
export default function EmployeeMobileApp(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let link=document.querySelector('link[data-employee-manifest]') as HTMLLinkElement|null;if(!link){link=document.createElement('link');link.rel='manifest';link.href='/employee-manifest.webmanifest';link.setAttribute('data-employee-manifest','1');document.head.appendChild(link)}if('serviceWorker'in navigator)navigator.serviceWorker.register('/employee-sw.js',{scope:'/employee-app'}).catch(()=>{});void load();return()=>{}},[]);
 async function load(){if(!token())return;setLoading(true);setError('');try{const r=await axios.get(`${API_BASE}/employee-self/dashboard`,cfg());setData(r.data)}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||e?.message||'Betöltési hiba.')}finally{setLoading(false)}}
 if(!token())return <main className="ema-login"><section><div className="ema-logo">K</div><div className="ema-kicker">KLEOPÁTRA • DOLGOZÓI APP</div><h1>Munkatársi mobilalkalmazás</h1><p>A dolgozói alkalmazás külön belépési ponttal működik. Jelentkezzen be a VIR azonosítójával.</p><a href="/login"><LogIn size={18}/>Bejelentkezés</a></section></main>;
 const e=data?.employee||{},leave=data?.leave||{},attendance=data?.attendance||{},shifts=data?.upcoming_shifts||[];
 return <main className="ema-page"><header><div><div className="ema-kicker">KLEOPÁTRA • DOLGOZÓI APP</div><h1>Szia, {String(e.full_name||'Kolléga').split(' ')[0]}!</h1><p>{e.position_name||'Munkatárs'} • {e.location_name||'Saját szalon'}</p></div><button onClick={load} disabled={loading}><RefreshCw size={17}/></button></header>{error&&<div className="ema-error">{error}</div>}
 <section className="ema-cards"><Card icon={CalendarDays} label="Ledolgozott nap / hó" value={attendance.worked_days_month??'—'}/><Card icon={WalletCards} label="Maradék szabadság" value={`${leave.remaining_days??'—'} nap`}/><Card icon={Clock3} label="Túlóra / év" value={`${Math.round(Number(attendance.overtime_minutes_year||0)/60)} óra`}/></section>
 <nav className="ema-quick"><a href="/modules/team/timetable"><CalendarDays/>Beosztás</a><a href="/staff/chat"><MessageCircle/>Belső chat</a><a href="/knowledge-base/library"><BookOpenText/>Tudástár</a><a href="/knowledge-base/checklists"><CheckCircle2/>Check listák</a></nav>
 <section className="ema-section"><div className="ema-section-title"><h2>Következő műszakok</h2><a href="/modules/team/timetable">Teljes naptár</a></div>{shifts.length?<div className="ema-shifts">{shifts.map((s:any)=><article key={s.id}><div className="ema-date"><b>{new Date(s.work_date).toLocaleDateString('hu-HU',{weekday:'short'})}</b><span>{new Date(s.work_date).toLocaleDateString('hu-HU',{month:'short',day:'numeric'})}</span></div><div><b>{String(s.starts_at||'').slice(0,5)} – {String(s.ends_at||'').slice(0,5)}</b><span>{s.shift_type||'Normál műszak'}{s.is_training?' • képzés':''}</span></div></article>)}</div>:<div className="ema-empty">Nincs rögzített műszak a következő 14 napra.</div>}</section>
 <section className="ema-section"><div className="ema-section-title"><h2>Szabadság</h2></div><div className="ema-leave"><div><span>Éves keret</span><b>{leave.entitlement_days??20} nap</b></div><div><span>Kivett</span><b>{leave.taken_days??0} nap</b></div><div><span>Függőben</span><b>{leave.pending_days??0} nap</b></div><div className="strong"><span>Maradék</span><b>{leave.remaining_days??'—'} nap</b></div></div></section>
 <footer><UserRound size={16}/><span>{e.full_name||e.email||'Munkatársi fiók'}</span><a href="/">VIR megnyitása</a></footer></main>
}
function Card({icon:I,label,value}:{icon:any,label:string,value:any}){return <article><I size={19}/><small>{label}</small><b>{value}</b></article>}
