import{useCallback,useEffect,useState}from'react';
import{AlertTriangle,ArrowLeft,BrainCircuit,CheckCircle2,Clock3,GitMerge,Mail,Network,RefreshCw,Route,Save,ShieldAlert,Siren,Target,TrendingUp,Users}from'lucide-react';
import{CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{useNavigate}from'react-router-dom';
import api from'../api';
import'./ExceptionIntelligencePage.css';

const BASE='/api/transactions/notifications/exceptions';
type Rule={severity:string;level1_after_minutes:number;level2_after_minutes:number;level3_after_minutes:number;active:boolean};
const fmt=(v:any)=>v==null?'—':Number(v).toLocaleString('hu-HU');
const minutes=(v:any)=>{const m=Number(v);if(!Number.isFinite(m))return'—';if(m<60)return`${Math.round(m)} p`;if(m<1440)return`${Math.floor(m/60)} ó ${Math.round(m%60)} p`;return`${Math.floor(m/1440)} n ${Math.floor((m%1440)/60)} ó`};
const dateTime=(v:any)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const sevHu:Record<string,string>={critical:'KRITIKUS',high:'MAGAS',medium:'KÖZEPES',low:'ALACSONY'};
const catHu:Record<string,string>={finance:'Pénzügy',nav:'NAV',inventory:'Készlet',procurement:'Beszerzés',cashier:'Pénztár',payroll:'Bérszámfejtés',communications:'Kommunikáció',complaints:'Panasz',trace:'Trace',system:'Rendszer',process:'Folyamatintegritás',assets:'Tárgyi eszköz'};

export default function ExceptionIntelligencePage(){
 const navigate=useNavigate();const[days,setDays]=useState(30),[data,setData]=useState<any>(null),[rules,setRules]=useState<Rule[]>([]),[loading,setLoading]=useState(false),[running,setRunning]=useState(false),[briefing,setBriefing]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const locationId=localStorage.getItem('kleo_location_id')||'';
 const load=useCallback(async()=>{setLoading(true);setError('');try{const q=new URLSearchParams({days:String(days)});if(locationId)q.set('location_id',locationId);const[a,b]=await Promise.all([api.get(`${BASE}/intelligence/dashboard?${q.toString()}`),api.get(`${BASE}/intelligence/escalation-rules`)]);setData(a.data);setRules(b.data?.items||[])}catch(e:any){setError(e?.response?.data?.message||'Az Exception Intelligence nem tölthető be.')}finally{setLoading(false)}},[days,locationId]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const t=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(t)},[load]);
 async function run(){setRunning(true);setError('');try{const r=await api.post(`${BASE}/intelligence/run`);setNotice(`Intelligence ciklus kész: ${r.data?.escalations?.escalated||0} új eszkaláció, ${r.data?.clusters?.active_clusters||0} aktív root-cause klaszter.`);await load()}catch(e:any){setError(e?.response?.data?.message||'Az Intelligence ciklus nem futtatható.')}finally{setRunning(false)}}
 async function brief(type:'morning'|'evening'){setBriefing(type);setError('');try{const r=await api.post(`${BASE}/intelligence/brief/${type}`);setNotice(`${type==='morning'?'Reggeli':'Esti'} vezetői brief: ${r.data?.sent||0} elküldve, ${r.data?.logged||0} naplózva.`)}catch(e:any){setError(e?.response?.data?.message||'A vezetői brief nem küldhető.')}finally{setBriefing('')}}
 async function saveRule(rule:Rule){try{await api.put(`${BASE}/intelligence/escalation-rules/${rule.severity}`,rule);setNotice(`${sevHu[rule.severity]||rule.severity} eszkalációs szabály mentve.`);await load()}catch(e:any){setError(e?.response?.data?.message||'Az eszkalációs szabály nem menthető.')}}
 const health=data?.health||{};
 return <div className="eip-page">
  <header className="eip-hero"><div><button className="eip-back" onClick={()=>navigate('/finance/exception-command-center')}><ArrowLeft/> Command Center</button><span>STATISZTIKA ÉS VIR · ROOT-CAUSE / ESCALATION ANALYTICS</span><h1><Network/> Exception Intelligence</h1><p>Automatikus eszkaláció, visszatérési minták, többmodulos gyökérok-korreláció, SLA teljesítmény és vezetői trendkontroll.</p></div><div className={`eip-score ${health.status||'ok'}`}><small>EXCEPTION HEALTH SCORE</small><b>{health.score??'—'}</b><span>/ 100</span><em>{health.status==='critical'?'KRITIKUS':health.status==='warning'?'FIGYELMEZTETÉS':'RENDBEN'}</em></div></header>
  <div className="eip-toolbar"><div className="eip-period"><button className={days===7?'active':''} onClick={()=>setDays(7)}>7 nap</button><button className={days===30?'active':''} onClick={()=>setDays(30)}>30 nap</button><button className={days===90?'active':''} onClick={()=>setDays(90)}>90 nap</button></div><button onClick={run} disabled={running}><RefreshCw className={running?'spin':''}/>{running?'Elemzés…':'Intelligence ciklus'}</button><button onClick={()=>brief('morning')} disabled={Boolean(briefing)}><Mail/>{briefing==='morning'?'Küldés…':'Reggeli brief'}</button><button onClick={()=>brief('evening')} disabled={Boolean(briefing)}><Mail/>{briefing==='evening'?'Küldés…':'Esti brief'}</button></div>
  {error&&<div className="eip-error"><AlertTriangle/>{error}</div>}{notice&&<div className="eip-notice"><CheckCircle2/>{notice}</div>}
  {loading&&!data&&<div className="eip-loading"><RefreshCw className="spin"/> Exception Intelligence betöltése…</div>}
  {data&&<>
   <section className="eip-kpis">
    <article className={Number(health.critical)>0?'danger':''}><ShieldAlert/><div><small>Kritikus aktív</small><b>{fmt(health.critical)}</b><span>azonnali vezetői figyelem</span></div></article>
    <article className={Number(health.breached)>0?'danger':''}><Clock3/><div><small>SLA sértett</small><b>{fmt(health.breached)}</b><span>kapacitás / routing kockázat</span></div></article>
    <article><GitMerge/><div><small>Root-cause klaszter</small><b>{fmt(health.active_clusters)}</b><span>összefüggő eltéréscsoport</span></div></article>
    <article><TrendingUp/><div><small>Ismétlődési esemény</small><b>{fmt(health.recurrence_events)}</b><span>CAPA jelölt</span></div></article>
    <article className={Number(health.unassigned)>0?'warning':''}><Users/><div><small>Kiosztatlan</small><b>{fmt(health.unassigned)}</b><span>konkrét felelős nélkül</span></div></article>
    <article><Siren/><div><small>Aktív ügy</small><b>{fmt(health.active)}</b><span>teljes Exception work queue</span></div></article>
   </section>
   <section className="eip-grid two"><article className="eip-card trend"><header><div><h2><TrendingUp/> Exception trend</h2><p>Új, lezárt, kritikus és SLA-sértett ügyek napi alakulása.</p></div></header><div className="eip-chart"><ResponsiveContainer width="100%" height={310}><LineChart data={data.trend||[]} margin={{top:10,right:12,left:-18,bottom:0}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day" tickFormatter={(v:string)=>v.slice(5)}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="created" name="Új" strokeWidth={2}/><Line type="monotone" dataKey="resolved" name="Lezárt" strokeWidth={2}/><Line type="monotone" dataKey="critical_created" name="Kritikus új" strokeWidth={2}/><Line type="monotone" dataKey="breached" name="SLA sértett" strokeWidth={2}/></LineChart></ResponsiveContainer></div></article>
    <article className="eip-card recommendations"><header><div><h2><BrainCircuit/> Vezetői fókusz</h2><p>Determinisztikus ajánlások a jelenlegi Exception mintázat alapján.</p></div></header><div className="eip-recommendations">{(data.recommendations||[]).map((x:string,i:number)=><div key={i}><Target/><span>{x}</span></div>)}</div><div className="eip-meta"><span>Időablak: {data.period_days} nap</span><span>Frissítve: {dateTime(data.generated_at)}</span></div></article>
   </section>
   <section className="eip-card"><header><div><h2><GitMerge/> Aktív root-cause klaszterek</h2><p>A rendszer közös trace, entitás, telephelyi hibahalmozódás vagy visszatérés alapján kapcsolja össze az ügyeket.</p></div></header>{(data.clusters||[]).length?<div className="eip-clusters">{data.clusters.map((x:any)=><article key={x.id} className={`sev-${x.severity}`}><div className="eip-cluster-head"><span>{sevHu[x.severity]||x.severity}</span><em>{x.cluster_type}</em></div><h3>{x.title}</h3><p>{x.summary}</p><div className="eip-cluster-stats"><b>{x.case_count} ügy</b><span>{x.source_count} forrás</span><span>{x.location_id||'globális'}</span></div><div className="eip-rootcause"><BrainCircuit/><span>{x.evidence?.recommendation||'Root-cause vizsgálat szükséges.'}</span></div></article>)}</div>:<div className="eip-empty"><CheckCircle2/> Nincs aktív root-cause klaszter.</div>}</section>
   <section className="eip-grid two"><article className="eip-card"><header><div><h2><TrendingUp/> Visszatérő ügyek</h2><p>Azonos Exception többszöri visszatérése vagy újranyitása.</p></div></header><div className="eip-table-wrap"><table><thead><tr><th>Ügy</th><th>Kategória</th><th>Ismétlés</th><th>Státusz</th><th>Utolsó jelzés</th></tr></thead><tbody>{(data.recurring||[]).map((x:any)=><tr key={x.id}><td><b>{x.title}</b><small>{x.location_id||'globális'}</small></td><td>{catHu[x.category]||x.category}</td><td><strong>{x.occurrence_count}×</strong></td><td>{x.status}</td><td>{dateTime(x.last_detected_at)}</td></tr>)}</tbody></table>{!(data.recurring||[]).length&&<div className="eip-empty">Nincs ismétlődő ügy a kiválasztott időszakban.</div>}</div></article>
    <article className="eip-card"><header><div><h2><Target/> Telephelyi hotspotok</h2><p>Azonos telephely/kategória alatt halmozódó aktív eltérések.</p></div></header><div className="eip-hotspots">{(data.hotspots||[]).map((x:any,i:number)=><div key={`${x.location_id}-${x.category}-${i}`}><div><b>{x.location_id==='__all__'?'Globális':x.location_id}</b><span>{catHu[x.category]||x.category}</span></div><strong>{x.active}</strong><em>{x.critical} kritikus · {x.breached} SLA</em></div>)}{!(data.hotspots||[]).length&&<div className="eip-empty"><CheckCircle2/> Nincs aktív hotspot.</div>}</div></article>
   </section>
   <section className="eip-grid two"><article className="eip-card"><header><div><h2><Users/> Csapat response performance</h2><p>Operatív reakció- és lezárási mutatók; nem dolgozói minősítés, hanem kapacitás- és folyamatkontroll.</p></div></header><div className="eip-table-wrap"><table><thead><tr><th>Csapat</th><th>Ügy</th><th>Aktív</th><th>SLA</th><th>MTTA</th><th>MTTR</th></tr></thead><tbody>{(data.teams||[]).map((x:any)=><tr key={x.team_key}><td><b>{x.team_key}</b></td><td>{x.total}</td><td>{x.active}</td><td><strong>{x.sla_compliance_pct}%</strong></td><td>{minutes(x.avg_ack_minutes)}</td><td>{minutes(x.avg_resolution_minutes)}</td></tr>)}</tbody></table></div></article>
    <article className="eip-card"><header><div><h2><Users/> Felelősi response performance</h2><p>Az ügykiosztás működésének és a reakcióidőknek a kontrollja.</p></div></header><div className="eip-table-wrap"><table><thead><tr><th>Felelős</th><th>Ügy</th><th>Aktív</th><th>SLA</th><th>MTTA</th><th>MTTR</th></tr></thead><tbody>{(data.owners||[]).map((x:any)=><tr key={x.owner_key}><td><b>{x.owner_name||x.owner_key}</b><small>{x.owner_name&&x.owner_key}</small></td><td>{x.total}</td><td>{x.active}</td><td><strong>{x.sla_compliance_pct}%</strong></td><td>{minutes(x.avg_ack_minutes)}</td><td>{minutes(x.avg_resolution_minutes)}</td></tr>)}</tbody></table>{!(data.owners||[]).length&&<div className="eip-empty">Még nincs elegendő felelősi történeti adat.</div>}</div></article>
   </section>
   <section className="eip-card"><header><div><h2><Siren/> Legutóbbi eszkalációk</h2><p>L1 = átvételi figyelmeztetés, L2 = vezetői eszkaláció, L3 = executive beavatkozás.</p></div></header><div className="eip-escalations">{(data.escalations||[]).slice(0,30).map((x:any)=><div key={x.id}><span className={`level l${x.escalation_level}`}>L{x.escalation_level}</span><div><b>{x.title}</b><small>{catHu[x.category]||x.category} · {x.owner_name||'nincs felelős'} · {x.trigger_code}</small></div><em>{x.status}</em><time>{dateTime(x.created_at)}</time></div>)}{!(data.escalations||[]).length&&<div className="eip-empty"><CheckCircle2/> Nincs eszkaláció a kiválasztott időszakban.</div>}</div></section>
   <section className="eip-card"><header><div><h2><Route/> Automatikus eszkalációs mátrix</h2><p>Az idők az ügy első észlelésétől számítódnak. A rendszer SLA-sértés esetén a korábbi szintnél gyorsabban is továbbléphet.</p></div></header><div className="eip-rules">{rules.map((r,i)=><article key={r.severity}><header><b>{sevHu[r.severity]||r.severity}</b><label><input type="checkbox" checked={r.active} onChange={e=>setRules(v=>v.map((x,j)=>j===i?{...x,active:e.target.checked}:x))}/> aktív</label></header><div><label>L1 perc<input type="number" value={r.level1_after_minutes} onChange={e=>setRules(v=>v.map((x,j)=>j===i?{...x,level1_after_minutes:Number(e.target.value)}:x))}/></label><label>L2 perc<input type="number" value={r.level2_after_minutes} onChange={e=>setRules(v=>v.map((x,j)=>j===i?{...x,level2_after_minutes:Number(e.target.value)}:x))}/></label><label>L3 perc<input type="number" value={r.level3_after_minutes} onChange={e=>setRules(v=>v.map((x,j)=>j===i?{...x,level3_after_minutes:Number(e.target.value)}:x))}/></label></div><button onClick={()=>saveRule(r)}><Save/> Mentés</button></article>)}</div></section>
  </>}
 </div>
}
