import React,{useEffect,useRef,useState}from'react';
import{CheckCircle2,LockKeyhole,Maximize2,ScanLine,ShieldCheck,XCircle}from'lucide-react';
import api from'../api/api';

type Result={kind:'idle'|'ok'|'error';title:string;subtitle:string;locker?:number};
export default function FitnessLockerKiosk(){const[input,setInput]=useState(''),[result,setResult]=useState<Result>({kind:'idle',title:'Érintsd a Fitness kártyád',subtitle:'A rendszer automatikusan kiosztja vagy kinyitja a saját rekeszed.'}),[online,setOnline]=useState(false),[busy,setBusy]=useState(false);const ref=useRef<HTMLInputElement|null>(null),timer=useRef<any>(null);
 async function refresh(){try{const r=await api.get('/vir/fitness/lockers/controller/status');setOnline(Boolean(r.data?.online))}catch{setOnline(false)}}
 useEffect(()=>{void refresh();const i=setInterval(()=>void refresh(),5000);const focus=()=>ref.current?.focus();window.addEventListener('click',focus);focus();return()=>{clearInterval(i);window.removeEventListener('click',focus);if(timer.current)clearTimeout(timer.current)}},[]);
 function resetLater(){if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setResult({kind:'idle',title:'Érintsd a Fitness kártyád',subtitle:'A rendszer automatikusan kiosztja vagy kinyitja a saját rekeszed.'});ref.current?.focus()},6000)}
 async function scan(){const card=input.trim();if(!card||busy)return;setBusy(true);setInput('');try{const r=await api.post('/vir/fitness/lockers/scan',{card_uid:card});setResult({kind:'ok',title:`${String(r.data?.locker_no||'').padStart(2,'0')}. REKESZ`,subtitle:r.data?.member_name?`${r.data.member_name}, a rekeszed nyílik.`:'A rekeszed nyílik.',locker:r.data?.locker_no});}catch(e:any){setResult({kind:'error',title:'A rekesz nem nyitható',subtitle:e?.response?.data?.reason||e?.response?.data?.message||'Kérj segítséget a recepción.'})}finally{setBusy(false);resetLater()}}
 const theme=result.kind==='ok'?{bg:'#ecfdf3',fg:'#067647'}:result.kind==='error'?{bg:'#fff1f0',fg:'#b42318'}:{bg:'#fff',fg:'#33262c'};
 return <div style={{...screen,background:theme.bg,color:theme.fg}} onClick={()=>ref.current?.focus()}><input ref={ref} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void scan()}} aria-label="RFID kártyaolvasó bemenet" autoFocus style={hiddenInput}/><header style={top}><div style={brand}><LockKeyhole size={30}/><div><b>KLEOPÁTRA · GYÖNGYÖS FITNESS</b><small>Öltözőszekrény</small></div></div><div style={right}><span style={{...status,color:online?'#067647':'#b42318'}}><ShieldCheck size={18}/>{online?'RENDSZER ONLINE':'VEZÉRLŐ OFFLINE'}</span><button style={full} onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize2 size={18}/> Teljes képernyő</button></div></header><main style={center}>{result.kind==='idle'?<div style={iconRing}><ScanLine size={76}/></div>:result.kind==='ok'?<CheckCircle2 size={100}/>:<XCircle size={100}/>}<h1 style={headline}>{result.title}</h1><p style={sub}>{busy?'Kártya ellenőrzése…':result.subtitle}</p>{result.kind==='ok'&&<div style={lockerNumber}>{String(result.locker||'').padStart(2,'0')}</div>}<div style={hint}>{result.kind==='idle'?'Tartsd a kártyát az olvasóhoz · nem kell a képernyőhöz érni':'A kijelző néhány másodperc múlva visszaáll.'}</div></main><footer style={footer}>20 rekeszes automatikus szekrényrendszer · kártyaazonosító nem jelenik meg és nem kerül nyersen tárolásra</footer></div>}
const screen:React.CSSProperties={position:'fixed',inset:0,zIndex:10000,display:'grid',gridTemplateRows:'auto 1fr auto',fontFamily:'Inter,system-ui,sans-serif',transition:'background .2s',overflow:'hidden'};const hiddenInput:React.CSSProperties={position:'fixed',left:-9999,top:-9999,opacity:0};const top:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'center',padding:'24px 32px',gap:16,background:'rgba(255,255,255,.78)',borderBottom:'1px solid rgba(60,30,45,.1)'};const brand:React.CSSProperties={display:'flex',alignItems:'center',gap:12,color:'#8d2359',letterSpacing:'.06em'};const right:React.CSSProperties={display:'flex',alignItems:'center',gap:10};const status:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:6,fontSize:13,fontWeight:900};const full:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:6,padding:'9px 12px',border:'1px solid #d9ccd2',borderRadius:10,background:'#fff',fontWeight:800,cursor:'pointer'};const center:React.CSSProperties={display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',textAlign:'center',padding:30};const iconRing:React.CSSProperties={width:150,height:150,borderRadius:'50%',display:'grid',placeItems:'center',background:'#f8edf2',color:'#8d2359',boxShadow:'0 0 0 20px rgba(141,35,89,.05)'};const headline:React.CSSProperties={fontSize:'clamp(44px,7vw,92px)',lineHeight:1,margin:'32px 0 12px',fontWeight:950,letterSpacing:'-.04em'};const sub:React.CSSProperties={fontSize:'clamp(20px,2.2vw,32px)',margin:0,maxWidth:900};const lockerNumber:React.CSSProperties={marginTop:26,width:190,height:150,borderRadius:28,display:'grid',placeItems:'center',background:'#fff',fontSize:92,fontWeight:950,boxShadow:'0 18px 60px rgba(0,0,0,.12)'};const hint:React.CSSProperties={marginTop:28,fontSize:16,opacity:.7};const footer:React.CSSProperties={padding:'15px 25px',textAlign:'center',fontSize:12,background:'rgba(255,255,255,.7)',borderTop:'1px solid rgba(60,30,45,.1)'};
