import React,{FormEvent,useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,BookOpen,Building2,Clock3,Database,FileCheck2,FileText,RefreshCw,Save,Scale,ShieldCheck,UserCheck}from"lucide-react";
import api from"../api/api";
import"./GdprCenterPage.css";

type Tab="overview"|"activities"|"retention"|"requests"|"incidents"|"processors"|"notices"|"consents"|"dpias"|"settings"|"guide";
type Item=Record<string,any>;
const endpoint="/transactions/gdpr";
const tabs:Array<{key:Tab,label:string,icon:any}>=[
 {key:"overview",label:"Áttekintés",icon:ShieldCheck},{key:"activities",label:"Adatkezelések",icon:Database},
 {key:"retention",label:"Megőrzés és törlés",icon:Clock3},{key:"requests",label:"Érintetti kérelmek",icon:UserCheck},
 {key:"incidents",label:"Incidensek",icon:AlertTriangle},{key:"processors",label:"Adatfeldolgozók",icon:Building2},
 {key:"notices",label:"Tájékoztatók",icon:FileCheck2},{key:"consents",label:"Hozzájárulások",icon:UserCheck},{key:"dpias",label:"DPIA",icon:Scale},
 {key:"settings",label:"Beállítások",icon:Save},{key:"guide",label:"Mit kell tudni?",icon:BookOpen},
];
const csv=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
const dt=(v:any)=>v?new Date(v).toLocaleString("hu-HU"):"—";
const date=(v:any)=>v?new Date(v).toLocaleDateString("hu-HU"):"—";
const err=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||"A művelet nem sikerült.";

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="gdpr-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="gdpr-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Bezárás">×</button></header>{children}</section></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?"wide":""}><span>{label}</span>{children}</label>}
function Empty({children}:{children:React.ReactNode}){return <div className="gdpr-empty"><FileText/><p>{children}</p></div>}
function Status({value}:{value:any}){return <span className={`gdpr-status s-${String(value||"").replace(/_/g,"-")}`}>{String(value||"—").replace(/_/g," ")}</span>}

export default function GdprCenterPage(){
 const[tab,setTab]=useState<Tab>("overview"),[overview,setOverview]=useState<Item>({}),[items,setItems]=useState<Item[]>([]),[settings,setSettings]=useState<Item[]>([]),[guide,setGuide]=useState<Item>({});
 const[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[modal,setModal]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{
  const o=await api.get(`${endpoint}/overview`);setOverview(o.data||{});
  if(tab==="activities")setItems((await api.get(`${endpoint}/processing-activities`)).data||[]);
  else if(tab==="retention")setItems((await api.get(`${endpoint}/retention-policies`)).data||[]);
  else if(tab==="requests")setItems((await api.get(`${endpoint}/requests`)).data||[]);
  else if(tab==="incidents")setItems((await api.get(`${endpoint}/incidents`)).data||[]);
  else if(tab==="processors")setItems((await api.get(`${endpoint}/processors`)).data||[]);
  else if(tab==="notices")setItems((await api.get(`${endpoint}/notices`)).data||[]);
  else if(tab==="consents")setItems((await api.get(`${endpoint}/consents`)).data||[]);
  else if(tab==="dpias")setItems((await api.get(`${endpoint}/dpias`)).data||[]);
  else if(tab==="settings")setSettings((await api.get(`${endpoint}/settings`)).data||[]);
  else if(tab==="guide")setGuide((await api.get(`${endpoint}/guide`)).data||{});
 }catch(e){setError(err(e))}finally{setLoading(false)}},[tab]);
 useEffect(()=>{void load()},[load]);
 const refresh=()=>void load();
 async function submit(path:string,payload:any){setError("");try{await api.post(`${endpoint}/${path}`,payload);setModal(null);setNotice("A bejegyzés mentve és auditálva.");await load()}catch(e){setError(err(e))}}
 async function patch(path:string,id:string,payload:any){setError("");try{await api.patch(`${endpoint}/${path}/${id}`,payload);setNotice("A módosítás mentve és auditálva.");await load()}catch(e){setError(err(e))}}
 return <main className="gdpr-page">
  <header className="gdpr-hero"><div><small>KLEOPÁTRA · ADATVÉDELMI IRÁNYÍTÁS</small><h1><ShieldCheck/>GDPR-központ</h1><p>Minden adatvédelmi nyilvántartás, határidő, döntés és konfiguráció egy auditált felületen.</p></div><button onClick={refresh} disabled={loading}><RefreshCw className={loading?"spin":""}/>Frissítés</button></header>
  {error&&<div className="gdpr-alert error"><AlertTriangle/>{error}</div>}{notice&&<div className="gdpr-alert ok"><ShieldCheck/>{notice}</div>}
  <nav className="gdpr-tabs" aria-label="GDPR-központ részei">{tabs.map(x=>{const I=x.icon;return <button key={x.key} className={tab===x.key?"active":""} onClick={()=>{setTab(x.key);setNotice("")}}><I/>{x.label}</button>})}</nav>
  {tab==="overview"&&<Overview data={overview} onGo={setTab}/>}
  {tab==="activities"&&<List title="Adatkezelési tevékenységek" text="A GDPR 30. cikk szerinti belső adatkezelési nyilvántartás." add="Új adatkezelés" onAdd={()=>setModal("activity")} items={items} columns={["name","legal_basis","retention_rule","owner","review_at","status"]}/>}
  {tab==="retention"&&<Retention items={items} onAdd={()=>setModal("retention")} onToggle={(x:any)=>patch("retention-policies",x.id,{enabled:!x.enabled})}/>}
  {tab==="requests"&&<Requests items={items} onAdd={()=>setModal("request")} onStatus={(x:any,status:string)=>patch("requests",x.id,{status,identity_verified:status!=="identity_check"?x.identity_verified:undefined})}/>}
  {tab==="incidents"&&<Incidents items={items} onAdd={()=>setModal("incident")} onStatus={(x:any,status:string)=>patch("incidents",x.id,{status})}/>}
  {tab==="processors"&&<List title="Adatfeldolgozók" text="Szerződések, feldolgozási helyek, alfeldolgozók és továbbítási garanciák." add="Új adatfeldolgozó" onAdd={()=>setModal("processor")} items={items} columns={["name","service","processing_locations","dpa_signed_at","transfer_mechanism","status"]}/>}
  {tab==="notices"&&<List title="Tájékoztató-verziók" text="A közölt pontos szöveg verziója és tartalmi lenyomata bizonyítható marad." add="Új verzió" onAdd={()=>setModal("notice")} items={items} columns={["notice_type","version","title","content_hash","effective_from","status"]}/>}
  {tab==="consents"&&<List title="Hozzájárulási bizonyítékok" text="A megadás, megtagadás és visszavonás külön, bizonyítható esemény." add="Új esemény" onAdd={()=>setModal("consent")} items={items} columns={["subject_ref","purpose","notice_version","status","source","captured_at"]}/>}
  {tab==="dpias"&&<List title="Adatvédelmi hatásvizsgálatok" text="Magas kockázatú adatkezelések szűrése, intézkedései és jóváhagyása." add="Új DPIA-szűrés" onAdd={()=>setModal("dpia")} items={items} columns={["title","processing_activity","dpia_required","owner","review_at","status"]}/>}
  {tab==="settings"&&<Settings rows={settings} onSaved={async(key,value)=>{await api.put(`${endpoint}/settings/${key}`,{value});setNotice("A GDPR-beállítás mentve és auditálva.");await load()}}/>}
  {tab==="guide"&&<Guide data={guide}/>}
  {modal==="activity"&&<ActivityForm close={()=>setModal(null)} submit={p=>submit("processing-activities",p)}/>}
  {modal==="retention"&&<RetentionForm close={()=>setModal(null)} submit={p=>submit("retention-policies",p)}/>}
  {modal==="request"&&<RequestForm close={()=>setModal(null)} submit={p=>submit("requests",p)}/>}
  {modal==="incident"&&<IncidentForm close={()=>setModal(null)} submit={p=>submit("incidents",p)}/>}
  {modal==="processor"&&<ProcessorForm close={()=>setModal(null)} submit={p=>submit("processors",p)}/>}
  {modal==="notice"&&<NoticeForm close={()=>setModal(null)} submit={p=>submit("notices",p)}/>}
  {modal==="consent"&&<ConsentForm close={()=>setModal(null)} submit={p=>submit("consents",p)}/>}
  {modal==="dpia"&&<DpiaForm close={()=>setModal(null)} submit={p=>submit("dpias",p)}/>}
 </main>
}

function Overview({data,onGo}:{data:Item;onGo:(t:Tab)=>void}){const cards=[
 ["Aktív adatkezelések",data.activities||0,"activities"],["Felülvizsgálat esedékes",data.reviews_due||0,"activities"],
 ["Nyitott kérelmek",data.open_requests||0,"requests"],["Lejárt kérelmek",data.overdue_requests||0,"requests"],
 ["Nyitott incidensek",data.open_incidents||0,"incidents"],["Értékelendő incidensek",data.incidents_to_assess||0,"incidents"],
 ["Aktív megőrzési szabályok",data.active_retention_policies||0,"retention"],["Aktív adatfeldolgozók",data.active_processors||0,"processors"]];
 return <><section className="gdpr-kpis">{cards.map(([label,value,target])=><button key={label as string} className={Number(value)>0&&String(label).match(/lejárt|értékelendő|esedékes/i)?"warn":""} onClick={()=>onGo(target as Tab)}><span>{label}</span><b>{value}</b></button>)}</section><section className="gdpr-onboarding"><ShieldCheck/><div><h2>Éles indulás előtti sorrend</h2><ol><li>Töltsd ki az adatkezelő és adatvédelmi kapcsolattartó adatait.</li><li>Vedd nyilvántartásba az összes adatkezelési célt és adatfeldolgozót.</li><li>Jogi jóváhagyás után állítsd be a megőrzési időket.</li><li>A törlési automatika csak előnézetes ellenőrzés után kapcsolható be.</li><li>Próbáld végig az érintetti kérelem és incidens folyamatot.</li></ol></div></section></>}
function List({title,text:addText,add,onAdd,items,columns}:{title:string;text:string;add:string;onAdd:()=>void;items:Item[];columns:string[]}){const[q,setQ]=useState("");const shown=items.filter(x=>JSON.stringify(x).toLocaleLowerCase("hu").includes(q.toLocaleLowerCase("hu")));const labels:Item={name:"Név",legal_basis:"Jogalap",retention_rule:"Megőrzés",owner:"Felelős",review_at:"Felülvizsgálat",status:"Állapot",service:"Szolgáltatás",processing_locations:"Feldolgozás helye",dpa_signed_at:"DPA",transfer_mechanism:"Továbbítás",notice_type:"Típus",version:"Verzió",title:"Cím",content_hash:"Tartalom-hash",effective_from:"Hatályos",subject_ref:"Érintett hivatkozása",purpose:"Cél",notice_version:"Tájékoztató",source:"Forrás",captured_at:"Rögzítve",processing_activity:"Adatkezelés",dpia_required:"DPIA szükséges"};return <section className="gdpr-panel"><header><div><h2>{title}</h2><p>{addText}</p></div><button onClick={onAdd}>+ {add}</button></header><input className="gdpr-filter" value={q} onChange={e=>setQ(e.target.value)} placeholder="Keresés és szűrés…" aria-label={`${title} szűrése`}/>{!shown.length?<Empty>Nincs a szűrésnek megfelelő bejegyzés.</Empty>:<div className="gdpr-table"><table><thead><tr>{columns.map(c=><th key={c}>{labels[c]||c}</th>)}</tr></thead><tbody>{shown.map(x=><tr key={x.id}>{columns.map(c=><td key={c}>{c==="status"?<Status value={x[c]}/>:c.endsWith("_at")||c==="effective_from"?date(x[c]):typeof x[c]==="boolean"?(x[c]?"Igen":"Nem"):Array.isArray(x[c])?x[c].join(", ")||"—":String(x[c]??"—")}</td>)}</tr>)}</tbody></table></div>}</section>}
function Retention({items,onAdd,onToggle}:{items:Item[];onAdd:()=>void;onToggle:(x:Item)=>void}){return <section className="gdpr-panel"><header><div><h2>Megőrzés és törlés</h2><p>A szabályok alapból kikapcsoltak. Aktiválás előtt jogi jóváhagyás és előnézet szükséges.</p></div><button onClick={onAdd}>+ Új szabály</button></header>{!items.length?<Empty>Még nincs megőrzési szabály.</Empty>:<div className="gdpr-table"><table><thead><tr><th>Szabály</th><th>Adattípus</th><th>Kezdőesemény</th><th>Idő</th><th>Művelet</th><th>Jogi zárolás</th><th>Aktív</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.entity_type}</td><td>{x.trigger_event}</td><td>{x.retention_days} nap</td><td><Status value={x.action}/></td><td>{x.legal_hold_supported?"Igen":"Nem"}</td><td><button className={x.enabled?"toggle on":"toggle"} onClick={()=>onToggle(x)} aria-pressed={x.enabled}>{x.enabled?"Bekapcsolva":"Kikapcsolva"}</button></td></tr>)}</tbody></table></div>}</section>}
function Requests({items,onAdd,onStatus}:{items:Item[];onAdd:()=>void;onStatus:(x:Item,s:string)=>void}){return <section className="gdpr-panel"><header><div><h2>Érintetti kérelmek</h2><p>Határidő, személyazonosság, felelős, döntés és teljesítés nyomon követése.</p></div><button onClick={onAdd}>+ Új kérelem</button></header>{!items.length?<Empty>Még nincs érintetti kérelem.</Empty>:<div className="gdpr-table"><table><thead><tr><th>Hivatkozás</th><th>Típus</th><th>Érintett</th><th>Beérkezett</th><th>Határidő</th><th>Azonosított</th><th>Állapot</th></tr></thead><tbody>{items.map(x=><tr className={new Date(x.due_at)<new Date()&&!['completed','rejected','cancelled'].includes(x.status)?"overdue":""} key={x.id}><td>{x.reference_no}</td><td>{x.request_type}</td><td>{x.subject_name}</td><td>{date(x.received_at)}</td><td>{date(x.due_at)}</td><td>{x.identity_verified?"Igen":"Nem"}</td><td><select value={x.status} onChange={e=>onStatus(x,e.target.value)}><option value="received">beérkezett</option><option value="identity_check">azonosítás</option><option value="in_progress">folyamatban</option><option value="extended">hosszabbítva</option><option value="completed">teljesítve</option><option value="rejected">elutasítva</option><option value="cancelled">visszavonva</option></select></td></tr>)}</tbody></table></div>}</section>}
function Incidents({items,onAdd,onStatus}:{items:Item[];onAdd:()=>void;onStatus:(x:Item,s:string)=>void}){return <section className="gdpr-panel"><header><div><h2>Adatvédelmi incidensek</h2><p>72 órás határidő, kockázatértékelés, korlátozás és értesítési döntés.</p></div><button className="danger" onClick={onAdd}>+ Incidens rögzítése</button></header>{!items.length?<Empty>Nincs rögzített incidens.</Empty>:<div className="gdpr-cards">{items.map(x=><article key={x.id} className={`incident ${x.severity}`}><header><div><small>{x.reference_no}</small><h3>{x.title}</h3></div><Status value={x.severity}/></header><p>{x.description}</p><dl><div><dt>Tudomásszerzés</dt><dd>{dt(x.aware_at)}</dd></div><div><dt>72 órás határidő</dt><dd>{dt(x.notification_deadline)}</dd></div><div><dt>Hatósági döntés</dt><dd>{x.authority_notification_required==null?"Értékelendő":x.authority_notification_required?"Bejelentendő":"Nem bejelentendő"}</dd></div></dl><select value={x.status} onChange={e=>onStatus(x,e.target.value)}><option value="open">nyitott</option><option value="contained">korlátozott</option><option value="assessing">értékelés alatt</option><option value="notified">bejelentve</option><option value="closed">lezárt</option></select></article>)}</div>}</section>}

const settingLabels:Item={controller_name:"Adatkezelő neve",controller_contact_email:"Adatkezelő kapcsolati e-mail",dpo_name:"Adatvédelmi tisztviselő / felelős",dpo_email:"Adatvédelmi kapcsolati e-mail",authority_name:"Felügyeleti hatóság",authority_url:"Hatóság weboldala",request_deadline_days:"Érintetti kérelem alap-határideje (nap)",incident_notification_hours:"Incidens bejelentési határidő (óra)",retention_automation_enabled:"Megőrzési automatika",retention_preview_only:"Csak előnézet",privacy_notice_version:"Adatvédelmi tájékoztató verziója",privacy_notice_url:"Adatvédelmi tájékoztató URL",cookie_notice_url:"Cookie tájékoztató URL",default_audit_retention_months:"Auditnapló megőrzése (hónap)"};
function Settings({rows,onSaved}:{rows:Item[];onSaved:(key:string,value:any)=>Promise<void>}){const values=useMemo(()=>Object.fromEntries(rows.map(x=>[x.key,x.value])),[rows]);const[draft,setDraft]=useState<Item>({});useEffect(()=>setDraft(values),[values]);return <section className="gdpr-panel"><header><div><h2>GDPR-beállítások</h2><p>Csak a működés közben valóban változó paraméterek konfigurálhatók. A jogszabályi alapelvek nem kapcsolhatók ki.</p></div></header><div className="gdpr-settings">{rows.map(x=>{const v=draft[x.key];const isBool=typeof x.value==="boolean";return <div key={x.key}><label><span>{settingLabels[x.key]||x.key}</span>{isBool?<input type="checkbox" checked={Boolean(v)} onChange={e=>setDraft(d=>({...d,[x.key]:e.target.checked}))}/>:<input type={typeof x.value==="number"?"number":"text"} value={v??""} onChange={e=>setDraft(d=>({...d,[x.key]:typeof x.value==="number"?Number(e.target.value):e.target.value}))}/>}</label><button disabled={v===x.value} onClick={()=>onSaved(x.key,v)}><Save/>Mentés</button></div>})}</div></section>}
function Guide({data}:{data:Item}){return <section className="gdpr-panel"><header><div><h2>GDPR működési útmutató</h2><p>{data.legal_notice}</p></div></header><div className="gdpr-guide">{(data.sections||[]).map((x:Item)=><article key={x.key}><h3>{x.title}</h3><p>{x.text}</p><strong>{x.articles}</strong></article>)}</div><footer className="gdpr-sources">{(data.sources||[]).map((x:Item)=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.title}</a>)}</footer></section>}

function ActivityForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({status:"draft",special_categories:false});const send=(e:FormEvent)=>{e.preventDefault();submit({...p,data_subjects:csv(p.data_subjects||""),data_categories:csv(p.data_categories||""),recipients:csv(p.recipients||""),processors:csv(p.processors||"")})};return <Modal title="Új adatkezelési tevékenység" onClose={close}><form className="gdpr-form" onSubmit={send}><Field label="Név"><input required onChange={e=>set({...p,name:e.target.value})}/></Field><Field label="Felelős"><input onChange={e=>set({...p,owner:e.target.value})}/></Field><Field label="Cél" wide><textarea required onChange={e=>set({...p,purpose:e.target.value})}/></Field><Field label="Jogalap"><input required placeholder="pl. szerződés teljesítése" onChange={e=>set({...p,legal_basis:e.target.value})}/></Field><Field label="Érintettek"><input placeholder="vendégek, dolgozók" onChange={e=>set({...p,data_subjects:e.target.value})}/></Field><Field label="Adatkategóriák"><input placeholder="név, elérhetőség" onChange={e=>set({...p,data_categories:e.target.value})}/></Field><Field label="Címzettek"><input onChange={e=>set({...p,recipients:e.target.value})}/></Field><Field label="Adatfeldolgozók"><input onChange={e=>set({...p,processors:e.target.value})}/></Field><Field label="Megőrzési szabály" wide><textarea required onChange={e=>set({...p,retention_rule:e.target.value})}/></Field><Field label="Biztonsági intézkedések" wide><textarea onChange={e=>set({...p,security_measures:e.target.value})}/></Field><Field label="Különleges adat"><input type="checkbox" onChange={e=>set({...p,special_categories:e.target.checked})}/></Field><Field label="Felülvizsgálat"><input type="date" onChange={e=>set({...p,review_at:e.target.value})}/></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Mentés</button></div></form></Modal>}
function RetentionForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({action:"review",enabled:false,legal_hold_supported:true});return <Modal title="Új megőrzési szabály" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit(p)}}><Field label="Név"><input required onChange={e=>set({...p,name:e.target.value})}/></Field><Field label="Adattípus"><input required placeholder="pl. job_application" onChange={e=>set({...p,entity_type:e.target.value})}/></Field><Field label="Kezdőesemény"><input required placeholder="pl. pályázat lezárása" onChange={e=>set({...p,trigger_event:e.target.value})}/></Field><Field label="Megőrzés napokban"><input required min="0" type="number" onChange={e=>set({...p,retention_days:Number(e.target.value)})}/></Field><Field label="Művelet"><select value={p.action} onChange={e=>set({...p,action:e.target.value})}><option value="review">kézi felülvizsgálat</option><option value="anonymize">anonimizálás</option><option value="soft_delete">inaktiválás</option><option value="delete">törlés</option></select></Field><Field label="Jogi indok" wide><textarea onChange={e=>set({...p,legal_basis:e.target.value})}/></Field><p className="form-warning">A szabály biztonsági okból kikapcsolva jön létre. Aktiválás előtt jogi jóváhagyás szükséges.</p><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Mentés</button></div></form></Modal>}
function RequestForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({request_type:"access"});return <Modal title="Új érintetti kérelem" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit(p)}}><Field label="Kérelem típusa"><select value={p.request_type} onChange={e=>set({...p,request_type:e.target.value})}><option value="access">hozzáférés</option><option value="rectification">helyesbítés</option><option value="erasure">törlés</option><option value="restriction">korlátozás</option><option value="portability">hordozhatóság</option><option value="objection">tiltakozás</option><option value="consent_withdrawal">hozzájárulás visszavonása</option><option value="other">egyéb</option></select></Field><Field label="Érintett neve"><input required onChange={e=>set({...p,subject_name:e.target.value})}/></Field><Field label="Kapcsolattartás"><input onChange={e=>set({...p,subject_contact:e.target.value})}/></Field><Field label="Felelős"><input onChange={e=>set({...p,assigned_to:e.target.value})}/></Field><Field label="Kérelem terjedelme" wide><textarea onChange={e=>set({...p,scope:e.target.value})}/></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Rögzítés</button></div></form></Modal>}
function IncidentForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({severity:"medium",detected_at:new Date().toISOString().slice(0,16),aware_at:new Date().toISOString().slice(0,16)});return <Modal title="Adatvédelmi incidens rögzítése" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit({...p,data_categories:csv(p.data_categories||"")})}}><Field label="Cím"><input required onChange={e=>set({...p,title:e.target.value})}/></Field><Field label="Súlyosság"><select value={p.severity} onChange={e=>set({...p,severity:e.target.value})}><option value="low">alacsony</option><option value="medium">közepes</option><option value="high">magas</option><option value="critical">kritikus</option></select></Field><Field label="Észlelés"><input type="datetime-local" value={p.detected_at} onChange={e=>set({...p,detected_at:e.target.value})}/></Field><Field label="Tudomásszerzés"><input type="datetime-local" value={p.aware_at} onChange={e=>set({...p,aware_at:e.target.value})}/></Field><Field label="Leírás" wide><textarea required onChange={e=>set({...p,description:e.target.value})}/></Field><Field label="Érintett adatkategóriák" wide><input placeholder="név, e-mail, foglalás" onChange={e=>set({...p,data_categories:e.target.value})}/></Field><Field label="Azonnali korlátozás" wide><textarea onChange={e=>set({...p,containment:e.target.value})}/></Field><Field label="Felelős"><input onChange={e=>set({...p,owner:e.target.value})}/></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit" className="danger">Incidens rögzítése</button></div></form></Modal>}
function ProcessorForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({status:"active"});return <Modal title="Új adatfeldolgozó" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit({...p,data_categories:csv(p.data_categories||""),processing_locations:csv(p.processing_locations||"")})}}><Field label="Szolgáltató neve"><input required onChange={e=>set({...p,name:e.target.value})}/></Field><Field label="Szolgáltatás"><input required onChange={e=>set({...p,service:e.target.value})}/></Field><Field label="Adatkategóriák"><input onChange={e=>set({...p,data_categories:e.target.value})}/></Field><Field label="Feldolgozás helye"><input placeholder="Magyarország, EU" onChange={e=>set({...p,processing_locations:e.target.value})}/></Field><Field label="DPA aláírása"><input type="date" onChange={e=>set({...p,dpa_signed_at:e.target.value})}/></Field><Field label="Továbbítási mechanizmus"><input placeholder="nincs / megfelelőségi határozat / SCC" onChange={e=>set({...p,transfer_mechanism:e.target.value})}/></Field><Field label="Alfeldolgozói lista URL"><input type="url" onChange={e=>set({...p,subprocessor_url:e.target.value})}/></Field><Field label="Felelős"><input onChange={e=>set({...p,owner:e.target.value})}/></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Mentés</button></div></form></Modal>}

function NoticeForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({notice_type:"privacy",status:"draft",effective_from:new Date().toISOString().slice(0,16)});return <Modal title="Tájékoztató-verzió rögzítése" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit(p)}}><Field label="Típus"><select value={p.notice_type} onChange={e=>set({...p,notice_type:e.target.value})}><option value="privacy">adatvédelmi</option><option value="cookie">cookie</option><option value="employee">munkavállalói</option><option value="applicant">pályázói</option><option value="marketing">marketing</option><option value="other">egyéb</option></select></Field><Field label="Verzió"><input required onChange={e=>set({...p,version:e.target.value})}/></Field><Field label="Cím"><input required onChange={e=>set({...p,title:e.target.value})}/></Field><Field label="Hatálybalépés"><input type="datetime-local" value={p.effective_from} onChange={e=>set({...p,effective_from:e.target.value})}/></Field><Field label="Nyilvános URL" wide><input type="url" onChange={e=>set({...p,url:e.target.value})}/></Field><Field label="Tartalom SHA-256 lenyomata" wide><input required pattern="[A-Fa-f0-9]{64}" title="64 hexadecimális karakter" onChange={e=>set({...p,content_hash:e.target.value})}/></Field><Field label="Állapot"><select value={p.status} onChange={e=>set({...p,status:e.target.value})}><option value="draft">tervezet</option><option value="active">hatályos</option><option value="retired">visszavont</option></select></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Mentés</button></div></form></Modal>}
function ConsentForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({status:"granted",source:"admin"});return <Modal title="Hozzájárulási esemény" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit({...p,evidence:{reference:p.evidence_reference||""}})}}><Field label="Érintett belső hivatkozása"><input required onChange={e=>set({...p,subject_ref:e.target.value})}/></Field><Field label="Cél"><input required placeholder="pl. marketing e-mail" onChange={e=>set({...p,purpose:e.target.value})}/></Field><Field label="Tájékoztató-verzió UUID"><input onChange={e=>set({...p,notice_version_id:e.target.value})}/></Field><Field label="Esemény"><select value={p.status} onChange={e=>set({...p,status:e.target.value})}><option value="granted">megadva</option><option value="withdrawn">visszavonva</option><option value="refused">megtagadva</option></select></Field><Field label="Forrás"><input required value={p.source} onChange={e=>set({...p,source:e.target.value})}/></Field><Field label="Bizonyíték hivatkozása"><input onChange={e=>set({...p,evidence_reference:e.target.value})}/></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Rögzítés</button></div></form></Modal>}
function DpiaForm({close,submit}:{close:()=>void;submit:(p:any)=>void}){const[p,set]=useState<Item>({status:"screening"});return <Modal title="DPIA előszűrés" onClose={close}><form className="gdpr-form" onSubmit={e=>{e.preventDefault();submit(p)}}><Field label="Cím"><input required onChange={e=>set({...p,title:e.target.value})}/></Field><Field label="Felelős"><input onChange={e=>set({...p,owner:e.target.value})}/></Field><Field label="Szűrés indoka" wide><textarea required onChange={e=>set({...p,screening_reason:e.target.value})}/></Field>{[["systematic_monitoring","Rendszeres megfigyelés"],["special_category_scale","Különleges adatok nagy körben"],["vulnerable_subjects","Kiszolgáltatott érintettek"],["new_technology","Új technológia"]].map(([k,l])=><Field key={k} label={l}><input type="checkbox" onChange={e=>set({...p,[k]:e.target.checked})}/></Field>)}<Field label="Szükségesség és arányosság" wide><textarea onChange={e=>set({...p,necessity_proportionality:e.target.value})}/></Field><Field label="Kockázatok" wide><textarea onChange={e=>set({...p,risks:e.target.value})}/></Field><Field label="Kockázatcsökkentő intézkedések" wide><textarea onChange={e=>set({...p,measures:e.target.value})}/></Field><Field label="Felülvizsgálat"><input type="date" onChange={e=>set({...p,review_at:e.target.value})}/></Field><div className="actions"><button type="button" onClick={close}>Mégse</button><button type="submit">Mentés</button></div></form></Modal>}
