import React,{useMemo,useState}from"react";
import axios from"axios";
import{CheckCircle2,Send,Star}from"lucide-react";
import"./GuestReviewTabletPage.css";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
export default function GuestReviewTabletPage(){
 const params=useMemo(()=>new URLSearchParams(window.location.search),[]);const token=params.get('token')||'',employee_id=params.get('employee_id')||'',location_id=params.get('location_id')||'';
 const[rating,setRating]=useState(5),[name,setName]=useState(''),[text,setText]=useState(''),[sending,setSending]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setSending(true);setError('');try{await axios.post(`${API_BASE}/public/vir-spec/reviews${token?`?token=${encodeURIComponent(token)}`:''}`,{rating,client_name:name,review_text:text,employee_id:employee_id||null,location_id:location_id||null});setDone(true)}catch(err:any){setError(err?.response?.data?.message||'Az értékelés mentése most nem sikerült.')}finally{setSending(false)}}
 if(done)return <main className="grt-page"><section className="grt-card done"><CheckCircle2 size={64}/><div className="grt-kicker">KLEOPÁTRA SZÉPSÉGSZALONOK</div><h1>Köszönjük a visszajelzését!</h1><p>Az értékelést rögzítettük. A nyilvános megjelenés előtt kollégánk moderálja.</p><button onClick={()=>{setDone(false);setRating(5);setName('');setText('')}}>Új értékelés</button></section></main>;
 return <main className="grt-page"><form className="grt-card" onSubmit={submit}><div className="grt-kicker">KLEOPÁTRA • VENDÉGÉRTÉKELÉS</div><h1>Milyen volt a mai élmény?</h1><p>Érintse meg a csillagokat, majd ha szeretné, írjon néhány szót.</p><div className="grt-stars" role="radiogroup" aria-label="Értékelés">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setRating(n)} aria-label={`${n} csillag`} className={n<=rating?'active':''}><Star size={48} fill={n<=rating?'currentColor':'none'}/></button>)}</div><div className="grt-score">{rating} / 5</div><label>Név <span>(nem kötelező)</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Az Ön neve"/></label><label>Megjegyzés <span>(nem kötelező)</span><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Mit szeretne kiemelni?"/></label>{error&&<div className="grt-error">{error}</div>}<button className="grt-submit" disabled={sending}><Send size={19}/>{sending?'Küldés…':'Értékelés elküldése'}</button><small className="grt-privacy">A vélemény nem kerül automatikusan Facebookra. Nyilvános megjelenés csak moderátori jóváhagyás után történhet.</small></form></main>
}
