import React, { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Clock3, Coffee, FileCheck2, Filter, Plus, TimerReset, UserRoundCheck, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import withBase from "../utils/apiBase";
import "./HrAttendancePage.css";

type Employee={id:string;full_name:string;position_name?:string;location_id?:string;location_name?:string;active?:boolean};
type Timesheet={id:string;employee_id:string;full_name:string;location_name?:string;work_date:string;clock_in?:string;clock_out?:string;break_minutes:number;regular_minutes:number;overtime_minutes:number;status:string;note?:string};
type LeaveType={id:string;name:string;color?:string;is_paid:boolean};
type Leave={id:string;employee_id:string;full_name:string;leave_type_name:string;color?:string;date_from:string;date_to:string;reason?:string;status:string};
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,8)+"01";
const hours=(minutes:number)=>`${(Number(minutes||0)/60).toLocaleString("hu-HU",{maximumFractionDigits:1})} óra`;
const statusLabel:Record<string,string>={draft:"Piszkozat",submitted:"Beküldve",approved:"Jóváhagyva",rejected:"Elutasítva",pending:"Függőben",cancelled:"Visszavonva"};

export default function HrAttendancePage(){
 const location=useLocation(); const initial=location.pathname.includes("vacation")?"leave":"time";
 const [tab,setTab]=useState<"time"|"leave">(initial); const [employees,setEmployees]=useState<Employee[]>([]); const [timesheets,setTimesheets]=useState<Timesheet[]>([]); const [leaveTypes,setLeaveTypes]=useState<LeaveType[]>([]); const [leaves,setLeaves]=useState<Leave[]>([]); const [summary,setSummary]=useState<any>({});
 const [from,setFrom]=useState(monthStart()); const [to,setTo]=useState(today()); const [employeeFilter,setEmployeeFilter]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [timeModal,setTimeModal]=useState(false); const [leaveModal,setLeaveModal]=useState(false); const [saving,setSaving]=useState(false);
 const [timeForm,setTimeForm]=useState<any>({employee_id:"",location_id:"",work_date:today(),clock_in:"08:00",clock_out:"16:30",break_minutes:30,status:"submitted",note:""});
 const [leaveForm,setLeaveForm]=useState<any>({employee_id:"",leave_type_id:"",date_from:today(),date_to:today(),minutes_per_day:480,reason:"",status:"pending"});
 const token=localStorage.getItem("kleo_token")||localStorage.getItem("token")||"";
 const api=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(withBase(path),{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init?.headers||{})}});const raw=await response.text();const data=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(data?.error||"A művelet nem sikerült.");return data;},[token]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=`from=${from}&to=${to}${employeeFilter?`&employee_id=${employeeFilter}`:""}`;const [e,t,lt,l,s]=await Promise.all([api("employees"),api(`hr/timesheets?${q}`),api("hr/leave-types"),api(`hr/leave-requests${employeeFilter?`?employee_id=${employeeFilter}`:""}`),api(`hr/attendance-summary?from=${from}&to=${to}`)]);setEmployees(Array.isArray(e)?e:[]);setTimesheets(Array.isArray(t)?t:[]);setLeaveTypes(Array.isArray(lt)?lt:[]);setLeaves(Array.isArray(l)?l:[]);setSummary(s||{});}catch(e:any){setError(e.message);}finally{setLoading(false);}},[api,employeeFilter,from,to]);
 useEffect(()=>{load();},[load]);
 const showNotice=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),3000)};
 const computed=useMemo(()=>({regular:timesheets.reduce((s,x)=>s+Number(x.regular_minutes||0),0),overtime:timesheets.reduce((s,x)=>s+Number(x.overtime_minutes||0),0),pending:leaves.filter(x=>x.status==="pending").length}),[timesheets,leaves]);
 const saveTime=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const start=new Date(`${timeForm.work_date}T${timeForm.clock_in}:00`);const end=new Date(`${timeForm.work_date}T${timeForm.clock_out}:00`);if(end<=start)throw new Error("A munkaidő vége legyen későbbi a kezdésnél.");const total=Math.max(0,Math.round((end.getTime()-start.getTime())/60000)-Number(timeForm.break_minutes||0));await api("hr/timesheets",{method:"POST",body:JSON.stringify({...timeForm,clock_in:start.toISOString(),clock_out:end.toISOString(),regular_minutes:Math.min(total,480),overtime_minutes:Math.max(0,total-480)})});setTimeModal(false);showNotice("A jelenléti sor mentése sikerült.");await load();}catch(e:any){setError(e.message);}finally{setSaving(false)}};
 const saveLeave=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await api("hr/leave-requests",{method:"POST",body:JSON.stringify(leaveForm)});setLeaveModal(false);showNotice("A távolléti kérelem létrejött.");await load();}catch(e:any){setError(e.message);}finally{setSaving(false)}};
 const setTimeStatus=async(id:string,status:string)=>{try{await api(`hr/timesheets/${id}/status`,{method:"PATCH",body:JSON.stringify({status})});showNotice(status==="approved"?"Jelenlét jóváhagyva.":"Jelenlét elutasítva.");await load();}catch(e:any){setError(e.message)}};
 const setLeaveStatus=async(id:string,status:string)=>{try{await api(`hr/leave-requests/${id}`,{method:"PATCH",body:JSON.stringify({status})});showNotice(status==="approved"?"Szabadság jóváhagyva.":"Kérelem elutasítva.");await load();}catch(e:any){setError(e.message)}};
 return <main className="attendance-page">{notice&&<div className="attendance-toast"><Check size={17}/>{notice}</div>}<section className="attendance-hero"><div><span>CSAPAT ÉS HR</span><h1>Munkaidő és távollétek</h1><p>Jelenlét, túlóra, szabadság és vezetői jóváhagyás egy helyen.</p></div><button className="attendance-primary" onClick={()=>tab==="time"?setTimeModal(true):setLeaveModal(true)}><Plus size={18}/>{tab==="time"?"Jelenlét rögzítése":"Új távollét"}</button></section>
 <section className="attendance-stats"><article><Clock3/><div><small>Rendes munkaidő</small><strong>{hours(summary.regular_minutes??computed.regular)}</strong></div></article><article><TimerReset/><div><small>Túlóra</small><strong>{hours(summary.overtime_minutes??computed.overtime)}</strong></div></article><article><UserRoundCheck/><div><small>Érintett munkatárs</small><strong>{summary.employee_count??0}</strong></div></article><article><FileCheck2/><div><small>Függő kérelmek</small><strong>{summary.pending_leave_count??computed.pending}</strong></div></article></section>
 <nav className="attendance-tabs"><button className={tab==="time"?"active":""} onClick={()=>setTab("time")}><Clock3 size={17}/>Munkaidő</button><button className={tab==="leave"?"active":""} onClick={()=>setTab("leave")}><CalendarDays size={17}/>Szabadságok és távollétek</button></nav>
 {error&&<div className="attendance-alert">{error}<button onClick={()=>setError("")}><X size={16}/></button></div>}
 <section className="attendance-panel"><header className="attendance-filter"><Filter size={17}/><label>Időszak<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>–</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Munkatárs<select value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value)}><option value="">Minden munkatárs</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label></header>
 {tab==="time"?<div className="attendance-table-wrap"><table><thead><tr><th>Dátum</th><th>Munkatárs</th><th>Telephely</th><th>Érkezés</th><th>Távozás</th><th>Szünet</th><th>Munkaidő</th><th>Túlóra</th><th>Státusz</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={10} className="attendance-empty">Betöltés…</td></tr>:timesheets.length===0?<tr><td colSpan={10} className="attendance-empty">Ebben az időszakban nincs jelenléti adat.</td></tr>:timesheets.map(t=><tr key={t.id}><td><strong>{new Date(t.work_date).toLocaleDateString("hu-HU")}</strong></td><td>{t.full_name}</td><td>{t.location_name||"—"}</td><td>{t.clock_in?new Date(t.clock_in).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"}):"—"}</td><td>{t.clock_out?new Date(t.clock_out).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"}):"—"}</td><td><span className="with-icon"><Coffee size={13}/>{t.break_minutes||0} perc</span></td><td>{hours(t.regular_minutes)}</td><td className={t.overtime_minutes>0?"overtime":""}>{hours(t.overtime_minutes)}</td><td><span className={`attendance-status ${t.status}`}>{statusLabel[t.status]||t.status}</span></td><td>{t.status!=="approved"&&<div className="row-actions"><button title="Jóváhagyás" onClick={()=>setTimeStatus(t.id,"approved")}><Check/></button><button title="Elutasítás" onClick={()=>setTimeStatus(t.id,"rejected")}><X/></button></div>}</td></tr>)}</tbody></table></div>
 :<div className="leave-grid">{loading?<p className="attendance-empty">Betöltés…</p>:leaves.length===0?<p className="attendance-empty">Nincs távolléti kérelem.</p>:leaves.map(l=><article className="leave-card" key={l.id} style={{"--leave-color":l.color||"#7657df"} as React.CSSProperties}><header><span>{l.leave_type_name}</span><b className={`attendance-status ${l.status}`}>{statusLabel[l.status]||l.status}</b></header><h3>{l.full_name}</h3><p>{new Date(l.date_from).toLocaleDateString("hu-HU")} – {new Date(l.date_to).toLocaleDateString("hu-HU")}</p><small>{l.reason||"Nincs indoklás."}</small>{l.status==="pending"&&<footer><button onClick={()=>setLeaveStatus(l.id,"approved")}><Check/>Jóváhagyás</button><button onClick={()=>setLeaveStatus(l.id,"rejected")}><X/>Elutasítás</button></footer>}</article>)}</div>}</section>
 {timeModal&&<Modal title="Jelenlét rögzítése" onClose={()=>setTimeModal(false)} onSubmit={saveTime} saving={saving}><Field label="Munkatárs *"><select required value={timeForm.employee_id} onChange={e=>{const emp=employees.find(x=>x.id===e.target.value);setTimeForm({...timeForm,employee_id:e.target.value,location_id:emp?.location_id||""})}}><option value="">Válasszon</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Munkanap *"><input required type="date" value={timeForm.work_date} onChange={e=>setTimeForm({...timeForm,work_date:e.target.value})}/></Field><Field label="Érkezés *"><input required type="time" value={timeForm.clock_in} onChange={e=>setTimeForm({...timeForm,clock_in:e.target.value})}/></Field><Field label="Távozás *"><input required type="time" value={timeForm.clock_out} onChange={e=>setTimeForm({...timeForm,clock_out:e.target.value})}/></Field><Field label="Szünet (perc)"><input type="number" min="0" value={timeForm.break_minutes} onChange={e=>setTimeForm({...timeForm,break_minutes:e.target.value})}/></Field><Field label="Megjegyzés" wide><textarea value={timeForm.note} onChange={e=>setTimeForm({...timeForm,note:e.target.value})}/></Field></Modal>}
 {leaveModal&&<Modal title="Új távolléti kérelem" onClose={()=>setLeaveModal(false)} onSubmit={saveLeave} saving={saving}><Field label="Munkatárs *"><select required value={leaveForm.employee_id} onChange={e=>setLeaveForm({...leaveForm,employee_id:e.target.value})}><option value="">Válasszon</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Távollét típusa *"><select required value={leaveForm.leave_type_id} onChange={e=>setLeaveForm({...leaveForm,leave_type_id:e.target.value})}><option value="">Válasszon</option>{leaveTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Első nap *"><input required type="date" value={leaveForm.date_from} onChange={e=>setLeaveForm({...leaveForm,date_from:e.target.value})}/></Field><Field label="Utolsó nap *"><input required type="date" value={leaveForm.date_to} onChange={e=>setLeaveForm({...leaveForm,date_to:e.target.value})}/></Field><Field label="Napi idő (perc)"><input type="number" min="0" max="1440" value={leaveForm.minutes_per_day} onChange={e=>setLeaveForm({...leaveForm,minutes_per_day:e.target.value})}/></Field><Field label="Indoklás" wide><textarea value={leaveForm.reason} onChange={e=>setLeaveForm({...leaveForm,reason:e.target.value})}/></Field></Modal>}</main>;
}
function Modal({title,onClose,onSubmit,saving,children}:{title:string;onClose:()=>void;onSubmit:(e:FormEvent)=>void;saving:boolean;children:React.ReactNode}){return <div className="attendance-modal-bg"><form className="attendance-modal" onSubmit={onSubmit}><header><div><span>CSAPAT ÉS HR</span><h2>{title}</h2></div><button type="button" onClick={onClose}><X/></button></header><div className="attendance-form">{children}</div><footer><button type="button" onClick={onClose}>Mégse</button><button className="attendance-primary" disabled={saving}>{saving?"Mentés…":"Mentés"}</button></footer></form></div>}
function Field({label,children,wide}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?"wide":""}><span>{label}</span>{children}</label>}
