import React,{useEffect,useMemo,useState}from"react";
import{ExternalLink,RefreshCw,Save,Search,Settings2,ShieldCheck,Users,WalletCards}from"lucide-react";
import api from"../api/api";
import"./KleoTeamAdminPanel.css";

const LABELS:Record<string,string>={schedule:'Beosztás és műszakok',attendance:'Jelenlét és munkaidő',workorders:'Munkalapok',tasks:'Feladatok és jóváhagyások',chat:'Belső chat',knowledge:'Tudásbázis',checklists:'Check listák',quiz:'Munkaköri teszt',training:'Képzések',evaluations:'Értékelések',compensation:'Bér és jutalék'};
function msg(e:any){return e?.response?.data?.error||e?.response?.data?.message||e?.message||'A művelet sikertelen.'}
export default function KleoTeamAdminPanel(){
 const[config,setConfig]=useState<any>(null),[modules,setModules]=useState<string[]>([]),[employees,setEmployees]=useState<any[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setLoading(true);setError('');try{const[c,e]=await Promise.all([api.get('/employee-self/admin/config'),api.get('/employee-self/admin/employees')]);setConfig(c.data?.config||null);setModules(e.data?.modules||c.data?.modules||[]);setEmployees(e.data?.employees||[])}catch(e){setError(msg(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function saveConfig(next:any){setSaving('config');setError('');setNotice('');try{const r=await api.put('/employee-self/admin/config',next);setConfig(r.data?.config||next);setNotice('A Kleo Team globális beállításai elmentve.')}catch(e){setError(msg(e))}finally{setSaving('')}}
 async function setPermission(employee:any,key:string,value:boolean){setSaving(`${employee.id}:${key}`);setError('');try{await api.put(`/employee-self/admin/employees/${employee.id}`,{permissions:{[key]:value}});setEmployees(rows=>rows.map(x=>x.id===employee.id?{...x,permissions:{...(x.permissions||{}),[key]:value}}:x))}catch(e){setError(msg(e))}finally{setSaving('')}}
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return !q?employees:employees.filter(x=>`${x.full_name} ${x.email||''} ${x.position_name||''} ${x.location_name||''}`.toLowerCase().includes(q))},[employees,query]);
 if(loading&&!config)return <div className="kta-loading">Kleo Team adminisztráció betöltése…</div>;
 const globalModules=config?.global_modules||config?.modules||{};
 return <main className="kta-page">
  <header className="kta-hero"><div><div className="kta-kicker">KLEO TEAM CONTROL CENTER</div><h1>Kleo Team adminisztráció</h1><p>Globális modulkapcsolók, munkatársi hozzáférések és a dolgozói portál központi vezérlése.</p></div><div className="kta-actions"><a href="/employee-app" target="_blank" rel="noreferrer"><ExternalLink size={16}/>Dolgozói portál</a><a href="/admin/saas?workspace=kleo-team-subscription"><WalletCards size={16}/>Előfizetés</a><button onClick={()=>void load()}><RefreshCw size={16}/>Frissítés</button></div></header>
  {error&&<div className="kta-alert error">{error}</div>}{notice&&<div className="kta-alert ok">{notice}</div>}
  <section className="kta-summary"><article><Users/><div><strong>{employees.length}</strong><span>aktív munkatárs</span></div></article><article><Settings2/><div><strong>{modules.filter(k=>globalModules[k]!==false).length}/{modules.length}</strong><span>globálisan aktív modul</span></div></article><article><ShieldCheck/><div><strong>{config?.enabled===false?'Kikapcsolva':'Aktív'}</strong><span>Kleo Team portál</span></div></article></section>
  <section className="kta-card"><div className="kta-card-head"><div><h2>Portál alapbeállításai</h2><p>Az itt megadott beállítás minden munkatársra érvényes.</p></div><label className="kta-master"><input type="checkbox" checked={config?.enabled!==false} onChange={e=>setConfig((c:any)=>({...c,enabled:e.target.checked}))}/><span>Portál engedélyezve</span></label></div><div className="kta-form-grid"><label>Megjelenő név<input value={config?.brand_name||'Kleo Team'} onChange={e=>setConfig((c:any)=>({...c,brand_name:e.target.value}))}/></label><label>Üdvözlő szöveg<input value={config?.welcome_message||''} onChange={e=>setConfig((c:any)=>({...c,welcome_message:e.target.value}))}/></label></div><button className="kta-primary" disabled={saving==='config'} onClick={()=>void saveConfig({enabled:config?.enabled!==false,brand_name:config?.brand_name,welcome_message:config?.welcome_message,modules:globalModules})}><Save size={16}/>{saving==='config'?'Mentés…':'Alapbeállítások mentése'}</button></section>
  <section className="kta-card"><div className="kta-card-head"><div><h2>Globális modulok</h2><p>Kikapcsolás után a modul egyetlen munkatársnál sem használható, még egyedi engedéllyel sem.</p></div></div><div className="kta-module-grid">{modules.map(key=><label key={key} className={`kta-module ${globalModules[key]===false?'off':''}`}><input type="checkbox" checked={globalModules[key]!==false} onChange={e=>{const next={...globalModules,[key]:e.target.checked};setConfig((c:any)=>({...c,global_modules:next,modules:next}));void saveConfig({enabled:config?.enabled!==false,brand_name:config?.brand_name,welcome_message:config?.welcome_message,modules:next})}}/><span><b>{LABELS[key]||key}</b><small>{globalModules[key]===false?'Kikapcsolva':'Engedélyezve'}</small></span></label>)}</div></section>
  <section className="kta-card"><div className="kta-card-head"><div><h2>Munkatársi hozzáférések</h2><p>Egyedileg letiltható bármely modul. Az üresen hagyott korábbi beállítás automatikusan a globális szabályt követi.</p></div><label className="kta-search"><Search size={16}/><input placeholder="Név, e-mail, munkakör vagy telephely" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="kta-table-wrap"><table><thead><tr><th>Munkatárs</th>{modules.map(k=><th key={k} title={LABELS[k]||k}>{(LABELS[k]||k).split(' ')[0]}</th>)}</tr></thead><tbody>{visible.map(emp=><tr key={emp.id}><td><b>{emp.full_name}</b><small>{[emp.position_name,emp.location_name].filter(Boolean).join(' • ')||emp.email||'—'}</small></td>{modules.map(key=>{const globalOn=globalModules[key]!==false,checked=emp.permissions?.[key]!==false&&globalOn,busy=saving===`${emp.id}:${key}`;return <td key={key}><input aria-label={`${emp.full_name} – ${LABELS[key]||key}`} type="checkbox" checked={checked} disabled={!globalOn||busy} onChange={e=>void setPermission(emp,key,e.target.checked)}/></td>})}</tr>)}</tbody></table></div>{!visible.length&&<div className="kta-empty">Nincs a keresésnek megfelelő munkatárs.</div>}</section>
  <section className="kta-card kta-note"><ShieldCheck/><div><h2>Jogosultsági modell</h2><p>A globális kapcsoló a felső korlát. A munkatársi kapcsoló csak olyan modult engedélyezhet, amely globálisan is aktív. A béradatok és értékelések self-service végpontjai kizárólag a bejelentkezett munkatárs saját rekordjait adják vissza.</p></div></section>
 </main>;
}