import React,{useEffect,useMemo,useState}from"react";
import{Bell,CalendarDays,ChevronRight,Clock3,Download,Gift,Home,LocateFixed,MapPin,Navigation,Scissors,Send,Star,WalletCards}from"lucide-react";
import api from"../api/api";import"./KleopatraMobileApp.css";
const LOGO="/kleopatra-logo.png";
const toKey=(v:string)=>{const p="=".repeat((4-v.length%4)%4),b=atob((v+p).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...b].map(x=>x.charCodeAt(0)))};
const km=(a:{lat:number;lng:number},b:any)=>{const r=(n:number)=>n*Math.PI/180,d1=r(+b.latitude-a.lat),d2=r(+b.longitude-a.lng),h=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(+b.latitude))*Math.sin(d2/2)**2;return 12742*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))};
const map=(s:any)=>{const a=+s.latitude,o=+s.longitude,d=.009;return`https://www.openstreetmap.org/export/embed.html?bbox=${o-d}%2C${a-d}%2C${o+d}%2C${a+d}&layer=mapnik&marker=${a}%2C${o}`};
export default function KleopatraMobileApp(){
 const[data,setData]=useState<any>({actions:[]}),[salons,setSalons]=useState<any[]>([]),[selected,setSelected]=useState<any>(),[reviews,setReviews]=useState<any[]>([]),[pos,setPos]=useState<any>(),[install,setInstall]=useState<any>(),[enabled,setEnabled]=useState(typeof Notification!=="undefined"&&Notification.permission==="granted"),[review,setReview]=useState({guest_name:"",rating:0,comment:""}),[message,setMessage]=useState("");
 useEffect(()=>{api.get("/public/marketing/daily-actions").then(r=>setData(r.data)).catch(()=>{});api.get("/public/marketing/salons").then(r=>{setSalons(r.data||[]);setSelected(r.data?.[0])}).catch(()=>{});const h=(e:any)=>{e.preventDefault();setInstall(e)};window.addEventListener("beforeinstallprompt",h);return()=>window.removeEventListener("beforeinstallprompt",h)},[]);
 useEffect(()=>{if(selected)api.get(`/public/marketing/salons/${selected.id}/reviews`).then(r=>setReviews(r.data||[])).catch(()=>setReviews([]))},[selected]);
 const ordered=useMemo(()=>salons.map(s=>({...s,distance_km:pos?km(pos,s):null})).sort((a,b)=>(a.distance_km??9999)-(b.distance_km??9999)),[salons,pos]);
 async function notify(){try{if(typeof Notification==="undefined")return;const p=await Notification.requestPermission();if(p!=="granted")return;const reg=await navigator.serviceWorker.ready;if(data.vapid_public_key){const subscription=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:toKey(data.vapid_public_key)});await api.post("/public/marketing/daily-actions/subscribe",{subscription})}setEnabled(true);new Notification("Kleopátra",{body:"Az értesítések aktívak.",icon:"/logo192.png"})}catch{}}
 function locate(){setMessage("Helyzet meghatározása…");navigator.geolocation?.getCurrentPosition(r=>{const p={lat:r.coords.latitude,lng:r.coords.longitude};setPos(p);const closest=[...salons].sort((a,b)=>km(p,a)-km(p,b))[0];if(closest)setSelected({...closest,distance_km:km(p,closest)});setMessage("Távolság szerint rendeztük a szalonokat.")},()=>setMessage("A távolsághoz engedélyezze a helyhozzáférést."),{enableHighAccuracy:true,timeout:10000})}
 async function submit(e:React.FormEvent){e.preventDefault();try{const r=await api.post(`/public/marketing/salons/${selected.id}/reviews`,review);setMessage(r.data.message);setReview({guest_name:"",rating:0,comment:""})}catch(x:any){setMessage(x?.response?.data?.message||"A küldés sikertelen.")}}
 return <main className="kapp"><header className="kapp-header"><a href="#home"><img src={LOGO} alt="Kleopátra Szépségszalonok"/></a><div>{install&&<button onClick={()=>install.prompt()}><Download/><span>Telepítés</span></button>}<button className={enabled?"enabled":""} onClick={notify}><Bell/><span>{enabled?"Értesítések aktívak":"Értesítések"}</span></button></div></header>
 <section id="home" className="kapp-hero"><div><small>KLEOPÁTRA BEAUTY CLUB</small><h1>Szépség, személyesen.</h1><p>Foglalás, szalonok, exkluzív ajánlatok és hűségelőnyök egy letisztult alkalmazásban.</p><a href="/foglalas"><CalendarDays/>Időpontot foglalok</a></div><div className="kapp-hero-logo"><img src={LOGO} alt=""/></div></section>
 <section className="kapp-quick"><a href="/foglalas"><Scissors/><span><b>Gyors foglalás</b><small>Néhány egyszerű lépés</small></span><ChevronRight/></a><button><WalletCards/><span><b>Beauty Pass</b><small>Bérletek és pontok</small></span><ChevronRight/></button><button><Gift/><span><b>Ajándékok</b><small>Kuponok és utalványok</small></span><ChevronRight/></button><a href="#salons"><MapPin/><span><b>Szalonok</b><small>Legközelebbi helyszín</small></span><ChevronRight/></a></section>
 <section className="kapp-block kapp-deals"><header><div><small>ÖNNEK VÁLOGATVA</small><h2>Napi akciók</h2></div><span>{data.actions.length} aktív ajánlat</span></header><div>{data.actions.length?data.actions.map((x:any)=><article key={x.id}>{x.image_url&&<img src={x.image_url} alt=""/>}<div><small>KLEOPÁTRA EXKLUZÍV</small><h3>{x.headline}</h3><strong>{x.discount_text}</strong><div dangerouslySetInnerHTML={{__html:x.description_html}}/><a href={x.cta_url||"/foglalas"}>{x.cta_label||"Foglalok"}</a></div></article>):<article className="empty-deal"><img src={LOGO} alt="Kleopátra"/><div><h3>A következő meglepetés készül</h3><p>Kapcsolja be az értesítéseket, hogy elsőként értesüljön.</p></div></article>}</div></section>
 <section id="salons" className="kapp-block kapp-salons"><header><div><small>HELYSZÍNEINK</small><h2>A legközelebbi Kleopátra</h2></div><button onClick={locate}><LocateFixed/>Távolság meghatározása</button></header>{message&&<p className="kapp-message">{message}</p>}<div className="kapp-salon-layout"><aside>{ordered.map(s=><button key={s.id} className={selected?.id===s.id?"active":""} onClick={()=>setSelected(s)}><MapPin/><span><b>{s.city_label}</b><small>{s.address}</small>{s.distance_km!=null&&<em>{s.distance_km<1?`${Math.round(s.distance_km*1000)} m`:`${s.distance_km.toFixed(1)} km`} Öntől</em>}</span><ChevronRight/></button>)}</aside>{selected&&<article className="kapp-salon-card"><iframe title={`${selected.city_label} térkép`} src={map(selected)} loading="lazy"/><div><img src={LOGO} alt="Kleopátra"/><small>KLEOPÁTRA SZÉPSÉGSZALON</small><h3>{selected.city_label}</h3><p><MapPin/>{selected.address}</p><p><Clock3/>{selected.hours}</p><div className="kapp-rating"><Star/><b>{selected.rating||"Új"}</b><span>{selected.review_count||0} vélemény</span></div><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}`}><Navigation/>Útvonaltervezés</a></div></article>}</div></section>
 {selected&&<section id="reviews" className="kapp-block kapp-reviews"><header><div><small>VENDÉGEINK MONDTÁK</small><h2>Vélemények</h2></div></header><div className="kapp-review-grid"><form onSubmit={submit}><h3>Értékelje a(z) {selected.city_label} szalont</h3><div className="kapp-stars">{[1,2,3,4,5].map(n=><button type="button" className={n<=review.rating?"on":""} onClick={()=>setReview({...review,rating:n})} key={n} aria-label={`${n} csillag`}><Star/></button>)}</div><label>Név<input value={review.guest_name} onChange={e=>setReview({...review,guest_name:e.target.value})}/></label><label>Vélemény<textarea value={review.comment} onChange={e=>setReview({...review,comment:e.target.value})}/></label><button className="submit"><Send/>Vélemény elküldése</button><small>Moderáció után jelenik meg.</small></form><div className="kapp-review-list">{reviews.length?reviews.map(x=><article key={x.id}><div><span>{x.guest_name[0]}</span><b>{x.guest_name}</b><em>{"★".repeat(x.rating)}{"☆".repeat(5-x.rating)}</em></div><p>{x.comment}</p><small>{new Date(x.created_at).toLocaleDateString("hu-HU")}</small></article>):<div className="no-review"><Star/><h3>Legyen Ön az első értékelő!</h3><p>Ossza meg tapasztalatát.</p></div>}</div></div></section>}
 <nav><a href="#home" className="active"><Home/><span>Kezdőlap</span></a><a href="/foglalas"><CalendarDays/><span>Foglalás</span></a><a href="#salons"><MapPin/><span>Szalonok</span></a><a href="#reviews"><Star/><span>Vélemények</span></a></nav></main>}
