import React,{useEffect,useMemo,useState}from"react";
import{Award,BookOpenText,CheckCircle2,ExternalLink,FileCheck2,GraduationCap,RefreshCw,ShieldCheck}from"lucide-react";
import{useLocation,useNavigate}from"react-router-dom";
import api from"../api/api";
import{hasStoredRole}from"../utils/roles";
import VirCustomizerPage from"./VirCustomizerPage";
import"./KnowledgeBasePage.css";

const em=(e:any)=>e?.response?.data?.message||e?.message||"A tudásbázis nem tölthető be.";
type Tab="library"|"processes"|"quiz"|"vir";
type Level="beginner"|"advanced"|"expert";
const levelKeys:Level[]=["beginner","advanced","expert"];
const validLevel=(x:string|null):Level=>levelKeys.includes(x as Level)?x as Level:"beginner";
export default function KnowledgeBasePage(){
 const nav=useNavigate(),loc=useLocation(),admin=hasStoredRole(["admin","manager"]),query=new URLSearchParams(loc.search);
 const tab:Tab=query.get("tab")==="vir"&&admin?"vir":loc.pathname.endsWith("/processes")?"processes":loc.pathname.endsWith("/quiz")?"quiz":"library";
 const initialLevel=validLevel(query.get("level"));
 const[data,setData]=useState<any>({materials:[],processes:[],attempts:[],sources:[]}),[quiz,setQuiz]=useState<any[]>([]),[quizMeta,setQuizMeta]=useState<any>({}),[answers,setAnswers]=useState<Record<string,number>>({}),[result,setResult]=useState<any>(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const[level,setLevel]=useState<Level>(initialLevel),[profession,setProfession]=useState(query.get("profession")||""),[materialLevel,setMaterialLevel]=useState<"all"|Level>(query.get("level")?initialLevel:"all");
 async function load(nextProfession=profession,nextLevel:Level=level){setBusy(true);setMessage("");try{const params=nextProfession?{profession:nextProfession}:{},[d,q]=await Promise.all([api.get("/transactions/knowledge-base",{params}),api.get("/transactions/knowledge-base/quiz",{params:{...params,level:nextLevel}})]);setData(d.data);setQuiz(q.data.questions||[]);setQuizMeta(q.data);if(!nextProfession&&q.data?.profession?.key)setProfession(q.data.profession.key)}catch(e){setMessage(em(e))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function selectLevel(next:Level){setLevel(next);setAnswers({});setResult(undefined);await load(profession,next)}
 async function selectProfession(next:string){setProfession(next);setAnswers({});setResult(undefined);await load(next,level)}
 async function submit(){setBusy(true);setMessage("");try{const r=await api.post("/transactions/knowledge-base/quiz/submit",{answers,level,profession});setResult(r.data);setMessage(`${r.data?.profession?.label||"Munkaköri"} · ${r.data?.level_label||""} teszt eredménye bekerült az aktuális havi minősítésbe.`);await load(profession,level)}catch(e){setMessage(em(e))}finally{setBusy(false)}}
 const sourceByCode=useMemo(()=>new Map((data.sources||[]).map((s:any)=>[s.code,s])),[data.sources]);
 const categories=useMemo(()=>Array.from(new Set((quiz||[]).map((q:any)=>q.topic))).filter(Boolean),[quiz]);
 const shownMaterials=useMemo(()=>(data.materials||[]).filter((x:any)=>materialLevel==="all"||x.level===materialLevel),[data.materials,materialLevel]);
 const levels=(quizMeta.available_levels?.length?quizMeta.available_levels:data.academy_levels)||levelKeys.map(key=>({key,label:key==="beginner"?"Kezdő":key==="advanced"?"Haladó":"Szakértő"}));
 const professions=(quizMeta.available_professions?.length?quizMeta.available_professions:data.available_professions)||[];
 const materialLink=`/knowledge-base/library?profession=${encodeURIComponent(profession||quizMeta.profession?.key||"")}&level=${level}`;
 if(tab==="vir"&&admin)return <VirCustomizerPage/>;
 return <div className="kb">
  <header><div><small>KLEOPÁTRA BELSŐ AKADÉMIA</small><h1><BookOpenText/>Tudástár és munkaköri akadémia</h1><p>{data.profession?.label||data.employee?.position_name||data.role||"Munkatárs"} számára összeállított, forrásolt szakmai anyagok és háromszintű tudásellenőrzés.</p></div><button onClick={()=>void load()}><RefreshCw className={busy?"spin":""}/>Frissítés</button></header>
  {message&&<div className="kb-message">{message}</div>}
  <nav><button className={tab==="library"?"active":""} onClick={()=>nav("/knowledge-base/library")}><GraduationCap/>Tudásanyagok</button><button className={tab==="processes"?"active":""} onClick={()=>nav("/knowledge-base/processes")}><FileCheck2/>Folyamatok</button><button className={tab==="quiz"?"active":""} onClick={()=>nav("/knowledge-base/quiz")}><Award/>Munkaköri teszt</button></nav>
  {(professions.length>1||data.profession?.label)&&<section className="kb-academy-toolbar">{professions.length>1&&<label><span>Szakma / munkakör</span><select value={profession||quizMeta.profession?.key||""} onChange={e=>void selectProfession(e.target.value)}>{professions.map((p:any)=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label>}<div className="kb-current-profession"><b>{quizMeta.profession?.label||data.profession?.label}</b><span>{quizMeta.profession?.category||data.profession?.category}</span></div></section>}
  {tab==="library"&&<><section className="kb-source-note"><ShieldCheck/><div><b>Forrásolt szakmai tudástár</b><span>IKK, NNGYK, EU-OSHA, ECHA, EUR-Lex, Európai Bizottság, NAIH/GDPR és NAV elsődleges forrásokkal. A kivonatok belső oktatást szolgálnak; a hatályos jogszabály, szakmai KKK, kompetenciahatár és gyártói előírás elsőbbséget élvez.</span></div></section><div className="kb-library-toolbar"><b>Tananyagszint</b><div className="kb-levels"><button className={materialLevel==="all"?"active":""} onClick={()=>setMaterialLevel("all")}>Összes <small>{data.materials?.length||0}</small></button>{levels.map((x:any)=><button key={x.key} className={materialLevel===x.key?"active":""} onClick={()=>setMaterialLevel(x.key)}>{x.label}<small>{(data.materials||[]).filter((m:any)=>m.level===x.key).length}</small></button>)}</div></div><section className="kb-grid">{shownMaterials.map((x:any)=><article key={x.code}><div className="kb-card-tags"><span>{x.category}</span><b className={`kb-level-badge ${x.level||""}`}>{x.level_label||"Kezdő"}</b></div><h2>{x.title}</h2><p>{x.summary}</p>{x.learning_points?.length>0&&<ul>{x.learning_points.map((p:string)=><li key={p}>{p}</li>)}</ul>}<footer><code>{x.code}</code>{x.source?.url?<a href={x.source.url} target="_blank" rel="noreferrer" title={x.source.authority}>{x.source.authority}<ExternalLink/></a>:<em>{x.source_code}</em>}</footer></article>)}</section>{shownMaterials.length===0&&<div className="kb-empty">Ehhez a szinthez még nincs megjeleníthető tananyag.</div>}<section className="kb-sources"><h2>Felhasznált szakmai források</h2>{Array.from(sourceByCode.values()).map((s:any)=><a key={s.code} href={s.url} target="_blank" rel="noreferrer"><b>{s.name}</b><span>{s.authority} · ellenőrizve: {s.reviewed_at}</span><ExternalLink/></a>)}</section></>}
  {tab==="processes"&&<section className="kb-processes">{data.processes.map((x:any)=><article key={x.code}><header><ShieldCheck/><div><small>{x.code}</small><h2>{x.title}</h2></div></header><ol>{x.steps.map((s:string)=><li key={s}><CheckCircle2/>{s}</li>)}</ol></article>)}</section>}
  {tab==="quiz"&&<section className="kb-quiz"><div className="kb-quiz-selector"><div><b>Tesztszint</b><div className="kb-levels">{levels.map((x:any)=><button key={x.key} className={level===x.key?"active":""} onClick={()=>void selectLevel(x.key)}><span>{x.label}</span><small>{x.question_count??""} kérdés</small></button>)}</div></div><button className="kb-study-link" onClick={()=>{setMaterialLevel(level);nav(materialLink)}}><BookOpenText/>Kapcsolódó tananyagok</button></div><header><div><h2>{quizMeta.profession?.label||"Munkaköri"} – {quizMeta.level_label||"Kezdő"} teszt</h2><p>Munkakör: <b>{quizMeta.role||data.role||"Munkatárs"}</b> · Küszöb: {quizMeta.pass_percent||80}% · Verzió: {quizMeta.quiz_version||"v29"} · Kérdések: {quiz.length}</p>{categories.length>0&&<small>Témák: {categories.join(" · ")}</small>}</div>{data.attempts?.[0]&&<strong>Legutóbbi: {Number(data.attempts[0].score)}%</strong>}</header>{quiz.map((q:any,i:number)=><fieldset key={q.id}><legend>{i+1}. {q.q}</legend><small>{q.topic}</small>{q.answers.map((a:string,j:number)=><label key={`${q.id}-${j}`}><input type="radio" name={q.id} checked={answers[q.id]===j} onChange={()=>setAnswers(prev=>({...prev,[q.id]:j}))}/><span>{a}</span></label>)}</fieldset>)}{result&&<><div className={result.passed?"kb-result pass":"kb-result fail"}><Award/><b>{result.score}%</b><span>{result.correct}/{result.total} helyes válasz · {result.passed?"Megfelelt":"Ismétlés szükséges"}</span></div><div className="kb-review">{result.review?.map((r:any)=><article className={r.correct?"ok":"bad"} key={r.id}><b>{r.correct?"Helyes":"Javítandó"}</b><p>{r.explanation}</p>{r.source?.url&&<a href={r.source.url} target="_blank" rel="noreferrer">Szakmai forrás <ExternalLink/></a>}</article>)}</div></>}<button className="kb-submit" disabled={busy||quiz.length===0||!quiz.every((q:any)=>answers[q.id]!==undefined)} onClick={submit}>Teszt lezárása és minősítés mentése</button></section>}
 </div>;
}
