import React,{useEffect,useMemo,useState}from"react";
import{Award,BookOpenText,CheckCircle2,ExternalLink,FileCheck2,GraduationCap,RefreshCw,ShieldCheck,SlidersHorizontal}from"lucide-react";
import{useLocation,useNavigate}from"react-router-dom";
import api from"../api/api";
import{hasStoredRole}from"../utils/roles";
import VirCustomizerPage from"./VirCustomizerPage";
import"./KnowledgeBasePage.css";

const em=(e:any)=>e?.response?.data?.message||e?.message||"A tudásbázis nem tölthető be.";
type Tab="library"|"processes"|"quiz"|"vir";
export default function KnowledgeBasePage(){
 const nav=useNavigate(),loc=useLocation(),admin=hasStoredRole(["admin","manager"]),query=new URLSearchParams(loc.search);
 const tab:Tab=query.get("tab")==="vir"&&admin?"vir":loc.pathname.endsWith("/processes")?"processes":loc.pathname.endsWith("/quiz")?"quiz":"library";
 const[data,setData]=useState<any>({materials:[],processes:[],attempts:[],sources:[]}),[quiz,setQuiz]=useState<any[]>([]),[quizMeta,setQuizMeta]=useState<any>({}),[answers,setAnswers]=useState<Record<string,number>>({}),[result,setResult]=useState<any>(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){setBusy(true);setMessage("");try{const[d,q]=await Promise.all([api.get("/transactions/knowledge-base"),api.get("/transactions/knowledge-base/quiz")]);setData(d.data);setQuiz(q.data.questions||[]);setQuizMeta(q.data)}catch(e){setMessage(em(e))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function submit(){setBusy(true);setMessage("");try{const r=await api.post("/transactions/knowledge-base/quiz/submit",{answers});setResult(r.data);setMessage("Az eredmény bekerült az aktuális havi minősítésbe.");await load()}catch(e){setMessage(em(e))}finally{setBusy(false)}}
 const sourceByCode=useMemo(()=>new Map((data.sources||[]).map((s:any)=>[s.code,s])),[data.sources]);
 const categories=useMemo(()=>Array.from(new Set((quiz||[]).map((q:any)=>q.topic))).filter(Boolean),[quiz]);
 return <div className="kb">
  <header><div><small>KLEOPÁTRA BELSŐ AKADÉMIA</small><h1><BookOpenText/>Tudástár és munkaköri akadémia</h1><p>{data.employee?.position_name||data.role||"Munkatárs"} számára összeállított, forrásolt szakmai anyagok és munkaköri tudásellenőrzés.</p></div><button onClick={load}><RefreshCw className={busy?"spin":""}/>Frissítés</button></header>
  {message&&<div className="kb-message">{message}</div>}
  <nav><button className={tab==="library"?"active":""} onClick={()=>nav("/knowledge-base/library")}><GraduationCap/>Tudásanyagok</button><button className={tab==="processes"?"active":""} onClick={()=>nav("/knowledge-base/processes")}><FileCheck2/>Folyamatok</button><button className={tab==="quiz"?"active":""} onClick={()=>nav("/knowledge-base/quiz")}><Award/>Munkaköri teszt</button>{admin&&<button className={tab==="vir"?"active":""} onClick={()=>nav("/knowledge-base/library?tab=vir")}><SlidersHorizontal/>VIR Admin</button>}</nav>
  {tab==="library"&&<><section className="kb-source-note"><ShieldCheck/><div><b>Forrásolt szakmai tudástár</b><span>IKK, NNGYK, EU-OSHA, NAIH és NAV elsődleges forrásokkal. A kivonatok belső oktatást szolgálnak; a hatályos jogszabály, szakmai KKK és gyártói előírás elsőbbséget élvez.</span></div></section><section className="kb-grid">{data.materials.map((x:any)=><article key={x.code}><span>{x.category}</span><h2>{x.title}</h2><p>{x.summary}</p>{x.learning_points?.length>0&&<ul>{x.learning_points.map((p:string)=><li key={p}>{p}</li>)}</ul>}<footer><code>{x.code}</code>{x.source?.url?<a href={x.source.url} target="_blank" rel="noreferrer" title={x.source.authority}>{x.source.authority}<ExternalLink/></a>:<em>{x.source_code}</em>}</footer></article>)}</section><section className="kb-sources"><h2>Felhasznált szakmai források</h2>{Array.from(sourceByCode.values()).map((s:any)=><a key={s.code} href={s.url} target="_blank" rel="noreferrer"><b>{s.name}</b><span>{s.authority} · ellenőrizve: {s.reviewed_at}</span><ExternalLink/></a>)}</section></>}
  {tab==="processes"&&<section className="kb-processes">{data.processes.map((x:any)=><article key={x.code}><header><ShieldCheck/><div><small>{x.code}</small><h2>{x.title}</h2></div></header><ol>{x.steps.map((s:string)=><li key={s}><CheckCircle2/>{s}</li>)}</ol></article>)}</section>}
  {tab==="quiz"&&<section className="kb-quiz"><header><div><h2>Munkaköri tudásellenőrzés</h2><p>Munkakör: <b>{quizMeta.role||data.role||"Munkatárs"}</b> · Küszöb: {quizMeta.pass_percent||80}% · Verzió: {quizMeta.quiz_version||"v28"} · Kérdések: {quiz.length}</p>{categories.length>0&&<small>Témák: {categories.join(" · ")}</small>}</div>{data.attempts?.[0]&&<strong>Legutóbbi: {Number(data.attempts[0].score)}%</strong>}</header>{quiz.map((q:any,i:number)=><fieldset key={q.id}><legend>{i+1}. {q.q}</legend><small>{q.topic}</small>{q.answers.map((a:string,j:number)=><label key={`${q.id}-${j}`}><input type="radio" name={q.id} checked={answers[q.id]===j} onChange={()=>setAnswers(prev=>({...prev,[q.id]:j}))}/><span>{a}</span></label>)}</fieldset>)}{result&&<><div className={result.passed?"kb-result pass":"kb-result fail"}><Award/><b>{result.score}%</b><span>{result.correct}/{result.total} helyes válasz · {result.passed?"Megfelelt":"Ismétlés szükséges"}</span></div><div className="kb-review">{result.review?.map((r:any)=><article className={r.correct?"ok":"bad"} key={r.id}><b>{r.correct?"Helyes":"Javítandó"}</b><p>{r.explanation}</p>{r.source?.url&&<a href={r.source.url} target="_blank" rel="noreferrer">Szakmai forrás <ExternalLink/></a>}</article>)}</div></>}<button className="kb-submit" disabled={busy||quiz.length===0||!quiz.every((q:any)=>answers[q.id]!==undefined)} onClick={submit}>Kvíz lezárása és minősítés mentése</button></section>}
  {tab==="vir"&&admin&&<VirCustomizerPage/>}
 </div>;
}
