import React,{useEffect,useMemo,useState}from'react';
import{Building2,CheckCircle2,CircleDollarSign,Edit3,Landmark,Plus,RefreshCw,Save,ShieldCheck,Store,Upload}from'lucide-react';
import api from'../api';
import LegalEntityImportDialog from'../components/LegalEntityImportDialog';
import{hasStoredRole}from'../utils/roles';

type Location={id:string;name:string;city?:string|null};
type EntityLocation={id:string;name:string;city?:string|null;is_default?:boolean};
type Entity={id:string;entity_type:'COMPANY'|'SOLE_PROPRIETOR'|'OTHER';legal_name:string;short_name?:string|null;legal_form?:string|null;tax_number:string;group_tax_number?:string|null;eu_vat_number?:string|null;company_register_number?:string|null;sole_proprietor_registration_number?:string|null;statistical_number?:string|null;registered_country_code:string;registered_postal_code:string;registered_city:string;registered_address_line:string;main_activity_code?:string|null;main_activity_name?:string|null;representative_name?:string|null;representative_title?:string|null;bank_account_number?:string|null;iban?:string|null;bic?:string|null;official_email?:string|null;phone?:string|null;currency:string;default_vat_rate:number;invoice_prefix:string;receipt_prefix:string;accounting_ledger_code:string;active:boolean;locations?:EntityLocation[]};
type Summary={income:number;expense:number;balance:number;movement_count:number;invoice_count:number;invoice_gross:number;work_order_count:number;work_order_gross:number;from:string;to:string};
type Draft=Omit<Entity,'id'|'locations'>&{location_ids:string[];default_for_location_ids:string[]};
const empty=():Draft=>({entity_type:'COMPANY',legal_name:'',short_name:'',legal_form:'Kft.',tax_number:'',group_tax_number:'',eu_vat_number:'',company_register_number:'',sole_proprietor_registration_number:'',statistical_number:'',registered_country_code:'HU',registered_postal_code:'',registered_city:'',registered_address_line:'',main_activity_code:'',main_activity_name:'',representative_name:'',representative_title:'',bank_account_number:'',iban:'',bic:'',official_email:'',phone:'',currency:'HUF',default_vat_rate:27,invoice_prefix:'KLEO',receipt_prefix:'KLEO-NY',accounting_ledger_code:'',active:true,location_ids:[],default_for_location_ids:[]});
const money=(v:any)=>`${new Intl.NumberFormat('hu-HU',{maximumFractionDigits:0}).format(Number(v||0))} Ft`;
const errorText=(e:any)=>{const d=e?.response?.data;return[d?.message,...(Array.isArray(d?.errors)?d.errors:[])].filter(Boolean).join(' · ')||e?.message||'A művelet nem sikerült.'};
const card:React.CSSProperties={background:'#fff',border:'1px solid #e2e8f0',borderRadius:16,padding:18,boxShadow:'0 8px 24px rgba(15,23,42,.04)'};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',minHeight:40,border:'1px solid #cbd5e1',borderRadius:9,padding:'8px 10px',background:'#fff'};
const label:React.CSSProperties={display:'grid',gap:5,fontSize:12,fontWeight:800,color:'#334155'};
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12};

export default function LegalEntitiesSettingsPage(){
 const admin=hasStoredRole(['admin']);
 const[entities,setEntities]=useState<Entity[]>([]),[locations,setLocations]=useState<Location[]>([]),[selectedId,setSelectedId]=useState(''),[draft,setDraft]=useState<Draft>(empty()),[summary,setSummary]=useState<Summary|null>(null);
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[importOpen,setImportOpen]=useState(false);
 const selected=useMemo(()=>entities.find(x=>String(x.id)===selectedId)||null,[entities,selectedId]);
 async function load(){setLoading(true);setError('');try{const[e,l]=await Promise.all([api.get('/vir/receipt-compliance/legal-entities',{params:{include_inactive:1}}),api.get('/locations')]);const er=Array.isArray(e.data?.rows)?e.data.rows:[],lr=Array.isArray(l.data)?l.data:Array.isArray(l.data?.locations)?l.data.locations:[];setEntities(er);setLocations(lr.map((x:any)=>({id:String(x.id),name:String(x.name||'Szalon'),city:x.city||null})));}catch(e){setError(errorText(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selected){setSummary(null);return}const locs=Array.isArray(selected.locations)?selected.locations:[];setDraft({...empty(),...selected,location_ids:locs.map(x=>String(x.id)),default_for_location_ids:locs.filter(x=>x.is_default).map(x=>String(x.id))});void api.get(`/vir/receipt-compliance/legal-entities/${encodeURIComponent(selected.id)}/accounting/summary`).then(r=>setSummary(r.data)).catch(()=>setSummary(null));},[selected]);
 function patch<K extends keyof Draft>(k:K,v:Draft[K]){setDraft(d=>({...d,[k]:v}))}
 function newEntity(){setSelectedId('');setSummary(null);setDraft(empty());setNotice('Új cég rögzítése. A csillaggal jelölt mezők kitöltése kötelező.')}
 function toggleLocation(id:string){setDraft(d=>{const has=d.location_ids.includes(id),location_ids=has?d.location_ids.filter(x=>x!==id):[...d.location_ids,id],default_for_location_ids=d.default_for_location_ids.filter(x=>location_ids.includes(x));return{...d,location_ids,default_for_location_ids}})}
 function toggleDefault(id:string){setDraft(d=>{if(!d.location_ids.includes(id))return d;const has=d.default_for_location_ids.includes(id);return{...d,default_for_location_ids:has?d.default_for_location_ids.filter(x=>x!==id):[...d.default_for_location_ids,id]}})}
 async function save(){if(!admin)return;setSaving(true);setError('');setNotice('');try{const payload={...draft,tax_number:String(draft.tax_number||'').replace(/\D/g,''),group_tax_number:String(draft.group_tax_number||'').replace(/\D/g,'')||null};const r=selectedId?await api.put(`/vir/receipt-compliance/legal-entities/${encodeURIComponent(selectedId)}`,payload):await api.post('/vir/receipt-compliance/legal-entities',payload);setNotice(`${r.data?.entity?.legal_name||draft.legal_name} mentve. A cégdimenzió a munkalapokra, pénzügyi tételekre, számlákra és nyugtákra is érvényes.`);await load();if(!selectedId&&r.data?.entity?.id)setSelectedId(String(r.data.entity.id));}catch(e){setError(errorText(e))}finally{setSaving(false)}}
 async function imported(message:string){setSelectedId('');setNotice(message);await load()}
 return <main style={{maxWidth:1500,margin:'0 auto',padding:'26px 28px 70px',background:'#f8fafc',minHeight:'100vh'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap',marginBottom:18}}><div><small style={{fontWeight:900,color:'#6d28d9',letterSpacing:'.09em'}}>BEÁLLÍTÁSOK · CÉGTÖRZS · KÖNYVELÉS</small><h1 style={{margin:'5px 0',display:'flex',gap:10,alignItems:'center'}}><Building2/>Cégek és könyvelési egységek</h1><p style={{maxWidth:920,color:'#64748b',margin:0}}>Több jogi személy vagy egyéni vállalkozó kezelése egy VIR-ben. A céghez szalonok rendelhetők, szalononként alapértelmezett kibocsátó adható meg, és minden könyvelési tétel külön cégdimenziót kap.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>void load()} style={{...input,width:'auto',fontWeight:800,cursor:'pointer'}}><RefreshCw size={15}/> Frissítés</button>{admin&&<button type="button" onClick={()=>setImportOpen(true)} style={{border:'1px solid #7c3aed',borderRadius:10,padding:'10px 14px',background:'#f5f3ff',color:'#5b21b6',fontWeight:900,cursor:'pointer',display:'inline-flex',gap:7,alignItems:'center'}}><Upload size={16}/> Import</button>}{admin&&<button onClick={newEntity} style={{border:0,borderRadius:10,padding:'10px 14px',background:'#5b21b6',color:'#fff',fontWeight:900,cursor:'pointer'}}><Plus size={16}/> Új cég</button>}</div></header>
  {error&&<div style={{...card,borderColor:'#fecaca',background:'#fff1f2',color:'#b91c1c',marginBottom:14,fontWeight:700}}>{error}</div>}{notice&&<div style={{...card,borderColor:'#bbf7d0',background:'#f0fdf4',color:'#166534',marginBottom:14,fontWeight:700}}><CheckCircle2 size={17}/> {notice}</div>}
  <section style={{display:'grid',gridTemplateColumns:'minmax(270px,360px) minmax(0,1fr)',gap:16,alignItems:'start'}}>
   <aside style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{margin:'0 0 10px'}}>Nyilvántartott cégek</h2><b>{entities.length}</b></div>{loading?<p>Betöltés…</p>:entities.map(e=><button key={e.id} onClick={()=>setSelectedId(String(e.id))} style={{width:'100%',textAlign:'left',border:selectedId===String(e.id)?'2px solid #7c3aed':'1px solid #e2e8f0',background:e.active?'#fff':'#f8fafc',borderRadius:11,padding:11,marginBottom:8,cursor:'pointer'}}><b style={{display:'block'}}>{e.short_name||e.legal_name}</b><small style={{display:'block',color:'#64748b'}}>Adószám: {e.tax_number} · {e.accounting_ledger_code}</small><small style={{display:'block',color:'#64748b'}}>{(e.locations||[]).map(l=>l.name).join(', ')||'Nincs szalon'}</small></button>)}</aside>
   <div style={{display:'grid',gap:16}}>
    <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><h2 style={{margin:'0 0 4px'}}>{selected?<><Edit3 size={18}/> {selected.legal_name}</>:'Új cég törzsadatai'}</h2><small style={{color:'#64748b'}}>A jogi forma alapján releváns nyilvántartási azonosító kötelező; a számlázási/nyugta- és könyvelési mezők elkülönítik az egyes cégek bizonylatait.</small></div>{admin&&<button onClick={()=>void save()} disabled={saving} style={{border:0,borderRadius:10,padding:'10px 15px',background:'#166534',color:'#fff',fontWeight:900,cursor:'pointer'}}><Save size={16}/> {saving?'Mentés…':'Mentés'}</button>}</div>
     <h3>Jogi azonosítók</h3><div style={grid}><label style={label}>Szervezettípus*<select style={input} value={draft.entity_type} onChange={e=>patch('entity_type',e.target.value as Draft['entity_type'])}><option value="COMPANY">Cég / gazdasági társaság</option><option value="SOLE_PROPRIETOR">Egyéni vállalkozó</option><option value="OTHER">Egyéb szervezet</option></select></label><Field name="Hivatalos név*" value={draft.legal_name} onChange={v=>patch('legal_name',v)}/><Field name="Rövid név" value={draft.short_name||''} onChange={v=>patch('short_name',v)}/><Field name="Jogi forma" value={draft.legal_form||''} onChange={v=>patch('legal_form',v)}/><Field name="Adószám (11 számjegy)*" value={draft.tax_number} onChange={v=>patch('tax_number',v)}/><Field name="Csoportos adószám" value={draft.group_tax_number||''} onChange={v=>patch('group_tax_number',v)}/><Field name="EU közösségi adószám" value={draft.eu_vat_number||''} onChange={v=>patch('eu_vat_number',v)}/>{draft.entity_type==='COMPANY'&&<Field name="Cégjegyzékszám*" value={draft.company_register_number||''} onChange={v=>patch('company_register_number',v)}/>} {draft.entity_type==='SOLE_PROPRIETOR'&&<Field name="EV nyilvántartási szám*" value={draft.sole_proprietor_registration_number||''} onChange={v=>patch('sole_proprietor_registration_number',v)}/>}<Field name="Statisztikai számjel" value={draft.statistical_number||''} onChange={v=>patch('statistical_number',v)}/></div>
     <h3>Székhely és tevékenység</h3><div style={grid}><Field name="Országkód*" value={draft.registered_country_code} onChange={v=>patch('registered_country_code',v.toUpperCase())}/><Field name="Irányítószám*" value={draft.registered_postal_code} onChange={v=>patch('registered_postal_code',v)}/><Field name="Város*" value={draft.registered_city} onChange={v=>patch('registered_city',v)}/><Field name="Közterület / házszám*" value={draft.registered_address_line} onChange={v=>patch('registered_address_line',v)}/><Field name="Főtevékenység TEÁOR/ÖVTJ" value={draft.main_activity_code||''} onChange={v=>patch('main_activity_code',v)}/><Field name="Főtevékenység megnevezése" value={draft.main_activity_name||''} onChange={v=>patch('main_activity_name',v)}/></div>
     <h3>Képviselet, bank és kapcsolattartás</h3><div style={grid}><Field name="Képviselő neve" value={draft.representative_name||''} onChange={v=>patch('representative_name',v)}/><Field name="Képviselő tisztsége" value={draft.representative_title||''} onChange={v=>patch('representative_title',v)}/><Field name="Belföldi bankszámlaszám" value={draft.bank_account_number||''} onChange={v=>patch('bank_account_number',v)}/><Field name="IBAN" value={draft.iban||''} onChange={v=>patch('iban',v)}/><Field name="BIC/SWIFT" value={draft.bic||''} onChange={v=>patch('bic',v)}/><Field name="Hivatalos e-mail" value={draft.official_email||''} onChange={v=>patch('official_email',v)}/><Field name="Telefon" value={draft.phone||''} onChange={v=>patch('phone',v)}/></div>
     <h3>Bizonylat és külön könyvelés</h3><div style={grid}><Field name="Könyvelési azonosító*" value={draft.accounting_ledger_code} onChange={v=>patch('accounting_ledger_code',v.toUpperCase())}/><Field name="Pénznem" value={draft.currency} onChange={v=>patch('currency',v.toUpperCase())}/><Field name="Alap ÁFA (%)" type="number" value={String(draft.default_vat_rate)} onChange={v=>patch('default_vat_rate',Number(v))}/><Field name="Számlaprefix" value={draft.invoice_prefix} onChange={v=>patch('invoice_prefix',v.toUpperCase())}/><Field name="Nyugtaprefix" value={draft.receipt_prefix} onChange={v=>patch('receipt_prefix',v.toUpperCase())}/><label style={{...label,alignContent:'end'}}><span>Aktív cég</span><input type="checkbox" checked={draft.active} onChange={e=>patch('active',e.target.checked)} style={{width:20,height:20}}/></label></div>
    </section>
    <section style={card}><h2 style={{display:'flex',gap:8,alignItems:'center',marginTop:0}}><Store size={20}/>Szalon-hozzárendelés</h2><p style={{color:'#64748b'}}>Egy cég több szalonban is jelen lehet, és egy szalonban több cég is működhet. Szalononként pontosan egy cég jelölhető alapértelmezettnek.</p><div style={{display:'grid',gap:8}}>{locations.map(l=>{const on=draft.location_ids.includes(l.id),def=draft.default_for_location_ids.includes(l.id);return <div key={l.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:12,alignItems:'center',border:'1px solid #e2e8f0',borderRadius:10,padding:'10px 12px'}}><div><b>{l.name}</b><small style={{display:'block',color:'#64748b'}}>{l.city||''}</small></div><label style={{fontSize:12,fontWeight:800}}><input type="checkbox" checked={on} onChange={()=>toggleLocation(l.id)}/> Jelen van</label><label style={{fontSize:12,fontWeight:800,color:def?'#166534':'#475569'}}><input type="checkbox" disabled={!on} checked={def} onChange={()=>toggleDefault(l.id)}/> Alapcég</label></div>})}</div></section>
    {selected&&<section style={card}><h2 style={{display:'flex',gap:8,alignItems:'center',marginTop:0}}><Landmark size={20}/>Külön könyvelés · {selected.short_name||selected.legal_name}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}><Kpi icon={<CircleDollarSign/>} label="Bevételek" value={money(summary?.income)}/><Kpi icon={<CircleDollarSign/>} label="Kiadások" value={money(summary?.expense)}/><Kpi icon={<ShieldCheck/>} label="Egyenleg" value={money(summary?.balance)}/><Kpi icon={<Landmark/>} label="Számlák" value={String(summary?.invoice_count||0)}/><Kpi icon={<Building2/>} label="Munkalapok" value={String(summary?.work_order_count||0)}/></div><p style={{color:'#64748b',fontSize:12,marginBottom:0}}>A pénzügyi mozgások, számlák, munkalapok és nyugták a <b>{selected.accounting_ledger_code}</b> cégdimenzió alatt elkülönítetten kérdezhetők le. A cég pénzügyi lezárás után nem cserélhető a munkalapon.</p></section>}
   </div>
  </section>
  {admin&&<LegalEntityImportDialog open={importOpen} locations={locations} onClose={()=>setImportOpen(false)} onImported={imported}/>} 
 </main>;
}
function Field({name,value,onChange,type='text'}:{name:string;value:string;onChange:(v:string)=>void;type?:string}){return <label style={label}>{name}<input style={input} type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Kpi({icon,label:lab,value}:{icon:React.ReactNode;label:string;value:string}){return <div style={{border:'1px solid #e2e8f0',borderRadius:12,padding:12,display:'flex',gap:9,alignItems:'center'}}><span style={{color:'#6d28d9'}}>{icon}</span><div><small style={{display:'block',color:'#64748b'}}>{lab}</small><b>{value}</b></div></div>}
