import React,{useCallback,useEffect,useState}from'react';
import axios from'axios';
import{BellRing,RefreshCw,Save,ShieldAlert}from'lucide-react';
import'./SaasFranchiseAdminPage.css';

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const authConfig=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
type Policy={enabled:boolean;trial_warning_days:number;trial_grace_days:number;notify_on_warning:boolean;notify_on_grace:boolean;notify_on_suspend:boolean;auto_apply_suspend:boolean};
type Summary={warn:number;grace:number;suspend:number};
type QueueRow={id:string;tenant_name:string;notification_type:string;recipient_email?:string|null;status:string;created_at:string};
const DEFAULT_POLICY:Policy={enabled:false,trial_warning_days:3,trial_grace_days:3,notify_on_warning:true,notify_on_grace:true,notify_on_suspend:true,auto_apply_suspend:false};

export default function LifecyclePolicyPanel(){
 const[policy,setPolicy]=useState<Policy>(DEFAULT_POLICY),[summary,setSummary]=useState<Summary>({warn:0,grace:0,suspend:0}),[queue,setQueue]=useState<QueueRow[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,q]=await Promise.all([axios.get(`${API_BASE}/saas/platform/lifecycle-policy`,authConfig()),axios.get(`${API_BASE}/saas/platform/lifecycle-policy/notifications`,authConfig())]);setPolicy({...DEFAULT_POLICY,...p.data?.policy});setSummary(p.data?.summary||{warn:0,grace:0,suspend:0});setQueue(Array.isArray(q.data?.rows)?q.data.rows:[])}catch(e:any){if(e?.response?.status!==403)setError(e?.response?.data?.error||'A lifecycle policy nem tölthető be.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const save=async()=>{setLoading(true);setError('');setMessage('');try{const r=await axios.patch(`${API_BASE}/saas/platform/lifecycle-policy/config`,policy,authConfig());setPolicy({...DEFAULT_POLICY,...r.data?.policy});setMessage('A lifecycle policy beállításai mentve.');await load()}catch(e:any){setError(e?.response?.data?.error||'A lifecycle policy nem menthető.')}finally{setLoading(false)}};
 const prepare=async()=>{setLoading(true);setError('');setMessage('');try{const r=await axios.post(`${API_BASE}/saas/platform/lifecycle-policy/prepare-notifications`,{},authConfig());setMessage(`${Number(r.data?.prepared_count||0)} új lifecycle értesítés került a várólistára.`);await load()}catch(e:any){setError(e?.response?.data?.error||'Az értesítési sor nem készíthető elő.')}finally{setLoading(false)}};
 const apply=async()=>{setLoading(true);setError('');setMessage('');try{const r=await axios.post(`${API_BASE}/saas/platform/lifecycle-policy/apply`,{},authConfig());setMessage(`${Number(r.data?.applied_count||0)} tenant lifecycle felfüggesztése került alkalmazásra.`);await load()}catch(e:any){setError(e?.response?.data?.error||'A lifecycle policy nem alkalmazható.')}finally{setLoading(false)}};
 return <div className="saas-admin-page" style={{paddingBottom:0}}><section className="saas-panel"><div className="saas-panel-title"><div><h3>Lifecycle policy és értesítési queue</h3><p>Trial, grace és fizetési kockázatok szabályozott kezelése. A queue idempotens; a felfüggesztés külön auditált művelet.</p></div><ShieldAlert size={20}/></div>{error&&<div className="saas-alert is-error">{error}</div>}{message&&<div className="saas-alert is-success">{message}</div>}
 <div className="saas-kpis"><article><BellRing/><div><strong>{summary.warn}</strong><span>Trial figyelmeztetés</span></div></article><article><BellRing/><div><strong>{summary.grace}</strong><span>Grace állapot</span></div></article><article><ShieldAlert/><div><strong>{summary.suspend}</strong><span>Felfüggesztési jelölt</span></div></article><article><BellRing/><div><strong>{queue.filter(x=>x.status==='pending').length}</strong><span>Queue-ban vár</span></div></article></div>
 <div className="saas-form-grid" style={{marginTop:16}}><label>Policy engedélyezve<input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/></label><label>Trial figyelmeztetés (nap)<input type="number" min={1} max={30} value={policy.trial_warning_days} onChange={e=>setPolicy({...policy,trial_warning_days:Number(e.target.value)})}/></label><label>Trial grace (nap)<input type="number" min={0} max={30} value={policy.trial_grace_days} onChange={e=>setPolicy({...policy,trial_grace_days:Number(e.target.value)})}/></label><label>Warning értesítés<input type="checkbox" checked={policy.notify_on_warning} onChange={e=>setPolicy({...policy,notify_on_warning:e.target.checked})}/></label><label>Grace értesítés<input type="checkbox" checked={policy.notify_on_grace} onChange={e=>setPolicy({...policy,notify_on_grace:e.target.checked})}/></label><label>Felfüggesztési értesítés<input type="checkbox" checked={policy.notify_on_suspend} onChange={e=>setPolicy({...policy,notify_on_suspend:e.target.checked})}/></label><label title="A tényleges scheduler bekötéséig ez csak policy-konfiguráció; a kézi Alkalmazás gomb auditált marad.">Automatikus suspend engedély<input type="checkbox" checked={policy.auto_apply_suspend} onChange={e=>setPolicy({...policy,auto_apply_suspend:e.target.checked})}/></label><button type="button" onClick={()=>void save()} disabled={loading}><Save size={16}/>Beállítások mentése</button><button type="button" className="is-secondary" onClick={()=>void prepare()} disabled={loading}><BellRing size={16}/>Értesítési queue előkészítése</button><button type="button" className="is-secondary" onClick={()=>void apply()} disabled={loading||summary.suspend===0}><ShieldAlert size={16}/>Policy alkalmazása</button><button type="button" className="is-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/>Frissítés</button></div>
 <div className="saas-table-wrap" style={{marginTop:16}}><table><thead><tr><th>Tenant</th><th>Típus</th><th>Címzett</th><th>Állapot</th><th>Létrehozva</th></tr></thead><tbody>{queue.length?queue.slice(0,30).map(row=><tr key={row.id}><td>{row.tenant_name}</td><td>{row.notification_type}</td><td>{row.recipient_email||'—'}</td><td>{row.status}</td><td>{new Date(row.created_at).toLocaleString('hu-HU')}</td></tr>):<tr><td colSpan={5}>Nincs lifecycle értesítés a queue-ban.</td></tr>}</tbody></table></div>
 </section></div>;
}
