import React,{useCallback,useEffect,useState}from'react';
import axios from'axios';
import{Activity,BellRing,CheckCircle2,Clock3,RefreshCw,RotateCcw,Save,ShieldAlert}from'lucide-react';
import'./SaasFranchiseAdminPage.css';

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const authConfig=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
type Policy={enabled:boolean;trial_warning_days:number;trial_grace_days:number;notify_on_warning:boolean;notify_on_grace:boolean;notify_on_suspend:boolean;auto_apply_suspend:boolean};type Summary={warn:number;grace:number;suspend:number};type QueueRow={id:string;tenant_name:string;notification_type:string;recipient_email?:string|null;status:string;attempts?:number;next_attempt_at?:string|null;last_error?:string|null;created_at:string};type SchedulerRun={id:string;trigger_source:string;status:string;reason?:string|null;started_at:string;finished_at?:string|null;candidate_count:number;prepared_count:number;suspended_count:number;processed_count:number;sent_count:number;retry_count:number;failed_count:number;instance_id?:string|null;error_text?:string|null};type SchedulerHealth={health:string;last_run?:SchedulerRun|null;last_run_age_minutes?:number|null;queue?:{pending:number;failed:number;sent:number;due_now:number;next_attempt_at?:string|null};runs?:SchedulerRun[]};type OpsAlert={id:string;alert_type:string;severity:string;title:string;message:string;status:string;last_seen_at:string;acknowledged_by?:string|null;last_notified_at?:string|null;notification_error?:string|null};
const DEFAULT_POLICY:Policy={enabled:false,trial_warning_days:3,trial_grace_days:3,notify_on_warning:true,notify_on_grace:true,notify_on_suspend:true,auto_apply_suspend:false};const HEALTH_LABEL:Record<string,string>={healthy:'Rendben',warning:'Figyelmeztetés',critical:'Hiba',unknown:'Nincs futási adat'};
export default function LifecyclePolicyPanel(){
 const[policy,setPolicy]=useState<Policy>(DEFAULT_POLICY),[summary,setSummary]=useState<Summary>({warn:0,grace:0,suspend:0}),[queue,setQueue]=useState<QueueRow[]>([]),[health,setHealth]=useState<SchedulerHealth>({health:'unknown',runs:[]}),[alerts,setAlerts]=useState<OpsAlert[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,q,h,a]=await Promise.all([axios.get(`${API_BASE}/saas/platform/lifecycle-policy`,authConfig()),axios.get(`${API_BASE}/saas/platform/lifecycle-policy/notifications`,authConfig()),axios.get(`${API_BASE}/saas/platform/lifecycle-policy/health`,authConfig()),axios.get(`${API_BASE}/saas/platform/lifecycle-policy/alerts`,authConfig())]);setPolicy({...DEFAULT_POLICY,...p.data?.policy});setSummary(p.data?.summary||{warn:0,grace:0,suspend:0});setQueue(Array.isArray(q.data?.rows)?q.data.rows:[]);setHealth({health:'unknown',runs:[],...h.data});setAlerts(Array.isArray(a.data?.rows)?a.data.rows:[])}catch(e:any){if(e?.response?.status!==403)setError(e?.response?.data?.error||'A lifecycle policy nem tölthető be.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const action=async(url:string,body:any,success:(data:any)=>string)=>{setLoading(true);setError('');setMessage('');try{const r=await axios.post(`${API_BASE}/saas/platform/lifecycle-policy/${url}`,body,authConfig());setMessage(success(r.data));await load()}catch(e:any){setError(e?.response?.data?.error||'A lifecycle művelet nem sikerült.')}finally{setLoading(false)}};const save=async()=>{setLoading(true);try{const r=await axios.patch(`${API_BASE}/saas/platform/lifecycle-policy/config`,policy,authConfig());setPolicy({...DEFAULT_POLICY,...r.data?.policy});setMessage('A lifecycle policy beállításai mentve.');await load()}catch(e:any){setError(e?.response?.data?.error||'A lifecycle policy nem menthető.')}finally{setLoading(false)}};const retry=async(id:string)=>action(`notifications/${id}/retry`,{},()=>`A failed queue elem újrapróbálásra visszaállítva (#${id}).`);const alertAction=async(id:string,kind:'acknowledge'|'resolve')=>action(`alerts/${id}/${kind}`,{},()=>kind==='acknowledge'?'Riasztás nyugtázva.':'Riasztás lezárva.');const last=health.last_run;const openAlerts=alerts.filter(a=>a.status!=='resolved');
 return <div className="saas-admin-page" style={{paddingBottom:0}}><section className="saas-panel"><div className="saas-panel-title"><div><h3>Lifecycle policy, scheduler és értesítési queue</h3><p>Automatikus órás lifecycle futás, health monitoring, futástörténet, dead-letter recovery és operátori incidenskezelés.</p></div><Activity size={20}/></div>{error&&<div className="saas-alert is-error">{error}</div>}{message&&<div className="saas-alert is-success">{message}</div>}
 <div className="saas-kpis"><article><Activity/><div><strong>{HEALTH_LABEL[health.health]||health.health}</strong><span>Scheduler health</span></div></article><article><Clock3/><div><strong>{health.last_run_age_minutes==null?'—':`${health.last_run_age_minutes} p`}</strong><span>Utolsó futás óta</span></div></article><article><ShieldAlert/><div><strong>{openAlerts.filter(a=>a.severity==='critical').length}</strong><span>Nyitott critical alert</span></div></article><article><BellRing/><div><strong>{health.queue?.failed??0}</strong><span>Dead-letter / failed</span></div></article></div>
 {last&&<div className={`saas-alert ${last.status==='failed'?'is-error':'is-success'}`}>Utolsó futás: <b>{last.status}</b> · {new Date(last.started_at).toLocaleString('hu-HU')} · prepared {last.prepared_count} · sent {last.sent_count} · failed {last.failed_count}</div>}
 <div className="saas-form-grid" style={{marginTop:16}}><label>Policy engedélyezve<input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/></label><label>Trial warning (nap)<input type="number" min={1} max={30} value={policy.trial_warning_days} onChange={e=>setPolicy({...policy,trial_warning_days:Number(e.target.value)})}/></label><label>Trial grace (nap)<input type="number" min={0} max={30} value={policy.trial_grace_days} onChange={e=>setPolicy({...policy,trial_grace_days:Number(e.target.value)})}/></label><label>Automatikus suspend<input type="checkbox" checked={policy.auto_apply_suspend} onChange={e=>setPolicy({...policy,auto_apply_suspend:e.target.checked})}/></label><button type="button" onClick={()=>void save()} disabled={loading}><Save size={16}/>Beállítások mentése</button><button type="button" className="is-secondary" onClick={()=>void action('run-now',{},()=>`Scheduler kézi futás kész.`)} disabled={loading}><Activity size={16}/>Scheduler futtatása most</button><button type="button" className="is-secondary" onClick={()=>void action('alerts/reconcile',{},()=>`Watchdog ellenőrzés lefutott.`)} disabled={loading}><ShieldAlert size={16}/>Alert watchdog most</button><button type="button" className="is-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/>Frissítés</button></div>
 <h4 style={{marginTop:20}}>Operátori riasztások</h4><div className="saas-table-wrap"><table><thead><tr><th>Súlyosság</th><th>Riasztás</th><th>Állapot</th><th>Utolsó észlelés</th><th>Eszkaláció</th><th>Művelet</th></tr></thead><tbody>{alerts.length?alerts.slice(0,30).map(a=><tr key={a.id}><td><b>{a.severity}</b></td><td><b>{a.title}</b><br/><small>{a.message}</small></td><td>{a.status}</td><td>{new Date(a.last_seen_at).toLocaleString('hu-HU')}</td><td>{a.last_notified_at?new Date(a.last_notified_at).toLocaleString('hu-HU'):a.notification_error||'—'}</td><td>{a.status==='open'?<button type="button" className="is-secondary" onClick={()=>void alertAction(a.id,'acknowledge')} disabled={loading}><CheckCircle2 size={14}/>Nyugtázás</button>:null}{a.status!=='resolved'?<button type="button" className="is-secondary" onClick={()=>void alertAction(a.id,'resolve')} disabled={loading}><CheckCircle2 size={14}/>Lezárás</button>:'—'}</td></tr>):<tr><td colSpan={6}>Nincs operátori lifecycle riasztás.</td></tr>}</tbody></table></div>
 <h4 style={{marginTop:20}}>Értesítési queue / dead-letter</h4><div className="saas-table-wrap"><table><thead><tr><th>Tenant</th><th>Típus</th><th>Állapot</th><th>Próba</th><th>Hiba</th><th>Művelet</th></tr></thead><tbody>{queue.length?queue.slice(0,30).map(row=><tr key={row.id}><td>{row.tenant_name}</td><td>{row.notification_type}</td><td>{row.status}</td><td>{row.attempts||0}</td><td>{row.last_error||'—'}</td><td>{row.status==='failed'?<button type="button" className="is-secondary" onClick={()=>void retry(row.id)} disabled={loading}><RotateCcw size={14}/>Újrapróbálás</button>:'—'}</td></tr>):<tr><td colSpan={6}>Nincs lifecycle értesítés.</td></tr>}</tbody></table></div>
 <h4 style={{marginTop:20}}>Scheduler futástörténet</h4><div className="saas-table-wrap"><table><thead><tr><th>Indítás</th><th>Trigger</th><th>Állapot</th><th>Jelölt</th><th>Előkészítve</th><th>Küldve</th><th>Failed</th></tr></thead><tbody>{health.runs?.length?health.runs.slice(0,20).map(run=><tr key={run.id}><td>{new Date(run.started_at).toLocaleString('hu-HU')}</td><td>{run.trigger_source}</td><td>{run.status}</td><td>{run.candidate_count}</td><td>{run.prepared_count}</td><td>{run.sent_count}</td><td>{run.failed_count}</td></tr>):<tr><td colSpan={7}>Még nincs rögzített scheduler futás.</td></tr>}</tbody></table></div></section></div>;
}
