import React, { useEffect, useMemo, useState } from "react";
import api from "../api";
import ProcurementPanel from "./inventory/ProcurementPanel";
import "./Logisztika.css";

type Location={id:string;name?:string;title?:string};
type Product={id:string;name:string;internal_code?:string|null;brand?:string|null};
type Balance={id:string|number;product_id:string;product_name:string;internal_code?:string|null;brand?:string|null;location_id:string|null;quantity:number|string;min_quantity:number|string;unit_cost:number|string;stock_value:number|string;updated_at:string};
type Movement={id:string|number;product_name:string;movement_type:string;quantity:number|string;balance_after:number|string|null;unit_cost?:number|string|null;stock_value_after?:number|string|null;work_order_id?:string|number|null;note?:string|null;created_at:string};
type MovementType="opening"|"receipt"|"adjustment";
const labels:Record<string,string>={opening:"Nyitókészlet",receipt:"Bevételezés",adjustment:"Korrekció",work_order_consumption:"Munkalap felhasználás",work_order_reversal:"Munkalap visszaforgatás"};
const arr=<T,>(v:any):T[]=>Array.isArray(v)?v:Array.isArray(v?.items)?v.items:Array.isArray(v?.data)?v.data:[];
const huf=(v:unknown)=>`${Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:0})} Ft`;
const q=(v:unknown)=>Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:3});

export default function Logisztika(){
 const[locations,setLocations]=useState<Location[]>([]),[products,setProducts]=useState<Product[]>([]),[balances,setBalances]=useState<Balance[]>([]),[movements,setMovements]=useState<Movement[]>([]);
 const[locationId,setLocationId]=useState(""),[tab,setTab]=useState<"stock"|"movements"|"procurement">("stock"),[search,setSearch]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
 const[editingId,setEditingId]=useState<string|number|null>(null),[settingsForm,setSettingsForm]=useState({min_quantity:"",unit_cost:""});
 const[form,setForm]=useState({product_id:"",movement_type:"receipt" as MovementType,quantity:"",unit_cost:"",min_quantity:"",note:""});
 const locationQuery=locationId?`?location_id=${encodeURIComponent(locationId)}`:"";
 async function loadRefs(){const[l,p]=await Promise.all([api.get("/api/locations"),api.get("/api/products?include_inactive=1")]);setLocations(arr<Location>(l.data));setProducts(arr<Product>(p.data))}
 async function loadInventory(){setLoading(true);setError("");try{const[b,m]=await Promise.all([api.get(`/api/transactions/inventory${locationQuery}`),api.get(`/api/transactions/inventory/movements${locationId?`?location_id=${encodeURIComponent(locationId)}&limit=200`:"?limit=200"}`)]);setBalances(arr<Balance>(b.data));setMovements(arr<Movement>(m.data))}catch(e:any){setError(e?.response?.data?.message||"A készletadatok betöltése nem sikerült.")}finally{setLoading(false)}}
 useEffect(()=>{loadRefs().catch(()=>setError("A törzsadatok betöltése nem sikerült."))},[]);useEffect(()=>{void loadInventory()},[locationId]); // eslint-disable-line react-hooks/exhaustive-deps
 const filtered=useMemo(()=>{const s=search.trim().toLowerCase();return !s?balances:balances.filter(x=>`${x.product_name} ${x.internal_code||""} ${x.brand||""}`.toLowerCase().includes(s))},[balances,search]);
 const totalUnits=balances.reduce((a,x)=>a+Number(x.quantity||0),0),totalValue=balances.reduce((a,x)=>a+Number(x.stock_value||0),0),low=balances.filter(x=>Number(x.quantity)>0&&Number(x.quantity)<=Number(x.min_quantity)).length,out=balances.filter(x=>Number(x.quantity)<=0).length;
 async function saveMovement(e:React.FormEvent){e.preventDefault();setError("");setSuccess("");const quantity=Number(form.quantity),unitCost=form.unit_cost===""?null:Number(form.unit_cost),minQuantity=form.min_quantity===""?null:Number(form.min_quantity);if(!form.product_id)return setError("Válassz terméket.");if(!Number.isFinite(quantity))return setError("A mennyiség csak szám lehet.");if(unitCost!==null&&(!Number.isFinite(unitCost)||unitCost<0))return setError("A beszerzési ár hibás.");if(minQuantity!==null&&(!Number.isFinite(minQuantity)||minQuantity<0))return setError("A minimum készlet hibás.");setSaving(true);try{await api.post("/api/transactions/inventory/movements",{product_id:form.product_id,location_id:locationId||null,movement_type:form.movement_type,quantity,unit_cost:unitCost,min_quantity:minQuantity,note:form.note.trim()||null});setSuccess("A készletmozgás sikeresen rögzítve.");setForm(x=>({...x,quantity:"",unit_cost:"",min_quantity:"",note:""}));await loadInventory()}catch(e:any){setError(e?.response?.data?.message||"A mentés nem sikerült.")}finally{setSaving(false)}}
 function startEdit(r:Balance){setEditingId(r.id);setSettingsForm({min_quantity:String(r.min_quantity??0),unit_cost:String(r.unit_cost??0)})}
 async function saveSettings(r:Balance){const min=Number(settingsForm.min_quantity),cost=Number(settingsForm.unit_cost);if(!Number.isFinite(min)||min<0||!Number.isFinite(cost)||cost<0)return setError("A készletparaméterek hibásak.");setSaving(true);try{await api.patch(`/api/transactions/inventory/balances/${r.id}/settings`,{min_quantity:min,unit_cost:cost});setEditingId(null);setSuccess("A készletparaméterek frissültek.");await loadInventory()}catch(e:any){setError(e?.response?.data?.message||"A mentés nem sikerült.")}finally{setSaving(false)}}
 return <div className="inventory-page">
  <header className="inventory-header"><div><span className="inventory-eyebrow">LOGISZTIKA / RAKTÁR</span><h1>Készlet és beszerzés</h1><p>Készletezés, értékelés, automatikus utánrendelés, beszerzési rendelés és bevételezés egy folyamatban.</p></div><div className="inventory-location"><label>Telephely</label><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Központi készlet</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name||l.title||l.id}</option>)}</select></div></header>
  {error&&<div className="inventory-alert error">{error}</div>}{success&&<div className="inventory-alert success">{success}</div>}
  <section className="inventory-kpis inventory-kpis--five"><div><strong>{balances.length}</strong><span>Készletezett termék</span></div><div><strong>{q(totalUnits)}</strong><span>Összes mennyiség</span></div><div><strong>{huf(totalValue)}</strong><span>Készletérték</span></div><div><strong>{low}</strong><span>Minimum alatt</span></div><div><strong>{out}</strong><span>Kifogyott</span></div></section>
  <div className="inventory-main-tabs"><button className={tab==="stock"?"active":""} onClick={()=>setTab("stock")}>Készlet</button><button className={tab==="movements"?"active":""} onClick={()=>setTab("movements")}>Mozgástörténet</button><button className={tab==="procurement"?"active":""} onClick={()=>setTab("procurement")}>Beszerzés és utánrendelés</button></div>
  {tab==="procurement"?<ProcurementPanel locationId={locationId} onInventoryChanged={loadInventory}/>:<section className="inventory-grid">
   <div className="inventory-card movement-card"><div className="card-title"><h2>Készletmozgás rögzítése</h2><p>Bevételezésnél súlyozott átlagos beszerzési ár számolódik.</p></div><form onSubmit={saveMovement} className="movement-form"><label>Termék<select value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}><option value="">Válassz terméket…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Mozgás típusa<select value={form.movement_type} onChange={e=>setForm({...form,movement_type:e.target.value as MovementType})}><option value="opening">Nyitókészlet</option><option value="receipt">Bevételezés</option><option value="adjustment">Korrekció</option></select></label><label>Mennyiség<input type="number" step="0.001" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label>{form.movement_type!=="adjustment"&&<label>Beszerzési egységár (Ft)<input type="number" min="0" step="0.01" value={form.unit_cost} onChange={e=>setForm({...form,unit_cost:e.target.value})}/></label>}<label>Minimum készletszint<input type="number" min="0" step="0.001" value={form.min_quantity} onChange={e=>setForm({...form,min_quantity:e.target.value})}/></label><label>Megjegyzés<textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button disabled={saving}>{saving?"Mentés…":"Mozgás rögzítése"}</button></form></div>
   <div className="inventory-card table-card">{tab==="stock"?<><input className="inventory-search" placeholder="Keresés termékre…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>Termék</th><th>Készlet</th><th>Minimum</th><th>Beszerzési ár</th><th>Készletérték</th><th>Állapot</th><th></th></tr></thead><tbody>{filtered.map(r=>{const isEdit=editingId===r.id,qty=Number(r.quantity),min=Number(r.min_quantity);return <tr key={r.id}><td><b>{r.product_name}</b><small className="inventory-subline">{[r.brand,r.internal_code].filter(Boolean).join(" · ")}</small></td><td>{q(qty)}</td><td>{isEdit?<input className="inventory-inline-input" type="number" value={settingsForm.min_quantity} onChange={e=>setSettingsForm({...settingsForm,min_quantity:e.target.value})}/>:q(min)}</td><td>{isEdit?<input className="inventory-inline-input" type="number" value={settingsForm.unit_cost} onChange={e=>setSettingsForm({...settingsForm,unit_cost:e.target.value})}/>:huf(r.unit_cost)}</td><td><b>{huf(r.stock_value)}</b></td><td><span className={`stock-badge ${qty<=0?"danger":qty<=min?"warning":"ok"}`}>{qty<=0?"Kifogyott":qty<=min?"Minimum alatt":"Rendben"}</span></td><td>{isEdit?<div className="inventory-inline-actions"><button onClick={()=>saveSettings(r)}>Mentés</button><button className="secondary" onClick={()=>setEditingId(null)}>Mégse</button></div>:<button className="inventory-edit" onClick={()=>startEdit(r)}>Szerkesztés</button>}</td></tr>})}</tbody></table></div></>:<div className="table-wrap"><table><thead><tr><th>Időpont</th><th>Termék</th><th>Típus</th><th>Változás</th><th>Egyenleg</th><th>Egységár</th><th>Készletérték</th><th>Megjegyzés</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString("hu-HU")}</td><td><b>{m.product_name}</b></td><td>{labels[m.movement_type]||m.movement_type}</td><td className={Number(m.quantity)<0?"qty-negative":"qty-positive"}>{Number(m.quantity)>0?"+":""}{q(m.quantity)}</td><td>{q(m.balance_after)}</td><td>{huf(m.unit_cost)}</td><td>{huf(m.stock_value_after)}</td><td>{m.note||(m.work_order_id?`Munkalap #${m.work_order_id}`:"—")}</td></tr>)}</tbody></table></div>}</div>
  </section>}
 </div>
}
