import{useCallback,useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowLeft,CheckCircle2,ClipboardCheck,Clock3,ExternalLink,Flame,MessageSquareText,MonitorPlay,Plus,RefreshCw,Save,ShieldAlert,Siren,Target,Users}from'lucide-react';
import{useNavigate}from'react-router-dom';
import api from'../api';
import'./MajorIncidentWarRoomPage.css';

const BASE='/api/transactions/notifications/exceptions/intelligence/major-incidents';
const statusHu:Record<string,string>={open:'Nyitott',mitigating:'Mitigáció',monitoring:'Monitoring',resolved:'Feloldott',postmortem_closed:'Post-mortem lezárva',dismissed:'Elutasított'};
const sevHu:Record<string,string>={sev1:'SEV1 · KRITIKUS',sev2:'SEV2 · SÚLYOS',sev3:'SEV3 · JELENTŐS'};
const fmt=(v:any)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const emptyPost={root_cause:'',impact_summary:'',lessons_learned:'',follow_up_actions:''};

export default function MajorIncidentWarRoomPage(){
 const navigate=useNavigate();
 const[summary,setSummary]=useState<any>(null),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(false),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState('all'),[severity,setSeverity]=useState('all');
 const[form,setForm]=useState<any>({}),[resolutionNote,setResolutionNote]=useState(''),[resolutionEvidence,setResolutionEvidence]=useState(''),[postmortem,setPostmortem]=useState<any>(emptyPost),[transitionNote,setTransitionNote]=useState('');
 const[action,setAction]=useState<any>({title:'',detail:'',priority:'high',owner_key:'',owner_name:'',due_at:''});
 const[update,setUpdate]=useState<any>({update_type:'status',audience:'internal',message:''});
 const locationId=localStorage.getItem('kleo_location_id')||'';
 const query=useMemo(()=>{const p=new URLSearchParams();if(status!=='all')p.set('status',status);if(severity!=='all')p.set('severity',severity);if(locationId)p.set('location_id',locationId);return p.toString()},[status,severity,locationId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const sp=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const[a,b]=await Promise.all([api.get(`${BASE}/summary${sp}`),api.get(`${BASE}?${query}`)]);setSummary(a.data);setItems(b.data?.items||[])}catch(e:any){setError(e?.response?.data?.message||'A Major Incident központ nem tölthető be.')}finally{setLoading(false)}},[locationId,query]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const t=window.setInterval(()=>void load(),30_000);return()=>window.clearInterval(t)},[load]);
 async function open(id:string){try{const r=await api.get(`${BASE}/${id}${locationId?`?location_id=${encodeURIComponent(locationId)}`:''}`);setSelected(r.data);const x=r.data.item;setForm({incident_commander_key:x.incident_commander_key||'',incident_commander_name:x.incident_commander_name||'',technical_lead_key:x.technical_lead_key||'',technical_lead_name:x.technical_lead_name||'',communications_lead_key:x.communications_lead_key||'',communications_lead_name:x.communications_lead_name||'',customer_impact:x.customer_impact||'',operational_impact:x.operational_impact||'',financial_impact:x.financial_impact||''});setResolutionNote(x.resolution_note||'');setResolutionEvidence('');setPostmortem({...emptyPost,...(x.postmortem||{})});setTransitionNote('')}catch(e:any){setError(e?.response?.data?.message||'A Major Incident nem nyitható meg.')}}
 async function sync(){setSyncing(true);setError('');try{const r=await api.post(`${BASE}/sync`);setNotice(`War Room detektor: ${r.data?.created||0} új incidens, ${r.data?.escalated||0} súlyosság-emelés, ${r.data?.auto_monitoring||0} monitoringba tett eset.`);await load()}catch(e:any){setError(e?.response?.data?.message||'A War Room detektor nem futtatható.')}finally{setSyncing(false)}}
 async function patch(input:any){if(!selected)return;try{await api.patch(`${BASE}/${selected.item.id}`,input);setNotice('Major Incident frissítve.');await open(selected.item.id);await load()}catch(e:any){setError(e?.response?.data?.message||'A Major Incident módosítás nem menthető.')}}
 async function saveCommand(){await patch({...form,note:'War Room command team / impact adatok frissítve.'})}
 async function move(next:string){if(!selected)return;const commander=String(form.incident_commander_key||'').trim();if(['mitigating','monitoring','resolved','postmortem_closed'].includes(next)&&!commander){setError('Mitigációhoz/feloldáshoz incident commander kijelölése szükséges.');return}const input:any={...form,status:next,note:transitionNote.trim()};if(next==='resolved'||next==='postmortem_closed'){if(resolutionNote.trim().length<10||resolutionEvidence.trim().length<5){setError('Feloldáshoz legalább 10 karakteres indok és konkrét bizonyíték szükséges.');return}input.resolution_note=resolutionNote.trim();input.resolution_evidence={description:resolutionEvidence.trim(),source:'war-room-management',recorded_at:new Date().toISOString()}}if(next==='postmortem_closed'){for(const key of Object.keys(emptyPost))if(String(postmortem[key]||'').trim().length<10){setError('A post-mortem minden mezőjét érdemben ki kell tölteni.');return}input.postmortem=postmortem}setError('');await patch(input);setTransitionNote('')}
 async function addAction(){if(!selected||action.title.trim().length<5){setError('Az akció megnevezése legalább 5 karakter legyen.');return}try{await api.post(`${BASE}/${selected.item.id}/actions`,{...action,due_at:action.due_at||null});setAction({title:'',detail:'',priority:'high',owner_key:'',owner_name:'',due_at:''});setNotice('War Room akció létrehozva.');await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'Az akció nem hozható létre.')}}
 async function actionStatus(a:any,next:string){if(!selected)return;const input:any={status:next};if(next==='done'){const evidence=window.prompt('Végrehajtási bizonyíték rövid leírása:','');if(!evidence||evidence.trim().length<5)return;input.completion_evidence={description:evidence.trim(),source:'war-room-action'}}try{await api.patch(`${BASE}/${selected.item.id}/actions/${a.id}`,input);await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'Az akció státusza nem módosítható.')}}
 async function addUpdate(){if(!selected||update.message.trim().length<5){setError('A War Room update legalább 5 karakter legyen.');return}try{await api.post(`${BASE}/${selected.item.id}/updates`,update);setUpdate({...update,message:''});setNotice('War Room update rögzítve.');await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'A War Room update nem rögzíthető.')}}
 const current=selected?.item;
 const nexts:Record<string,string[]>={open:['mitigating','dismissed'],mitigating:['monitoring','open'],monitoring:['resolved','mitigating'],resolved:['postmortem_closed','monitoring'],postmortem_closed:[],dismissed:['open']};
 const timeline=useMemo(()=>{if(!selected)return[];return[...(selected.events||[]).map((x:any)=>({...x,kind:'event'})),...(selected.updates||[]).map((x:any)=>({...x,kind:'update'}))].sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime())},[selected]);
 return <div className="mi-page">
  <header className="mi-hero"><div><button onClick={()=>navigate('/finance/exception-command-center/intelligence')}><ArrowLeft/> Exception Intelligence</button><span>STATISZTIKA ÉS VIR · MAJOR INCIDENT MANAGEMENT</span><h1><MonitorPlay/> Major Incident / War Room</h1><p>Automatikus incidensdeklarálás, SEV-besorolás, impact score, command team, mitigációs akciók, vezetői idővonal és kötelező post-mortem.</p></div><div className="mi-control"><Flame/><b>AUTOMATIC DETECTION · HUMAN COMMAND</b><span>A rendszer felismer és riaszt; külső kommunikációt és lezárási döntést nem végez önállóan.</span></div></header>
  <div className="mi-toolbar"><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">Minden SEV</option><option value="sev1">SEV1</option><option value="sev2">SEV2</option><option value="sev3">SEV3</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Aktív incidensek</option>{Object.entries(statusHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={sync} disabled={syncing}><RefreshCw className={syncing?'spin':''}/>{syncing?'Detektálás…':'War Room detektor futtatása'}</button></div>
  {error&&<div className="mi-error"><AlertTriangle/>{error}</div>}{notice&&<div className="mi-notice"><CheckCircle2/>{notice}</div>}
  {summary&&<section className="mi-kpis"><article className={Number(summary.sev1)>0?'danger':''}><Siren/><div><small>SEV1 aktív</small><b>{summary.sev1||0}</b></div></article><article className={Number(summary.sev2)>0?'warning':''}><ShieldAlert/><div><small>SEV2 aktív</small><b>{summary.sev2||0}</b></div></article><article><Flame/><div><small>Aktív War Room</small><b>{summary.active||0}</b></div></article><article className={Number(summary.commander_missing)>0?'warning':''}><Users/><div><small>Commander hiányzik</small><b>{summary.commander_missing||0}</b></div></article><article className={Number(summary.overdue_actions)>0?'danger':''}><Clock3/><div><small>Lejárt akció</small><b>{summary.overdue_actions||0}</b></div></article><article><ClipboardCheck/><div><small>Post-mortem vár</small><b>{summary.awaiting_postmortem||0}</b></div></article></section>}
  <section className="mi-work"><div className="mi-list"><header><b>Major Incident munkasor</b><span>{items.length} incidens</span></header>{loading&&!items.length&&<div className="mi-empty">Betöltés…</div>}{items.map(x=><button key={x.id} className={`${selected?.item?.id===x.id?'active':''} ${x.severity}`} onClick={()=>open(x.id)}><div><span>{sevHu[x.severity]||x.severity}</span><em>{statusHu[x.status]||x.status}</em></div><h3>{x.incident_no}</h3><b>{x.title}</b><p>{x.summary}</p><footer><strong>{x.impact_score}/100 impact</strong><span>{x.location_id||'globális'}</span><span>{x.linked_cases||0} case</span><span>{x.open_actions||0} akció</span></footer></button>)}{!loading&&!items.length&&<div className="mi-empty"><CheckCircle2/> Nincs aktív Major Incident.</div>}</div>
   <div className="mi-detail">{!selected?<div className="mi-placeholder"><MonitorPlay/><h2>Válasszon War Roomot</h2><p>Az incidens megnyitása után itt kezelhető a command team, az impact, a mitigáció, az akciók, a döntési idővonal és a post-mortem.</p></div>:<><header className={`mi-detail-head ${current.severity}`}><div><span>{sevHu[current.severity]} · {current.impact_score}/100</span><h2>{current.incident_no} · {current.title}</h2><p>{current.summary}</p></div><div><b>{statusHu[current.status]}</b><small>Deklarálva: {fmt(current.declared_at)}</small></div></header>
    <section className="mi-command"><h3><Users/> War Room command team és impact</h3><div className="mi-fields"><label>Incident commander azonosító / e-mail<input value={form.incident_commander_key||''} onChange={e=>setForm({...form,incident_commander_key:e.target.value})}/></label><label>Incident commander neve<input value={form.incident_commander_name||''} onChange={e=>setForm({...form,incident_commander_name:e.target.value})}/></label><label>Technical lead<input value={form.technical_lead_key||''} onChange={e=>setForm({...form,technical_lead_key:e.target.value})}/></label><label>Technical lead neve<input value={form.technical_lead_name||''} onChange={e=>setForm({...form,technical_lead_name:e.target.value})}/></label><label>Communications lead<input value={form.communications_lead_key||''} onChange={e=>setForm({...form,communications_lead_key:e.target.value})}/></label><label>Communications lead neve<input value={form.communications_lead_name||''} onChange={e=>setForm({...form,communications_lead_name:e.target.value})}/></label></div><div className="mi-impact"><label>Ügyfélhatás<textarea value={form.customer_impact||''} onChange={e=>setForm({...form,customer_impact:e.target.value})}/></label><label>Operatív hatás<textarea value={form.operational_impact||''} onChange={e=>setForm({...form,operational_impact:e.target.value})}/></label><label>Pénzügyi hatás<textarea value={form.financial_impact||''} onChange={e=>setForm({...form,financial_impact:e.target.value})}/></label></div><button className="primary" onClick={saveCommand}><Save/> Command team / impact mentése</button></section>
    <section className="mi-transition"><h3><Target/> Incident lifecycle</h3><textarea value={transitionNote} onChange={e=>setTransitionNote(e.target.value)} placeholder="Döntés / státuszváltás indoka…"/>{['monitoring','resolved'].includes(current.status)&&<><textarea value={resolutionNote} onChange={e=>setResolutionNote(e.target.value)} placeholder="Feloldási indok (min. 10 karakter)…"/><textarea value={resolutionEvidence} onChange={e=>setResolutionEvidence(e.target.value)} placeholder="Feloldási bizonyíték leírása…"/></>}{current.status==='resolved'&&<div className="mi-post"><h4>Post-mortem</h4><textarea value={postmortem.root_cause} onChange={e=>setPostmortem({...postmortem,root_cause:e.target.value})} placeholder="Gyökérok…"/><textarea value={postmortem.impact_summary} onChange={e=>setPostmortem({...postmortem,impact_summary:e.target.value})} placeholder="Hatás összefoglalása…"/><textarea value={postmortem.lessons_learned} onChange={e=>setPostmortem({...postmortem,lessons_learned:e.target.value})} placeholder="Tanulságok…"/><textarea value={postmortem.follow_up_actions} onChange={e=>setPostmortem({...postmortem,follow_up_actions:e.target.value})} placeholder="Követő / megelőző intézkedések…"/></div>}<div className="mi-buttons">{(nexts[current.status]||[]).map(next=><button key={next} className={next==='dismissed'?'reject':next==='postmortem_closed'?'verify':''} onClick={()=>move(next)}>{statusHu[next]}</button>)}</div></section>
    <section className="mi-linked"><h3><Siren/> Kapcsolt Exception case-ek</h3>{(selected.cases||[]).map((x:any)=><div key={x.id}><span className={`case-sev ${x.severity}`}>{String(x.severity).toUpperCase()}</span><div><b>{x.title}</b><small>{x.category} · {x.status} · SLA {x.sla_state} · {x.reason}</small></div>{x.source_route&&<button onClick={()=>navigate(x.source_route)}><ExternalLink/></button>}</div>)}{selected.capa&&<button className="capa-link" onClick={()=>navigate('/finance/exception-command-center/capa')}><ClipboardCheck/> Kapcsolt CAPA: {selected.capa.title} · {selected.capa.status}</button>}</section>
    <section className="mi-actions"><h3><Target/> War Room action board</h3><div className="mi-action-new"><input value={action.title} onChange={e=>setAction({...action,title:e.target.value})} placeholder="Akció…"/><input value={action.owner_name} onChange={e=>setAction({...action,owner_name:e.target.value})} placeholder="Felelős neve…"/><input value={action.owner_key} onChange={e=>setAction({...action,owner_key:e.target.value})} placeholder="Felelős e-mail / ID…"/><select value={action.priority} onChange={e=>setAction({...action,priority:e.target.value})}><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><input type="datetime-local" value={action.due_at} onChange={e=>setAction({...action,due_at:e.target.value})}/><button onClick={addAction}><Plus/> Hozzáadás</button></div><div className="mi-action-list">{(selected.actions||[]).map((a:any)=><div key={a.id} className={`${a.priority} ${a.status}`}><div><span>{a.priority}</span><b>{a.title}</b><small>{a.owner_name||a.owner_key||'nincs felelős'} · {a.due_at?`határidő ${fmt(a.due_at)}`:'nincs határidő'}</small></div><div>{a.status==='open'&&<button onClick={()=>actionStatus(a,'in_progress')}>Indítás</button>}{a.status==='in_progress'&&<button onClick={()=>actionStatus(a,'done')}>Kész + evidence</button>}<em>{a.status}</em></div></div>)}</div></section>
    <section className="mi-update"><h3><MessageSquareText/> War Room update</h3><div><select value={update.update_type} onChange={e=>setUpdate({...update,update_type:e.target.value})}><option value="status">Státusz</option><option value="decision">Döntés</option><option value="observation">Megfigyelés</option><option value="communication">Kommunikáció</option></select><select value={update.audience} onChange={e=>setUpdate({...update,audience:e.target.value})}><option value="internal">Belső</option><option value="executive">Vezetői</option><option value="stakeholder">Stakeholder jegyzet</option></select><textarea value={update.message} onChange={e=>setUpdate({...update,message:e.target.value})} placeholder="Mi történt, mit döntöttünk, mi a következő lépés?"/><button onClick={addUpdate}><Plus/> Update rögzítése</button></div><small>A stakeholder update naplóbejegyzés; a rendszer külső címzettnek nem küldi el automatikusan.</small></section>
    <section className="mi-timeline"><h3><Clock3/> War Room idővonal</h3>{timeline.map((x:any)=><div key={`${x.kind}-${x.id}`}><time>{fmt(x.created_at)}</time><span>{x.kind==='update'?`${x.audience} / ${x.update_type}`:x.event_type}</span><b>{x.actor_key}</b><p>{x.message}</p></div>)}</section>
   </>}</div>
  </section>
 </div>
}