import React,{useEffect,useMemo,useState}from"react";
import{ArchiveRestore,CheckCircle2,Database,FileSpreadsheet,History,RefreshCcw,ShieldCheck,UploadCloud,Users,AlertTriangle}from"lucide-react";
import api from"../api/api";
import"./MigrationCenterPage.css";

type Provider={code:string;name:string;description:string;mode:string[];duplicate_visible?:boolean;legacy_tools?:{entity:string;method:string;path:string}[]};
type Run={id:string;provider:string;entity_type:string;status:string;filename?:string;duplicate_policy:string;mapping?:Record<string,string>;stats?:Record<string,any>;created_at?:string;rolled_back_at?:string};
type Detail={run:Run;items:any[];events:any[]};
const ENTITY_LABELS:Record<string,string>={clients:"Vendégek",employees:"Munkatársak",services:"Szolgáltatások",products:"Termékek",appointments:"Időpontok"};
const POLICIES=[{code:"review",label:"Kézi felülvizsgálat",hint:"Duplikáció esetén megáll az éles import."},{code:"skip",label:"Duplikált kihagyása",hint:"A VIR-ben már megtalált rekordokat nem módosítja."},{code:"merge",label:"Egyesítés",hint:"A felismert mezőkkel frissíti a meglévő rekordot."},{code:"create_new",label:"Új rekord is lehet",hint:"Duplikáció esetén is új rekord készül."}];
const fmt=(v:any)=>Number(v||0).toLocaleString("hu-HU");

export default function MigrationCenterPage(){
 const[providers,setProviders]=useState<Provider[]>([]),[runs,setRuns]=useState<Run[]>([]),[provider,setProvider]=useState("altegio"),[entity,setEntity]=useState("clients"),[policy,setPolicy]=useState("review"),[file,setFile]=useState<File|null>(null),[detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const selectedProvider=useMemo(()=>providers.find(p=>p.code===provider),[providers,provider]);
 const load=async()=>{const[p,r]=await Promise.all([api.get("/vir/migration-center/providers"),api.get("/vir/migration-center/runs")]);setProviders(p.data?.providers||[]);setRuns(r.data?.rows||[])};
 useEffect(()=>{load().catch(e=>setError(e?.response?.data?.error||"A Migrációs Központ nem tölthető be."))},[]);
 const openRun=async(id:string)=>{const r=await api.get(`/vir/migration-center/runs/${id}`);setDetail(r.data);};
 const createAndUpload=async()=>{if(!file){setError("Válasszon CSV vagy Excel fájlt.");return}setBusy(true);setError("");setMessage("");try{const created=await api.post("/vir/migration-center/runs",{provider,entity_type:entity,duplicate_policy:policy,source_mode:"file"});const id=created.data?.run?.id;const fd=new FormData();fd.append("file",file);const analyzed=await api.post(`/vir/migration-center/runs/${id}/upload`,fd,{headers:{"Content-Type":"multipart/form-data"}});setMessage(`Előnézet elkészült: ${fmt(analyzed.data?.stats?.total)} sor, ${fmt(analyzed.data?.stats?.duplicates)} lehetséges duplikáció.`);await Promise.all([load(),openRun(id)])}catch(e:any){setError(e?.response?.data?.error||"A migrációs előnézet nem készíthető el.")}finally{setBusy(false)}};
 const applyRun=async()=>{if(!detail?.run?.id)return;setBusy(true);setError("");try{const r=await api.post(`/vir/migration-center/runs/${detail.run.id}/apply`,{duplicate_policy:policy});setMessage(`Import lezárva: ${r.data?.status}. Létrehozva: ${fmt(r.data?.stats?.created)}, egyesítve: ${fmt(r.data?.stats?.merged)}, kihagyva: ${fmt(r.data?.stats?.skipped)}.`);await Promise.all([load(),openRun(detail.run.id)])}catch(e:any){setError(e?.response?.data?.error||"Az import nem indítható.")}finally{setBusy(false)}};
 const rollback=async()=>{if(!detail?.run?.id||!window.confirm("Biztosan visszaállítja ennek a migrációs futásnak a változásait?"))return;setBusy(true);setError("");try{const r=await api.post(`/vir/migration-center/runs/${detail.run.id}/rollback`);setMessage(`Rollback kész. Visszaállított műveletek: ${fmt(r.data?.reverted)}.`);await Promise.all([load(),openRun(detail.run.id)])}catch(e:any){setError(e?.response?.data?.error||"A rollback nem fejezhető be automatikusan.")}finally{setBusy(false)}};
 const legacyUpload=async(path:string)=>{if(!file){setError("A natív Altegio gyorsimporthoz is válasszon fájlt.");return}if(!window.confirm("Ez a kompatibilitási gyorsút közvetlenül írja a VIR adatokat, a v18 staging/rollback nélkül. Folytatja?"))return;setBusy(true);setError("");try{const fd=new FormData();fd.append("file",file);await api.post(path.replace(/^\/api/,""),fd,{headers:{"Content-Type":"multipart/form-data"}});setMessage("A natív Altegio kompatibilitási import lefutott.")}catch(e:any){setError(e?.response?.data?.error||"A natív Altegio import nem sikerült.")}finally{setBusy(false)}};
 const stats=detail?.run?.stats||{};
 return <div className="migration-v18">
  <header className="migration-hero"><div><span className="migration-kicker"><Database size={15}/> VIR MIGRÁCIÓS KÖZPONT v18</span><h1>Adatköltöztetés kontrolláltan, visszaállíthatóan</h1><p>Altegio, Booksy, Fresha, Excel és CSV források egységes előnézettel, duplikációkezeléssel, tenant-határral és audit evidence-szel.</p></div><div className="migration-shield"><ShieldCheck size={30}/><strong>Staging first</strong><span>Élesítés előtt mindig elemzés.</span></div></header>
  {error&&<div className="migration-alert error"><AlertTriangle size={18}/>{error}</div>}{message&&<div className="migration-alert success"><CheckCircle2 size={18}/>{message}</div>}
  <section className="migration-card"><h2>1. Forrásrendszer</h2><div className="provider-grid">{providers.map(p=><button key={p.code} className={`provider-card ${provider===p.code?"active":""}`} onClick={()=>setProvider(p.code)}><strong>{p.name}</strong><span>{p.description}</span>{p.code==="altegio"&&<em>KIEMELT · NATÍV IMPORT IS MEGMARAD</em>}</button>)}</div></section>
  <section className="migration-grid"><div className="migration-card"><h2>2. Migrálandó adat</h2><div className="choice-grid">{Object.entries(ENTITY_LABELS).map(([code,label])=><button key={code} className={entity===code?"active":""} onClick={()=>setEntity(code)}><Users size={17}/>{label}{code==="appointments"&&<small>v18: előnézet</small>}</button>)}</div></div><div className="migration-card"><h2>3. Duplikációs szabály</h2><div className="policy-list">{POLICIES.map(p=><label key={p.code} className={policy===p.code?"active":""}><input type="radio" checked={policy===p.code} onChange={()=>setPolicy(p.code)}/><span><strong>{p.label}</strong><small>{p.hint}</small></span></label>)}</div></div></section>
  <section className="migration-card upload-card"><div><h2>4. Fájl és előnézet</h2><p>CSV/XLS/XLSX, legfeljebb 25 MB és 50 000 sor futásonként.</p></div><label className="file-picker"><FileSpreadsheet size={24}/><span>{file?.name||"Fájl kiválasztása"}</span><input type="file" accept=".csv,.xls,.xlsx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={busy||!file} onClick={createAndUpload}><UploadCloud size={18}/>{busy?"Feldolgozás…":"Staging + előnézet"}</button></section>
  {selectedProvider?.code==="altegio"&&<section className="migration-card legacy-altegio"><div><h2>Altegio kompatibilitási gyorsutak</h2><p>Szándékosan megmaradnak a v18 mellett. Ezek közvetlen importok; a v18 staging használata ajánlott.</p></div><div>{selectedProvider.legacy_tools?.map(t=><button key={t.path} disabled={busy||!file} onClick={()=>legacyUpload(t.path)}>Natív Altegio → {ENTITY_LABELS[t.entity]||t.entity}</button>)}</div></section>}
  {detail&&<section className="migration-card preview"><div className="preview-head"><div><span className="status">{detail.run.status}</span><h2>Futás: {detail.run.provider.toUpperCase()} → {ENTITY_LABELS[detail.run.entity_type]||detail.run.entity_type}</h2><p>{detail.run.filename}</p></div><button onClick={()=>openRun(detail.run.id)}><RefreshCcw size={17}/> Frissítés</button></div><div className="stats-grid"><div><small>Összes sor</small><strong>{fmt(stats.total)}</strong></div><div><small>Importálható</small><strong>{fmt(stats.ready)}</strong></div><div className={Number(stats.duplicates)>0?"warn":""}><small>Duplikált</small><strong>{fmt(stats.duplicates)}</strong></div><div><small>Hibás</small><strong>{fmt(stats.invalid||stats.failed)}</strong></div></div><div className="mapping"><h3>Automatikus mezőleképezés</h3>{Object.entries(detail.run.mapping||{}).length?<div className="mapping-grid">{Object.entries(detail.run.mapping||{}).map(([target,source])=><div key={target}><code>{String(source)}</code><span>→</span><strong>{target}</strong></div>)}</div>:<p>Nincs automatikusan felismert mező.</p>}</div><div className="preview-table"><table><thead><tr><th>Sor</th><th>Állapot</th><th>Duplikált cél</th><th>Hiba</th></tr></thead><tbody>{detail.items.slice(0,50).map(i=><tr key={i.id}><td>{i.row_number}</td><td>{i.disposition}</td><td>{i.duplicate_target_pk||"—"}</td><td>{i.error||"—"}</td></tr>)}</tbody></table></div><div className="actions"><button className="primary" disabled={busy||detail.run.entity_type==="appointments"} onClick={applyRun}><CheckCircle2 size={18}/> Import végrehajtása</button><button disabled={busy||!["completed","partial"].includes(detail.run.status)} onClick={rollback}><ArchiveRestore size={18}/> Rollback</button><button onClick={()=>window.open(`${window.location.origin}/api/vir/migration-center/runs/${detail.run.id}/evidence`,"_blank","noopener,noreferrer")}><History size={18}/> Evidence</button></div>{detail.run.entity_type==="appointments"&&<div className="migration-note">Az időpontok v18-ban előnézet/validáció módban vannak; kliens–szolgáltatás–munkatárs reláció feloldása nélkül nem írunk éles időpontot.</div>}</section>}
  <section className="migration-card"><h2>Korábbi migrációk</h2><div className="run-list">{runs.length?runs.map(r=><button key={r.id} onClick={()=>openRun(r.id)}><span><strong>{r.provider.toUpperCase()} · {ENTITY_LABELS[r.entity_type]||r.entity_type}</strong><small>{r.filename||"nincs fájl"}</small></span><em>{r.status}</em></button>):<p>Még nincs migrációs futás.</p>}</div></section>
 </div>;
}
