import React,{useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,CheckCircle2,ClipboardCheck,FileText,MessageSquareWarning,Plus,RefreshCw,ShieldCheck,Wrench}from"lucide-react";
import api from"../api/api";
import"./OperationsQualityPage.css";

const config:any={
 tasks:{title:"Teendők és jóváhagyások",icon:ClipboardCheck,desc:"Munkatárshoz rendelt feladat → elvégzés → vezetői jóváhagyás → 2018-as értékelés automatika.",states:[["open","Nyitott"],["assigned","Kiosztva"],["in_progress","Folyamatban"],["completed","Elvégezve – jóváhagyásra vár"],["approved","Jóváhagyva"]]},
 maintenance:{title:"Karbantartások és szervizek",icon:Wrench,desc:"Eszközök, szervizpartnerek, határidők és következő felülvizsgálatok.",states:[["reported","Bejelentve"],["scheduled","Ütemezve"],["in_progress","Folyamatban"],["resolved","Megoldva"]]},
 documents:{title:"Elektronikus dokumentumtár",icon:FileText,desc:"Szabályzatok, szerződések, igazolások, számlák és képesítések.",states:[["draft","Piszkozat"],["valid","Érvényes"],["expiring","Lejáró"],["expired","Lejárt"],["archived","Archivált"]]},
 "internal-email":{title:"Belső e-mail",icon:FileText,desc:"Belső és külső címzetteknek előkészített, követhető levelek.",states:[["draft","Piszkozat"],["queued","Küldésre vár"],["sent","Elküldve"],["failed","Sikertelen"]]},
 complaints:{title:"Panaszkezelés",icon:MessageSquareWarning,desc:"Személyesen, telefonon, online vagy e-mailben érkezett panaszok kivizsgálása.",states:[["new","Új"],["investigating","Vizsgálat"],["accepted","Jogos"],["rejected","Elutasítva"],["resolved","Lezárva"]]},
 audits:{title:"Minőségellenőrzések és auditok",icon:ShieldCheck,desc:"Higiéniai, dokumentációs, pénztár-, készlet- és vendégélmény-auditok.",states:[["planned","Tervezett"],["in_progress","Folyamatban"],["review","Felülvizsgálat"],["approved","Jóváhagyva"]]},
 incidents:{title:"Események és eltérések",icon:AlertTriangle,desc:"Balesetek, eszközhibák, adatvédelmi és szolgáltatásminőségi eltérések rögzítése.",states:[["open","Nyitott"],["investigating","Kivizsgálás"],["action_required","Intézkedés kell"],["resolved","Lezárva"]]}
};
const pathMap:any={"/extra/tasks":"tasks","/spec/maintenance":"maintenance","/extra/documents":"documents","/spec/internal-email":"internal-email","/marketing/complaints":"complaints","/operations/audits":"audits","/operations/incidents":"incidents"};
function err(e:any){return e?.response?.data?.message||e?.response?.data?.error||e?.message||"A művelet sikertelen."}
const freshForm=(moduleKey:string,cfg:any)=>({title:"",description:"",department:"",assignee:"",employee_id:"",priority:"normal",status:cfg.states[0][0],due_at:"",recurrence:"",requires_approval:moduleKey==="tasks"});

export default function OperationsQualityPage(){
 const moduleKey=pathMap[window.location.pathname]||"tasks",cfg=config[moduleKey],Icon=cfg.icon;
 const[data,setData]=useState<any>({records:[],summary:{},legacy2018:{}}),[employees,setEmployees]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[show,setShow]=useState(false),[form,setForm]=useState<any>(()=>freshForm(moduleKey,cfg));
 const load=useCallback(async()=>{setLoading(true);setError("");try{const overview=api.get("/transactions/operations-quality/overview");const people=moduleKey==="tasks"?api.get("/transactions/operations-quality/employees"):Promise.resolve({data:[]});const[o,p]=await Promise.all([overview,people]);setData(o.data);setEmployees(Array.isArray(p.data)?p.data:[])}catch(e){setError(err(e))}finally{setLoading(false)}},[moduleKey]);
 useEffect(()=>{setForm(freshForm(moduleKey,cfg));void load()},[moduleKey,load]);
 const rows=useMemo(()=>data.records.filter((x:any)=>x.module_key===moduleKey),[data.records,moduleKey]);
 async function run(fn:()=>Promise<any>,msg:string){setError("");setNotice("");try{await fn();setNotice(msg);await load()}catch(e){setError(err(e))}}
 async function save(e:React.FormEvent){e.preventDefault();await run(()=>api.post("/transactions/operations-quality/records",{...form,module_key:moduleKey,due_at:form.due_at||null}),"A tétel elmentve.");setShow(false);setForm(freshForm(moduleKey,cfg))}
 async function reconcile(){await run(()=>api.post("/transactions/operations-quality/legacy-2018/reconcile",{}),"A 2018-as értékelés automatikus piros X szinkronja lefutott.")}
 const isTasks=moduleKey==="tasks";
 const legacy=data.legacy2018||{};
 return <main className="opsq">
  <header><div><small>MŰKÖDÉS ÉS MINŐSÉG</small><h1><Icon/>{cfg.title}</h1><p>{cfg.desc}</p></div><div className="opsq-actions"><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/>Frissítés</button>{isTasks&&<button onClick={()=>void reconcile()}><RefreshCw/>2018 szinkron</button>}<button className="primary" onClick={()=>setShow(!show)}><Plus/>Új tétel</button></div></header>
  {error&&<div className="opsq-note error">{error}</div>}{notice&&<div className="opsq-note ok">{notice}</div>}
  <div className="opsq-kpis">
   <article><b>{rows.length}</b><span>Összes tétel</span></article>
   {isTasks?<><article><b>{rows.filter((x:any)=>x.requires_approval&&x.status==="completed").length}</b><span>Vezetői jóváhagyásra vár</span></article><article><b>{legacy.overdue_without_approval??0}</b><span>Lejárt, nincs jóváhagyva</span></article><article><b>{legacy.automatic_red_x??0}</b><span>Automatikus piros X</span></article></>:<><article><b>{rows.filter((x:any)=>!["approved","resolved","archived","valid","sent"].includes(x.status)).length}</b><span>Folyamatban</span></article><article><b>{rows.filter((x:any)=>x.requires_approval).length}</b><span>Jóváhagyást igényel</span></article><article><b>{rows.filter((x:any)=>x.priority==="high").length}</b><span>Kiemelt</span></article></>}
  </div>
  {isTasks&&<div className="opsq-note ok"><b>2018-as értékelési szabály:</b> egy lejárt, munkatárshoz rendelt és vezetői jóváhagyást igénylő feladat jóváhagyás nélkül 1 automatikus piros X-et ad. Jóváhagyáskor az automatikus X törlődik. Egy kézi piros vagy fekete pontbejegyzés maximum 5 pont lehet.</div>}
  {show&&<form className="opsq-form" onSubmit={save}><h2>Új {cfg.title.toLowerCase()} tétel</h2><label>Megnevezés<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Leírás<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div><label>Részleg<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label>{isTasks?<label>Munkatárs<select required value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}><option value="">Munkatárs kiválasztása</option>{employees.map((p:any)=><option key={p.id} value={p.id}>{p.full_name||`${p.last_name||""} ${p.first_name||""}`.trim()||p.id}</option>)}</select></label>:<label>Felelős / címzett<input value={form.assignee} onChange={e=>setForm({...form,assignee:e.target.value})}/></label>}<label>Határidő<input type="datetime-local" required={isTasks} value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Ismétlődés<select value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})}><option value="">Egyszeri</option><option>naponta</option><option>hetente</option><option>havonta</option><option>évente</option></select></label></div><label className="check"><input type="checkbox" checked={form.requires_approval} disabled={isTasks} onChange={e=>setForm({...form,requires_approval:e.target.checked})}/>{isTasks?"Vezetői jóváhagyás kötelező a 2018-as értékelési lánchoz":"Vezetői jóváhagyás szükséges"}</label><button className="primary">Mentés</button></form>}
  <section className="opsq-panel">{loading?<p className="empty">Betöltés…</p>:rows.length?rows.map((x:any)=>{const taskStates=isTasks?cfg.states.filter((s:any)=>s[0]!=="approved"||["completed","approved"].includes(x.status)):cfg.states;return <article className={`opsq-row ${x.priority}`} key={x.id}><div className="opsq-icon"><Icon/></div><div><h3>{x.title}{x.requires_approval&&<em>{x.status==="completed"?"Jóváhagyásra vár":"Jóváhagyandó"}</em>}</h3><p>{x.description||"Nincs leírás."}</p><small>{x.department||"Minden részleg"} · {x.employee_name||x.assignee||"Nincs felelős"}{x.due_at?` · Határidő: ${new Date(x.due_at).toLocaleString("hu-HU")}`:""}{x.recurrence?` · ${x.recurrence}`:""}{x.approved_at?` · Jóváhagyva: ${new Date(x.approved_at).toLocaleString("hu-HU")}`:""}</small></div><select value={x.status} onChange={e=>void run(()=>api.patch(`/transactions/operations-quality/records/${x.id}`,{status:e.target.value}),"Az állapot frissült.")}>{taskStates.map((s:any)=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select>{x.status==="completed"&&x.requires_approval&&<button className="approve" onClick={()=>void run(()=>api.patch(`/transactions/operations-quality/records/${x.id}`,{status:"approved"}),"A feladat vezetőileg jóváhagyva; az esetleges automatikus piros X törölve.")}><CheckCircle2/>Jóváhagyás</button>}</article>}):<p className="empty">Ebben a modulban még nincs tétel.</p>}</section>
 </main>
}
