import{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,CheckCircle2,ChevronRight,ClipboardCheck,Gauge,Link2,RefreshCw,Save,ShieldCheck,Target,TestTube2,TrendingDown,XCircle}from'lucide-react';
import{useNavigate}from'react-router-dom';
import api from'../api';
import'./OperationalRiskControlRegisterPage.css';

const BASE='/api/transactions/notifications/risk-register';
const statusHu:Record<string,string>={identified:'Azonosított',assessed:'Értékelt',mitigating:'Kezelés alatt',monitoring:'Megfigyelés',accepted:'Elfogadott',closed:'Lezárt'};
const bandHu:Record<string,string>={low:'Alacsony',medium:'Közepes',high:'Magas',critical:'Kritikus'};
const fmt=(v:any)=>v?new Date(v).toLocaleString('hu-HU'):'—';const n=(v:any)=>Number(v||0);const evidence=(description:string,source:string)=>description.trim()?{description:description.trim(),source}:{};

export default function OperationalRiskControlRegisterPage(){
 const nav=useNavigate();const[summary,setSummary]=useState<any>(null),[risks,setRisks]=useState<any[]>([]),[controls,setControls]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState('all'),[band,setBand]=useState('all');
 const[create,setCreate]=useState({title:'',description:'',category:'process',likelihood:3,impact:3,appetite_threshold:8,owner_key:''});const[edit,setEdit]=useState<any>({});
 const locationId=localStorage.getItem('kleo_location_id')||'';
 const query=useMemo(()=>{const p=new URLSearchParams();if(status!=='all')p.set('status',status);if(band!=='all')p.set('band',band);if(locationId)p.set('location_id',locationId);return p.toString()},[status,band,locationId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const loc=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const[a,b,c]=await Promise.all([api.get(`${BASE}/summary${loc}`),api.get(`${BASE}/risks?${query}`),api.get(`${BASE}/controls`)]);setSummary(a.data);setRisks(b.data?.items||[]);setControls(c.data?.items||[])}catch(e:any){setError(e?.response?.data?.message||'A Risk & Control Register nem tölthető be.')}finally{setLoading(false)}},[locationId,query]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const t=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(t)},[load]);
 async function open(id:string){try{const loc=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const r=await api.get(`${BASE}/risks/${id}${loc}`);setSelected(r.data);const x=r.data.item;setEdit({status:x.status,treatment:x.treatment,likelihood:x.likelihood,impact:x.impact,appetite_threshold:x.appetite_threshold,owner_key:x.owner_key||'',owner_team:x.owner_team||'',next_review_at:x.next_review_at?new Date(x.next_review_at).toISOString().slice(0,10):'',note:'',approver_key:'',evidence:''})}catch(e:any){setError(e?.response?.data?.message||'A risk nem nyitható meg.')}}
 async function sync(){try{const r=await api.post(`${BASE}/sync`);setNotice(`Risk sync kész: ${r.data?.created||0} új, ${r.data?.updated||0} frissített; Exception bridge: ${r.data?.exceptions?.detected||0} aktív jelzés.`);await load()}catch(e:any){setError(e?.response?.data?.message||'A risk sync nem futtatható.')}}
 async function createRisk(){if(create.title.trim().length<5||create.description.trim().length<10){setError('Legalább 5 karakteres cím és 10 karakteres leírás szükséges.');return}try{const r=await api.post(`${BASE}/risks`,{...create,location_id:locationId||null});setNotice('Operational risk létrehozva.');setCreate({...create,title:'',description:''});await load();if(r.data?.item?.id)await open(r.data.item.id)}catch(e:any){setError(e?.response?.data?.message||'A risk nem hozható létre.')}}
 async function saveRisk(){if(!selected)return;const closing=['accepted','closed'].includes(edit.status);if(closing&&(String(edit.note||'').trim().length<10||String(edit.evidence||'').trim().length<5)){setError('Elfogadáshoz/lezáráshoz részletes indok és evidence szükséges.');return}try{const body={...edit,next_review_at:edit.next_review_at?new Date(`${edit.next_review_at}T12:00:00`).toISOString():undefined,evidence:evidence(edit.evidence||'','risk-governance')};const r=await api.patch(`${BASE}/risks/${selected.item.id}`,body);setSelected(r.data);setNotice('Risk értékelés mentve.');await load()}catch(e:any){setError(e?.response?.data?.message||'A risk nem menthető.')}}
 async function linkControl(){if(!selected)return;const id=window.prompt('Control UUID a katalógusból:','')||'';if(!id.trim())return;try{const r=await api.post(`${BASE}/risks/${selected.item.id}/controls/${id}/link`,{weight:100,rationale:'Vezetői hozzárendelés'});setSelected(r.data);await load()}catch(e:any){setError(e?.response?.data?.message||'A control nem rendelhető hozzá.')}}
 async function testControl(c:any){const design=Number(window.prompt('Design effectiveness 0–100:',String(c.design_score||80))||'');const operating=Number(window.prompt('Operating effectiveness 0–100:',String(c.operation_score||80))||'');const note=window.prompt('Teszt értékelése (min. 10 karakter):','')||'';const ev=window.prompt('Teszt evidence (min. 5 karakter):','')||'';if(!Number.isFinite(design)||!Number.isFinite(operating)||note.trim().length<10||ev.trim().length<5)return;try{await api.post(`${BASE}/controls/${c.id}/tests`,{risk_id:selected?.item?.id||null,design_score:design,operating_score:operating,test_note:note,evidence:evidence(ev,'control-test')});setNotice('Control test rögzítve.');if(selected)await open(selected.item.id);await load()}catch(e:any){setError(e?.response?.data?.message||'A control test nem rögzíthető.')}}
 async function createKri(){if(!selected)return;const code=window.prompt('KRI kód:','KRI-')||'',name=window.prompt('KRI megnevezése:','')||'',desc=window.prompt('KRI leírása:','')||'',warning=Number(window.prompt('Warning küszöb:','5')||''),breach=Number(window.prompt('Breach küszöb:','10')||'');if(!code||!name||!desc||!Number.isFinite(warning)||!Number.isFinite(breach))return;try{await api.post(`${BASE}/risks/${selected.item.id}/kri`,{code,name,description:desc,direction:'max',warning_threshold:warning,breach_threshold:breach,frequency:'monthly'});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'A KRI nem hozható létre.')}}
 async function measureKri(k:any){const value=Number(window.prompt(`${k.name} új érték:`,String(k.last_value??''))||'');if(!Number.isFinite(value))return;const note=window.prompt('Mérési megjegyzés:','')||'';try{await api.post(`${BASE}/kri/${k.id}/measurements`,{value,note});await open(selected.item.id);await load()}catch(e:any){setError(e?.response?.data?.message||'A KRI mérés nem rögzíthető.')}}
 const heat=useMemo(()=>{const m=new Map<string,number>();for(const r of risks){const key=`${r.likelihood}:${r.impact}`;m.set(key,(m.get(key)||0)+1)}return m},[risks]);
 const item=selected?.item;
 return <div className="orr-page">
  <header className="orr-hero"><div><button onClick={()=>nav('/finance/exception-command-center/gameday')}><ChevronRight className="back"/> Business Continuity GameDay</button><span>STATISZTIKA ÉS VIR · ENTERPRISE RISK GOVERNANCE</span><h1><Gauge/> Operational Risk & Control Register</h1><p>Egységes kockázati nyilvántartás inherent/residual scoringgal, risk appetite-tal, key control tesztekkel, KRI-kkel és automatikus Exception visszacsatolással.</p></div><div className="orr-chain"><b>CONTROL LOOP</b><span>Exception → CAPA → Major Incident → Resilience → GameDay → Risk & Control → Exception</span></div></header>
  {error&&<div className="orr-error"><AlertTriangle/>{error}</div>}{notice&&<div className="orr-notice"><CheckCircle2/>{notice}</div>}
  {summary&&<section className="orr-kpis"><article className={n(summary.critical_residual)?'danger':''}><AlertTriangle/><div><small>Kritikus residual</small><b>{n(summary.critical_residual)}</b></div></article><article className={n(summary.outside_appetite)?'warning':''}><Target/><div><small>Appetite felett</small><b>{n(summary.outside_appetite)}</b></div></article><article><ShieldCheck/><div><small>Key controls</small><b>{n(summary.key_controls)}</b></div></article><article className={n(summary.key_controls_due)?'warning':''}><TestTube2/><div><small>Teszt esedékes</small><b>{n(summary.key_controls_due)}</b></div></article><article className={n(summary.breached_kri)?'danger':''}><Activity/><div><small>Breached KRI</small><b>{n(summary.breached_kri)}</b></div></article><article><TrendingDown/><div><small>Control effectiveness</small><b>{summary.avg_effectiveness==null?'—':`${summary.avg_effectiveness}%`}</b></div></article></section>}
  <section className="orr-top"><div className="orr-create"><h2><Gauge/> Új operational risk</h2><input value={create.title} onChange={e=>setCreate({...create,title:e.target.value})} placeholder="Risk cím"/><textarea value={create.description} onChange={e=>setCreate({...create,description:e.target.value})} placeholder="Risk event / ok / üzleti hatás…"/><div><select value={create.category} onChange={e=>setCreate({...create,category:e.target.value})}><option value="process">Process</option><option value="finance">Finance</option><option value="resilience">Resilience</option><option value="continuity">Continuity</option><option value="security">Security</option><option value="operations">Operations</option></select><input type="number" min="1" max="5" value={create.likelihood} onChange={e=>setCreate({...create,likelihood:Number(e.target.value)})}/><input type="number" min="1" max="5" value={create.impact} onChange={e=>setCreate({...create,impact:Number(e.target.value)})}/><input value={create.owner_key} onChange={e=>setCreate({...create,owner_key:e.target.value})} placeholder="Risk owner"/></div><button onClick={createRisk}><Save/> Risk létrehozása</button></div>
   <div className="orr-heat"><h2>5×5 Risk Heatmap</h2><div className="orr-matrix">{[5,4,3,2,1].map(impact=><div className="orr-matrix-row" key={impact}><b>I{impact}</b>{[1,2,3,4,5].map(likelihood=>{const score=impact*likelihood,cls=score>=16?'critical':score>=10?'high':score>=5?'medium':'low';return <div className={cls} key={`${likelihood}:${impact}`}><span>{score}</span><b>{heat.get(`${likelihood}:${impact}`)||0}</b></div>})}</div>)}<div className="orr-axis"><span></span>{[1,2,3,4,5].map(x=><b key={x}>L{x}</b>)}</div></div></div>
  </section>
  <div className="orr-filter"><div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Minden státusz</option>{Object.entries(statusHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={band} onChange={e=>setBand(e.target.value)}><option value="all">Minden residual band</option>{Object.entries(bandHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><button onClick={sync}><RefreshCw/> Források + Exception bridge szinkron</button></div>
  <section className="orr-work"><aside><header><b>Risk register</b><span>{risks.length}</span></header>{risks.map(r=><button key={r.id} className={`${selected?.item?.id===r.id?'selected':''} ${r.residual_band}`} onClick={()=>open(r.id)}><div><strong>{r.risk_no}</strong><em>{bandHu[r.residual_band]||r.residual_band}</em></div><b>{r.title}</b><small>{r.category} · {statusHu[r.status]||r.status}</small><footer><span>Inherent {r.inherent_score}/25</span><strong>Residual {r.residual_score}/25</strong><i className={r.appetite_state}>{r.appetite_state==='within'?'APPETITE OK':'APPETITE FELETT'}</i></footer></button>)}</aside>
   <main>{!selected?<div className="orr-empty"><Gauge/><h2>Válasszon risket</h2><p>A control mapping, KRI és governance részletek itt kezelhetők.</p></div>:<><header className="orr-detail"><div><span>{item.risk_no} · {statusHu[item.status]}</span><h2>{item.title}</h2><p>{item.description}</p></div><div className={`orr-appetite ${item.appetite_state}`}><Target/><b>{item.residual_score}/25</b><small>appetite ≤ {item.appetite_threshold}</small></div></header>
    <section className="orr-score"><article><span>Inherent</span><b>{item.inherent_score}/25</b><em>{bandHu[item.inherent_band]}</em></article><TrendingDown/><article><span>Residual</span><b>{item.residual_score}/25</b><em>{bandHu[item.residual_band]}</em></article><article><span>Control effectiveness</span><b>{item.control_effectiveness??0}%</b><em>{item.appetite_state==='within'?'within appetite':'outside appetite'}</em></article></section>
    <section className="orr-edit"><h3>Risk assessment & governance</h3><div><select value={edit.status||item.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{Object.entries(statusHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={edit.treatment||item.treatment} onChange={e=>setEdit({...edit,treatment:e.target.value})}><option value="reduce">Reduce</option><option value="avoid">Avoid</option><option value="transfer">Transfer</option><option value="accept">Accept</option><option value="monitor">Monitor</option></select><input type="number" min="1" max="5" value={edit.likelihood??item.likelihood} onChange={e=>setEdit({...edit,likelihood:Number(e.target.value)})}/><input type="number" min="1" max="5" value={edit.impact??item.impact} onChange={e=>setEdit({...edit,impact:Number(e.target.value)})}/><input type="number" min="1" max="25" value={edit.appetite_threshold??item.appetite_threshold} onChange={e=>setEdit({...edit,appetite_threshold:Number(e.target.value)})}/><input type="date" value={edit.next_review_at||''} onChange={e=>setEdit({...edit,next_review_at:e.target.value})}/><input value={edit.owner_key||''} onChange={e=>setEdit({...edit,owner_key:e.target.value})} placeholder="Risk owner"/><input value={edit.approver_key||''} onChange={e=>setEdit({...edit,approver_key:e.target.value})} placeholder="Független approver (accept)"/></div>{['accepted','closed'].includes(edit.status)&&<div><input value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})} placeholder="Governance indok / lezárási értékelés"/><input value={edit.evidence||''} onChange={e=>setEdit({...edit,evidence:e.target.value})} placeholder="Evidence"/></div>}<button onClick={saveRisk}><Save/> Risk assessment mentése</button></section>
    <section className="orr-controls"><header><div><h3><ShieldCheck/> Controls</h3><p>A residual score a hozzárendelt kontrollok legutóbbi effectiveness tesztjéből számolódik, maximum 80% kockázatcsökkentéssel.</p></div><button onClick={linkControl}><Link2/> Control hozzárendelés</button></header>{(selected.controls||[]).map((c:any)=><article key={c.id} className={c.is_key_control?'key':''}><div><span>{c.is_key_control?'KEY CONTROL':'CONTROL'} · {c.control_no}</span><b>{c.name}</b><small>{c.control_type} · {c.execution_mode} · {c.frequency}</small><p>{c.description}</p></div><div className="orr-control-score"><b>{n(c.effectiveness_score).toFixed(0)}%</b><small>effectiveness</small><em className={c.last_test?.result||'untested'}>{c.last_test?.result||'UNTESTED'}</em><button onClick={()=>testControl(c)}><TestTube2/> Teszt</button></div></article>)}</section>
    <section className="orr-kris"><header><div><h3><Activity/> Key Risk Indicators</h3><p>Append-only mérések; breach esetén automatikus Exception case.</p></div><button onClick={createKri}>+ KRI</button></header>{(selected.kris||[]).map((k:any)=><article key={k.id} className={k.last_state}><div><span>{k.code}</span><b>{k.name}</b><small>{k.description}</small></div><div><b>{k.last_value??'—'} {k.unit||''}</b><em>{String(k.last_state).toUpperCase()}</em><small>warning {k.warning_threshold} · breach {k.breach_threshold}</small><button onClick={()=>measureKri(k)}>Mérés</button></div></article>)}{!selected.kris?.length&&<div className="orr-empty-row">Még nincs KRI ehhez a riskhez.</div>}</section>
    <section className="orr-sources"><h3>Source chain</h3>{(selected.sources||[]).map((s:any)=><article key={s.id} className={s.status}><div><b>{s.source_type}</b><span>{s.source_key}</span></div><em>{s.severity}</em><small>{fmt(s.last_seen_at)}</small>{s.source_route&&<button onClick={()=>nav(s.source_route)}>Forrás megnyitása</button>}</article>)}</section>
    <section className="orr-timeline"><h3>Audit timeline</h3>{(selected.events||[]).map((e:any)=><article key={e.id}><span>{fmt(e.created_at)}</span><div><b>{e.event_type}</b><p>{e.message}</p><small>{e.actor_key}</small></div>{e.to_status&&<em>{e.from_status||'—'} → {e.to_status}</em>}</article>)}</section>
   </>}</main>
  </section>
  <section className="orr-catalog"><h2><ClipboardCheck/> Control catalogue</h2><div>{controls.map(c=><article key={c.id}><span>{c.control_no}{c.is_key_control?' · KEY':''}</span><b>{c.name}</b><small>{c.category} · {c.control_type} · {c.execution_mode} · {c.frequency}</small><p>{c.expected_evidence}</p><footer><strong>{n(c.effectiveness_score).toFixed(0)}%</strong><em>{c.last_result||'untested'}</em><button onClick={()=>testControl(c)}>Teszt</button></footer></article>)}</div></section>
 </div>
}
