import React,{useCallback,useEffect,useMemo,useState}from"react";
import{BadgeDollarSign,BookOpenCheck,Calculator,CheckCircle2,Download,FileText,Landmark,Mail,RefreshCw,Send,ShieldCheck,UsersRound}from"lucide-react";
import api from"../api";
import"./PayrollPage.css";

type Tab="payroll"|"runs"|"payslips"|"accounting"|"legal";
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,8)+"01";
const money=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const statusHu=(v:string)=>({draft:"Piszkozat",calculated:"Kiszámítva",approved:"Jóváhagyva",paid:"Kifizetve",cancelled:"Törölve"}as any)[v]||v;

export default function PayrollPage(){
 const initial=(new URLSearchParams(window.location.search).get("tab")||"payroll") as Tab;
 const[tab,setTab]=useState<Tab>(["payroll","runs","payslips","accounting","legal"].includes(initial)?initial:"payroll");
 const[from,setFrom]=useState(monthStart());const[to,setTo]=useState(today());const[locationId,setLocationId]=useState(localStorage.getItem("kleo_location_id")||"");
 const[locations,setLocations]=useState<any[]>([]);const[preview,setPreview]=useState<any>({items:[],totals:{}});const[runs,setRuns]=useState<any[]>([]);const[selectedRun,setSelectedRun]=useState<any>(null);const[runDetail,setRunDetail]=useState<any>(null);const[legal,setLegal]=useState<any>({});const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const show=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(""),3200)};
 const loadBase=useCallback(async()=>{setLoading(true);setError("");try{const[l,rules,rs]=await Promise.all([api.get("/api/locations"),api.get(`/api/payroll-accounting/legal-rules?date=${to}`),api.get("/api/payroll/runs")]);setLocations(Array.isArray(l.data)?l.data:[]);setLegal(rules.data||{});setRuns(Array.isArray(rs.data)?rs.data:[]);}catch(e:any){setError(e?.response?.data?.error||e?.message||"Az adatok nem tölthetők be.");}finally{setLoading(false)}},[to]);
 useEffect(()=>{loadBase()},[loadBase]);
 async function calc(){setLoading(true);setError("");try{const r=await api.post("/api/payroll/preview",{from,to,location_id:locationId||null});setPreview(r.data||{items:[],totals:{}});}catch(e:any){setError(e?.response?.data?.error||"A számfejtési előnézet nem készíthető el.");}finally{setLoading(false)}}
 useEffect(()=>{calc()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function createRun(){try{setLoading(true);await api.post("/api/payroll/runs",{from,to,location_id:locationId||null,title:`${from} – ${to} havi számfejtés`});show("Számfejtési futás létrehozva.");await loadBase();setTab("runs");}catch(e:any){setError(e?.response?.data?.error||"A futás nem hozható létre.");}finally{setLoading(false)}}
 async function setStatus(id:string,status:string){try{await api.patch(`/api/payroll/runs/${id}/status`,{status});show("Státusz módosítva.");await loadBase();if(selectedRun?.id===id)await openRun({...selectedRun,status});}catch(e:any){setError(e?.response?.data?.error||"A státusz nem módosítható.")}}
 async function openRun(r:any){setSelectedRun(r);setLoading(true);try{const d=await api.get(`/api/payroll-accounting/runs/${r.id}`);setRunDetail(d.data);setTab("payslips");}catch(e:any){setError(e?.response?.data?.error||"A számfejtés részletei nem tölthetők be.");}finally{setLoading(false)}}
 async function pdf(employeeId:string){if(!selectedRun)return;try{const r=await api.get(`/api/payroll-accounting/runs/${selectedRun.id}/employees/${employeeId}/payslip.pdf`,{responseType:"blob"});const u=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=u;a.download=`berjegyzek-${selectedRun.period_to}-${employeeId}.pdf`;a.click();URL.revokeObjectURL(u);}catch(e:any){setError(e?.response?.data?.error||"A bérjegyzék nem tölthető le.")}}
 async function emailOne(employeeId:string){if(!selectedRun)return;try{await api.post(`/api/payroll-accounting/runs/${selectedRun.id}/employees/${employeeId}/email-payslip`,{});show("Bérjegyzék elküldve.");await openRun(selectedRun);}catch(e:any){setError(e?.response?.data?.error||"Az e-mail nem küldhető el.")}}
 async function emailAll(){if(!selectedRun)return;try{setLoading(true);const r=await api.post(`/api/payroll-accounting/runs/${selectedRun.id}/email-all-payslips`,{});show(`${r.data.sent||0} bérjegyzék elküldve, ${r.data.failed||0} sikertelen.`);await openRun(selectedRun);}catch(e:any){setError(e?.response?.data?.error||"A tömeges küldés sikertelen.");}finally{setLoading(false)}}
 async function postLedger(){if(!selectedRun)return;try{await api.post(`/api/payroll-accounting/runs/${selectedRun.id}/post-to-ledger`,{});show("A számfejtés feladva a főkönyvbe.");await openRun(selectedRun);setTab("accounting");}catch(e:any){setError(e?.response?.data?.error||"A könyvelési feladás sikertelen.")}}
 const stats=useMemo(()=>({count:preview.items?.length||0,gross:preview.totals?.gross||0,net:preview.totals?.net||0,cost:(preview.totals?.gross||0)*(1+Number(legal.SZOCHO?.rate||0.13))}),[preview,legal]);
 const approved=selectedRun&&["approved","paid"].includes(selectedRun.status);
 return <main className="payroll-page">
 {notice&&<div className="payroll-toast"><CheckCircle2 size={17}/>{notice}</div>}
 <section className="payroll-hero"><div><span>PÉNZÜGYEK / KÖNYVELÉS</span><h1>Bérszámfejtési és könyvelési központ</h1><p>Munkaidő, jutalék, jogszabályi levonások, PDF bérjegyzék, e-mail és főkönyvi feladás egy folyamatban.</p></div><button className="payroll-primary" onClick={loadBase}><RefreshCw/>Frissítés</button></section>
 <section className="payroll-stats"><article><UsersRound/><div><small>Munkavállalók</small><strong>{stats.count}</strong></div></article><article><BadgeDollarSign/><div><small>Bruttó bértömeg</small><strong>{money(stats.gross)}</strong></div></article><article><Calculator/><div><small>Nettó kifizetés</small><strong>{money(stats.net)}</strong></div></article><article><Landmark/><div><small>Becsült teljes munkáltatói költség</small><strong>{money(stats.cost)}</strong></div></article></section>
 <nav className="payroll-tabs"><button className={tab==="payroll"?"active":""}onClick={()=>setTab("payroll")}><Calculator/>Havi számfejtés</button><button className={tab==="runs"?"active":""}onClick={()=>setTab("runs")}><FileText/>Számfejtési futások</button><button className={tab==="payslips"?"active":""}onClick={()=>setTab("payslips")}><Mail/>Bérjegyzékek</button><button className={tab==="accounting"?"active":""}onClick={()=>setTab("accounting")}><BookOpenCheck/>Könyvelés</button><button className={tab==="legal"?"active":""}onClick={()=>setTab("legal")}><ShieldCheck/>Jogszabályi paraméterek</button></nav>
 {error&&<div className="payroll-alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 {tab==="payroll"&&<section className="payroll-panel"><div className="payroll-toolbar"><label>Időszak<input type="date"value={from}onChange={e=>setFrom(e.target.value)}/><span>–</span><input type="date"value={to}onChange={e=>setTo(e.target.value)}/></label><label>Telephely<select value={locationId}onChange={e=>setLocationId(e.target.value)}><option value="">Minden telephely</option>{locations.map(x=><option key={x.id}value={x.id}>{x.name}</option>)}</select></label><button onClick={calc}>Előnézet</button><button className="finalize"onClick={createRun}disabled={!preview.items?.length||loading}>Számfejtés létrehozása</button></div><div className="payroll-table"><table><thead><tr><th>Munkatárs</th><th>Munkaidő</th><th>Alapbér</th><th>Jutalékok</th><th>Túlóra</th><th>Levonás</th><th>Bruttó</th><th>Nettó</th></tr></thead><tbody>{preview.items?.map((x:any)=><tr key={x.employee_id}><td><strong>{x.full_name}</strong><small>{x.position_name||""}</small></td><td>{(Number(x.regular_minutes||0)/60).toFixed(1)} ó</td><td>{money(x.base_pay)}</td><td>{money(Number(x.service_commission||0)+Number(x.product_commission||0)+Number(x.revenue_commission||0))}</td><td>{money(x.overtime_pay)}</td><td className="deduction">−{money(x.deductions)}</td><td><strong>{money(x.gross_pay)}</strong></td><td className="net"><strong>{money(x.net_pay)}</strong></td></tr>)}{!preview.items?.length&&<tr><td colSpan={8}className="empty">Nincs számfejthető adat.</td></tr>}</tbody></table></div></section>}
 {tab==="runs"&&<section className="payroll-panel"><div className="run-list">{runs.map(r=><article key={r.id}><div><span>{r.period_from} – {r.period_to}</span><h3>{r.title}</h3><small>{r.employee_count||0} munkatárs</small></div><div><small>Bruttó</small><strong>{money(r.gross_total)}</strong></div><div><small>Nettó</small><strong>{money(r.net_total)}</strong></div><div className="run-actions"><select value={r.status}onChange={e=>setStatus(r.id,e.target.value)}><option value="draft">Piszkozat</option><option value="calculated">Kiszámítva</option><option value="approved">Jóváhagyva</option><option value="paid">Kifizetve</option><option value="cancelled">Törölve</option></select><button onClick={()=>openRun(r)}>Megnyitás</button></div></article>)}</div></section>}
 {tab==="payslips"&&<section className="payroll-panel">{!selectedRun?<div className="empty">Válasszon egy számfejtési futást a „Számfejtési futások” fülön.</div>:<><header className="detail-head"><div><span>{selectedRun.period_from} – {selectedRun.period_to}</span><h2>{selectedRun.title}</h2><small>Állapot: {statusHu(selectedRun.status)}</small></div><div><button onClick={emailAll}disabled={!approved||loading}><Send size={16}/>Összes bérjegyzék küldése</button><button onClick={postLedger}disabled={!approved}><BookOpenCheck size={16}/>Főkönyvi feladás</button></div></header><div className="payroll-table"><table><thead><tr><th>Munkatárs</th><th>E-mail</th><th>Bruttó</th><th>SZJA</th><th>TB</th><th>Nettó</th><th>Szocho</th><th>Teljes költség</th><th>Bérjegyzék</th></tr></thead><tbody>{runDetail?.items?.map((x:any)=><tr key={x.employee_id}><td><strong>{x.full_name}</strong></td><td>{x.email||"—"}</td><td>{money(x.gross_pay)}</td><td>{money(x.statutory?.pit)}</td><td>{money(x.statutory?.tb)}</td><td className="net"><strong>{money(x.statutory?.net_pay)}</strong></td><td>{money(x.statutory?.employer_szocho)}</td><td>{money(x.statutory?.total_employer_cost)}</td><td><div className="row-actions"><button title="PDF"onClick={()=>pdf(x.employee_id)}disabled={!approved}><Download size={15}/></button><button title="E-mail"onClick={()=>emailOne(x.employee_id)}disabled={!approved||!x.email}><Mail size={15}/></button><span className={`mail-state ${x.email_status||""}`}>{x.email_status||"nincs"}</span></div></td></tr>)}</tbody></table></div></>}</section>}
 {tab==="accounting"&&<section className="payroll-panel accounting-view"><header><div><span>FŐKÖNYV</span><h2>Bérszámfejtési könyvelési feladások</h2><p>Jóváhagyott számfejtésből automatikusan létrehozott kettős könyvelési tételek.</p></div>{selectedRun&&<button onClick={postLedger}disabled={!approved}>Főkönyvi feladás</button>}</header>{runDetail?.journals?.length?runDetail.journals.map((j:any)=><article className="journal-card"key={j.id}><div><strong>{j.document_no}</strong><span>{j.entry_date} · {j.description}</span></div><table><thead><tr><th>Számla</th><th>Megnevezés</th><th>Tartozik</th><th>Követel</th></tr></thead><tbody>{(j.lines||[]).map((l:any)=><tr key={l.id}><td>{l.account_code}</td><td>{l.account_name}</td><td>{money(l.debit)}</td><td>{money(l.credit)}</td></tr>)}</tbody></table></article>):<div className="empty">Még nincs kiválasztott vagy könyvelt számfejtés. Nyisson meg egy jóváhagyott futást, majd végezze el a főkönyvi feladást.</div>}</section>}
 {tab==="legal"&&<section className="payroll-panel legal-view"><header><span>2026 / ÉRVÉNYES PARAMÉTEREK</span><h2>Jogszabályi számfejtési paraméterek</h2><p>A szabályok adatbázisban, érvényességi idővel tárolódnak. A munkavállalói kedvezmények nyilatkozathoz kötöttek.</p></header><div className="legal-grid">{Object.entries(legal).map(([code,v]:any)=><article key={code}><span>{code}</span><strong>{v.rate!=null?`${Number(v.rate)*100}%`:money(v.amount)}</strong><small>{v.amount?`Összeg: ${money(v.amount)}`:"Adó-/járulékkulcs"}</small></article>)}</div><div className="legal-warning"><ShieldCheck/><p><b>Kontrollpont:</b> a rendszer automatikusan számol, de a kedvezmények jogosultságát és a havi véglegesítést bérügyi jogosultsággal rendelkező személynek jóvá kell hagynia.</p></div></section>}
 </main>
}
