import React,{useEffect,useMemo,useState}from'react';
import{Banknote,CheckCircle2,CreditCard,FileText,Gift,RefreshCw,Search,WalletCards}from'lucide-react';
import api from'../api';
import FinanceOperationsPanel from'./finance/FinanceOperationsPanel';
import FinanceInvoicesPanel from'./finance/FinanceInvoicesPanel';
import FinanceControlCenter from'./finance/FinanceControlCenter';
import FinanceDailyDashboard from'./finance/FinanceDailyDashboard';
import FinanceAltegioWorkspace from'./finance/FinanceAltegioWorkspace';
import CashRegisterSessionPanel from'./finance/CashRegisterSessionPanel';
import WorkOrderLoyaltyPanel,{LoyaltySelection}from'./workorders/WorkOrderLoyaltyPanel';
import'./Penzugy.css';

type WorkOrder={id:string|number;work_order_number?:string;client_name?:string;status:string;created_at?:string;completed_at?:string;gross_total?:number;discount_amount?:number;tip_amount?:number;amount_due?:number;amount_paid?:number;paid_total?:number;payment_status?:string;invoice_status?:string;financial_closed_at?:string};
type PaymentRow={payment_method:string;amount:number;note?:string};
type Summary={cash_sales:number;card_sales:number;transfer_sales:number;voucher_sales:number;other_sales:number;tips:number;discounts:number;workorder_count:number};
const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString('hu-HU')} Ft`;
const methods=[['cash','Készpénz'],['card','Bankkártya'],['transfer','Átutalás'],['voucher','Utalvány'],['other','Egyéb']];
const emptyLoyalty:LoyaltySelection={walletAmount:0,pointsToSpend:0,couponCode:'',voucherCode:'',voucherAmount:0,passUsages:[]};
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export default function Penzugy(){
 const[orders,setOrders]=useState<WorkOrder[]>([]),[selected,setSelected]=useState<WorkOrder|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[discount,setDiscount]=useState(0),[tip,setTip]=useState(0),[invoiceStatus,setInvoiceStatus]=useState('not_requested'),[payments,setPayments]=useState<PaymentRow[]>([{payment_method:'cash',amount:0}]);
 const[loyalty,setLoyalty]=useState<LoyaltySelection>(emptyLoyalty);const[loyaltyResult,setLoyaltyResult]=useState<any>(null);
 const[summary,setSummary]=useState<Summary|null>(null),[dashboardRefresh,setDashboardRefresh]=useState(0);
 const locationId=localStorage.getItem('kleo_location_id')||'',today=localDate();
 async function load(){setLoading(true);setError('');try{const suffix=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const[o,s]=await Promise.all([api.get(`/api/transactions/cashier/workorders${suffix}`),api.get(`/api/transactions/cashier/daily-summary?date=${today}${locationId?`&location_id=${encodeURIComponent(locationId)}`:''}`)]);const rows:WorkOrder[]=o.data||[];setOrders(rows);setSummary(s.data||null);const target=new URLSearchParams(window.location.search).get('workorder');if(target){const hit=rows.find(x=>String(x.id)===String(target)||String(x.work_order_number||'')===String(target));if(hit)choose(hit)}}catch(e:any){setError(e?.response?.data?.message||'A pénztár adatai nem tölthetők be.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const refreshDashboard=()=>setDashboardRefresh(x=>x+1);
 async function refreshAll(){await load();refreshDashboard()}
 const filtered=useMemo(()=>orders.filter(o=>`${o.work_order_number||o.id} ${o.client_name||''} ${o.status} ${o.payment_status||''}`.toLowerCase().includes(query.toLowerCase())),[orders,query]);
 const baseGross=Number(selected?.gross_total||0),due=Math.max(0,baseGross-Number(discount||0)+Number(tip||0)),alreadyPaid=Number(selected?.paid_total||selected?.amount_paid||0),newPaymentTotal=payments.reduce((s,p)=>s+Number(p.amount||0),0),remaining=Math.max(0,due-alreadyPaid-newPaymentTotal);
 const hasLoyalty=Boolean(loyalty.accountId||loyalty.couponCode||loyalty.voucherCode||loyalty.passUsages.length||loyalty.walletAmount>0||loyalty.pointsToSpend>0);
 function choose(o:WorkOrder){setSelected(o);setDiscount(Number(o.discount_amount||0));setTip(Number(o.tip_amount||0));setInvoiceStatus(o.invoice_status||'not_requested');const open=Math.max(0,Number(o.gross_total||0)-Number(o.discount_amount||0)+Number(o.tip_amount||0)-Number(o.paid_total||o.amount_paid||0));setPayments([{payment_method:'cash',amount:open}]);setLoyalty(emptyLoyalty);setLoyaltyResult(null);setError('');setNotice('')}
 function updatePayment(index:number,patch:Partial<PaymentRow>){setPayments(prev=>prev.map((p,i)=>i===index?{...p,...patch}:p))}
 async function settle(closeFinancially:boolean){if(!selected)return;setLoading(true);setError('');setNotice('');const workOrderId=String(selected.id);try{if(hasLoyalty){const r=await api.post(`/api/transactions/loyalty-cashier/workorders/${workOrderId}/settle`,{discount_amount:Number(discount||0),tip_amount:Number(tip||0),invoice_status:invoiceStatus,close_financially:closeFinancially,payments:payments.filter(p=>Number(p.amount)>0),account_id:loyalty.accountId||null,customer_id:loyalty.customerId||null,wallet_amount:Number(loyalty.walletAmount||0),points_to_spend:Number(loyalty.pointsToSpend||0),coupon_code:loyalty.couponCode||null,voucher_code:loyalty.voucherCode||null,voucher_amount:Number(loyalty.voucherAmount||0),pass_usages:loyalty.passUsages});setLoyaltyResult(r.data?.settlement||null)}else await api.post(`/api/transactions/cashier/workorders/${workOrderId}/settle`,{discount_amount:Number(discount||0),tip_amount:Number(tip||0),invoice_status:invoiceStatus,close_financially:closeFinancially,payments:payments.filter(p=>Number(p.amount)>0)});
  if(closeFinancially){try{await api.post(`/api/transactions/workorder-finalization/workorders/${workOrderId}/finalize`,{});setNotice('Fizetés rögzítve, készlet és pénzügy könyvelve, jutalékalap létrehozva, a munkalap lezárva és archiválva.');window.history.replaceState({},'',window.location.pathname)}catch(finalizeError:any){setError(`A fizetés és a pénzügyi zárás megtörtént, de a végleges munkalap-zárás nem sikerült: ${finalizeError?.response?.data?.message||finalizeError?.message||'ismeretlen hiba'}`);await load();refreshDashboard();return}}
  setSelected(null);setLoyalty(emptyLoyalty);await load();refreshDashboard()
 }catch(e:any){setError(e?.response?.data?.message||'A fizetés nem menthető.')}finally{setLoading(false)}}
 return <div className="cashier-page">
  <div className="cashier-header"><div><span className="eyebrow">PÉNZÜGY</span><h1>Pénztár és pénzügyi lezárás</h1><p>Fizetés → pénzügyi zárás → készlet → jutalék → munkalap-archiválás egy folyamatban.</p></div><button onClick={()=>void refreshAll()} disabled={loading}><RefreshCw size={17}/> Frissítés</button></div>
  <FinanceDailyDashboard refreshKey={dashboardRefresh}/>
  <FinanceAltegioWorkspace/>
  {summary&&<div className="cashier-kpis"><article><Banknote/><span>Készpénz</span><b>{fmt(summary.cash_sales)}</b></article><article><CreditCard/><span>Kártya</span><b>{fmt(summary.card_sales)}</b></article><article><WalletCards/><span>Egyéb elektronikus</span><b>{fmt(Number(summary.transfer_sales||0)+Number(summary.other_sales||0))}</b></article><article><Gift/><span>Utalvány</span><b>{fmt(summary.voucher_sales)}</b></article><article><FileText/><span>Mai munkalapok</span><b>{summary.workorder_count||0}</b></article></div>}
  <CashRegisterSessionPanel onChanged={()=>{void refreshAll()}}/>
  {error&&<div className="cashier-error">{error}</div>}{notice&&<div style={{padding:12,marginBottom:14,borderRadius:10,background:'#ecfdf3',color:'#027a48'}}>{notice}</div>}{loyaltyResult&&<div style={{padding:12,marginBottom:14,borderRadius:10,background:'#ecfdf3',color:'#027a48'}}>Hűségelszámolás kész: kupon {fmt(loyaltyResult.coupon_discount)}, pont {fmt(loyaltyResult.points_discount)}, bérlet {fmt(loyaltyResult.pass_value_used)}, wallet {fmt(loyaltyResult.wallet_used)}, utalvány {fmt(loyaltyResult.voucher_used)}, jóváírt pont {Number(loyaltyResult.points_earned||0).toLocaleString('hu-HU')}.</div>}
  <div className="cashier-grid">
   <section className="cashier-card order-list-card"><div className="card-title"><div><h2>Munkalapok</h2><small>Fizetésre váró és lezárt tételek</small></div><div className="cashier-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Vendég vagy munkalap…"/></div></div><div className="cashier-order-list">{filtered.map(o=><button key={String(o.id)} className={selected?.id===o.id?'active':''} onClick={()=>choose(o)}><div><b>{o.work_order_number||`#${o.id}`} · {o.client_name||'Névtelen vendég'}</b><small>{o.completed_at?new Date(o.completed_at).toLocaleString('hu-HU'):o.status}</small></div><div className="order-money"><b>{fmt(o.gross_total)}</b><span className={`status ${o.payment_status||'unpaid'}`}>{o.payment_status==='paid'?'Fizetve':o.payment_status==='partial'?'Részfizetés':'Fizetendő'}</span></div></button>)}{!filtered.length&&<div className="empty-state">Nincs megjeleníthető munkalap.</div>}</div></section>
   <section className="cashier-card settlement-card"><div className="card-title"><div><h2>Fizetés rögzítése</h2><small>{selected?(selected.work_order_number||`Munkalap #${selected.id}`):'Válassz egy munkalapot'}</small></div></div>{!selected?<div className="empty-state large">A bal oldali listából válassz munkalapot.</div>:<><div className="money-summary"><div><span>Bruttó összeg</span><b>{fmt(baseGross)}</b></div><div><span>Már fizetve</span><b>{fmt(alreadyPaid)}</b></div><div className="total"><span>Fizetendő</span><b>{fmt(due)}</b></div></div><div className="field-row"><label>Kedvezmény (Ft)<input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><label>Borravaló (Ft)<input type="number" min="0" value={tip} onChange={e=>setTip(Number(e.target.value))}/></label></div><label className="full-field">Számlázási állapot<select value={invoiceStatus} onChange={e=>setInvoiceStatus(e.target.value)}><option value="not_requested">Nem kért számlát</option><option value="requested">Számla kért</option><option value="issued">Számla kiállítva</option><option value="cancelled">Számla sztornózva</option></select></label><h3>Fizetések</h3><div className="payment-lines">{payments.map((p,i)=><div className="payment-line" key={i}><select value={p.payment_method} onChange={e=>updatePayment(i,{payment_method:e.target.value})}>{methods.map(m=><option key={m[0]} value={m[0]}>{m[1]}</option>)}</select><input type="number" min="0" value={p.amount} onChange={e=>updatePayment(i,{amount:Number(e.target.value)})}/><button onClick={()=>setPayments(prev=>prev.filter((_,x)=>x!==i))}>×</button></div>)}</div><button className="add-payment" onClick={()=>setPayments(p=>[...p,{payment_method:'card',amount:remaining}])}>+ Fizetési mód hozzáadása</button>{hasLoyalty&&<div style={{fontSize:12,color:'#6941c6',marginTop:8}}>A hűségkedvezményeket és hűségfizetéseket a lezáráskor a rendszer automatikusan levonja. A készpénz/kártya összeget a backend a tényleges fennmaradó összegre korlátozza.</div>}<div className="remaining"><span>Hátralék a normál fizetés alapján</span><b>{fmt(remaining)}</b></div><div className="settle-actions"><button className="secondary" onClick={()=>void settle(false)} disabled={loading}>Részfizetés mentése</button><button className="primary" onClick={()=>void settle(true)} disabled={loading}><CheckCircle2 size={17}/> Fizetés + végleges lezárás</button></div></>}</section>
  </div>
  {selected&&<WorkOrderLoyaltyPanel key={String(selected.id)} grossTotal={baseGross} disabled={loading} onChange={setLoyalty}/>} 
  <FinanceOperationsPanel/><FinanceInvoicesPanel/><FinanceControlCenter/>
 </div>
}
