import React,{useEffect,useMemo,useState}from'react';
import{CreditCard,FileText,Minus,PackagePlus,Plus,Receipt,Search,ShoppingBag,Trash2}from'lucide-react';
import api from'../api/api';

type Product={id:string;name:string;price:number|string;available_stock?:number|string;vat_rate?:number|string};
type Location={id:string;name:string};
type Line={product:Product;quantity:number};
const money=(v:unknown)=>`${Number(v||0).toLocaleString('hu-HU',{maximumFractionDigits:0})} Ft`;

export default function ProductSalePage(){
 const[locations,setLocations]=useState<Location[]>([]);const[locationId,setLocationId]=useState('');const[products,setProducts]=useState<Product[]>([]);const[lines,setLines]=useState<Line[]>([]);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState<any>(null);
 const[payment,setPayment]=useState('card');const[invoice,setInvoice]=useState(false);const[customer,setCustomer]=useState({name:'',phone:'',email:'',postal_code:'',city:'',address:'',tax_number:''});
 useEffect(()=>{void(async()=>{setLoading(true);try{const r=await api.get('/transactions/workorder-editor/options');const ls=Array.isArray(r.data?.locations)?r.data.locations:[];setLocations(ls);const initial=String(r.data?.location?.id||r.data?.scope?.location_id||ls[0]?.id||'');setLocationId(initial)}catch{}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!locationId)return;void(async()=>{try{const r=await api.get('/transactions/cashier/retail/products',{params:{location_id:locationId}});setProducts(Array.isArray(r.data)?r.data:[])}catch(e:any){setError(e?.response?.data?.message||e?.message||'A terméklista nem tölthető be.')}})()},[locationId]);
 const shown=useMemo(()=>{const q=query.trim().toLocaleLowerCase('hu-HU');return q?products.filter(p=>p.name.toLocaleLowerCase('hu-HU').includes(q)):products},[products,query]);
 const total=useMemo(()=>lines.reduce((n,l)=>n+Number(l.product.price||0)*l.quantity,0),[lines]);
 const add=(p:Product)=>setLines(v=>{const hit=v.find(x=>x.product.id===p.id);return hit?v.map(x=>x.product.id===p.id?{...x,quantity:x.quantity+1}:x):[...v,{product:p,quantity:1}]});
 const qty=(id:string,d:number)=>setLines(v=>v.map(x=>x.product.id===id?{...x,quantity:Math.max(.01,Math.round((x.quantity+d)*100)/100)}:x));
 async function complete(){if(!locationId||!lines.length)return;setSaving(true);setError('');setSuccess(null);try{const body={location_id:locationId,payment_method:payment,invoice_requested:invoice,customer_name:customer.name||null,customer_phone:customer.phone||null,customer_email:customer.email||null,billing_name:customer.name||'Magánszemély',billing_tax_number:customer.tax_number||null,billing_country_code:'HU',billing_postal_code:customer.postal_code||null,billing_city:customer.city||null,billing_address:customer.address||null,items:lines.map(l=>({product_id:l.product.id,quantity:l.quantity,unit_price:Number(l.product.price||0)}))};const r=await api.post('/transactions/cashier/retail/sales',body);setSuccess(r.data);setLines([])}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||'A termékeladás nem rögzíthető.')}finally{setSaving(false)}}
 return <main style={page}>
  <header style={hero}><div><span style={kicker}><ShoppingBag size={16}/> TERMÉKELADÁS</span><h1 style={{margin:'6px 0'}}>Bolti értékesítés</h1><p style={muted}>Termék eladása szolgáltatás és munkalap nélkül. Igény esetén számlatervezet is készül.</p></div><div style={totalBox}><span>Fizetendő</span><b>{money(total)}</b></div></header>
  {error&&<div style={bad}>{error}</div>}{success&&<div style={good}><Receipt/><div><b>Az eladás rögzítve.</b><span>Eladás: {String(success.sale?.id||'—')}{success.invoice?.invoice_no?` · Számla: ${success.invoice.invoice_no}`:''}</span></div></div>}
  <div style={layout}>
   <section style={panel}><h2 style={sectionTitle}><PackagePlus/> Termék kiválasztása</h2><div style={toolbar}><label style={field}>Szalon<select style={input} value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label style={{...field,flex:1}}><Search size={15}/> Keresés<input style={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Termék neve"/></label></div>{loading?<div style={empty}>Betöltés…</div>:<div style={productGrid}>{shown.slice(0,120).map(p=><button key={p.id} type="button" style={productCard} onClick={()=>add(p)}><b>{p.name}</b><span>{money(p.price)}</span><small>Készlet: {Number(p.available_stock||0).toLocaleString('hu-HU')}</small></button>)}</div>}</section>
   <section style={panel}><h2 style={sectionTitle}><ShoppingBag/> Kosár</h2>{lines.length?<div style={{display:'grid',gap:8}}>{lines.map(l=><div key={l.product.id} style={line}><div><b>{l.product.name}</b><small>{money(l.product.price)} / db</small></div><div style={qtyBox}><button type="button" onClick={()=>qty(l.product.id,-1)}><Minus size={14}/></button><b>{l.quantity.toLocaleString('hu-HU')}</b><button type="button" onClick={()=>qty(l.product.id,1)}><Plus size={14}/></button></div><b>{money(Number(l.product.price||0)*l.quantity)}</b><button type="button" style={trash} onClick={()=>setLines(v=>v.filter(x=>x.product.id!==l.product.id))}><Trash2 size={15}/></button></div>)}</div>:<div style={empty}>Még nincs termék a kosárban.</div>}
    <hr style={hr}/><h3>Fizetés</h3><label style={field}>Fizetési mód<select style={input} value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Készpénz</option><option value="card">Bankkártya</option><option value="transfer">Átutalás</option><option value="voucher">Utalvány</option><option value="other">Egyéb</option></select></label><label style={check}><input type="checkbox" checked={invoice} onChange={e=>setInvoice(e.target.checked)}/><FileText size={16}/> Számlát kérek a termékekről</label>{invoice&&<div style={formGrid}><label style={field}>Számlázási név<input style={input} value={customer.name} onChange={e=>setCustomer(v=>({...v,name:e.target.value}))}/></label><label style={field}>Adószám (ha cég)<input style={input} value={customer.tax_number} onChange={e=>setCustomer(v=>({...v,tax_number:e.target.value}))}/></label><label style={field}>Irányítószám<input style={input} value={customer.postal_code} onChange={e=>setCustomer(v=>({...v,postal_code:e.target.value}))}/></label><label style={field}>Város<input style={input} value={customer.city} onChange={e=>setCustomer(v=>({...v,city:e.target.value}))}/></label><label style={{...field,gridColumn:'1/-1'}}>Cím<input style={input} value={customer.address} onChange={e=>setCustomer(v=>({...v,address:e.target.value}))}/></label></div>}<button type="button" style={primary} disabled={saving||!lines.length||!locationId} onClick={()=>void complete()}><CreditCard size={17}/>{saving?'Rögzítés…':invoice?'Eladás és számla létrehozása':'Eladás rögzítése'}</button>
   </section>
  </div>
 </main>
}
const page:React.CSSProperties={padding:'24px',maxWidth:1500,margin:'0 auto'};const hero:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',flexWrap:'wrap',marginBottom:18};const kicker:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:6,fontWeight:900,fontSize:12,letterSpacing:'.08em'};const muted:React.CSSProperties={color:'#74675d',margin:0};const totalBox:React.CSSProperties={display:'grid',padding:'14px 20px',borderRadius:14,background:'#241d18',color:'#fff',minWidth:180};const layout:React.CSSProperties={display:'grid',gridTemplateColumns:'minmax(0,1.35fr) minmax(340px,.65fr)',gap:16};const panel:React.CSSProperties={background:'#fff',border:'1px solid #eee4dc',borderRadius:16,padding:16,boxShadow:'0 8px 24px rgba(48,36,25,.07)'};const sectionTitle:React.CSSProperties={display:'flex',alignItems:'center',gap:7,margin:'0 0 12px'};const toolbar:React.CSSProperties={display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'};const field:React.CSSProperties={display:'grid',gap:5,fontSize:12,fontWeight:800};const input:React.CSSProperties={height:40,border:'1px solid #d8cec4',borderRadius:9,padding:'0 10px',boxSizing:'border-box',width:'100%'};const productGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(170px,1fr))',gap:8,marginTop:12,maxHeight:520,overflow:'auto'};const productCard:React.CSSProperties={display:'grid',gap:5,textAlign:'left',padding:12,border:'1px solid #e8ded5',borderRadius:11,background:'#fff',cursor:'pointer'};const empty:React.CSSProperties={padding:14,border:'1px dashed #d8cec4',borderRadius:10,color:'#74675d',marginTop:10};const line:React.CSSProperties={display:'grid',gridTemplateColumns:'minmax(0,1fr) auto auto auto',gap:8,alignItems:'center',padding:'9px 0',borderBottom:'1px solid #eee4dc'};const qtyBox:React.CSSProperties={display:'flex',alignItems:'center',gap:6};const trash:React.CSSProperties={border:0,background:'transparent',cursor:'pointer'};const hr:React.CSSProperties={border:0,borderTop:'1px solid #eee4dc',margin:'16px 0'};const check:React.CSSProperties={display:'flex',alignItems:'center',gap:7,margin:'12px 0',fontWeight:800};const formGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'1fr 1fr',gap:8};const primary:React.CSSProperties={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:7,width:'100%',marginTop:14,border:0,borderRadius:11,padding:'12px 14px',background:'#2b2118',color:'#fff',fontWeight:900,cursor:'pointer'};const bad:React.CSSProperties={padding:11,borderRadius:10,background:'#fef3f2',color:'#b42318',marginBottom:12};const good:React.CSSProperties={display:'flex',gap:9,alignItems:'center',padding:11,borderRadius:10,background:'#ecfdf3',color:'#067647',marginBottom:12};
