import React, { useEffect, useMemo, useRef, useState } from "react";
import { ChevronDown, ChevronRight, FileSpreadsheet, Loader2, Package, Search, SlidersHorizontal, Upload } from "lucide-react";
import withBase from "../utils/apiBase";

type Product = {
  id:string; name:string; internal_code?:string|null; barcode?:string|null; brand?:string|null;
  product_group_id?:string|null; product_category_id?:string|null; product_group_name?:string|null; product_category_name?:string|null;
  purchase_price_net?:number|null; retail_price_gross?:number|null; is_active?:boolean|null;
  critical_quantity?:number|null; ordered_quantity?:number|null;
};
type ImportResult={ok?:boolean;sourceRows?:number;categories?:number;created?:number;updated?:number;skipped?:number;error?:string;detail?:string;code?:string|null};
const token=()=>localStorage.getItem("kleo_token")||localStorage.getItem("token")||"";
const auth=()=>token()?{Authorization:`Bearer ${token()}`} : undefined;
const money=(v:any)=>v==null?"—":`${Number(v).toLocaleString("hu-HU")} Ft`;

export default function ProductCatalogPage(){
  const [items,setItems]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [q,setQ]=useState(""); const [group,setGroup]=useState(""); const [category,setCategory]=useState(""); const [minPrice,setMinPrice]=useState(""); const [maxPrice,setMaxPrice]=useState(""); const [inactive,setInactive]=useState(false);
  const [openGroups,setOpenGroups]=useState<Record<string,boolean>>({}); const [openCats,setOpenCats]=useState<Record<string,boolean>>({});
  const inputRef=useRef<HTMLInputElement|null>(null); const [uploading,setUploading]=useState(false); const [msg,setMsg]=useState(""); const [msgErr,setMsgErr]=useState(false);
  const load=async()=>{try{setLoading(true);setError("");const r=await fetch(withBase(`products${inactive?"?include_inactive=1":""}`),{headers:auth()});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();setItems(Array.isArray(d)?d:[]);}catch(e:any){setError(e?.message||"A termékek betöltése nem sikerült.");}finally{setLoading(false)}};
  useEffect(()=>{void load()},[inactive]);

  const groups=useMemo(()=>Array.from(new Set(items.map(x=>x.product_group_name||"Egyéb"))).sort((a,b)=>a.localeCompare(b,"hu")),[items]);
  const cats=useMemo(()=>Array.from(new Set(items.filter(x=>!group||(x.product_group_name||"Egyéb")===group).map(x=>x.product_category_name||"Egyéb"))).sort((a,b)=>a.localeCompare(b,"hu")),[items,group]);
  const filtered=useMemo(()=>items.filter(x=>{const s=`${x.name} ${x.internal_code||""} ${x.barcode||""} ${x.brand||""}`.toLocaleLowerCase("hu-HU");const p=Number(x.retail_price_gross??0);if(q&& !s.includes(q.toLocaleLowerCase("hu-HU")))return false;if(group&&(x.product_group_name||"Egyéb")!==group)return false;if(category&&(x.product_category_name||"Egyéb")!==category)return false;if(minPrice&&p<Number(minPrice))return false;if(maxPrice&&p>Number(maxPrice))return false;return true}),[items,q,group,category,minPrice,maxPrice]);
  const tree=useMemo(()=>{const gm=new Map<string,Map<string,Product[]>>();filtered.forEach(p=>{const g=p.product_group_name||"Egyéb";const c=p.product_category_name||"Egyéb";if(!gm.has(g))gm.set(g,new Map());const cm=gm.get(g)!;if(!cm.has(c))cm.set(c,[]);cm.get(c)!.push(p)});return Array.from(gm.entries()).sort(([a],[b])=>a.localeCompare(b,"hu"));},[filtered]);

  const importFile=async(file:File)=>{const form=new FormData();form.append("file",file);try{setUploading(true);setMsgErr(false);setMsg("Altegio termékek importálása…");const r=await fetch(withBase("products/import/altegio"),{method:"POST",headers:auth(),body:form});const d=(await r.json().catch(()=>({}))) as ImportResult;if(!r.ok||!d.ok){const tail=[d.code?`[${d.code}]`:"",d.detail||""].filter(Boolean).join(" ");throw new Error(`${d.error||`Import hiba (${r.status})`}${tail?` ${tail}`:""}`)}setMsg(`${d.categories??0} kategória · új ${d.created??0} · frissített ${d.updated??0} · kihagyott ${d.skipped??0}`);await load();}catch(e:any){setMsgErr(true);setMsg(e?.message||"Az Altegio termékimport nem sikerült.");}finally{setUploading(false);if(inputRef.current)inputRef.current.value=""}};

  return <div style={{padding:"18px 22px 36px",maxWidth:1700,margin:"0 auto"}}><section style={{background:"#fff",border:"1px solid #eee8de",borderRadius:18,boxShadow:"0 12px 34px rgba(45,34,21,.06)",overflow:"hidden"}}>
    <div style={{padding:"22px 24px 16px",display:"flex",justifyContent:"space-between",gap:16,borderBottom:"1px solid #f0ece5",alignItems:"flex-start"}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:".08em",textTransform:"uppercase",color:"#9b7c43"}}>Törzsadatok</div><h1 style={{margin:"5px 0 4px",fontSize:26,color:"#211b16"}}>Termékek</h1><p style={{margin:0,color:"#756d64",fontSize:13}}>Termékcsoport → kategória → termék hierarchia, Altegio importtal.</p></div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}>{msg&&<span style={{fontSize:12,fontWeight:700,color:msgErr?"#b42318":"#357a55",maxWidth:520}}>{msg}</span>}<input ref={inputRef} type="file" accept=".xls,.xlsx" style={{display:"none"}} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/><button disabled={uploading} onClick={()=>inputRef.current?.click()} style={secondaryBtn}>{uploading?<Loader2 size={16}/>:<FileSpreadsheet size={16}/>} {uploading?"Importálás…":"Altegio Excel import"} {!uploading&&<Upload size={14}/>}</button><button onClick={()=>setInactive(v=>!v)} style={secondaryBtn}>{inactive?"Csak aktív":"Inaktívak is"}</button></div></div>
    <div style={{padding:"16px 20px 18px",background:"linear-gradient(180deg,#fff,#fcfaf6)",borderBottom:"1px solid #eee8de"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12,color:"#6b5b48",fontWeight:800,fontSize:13}}><SlidersHorizontal size={16}/>Szűrés</div><div style={{display:"grid",gridTemplateColumns:"minmax(260px,1.6fr) minmax(180px,1fr) minmax(180px,1fr) 130px 130px auto",gap:10,alignItems:"end"}}><Field label="Név / cikkszám / vonalkód"><div style={inputWrap}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Keresés…" style={input}/></div></Field><Field label="Termékcsoport"><select value={group} onChange={e=>{setGroup(e.target.value);setCategory("")}} style={select}><option value="">Összes csoport</option>{groups.map(g=><option key={g}>{g}</option>)}</select></Field><Field label="Kategória"><select value={category} onChange={e=>setCategory(e.target.value)} style={select}><option value="">Összes kategória</option>{cats.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Min. ár"><input type="number" value={minPrice} onChange={e=>setMinPrice(e.target.value)} style={inputBare}/></Field><Field label="Max. ár"><input type="number" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} style={inputBare}/></Field><button onClick={()=>{setQ("");setGroup("");setCategory("");setMinPrice("");setMaxPrice("")}} style={secondaryBtn}>Törlés</button></div></div>
    <div style={{padding:"12px 20px 6px",fontSize:12,color:"#756d64"}}><b style={{color:"#211b16"}}>{filtered.length}</b> termék · a csoportok és alkategóriák alapból zártak</div>
    {error&&<div style={{margin:20,padding:12,borderRadius:10,background:"#fff0f0",color:"#9c2d2d",fontWeight:700}}>{error}</div>}
    {loading?<div style={{padding:30}}>Termékek betöltése…</div>:<div style={{padding:"4px 14px 18px"}}>{tree.map(([g,cm])=>{const go=openGroups[g]===true;const count=Array.from(cm.values()).reduce((a,b)=>a+b.length,0);return <div key={g} style={box}><button onClick={()=>setOpenGroups(p=>({...p,[g]:!go}))} style={groupBtn}>{go?<ChevronDown size={17}/>:<ChevronRight size={17}/>}<Package size={16}/><strong style={{flex:1}}>{g}</strong><Badge>{count} termék</Badge></button>{go&&<div style={{padding:"5px 8px 9px"}}>{Array.from(cm.entries()).sort(([a],[b])=>a.localeCompare(b,"hu")).map(([c,rows])=>{const ck=`${g}::${c}`;const co=openCats[ck]===true;return <div key={ck} style={{border:"1px solid #f0ece5",borderRadius:10,marginTop:6,overflow:"hidden"}}><button onClick={()=>setOpenCats(p=>({...p,[ck]:!co}))} style={catBtn}>{co?<ChevronDown size={15}/>:<ChevronRight size={15}/>}<strong style={{flex:1}}>{c}</strong><Badge>{rows.length}</Badge></button>{co&&<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr><Th>Név</Th><Th>Cikkszám</Th><Th>Vonalkód</Th><Th>Beszerzési ár</Th><Th>Eladási ár</Th><Th>Állapot</Th></tr></thead><tbody>{rows.sort((a,b)=>a.name.localeCompare(b.name,"hu")).map(p=><tr key={p.id} style={{borderTop:"1px solid #f2eee8"}}><Td><b>{p.name}</b></Td><Td>{p.internal_code||"—"}</Td><Td>{p.barcode||"—"}</Td><Td>{money(p.purchase_price_net)}</Td><Td>{money(p.retail_price_gross)}</Td><Td><span style={{fontWeight:800,color:p.is_active===false?"#9a514b":"#2f7654"}}>{p.is_active===false?"inaktív":"aktív"}</span></Td></tr>)}</tbody></table></div>}</div>})}</div>}</div>})}</div>}
  </section></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:6,fontSize:11,fontWeight:800,color:"#6f655c"}}>{label}{children}</label>}
function Badge({children}:{children:React.ReactNode}){return <span style={{fontSize:11,fontWeight:800,color:"#9b7c43",background:"#f4eddf",padding:"4px 8px",borderRadius:999}}>{children}</span>}
function Th({children}:{children:React.ReactNode}){return <th style={{textAlign:"left",padding:"10px 13px",fontSize:10,letterSpacing:".07em",textTransform:"uppercase",color:"#8a7f74",fontWeight:900}}>{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td style={{padding:"11px 13px",color:"#62594f",verticalAlign:"top"}}>{children}</td>}
const box:React.CSSProperties={border:"1px solid #eee8de",borderRadius:12,margin:"8px 0",overflow:"hidden",background:"#fff"};
const groupBtn:React.CSSProperties={width:"100%",border:0,background:"#fbfaf7",padding:"13px 15px",display:"flex",alignItems:"center",gap:10,cursor:"pointer",textAlign:"left",color:"#2a221a"};
const catBtn:React.CSSProperties={width:"100%",border:0,background:"#fff",padding:"11px 13px",display:"flex",alignItems:"center",gap:8,cursor:"pointer",textAlign:"left",color:"#4a4036"};
const secondaryBtn:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,padding:"0 13px",background:"#fff",color:"#5f554b",fontWeight:750,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:7};
const inputWrap:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,display:"flex",alignItems:"center",gap:7,padding:"0 10px",background:"#fff",color:"#8c8175"};
const input:React.CSSProperties={border:0,outline:"none",width:"100%",fontSize:12,background:"transparent",color:"#29221c"};
const inputBare:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,padding:"0 10px",fontSize:12,outline:"none",background:"#fff",boxSizing:"border-box"};
const select:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,padding:"0 10px",fontSize:12,outline:"none",background:"#fff",color:"#29221c",width:"100%"};
