import React,{useCallback,useEffect,useMemo,useState}from"react";
import withBase from"../utils/apiBase";
import"./ProductTaxonomyReviewPage.css";

type Group={id:string;name:string;code?:string|null};
type Category={id:string;name:string;code?:string|null;product_group_id?:string|null};
type ReviewItem={id:string;name:string;internal_code?:string|null;brand?:string|null;line_name?:string|null;source_category_name?:string|null;source_system?:string|null;taxonomy_source?:string|null;taxonomy_confidence?:number|null;product_group_id?:string|null;product_group_name?:string|null;product_category_id?:string|null;product_category_name?:string|null;is_unclassified?:boolean;is_low_confidence?:boolean;is_fallback?:boolean;last_manual_review_at?:string|null};
type Summary={taxonomy_version?:string;total:number;active:number;unclassified:number;low_confidence:number;fallback:number;manual:number};
type Mode="review"|"low"|"fallback"|"unclassified"|"all";

const token=()=>localStorage.getItem("kleo_token")||localStorage.getItem("token")||"";
const headers=(json=false)=>({...(json?{"Content-Type":"application/json"}:{}),...(token()?{Authorization:`Bearer ${token()}`}:{})});
async function readJson<T>(r:Response):Promise<T>{const text=await r.text();const data=text?JSON.parse(text):{};if(!r.ok)throw new Error(data?.error||data?.message||`HTTP ${r.status}`);return data as T}
const pct=(v:number|null|undefined)=>`${Math.round(Number(v||0)*100)}%`;

export default function ProductTaxonomyReviewPage(){
 const[groups,setGroups]=useState<Group[]>([]),[categories,setCategories]=useState<Category[]>([]),[items,setItems]=useState<ReviewItem[]>([]);
 const[summary,setSummary]=useState<Summary|null>(null),[mode,setMode]=useState<Mode>("review"),[search,setSearch]=useState(""),[threshold,setThreshold]=useState(.6);
 const[loading,setLoading]=useState(false),[savingId,setSavingId]=useState<string|null>(null),[rebuilding,setRebuilding]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const[draft,setDraft]=useState<Record<string,{group:string;category:string;note:string}>>({});

 const loadRefs=useCallback(async()=>{const[g,c]=await Promise.all([fetch(withBase("product-groups"),{headers:headers()}),fetch(withBase("product-categories"),{headers:headers()})]);setGroups(await readJson<Group[]>(g));setCategories(await readJson<Category[]>(c))},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const qs=new URLSearchParams({mode,threshold:String(threshold),limit:"500"});if(search.trim())qs.set("search",search.trim());const[list,stats]=await Promise.all([fetch(withBase(`products/taxonomy/review?${qs}`),{headers:headers()}),fetch(withBase(`products/taxonomy/review/summary?threshold=${threshold}`),{headers:headers()})]);const ld=await readJson<{items:ReviewItem[]}>(list);const sd=await readJson<Summary>(stats);setItems(ld.items||[]);setSummary(sd)}catch(e:any){setError(e?.message||"A felülvizsgálati lista nem tölthető be.")}finally{setLoading(false)}},[mode,search,threshold]);
 useEffect(()=>{void loadRefs().catch((e:any)=>setError(e?.message||"A terméktörzs referenciaadatai nem tölthetők be."))},[loadRefs]);
 useEffect(()=>{const t=setTimeout(()=>void load(),search?350:0);return()=>clearTimeout(t)},[load,search]);

 const categoriesFor=(gid:string)=>categories.filter(c=>String(c.product_group_id||"")===String(gid));
 const edit=(x:ReviewItem)=>draft[x.id]||{group:String(x.product_group_id||""),category:String(x.product_category_id||""),note:""};
 const patchDraft=(id:string,p:Partial<{group:string;category:string;note:string}>)=>setDraft(d=>({...d,[id]:{...edit(items.find(x=>x.id===id)!),...d[id],...p}}));
 const save=async(x:ReviewItem)=>{const d=edit(x);if(!d.group||!d.category)return setError("Válasszon termékcsoportot és kategóriát.");setSavingId(x.id);setError("");setSuccess("");try{const r=await fetch(withBase(`products/taxonomy/review/${x.id}`),{method:"PATCH",headers:headers(true),body:JSON.stringify({product_group_id:d.group,product_category_id:d.category,note:d.note||null})});await readJson(r);setDraft(v=>{const n={...v};delete n[x.id];return n});setSuccess(`${x.name}: kézi besorolás elmentve.`);await load()}catch(e:any){setError(e?.message||"A kézi besorolás mentése nem sikerült.")}finally{setSavingId(null)}};
 const rebuild=async()=>{setRebuilding(true);setError("");setSuccess("");try{const r=await fetch(withBase("products/taxonomy/rebuild"),{method:"POST",headers:headers(true),body:JSON.stringify({force:false})});const d=await readJson<any>(r);setSuccess(`Automatikus újrabesorolás kész${d?.updated!=null?`: ${d.updated} termék frissült.`:"."}`);await load()}catch(e:any){setError(e?.message||"Az újrabesorolás nem sikerült.")}finally{setRebuilding(false)}};
 const reviewCount=useMemo(()=>summary?Math.max(summary.unclassified,summary.low_confidence,summary.fallback):items.length,[summary,items.length]);

 return <div className="taxonomy-review-page">
  <header className="taxonomy-review-hero"><div><span className="taxonomy-eyebrow">KÉSZLETGAZDÁLKODÁS / TERMÉKTÖRZS</span><h1>Termékbesorolás ellenőrzése</h1><p>Az automatikusan bizonytalan, „Egyéb” vagy hiányos besorolású termékek kontrollált felülvizsgálata. A kézi döntés auditálva, 100% bizonyosságú besorolásként kerül mentésre.</p></div><div className="taxonomy-hero-actions"><a href="/masterdata/products">← Termékek</a><button onClick={rebuild} disabled={rebuilding}>{rebuilding?"Újrabesorolás…":"Automatikus újrabesorolás"}</button></div></header>
  {error&&<div className="taxonomy-alert error">{error}</div>}{success&&<div className="taxonomy-alert success">{success}</div>}
  <section className="taxonomy-kpis"><div><strong>{summary?.total??"—"}</strong><span>Összes termék</span></div><div><strong>{reviewCount}</strong><span>Ellenőrzendő</span></div><div><strong>{summary?.low_confidence??"—"}</strong><span>Alacsony bizonyosság</span></div><div><strong>{summary?.fallback??"—"}</strong><span>„Egyéb” fallback</span></div><div><strong>{summary?.unclassified??"—"}</strong><span>Nincs besorolva</span></div><div><strong>{summary?.manual??"—"}</strong><span>Kézzel ellenőrzött</span></div></section>
  <section className="taxonomy-controls"><div className="taxonomy-modes">{([['review','Ellenőrzendő'],['low','Bizonytalan'],['fallback','Egyéb'],['unclassified','Besorolatlan'],['all','Összes']] as [Mode,string][]).map(([k,l])=><button key={k} className={mode===k?"active":""} onClick={()=>setMode(k)}>{l}</button>)}</div><input placeholder="Keresés név, cikkszám, márka vagy eredeti Altegio kategória alapján…" value={search} onChange={e=>setSearch(e.target.value)}/><label>Határérték <select value={threshold} onChange={e=>setThreshold(Number(e.target.value))}><option value={.5}>50%</option><option value={.6}>60%</option><option value={.7}>70%</option><option value={.8}>80%</option></select></label></section>
  <section className="taxonomy-card"><div className="taxonomy-card-title"><div><h2>Felülvizsgálati sor</h2><p>{loading?"Betöltés…":`${items.length} termék látható`}{summary?.taxonomy_version?` · taxonómia: ${summary.taxonomy_version}`:""}</p></div></div>
   <div className="taxonomy-table-wrap"><table><thead><tr><th>Termék / forrás</th><th>Miért ellenőrzendő?</th><th>Jelenlegi besorolás</th><th>Bizonyosság</th><th>Új csoport</th><th>Új kategória</th><th>Megjegyzés</th><th></th></tr></thead><tbody>{items.map(x=>{const d=edit(x),cats=categoriesFor(d.group);return <tr key={x.id}><td><b>{x.name}</b><small>{[x.brand,x.line_name,x.internal_code].filter(Boolean).join(" · ")||"—"}</small><em>Eredeti: {x.source_category_name||"—"}</em></td><td><div className="taxonomy-reasons">{x.is_unclassified&&<span className="danger">Nincs besorolva</span>}{x.is_low_confidence&&<span className="warning">Bizonytalan</span>}{x.is_fallback&&<span>Fallback</span>}{x.taxonomy_source==="manual"&&<span className="ok">Kézi</span>}</div></td><td>{x.product_group_name||"—"}<small>{x.product_category_name||"—"}</small></td><td><span className={`taxonomy-confidence ${Number(x.taxonomy_confidence||0)<threshold?"low":"high"}`}>{pct(x.taxonomy_confidence)}</span></td><td><select value={d.group} onChange={e=>patchDraft(x.id,{group:e.target.value,category:""})}><option value="">Válasszon…</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></td><td><select value={d.category} onChange={e=>patchDraft(x.id,{category:e.target.value})} disabled={!d.group}><option value="">Válasszon…</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td><input value={d.note} onChange={e=>patchDraft(x.id,{note:e.target.value})} placeholder="Miért módosult?"/></td><td><button className="taxonomy-save" onClick={()=>save(x)} disabled={savingId===x.id||!d.group||!d.category}>{savingId===x.id?"Mentés…":"Jóváhagyás"}</button></td></tr>})}{!loading&&!items.length&&<tr><td colSpan={8} className="taxonomy-empty">Nincs a szűrésnek megfelelő ellenőrzendő termék.</td></tr>}</tbody></table></div>
  </section>
 </div>
}
