import React,{useCallback,useEffect,useMemo,useRef,useState}from"react";
import{CalendarDays,CheckCircle2,Clock3,MapPin,Mic,MicOff,RefreshCw,Scissors,ShieldCheck,Sparkles,Tag,UserRound,Volume2,X}from"lucide-react";
import api from"../api/api";
import"./CustomerBookingPage.css";
import"./PublicBookingPage.css";
import"./PublicBookingRecommendations.css";

type Location={id:string;name:string};
type Service={id:string;name:string;duration_minutes:number;price:number|string;category_name?:string};
type Employee={id:string;full_name:string;photo_url?:string|null};
type Slot={employee_id:string;employee_name:string;start:string;end:string};
type VoicePeriod="morning"|"afternoon"|"evening"|null;
type VoiceResponse={ok:boolean;intent:{intent:"book"|"waitlist"|"cancel";location_id:string|null;service_ids:string[];employee_id:string|null;date:string|null;time:string|null;preferred_period:VoicePeriod};missing_fields:string[];recognized:boolean;ai_used:boolean;requires_confirmation:boolean;spoken_follow_up:string};
type Recommendation={type:"service"|"promotion";service_id:string|null;title:string;message:string;name?:string;price?:number;duration_minutes?:number;ai_generated:boolean};

type Guest={full_name:string;phone:string;email:string;marketing_consent:boolean};
const pad=(n:number)=>String(n).padStart(2,"0");
const localDate=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const money=(v:unknown)=>`${Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:0})} Ft`;
const time=(v:string)=>new Date(v).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"});
const minuteOf=(v:string)=>{const d=new Date(v);return d.getHours()*60+d.getMinutes()};
function speak(text:string){try{if(!text||typeof window==="undefined"||!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="hu-HU";u.rate=.96;window.speechSynthesis.speak(u)}catch{}}

export default function PublicBookingPage(){
 const[locations,setLocations]=useState<Location[]>([]),[locationId,setLocationId]=useState("");
 const[services,setServices]=useState<Service[]>([]),[selectedServiceIds,setSelectedServiceIds]=useState<string[]>([]);
 const[employees,setEmployees]=useState<Employee[]>([]),[employeeId,setEmployeeId]=useState("");
 const[selectedDate,setSelectedDate]=useState(localDate()),[slots,setSlots]=useState<Slot[]>([]),[selectedSlot,setSelectedSlot]=useState<Slot|null>(null);
 const[settings,setSettings]=useState<any>(null),[loading,setLoading]=useState(false),[booking,setBooking]=useState(false),[waiting,setWaiting]=useState(false);
 const[error,setError]=useState(""),[notice,setNotice]=useState(""),[confirmOpen,setConfirmOpen]=useState(false);
 const[guest,setGuest]=useState<Guest>({full_name:"",phone:"",email:"",marketing_consent:false});
 const[listening,setListening]=useState(false),[voiceLoading,setVoiceLoading]=useState(false),[voiceTranscript,setVoiceTranscript]=useState(""),[voiceResult,setVoiceResult]=useState<VoiceResponse|null>(null),[voiceUsed,setVoiceUsed]=useState(false);
 const[recommendations,setRecommendations]=useState<Recommendation[]>([]),[recommendationsLoading,setRecommendationsLoading]=useState(false),[recommendationsAi,setRecommendationsAi]=useState(false);
 const recognitionRef=useRef<any>(null);
 const contactValid=Boolean(guest.full_name.trim()&&(guest.phone.trim()||guest.email.trim()));

 useEffect(()=>{api.get("/public/marketing/booking/catalog").then(r=>setLocations((r.data?.locations||[]).map((x:any)=>({id:String(x.id),name:x.name})))).catch(()=>setError("A szalonok jelenleg nem tölthetők be."))},[]);
 useEffect(()=>{setSelectedSlot(null);setConfirmOpen(false);setSlots([]);if(!locationId){setServices([]);setEmployees([]);setSettings(null);return}let active=true;setLoading(true);setError("");api.get("/public/marketing/booking/catalog",{params:{location_id:locationId}}).then(r=>{if(!active)return;const ss=(r.data?.services||[]).map((x:any)=>({...x,id:String(x.id)})),ee=(r.data?.employees||[]).map((x:any)=>({...x,id:String(x.id)}));setServices(ss);setEmployees(ee);setSettings(r.data?.settings||null);const okS=new Set(ss.map((x:Service)=>x.id));setSelectedServiceIds(ids=>ids.filter(id=>okS.has(id)));const okE=new Set(ee.map((x:Employee)=>x.id));setEmployeeId(id=>okE.has(id)?id:"")}).catch((e:any)=>active&&setError(e?.response?.data?.error||"A foglalási katalógus nem tölthető be.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[locationId]);

 const loadAvailability=useCallback(async()=>{setSelectedSlot(null);setConfirmOpen(false);setSlots([]);if(!locationId||!selectedDate||!selectedServiceIds.length)return;setLoading(true);setError("");try{const r=await api.get("/public/marketing/booking/availability",{params:{location_id:locationId,date:selectedDate,service_ids:selectedServiceIds.join(","),employee_id:employeeId||undefined}});setSlots((r.data?.slots||[]).map((x:any)=>({...x,employee_id:String(x.employee_id)})))}catch(e:any){setError(e?.response?.data?.error||"A szabad időpontok nem tölthetők be.")}finally{setLoading(false)}},[locationId,selectedDate,selectedServiceIds,employeeId]);
 useEffect(()=>{void loadAvailability()},[loadAvailability]);
 useEffect(()=>{setRecommendations([]);setRecommendationsAi(false);if(!locationId||!selectedServiceIds.length)return;let active=true;const timer=window.setTimeout(()=>{setRecommendationsLoading(true);api.get("/public/marketing/booking/recommendations",{params:{location_id:locationId,service_ids:selectedServiceIds.join(",")}}).then(r=>{if(!active)return;setRecommendations(Array.isArray(r.data?.recommendations)?r.data.recommendations:[]);setRecommendationsAi(Boolean(r.data?.ai_used))}).catch(()=>active&&setRecommendations([])).finally(()=>active&&setRecommendationsLoading(false))},350);return()=>{active=false;window.clearTimeout(timer)}},[locationId,selectedServiceIds]);
 const selectedServices=useMemo(()=>services.filter(s=>selectedServiceIds.includes(s.id)),[services,selectedServiceIds]);
 const totalDuration=selectedServices.reduce((sum,s)=>sum+Number(s.duration_minutes||0),0),grossTotal=selectedServices.reduce((sum,s)=>sum+Number(s.price||0),0),discount=Number(settings?.online_discount_percent||0),estimatedTotal=Math.max(0,grossTotal*(1-discount/100));
 const availableEmployeeIds=useMemo(()=>new Set(slots.map(s=>s.employee_id)),[slots]);
 const visibleEmployees=selectedServiceIds.length&&!loading?employees.filter(e=>availableEmployeeIds.has(e.id)||e.id===employeeId):employees;

 useEffect(()=>{if(!voiceUsed||!voiceResult||!slots.length||selectedSlot)return;const pref=voiceResult.intent;let candidates=employeeId?slots.filter(s=>s.employee_id===employeeId):slots;if(!candidates.length)candidates=slots;if(pref.time){const[h,m]=pref.time.split(":").map(Number),target=h*60+m;candidates=[...candidates].sort((a,b)=>Math.abs(minuteOf(a.start)-target)-Math.abs(minuteOf(b.start)-target))}else if(pref.preferred_period){const f=candidates.filter(s=>{const m=minuteOf(s.start);return pref.preferred_period==="morning"?m<720:pref.preferred_period==="afternoon"?m>=720&&m<1020:m>=1020});if(f.length)candidates=f}if(candidates[0])setSelectedSlot(candidates[0])},[slots,voiceUsed,voiceResult,employeeId,selectedSlot]);

 const interpretVoice=async(transcript:string)=>{setVoiceLoading(true);setError("");setNotice("");try{const r=await api.post("/public/marketing/booking/voice/interpret",{transcript}),v=r.data as VoiceResponse;setVoiceResult(v);setVoiceUsed(true);if(v.intent.intent==="cancel"){const msg="A hangfelismerés lemondási szándékot érzékelt. Biztonsági okból meglévő foglalást hang alapján nem törlünk.";setNotice(msg);speak(v.spoken_follow_up||msg);return}if(v.intent.location_id)setLocationId(v.intent.location_id);if(v.intent.service_ids?.length)setSelectedServiceIds(v.intent.service_ids);if(v.intent.employee_id)setEmployeeId(v.intent.employee_id);if(v.intent.date)setSelectedDate(v.intent.date);setSelectedSlot(null);setConfirmOpen(false);setNotice(v.ai_used?"A kérés AI-val értelmezve. Ellenőrizd a kiválasztott adatokat.":"A hangos kérés értelmezve. Ellenőrizd a kiválasztott adatokat.");speak(v.spoken_follow_up)}catch(e:any){const msg=e?.response?.data?.error||"A hangos foglalási kérés nem értelmezhető.";setError(msg);speak(msg)}finally{setVoiceLoading(false)}};
 const startListening=()=>{const Ctor=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Ctor){setError("Ez a böngésző nem támogatja a beépített beszédfelismerést. Chrome vagy Edge használata javasolt.");return}try{recognitionRef.current?.abort?.()}catch{}const r=new Ctor();r.lang="hu-HU";r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>{setListening(true);setError("");setNotice("Mondd el egy mondatban a szalont, szolgáltatást, napot és ha szeretnéd a szakembert vagy időpontot.")};r.onend=()=>setListening(false);r.onerror=(e:any)=>{setListening(false);setError(e?.error==="not-allowed"?"A mikrofon használata nincs engedélyezve.":"A beszédfelismerés megszakadt. Próbáld újra.")};r.onresult=(e:any)=>{const text=String(e?.results?.[0]?.[0]?.transcript||"").trim();setVoiceTranscript(text);if(text)void interpretVoice(text)};recognitionRef.current=r;r.start()};
 const stopListening=()=>{try{recognitionRef.current?.stop?.()}catch{}setListening(false)};
 const chooseLocation=(id:string)=>{setVoiceUsed(false);setVoiceResult(null);setLocationId(id);setSelectedServiceIds([]);setEmployeeId("");setSelectedSlot(null)};
 const toggleService=(id:string)=>{setVoiceUsed(false);setVoiceResult(null);setSelectedServiceIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);setSelectedSlot(null)};
 const chooseEmployee=(id:string)=>{setVoiceUsed(false);setVoiceResult(null);setEmployeeId(id===employeeId?"":id);setSelectedSlot(null)};
 const addRecommendation=(item:Recommendation)=>{if(!item.service_id||selectedServiceIds.includes(item.service_id))return;setSelectedServiceIds(ids=>[...ids,item.service_id as string]);setSelectedSlot(null);setNotice(`${item.name||"Az ajánlott szolgáltatás"} hozzáadva. Az időpontokat az új teljes időtartammal frissítjük.`)};

 const book=async()=>{if(!confirmOpen||!selectedSlot||!locationId||!selectedServiceIds.length||!contactValid)return;setBooking(true);setError("");setNotice("");try{const r=await api.post("/public/marketing/booking/book",{location_id:locationId,employee_id:selectedSlot.employee_id,service_ids:selectedServiceIds,client_name:guest.full_name.trim(),phone:guest.phone.trim(),email:guest.email.trim(),marketing_consent:guest.marketing_consent,start_time:selectedSlot.start,booking_source:voiceUsed?"voice":"online"});const state=r.data?.confirmation_required?"A foglalás rögzítve, a szalon visszaigazolása szükséges.":"A foglalás sikeresen rögzítve és megerősítve.";setNotice(state);speak(state);setSelectedSlot(null);setConfirmOpen(false);setVoiceUsed(false);setVoiceResult(null);await loadAvailability()}catch(e:any){setError(e?.response?.data?.error||e?.message||"A foglalás nem sikerült.")}finally{setBooking(false)}};
 const joinWaitlist=async()=>{if(!locationId||!selectedServiceIds.length||!contactValid)return;setWaiting(true);setError("");try{const from=new Date(`${selectedDate}T00:00:00`),to=new Date(`${selectedDate}T23:59:59`);await api.post("/public/marketing/booking/waitlist",{location_id:locationId,client_name:guest.full_name.trim(),phone:guest.phone.trim(),email:guest.email.trim(),service_ids:selectedServiceIds,employee_id:employeeId||null,preferred_from:from.toISOString(),preferred_to:to.toISOString(),booking_source:voiceUsed?"voice":"online"});const msg="Felkerültél a várólistára erre a napra.";setNotice(msg);speak(msg)}catch(e:any){setError(e?.response?.data?.error||"A várólistára jelentkezés nem sikerült.")}finally{setWaiting(false)}};

 return <main className="customer-booking public-booking">
  <nav className="pb-brand"><a href="/booking" className="pb-logo"><b>KLEOPÁTRA</b><span>SZÉPSÉGSZALONOK</span></a><div><ShieldCheck/><span>Biztonságos online foglalás</span></div><a href="/login" className="pb-login">Belépés</a></nav>
  <header className="cb-hero pb-hero"><div><span>FOGLALÁS 3.0 · VOICE BOOKING</span><h1>Foglalj online vagy mondd el, mit szeretnél</h1><p>Válassz szalont, több szolgáltatást és időpontot, vagy használd a mikrofont. A rendszer csak a végső összegzés külön megerősítése után ment.</p></div><div className="cb-voice-actions"><button className={listening?"listening":""} onClick={listening?stopListening:startListening} disabled={voiceLoading}>{listening?<MicOff/>:<Mic/>}<span>{voiceLoading?"Értelmezés…":listening?"Leállítás":"Hangos foglalás"}</span></button>{loading&&<RefreshCw className="spin"/>}</div></header>
  {voiceTranscript&&<div className="cb-voice-transcript"><Mic/><div><b>Ezt értettem:</b><span>„{voiceTranscript}”</span></div>{voiceResult?.spoken_follow_up&&<button onClick={()=>speak(voiceResult.spoken_follow_up)} title="Visszakérdezés felolvasása"><Volume2/></button>}</div>}
  {error&&<div className="cb-message is-error">{error}</div>}{notice&&<div className="cb-message is-success"><CheckCircle2/>{notice}</div>}

  <section className="pb-guest-card"><header><span>1. KAPCSOLATTARTÁS</span><h2>Foglalási adatok</h2><p>Legalább telefonszámot vagy e-mail címet adj meg, hogy a szalon elérhessen.</p></header><div className="pb-guest-grid"><label><span>Név *</span><input value={guest.full_name} onChange={e=>setGuest(g=>({...g,full_name:e.target.value}))} autoComplete="name" placeholder="Teljes név"/></label><label><span>Telefonszám</span><input value={guest.phone} onChange={e=>setGuest(g=>({...g,phone:e.target.value}))} autoComplete="tel" placeholder="+36 ..."/></label><label><span>E-mail</span><input type="email" value={guest.email} onChange={e=>setGuest(g=>({...g,email:e.target.value}))} autoComplete="email" placeholder="nev@email.hu"/></label><label className="pb-consent"><input type="checkbox" checked={guest.marketing_consent} onChange={e=>setGuest(g=>({...g,marketing_consent:e.target.checked}))}/><span>Hozzájárulok marketing célú megkeresésekhez.</span></label></div></section>

  <section className="cb-layout"><aside className="cb-filters"><label><span>2. Szalon</span><select value={locationId} onChange={e=>chooseLocation(e.target.value)}><option value="">Válassz szalont</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><div className="cb-filter-group"><header><div><span>3. Szolgáltatások</span><small>Több is választható</small></div>{selectedServiceIds.length>0&&<button onClick={()=>setSelectedServiceIds([])}>Mind törlése</button>}</header><div className="cb-choice-scroll">{services.map(s=><button key={s.id} className={selectedServiceIds.includes(s.id)?"active":""} onClick={()=>toggleService(s.id)}><Scissors/><div><b>{s.name}</b><small>{s.duration_minutes} perc · {money(s.price)}</small></div></button>)}</div></div><div className="cb-filter-group"><header><div><span>4. Szakember</span><small>Opcionális</small></div>{employeeId&&<button onClick={()=>setEmployeeId("")}>Törlés</button>}</header><div className="cb-choice-scroll">{visibleEmployees.map(e=><button key={e.id} className={employeeId===e.id?"active":""} onClick={()=>chooseEmployee(e.id)}><UserRound/><div><b>{e.full_name}</b><small>{selectedServiceIds.length?"A kiválasztott szolgáltatásokhoz elérhető":"Válassz előbb szolgáltatást"}</small></div></button>)}</div></div></aside>
   <section className="pb-time-panel"><header><div><span>5. DÁTUM ÉS IDŐ</span><h2>Szabad időpontok</h2></div><Clock3/></header><div className="pb-date-row"><label><CalendarDays/><div><span>Nap</span><input type="date" min={localDate()} value={selectedDate} onChange={e=>{setVoiceUsed(false);setSelectedDate(e.target.value);setSelectedSlot(null)}}/></div></label><div className="pb-context"><MapPin/><span>{locations.find(x=>x.id===locationId)?.name||"Válassz szalont"}</span>{selectedServices.length>0&&<><Scissors/><span>{selectedServices.length} szolgáltatás · {totalDuration} perc</span></>}</div></div>
    {selectedServiceIds.length>0&&(recommendationsLoading||recommendations.length>0)&&<section className="pb-recommendations"><header><div><Sparkles/><span><b>Személyre szabott ajánlatok</b><small>{recommendationsAi?"AI-val megfogalmazva · ellenőrzött katalógusból":"Aktuális katalógus és akciók alapján"}</small></span></div></header>{recommendationsLoading&&!recommendations.length?<div className="pb-recommend-loading"><RefreshCw className="spin"/> Ajánlatok keresése…</div>:<div className="pb-recommend-list">{recommendations.map((r,i)=><article key={`${r.type}-${r.service_id||i}`} className={r.type}><span className="pb-recommend-icon">{r.type==="promotion"?<Tag/>:<Sparkles/>}</span><div><small>{r.title}</small><b>{r.name||"Aktuális kedvezmény"}</b><p>{r.message}</p>{r.type==="service"&&<em>{r.duration_minutes} perc · {money(r.price)}</em>}</div>{r.type==="service"&&r.service_id&&<button onClick={()=>addRecommendation(r)}>Hozzáadom</button>}</article>)}</div>}</section>}
    {!locationId?<div className="cb-empty">Először válassz szalont.</div>:!selectedServiceIds.length?<div className="cb-empty">Válassz egy vagy több szolgáltatást.</div>:slots.length===0&&!loading?<div className="cb-empty"><span>Erre a napra nincs szabad időpont a kiválasztott feltételekkel.</span><button className="cb-waitlist" onClick={joinWaitlist} disabled={waiting||!contactValid}>{waiting?"Mentés…":"Várólistára kérem"}</button>{!contactValid&&<small>Add meg előbb a neved és legalább egy elérhetőséged.</small>}</div>:<div className="cb-slot-groups">{Array.from(new Map(slots.map(s=>[s.employee_id,s.employee_name])).entries()).map(([id,name])=><article key={id}><header><div><b>{name}</b><small>{totalDuration} perc összesen</small></div>{!employeeId&&<button onClick={()=>setEmployeeId(id)}>Szakember kiválasztása</button>}</header><div>{slots.filter(s=>s.employee_id===id).map(slot=><button key={`${slot.employee_id}-${slot.start}`} className={selectedSlot?.start===slot.start&&selectedSlot.employee_id===slot.employee_id?"active":""} onClick={()=>{setSelectedSlot(slot);setConfirmOpen(false)}}>{time(slot.start)}</button>)}</div></article>)}</div>}
   </section></section>

  {selectedSlot&&<div className="cb-confirm"><div><span>KIVÁLASZTOTT IDŐPONT</span><b>{selectedServices.map(s=>s.name).join(" + ")}</b><p>{selectedSlot.employee_name} · {new Date(selectedSlot.start).toLocaleString("hu-HU",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"})} · kb. {money(estimatedTotal)}</p></div><button onClick={()=>{if(!contactValid){setError("Add meg a neved és legalább telefonszámot vagy e-mail címet.");return}setConfirmOpen(true)}}>Összegzés és megerősítés</button></div>}
  {confirmOpen&&selectedSlot&&<div className="cb-confirm-overlay" role="dialog" aria-modal="true"><section className="cb-confirm-dialog"><header><div><span>VÉGSŐ ELLENŐRZÉS</span><h2>Foglalási összegzés</h2></div><button onClick={()=>setConfirmOpen(false)} aria-label="Bezárás"><X/></button></header><div className="cb-summary-grid"><div><small>Vendég</small><b>{guest.full_name}</b></div><div><small>Kapcsolat</small><b>{guest.phone||guest.email}</b></div><div><small>Szalon</small><b>{locations.find(x=>x.id===locationId)?.name}</b></div><div><small>Dátum és idő</small><b>{new Date(selectedSlot.start).toLocaleString("hu-HU",{year:"numeric",month:"long",day:"numeric",weekday:"long",hour:"2-digit",minute:"2-digit"})}</b></div><div><small>Szakember</small><b>{selectedSlot.employee_name}</b></div><div><small>Időtartam</small><b>{totalDuration} perc</b></div></div><div className="cb-summary-services">{selectedServices.map(s=><div key={s.id}><span>{s.name}</span><b>{money(s.price)}</b></div>)}</div><div className="cb-summary-total"><div><small>Listaár</small><span>{money(grossTotal)}</span></div>{discount>0&&<div><small>Online kedvezmény</small><span>-{discount}%</span></div>}<div className="total"><small>Becsült fizetendő</small><b>{money(estimatedTotal)}</b></div></div>{voiceUsed&&<div className="cb-voice-safe"><Mic/><span>Hangalapú kérésből készült. A foglalás csak az alábbi gomb megnyomásával kerül mentésre.</span></div>}<button className="cb-final-book" onClick={book} disabled={booking||!contactValid}>{booking?"Foglalás mentése…":"Megerősítem és lefoglalom"}</button></section></div>}
 </main>
}
