import React,{useEffect,useMemo,useState}from'react';
import{Link,useSearchParams}from'react-router-dom';
import api from'../api';

type Receipt={id:string;location_id:string|null;source_type:'WORK_ORDER'|'RETAIL_SALE';source_id:string;source_number:string|null;receipt_number:string;document_type:'SALE'|'VOID';status:'ISSUED'|'VOIDED';original_receipt_number?:string|null;issued_at:string;currency:string;gross_total:number;customer_name?:string|null;customer_email?:string|null;email_sent_at?:string|null;voided_at?:string|null;void_reason?:string|null};
const HUF=new Intl.NumberFormat('hu-HU',{maximumFractionDigits:0});
const money=(v:any,c='HUF')=>c==='HUF'?`${HUF.format(Number(v||0))} Ft`:new Intl.NumberFormat('hu-HU',{style:'currency',currency:c}).format(Number(v||0));
const msg=(e:any,f:string)=>e?.response?.data?.message||e?.response?.data?.error||f;

export default function ReceiptDocumentsPage(){
 const[params]=useSearchParams();
 const[rows,setRows]=useState<Receipt[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[sourceType,setSourceType]=useState<'WORK_ORDER'|'RETAIL_SALE'>((params.get('source_type') as any)||'WORK_ORDER');
 const[sourceId,setSourceId]=useState(params.get('source_id')||''),[email,setEmail]=useState(params.get('email')||''),[sendEmail,setSendEmail]=useState(true);
 const active=useMemo(()=>rows.filter(r=>r.document_type==='SALE'),[rows]);
 async function load(){try{const r=await api.get('/api/vir/receipt-compliance/documents');setRows(r.data?.rows||[])}catch(e:any){setError(msg(e,'A nyugták nem tölthetők be.'))}}
 useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}finally{setBusy(false)}}
 async function issue(){if(!sourceId.trim()){setError('A munkalap vagy termékeladás azonosítója kötelező.');return}await run(async()=>{try{const r=await api.post('/api/vir/receipt-compliance/documents/issue',{source_type:sourceType,source_id:sourceId.trim(),customer_email:email.trim()||null,send_email:sendEmail});setNotice(`${r.data?.receipt?.receipt_number||'A nyugta'} elkészült${r.data?.delivery?.sent?' és e-mailben elküldve':''}.`);setSourceId('');await load()}catch(e:any){setError(msg(e,'A nyugta nem állítható ki.'))}})}
 async function pdf(row:Receipt){await run(async()=>{try{const r=await api.get(`/api/vir/receipt-compliance/documents/${row.id}/pdf`,{responseType:'blob'});const url=URL.createObjectURL(new Blob([r.data],{type:'application/pdf'}));window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e:any){setError(msg(e,'A PDF nem nyitható meg.'))}})}
 async function send(row:Receipt){const to=window.prompt('Melyik e-mail-címre küldjük a nyugtát?',row.customer_email||'');if(to===null)return;await run(async()=>{try{const r=await api.post(`/api/vir/receipt-compliance/documents/${row.id}/send`,{email:to});setNotice(r.data?.delivery?.sent?'A nyugta e-mailben elküldve.':'A küldés naplózva, de az SMTP nincs élesítve.');await load()}catch(e:any){setError(msg(e,'Az e-mail küldése sikertelen.'))}})}
 async function voidReceipt(row:Receipt){const reason=window.prompt('Sztornó indoka:','');if(reason===null)return;if(reason.trim().length<3){setError('A sztornó indoka legalább 3 karakter.');return}const reverse=row.source_type==='WORK_ORDER'?window.confirm('A kapcsolt munkalap pénzügyi mozgásait is ellenkönyveljem?\n\nOK = igen, teljes pénzügyi sztornó\nMégse = csak a nyugta érvénytelenítő bizonylata készül el'):false;await run(async()=>{try{const r=await api.post(`/api/vir/receipt-compliance/documents/${row.id}/void`,{reason:reason.trim(),reverse_financial:reverse,send_email:Boolean(row.customer_email)});setNotice(`${r.data?.void_receipt?.receipt_number||'Az érvénytelenítő nyugta'} elkészült${r.data?.financial_reversed?' · pénzügy ellenkönyvelve':''}.`);await load()}catch(e:any){setError(msg(e,'A sztornó sikertelen.'))}})}
 return <main style={S.page}>
  <header style={S.head}><div><div style={S.eyebrow}>PÉNZÜGYEK · NYUGTA</div><h1 style={{margin:'4px 0'}}>Számítógépes nyugták</h1><p style={S.muted}>Elektronikus PDF-példány, ügyfélnek küldés, sértetlenségi hash és érvénytelenítő/sztornó folyamat.</p></div><div style={S.actions}><Link style={S.secondary} to="/finance/receipt-compliance">NAV adatszolgáltatás</Link><Link style={S.secondary} to="/workorders">Munkalapok</Link></div></header>
  <div style={S.info}><b>Fontos:</b> ez számítógéppel előállított, elektronikus megjelenésű nyugta. A jogszabályi „e-nyugta” megnevezés az engedélyezett e-pénztárgéppel kiállított bizonylatra vonatkozik.</div>
  {error&&<div style={S.bad}>{error}</div>}{notice&&<div style={S.good}>{notice}</div>}
  <section style={S.card}><div><h2 style={S.h2}>Új nyugta kiállítása</h2><p style={S.muted}>Csak teljesen kifizetett, nem számlázott forrásból állítható ki. Ugyanahhoz a forráshoz a rendszer nem duplikál nyugtát.</p></div><div style={S.grid}>
   <label style={S.field}><span>Forrás</span><select style={S.input} value={sourceType} onChange={e=>setSourceType(e.target.value as any)}><option value="WORK_ORDER">Munkalap</option><option value="RETAIL_SALE">Termékeladás</option></select></label>
   <label style={S.field}><span>Forrás azonosító</span><input style={S.input} value={sourceId} onChange={e=>setSourceId(e.target.value)} placeholder="UUID / munkalap azonosító"/></label>
   <label style={S.field}><span>Ügyfél e-mail (opcionális)</span><input style={S.input} value={email} onChange={e=>setEmail(e.target.value)} placeholder="vendeg@example.hu"/></label>
   <label style={{...S.field,justifyContent:'flex-end'}}><span><input type="checkbox" checked={sendEmail} onChange={e=>setSendEmail(e.target.checked)}/> PDF elküldése kiállításkor</span></label>
  </div><button style={S.primary} disabled={busy} onClick={()=>void issue()}>Nyugta kiállítása</button></section>
  <section style={S.stats}>{[['Értékesítési nyugták',active.length],['Aktív',active.filter(x=>x.status==='ISSUED').length],['Sztornózott',active.filter(x=>x.status==='VOIDED').length],['E-mailben elküldve',rows.filter(x=>x.email_sent_at).length]].map(([a,b])=><div style={S.stat} key={String(a)}><small>{a}</small><b>{b}</b></div>)}</section>
  <section style={S.card}><div style={S.sectionHead}><div><h2 style={S.h2}>Nyugtanapló</h2><p style={S.muted}>Az eredeti és érvénytelenítő bizonylatok külön sorban maradnak meg; törlés nincs.</p></div><button style={S.secondaryBtn} disabled={busy} onClick={()=>void load()}>Frissítés</button></div><div style={{overflowX:'auto'}}><table style={S.table}><thead><tr><Th>Nyugtaszám</Th><Th>Kelt</Th><Th>Típus</Th><Th>Forrás</Th><Th>Vendég</Th><Th>Összeg</Th><Th>Státusz</Th><Th>Művelet</Th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><Td><b>{r.receipt_number}</b>{r.original_receipt_number&&<small style={S.sub}>Eredeti: {r.original_receipt_number}</small>}</Td><Td>{new Date(r.issued_at).toLocaleString('hu-HU')}</Td><Td>{r.document_type==='VOID'?'Érvénytelenítő':'Értékesítési'}</Td><Td>{r.source_type==='WORK_ORDER'?'Munkalap':'Termékeladás'}<small style={S.sub}>{r.source_number||r.source_id}</small></Td><Td>{r.customer_name||'—'}{r.customer_email&&<small style={S.sub}>{r.customer_email}</small>}</Td><Td><b>{money(r.gross_total,r.currency)}</b></Td><Td><span style={r.status==='ISSUED'?S.badgeGood:S.badgeVoid}>{r.status==='ISSUED'?'AKTÍV':'SZTORNÓZOTT'}</span>{r.email_sent_at&&<small style={S.sub}>e-mail ✓</small>}</Td><Td><div style={S.actions}><button style={S.small} onClick={()=>void pdf(r)}>PDF</button><button style={S.small} onClick={()=>void send(r)}>E-mail</button>{r.document_type==='SALE'&&r.status==='ISSUED'&&<button style={S.danger} onClick={()=>void voidReceipt(r)}>Sztornó</button>}</div></Td></tr>)}{!rows.length&&<tr><td colSpan={8} style={{padding:28,textAlign:'center',color:'#64748b'}}>Még nincs kiállított nyugta.</td></tr>}</tbody></table></div></section>
 </main>
}
function Th({children}:{children:React.ReactNode}){return <th style={S.th}>{children}</th>}function Td({children}:{children:React.ReactNode}){return <td style={S.td}>{children}</td>}
const S:any={page:{maxWidth:1580,margin:'0 auto',padding:'22px 28px 52px'},head:{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap'},eyebrow:{fontSize:12,fontWeight:900,letterSpacing:'.12em',color:'#6e56a3'},muted:{color:'#64748b',margin:'5px 0 0',lineHeight:1.5},actions:{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap'},secondary:{textDecoration:'none',border:'1px solid #d8d0e4',padding:'9px 12px',borderRadius:9,color:'#3b2458',fontWeight:800,background:'#fff'},info:{marginTop:16,padding:'12px 14px',borderRadius:10,background:'#eef6ff',border:'1px solid #bfdbfe',color:'#1e3a5f'},bad:{marginTop:12,padding:'11px 13px',background:'#fef2f2',border:'1px solid #fecaca',borderRadius:10,color:'#991b1b'},good:{marginTop:12,padding:'11px 13px',background:'#f0fdf4',border:'1px solid #bbf7d0',borderRadius:10,color:'#166534'},card:{marginTop:16,padding:18,border:'1px solid #e3dfe8',borderRadius:14,background:'#fff',boxShadow:'0 8px 25px rgba(59,36,88,.06)'},h2:{margin:'0 0 3px'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,margin:'15px 0'},field:{display:'flex',flexDirection:'column',gap:5,fontSize:12,fontWeight:800,color:'#475569'},input:{border:'1px solid #d7d0df',borderRadius:9,padding:'10px 11px',fontSize:14,background:'#fff'},primary:{border:0,borderRadius:9,padding:'10px 15px',background:'#6e56a3',color:'#fff',fontWeight:900,cursor:'pointer'},stats:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:16},stat:{padding:'14px 16px',border:'1px solid #e5e7eb',borderRadius:12,background:'#fafafa',display:'flex',flexDirection:'column',gap:5},sectionHead:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'},secondaryBtn:{border:'1px solid #d8d0e4',padding:'8px 11px',borderRadius:8,background:'#fff',fontWeight:800,color:'#3b2458'},table:{width:'100%',borderCollapse:'collapse',marginTop:14,minWidth:980},th:{textAlign:'left',fontSize:11,color:'#64748b',padding:'9px 8px',borderBottom:'1px solid #e5e7eb'},td:{padding:'10px 8px',borderBottom:'1px solid #f0edf3',fontSize:13,verticalAlign:'top'},sub:{display:'block',marginTop:3,color:'#64748b',fontSize:11,fontWeight:500},badgeGood:{display:'inline-block',padding:'4px 7px',borderRadius:999,background:'#dcfce7',color:'#166534',fontSize:10,fontWeight:900},badgeVoid:{display:'inline-block',padding:'4px 7px',borderRadius:999,background:'#fee2e2',color:'#991b1b',fontSize:10,fontWeight:900},small:{border:'1px solid #d8d0e4',background:'#fff',borderRadius:7,padding:'6px 8px',fontWeight:800,cursor:'pointer'},danger:{border:'1px solid #fecaca',background:'#fff1f2',color:'#9f1239',borderRadius:7,padding:'6px 8px',fontWeight:900,cursor:'pointer'}};
