import React,{useCallback,useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,DatabaseZap,PackageCheck,RefreshCw,ShieldAlert,Workflow}from'lucide-react';
import api from'../api';
import'./ReconciliationCenterPage.css';

type FinanceItem={work_order_id:string;work_order_number:string;location_id?:string|null;issues:string[];chain:Record<string,boolean|string>;amounts:{work_order:number;payments:number;invoice:number;accounting_debit:number}};
type FinanceResult={business_date:string;status:'ok'|'critical';counts:Record<string,number>;amount_summary:Record<string,number>;discrepancy_count:number;items:FinanceItem[];discrepancies:FinanceItem[];generated_at:string};
type StockItem={warehouse_id:string;warehouse_name:string;location_id?:string|null;location_name?:string|null;product_id:string;product_name:string;opening:number;receipts:number;usage_qty:number;sales:number;scrap:number;transfer_in:number;transfer_out:number;adjustments:number;expected_closing:number;observed_closing:number;difference:number;movement_count:number};
type StockResult={business_date:string;status:'ok'|'critical';item_count:number;discrepancy_count:number;total_abs_difference:number;items:StockItem[];discrepancies:StockItem[];generated_at:string};
type IntegrityStatus='ok'|'warning'|'critical';
type IntegrityChain={key:string;label:string;ok:number;total:number};
type IntegrityProcess={key:string;label:string;status:IntegrityStatus;entity_count:number;exception_count:number;chain:IntegrityChain[];details?:Record<string,unknown>};
type IntegrityException={process_key:string;entity_type:string;entity_id:string;step_key:string;severity:'warning'|'critical';code:string;title:string;detail:string;payload?:Record<string,unknown>};
type IntegrityResult={business_date:string;location_id?:string|null;status:IntegrityStatus;processes:IntegrityProcess[];exception_count:number;exceptions:IntegrityException[];generated_at:string};

const BASE='/api/transactions/notifications/reconciliation';
const money=(v:unknown)=>`${Math.round(Number(v||0)).toLocaleString('hu-HU')} Ft`;
const qty=(v:unknown)=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:3}).format(Number(v||0));
const budapestDate=(offsetDays=0)=>{const d=new Date(Date.now()+offsetDays*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
const issueName:Record<string,string>={booking_link_missing:'Foglaláskapcsolat hiányzik',settlement_missing:'Settlement hiányzik',payment_amount_mismatch:'Fizetési összeg eltér',financial_ledger_missing:'Pénzügyi ledger-kapcsolat hiányzik',cashier_link_missing:'Kasszakapcsolat hiányzik',invoice_not_issued:'Hivatalos számla nincs kiállítva',invoice_amount_mismatch:'Számlaösszeg eltér',nav_failed:'NAV adatszolgáltatás hibás',nav_not_completed:'NAV adatszolgáltatás nincs kész',accounting_not_reconciled:'Könyvelés nincs egyeztetve'};
const chainLabels:[string,string][]=[['booking_source_ok','Foglalás / forrás'],['work_orders','Lezárt munkalap'],['settlement_ok','Settlement'],['payment_ok','Rendezett fizetés'],['ledger_ok','Pénzügyi tranzakció'],['cashier_ok','Kassza'],['invoice_ok','Számla'],['nav_ok','NAV'],['accounting_ok','Könyvelés']];
const processName:Record<string,string>={finance:'Pénzügyi lánc',stock:'Készletintegritás',procurement:'Beszerzési lánc',system:'Rendszer-invariáns'};

export default function ReconciliationCenterPage(){
 const[date,setDate]=useState(budapestDate(-1)),[tab,setTab]=useState<'finance'|'stock'|'process'>('finance'),[finance,setFinance]=useState<FinanceResult|null>(null),[stock,setStock]=useState<StockResult|null>(null),[integrity,setIntegrity]=useState<IntegrityResult|null>(null),[loading,setLoading]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<any>(null);
 const locationId=localStorage.getItem('kleo_location_id')||'',locationName=localStorage.getItem('kleo_location_name')||'Összes engedélyezett telephely';
 const query=useMemo(()=>{const s=new URLSearchParams({date});if(locationId)s.set('location_id',locationId);return s.toString()},[date,locationId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const h=new URLSearchParams({days:'30'});if(locationId)h.set('location_id',locationId);const[f,s,p,hi]=await Promise.all([api.get(`${BASE}/finance?${query}`),api.get(`${BASE}/stock?${query}`),api.get(`${BASE}/process-integrity?${query}`),api.get(`${BASE}/history?${h}`)]);setFinance(f.data);setStock(s.data);setIntegrity(p.data);setHistory(hi.data)}catch(e:any){setError(e?.response?.data?.message||'Az üzleti integritási adatok nem tölthetők be.')}finally{setLoading(false)}},[query,locationId]);
 useEffect(()=>{void load()},[load]);
 async function run(){setRunning(true);setError('');try{await api.post(`${BASE}/run`,{date,location_id:locationId||null,scope:'all'});await load()}catch(e:any){setError(e?.response?.data?.message||'Az üzleti integritási ellenőrzés futtatása nem sikerült.')}finally{setRunning(false)}}
 const finBad=finance?.discrepancies||[],stockBad=stock?.discrepancies||[],integrityBad=integrity?.exceptions||[];
 return <div className="rec-page">
  <header className="rec-hero"><div><span>PÉNZÜGYEK · ÜZLETI INTEGRITÁS</span><h1><DatabaseZap/> Pénzügyi egyeztető központ</h1><p>{locationName} · napi lánckontroll, készletegyeztetés és end-to-end üzleti folyamatfelügyelet.</p></div><div className="rec-actions"><label>Üzleti nap<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="ghost" onClick={load} disabled={loading}><RefreshCw size={16}/>{loading?'Frissítés…':'Frissítés'}</button><button className="primary" onClick={run} disabled={running}><ShieldAlert size={16}/>{running?'Ellenőrzés…':'Teljes kontroll futtatása'}</button></div></header>
  {error&&<div className="rec-error"><AlertTriangle size={18}/>{error}</div>}
  <nav className="rec-tabs"><button className={tab==='finance'?'active':''} onClick={()=>setTab('finance')}>Pénzügyi lánc</button><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>Automatikus stock reconciliation</button><button className={tab==='process'?'active':''} onClick={()=>setTab('process')}>Folyamatintegritás</button></nav>

  {tab==='finance'&&finance&&<>
   <section className={`rec-status ${finance.status}`}><div>{finance.status==='ok'?<CheckCircle2/>:<ShieldAlert/>}<div><small>NAPI PÉNZÜGYI KONTROLL</small><b>{finance.status==='ok'?'MINDEN LÁNCSZEM EGYEZIK':'PIROS ELTÉRÉS'}</b><span>{finance.discrepancy_count} eltérő munkalap · {finance.business_date}</span></div></div><strong>{finance.counts.work_orders||0} lezárt munkalap</strong></section>
   <section className="rec-chain">{chainLabels.map(([key,label],i)=><React.Fragment key={key}><article className={(finance.counts[key]||0)===(finance.counts.work_orders||0)?'ok':'bad'}><small>{label}</small><b>{finance.counts[key]||0}</b>{key!=='work_orders'&&<span>/{finance.counts.work_orders||0}</span>}</article>{i<chainLabels.length-1&&<div className="equals">=</div>}</React.Fragment>)}</section>
   <section className="rec-amounts"><article><small>Munkalap érték</small><b>{money(finance.amount_summary.work_orders)}</b></article><article><small>Fizetések</small><b>{money(finance.amount_summary.payments)}</b></article><article><small>Számlák</small><b>{money(finance.amount_summary.invoices)}</b></article><article><small>Könyvelt összeg</small><b>{money(finance.amount_summary.accounting)}</b></article></section>
   <section className="rec-card"><div className="rec-card-head"><div><h2>Eltéréslista</h2><p>Munkalaponként megmutatja, hol szakad meg a foglalás → munkalap → fizetés → settlement → kassza → pénzügyi tranzakció → számla → NAV → főkönyv lánc.</p></div><span className={finBad.length?'badge bad':'badge ok'}>{finBad.length} eltérés</span></div>{finBad.length?<div className="rec-table-wrap"><table><thead><tr><th>Munkalap</th><th>Eltérés</th><th>Munkalap</th><th>Fizetés</th><th>Számla</th><th>Könyvelés</th></tr></thead><tbody>{finBad.map(x=><tr key={x.work_order_id}><td><b>{x.work_order_number}</b></td><td><div className="issue-tags">{x.issues.map(i=><span key={i}>{issueName[i]||i}</span>)}</div></td><td>{money(x.amounts.work_order)}</td><td>{money(x.amounts.payments)}</td><td>{money(x.amounts.invoice)}</td><td>{money(x.amounts.accounting_debit)}</td></tr>)}</tbody></table></div>:<div className="rec-empty"><CheckCircle2/> A kiválasztott üzleti napon nincs pénzügyi lánceltérés.</div>}</section>
  </>}

  {tab==='stock'&&stock&&<>
   <section className={`rec-status ${stock.status}`}><div>{stock.status==='ok'?<PackageCheck/>:<ShieldAlert/>}<div><small>AUTOMATIKUS STOCK RECONCILIATION</small><b>{stock.status==='ok'?'KÉSZLET EGYENLET RENDBEN':'PIROS KÉSZLETELTÉRÉS'}</b><span>{stock.discrepancy_count} eltérés · abszolút különbség: {qty(stock.total_abs_difference)}</span></div></div><strong>{stock.item_count} ellenőrzött készletpozíció</strong></section>
   <section className="rec-formula"><b>nyitókészlet + bevételezés + átadás be − felhasználás − értékesítés − selejt − átadás ki ± korrekció = zárókészlet</b><span>A rendszer ezt telephely/raktár/termék szinten újraszámolja a mozgásnaplóból.</span></section>
   <section className="rec-card"><div className="rec-card-head"><div><h2>Készleteltérések</h2><p>Csak a matematikailag nem egyező termékpozíciók jelennek meg pirosan.</p></div><span className={stockBad.length?'badge bad':'badge ok'}>{stockBad.length} eltérés</span></div>{stockBad.length?<div className="rec-table-wrap"><table><thead><tr><th>Telephely / raktár</th><th>Termék</th><th>Nyitó</th><th>+ Bevét</th><th>- Felhasználás</th><th>- Értékesítés</th><th>- Selejt</th><th>± Átadás</th><th>Várt záró</th><th>Tény záró</th><th>Eltérés</th></tr></thead><tbody>{stockBad.map(x=><tr key={`${x.warehouse_id}-${x.product_id}`}><td><b>{x.location_name||'Központ'}</b><small>{x.warehouse_name}</small></td><td>{x.product_name}</td><td>{qty(x.opening)}</td><td>{qty(x.receipts)}</td><td>{qty(x.usage_qty)}</td><td>{qty(x.sales)}</td><td>{qty(x.scrap)}</td><td>{qty(x.transfer_in-x.transfer_out+x.adjustments)}</td><td>{qty(x.expected_closing)}</td><td>{qty(x.observed_closing)}</td><td className="diff">{qty(x.difference)}</td></tr>)}</tbody></table></div>:<div className="rec-empty"><PackageCheck/> A kiválasztott üzleti napon nincs készleteltérés.</div>}</section>
  </>}

  {tab==='process'&&integrity&&<>
   <section className={`rec-status ${integrity.status}`}><div>{integrity.status==='ok'?<CheckCircle2/>:<Workflow/>}<div><small>END-TO-END BUSINESS PROCESS INTEGRITY</small><b>{integrity.status==='ok'?'MINDEN KRITIKUS FOLYAMAT ZÁR':'FOLYAMATELTÉRÉS VAN'}</b><span>{integrity.exception_count} kivétel · {integrity.business_date}</span></div></div><strong>{integrity.processes.filter(x=>x.status==='ok').length}/{integrity.processes.length} folyamat zöld</strong></section>
   <section className="rec-card"><div className="rec-card-head"><div><h2>Üzleti folyamatok</h2><p>A zöld státuszhoz nem elég, hogy a modul elérhető: minden láncszemnek és üzleti invariánsnak konzisztensen kell zárnia.</p></div><span className={integrity.status==='ok'?'badge ok':'badge bad'}>{integrity.status.toUpperCase()}</span></div></section>
   {integrity.processes.map(process=><section className="rec-card" key={process.key}><div className="rec-card-head"><div><h2>{processName[process.key]||process.key}</h2><p>{process.label}</p></div><span className={process.status==='ok'?'badge ok':'badge bad'}>{process.exception_count} kivétel</span></div><section className="rec-chain">{process.chain.map((step,i)=><React.Fragment key={`${process.key}-${step.key}`}><article className={step.ok===step.total?'ok':'bad'}><small>{step.label}</small><b>{step.ok}</b><span>/{step.total}</span></article>{i<process.chain.length-1&&<div className="equals">→</div>}</React.Fragment>)}</section></section>)}
   <section className="rec-card"><div className="rec-card-head"><div><h2>Központi kivétellista</h2><p>Egy helyen mutatja, hol szakadt meg a pénzügyi, készlet-, beszerzési vagy rendszerintegritási lánc.</p></div><span className={integrityBad.length?'badge bad':'badge ok'}>{integrityBad.length} kivétel</span></div>{integrityBad.length?<div className="rec-table-wrap"><table><thead><tr><th>Folyamat</th><th>Entitás</th><th>Lépés</th><th>Súlyosság</th><th>Eltérés</th></tr></thead><tbody>{integrityBad.map((x,i)=><tr key={`${x.process_key}-${x.entity_id}-${x.code}-${i}`}><td><b>{processName[x.process_key]||x.process_key}</b></td><td>{x.entity_type}<br/><small>{x.entity_id}</small></td><td>{x.step_key}</td><td className="diff">{x.severity==='critical'?'KRITIKUS':'FIGYELMEZTETÉS'}</td><td><b>{x.title}</b><br/><small>{x.detail}</small></td></tr>)}</tbody></table></div>:<div className="rec-empty"><CheckCircle2/> Nincs üzleti folyamatintegritási kivétel.</div>}</section>
  </>}

  <section className="rec-history"><h2>30 napos kontrolltörténet</h2><div>{(history?.finance||[]).slice(0,10).map((x:any)=><span className={x.status} key={`f-${x.business_date}`}>Pénzügy {String(x.business_date).slice(0,10)} · {x.discrepancy_count} eltérés</span>)}</div><div>{(history?.stock||[]).slice(0,10).map((x:any)=><span className={x.status} key={`s-${x.business_date}`}>Készlet {String(x.business_date).slice(0,10)} · {x.discrepancy_count} eltérés</span>)}</div><div>{(history?.process_integrity||[]).slice(0,10).map((x:any)=><span className={x.status} key={`p-${x.business_date}`}>Folyamat {String(x.business_date).slice(0,10)} · {x.exception_count} kivétel</span>)}</div></section>
 </div>
}
