import React,{useCallback,useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,DatabaseZap,PackageCheck,RefreshCw,ShieldAlert}from'lucide-react';
import api from'../api';
import'./ReconciliationCenterPage.css';

type FinanceItem={work_order_id:string;work_order_number:string;location_id?:string|null;issues:string[];chain:Record<string,boolean|string>;amounts:{work_order:number;payments:number;invoice:number;accounting_debit:number}};
type FinanceResult={business_date:string;status:'ok'|'critical';counts:Record<string,number>;amount_summary:Record<string,number>;discrepancy_count:number;items:FinanceItem[];discrepancies:FinanceItem[];generated_at:string};
type StockItem={warehouse_id:string;warehouse_name:string;location_id?:string|null;location_name?:string|null;product_id:string;product_name:string;opening:number;receipts:number;usage_qty:number;sales:number;scrap:number;transfer_in:number;transfer_out:number;adjustments:number;expected_closing:number;observed_closing:number;difference:number;movement_count:number};
type StockResult={business_date:string;status:'ok'|'critical';item_count:number;discrepancy_count:number;total_abs_difference:number;items:StockItem[];discrepancies:StockItem[];generated_at:string};

const BASE='/api/transactions/notifications/reconciliation';
const money=(v:unknown)=>`${Math.round(Number(v||0)).toLocaleString('hu-HU')} Ft`;
const qty=(v:unknown)=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:3}).format(Number(v||0));
const budapestDate=(offsetDays=0)=>{const d=new Date(Date.now()+offsetDays*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
const issueName:Record<string,string>={booking_link_missing:'Foglaláskapcsolat hiányzik',settlement_missing:'Settlement hiányzik',payment_amount_mismatch:'Fizetési összeg eltér',financial_ledger_missing:'Pénzügyi ledger-kapcsolat hiányzik',cashier_link_missing:'Kasszakapcsolat hiányzik',invoice_not_issued:'Hivatalos számla nincs kiállítva',invoice_amount_mismatch:'Számlaösszeg eltér',nav_failed:'NAV adatszolgáltatás hibás',nav_not_completed:'NAV adatszolgáltatás nincs kész',accounting_not_reconciled:'Könyvelés nincs egyeztetve'};
const chainLabels:[string,string][]=[['work_orders','Lezárt munkalap'],['settlement_ok','Settlement'],['payment_ok','Rendezett fizetés'],['ledger_ok','Pénzügyi tranzakció'],['cashier_ok','Kassza'],['invoice_ok','Számla'],['nav_ok','NAV'],['accounting_ok','Könyvelés']];

export default function ReconciliationCenterPage(){
 const[date,setDate]=useState(budapestDate(-1)),[tab,setTab]=useState<'finance'|'stock'>('finance'),[finance,setFinance]=useState<FinanceResult|null>(null),[stock,setStock]=useState<StockResult|null>(null),[loading,setLoading]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<any>(null);
 const locationId=localStorage.getItem('kleo_location_id')||'',locationName=localStorage.getItem('kleo_location_name')||'Összes engedélyezett telephely';
 const query=useMemo(()=>{const s=new URLSearchParams({date});if(locationId)s.set('location_id',locationId);return s.toString()},[date,locationId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const h=new URLSearchParams({days:'30'});if(locationId)h.set('location_id',locationId);const[f,s,hi]=await Promise.all([api.get(`${BASE}/finance?${query}`),api.get(`${BASE}/stock?${query}`),api.get(`${BASE}/history?${h}`)]);setFinance(f.data);setStock(s.data);setHistory(hi.data)}catch(e:any){setError(e?.response?.data?.message||'Az egyeztetési adatok nem tölthetők be.')}finally{setLoading(false)}},[query,locationId]);
 useEffect(()=>{void load()},[load]);
 async function run(){setRunning(true);setError('');try{await api.post(`${BASE}/run`,{date,location_id:locationId||null,scope:'all'});await load()}catch(e:any){setError(e?.response?.data?.message||'Az egyeztetés futtatása nem sikerült.')}finally{setRunning(false)}}
 const finBad=finance?.discrepancies||[],stockBad=stock?.discrepancies||[];
 return <div className="rec-page">
  <header className="rec-hero"><div><span>PÉNZÜGYEK · ÜZLETI INTEGRITÁS</span><h1><DatabaseZap/> Pénzügyi egyeztető központ</h1><p>{locationName} · napi teljes lánckontroll és automatikus készletegyeztetés.</p></div><div className="rec-actions"><label>Üzleti nap<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="ghost" onClick={load} disabled={loading}><RefreshCw size={16}/>{loading?'Frissítés…':'Frissítés'}</button><button className="primary" onClick={run} disabled={running}><ShieldAlert size={16}/>{running?'Egyeztetés…':'Futtatás és riasztás'}</button></div></header>
  {error&&<div className="rec-error"><AlertTriangle size={18}/>{error}</div>}
  <nav className="rec-tabs"><button className={tab==='finance'?'active':''} onClick={()=>setTab('finance')}>Pénzügyi lánc</button><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>Automatikus stock reconciliation</button></nav>

  {tab==='finance'&&finance&&<>
   <section className={`rec-status ${finance.status}`}><div>{finance.status==='ok'?<CheckCircle2/>:<ShieldAlert/>}<div><small>NAPI PÉNZÜGYI KONTROLL</small><b>{finance.status==='ok'?'MINDEN LÁNCSZEM EGYEZIK':'PIROS ELTÉRÉS'}</b><span>{finance.discrepancy_count} eltérő munkalap · {finance.business_date}</span></div></div><strong>{finance.counts.work_orders||0} lezárt munkalap</strong></section>
   <section className="rec-chain">{chainLabels.map(([key,label],i)=><React.Fragment key={key}><article className={(finance.counts[key]||0)===(finance.counts.work_orders||0)?'ok':'bad'}><small>{label}</small><b>{finance.counts[key]||0}</b>{key!=='work_orders'&&<span>/{finance.counts.work_orders||0}</span>}</article>{i<chainLabels.length-1&&<div className="equals">=</div>}</React.Fragment>)}</section>
   <section className="rec-amounts"><article><small>Munkalap érték</small><b>{money(finance.amount_summary.work_orders)}</b></article><article><small>Fizetések</small><b>{money(finance.amount_summary.payments)}</b></article><article><small>Számlák</small><b>{money(finance.amount_summary.invoices)}</b></article><article><small>Könyvelt összeg</small><b>{money(finance.amount_summary.accounting)}</b></article></section>
   <section className="rec-card"><div className="rec-card-head"><div><h2>Eltéréslista</h2><p>Munkalaponként megmutatja, hol szakad meg a foglalás → munkalap → settlement → kassza → számla → NAV → könyvelés lánc.</p></div><span className={finBad.length?'badge bad':'badge ok'}>{finBad.length} eltérés</span></div>{finBad.length?<div className="rec-table-wrap"><table><thead><tr><th>Munkalap</th><th>Eltérés</th><th>Munkalap</th><th>Fizetés</th><th>Számla</th><th>Könyvelés</th></tr></thead><tbody>{finBad.map(x=><tr key={x.work_order_id}><td><b>{x.work_order_number}</b></td><td><div className="issue-tags">{x.issues.map(i=><span key={i}>{issueName[i]||i}</span>)}</div></td><td>{money(x.amounts.work_order)}</td><td>{money(x.amounts.payments)}</td><td>{money(x.amounts.invoice)}</td><td>{money(x.amounts.accounting_debit)}</td></tr>)}</tbody></table></div>:<div className="rec-empty"><CheckCircle2/> A kiválasztott üzleti napon nincs pénzügyi lánceltérés.</div>}</section>
  </>}

  {tab==='stock'&&stock&&<>
   <section className={`rec-status ${stock.status}`}><div>{stock.status==='ok'?<PackageCheck/>:<ShieldAlert/>}<div><small>AUTOMATIKUS STOCK RECONCILIATION</small><b>{stock.status==='ok'?'KÉSZLET EGYENLET RENDBEN':'PIROS KÉSZLETELTÉRÉS'}</b><span>{stock.discrepancy_count} eltérés · abszolút különbség: {qty(stock.total_abs_difference)}</span></div></div><strong>{stock.item_count} ellenőrzött készletpozíció</strong></section>
   <section className="rec-formula"><b>nyitókészlet + bevételezés + átadás be − felhasználás − értékesítés − selejt − átadás ki ± korrekció = zárókészlet</b><span>A rendszer ezt telephely/raktár/termék szinten újraszámolja a mozgásnaplóból.</span></section>
   <section className="rec-card"><div className="rec-card-head"><div><h2>Készleteltérések</h2><p>Csak a matematikailag nem egyező termékpozíciók jelennek meg pirosan.</p></div><span className={stockBad.length?'badge bad':'badge ok'}>{stockBad.length} eltérés</span></div>{stockBad.length?<div className="rec-table-wrap"><table><thead><tr><th>Telephely / raktár</th><th>Termék</th><th>Nyitó</th><th>+ Bevét</th><th>- Felhasználás</th><th>- Értékesítés</th><th>- Selejt</th><th>± Átadás</th><th>Várt záró</th><th>Tény záró</th><th>Eltérés</th></tr></thead><tbody>{stockBad.map(x=><tr key={`${x.warehouse_id}-${x.product_id}`}><td><b>{x.location_name||'Központ'}</b><small>{x.warehouse_name}</small></td><td>{x.product_name}</td><td>{qty(x.opening)}</td><td>{qty(x.receipts)}</td><td>{qty(x.usage_qty)}</td><td>{qty(x.sales)}</td><td>{qty(x.scrap)}</td><td>{qty(x.transfer_in-x.transfer_out+x.adjustments)}</td><td>{qty(x.expected_closing)}</td><td>{qty(x.observed_closing)}</td><td className="diff">{qty(x.difference)}</td></tr>)}</tbody></table></div>:<div className="rec-empty"><PackageCheck/> A kiválasztott üzleti napon nincs készleteltérés.</div>}</section>
  </>}

  <section className="rec-history"><h2>30 napos kontrolltörténet</h2><div>{(history?.finance||[]).slice(0,10).map((x:any)=><span className={x.status} key={`f-${x.business_date}`}>Pénzügy {String(x.business_date).slice(0,10)} · {x.discrepancy_count} eltérés</span>)}</div><div>{(history?.stock||[]).slice(0,10).map((x:any)=><span className={x.status} key={`s-${x.business_date}`}>Készlet {String(x.business_date).slice(0,10)} · {x.discrepancy_count} eltérés</span>)}</div></section>
 </div>
}
