// src/pages/Register.tsx
import React,{useEffect,useMemo,useState}from"react";
import{useNavigate,useSearchParams}from"react-router-dom";
import axios from"axios";
import"./Login.css";
import logo from"../assets/kleo_logo.png";
import bg from"../assets/background_register.webp";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';

interface FormData{full_name:string;email:string;password:string;zip_code:string;city:string;address:string;birth_date:string;gender:string;heard_about_us:string;nearest_salon:string;newsletter:boolean;loyalty_program:boolean;consent:boolean;}
interface RegisterResponse{success:boolean;error?:string;}

type InviteInfo={email:string;tenant_name:string;tenant_slug:string;expires_at:string};

const Register:React.FC=()=>{
 const navigate=useNavigate();const[params]=useSearchParams();const inviteToken=useMemo(()=>String(params.get('tenant_invite')||'').trim(),[params]);
 const[formData,setFormData]=useState<FormData>({full_name:'',email:'',password:'',zip_code:'',city:'',address:'',birth_date:'',gender:'',heard_about_us:'',nearest_salon:'',newsletter:false,loyalty_program:false,consent:false});
 const[invite,setInvite]=useState<InviteInfo|null>(null),[inviteChecking,setInviteChecking]=useState(Boolean(inviteToken)),[error,setError]=useState(''),[loading,setLoading]=useState(false),[success,setSuccess]=useState('');
 useEffect(()=>{if(!inviteToken)return;let live=true;(async()=>{setInviteChecking(true);setError('');try{const r=await axios.get(`${API_BASE}/saas/admin-invitations/${encodeURIComponent(inviteToken)}`,{withCredentials:false});if(!live)return;setInvite(r.data?.invitation||null);setFormData(v=>({...v,email:r.data?.invitation?.email||v.email}));}catch(e:any){if(live)setError(e?.response?.data?.error||'A meghívó nem érvényes.');}finally{if(live)setInviteChecking(false)}})();return()=>{live=false}},[inviteToken]);
 const handleChange=(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>{const t=e.target;const value=t instanceof HTMLInputElement&&t.type==='checkbox'?t.checked:t.value;setFormData(p=>({...p,[t.name]:value}as FormData));};
 const activateAdmin=async(e:React.FormEvent)=>{e.preventDefault();if(!inviteToken||!invite)return;setLoading(true);setError('');try{await axios.post(`${API_BASE}/saas/admin-invitations/${encodeURIComponent(inviteToken)}/accept`,{full_name:formData.full_name,password:formData.password},{withCredentials:false});setSuccess('Az adminisztrátori fiók aktiválása sikerült. Most már bejelentkezhet.');setTimeout(()=>navigate('/login'),1200);}catch(err:any){setError(err?.response?.data?.error||'Az aktiválás nem sikerült.');}finally{setLoading(false)}};
 const registerCustomer=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);if(!formData.consent){setError('Az adatkezelési feltételek elfogadása kötelező.');setLoading(false);return;}try{const response=await axios.post<RegisterResponse>('/api/register',formData,{withCredentials:true});if(response.data.success){alert('Sikeres regisztráció! Kérlek, ellenőrizd az e-mail fiókodat és erősítsd meg a regisztrációd.');navigate('/login')}else setError(response.data.error||'Hiba a regisztráció során.');}catch(err:any){setError(err?.response?.data?.error||'Hálózati hiba történt.');}finally{setLoading(false)}};

 if(inviteToken)return <div className="login-page"><div className="login-card"><div className="login-card-bg" style={{backgroundImage:`url(${bg})`}}/><div className="login-card-overlay"/><div className="login-card-inner"><div className="login-header"><div className="login-logo"><img src={logo} alt="Kleoszalon logó"/></div></div><h1 className="login-title">Adminisztrátori fiók aktiválása</h1>{inviteChecking?<p className="login-subtitle">Meghívó ellenőrzése…</p>:invite?<><p className="login-subtitle"><strong>{invite.tenant_name}</strong><br/>{invite.email}<br/>A meghívó lejárata: {new Date(invite.expires_at).toLocaleString('hu-HU')}</p>{error&&<div className="login-error">{error}</div>}{success&&<div className="login-success">{success}</div>}<form onSubmit={activateAdmin}><div className="login-field"><label className="login-label">Teljes név</label><input className="login-input" name="full_name" value={formData.full_name} onChange={handleChange} required/></div><div className="login-field"><label className="login-label">E-mail</label><input className="login-input" value={invite.email} readOnly/></div><div className="login-field"><label className="login-label">Új jelszó</label><input className="login-input" type="password" name="password" value={formData.password} onChange={handleChange} minLength={10} required/><small>Legalább 10 karakter, betűvel és számmal.</small></div><button className="login-button" type="submit" disabled={loading}>{loading?'Aktiválás…':'Admin fiók aktiválása'}</button></form></>:<>{error&&<div className="login-error">{error}</div>}<button className="login-button" type="button" onClick={()=>navigate('/login')}>Belépés</button></>}</div></div></div>;

 return <div className="login-page"><div className="login-card"><div className="login-card-bg" style={{backgroundImage:`url(${bg})`}}/><div className="login-card-overlay"/><div className="login-card-inner"><div className="login-header"><div className="login-logo"><img src={logo} alt="Kleoszalon logó"/></div></div><h1 className="login-title">Kleoszalon Regisztráció</h1><p className="login-subtitle">Kérjük, add meg az adataidat a fiók létrehozásához.</p>{error&&<div className="login-error">{error}</div>}<form onSubmit={registerCustomer}>
  <div className="login-field"><label className="login-label">Teljes név</label><input type="text" name="full_name" className="login-input" value={formData.full_name} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">E-mail</label><input type="email" name="email" className="login-input" value={formData.email} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">Jelszó</label><input type="password" name="password" className="login-input" value={formData.password} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">Irányítószám</label><input name="zip_code" className="login-input" value={formData.zip_code} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">Város</label><input name="city" className="login-input" value={formData.city} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">Cím</label><input name="address" className="login-input" value={formData.address} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">Születési dátum</label><input type="date" name="birth_date" className="login-input" value={formData.birth_date} onChange={handleChange} required/></div>
  <div className="login-field"><label className="login-label">Nem</label><select name="gender" className="login-input" value={formData.gender} onChange={handleChange}><option value="">Válassz...</option><option value="male">Férfi</option><option value="female">Nő</option></select></div>
  <div className="login-field"><label className="login-label">Hogyan hallott rólunk?</label><input name="heard_about_us" className="login-input" value={formData.heard_about_us} onChange={handleChange}/></div>
  <div className="login-field"><label className="login-label">Legközelebbi szalon</label><input name="nearest_salon" className="login-input" value={formData.nearest_salon} onChange={handleChange}/></div>
  <div className="login-checkbox-group"><label className="login-checkbox"><input type="checkbox" name="newsletter" checked={formData.newsletter} onChange={handleChange}/>Kérek értesítést az akciókról</label><label className="login-checkbox"><input type="checkbox" name="loyalty_program" checked={formData.loyalty_program} onChange={handleChange}/>Részt kívánok venni a pontgyűjtő rendszerben</label><label className="login-checkbox"><input type="checkbox" name="consent" checked={formData.consent} onChange={handleChange} required/>Elfogadom az adatkezelési feltételeket</label></div>
  <button type="submit" disabled={loading} className="login-button">{loading?'Regisztráció...':'Regisztráció'}</button><div className="login-footer">Már van fiókod? <button type="button" className="login-footer-link" onClick={()=>navigate('/login')}>Belépés</button></div>
 </form></div></div></div>;
};
export default Register;
