import{useCallback,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,ArrowLeft,CheckCircle2,Clock3,ExternalLink,LockKeyhole,RefreshCw,Save,ShieldCheck,ShieldAlert,UnlockKeyhole}from'lucide-react';
import{useNavigate}from'react-router-dom';
import api from'../api';
import'./ResilienceRecoveryPage.css';

const BASE='/api/transactions/notifications/exceptions/intelligence/resilience';
const stateHu:Record<string,string>={impacted:'Érintett',recovering:'Helyreállítás',degraded:'Degradált',restored:'Helyreállt',verified:'Verifikált'};
const sessionHu:Record<string,string>={open:'Nyitott',recovering:'Helyreállítás',verifying:'Verifikáció',all_clear:'ALL CLEAR',closed:'Lezárt'};
const fmt=(v:any)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const n=(v:any)=>Number(v||0);

export default function ResilienceRecoveryPage(){
 const navigate=useNavigate();const[summary,setSummary]=useState<any>(null),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[profiles,setProfiles]=useState<any[]>([]),[loading,setLoading]=useState(false),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[status,setStatus]=useState('all'),[serviceDraft,setServiceDraft]=useState<Record<string,any>>({}),[stepEvidence,setStepEvidence]=useState<Record<string,string>>({});
 const[allClearNote,setAllClearNote]=useState(''),[allClearEvidence,setAllClearEvidence]=useState('');
 const[override,setOverride]=useState({release_ref:'',reason:'',evidence:'',duration_minutes:60}),[decisionNote,setDecisionNote]=useState(''),[decisionEvidence,setDecisionEvidence]=useState('');
 const locationId=localStorage.getItem('kleo_location_id')||'';
 const q=useMemo(()=>{const p=new URLSearchParams();if(status!=='all')p.set('status',status);if(locationId)p.set('location_id',locationId);return p.toString()},[status,locationId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const sp=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const[a,b,c]=await Promise.all([api.get(`${BASE}/summary${sp}`),api.get(`${BASE}/sessions?${q}`),api.get(`${BASE}/services`)]);setSummary(a.data);setItems(b.data?.items||[]);setProfiles(c.data?.items||[])}catch(e:any){setError(e?.response?.data?.message||'A Resilience & Recovery központ nem tölthető be.')}finally{setLoading(false)}},[locationId,q]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const t=window.setInterval(()=>void load(),45_000);return()=>window.clearInterval(t)},[load]);
 async function open(id:string){try{const sp=locationId?`?location_id=${encodeURIComponent(locationId)}`:'';const r=await api.get(`${BASE}/sessions/${id}${sp}`);setSelected(r.data);const draft:Record<string,any>={};for(const x of r.data.services||[])draft[x.service_key]={state:x.state,rpo_observed_minutes:x.rpo_observed_minutes??'',verification_note:x.verification_note||'',evidence:''};setServiceDraft(draft);setAllClearNote(r.data.item?.all_clear_note||'');setAllClearEvidence('')}catch(e:any){setError(e?.response?.data?.message||'A recovery session nem nyitható meg.')}}
 async function sync(){setSyncing(true);setError('');try{const r=await api.post(`${BASE}/sync`);setNotice(`Recovery sync: ${r.data?.sessions||0} session, ${r.data?.active_freezes||0} aktív change-freeze.`);await load()}catch(e:any){setError(e?.response?.data?.message||'A recovery sync nem futtatható.')}finally{setSyncing(false)}}
 async function saveService(x:any){if(!selected)return;const d=serviceDraft[x.service_key]||{};const input:any={state:d.state,rpo_observed_minutes:d.rpo_observed_minutes===''?null:Number(d.rpo_observed_minutes),verification_note:d.verification_note||'',evidence:d.evidence?{description:d.evidence,source:'resilience-management'}:{}};if(d.state==='verified'&&(String(d.verification_note||'').trim().length<10||String(d.evidence||'').trim().length<5)){setError('Verifikáláshoz legalább 10 karakteres jegyzet és konkrét evidence szükséges.');return}try{await api.patch(`${BASE}/sessions/${selected.item.id}/services/${x.service_key}`,input);setNotice(`${x.name} recovery állapota mentve.`);await open(selected.item.id);await load()}catch(e:any){setError(e?.response?.data?.message||'A szolgáltatás recovery állapota nem menthető.')}}
 async function stepStatus(step:any,next:string){if(!selected)return;let evidence='';if(next==='completed'){evidence=(stepEvidence[`${step.service_key}:${step.step_key}`]||'').trim();if(evidence.length<5){setError('Recovery step lezárásához konkrét bizonyíték szükséges.');return}}try{await api.patch(`${BASE}/sessions/${selected.item.id}/steps/${step.service_key}/${step.step_key}`,{status:next,evidence:evidence?{description:evidence,source:'recovery-runbook'}:{}});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'A runbook step nem módosítható.')}}
 async function allClear(){if(!selected)return;if(allClearNote.trim().length<10||allClearEvidence.trim().length<5){setError('ALL CLEAR-hez legalább 10 karakteres indok és konkrét bizonyíték szükséges.');return}if(!window.confirm('Biztosan kiadja az ALL CLEAR állapotot és feloldja az aktív change-freeze-et?'))return;try{await api.post(`${BASE}/sessions/${selected.item.id}/all-clear`,{note:allClearNote.trim(),evidence:{description:allClearEvidence.trim(),source:'recovery-all-clear'}});setNotice('ALL CLEAR rögzítve, change-freeze feloldva.');await open(selected.item.id);await load()}catch(e:any){setError(e?.response?.data?.message||'Az ALL CLEAR nem adható ki.')}}
 async function requestOverride(){if(!selected?.item?.freeze_id)return;if(override.release_ref.trim().length<7||override.reason.trim().length<10||override.evidence.trim().length<5){setError('Emergency override kéréshez release SHA/ref, részletes indok és evidence szükséges.');return}try{await api.post(`${BASE}/freezes/${selected.item.freeze_id}/overrides`,{release_ref:override.release_ref.trim(),reason:override.reason.trim(),duration_minutes:override.duration_minutes,evidence:{description:override.evidence.trim(),source:'emergency-change-request'}});setNotice('Emergency override kérés létrehozva. Második vezető jóváhagyása szükséges.');setOverride({...override,reason:'',evidence:''});await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'Az emergency override kérés nem hozható létre.')}}
 async function decideOverride(row:any,decision:'approved'|'rejected'){if(!selected?.item?.freeze_id)return;if(decisionNote.trim().length<5||(decision==='approved'&&decisionEvidence.trim().length<5)){setError('A döntéshez indok, jóváhagyásnál konkrét evidence is szükséges.');return}try{await api.post(`${BASE}/freezes/${selected.item.freeze_id}/overrides/${row.id}/decision`,{decision,note:decisionNote.trim(),evidence:decision==='approved'?{description:decisionEvidence.trim(),source:'second-person-approval'}:{}});setDecisionNote('');setDecisionEvidence('');setNotice(`Emergency override ${decision==='approved'?'jóváhagyva':'elutasítva'}.`);await open(selected.item.id)}catch(e:any){setError(e?.response?.data?.message||'Az override döntés nem menthető.')}}
 async function saveProfile(p:any){try{await api.put(`${BASE}/services/${p.service_key}`,p);setNotice(`${p.name} RTO/RPO profil mentve.`);await load()}catch(e:any){setError(e?.response?.data?.message||'Az RTO/RPO profil nem menthető.')}}
 const item=selected?.item;const stepsByService=useMemo(()=>{const m:Record<string,any[]>={};for(const s of selected?.steps||[])(m[s.service_key]||(m[s.service_key]=[])).push(s);return m},[selected]);
 return <div className="rr-page">
  <header className="rr-hero"><div><button onClick={()=>navigate('/finance/exception-command-center/major-incidents')}><ArrowLeft/> Major Incident / War Room</button><span>STATISZTIKA ÉS VIR · BUSINESS CONTINUITY / RECOVERY CONTROL</span><h1><Activity/> Resilience & Recovery</h1><p>RTO/RPO kontroll, recovery runbookok, change-freeze, kétkulcsos emergency change és bizonyítékos ALL CLEAR.</p></div><div className="rr-control"><ShieldCheck/><b>FAIL-CLOSED RECOVERY</b><span>SEV1/SEV2 alatt automatikus change-freeze · All Clear csak teljes verifikáció után</span></div></header>
  <div className="rr-toolbar"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Minden recovery session</option>{Object.entries(sessionHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={sync} disabled={syncing}><RefreshCw className={syncing?'spin':''}/>{syncing?'Szinkron…':'Recovery sync'}</button></div>
  {error&&<div className="rr-error"><AlertTriangle/>{error}</div>}{notice&&<div className="rr-notice"><CheckCircle2/>{notice}</div>}
  {summary&&<section className="rr-kpis"><article className={n(summary.active_freezes)>0?'danger':''}><LockKeyhole/><div><small>Aktív change-freeze</small><b>{n(summary.active_freezes)}</b></div></article><article className={n(summary.rto_breaches)>0?'danger':''}><Clock3/><div><small>RTO sértés</small><b>{n(summary.rto_breaches)}</b></div></article><article className={n(summary.rpo_breaches)>0?'danger':''}><ShieldAlert/><div><small>RPO sértés</small><b>{n(summary.rpo_breaches)}</b></div></article><article className={n(summary.unverified_services)>0?'warning':''}><Activity/><div><small>Nem verifikált szolgáltatás</small><b>{n(summary.unverified_services)}</b></div></article><article><RefreshCw/><div><small>Aktív recovery session</small><b>{n(summary.active_sessions)}</b></div></article><article className={n(summary.pending_overrides)>0?'warning':''}><UnlockKeyhole/><div><small>Override jóváhagyásra vár</small><b>{n(summary.pending_overrides)}</b></div></article></section>}
  <section className="rr-work"><div className="rr-list"><header><b>Recovery sessionök</b><span>{items.length}</span></header>{loading&&!items.length&&<div className="rr-empty">Betöltés…</div>}{items.map(x=><button key={x.id} className={`${selected?.item?.id===x.id?'active':''} ${x.severity}`} onClick={()=>open(x.id)}><div><span>{String(x.severity).toUpperCase()}</span><em>{sessionHu[x.status]||x.status}</em></div><b>{x.incident_no} · {x.incident_title}</b><small>{x.location_id||'globális'} · impact {x.impact_score}/100</small><footer><span>{x.verified_services}/{x.service_count} szolgáltatás</span><span>{x.completed_steps}/{x.step_count} step</span><strong>{x.freeze_status==='active'?'CHANGE-FREEZE':'freeze oldva'}</strong></footer></button>)}{!loading&&!items.length&&<div className="rr-empty"><CheckCircle2/> Nincs recovery session.</div>}</div>
   <div className="rr-detail">{!selected?<div className="rr-placeholder"><ShieldCheck/><h2>Válasszon recovery sessiont</h2><p>Itt vezérelhető a szolgáltatás-helyreállítás, runbook, RTO/RPO verifikáció és a change-freeze.</p></div>:<><header className={`rr-detail-head ${item.severity}`}><div><span>{String(item.severity).toUpperCase()} · {sessionHu[item.status]}</span><h2>{item.incident_no} · Recovery Control</h2><p>{item.incident_title}</p></div><button onClick={()=>navigate('/finance/exception-command-center/major-incidents')}><ExternalLink/> War Room</button></header>
    <section className="rr-freeze"><div><h3>{item.freeze_status==='active'?<LockKeyhole/>:<UnlockKeyhole/>} Change-freeze</h3><p>{item.freeze_reason||'Nincs aktív freeze.'}</p><small>Aktiválva: {fmt(item.activated_at)}</small></div><strong className={item.freeze_status==='active'?'active':'lifted'}>{item.freeze_status==='active'?'ACTIVE FREEZE':'LIFTED'}</strong></section>
    <section className="rr-services"><h3>Szolgáltatás helyreállítás · RTO/RPO</h3>{(selected.services||[]).map((x:any)=>{const d=serviceDraft[x.service_key]||{};const rtoBreach=n(x.elapsed_minutes)>n(x.rto_minutes)&&x.state!=='verified',rpoBreach=x.rpo_observed_minutes!=null&&n(x.rpo_observed_minutes)>n(x.rpo_minutes);return <article key={x.service_key} className={`${x.state} ${rtoBreach||rpoBreach?'breach':''}`}><header><div><b>{x.name}</b><small>{x.criticality.toUpperCase()} · owner: {x.owner_team||'—'}</small></div><div><span>RTO {x.rto_minutes} p</span><span>RPO {x.rpo_minutes} p</span><span>elapsed {x.elapsed_minutes} p</span></div></header><div className="rr-service-form"><select value={d.state||x.state} onChange={e=>setServiceDraft({...serviceDraft,[x.service_key]:{...d,state:e.target.value}})}>{Object.entries(stateHu).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input type="number" min="0" value={d.rpo_observed_minutes??''} onChange={e=>setServiceDraft({...serviceDraft,[x.service_key]:{...d,rpo_observed_minutes:e.target.value}})} placeholder="Mért RPO perc"/><input value={d.verification_note||''} onChange={e=>setServiceDraft({...serviceDraft,[x.service_key]:{...d,verification_note:e.target.value}})} placeholder="Verifikációs jegyzet…"/><input value={d.evidence||''} onChange={e=>setServiceDraft({...serviceDraft,[x.service_key]:{...d,evidence:e.target.value}})} placeholder="Evidence…"/><button onClick={()=>saveService(x)}><Save/> Mentés</button></div><div className="rr-runbook">{(stepsByService[x.service_key]||[]).map((s:any)=>{const key=`${s.service_key}:${s.step_key}`;return <div key={key} className={s.status}><span>{s.order_index}</span><div><b>{s.title}</b><small>{s.instruction}</small></div><em>{s.status}</em>{s.status!=='completed'&&<><input value={stepEvidence[key]||''} onChange={e=>setStepEvidence({...stepEvidence,[key]:e.target.value})} placeholder="Step evidence…"/><button onClick={()=>stepStatus(s,s.status==='pending'?'in_progress':'completed')}>{s.status==='pending'?'Indítás':'Lezárás'}</button></>}</div>})}</div></article>})}</section>
    {item.freeze_status==='active'&&<section className="rr-override"><h3><UnlockKeyhole/> Emergency change override · two-person rule</h3><p>Csak incidensjavító sürgős release esetén. A kérelmező nem hagyhatja jóvá a saját kérését.</p><div className="rr-override-form"><input value={override.release_ref} onChange={e=>setOverride({...override,release_ref:e.target.value})} placeholder="Release SHA / ref"/><input value={override.reason} onChange={e=>setOverride({...override,reason:e.target.value})} placeholder="Indok…"/><input value={override.evidence} onChange={e=>setOverride({...override,evidence:e.target.value})} placeholder="Kérés evidence…"/><input type="number" min="15" max="120" value={override.duration_minutes} onChange={e=>setOverride({...override,duration_minutes:Number(e.target.value)})}/><button onClick={requestOverride}>Override kérése</button></div><div className="rr-overrides">{(selected.overrides||[]).map((o:any)=><div key={o.id}><span className={o.status}>{o.status}</span><div><b>{o.release_ref}</b><small>{o.requested_by} · lejár: {fmt(o.expires_at)}</small><p>{o.reason}</p></div>{o.status==='pending'&&<div className="rr-decision"><input value={decisionNote} onChange={e=>setDecisionNote(e.target.value)} placeholder="Döntés indoka…"/><input value={decisionEvidence} onChange={e=>setDecisionEvidence(e.target.value)} placeholder="Approval evidence…"/><button onClick={()=>decideOverride(o,'approved')}>Jóváhagyás</button><button className="reject" onClick={()=>decideOverride(o,'rejected')}>Elutasítás</button></div>}</div>)}</div></section>}
    <section className="rr-allclear"><h3><ShieldCheck/> ALL CLEAR</h3><p>Csak minden kötelező runbook-step, minden szolgáltatás verifikációja és minden Critical/High War Room akció lezárása után adható ki.</p><textarea value={allClearNote} onChange={e=>setAllClearNote(e.target.value)} placeholder="All Clear indok…"/><textarea value={allClearEvidence} onChange={e=>setAllClearEvidence(e.target.value)} placeholder="All Clear evidence…"/><button disabled={item.status==='all_clear'||item.status==='closed'} onClick={allClear}><ShieldCheck/> ALL CLEAR + freeze feloldás</button>{item.actual_rto_minutes!=null&&<small>Aktuális RTO: {item.actual_rto_minutes} perc · max. mért RPO: {item.max_observed_rpo_minutes||0} perc</small>}</section>
   </>}</div>
  </section>
  <section className="rr-profiles"><header><div><h2>Business service RTO/RPO profilok</h2><p>A recovery prioritás és célidő szolgáltatásonként konfigurálható.</p></div></header><div>{profiles.map((p:any)=><article key={p.service_key}><b>{p.name}</b><small>{p.service_key} · {p.criticality}</small><label>RTO<input type="number" value={p.rto_minutes} onChange={e=>setProfiles(profiles.map(x=>x.service_key===p.service_key?{...x,rto_minutes:Number(e.target.value)}:x))}/></label><label>RPO<input type="number" value={p.rpo_minutes} onChange={e=>setProfiles(profiles.map(x=>x.service_key===p.service_key?{...x,rpo_minutes:Number(e.target.value)}:x))}/></label><button onClick={()=>saveProfile(p)}>Mentés</button></article>)}</div></section>
 </div>
}