import React,{useCallback,useEffect,useMemo,useState}from"react";
import axios from"axios";
import{BadgeDollarSign,Building2,CalendarClock,CreditCard,Network,ReceiptText,RefreshCw,RotateCcw,ShieldCheck,Sparkles,Store,Users}from"lucide-react";
import"./SaasFranchiseAdminPage.css";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const authConfig=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
const PLAN_OPTIONS=[
 {code:'start',name:'Start'},
 {code:'pro',name:'Pro'},
 {code:'franchise',name:'Franchise'},
 {code:'enterprise',name:'Enterprise'}
];

type TenantContext={tenant_id?:string;slug?:string;name?:string;legal_name?:string;status?:string;plan_code?:string;plan_name?:string;plan_features?:Record<string,boolean>;subscription_status?:string;current_period_end?:string|null;cancel_at_period_end?:boolean;grace_period_end?:string|null;last_payment_status?:string|null;app_name?:string|null;logo_url?:string|null;custom_domain?:string|null};
type LocationRow={id:string;name:string;city?:string|null;address?:string|null;is_active?:boolean;franchise_network_id?:number|null;franchise_network_name?:string|null;member_type?:'owned'|'franchise'|null};
type NetworkRow={id:number;code:string;name:string;owner_legal_name?:string|null;royalty_percent?:number|string;marketing_fee_percent?:number|string;member_count?:number;owned_location_count?:number;franchise_location_count?:number;active?:boolean};
type SubscriptionRow={id?:string;status?:string;starts_at?:string|null;trial_ends_at?:string|null;current_period_end?:string|null;cancel_at_period_end?:boolean;cancelled_at?:string|null;grace_period_end?:string|null;last_payment_status?:string|null;last_payment_at?:string|null;billing_provider?:string|null;external_subscription_id?:string|null;plan_code?:string;plan_name?:string;monthly_price?:number|string;currency?:string;features?:Record<string,boolean>};
type InvoiceRow={id:string;status?:string;period_start?:string|null;period_end?:string|null;currency?:string;net_amount?:number|string;tax_amount?:number|string;gross_amount?:number|string;due_at?:string|null;paid_at?:string|null;external_invoice_id?:string|null;created_at?:string|null};
type SubscriptionEvent={id:string;event_type:string;source?:string;created_at?:string|null;payload?:Record<string,unknown>};

const dateText=(value?:string|null)=>value?new Intl.DateTimeFormat('hu-HU',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'—';
const moneyText=(value?:number|string,currency='HUF')=>new Intl.NumberFormat('hu-HU',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value||0));
const statusText=(status?:string)=>({active:'Aktív',trial:'Próbaidő',past_due:'Fizetési késedelem',suspended:'Felfüggesztve',cancelled:'Lemondva',paid:'Fizetve',open:'Nyitott',draft:'Piszkozat',void:'Érvénytelen'}[String(status||'').toLowerCase()]||status||'—');

export default function SaasFranchiseAdminPage(){
 const[context,setContext]=useState<TenantContext|null>(null),[tenantRole,setTenantRole]=useState(''),[locations,setLocations]=useState<LocationRow[]>([]),[networks,setNetworks]=useState<NetworkRow[]>([]),[subscription,setSubscription]=useState<SubscriptionRow|null>(null),[invoices,setInvoices]=useState<InvoiceRow[]>([]),[events,setEvents]=useState<SubscriptionEvent[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[pendingAction,setPendingAction]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const[networkForm,setNetworkForm]=useState({code:'',name:'',owner_legal_name:'',royalty_percent:'0',marketing_fee_percent:'0'});
 const[memberForm,setMemberForm]=useState({network_id:'',location_id:'',member_type:'franchise'});
 const[selectedPlan,setSelectedPlan]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const cfg=authConfig();const[c,l,n,s]=await Promise.all([axios.get(`${API_BASE}/saas/context`,cfg),axios.get(`${API_BASE}/saas/locations`,cfg),axios.get(`${API_BASE}/saas/franchise-networks`,cfg),axios.get(`${API_BASE}/saas/subscription`,cfg)]);const tenant=c.data?.tenant||null;const sub=s.data?.subscription||null;setContext(tenant);setTenantRole(String(c.data?.tenant_role||''));setLocations(Array.isArray(l.data?.rows)?l.data.rows:[]);setNetworks(Array.isArray(n.data?.rows)?n.data.rows:[]);setSubscription(sub);setInvoices(Array.isArray(s.data?.invoices)?s.data.invoices:[]);setEvents(Array.isArray(s.data?.events)?s.data.events:[]);setSelectedPlan(String(sub?.plan_code||tenant?.plan_code||''))}catch(e:any){setError(e?.response?.data?.error||e?.message||'A SaaS adatok betöltése nem sikerült.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const features=useMemo(()=>Object.entries(context?.plan_features||subscription?.features||{}).filter(([k])=>k!=='all_modules'),[context,subscription]);
 const franchiseLocations=locations.filter(x=>x.member_type==='franchise').length,ownedLocations=locations.filter(x=>x.member_type==='owned').length;
 const feeStats=useMemo(()=>{let franchiseCount=0,weightedRoyalty=0,weightedMarketing=0;for(const n of networks){const count=Number(n.franchise_location_count||0);franchiseCount+=count;weightedRoyalty+=count*Number(n.royalty_percent||0);weightedMarketing+=count*Number(n.marketing_fee_percent||0)}return{franchiseCount,royalty:franchiseCount?weightedRoyalty/franchiseCount:0,marketing:franchiseCount?weightedMarketing/franchiseCount:0}},[networks]);
 const canManageSubscription=['owner','admin'].includes(tenantRole.toLowerCase());
 const providerManaged=Boolean(subscription?.external_subscription_id);
 const createNetwork=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{await axios.post(`${API_BASE}/saas/franchise-networks`,{...networkForm,royalty_percent:Number(networkForm.royalty_percent||0),marketing_fee_percent:Number(networkForm.marketing_fee_percent||0)},authConfig());setMessage('A franchise hálózat létrejött.');setNetworkForm({code:'',name:'',owner_legal_name:'',royalty_percent:'0',marketing_fee_percent:'0'});await load()}catch(e:any){setError(e?.response?.data?.error||'A franchise hálózat nem hozható létre.')}finally{setSaving(false)}};
 const assignLocation=async(e:React.FormEvent)=>{e.preventDefault();if(!memberForm.network_id||!memberForm.location_id)return;setSaving(true);setError('');setMessage('');try{await axios.post(`${API_BASE}/saas/franchise-networks/${memberForm.network_id}/members`,{location_id:memberForm.location_id,member_type:memberForm.member_type},authConfig());setMessage('A telephely franchise-besorolása frissült.');await load()}catch(e:any){setError(e?.response?.data?.error||'A telephely nem rendelhető a hálózathoz.')}finally{setSaving(false)}};
 const subscriptionAction=async(action:'change-plan'|'cancel'|'reactivate')=>{setPendingAction(action);setError('');setMessage('');try{if(action==='change-plan'){if(!selectedPlan)return;await axios.post(`${API_BASE}/saas/subscription/change-plan`,{plan_code:selectedPlan},authConfig());setMessage('Az előfizetési csomag frissült.')}else if(action==='cancel'){await axios.post(`${API_BASE}/saas/subscription/cancel`,{at_period_end:true},authConfig());setMessage('A lemondás az aktuális előfizetési időszak végére beütemezve.')}else{await axios.post(`${API_BASE}/saas/subscription/reactivate`,{},authConfig());setMessage('Az előfizetés újraaktiválása megtörtént.')}await load()}catch(e:any){setError(e?.response?.data?.error||'Az előfizetési művelet nem sikerült.')}finally{setPendingAction('')}};
 if(loading)return <div className="saas-admin-page"><div className="saas-loading"><RefreshCw size={20}/> SaaS / Franchise központ betöltése…</div></div>;
 return <div className="saas-admin-page">
  <div className="saas-header"><div><span className="saas-eyebrow"><Sparkles size={15}/> SaaS PLATFORM</span><h1>SaaS / Franchise központ</h1><p>Tenant, előfizetés, számlázás, telephelyek és franchise hálózat központi kezelése.</p></div><button type="button" className="saas-refresh" onClick={()=>void load()}><RefreshCw size={16}/>Frissítés</button></div>
  {error&&<div className="saas-alert is-error">{error}</div>}{message&&<div className="saas-alert is-success">{message}</div>}
  <section className="saas-tenant-card"><div><small>Aktív tenant</small><h2>{context?.name||'—'}</h2><p>{context?.legal_name||context?.slug||''}</p></div><div className="saas-badges"><span>{statusText(context?.status)}</span><span>{context?.plan_name||context?.plan_code||'Nincs csomag'}</span><span className={`status-${subscription?.status||context?.subscription_status||'unknown'}`}>{statusText(subscription?.status||context?.subscription_status)}</span></div></section>
  <div className="saas-kpis"><article><Building2/><div><strong>{locations.length}</strong><span>Telephely</span></div></article><article><Network/><div><strong>{networks.length}</strong><span>Franchise hálózat</span></div></article><article><Store/><div><strong>{franchiseLocations}</strong><span>Franchise szalon</span></div></article><article><ShieldCheck/><div><strong>{ownedLocations}</strong><span>Saját szalon</span></div></article></div>

  <section className="saas-panel saas-billing-panel"><div className="saas-panel-title"><div><h3>Előfizetés és számlázás</h3><p>Csomag, státusz, fizetési életciklus és SaaS számlák egy helyen.</p></div><CreditCard size={20}/></div>
   <div className="saas-billing-summary">
    <div><small>Aktuális csomag</small><strong>{subscription?.plan_name||context?.plan_name||'—'}</strong><span>{moneyText(subscription?.monthly_price,subscription?.currency||'HUF')} / hó</span></div>
    <div><small>Előfizetés státusza</small><strong>{statusText(subscription?.status||context?.subscription_status)}</strong><span>{subscription?.cancel_at_period_end?'Lemondás beütemezve':'Folyamatos előfizetés'}</span></div>
    <div><small>Aktuális időszak vége</small><strong>{dateText(subscription?.current_period_end||context?.current_period_end)}</strong><span>{subscription?.grace_period_end?`Türelmi idő: ${dateText(subscription.grace_period_end)}`:'Nincs aktív türelmi idő'}</span></div>
    <div><small>Utolsó fizetés</small><strong>{statusText(subscription?.last_payment_status||context?.last_payment_status||undefined)}</strong><span>{dateText(subscription?.last_payment_at)}</span></div>
   </div>
   {providerManaged&&<div className="saas-provider-note"><ShieldCheck size={17}/><span>Külső szolgáltató által kezelt előfizetés: {subscription?.billing_provider||'provider'}. A közvetlen csomagmódosítás és lemondás biztonsági okból le van tiltva a hitelesített provider-adapterig.</span></div>}
   <div className="saas-subscription-actions"><label>Csomagváltás<select value={selectedPlan} onChange={e=>setSelectedPlan(e.target.value)} disabled={!canManageSubscription||providerManaged||Boolean(pendingAction)}>{PLAN_OPTIONS.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select></label><button type="button" onClick={()=>void subscriptionAction('change-plan')} disabled={!canManageSubscription||providerManaged||!selectedPlan||selectedPlan===subscription?.plan_code||Boolean(pendingAction)}><CreditCard size={16}/>{pendingAction==='change-plan'?'Mentés…':'Csomag váltása'}</button>{subscription?.cancel_at_period_end||subscription?.status==='cancelled'?<button type="button" className="is-secondary" onClick={()=>void subscriptionAction('reactivate')} disabled={!canManageSubscription||providerManaged||Boolean(pendingAction)}><RotateCcw size={16}/>{pendingAction==='reactivate'?'Mentés…':'Előfizetés visszaaktiválása'}</button>:<button type="button" className="is-danger-soft" onClick={()=>void subscriptionAction('cancel')} disabled={!canManageSubscription||providerManaged||Boolean(pendingAction)}><CalendarClock size={16}/>{pendingAction==='cancel'?'Mentés…':'Lemondás az időszak végén'}</button>}</div>
   <div className="saas-billing-grid">
    <div><div className="saas-subheading"><ReceiptText size={17}/><b>SaaS számlatörténet</b></div><div className="saas-table-wrap"><table><thead><tr><th>Időszak</th><th>Bruttó</th><th>Státusz</th><th>Esedékes</th></tr></thead><tbody>{invoices.length?invoices.map(i=><tr key={i.id}><td>{dateText(i.period_start)} – {dateText(i.period_end)}</td><td>{moneyText(i.gross_amount,i.currency||'HUF')}</td><td><span className={`saas-status-pill status-${i.status||'unknown'}`}>{statusText(i.status)}</span></td><td>{dateText(i.due_at)}</td></tr>):<tr><td colSpan={4}>Még nincs SaaS számla.</td></tr>}</tbody></table></div></div>
    <div><div className="saas-subheading"><CalendarClock size={17}/><b>Előfizetési események</b></div><div className="saas-event-list">{events.length?events.slice(0,8).map(ev=><div key={ev.id}><span><b>{ev.event_type.replaceAll('_',' ')}</b><small>{ev.source||'system'}</small></span><time>{dateText(ev.created_at)}</time></div>):<p>Még nincs előfizetési esemény.</p>}</div></div>
   </div>
  </section>

  <div className="saas-grid">
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Modulok és white-label</h3><p>A csomag által engedélyezett rendszerfunkciók.</p></div><ShieldCheck size={20}/></div><div className="saas-feature-grid">{(context?.plan_features?.all_modules||subscription?.features?.all_modules)&&<span className="is-enabled">Minden modul engedélyezve</span>}{features.map(([key,enabled])=><span key={key} className={enabled?'is-enabled':'is-disabled'}>{key.replaceAll('_',' ')} · {enabled?'ON':'OFF'}</span>)}</div><div className="saas-meta"><div><small>Alkalmazásnév</small><b>{context?.app_name||'Kleoszalon VIR'}</b></div><div><small>Egyedi domain</small><b>{context?.custom_domain||'Nincs beállítva'}</b></div></div></section>
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Franchise pénzügyi összesítő</h3><p>Szerződéses díjráták a hálózati beállítások alapján.</p></div><BadgeDollarSign size={20}/></div><div className="saas-finance-kpis"><div><small>Franchise egység</small><strong>{feeStats.franchiseCount}</strong></div><div><small>Súlyozott royalty</small><strong>{feeStats.royalty.toFixed(2)}%</strong></div><div><small>Súlyozott marketingdíj</small><strong>{feeStats.marketing.toFixed(2)}%</strong></div><div><small>Összes díjráta</small><strong>{(feeStats.royalty+feeStats.marketing).toFixed(2)}%</strong></div></div><div className="saas-finance-note">A százalékos összesítő nem könyvel tényleges royalty-bevételt. Pénzösszeg akkor számítható auditálhatóan, amikor a franchise árbevételi alap telephelyenként a pénzügyi ledgerhez lesz kötve.</div></section>
  </div>

  <div className="saas-grid">
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Új franchise hálózat</h3><p>Royalty és marketingdíj alapértékekkel.</p></div><Network size={20}/></div><form className="saas-form" onSubmit={createNetwork}><label>Kód<input value={networkForm.code} onChange={e=>setNetworkForm(v=>({...v,code:e.target.value}))} placeholder="kleopatra-hu" required/></label><label>Név<input value={networkForm.name} onChange={e=>setNetworkForm(v=>({...v,name:e.target.value}))} placeholder="Kleopátra Franchise Magyarország" required/></label><label>Tulajdonos / jogi név<input value={networkForm.owner_legal_name} onChange={e=>setNetworkForm(v=>({...v,owner_legal_name:e.target.value}))}/></label><div className="saas-form-row"><label>Royalty %<input type="number" min="0" max="100" step="0.01" value={networkForm.royalty_percent} onChange={e=>setNetworkForm(v=>({...v,royalty_percent:e.target.value}))}/></label><label>Marketingdíj %<input type="number" min="0" max="100" step="0.01" value={networkForm.marketing_fee_percent} onChange={e=>setNetworkForm(v=>({...v,marketing_fee_percent:e.target.value}))}/></label></div><button disabled={saving} type="submit">Hálózat létrehozása</button></form></section>
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Telephely hálózathoz rendelése</h3><p>A besorolás később módosítható ugyanitt.</p></div><Store size={20}/></div><form className="saas-form" onSubmit={assignLocation}><label>Franchise hálózat<select required value={memberForm.network_id} onChange={e=>setMemberForm(v=>({...v,network_id:e.target.value}))}><option value="">Válassz hálózatot…</option>{networks.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Telephely<select required value={memberForm.location_id} onChange={e=>setMemberForm(v=>({...v,location_id:e.target.value}))}><option value="">Válassz telephelyet…</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}{l.city?` · ${l.city}`:''}</option>)}</select></label><label>Besorolás<select value={memberForm.member_type} onChange={e=>setMemberForm(v=>({...v,member_type:e.target.value}))}><option value="franchise">Franchise partner</option><option value="owned">Saját tulajdonú szalon</option></select></label><button disabled={saving||!networks.length} type="submit">Besorolás mentése</button></form></section>
  </div>
  <section className="saas-panel"><div className="saas-panel-title"><div><h3>Franchise hálózatok</h3><p>Központi hálózati és díjparaméterek.</p></div><Users size={20}/></div><div className="saas-table-wrap"><table><thead><tr><th>Hálózat</th><th>Tagok</th><th>Saját</th><th>Franchise</th><th>Royalty</th><th>Marketing</th><th>Összes díj</th></tr></thead><tbody>{networks.length?networks.map(n=><tr key={n.id}><td><b>{n.name}</b><small>{n.code}</small></td><td>{n.member_count||0}</td><td>{n.owned_location_count||0}</td><td>{n.franchise_location_count||0}</td><td>{Number(n.royalty_percent||0).toFixed(2)}%</td><td>{Number(n.marketing_fee_percent||0).toFixed(2)}%</td><td><b>{(Number(n.royalty_percent||0)+Number(n.marketing_fee_percent||0)).toFixed(2)}%</b></td></tr>):<tr><td colSpan={7}>Még nincs franchise hálózat.</td></tr>}</tbody></table></div></section>
  <section className="saas-panel"><div className="saas-panel-title"><div><h3>Telephelyek</h3><p>Saját és franchise besorolás tenanton belül.</p></div><Building2 size={20}/></div><div className="saas-location-list">{locations.map(l=><div key={l.id}><span><b>{l.name}</b><small>{[l.city,l.address].filter(Boolean).join(' · ')}</small></span><em className={l.member_type?`is-${l.member_type}`:''}>{l.member_type==='owned'?'Saját':l.member_type==='franchise'?'Franchise':'Nincs besorolva'}{l.franchise_network_name?` · ${l.franchise_network_name}`:''}</em></div>)}</div></section>
 </div>;
}
