import React,{useCallback,useEffect,useMemo,useState}from"react";
import axios from"axios";
import{BadgePercent,CircleDollarSign,CreditCard,ExternalLink,RefreshCw,ShieldCheck,TriangleAlert}from"lucide-react";
import"./SaasRevenueEnginePanel.css";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const authConfig=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
type CatalogPlan={code:string;name:string;monthly_price:number|string;annual_price:number|string;onboarding_fee:number|string;currency:string;max_locations?:number|null;max_users?:number|null;trial_days:number;recommended:boolean;booking_commission_percent:number|string;addons?:Record<string,number>};
type RevenueSummary={provider?:{configured:boolean;mode:string;tax_configured:boolean;webhook_verification?:string};subscription?:{status?:string;billing_provider?:string|null;billing_interval?:string;plan_code?:string;plan_name?:string;monthly_price?:number|string;annual_price?:number|string;currency?:string;grace_period_end?:string|null;next_retry_at?:string|null;dunning_step?:number;payment_method_status?:string|null;last_payment_status?:string|null;last_payment_at?:string|null;external_customer_id?:string|null};invoices?:Array<{id:string;status?:string;gross_amount?:number|string;currency?:string;paid_at?:string|null;due_at?:string|null}>};
const money=(v:any,c='HUF')=>new Intl.NumberFormat('hu-HU',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(v||0));
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('hu-HU',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';

export default function SaasRevenueEnginePanel(){
 const[catalog,setCatalog]=useState<CatalogPlan[]>([]),[summary,setSummary]=useState<RevenueSummary|null>(null),[plan,setPlan]=useState('pro'),[interval,setInterval]=useState<'month'|'year'>('month'),[coupon,setCoupon]=useState(''),[couponInfo,setCouponInfo]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[c,s]=await Promise.all([axios.get(`${API_BASE}/saas/revenue/catalog`,authConfig()),axios.get(`${API_BASE}/saas/revenue/summary`,authConfig())]);const rows=Array.isArray(c.data?.rows)?c.data.rows:[];setCatalog(rows);setSummary(s.data||null);const current=String(s.data?.subscription?.plan_code||'');if(current&&current!=='internal')setPlan(current);else if(rows.some((x:CatalogPlan)=>x.code==='pro'))setPlan('pro')}catch(e:any){setError(e?.response?.data?.error||e?.message||'A Revenue Engine nem tölthető be.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const selected=useMemo(()=>catalog.find(x=>x.code===plan)||catalog[0],[catalog,plan]);
 const validateCoupon=async()=>{if(!coupon.trim()||!plan)return;setBusy(true);setCouponInfo('');setError('');try{const r=await axios.post(`${API_BASE}/saas/revenue/coupons/validate`,{code:coupon.trim(),plan_code:plan},authConfig());setCouponInfo(`${r.data?.coupon?.percent_off||0}% kedvezmény elfogadva`)}catch(e:any){setError(e?.response?.data?.error||'A kupon nem érvényes.')}finally{setBusy(false)}};
 const checkout=async()=>{if(!plan)return;setBusy(true);setError('');try{const r=await axios.post(`${API_BASE}/saas/revenue/checkout`,{plan_code:plan,billing_interval:interval,coupon_code:coupon.trim()||undefined},authConfig());if(r.data?.url)window.location.assign(r.data.url);else throw new Error('A fizetési URL nem érkezett meg.')}catch(e:any){setError(e?.response?.data?.error||e?.message||'A fizetés nem indítható.');setBusy(false)}};
 const portal=async()=>{setBusy(true);setError('');try{const r=await axios.post(`${API_BASE}/saas/revenue/portal`,{},authConfig());if(r.data?.url)window.location.assign(r.data.url);else throw new Error('A billing portal URL nem érkezett meg.')}catch(e:any){setError(e?.response?.data?.error||e?.message||'A számlázási portál nem nyitható meg.');setBusy(false)}};
 if(loading)return <section className="revenue-engine-card"><div className="revenue-loading"><RefreshCw size={18}/> Revenue Engine betöltése…</div></section>;
 const provider=summary?.provider,sub=summary?.subscription,failed=sub?.status==='past_due'||sub?.status==='suspended';
 return <section className="revenue-engine-card">
  <div className="revenue-head"><div><span><CircleDollarSign size={17}/> SAAS REVENUE ENGINE v16</span><h2>Előfizetésből automatikus bevétel</h2><p>Checkout, ismétlődő terhelés, invoice-szinkron, grace period, dunning és billing portal egy kontrollrétegben.</p></div><button type="button" onClick={()=>void load()}><RefreshCw size={16}/>Frissítés</button></div>
  {error&&<div className="revenue-alert error">{error}</div>}
  <div className="revenue-readiness">
   <div><ShieldCheck size={19}/><span><small>Provider</small><b>Stripe · {provider?.configured?'KÉSZ':'NINCS KONFIGURÁLVA'}</b></span></div>
   <div><CreditCard size={19}/><span><small>Mód</small><b>{String(provider?.mode||'unknown').toUpperCase()}</b></span></div>
   <div className={provider?.tax_configured?'':'warn'}><BadgePercent size={19}/><span><small>Adó konfiguráció</small><b>{provider?.tax_configured?'KÉSZ':'HIÁNYZIK'}</b></span></div>
   <div className={failed?'warn':''}><TriangleAlert size={19}/><span><small>Dunning</small><b>{failed?`LÉPÉS ${sub?.dunning_step||0}`:'RENDBEN'}</b></span></div>
  </div>
  <div className="revenue-grid">
   <div className="revenue-builder"><h3>Új / első fizetős előfizetés</h3><div className="revenue-form"><label>Csomag<select value={plan} onChange={e=>setPlan(e.target.value)}>{catalog.map(p=><option key={p.code} value={p.code}>{p.name}{p.recommended?' · ajánlott':''}</option>)}</select></label><label>Számlázás<select value={interval} onChange={e=>setInterval(e.target.value as 'month'|'year')}><option value="month">Havi</option><option value="year">Éves</option></select></label><label>Kupon<div className="coupon-row"><input value={coupon} onChange={e=>{setCoupon(e.target.value.toUpperCase());setCouponInfo('')}} placeholder="pl. START20"/><button type="button" onClick={()=>void validateCoupon()} disabled={busy||!coupon.trim()}>Ellenőrzés</button></div></label></div>{couponInfo&&<div className="coupon-ok">{couponInfo}</div>}{selected&&<div className="price-preview"><strong>{money(interval==='year'?selected.annual_price:selected.monthly_price,selected.currency||'HUF')}</strong><span>{interval==='year'?'/ év':'/ hó'} · 0% foglalási jutalék · {selected.max_locations??'∞'} telephely · {selected.max_users??'∞'} felhasználó</span></div>}<button className="primary-pay" type="button" onClick={()=>void checkout()} disabled={busy||!provider?.configured||!provider?.tax_configured}><CreditCard size={17}/>{busy?'Feldolgozás…':'Stripe Checkout indítása'}</button></div>
   <div className="revenue-state"><h3>Aktuális billing állapot</h3><dl><div><dt>Csomag</dt><dd>{sub?.plan_name||sub?.plan_code||'—'}</dd></div><div><dt>Státusz</dt><dd>{sub?.status||'—'}</dd></div><div><dt>Intervallum</dt><dd>{sub?.billing_interval==='year'?'Éves':'Havi'}</dd></div><div><dt>Utolsó fizetés</dt><dd>{sub?.last_payment_status||'—'} · {date(sub?.last_payment_at)}</dd></div><div><dt>Grace period vége</dt><dd>{date(sub?.grace_period_end)}</dd></div><div><dt>Következő retry</dt><dd>{date(sub?.next_retry_at)}</dd></div><div><dt>Fizetési mód</dt><dd>{sub?.payment_method_status||'—'}</dd></div></dl><button type="button" className="portal" onClick={()=>void portal()} disabled={busy||!sub?.external_customer_id}><ExternalLink size={16}/>Billing portal megnyitása</button></div>
  </div>
  <div className="revenue-foot"><b>Fail-closed működés:</b> productionben checkout csak konfigurált providerrel és adózási beállítással indulhat. Fizetési hiba után a hozzáférés grace periodban marad, majd szabályozottan felfüggeszthető; sikeres invoice automatikusan visszaállítja az aktív állapotot.</div>
 </section>;
}
