import React,{useCallback,useEffect,useMemo,useState}from"react";
import axios from"axios";
import{Building2,Network,RefreshCw,ShieldCheck,Sparkles,Store,Users}from"lucide-react";
import"./SaasFranchiseAdminPage.css";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const authConfig=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};

type TenantContext={tenant_id?:string;slug?:string;name?:string;legal_name?:string;status?:string;plan_code?:string;plan_name?:string;plan_features?:Record<string,boolean>;subscription_status?:string;current_period_end?:string|null;app_name?:string|null;logo_url?:string|null;custom_domain?:string|null};
type LocationRow={id:string;name:string;city?:string|null;address?:string|null;is_active?:boolean;franchise_network_id?:number|null;franchise_network_name?:string|null;member_type?:'owned'|'franchise'|null};
type NetworkRow={id:number;code:string;name:string;owner_legal_name?:string|null;royalty_percent?:number|string;marketing_fee_percent?:number|string;member_count?:number;owned_location_count?:number;franchise_location_count?:number;active?:boolean};

export default function SaasFranchiseAdminPage(){
 const[context,setContext]=useState<TenantContext|null>(null),[locations,setLocations]=useState<LocationRow[]>([]),[networks,setNetworks]=useState<NetworkRow[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const[networkForm,setNetworkForm]=useState({code:'',name:'',owner_legal_name:'',royalty_percent:'0',marketing_fee_percent:'0'});
 const[memberForm,setMemberForm]=useState({network_id:'',location_id:'',member_type:'franchise'});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const cfg=authConfig();const[c,l,n]=await Promise.all([axios.get(`${API_BASE}/saas/context`,cfg),axios.get(`${API_BASE}/saas/locations`,cfg),axios.get(`${API_BASE}/saas/franchise-networks`,cfg)]);setContext(c.data?.tenant||null);setLocations(Array.isArray(l.data?.rows)?l.data.rows:[]);setNetworks(Array.isArray(n.data?.rows)?n.data.rows:[])}catch(e:any){setError(e?.response?.data?.error||e?.message||'A SaaS adatok betöltése nem sikerült.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const features=useMemo(()=>Object.entries(context?.plan_features||{}).filter(([k])=>k!=='all_modules'),[context]);
 const franchiseLocations=locations.filter(x=>x.member_type==='franchise').length,ownedLocations=locations.filter(x=>x.member_type==='owned').length;
 const createNetwork=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{await axios.post(`${API_BASE}/saas/franchise-networks`,{...networkForm,royalty_percent:Number(networkForm.royalty_percent||0),marketing_fee_percent:Number(networkForm.marketing_fee_percent||0)},authConfig());setMessage('A franchise hálózat létrejött.');setNetworkForm({code:'',name:'',owner_legal_name:'',royalty_percent:'0',marketing_fee_percent:'0'});await load()}catch(e:any){setError(e?.response?.data?.error||'A franchise hálózat nem hozható létre.')}finally{setSaving(false)}};
 const assignLocation=async(e:React.FormEvent)=>{e.preventDefault();if(!memberForm.network_id||!memberForm.location_id)return;setSaving(true);setError('');setMessage('');try{await axios.post(`${API_BASE}/saas/franchise-networks/${memberForm.network_id}/members`,{location_id:memberForm.location_id,member_type:memberForm.member_type},authConfig());setMessage('A telephely franchise-besorolása frissült.');await load()}catch(e:any){setError(e?.response?.data?.error||'A telephely nem rendelhető a hálózathoz.')}finally{setSaving(false)}};
 if(loading)return <div className="saas-admin-page"><div className="saas-loading"><RefreshCw size={20}/> SaaS / Franchise központ betöltése…</div></div>;
 return <div className="saas-admin-page">
  <div className="saas-header"><div><span className="saas-eyebrow"><Sparkles size={15}/> SaaS PLATFORM</span><h1>SaaS / Franchise központ</h1><p>Tenant, előfizetés, telephelyek és franchise hálózat központi kezelése.</p></div><button type="button" className="saas-refresh" onClick={()=>void load()}><RefreshCw size={16}/>Frissítés</button></div>
  {error&&<div className="saas-alert is-error">{error}</div>}{message&&<div className="saas-alert is-success">{message}</div>}
  <section className="saas-tenant-card"><div><small>Aktív tenant</small><h2>{context?.name||'—'}</h2><p>{context?.legal_name||context?.slug||''}</p></div><div className="saas-badges"><span>{context?.status||'—'}</span><span>{context?.plan_name||context?.plan_code||'Nincs csomag'}</span><span>{context?.subscription_status||'—'}</span></div></section>
  <div className="saas-kpis"><article><Building2/><div><strong>{locations.length}</strong><span>Telephely</span></div></article><article><Network/><div><strong>{networks.length}</strong><span>Franchise hálózat</span></div></article><article><Store/><div><strong>{franchiseLocations}</strong><span>Franchise szalon</span></div></article><article><ShieldCheck/><div><strong>{ownedLocations}</strong><span>Saját szalon</span></div></article></div>
  <div className="saas-grid">
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Előfizetés és modulok</h3><p>A csomag által engedélyezett rendszerfunkciók.</p></div><ShieldCheck size={20}/></div><div className="saas-feature-grid">{context?.plan_features?.all_modules&&<span className="is-enabled">Minden modul engedélyezve</span>}{features.map(([key,enabled])=><span key={key} className={enabled?'is-enabled':'is-disabled'}>{key.replaceAll('_',' ')} · {enabled?'ON':'OFF'}</span>)}</div><div className="saas-meta"><div><small>Alkalmazásnév</small><b>{context?.app_name||'Kleoszalon VIR'}</b></div><div><small>Egyedi domain</small><b>{context?.custom_domain||'Nincs beállítva'}</b></div></div></section>
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Új franchise hálózat</h3><p>Royalty és marketingdíj alapértékekkel.</p></div><Network size={20}/></div><form className="saas-form" onSubmit={createNetwork}><label>Kód<input value={networkForm.code} onChange={e=>setNetworkForm(v=>({...v,code:e.target.value}))} placeholder="kleopatra-hu" required/></label><label>Név<input value={networkForm.name} onChange={e=>setNetworkForm(v=>({...v,name:e.target.value}))} placeholder="Kleopátra Franchise Magyarország" required/></label><label>Tulajdonos / jogi név<input value={networkForm.owner_legal_name} onChange={e=>setNetworkForm(v=>({...v,owner_legal_name:e.target.value}))}/></label><div className="saas-form-row"><label>Royalty %<input type="number" min="0" max="100" step="0.01" value={networkForm.royalty_percent} onChange={e=>setNetworkForm(v=>({...v,royalty_percent:e.target.value}))}/></label><label>Marketingdíj %<input type="number" min="0" max="100" step="0.01" value={networkForm.marketing_fee_percent} onChange={e=>setNetworkForm(v=>({...v,marketing_fee_percent:e.target.value}))}/></label></div><button disabled={saving} type="submit">Hálózat létrehozása</button></form></section>
  </div>
  <section className="saas-panel"><div className="saas-panel-title"><div><h3>Franchise hálózatok</h3><p>Központi hálózati és díjparaméterek.</p></div><Users size={20}/></div><div className="saas-table-wrap"><table><thead><tr><th>Hálózat</th><th>Tagok</th><th>Saját</th><th>Franchise</th><th>Royalty</th><th>Marketing</th></tr></thead><tbody>{networks.length?networks.map(n=><tr key={n.id}><td><b>{n.name}</b><small>{n.code}</small></td><td>{n.member_count||0}</td><td>{n.owned_location_count||0}</td><td>{n.franchise_location_count||0}</td><td>{Number(n.royalty_percent||0).toFixed(2)}%</td><td>{Number(n.marketing_fee_percent||0).toFixed(2)}%</td></tr>):<tr><td colSpan={6}>Még nincs franchise hálózat.</td></tr>}</tbody></table></div></section>
  <div className="saas-grid">
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Telephelyek</h3><p>Saját és franchise besorolás tenanton belül.</p></div><Building2 size={20}/></div><div className="saas-location-list">{locations.map(l=><div key={l.id}><span><b>{l.name}</b><small>{[l.city,l.address].filter(Boolean).join(' · ')}</small></span><em className={l.member_type?`is-${l.member_type}`:''}>{l.member_type==='owned'?'Saját':l.member_type==='franchise'?'Franchise':'Nincs besorolva'}{l.franchise_network_name?` · ${l.franchise_network_name}`:''}</em></div>)}</div></section>
   <section className="saas-panel"><div className="saas-panel-title"><div><h3>Telephely hálózathoz rendelése</h3><p>A besorolás később módosítható ugyanitt.</p></div><Store size={20}/></div><form className="saas-form" onSubmit={assignLocation}><label>Franchise hálózat<select required value={memberForm.network_id} onChange={e=>setMemberForm(v=>({...v,network_id:e.target.value}))}><option value="">Válassz hálózatot…</option>{networks.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Telephely<select required value={memberForm.location_id} onChange={e=>setMemberForm(v=>({...v,location_id:e.target.value}))}><option value="">Válassz telephelyet…</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}{l.city?` · ${l.city}`:''}</option>)}</select></label><label>Besorolás<select value={memberForm.member_type} onChange={e=>setMemberForm(v=>({...v,member_type:e.target.value}))}><option value="franchise">Franchise partner</option><option value="owned">Saját tulajdonú szalon</option></select></label><button disabled={saving||!networks.length} type="submit">Besorolás mentése</button></form></section>
  </div>
 </div>;
}
