import React, { useEffect, useMemo, useState } from "react";
import { Building2, ChevronDown, ChevronRight, Clock3, Plus, Search, SlidersHorizontal, Tag, X, Save, CalendarDays, Settings2, UsersRound } from "lucide-react";
import withBase from "../utils/apiBase";
import ServiceNewModal from "../components/ServiceNewModal";
import { useLanguage } from "../i18n/LanguageProvider";

type LocationRef = { id: string; name: string };
type Service = {
  id: string; name: string; code?: string | null; service_type_id?: string | null; service_type_name?: string | null;
  list_price?: number | null; base_price?: number | null; duration_minutes?: number | null; is_active?: boolean | null;
  online_bookable?: boolean | null; locations?: LocationRef[]; description_short?: string|null; receipt_name?:string|null; online_name?:string|null;
};
type ServiceType = { id: string; name: string };

const token = () => localStorage.getItem("kleo_token") || localStorage.getItem("token") || "";
const headers = () => token() ? { Authorization: `Bearer ${token()}` } : undefined;
const money = (v: number | null | undefined, locale:string) => v == null ? "—" : `${Number(v).toLocaleString(locale)} Ft`;

export default function ServicesCatalogPage() {
  const {language,locale,t}=useLanguage();
  const text=(hu:string,en:string)=>language==="en"?en:hu;
  const [services,setServices]=useState<Service[]>([]); const [types,setTypes]=useState<ServiceType[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [name,setName]=useState(""); const [typeId,setTypeId]=useState(""); const [salonId,setSalonId]=useState("");
  const [minPrice,setMinPrice]=useState(""); const [maxPrice,setMaxPrice]=useState(""); const [minTime,setMinTime]=useState(""); const [maxTime,setMaxTime]=useState("");
  const [includeInactive,setIncludeInactive]=useState(false); const [expanded,setExpanded]=useState<Record<string,boolean>>({});
  const [newOpen,setNewOpen]=useState(false); const [selected,setSelected]=useState<Service|null>(null);

  const load=async()=>{ try { setLoading(true); setError(""); const [s,typeResponse]=await Promise.all([
      fetch(withBase(`services${includeInactive?"?include_inactive=1":""}`),{headers:headers()}),
      fetch(withBase("service-types"),{headers:headers()})]);
    if(!s.ok) throw new Error(`${text("Szolgáltatások","Services")}: HTTP ${s.status}`); const sd=await s.json(); const td=typeResponse.ok?await typeResponse.json():[];
    setServices(Array.isArray(sd)?sd:[]); setTypes(Array.isArray(td)?td:[]);
  } catch(e:any){setError(e?.message||text("A szolgáltatások betöltése nem sikerült.","Services could not be loaded."));} finally{setLoading(false);} };
  useEffect(()=>{void load();},[includeInactive]);

  const salons=useMemo(()=>{ const map=new Map<string,string>(); services.forEach(s=>(s.locations||[]).forEach(l=>map.set(String(l.id),l.name))); return Array.from(map.entries()).map(([id,name])=>({id,name})).sort((a,b)=>a.name.localeCompare(b.name,locale)); },[services,locale]);
  const filtered=useMemo(()=>services.filter(s=>{ const q=name.trim().toLocaleLowerCase(locale); const price=Number(s.list_price??s.base_price??0); const time=Number(s.duration_minutes??0);
    if(q&&!`${s.name} ${s.code||""} ${s.service_type_name||""}`.toLocaleLowerCase(locale).includes(q))return false;
    if(typeId&&String(s.service_type_id)!==typeId)return false; if(salonId&&!(s.locations||[]).some(l=>String(l.id)===salonId))return false;
    if(minPrice&&price<Number(minPrice))return false; if(maxPrice&&price>Number(maxPrice))return false; if(minTime&&time<Number(minTime))return false; if(maxTime&&time>Number(maxTime))return false; return true;
  }),[services,name,typeId,salonId,minPrice,maxPrice,minTime,maxTime,locale]);
  const grouped=useMemo(()=>{ const order=new Map(types.map((typeItem,i)=>[String(typeItem.id),i])); const m=new Map<string,{id:string;name:string;items:Service[]}>(); filtered.forEach(s=>{const key=String(s.service_type_id||"none");if(!m.has(key))m.set(key,{id:key,name:s.service_type_name||text("Egyéb / kategória nélkül","Other / uncategorized"),items:[]});m.get(key)!.items.push(s);}); return Array.from(m.values()).sort((a,b)=>(order.get(a.id)??9999)-(order.get(b.id)??9999)||a.name.localeCompare(b.name,locale)); },[filtered,types,locale,language]);
  const reset=()=>{setName("");setTypeId("");setSalonId("");setMinPrice("");setMaxPrice("");setMinTime("");setMaxTime("");};

  return <div style={{padding:"18px 22px 36px",maxWidth:1680,margin:"0 auto"}}>
    <section style={{background:"#fff",border:"1px solid #eee8de",borderRadius:18,boxShadow:"0 12px 34px rgba(45,34,21,.06)",overflow:"hidden"}}>
      <div style={{padding:"22px 24px 16px",display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",borderBottom:"1px solid #f0ece5"}}>
        <div><div style={{fontSize:12,fontWeight:800,letterSpacing:".08em",textTransform:"uppercase",color:"#9b7c43"}}>{text("Törzsadatok","Master data")}</div><h1 style={{margin:"5px 0 4px",fontSize:26,color:"#211b16"}}>{text("Szolgáltatások","Services")}</h1><p style={{margin:0,color:"#756d64",fontSize:13}}>{text("Kategóriahierarchia, árak, időtartamok és szalon-hozzárendelések egy helyen.","Category hierarchy, prices, durations and salon assignments in one place.")}</p></div>
        <div style={{display:"flex",gap:10}}><button onClick={()=>setIncludeInactive(v=>!v)} style={secondaryBtn}>{includeInactive?text("Csak aktív","Active only"):text("Inaktívak is","Include inactive")}</button><button onClick={()=>setNewOpen(true)} style={primaryBtn}><Plus size={16}/>{text("Új szolgáltatás","New service")}</button></div>
      </div>
      <div style={{padding:"16px 20px 18px",background:"linear-gradient(180deg,#fff,#fcfaf6)",borderBottom:"1px solid #eee8de"}}>
        <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12,color:"#6b5b48",fontWeight:800,fontSize:13}}><SlidersHorizontal size={16}/>{t("common.filter")}</div>
        <div style={{display:"grid",gridTemplateColumns:"minmax(260px,1.8fr) minmax(180px,1fr) minmax(200px,1fr) 130px 130px 120px 120px auto",gap:10,alignItems:"end"}}>
          <Field label={text("Név / kód","Name / code")}><div style={inputWrap}><Search size={15}/><input style={input} value={name} onChange={e=>setName(e.target.value)} placeholder={text("pl. géllakk, hajvágás…","e.g. gel polish, haircut…")}/></div></Field>
          <Field label={text("Kategória","Category")}><select style={select} value={typeId} onChange={e=>setTypeId(e.target.value)}><option value="">{text("Összes kategória","All categories")}</option>{types.map(typeItem=><option key={typeItem.id} value={typeItem.id}>{typeItem.name}</option>)}</select></Field>
          <Field label={text("Szalon","Salon")}><div style={inputWrap}><Building2 size={15}/><select style={{...select,border:0,padding:0,boxShadow:"none",background:"transparent"}} value={salonId} onChange={e=>setSalonId(e.target.value)}><option value="">{text("Minden szalon","All salons")}</option>{salons.map(salon=><option key={salon.id} value={salon.id}>{salon.name}</option>)}</select></div></Field>
          <Field label={text("Min. ár","Min. price")}><input style={inputBare} type="number" min={0} value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="Ft"/></Field><Field label={text("Max. ár","Max. price")}><input style={inputBare} type="number" min={0} value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Ft"/></Field>
          <Field label={text("Min. idő","Min. time")}><input style={inputBare} type="number" min={0} value={minTime} onChange={e=>setMinTime(e.target.value)} placeholder={text("perc","min")}/></Field><Field label={text("Max. idő","Max. time")}><input style={inputBare} type="number" min={0} value={maxTime} onChange={e=>setMaxTime(e.target.value)} placeholder={text("perc","min")}/></Field><button onClick={reset} style={{...secondaryBtn,height:38}}>{t("common.reset")}</button>
        </div>
      </div>
      <div style={{padding:"12px 20px 6px",display:"flex",justifyContent:"space-between",alignItems:"center",color:"#756d64",fontSize:12}}><span><b style={{color:"#211b16"}}>{filtered.length}</b> {text("szolgáltatás","services")} · <b style={{color:"#211b16"}}>{grouped.length}</b> {text("kategória","categories")}</span><span>{text("Kattints egy szolgáltatásra a szerkesztéshez","Click a service to edit it")}</span></div>
      {error&&<div style={{margin:20,padding:"12px 14px",borderRadius:10,background:"#fff0f0",color:"#9c2d2d",fontWeight:700}}>{error}</div>}
      {loading?<div style={{padding:30,color:"#756d64"}}>{text("Szolgáltatások betöltése…","Loading services…")}</div>:<div style={{padding:"4px 14px 18px"}}>{grouped.map(g=>{const open=expanded[g.id]===true;return <div key={g.id} style={{border:"1px solid #eee8de",borderRadius:12,margin:"8px 0",overflow:"hidden",background:"#fff"}}>
        <button onClick={()=>setExpanded(p=>({...p,[g.id]:!open}))} style={{width:"100%",border:0,background:"#fbfaf7",padding:"13px 15px",display:"flex",alignItems:"center",gap:10,cursor:"pointer",textAlign:"left"}}>{open?<ChevronDown size={17}/>:<ChevronRight size={17}/>}<strong style={{fontSize:14,flex:1,color:"#2a221a"}}>{g.name}</strong><span style={{fontSize:11,fontWeight:800,color:"#9b7c43",background:"#f4eddf",padding:"4px 8px",borderRadius:999}}>{g.items.length} {text("szolgáltatás","services")}</span></button>
        {open&&<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr><Th>{text("Név","Name")}</Th><Th>{text("Kód","Code")}</Th><Th>{text("Ár","Price")}</Th><Th>{text("Időtartam","Duration")}</Th><Th>{text("Szalon","Salon")}</Th><Th>Online</Th><Th>{text("Állapot","Status")}</Th></tr></thead><tbody>{g.items.map(s=><tr key={s.id} onClick={()=>setSelected(s)} style={{borderTop:"1px solid #f1ede6",cursor:"pointer"}} onMouseEnter={e=>(e.currentTarget.style.background="#fffdf8")} onMouseLeave={e=>(e.currentTarget.style.background="transparent")}><Td><div style={{fontWeight:750,color:"#2a221a"}}>{s.name}</div></Td><Td>{s.code||"—"}</Td><Td><span style={{display:"inline-flex",gap:5,alignItems:"center"}}><Tag size={13}/>{money(s.list_price??s.base_price,locale)}</span></Td><Td><span style={{display:"inline-flex",gap:5,alignItems:"center"}}><Clock3 size={13}/>{s.duration_minutes??"—"}{s.duration_minutes!=null?` ${text("perc","min")}`:""}</span></Td><Td>{(s.locations||[]).length?(s.locations||[]).map(l=>l.name).join(", "):text("Hálózat","Network")}</Td><Td>{s.online_bookable===false?text("nem","no"):text("igen","yes")}</Td><Td><span style={{fontWeight:800,color:s.is_active===false?"#9a514b":"#2f7654"}}>{s.is_active===false?t("common.inactive"):t("common.active")}</span></Td></tr>)}</tbody></table></div>}
      </div>})}{!grouped.length&&!error&&<div style={{padding:32,textAlign:"center",color:"#756d64"}}>{text("Nincs találat a megadott szűrőkre.","No results match the selected filters.")}</div>}</div>}
    </section>
    <ServiceNewModal isOpen={newOpen} onRequestClose={()=>setNewOpen(false)} onServiceCreated={()=>{setNewOpen(false);void load();}} />
    {selected&&<ServiceDrawer service={selected} types={types} onClose={()=>setSelected(null)} onSaved={(u)=>{setServices(p=>p.map(s=>s.id===u.id?{...s,...u}:s));setSelected(null);}}/>}
  </div>;
}

function ServiceDrawer({service,types,onClose,onSaved}:{service:Service;types:ServiceType[];onClose:()=>void;onSaved:(s:Service)=>void}){
  const {language,t}=useLanguage(); const text=(hu:string,en:string)=>language==="en"?en:hu;
  const [tab,setTab]=useState<"basic"|"online"|"extra">("basic"); const [saving,setSaving]=useState(false); const [err,setErr]=useState("");
  const [form,setForm]=useState({...service,base_price:service.base_price??service.list_price??0,duration_minutes:service.duration_minutes??30,online_bookable:service.online_bookable!==false,is_active:service.is_active!==false});
  const save=async()=>{try{setSaving(true);setErr("");const res=await fetch(withBase(`services/${service.id}`),{method:"PATCH",headers:{"Content-Type":"application/json",...(headers()||{})},body:JSON.stringify({name:form.name,code:form.code||null,service_type_id:form.service_type_id||null,base_price:Number(form.base_price||0),list_price:Number(form.base_price||0),duration_minutes:Number(form.duration_minutes||1),online_bookable:!!form.online_bookable,is_active:!!form.is_active})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error||`HTTP ${res.status}`);onSaved({...form,...data});}catch(e:any){setErr(e?.message||text("Mentési hiba","Save failed"));}finally{setSaving(false);}};
  return <><div onClick={onClose} style={{position:"fixed",inset:0,background:"rgba(35,28,20,.08)",zIndex:1198}}/><aside style={{position:"fixed",right:0,top:0,bottom:0,width:"min(520px,94vw)",background:"#fff",zIndex:1199,boxShadow:"-18px 0 45px rgba(35,28,20,.16)",display:"flex",flexDirection:"column",borderLeft:"1px solid #e9e4dc"}}>
    <div style={{padding:"18px 20px 12px",borderBottom:"1px solid #ece7df"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12}}><div><h2 style={{margin:0,fontSize:19,color:"#28221d"}}>{form.name}</h2><div style={{marginTop:4,fontSize:11,color:"#9a9084"}}>{text("Szolgáltatás szerkesztése","Edit service")}</div></div><button onClick={onClose} style={iconBtn}><X size={18}/></button></div>
    <div style={{display:"flex",gap:6,marginTop:14,flexWrap:"wrap"}}><Tab active={tab==="basic"} onClick={()=>setTab("basic")} icon={<Settings2 size={13}/>}>{text("Általános beállítások","General settings")}</Tab><Tab active={tab==="online"} onClick={()=>setTab("online")} icon={<CalendarDays size={13}/>}>{text("Online időpontfoglalás","Online booking")}</Tab><Tab active={tab==="extra"} onClick={()=>setTab("extra")} icon={<UsersRound size={13}/>}>{text("További beállítások","Additional settings")}</Tab></div></div>
    <div style={{padding:"18px 20px",overflowY:"auto",flex:1}}>{err&&<div style={{background:"#fff0f0",color:"#9b2c2c",padding:"10px 12px",borderRadius:9,marginBottom:14,fontSize:12,fontWeight:700}}>{err}</div>}
      {tab==="basic"&&<div style={{display:"grid",gap:14}}><DrawerField label={text("Név","Name")}><input style={drawerInput} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></DrawerField><DrawerField label={text("Kategória","Category")}><select style={drawerInput} value={form.service_type_id||""} onChange={e=>setForm({...form,service_type_id:e.target.value})}><option value="">{text("Nincs kategória","No category")}</option>{types.map(typeItem=><option key={typeItem.id} value={typeItem.id}>{typeItem.name}</option>)}</select></DrawerField><DrawerField label={text("Melyik szalonban","Salon assignment")}><div style={readonlyBox}>{(service.locations||[]).length?(service.locations||[]).map(l=>l.name).join(", "):text("Hálózat / minden szalon","Network / all salons")}</div></DrawerField><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><DrawerField label={text("Ár","Price")}><div style={{display:"flex",gap:6}}><input style={drawerInput} type="number" min={0} value={Number(form.base_price||0)} onChange={e=>setForm({...form,base_price:Number(e.target.value)})}/><span style={unit}>Ft</span></div></DrawerField><DrawerField label={text("Időtartam","Duration")}><div style={{display:"flex",gap:6}}><input style={drawerInput} type="number" min={1} value={Number(form.duration_minutes||1)} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})}/><span style={unit}>{text("perc","min")}</span></div></DrawerField></div><DrawerField label={text("Kód / API azonosító","Code / API identifier")}><input style={drawerInput} value={form.code||""} onChange={e=>setForm({...form,code:e.target.value})}/></DrawerField><Toggle label={text("Aktív szolgáltatás","Active service")} checked={!!form.is_active} onChange={v=>setForm({...form,is_active:v})}/></div>}
      {tab==="online"&&<div style={{display:"grid",gap:14}}><Toggle label={text("Online foglalható","Available for online booking")} checked={!!form.online_bookable} onChange={v=>setForm({...form,online_bookable:v})}/><div style={infoBox}>{text("Az online foglalhatóságot és az alap időtartamot itt állíthatod. A szakemberenként eltérő időtartamok az importált Altegio kapcsolatokban megmaradnak.","Set online availability and the base duration here. Staff-specific durations remain preserved in imported Altegio relationships.")}</div></div>}
      {tab==="extra"&&<div><h3 style={{margin:"0 0 12px",fontSize:14}}>{text("Szolgáltatást nyújtó szakemberek","Professionals providing this service")}</h3><div style={infoBox}>{text("A szakember-hozzárendelések külön a Szakember–szolgáltatás beállítások nézetben kezelhetők. Az Altegio-import a szakember-ID és az egyedi időtartam kapcsolatokat megőrzi.","Staff assignments are managed separately in Professional–service settings. Altegio import preserves staff IDs and custom duration relationships.")}</div></div>}
    </div>
    <div style={{padding:"12px 18px",borderTop:"1px solid #ece7df",display:"flex",justifyContent:"flex-end",gap:8,background:"#fff"}}><button onClick={onClose} style={secondaryBtn}>{t("common.cancel")}</button><button onClick={save} disabled={saving} style={primaryBtn}><Save size={15}/>{saving?t("common.saving"):t("common.save")}</button></div>
  </aside></>;
}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,padding:"12px 0",borderBottom:"1px solid #f0ece6",fontSize:12,fontWeight:750,color:"#5f554b"}}><span>{label}</span><button type="button" onClick={()=>onChange(!checked)} style={{width:38,height:22,border:0,borderRadius:999,background:checked?"#e8b82e":"#d8d4ce",padding:2,cursor:"pointer"}}><span style={{display:"block",width:18,height:18,borderRadius:"50%",background:"#fff",transform:checked?"translateX(16px)":"translateX(0)",transition:".15s"}}/></button></label>}
function Tab({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button onClick={onClick} style={{border:"1px solid #e6e1d8",background:active?"#f8f4ea":"#fff",color:active?"#6b5421":"#766c62",borderRadius:7,padding:"7px 9px",display:"inline-flex",gap:5,alignItems:"center",fontSize:10,fontWeight:800,cursor:"pointer"}}>{icon}{children}</button>}
function DrawerField({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:6,fontSize:11,fontWeight:800,color:"#6e655c"}}>{label}{children}</label>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:6,fontSize:11,fontWeight:800,color:"#6f655c"}}>{label}{children}</label>}
function Th({children}:{children:React.ReactNode}){return <th style={{textAlign:"left",padding:"10px 13px",fontSize:10,letterSpacing:".07em",textTransform:"uppercase",color:"#8a7f74",fontWeight:900}}>{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td style={{padding:"11px 13px",color:"#62594f",verticalAlign:"top"}}>{children}</td>}
const inputWrap:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,display:"flex",alignItems:"center",gap:7,padding:"0 10px",background:"#fff",color:"#8c8175"};
const input:React.CSSProperties={border:0,outline:"none",width:"100%",fontSize:12,background:"transparent",color:"#29221c"};
const inputBare:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,padding:"0 10px",fontSize:12,outline:"none",background:"#fff",boxSizing:"border-box"};
const select:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,padding:"0 10px",fontSize:12,outline:"none",background:"#fff",color:"#29221c",width:"100%"};
const drawerInput:React.CSSProperties={height:36,border:"1px solid #ded9d1",borderRadius:7,padding:"0 10px",fontSize:12,outline:"none",background:"#fff",color:"#2b251f",width:"100%",boxSizing:"border-box"};
const readonlyBox:React.CSSProperties={minHeight:36,border:"1px solid #ebe6de",borderRadius:7,padding:"9px 10px",fontSize:11,background:"#faf9f7",color:"#675e55"};
const unit:React.CSSProperties={height:36,minWidth:42,display:"grid",placeItems:"center",border:"1px solid #ded9d1",borderRadius:7,background:"#faf9f7",fontSize:11,color:"#786f66"};
const infoBox:React.CSSProperties={padding:"12px 13px",borderRadius:9,background:"#faf8f3",border:"1px solid #ece5d7",fontSize:11,lineHeight:1.55,color:"#6d6257"};
const iconBtn:React.CSSProperties={width:32,height:32,border:"1px solid #e6e1d8",borderRadius:8,background:"#fff",display:"grid",placeItems:"center",cursor:"pointer",color:"#756a5f"};
const primaryBtn:React.CSSProperties={height:38,border:0,borderRadius:9,padding:"0 14px",background:"#e83f99",color:"#fff",fontWeight:800,display:"inline-flex",alignItems:"center",gap:7,cursor:"pointer"};
const secondaryBtn:React.CSSProperties={height:38,border:"1px solid #ddd5ca",borderRadius:9,padding:"0 13px",background:"#fff",color:"#5f554b",fontWeight:750,cursor:"pointer"};