import React,{FormEvent,useEffect,useRef,useState}from"react";
import{Circle,MessageCirclePlus,RefreshCw,Search,Send,UsersRound}from"lucide-react";
import api from"../api/api";
import"./StaffChatPage.css";

type Coworker={id:string;full_name:string;email?:string;online?:boolean};type Conversation={id:string;other_name:string;title?:string;is_group?:boolean;last_message?:string;unread_count?:number;other_online?:boolean};type Message={id:string;sender_name:string;content:string;created_at:string;is_mine:boolean};
export default function StaffChatPage(){const[coworkers,setCoworkers]=useState<Coworker[]>([]);const[conversations,setConversations]=useState<Conversation[]>([]);const[selected,setSelected]=useState<Conversation|null>(null);const[messages,setMessages]=useState<Message[]>([]);const[text,setText]=useState("");const[q,setQ]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const bottom=useRef<HTMLDivElement|null>(null);
 const loadLists=async()=>{try{setError("");const[c,w]=await Promise.all([api.get("/transactions/staff-chat/conversations"),api.get("/transactions/staff-chat/coworkers",{params:{q}})]);setConversations(c.data||[]);setCoworkers(w.data||[]);await api.post("/transactions/staff-chat/presence")}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||"A chat nem tölthető be.")}finally{setLoading(false)}};
 useEffect(()=>{loadLists();const timer=window.setInterval(loadLists,30000);return()=>window.clearInterval(timer)},[q]);
 const open=async(c:Conversation)=>{setSelected(c);try{const r=await api.get(`/transactions/staff-chat/conversations/${c.id}/messages`);setMessages(r.data||[]);setConversations(v=>v.map(x=>x.id===c.id?{...x,unread_count:0}:x))}catch(e:any){setError(e?.response?.data?.message||"Az üzenetek nem tölthetők be.")}};
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 const start=async(c:Coworker)=>{try{const r=await api.post("/transactions/staff-chat/conversations",{coworker_id:c.id});await loadLists();const found=(await api.get("/transactions/staff-chat/conversations")).data?.find((x:Conversation)=>x.id===r.data.id);if(found)await open(found)}catch(e:any){setError(e?.response?.data?.message||"A beszélgetés nem indítható.")}};
 const send=async(ev:FormEvent)=>{ev.preventDefault();if(!selected||!text.trim())return;try{const r=await api.post(`/transactions/staff-chat/conversations/${selected.id}/messages`,{content:text.trim()});setMessages(v=>[...v,r.data]);setText("");await loadLists()}catch(e:any){setError(e?.response?.data?.message||"Az üzenet nem küldhető el.")}};
 return <main className="staff-chat-page"><header><div><span>BELSŐ KOMMUNIKÁCIÓ</span><h1>Munkatársi chat</h1><p>Saját beszélgetések a kollégákkal.</p></div><button onClick={loadLists}><RefreshCw size={16} className={loading?"spin":""}/>Frissítés</button></header>{error&&<div className="chat-error">{error}</div>}<div className="staff-chat-grid"><aside className="chat-sidebar"><div className="chat-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Kolléga keresése…"/></div><h3>Beszélgetések</h3><div className="conversation-list">{conversations.map(c=><button key={c.id} className={selected?.id===c.id?"is-active":""} onClick={()=>open(c)}><span className="avatar">{(c.other_name||c.title||"C").slice(0,1).toUpperCase()}</span><span className="conversation-copy"><b>{c.other_name||c.title||"Beszélgetés"}</b><small>{c.last_message||"Nincs még üzenet"}</small></span>{Number(c.unread_count)>0&&<em>{c.unread_count}</em>}</button>)}</div><h3>Új beszélgetés</h3><div className="coworker-list">{coworkers.slice(0,30).map(c=><button key={c.id} onClick={()=>start(c)}><Circle size={10} className={c.online?"online":"offline"}/><span><b>{c.full_name}</b><small>{c.online?"Elérhető":"Offline"}</small></span><MessageCirclePlus size={16}/></button>)}</div></aside><section className="chat-main">{selected?<><div className="chat-title"><span className="avatar big">{(selected.other_name||"C").slice(0,1).toUpperCase()}</span><div><h2>{selected.other_name||selected.title}</h2><small>{selected.is_group?"Csoportos beszélgetés":selected.other_online?"Elérhető":"Munkatárs"}</small></div></div><div className="message-stream">{messages.map(m=><div key={m.id} className={`message ${m.is_mine?"mine":"theirs"}`}><small>{m.is_mine?"Én":m.sender_name}</small><p>{m.content}</p><time>{new Date(m.created_at).toLocaleString("hu-HU",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time></div>)}<div ref={bottom}/></div><form className="chat-compose" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Írj üzenetet…"/><button disabled={!text.trim()}><Send size={17}/>Küldés</button></form></>:<div className="chat-empty"><UsersRound/><h2>Válassz beszélgetést</h2><p>Vagy indíts új beszélgetést egy kollégával a bal oldali listából.</p></div>}</section></div></main>}
