import React,{ChangeEvent,useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,ArrowLeft,Check,Download,FileSpreadsheet,Merge,RefreshCw,Upload,X}from"lucide-react";
import{useNavigate}from"react-router-dom";
import withBase from"../utils/apiBase";
import"./StaffImportPage.css";

type ImportRow={full_name:string;email?:string;phone?:string;birth_date?:string;qualification?:string;employment_type?:string;location_name?:string;position_name?:string;monthly_wage?:string;hourly_wage?:string;commission_percent?:string;active?:string};
type DuplicateGroup={email_key?:string;phone_key?:string;employees:Array<{id:string;full_name:string;email?:string;phone?:string;active?:boolean}>};
type ImportResult={total:number;imported:number;skipped:number;failed:number;results:Array<{row:number;status:string;message:string}>};
const headers=["full_name","email","phone","birth_date","qualification","employment_type","location_name","position_name","monthly_wage","hourly_wage","commission_percent","active"];
const labels:Record<string,string>={full_name:"Teljes név",email:"E-mail",phone:"Telefon",birth_date:"Születési dátum",qualification:"Végzettség",employment_type:"Foglalkoztatás",location_name:"Telephely",position_name:"Munkakör",monthly_wage:"Havi bér",hourly_wage:"Órabér",commission_percent:"Jutalék %",active:"Aktív"};
const token=()=>localStorage.getItem("token")||localStorage.getItem("kleo_token")||"";
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(withBase(path),{...options,credentials:"include",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`,...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||body.detail||`HTTP ${response.status}`);return body}
function splitCsv(line:string,delimiter:string){const cells:string[]=[];let current="",quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'){if(quoted&&line[i+1]==='"'){current+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){cells.push(current.trim());current=""}else current+=char}cells.push(current.trim());return cells}
function normalizeHeader(value:string){const raw=value.trim().toLowerCase().replace(/\s+/g,"_").normalize("NFD").replace(/[\u0300-\u036f]/g,"");const aliases:Record<string,string>={nev:"full_name",teljes_nev:"full_name",telefon:"phone",telefonszam:"phone",szuletesi_datum:"birth_date",vegzettseg:"qualification",foglalkoztatasi_forma:"employment_type",foglalkoztatas:"employment_type",telephely:"location_name",munkakor:"position_name",havi_ber:"monthly_wage",haviber:"monthly_wage",oraber:"hourly_wage",jutalek:"commission_percent",jutalek_szazalek:"commission_percent",aktiv:"active"};return aliases[raw]||raw}

export default function StaffImportPage(){
 const navigate=useNavigate();const[rows,setRows]=useState<ImportRow[]>([]);const[fileName,setFileName]=useState("");const[duplicates,setDuplicates]=useState<DuplicateGroup[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<ImportResult|null>(null);const[dragging,setDragging]=useState(false);
 const loadDuplicates=useCallback(async()=>{try{setDuplicates(await api<DuplicateGroup[]>("employees/duplicates"))}catch(e:any){setError(e.message)}},[]);useEffect(()=>{loadDuplicates()},[loadDuplicates]);
 const validRows=useMemo(()=>rows.filter(row=>row.full_name?.trim()&&(row.email?.trim()||row.phone?.trim())),[rows]);
 const parseFile=async(file?:File)=>{if(!file)return;setError("");setResult(null);try{const text=(await file.text()).replace(/^\ufeff/,"");const lines=text.split(/\r?\n/).filter(line=>line.trim());if(lines.length<2)throw new Error("A CSV-fájl nem tartalmaz adatsorokat.");const delimiter=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?";":",";const sourceHeaders=splitCsv(lines[0],delimiter).map(normalizeHeader);if(!sourceHeaders.includes("full_name"))throw new Error("A CSV fejlécében kötelező a Teljes név vagy full_name oszlop.");const parsed=lines.slice(1,501).map(line=>{const cells=splitCsv(line,delimiter);const item:any={};sourceHeaders.forEach((header,index)=>{if(headers.includes(header))item[header]=cells[index]||""});return item as ImportRow}).filter(item=>Object.values(item).some(Boolean));setRows(parsed);setFileName(file.name)}catch(e:any){setRows([]);setFileName("");setError(e.message)}};
 const choose=(event:ChangeEvent<HTMLInputElement>)=>{parseFile(event.target.files?.[0]);event.target.value=""};
 const runImport=async()=>{if(!validRows.length)return;setLoading(true);setError("");try{const data=await api<ImportResult>("employees/import",{method:"POST",body:JSON.stringify({records:validRows})});setResult(data);await loadDuplicates()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const downloadTemplate=()=>{const example=[headers,["Kiss Anna","anna.kiss@example.hu","+36 30 123 4567","1992-05-14","Kozmetikus","Teljes munkaidő","Budapest VIII.","Kozmetikus","420000","","12","igen"]];const blob=new Blob(["\ufeff"+example.map(row=>row.join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="kleoszalon-munkatars-import-sablon.csv";a.click();URL.revokeObjectURL(a.href)};
 return <main className="staff-import-page">
  <header className="staff-import-hero"><div><button onClick={()=>navigate("/employees")}><ArrowLeft size={16}/> Munkatársak</button><span>CSAPAT ÉS HR</span><h1>Importálás és duplikációkezelés</h1><p>Munkatársak tömeges rögzítése ellenőrzött CSV-fájlból, munkakörrel, telephellyel és bérezési adatokkal.</p></div><button className="template-button" onClick={downloadTemplate}><Download size={17}/> CSV-sablon letöltése</button></header>
  {error&&<div className="staff-import-error"><AlertTriangle/><span>{error}</span><button onClick={()=>setError("")}><X/></button></div>}
  <section className="staff-import-summary"><article><FileSpreadsheet/><div><small>Beolvasott sor</small><strong>{rows.length}</strong></div></article><article><Check/><div><small>Importálható</small><strong>{validRows.length}</strong></div></article><article><AlertTriangle/><div><small>Hiányos sor</small><strong>{rows.length-validRows.length}</strong></div></article><article><Merge/><div><small>Duplikációs csoport</small><strong>{duplicates.length}</strong></div></article></section>
  <div className="staff-import-layout"><section className="staff-import-panel"><div className="panel-heading"><div><h2>1. CSV-fájl feltöltése</h2><p>Maximum 500 munkatárs importálható egyszerre.</p></div>{rows.length>0&&<button onClick={()=>{setRows([]);setResult(null);setFileName("")}}>Törlés</button>}</div>
   <label className={`staff-dropzone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);parseFile(e.dataTransfer.files?.[0])}}><Upload/><strong>{fileName||"Húzza ide a CSV-fájlt"}</strong><span>vagy kattintson a tallózáshoz</span><input type="file" accept=".csv,text/csv" onChange={choose}/></label>
   {rows.length>0&&<><div className="preview-heading"><div><h2>2. Előnézet és ellenőrzés</h2><p>A telephely és a munkakör nevének pontosan egyeznie kell a rendszerben szereplő névvel.</p></div><button className="import-button" disabled={loading||!validRows.length} onClick={runImport}>{loading?<RefreshCw className="spin"/>:<Upload/>}{loading?"Importálás…":`${validRows.length} munkatárs importálása`}</button></div><div className="staff-preview"><table><thead><tr><th>Sor</th><th>Munkatárs</th><th>Telephely</th><th>Munkakör</th><th>Foglalkoztatás</th><th>Bérezés</th><th>Állapot</th></tr></thead><tbody>{rows.slice(0,100).map((row,index)=>{const valid=Boolean(row.full_name?.trim()&&(row.email?.trim()||row.phone?.trim()));return <tr key={index} className={valid?"":"invalid"}><td>{index+2}</td><td><b>{row.full_name||"Hiányzó név"}</b><small>{row.email||row.phone||"Nincs elérhetőség"}</small></td><td>{row.location_name||"Alapértelmezett"}</td><td>{row.position_name||"Nincs megadva"}</td><td>{row.employment_type||"—"}</td><td><b>{row.monthly_wage?`${Number(row.monthly_wage).toLocaleString("hu-HU")} Ft/hó`:row.hourly_wage?`${row.hourly_wage} Ft/óra`:"—"}</b><small>{row.commission_percent?`${row.commission_percent}% jutalék`:""}</small></td><td><em className={valid?"valid":"invalid"}>{valid?"Importálható":"Hiányos"}</em></td></tr>})}</tbody></table></div></>}
   {result&&<div className="import-result"><h2>Importálás eredménye</h2><div><span><b>{result.imported}</b> importálva</span><span><b>{result.skipped}</b> kihagyva</span><span><b>{result.failed}</b> hibás</span></div>{result.results.filter(item=>item.status!=="imported").slice(0,20).map(item=><p key={item.row}>CSV {item.row}. sor: {item.message}</p>)}</div>}
  </section>
  <aside className="staff-import-panel duplicates"><div className="panel-heading"><div><h2>Lehetséges duplikációk</h2><p>Azonos e-mail vagy telefonszám alapján.</p></div><button onClick={loadDuplicates} aria-label="Frissítés"><RefreshCw/></button></div>{duplicates.length===0?<div className="empty-duplicates"><Check/><strong>Nincs duplikáció</strong><span>A munkatársi törzs rendezett.</span></div>:duplicates.map((group,index)=><article key={index}><Merge/><div>{group.employees.map(employee=><p key={employee.id}><b>{employee.full_name}</b><span>{employee.email||employee.phone}{employee.active===false?" · inaktív":""}</span></p>)}</div></article>)}</aside></div>
  <section className="staff-column-help"><h2>Támogatott CSV-oszlopok</h2><div>{headers.map(header=><span key={header}><code>{header}</code>{labels[header]}</span>)}</div></section>
 </main>
}
