import React,{useCallback,useEffect,useState} from 'react';
import {CheckCircle2,AlertTriangle,XCircle,RefreshCw,Activity,Sparkles,Wrench} from 'lucide-react';
import api from '../api';import './SystemHealthPage.css';import ReleaseControlCenter from './ReleaseControlCenter';import ObservabilityApmPanel from './ObservabilityApmPanel';import ProcessIntegrityHealthPanel from './ProcessIntegrityHealthPanel';import TransactionTraceHealthPanel from './TransactionTraceHealthPanel';import ExceptionCommandCenterHealthPanel from './ExceptionCommandCenterHealthPanel';import ExceptionIntelligenceHealthPanel from './ExceptionIntelligenceHealthPanel';import ExceptionCapaHealthPanel from './ExceptionCapaHealthPanel';import MajorIncidentHealthPanel from './MajorIncidentHealthPanel';
type C={key:string;group?:string;label:string;status:'ok'|'warning'|'error';count?:number|null;latency_ms?:number;message:string};
type Analysis={severity:'healthy'|'warning'|'critical';summary:string;findings:{check_key:string;explanation:string;priority:string}[];recommended_action:'none'|'booking_runtime_repair';ai_used:boolean;model?:string};
export default function SystemHealthPage(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[analysis,setAnalysis]=useState<Analysis|null>(null),[analysing,setAnalysing]=useState(false),[repairing,setRepairing]=useState(false),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await api.get('/api/transactions/system-health');setData(r.data);setAnalysis(null)}catch(e:any){setError(e?.response?.data?.message||'A rendszerellenőrzés nem futtatható.')}finally{setLoading(false)}},[]);
 async function analyse(){if(!data)return;setAnalysing(true);setError('');try{const r=await api.post('/api/transactions/system-health/ai-analysis',{checks:data.checks});setAnalysis(r.data)}catch(e:any){setError(e?.response?.data?.message||'Az AI-elemzés nem futtatható.')}finally{setAnalysing(false)}}
 async function repair(){if(analysis?.recommended_action!=='booking_runtime_repair')return;setRepairing(true);setError('');try{const r=await api.post('/api/transactions/system-health/repair',{action:analysis.recommended_action});setNotice(r.data.message);await load()}catch(e:any){setError(e?.response?.data?.message||'A biztonságos javítás nem hajtható végre.')}finally{setRepairing(false)}}
 useEffect(()=>{void load()},[load]);const icon=(s:string)=>s==='ok'?<CheckCircle2/>:s==='warning'?<AlertTriangle/>:<XCircle/>;
 return <><ReleaseControlCenter/><ObservabilityApmPanel/><ProcessIntegrityHealthPanel/><TransactionTraceHealthPanel/><ExceptionCommandCenterHealthPanel/><ExceptionIntelligenceHealthPanel/><ExceptionCapaHealthPanel/><MajorIncidentHealthPanel/><div className="health-page"><header><div><span>ADMINISZTRÁCIÓ · RENDSZERDIAGNOSZTIKA</span><h1><Activity/> VIR rendszerellenőrzés</h1><p>Determinisztikus technikai ellenőrzések, üzleti folyamatintegritás, tranzakció-bizonyítás, Exception Management, Intelligence, CAPA governance és Major Incident / War Room readiness, AI-diagnózis és jóváhagyható biztonságos helyreállítás.</p></div><div className="health-actions"><button onClick={load} disabled={loading}><RefreshCw size={16}/> {loading?'Ellenőrzés…':'Újraellenőrzés'}</button><button className="ai-button" onClick={analyse} disabled={!data||analysing}><Sparkles size={16}/> {analysing?'AI elemzés…':'AI elemzés'}</button></div></header>{error&&<div className="health-error">{error}</div>}{notice&&<div className="health-notice">{notice}</div>}{analysis&&<section className={`health-ai ${analysis.severity}`}><div><span>{analysis.ai_used?`AI DIAGNÓZIS${analysis.model?` · ${analysis.model}`:''}`:'SZABÁLYALAPÚ DIAGNÓZIS'}</span><h2><Sparkles size={20}/>{analysis.summary}</h2></div>{analysis.findings.length>0&&<ul>{analysis.findings.map(f=><li key={f.check_key}><b>{f.priority==='high'?'Magas':f.priority==='low'?'Alacsony':'Közepes'}:</b> {f.explanation}</li>)}</ul>}{analysis.recommended_action==='booking_runtime_repair'&&<button onClick={repair} disabled={repairing}><Wrench size={16}/>{repairing?'Javítás…':'Biztonságos javítás futtatása'}</button>}<small>Az AI nem hajt végre parancsot és nem módosít adatot. Javítás csak a fenti, előre engedélyezett művelettel és az Ön kattintása után történik.</small></section>}{data&&<><section className="health-summary"><article className={data.status}><b>{data.summary.ok}</b><span>Rendben</span></article><article className="warning"><b>{data.summary.warnings}</b><span>Figyelmeztetés</span></article><article className="error"><b>{data.summary.errors}</b><span>Hiba</span></article><article><b>{data.summary.total}</b><span>Összes ellenőrzés</span></article></section><section className="health-card"><div className="health-card-head"><h2>Modul- és adatbázis állapot</h2><small>{new Date(data.generated_at).toLocaleString('hu-HU')}</small></div><div className="health-list">{data.checks.map((c:C)=><div className={`health-row ${c.status}`} key={c.key}><div className="health-icon">{icon(c.status)}</div><div><b>{c.label}</b><small>{c.message}</small></div><div className="health-meta">{c.count!=null&&<span>{c.count} db</span>}{c.latency_ms!=null&&<span>{c.latency_ms} ms</span>}</div></div>)}</div></section><div className="health-legend"><b>UAT döntés:</b> piros hibánál a modul vagy üzleti folyamat javítandó; sárga állapot tesztelhető, de ellenőrzést igényel; minden zöld esetén technikailag indulhat a teljes felhasználói teszt.</div></>}</div></>
}