import React,{useCallback,useEffect,useMemo,useState}from"react";
import axios from"axios";
import{CheckCircle2,Circle,Mail,PlayCircle,RefreshCw,Rocket,Save,ShieldCheck}from"lucide-react";
import"./SaasFranchiseAdminPage.css";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const authConfig=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
const PLANS=[['start','Start'],['pro','Pro'],['franchise','Franchise'],['enterprise','Enterprise']];
const MODULES=[['booking','Foglalás'],['crm','CRM'],['hr','HR'],['inventory','Készlet'],['finance','Pénzügy'],['marketing','Marketing'],['franchise','Franchise'],['mobile_app','Mobilapp'],['payroll','Bérszámfejtés'],['ai','AI']];
type Tenant={id:string;slug:string;name:string;status:string};type Checklist={key:string;label:string;complete:boolean};
type OnboardingState={progress:number;ready:boolean;next_step:string;checklist:Checklist[];tenant:any;admin:any;location:any;branding:any;features:any[];subscription:any;onboarding:any;events:any[]};
type Invitation={id:string;email:string;status:string;expires_at:string;created_at:string;accepted_at?:string|null};

export default function TenantOnboardingPanel(){
 const[tenants,setTenants]=useState<Tenant[]>([]),[tenantId,setTenantId]=useState(''),[state,setState]=useState<OnboardingState|null>(null),[invitation,setInvitation]=useState<Invitation|null>(null),[allowed,setAllowed]=useState<boolean|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const[company,setCompany]=useState({legal_name:'',tax_number:'',billing_email:'',default_locale:'hu-HU',default_currency:'HUF',timezone:'Europe/Budapest'});const[adminEmail,setAdminEmail]=useState('');const[location,setLocation]=useState({name:'',city:'',address:'',email:''});const[branding,setBranding]=useState({app_name:'',logo_url:'',favicon_url:'',primary_color:'',secondary_color:'',custom_domain:'',email_sender_name:''});const[modules,setModules]=useState<Record<string,boolean>>({booking:true,crm:true,hr:true,inventory:true,finance:true});const[subscription,setSubscription]=useState({plan_code:'start',status:'trial'});
 const endpoint=tenantId?`${API_BASE}/saas/platform/tenants/${tenantId}/onboarding`:'';const selected=useMemo(()=>tenants.find(t=>t.id===tenantId)||null,[tenants,tenantId]);
 const loadTenants=useCallback(async()=>{try{const r=await axios.get(`${API_BASE}/saas/platform/tenants`,authConfig());const list=Array.isArray(r.data?.rows)?r.data.rows:[];setTenants(list);setAllowed(true);setTenantId(v=>v||String(list.find((x:any)=>x.slug!=='kleopatra')?.id||list[0]?.id||''));}catch(e:any){if(e?.response?.status===403){setAllowed(false);return}setAllowed(true);setError(e?.response?.data?.error||'A tenant lista nem tölthető be.')}},[]);
 const loadState=useCallback(async()=>{if(!tenantId)return;setLoading(true);setError('');try{const[r,ir]=await Promise.all([axios.get(`${API_BASE}/saas/platform/tenants/${tenantId}/onboarding`,authConfig()),axios.get(`${API_BASE}/saas/platform/tenants/${tenantId}/admin-invitation`,authConfig())]);const d=r.data as OnboardingState;setState(d);setInvitation(ir.data?.invitation||null);setAdminEmail(ir.data?.invitation?.status==='pending'?ir.data.invitation.email:(d.admin?.email||''));setCompany({legal_name:d.tenant?.legal_name||'',tax_number:d.tenant?.tax_number||'',billing_email:d.tenant?.billing_email||'',default_locale:d.tenant?.default_locale||'hu-HU',default_currency:d.tenant?.default_currency||'HUF',timezone:d.tenant?.timezone||'Europe/Budapest'});setLocation({name:d.location?.name||'',city:d.location?.city||'',address:d.location?.address||'',email:d.location?.email||''});setBranding({app_name:d.branding?.app_name||'',logo_url:d.branding?.logo_url||'',favicon_url:d.branding?.favicon_url||'',primary_color:d.branding?.primary_color||'',secondary_color:d.branding?.secondary_color||'',custom_domain:d.branding?.custom_domain||'',email_sender_name:d.branding?.email_sender_name||''});setSubscription({plan_code:d.subscription?.plan_code||'start',status:d.subscription?.status==='active'?'active':'trial'});if(Array.isArray(d.features)&&d.features.length)setModules(Object.fromEntries(d.features.map((f:any)=>[f.feature_key,Boolean(f.enabled)])));}catch(e:any){setError(e?.response?.data?.error||'Az onboarding állapota nem tölthető be.')}finally{setLoading(false)}},[tenantId]);
 useEffect(()=>{void loadTenants()},[loadTenants]);useEffect(()=>{void loadState()},[loadState]);
 const save=async(path:string,payload:any,success:string)=>{if(!endpoint)return;setSaving(true);setError('');setMessage('');try{const r=await axios.put(`${endpoint}/${path}`,payload,authConfig());setState(r.data);setMessage(success)}catch(e:any){setError(e?.response?.data?.error||'A lépés mentése nem sikerült.')}finally{setSaving(false)}};
 const inviteAdmin=async()=>{if(!tenantId||!adminEmail.trim())return;setSaving(true);setError('');setMessage('');try{const r=await axios.post(`${API_BASE}/saas/platform/tenants/${tenantId}/admin-invitation`,{email:adminEmail.trim()},authConfig());setInvitation(r.data?.invitation||null);setMessage(r.data?.message||'Admin meghívó elküldve.');await loadState()}catch(e:any){setError(e?.response?.data?.error||'Az admin meghívó nem küldhető el.')}finally{setSaving(false)}};
 const complete=async()=>{if(!endpoint)return;setSaving(true);setError('');setMessage('');try{const r=await axios.post(`${endpoint}/complete`,{},authConfig());setState(r.data);setMessage('Az onboarding lezárult: a tenant üzemkész.');await loadTenants()}catch(e:any){const missing=e?.response?.data?.missing;setError((e?.response?.data?.error||'Az onboarding nem zárható le.')+(Array.isArray(missing)&&missing.length?` Hiányzik: ${missing.join(', ')}.`:''))}finally{setSaving(false)}};
 if(allowed===false)return null;
 return <div className="saas-admin-page" style={{paddingBottom:0}}><section className="saas-panel"><div className="saas-panel-title"><div><h3>Tenant onboarding</h3><p>Automatizált indulási folyamat: cég → admin meghívás/aktiválás → telephely → arculat → modulok → előfizetés → üzemkész.</p></div><Rocket size={22}/></div>{error&&<div className="saas-alert is-error">{error}</div>}{message&&<div className="saas-alert is-success">{message}</div>}<div className="saas-form-grid"><label>Onboarding tenant<select value={tenantId} onChange={e=>setTenantId(e.target.value)}>{tenants.map(t=><option key={t.id} value={t.id}>{t.name} ({t.slug})</option>)}</select></label><button type="button" className="is-secondary" onClick={()=>void loadState()} disabled={loading}><RefreshCw size={16}/>Állapot frissítése</button></div>{state&&<><div style={{margin:'18px 0 10px',display:'flex',alignItems:'center',gap:12}}><div style={{flex:1,height:12,background:'#e5e7eb',borderRadius:999,overflow:'hidden'}}><div style={{width:`${state.progress}%`,height:'100%',background:'currentColor'}}/></div><b>{state.progress}%</b>{state.ready&&<span className="saas-status-pill status-active">Üzemkész</span>}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}>{state.checklist?.map(item=><span key={item.key} style={{display:'inline-flex',alignItems:'center',gap:5,padding:'6px 9px',border:'1px solid #d1d5db',borderRadius:999}}>{item.complete?<CheckCircle2 size={15}/>:<Circle size={15}/>} {item.label}</span>)}</div><div className="saas-form-grid">
 <label>Hivatalos cégnév<input value={company.legal_name} onChange={e=>setCompany({...company,legal_name:e.target.value})}/></label><label>Adószám<input value={company.tax_number} onChange={e=>setCompany({...company,tax_number:e.target.value})}/></label><label>Számlázási e-mail<input type="email" value={company.billing_email} onChange={e=>setCompany({...company,billing_email:e.target.value})}/></label><button type="button" onClick={()=>void save('company',company,'Cégadatok mentve.')} disabled={saving}><Save size={16}/>Cégadatok</button>
 <label>Első admin e-mail<input type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} placeholder="admin@ceg.hu"/></label><button type="button" onClick={()=>void inviteAdmin()} disabled={saving||!adminEmail.trim()||Boolean(state.admin)}><Mail size={16}/>{state.admin?'Admin aktiválva':invitation?.status==='pending'?'Meghívó újraküldése':'Admin meghívása'}</button>{state.admin?<div><ShieldCheck size={16}/> Első admin aktiválva.</div>:invitation&&<div style={{gridColumn:'1/-1'}}><b>Meghívó:</b> {invitation.email} · <b>{invitation.status}</b>{invitation.status==='pending'&&<> · lejár: {new Date(invitation.expires_at).toLocaleString('hu-HU')}</>}</div>}
 <label>Telephely neve<input value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></label><label>Város<input value={location.city} onChange={e=>setLocation({...location,city:e.target.value})}/></label><label>Cím<input value={location.address} onChange={e=>setLocation({...location,address:e.target.value})}/></label><label>Telephely e-mail<input type="email" value={location.email} onChange={e=>setLocation({...location,email:e.target.value})}/></label><button type="button" onClick={()=>void save('location',location,'Első telephely mentve.')} disabled={saving}><Save size={16}/>Telephely</button>
 <label>App / márkanév<input value={branding.app_name} onChange={e=>setBranding({...branding,app_name:e.target.value})}/></label><label>Logó URL<input value={branding.logo_url} onChange={e=>setBranding({...branding,logo_url:e.target.value})}/></label><label>Elsődleges szín<input value={branding.primary_color} onChange={e=>setBranding({...branding,primary_color:e.target.value})} placeholder="#111827"/></label><label>Egyedi domain<input value={branding.custom_domain} onChange={e=>setBranding({...branding,custom_domain:e.target.value})}/></label><button type="button" onClick={()=>void save('branding',branding,'Arculat mentve.')} disabled={saving}><Save size={16}/>Branding</button>
 <div style={{gridColumn:'1/-1'}}><b>Modulok</b><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}>{MODULES.map(([key,label])=><label key={key} style={{display:'inline-flex',flexDirection:'row',alignItems:'center',gap:6}}><input type="checkbox" checked={Boolean(modules[key])} onChange={e=>setModules({...modules,[key]:e.target.checked})}/>{label}</label>)}</div><button type="button" style={{marginTop:10}} onClick={()=>void save('modules',{features:modules},'Modulok mentve.')} disabled={saving}><Save size={16}/>Modulok mentése</button></div>
 <label>Csomag<select value={subscription.plan_code} onChange={e=>setSubscription({...subscription,plan_code:e.target.value})}>{PLANS.map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Előfizetés<select value={subscription.status} onChange={e=>setSubscription({...subscription,status:e.target.value})}><option value="trial">14 napos próba</option><option value="active">Aktív</option></select></label><button type="button" onClick={()=>void save('subscription',subscription,'Előfizetés beállítva.')} disabled={saving}><PlayCircle size={16}/>Előfizetés</button></div><div style={{marginTop:18,display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><button type="button" onClick={()=>void complete()} disabled={saving||!state.ready}><Rocket size={17}/>{state.ready?'Onboarding lezárása – Üzemkész':'Hiányzó lépések vannak'}</button><span>Következő lépés: <b>{state.next_step}</b>{selected?` · ${selected.name}`:''}</span></div>{state.events?.length>0&&<details style={{marginTop:18}}><summary>Onboarding eseménynapló ({state.events.length})</summary><div className="saas-table-wrap" style={{marginTop:10}}><table><thead><tr><th>Idő</th><th>Lépés</th><th>Esemény</th><th>Felhasználó</th></tr></thead><tbody>{state.events.slice(0,20).map((ev:any,i:number)=><tr key={i}><td>{new Date(ev.created_at).toLocaleString('hu-HU')}</td><td>{ev.step_key}</td><td>{ev.event_type}</td><td>{ev.actor_user_id||'—'}</td></tr>)}</tbody></table></div></details>}</>}</section></div>;
}
