import React,{CSSProperties,FormEvent,useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,CalendarDays,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Plus,RefreshCw,Save,Send,Settings2,Trash2,UsersRound,X}from"lucide-react";
import withBase from"../utils/apiBase";
import"./timetableUpdate.css";

type Employee={id:string;full_name:string;position_name?:string;location_id?:string;location_name?:string;schedule_type:string;weekly_minutes:number;daily_minutes:number;min_daily_minutes:number;max_daily_minutes:number;max_weekly_minutes:number;min_daily_rest_minutes:number;min_weekly_rest_minutes:number;break_after_six_hours:number;additional_break_after_nine_hours:number;allow_split_shift:boolean;allow_sunday:boolean;allow_public_holiday:boolean;allow_night_work:boolean;standby_position:boolean;multi_shift_activity:boolean;seasonal_activity:boolean;uninterrupted_activity:boolean;voluntary_overtime_agreement:boolean;annual_overtime_limit:number;voluntary_overtime_limit:number;frame_start?:string;frame_end?:string;settlement_period_weeks?:number;notes?:string};
type Shift={id:string;employee_id:string;location_id?:string;work_date:string;starts_at:string;ends_at:string;break_minutes:number;shift_type:string;status:string;is_overtime:boolean;overtime_ordered:boolean;is_standby:boolean;is_on_call:boolean;is_training:boolean;legal_override_reason?:string;note?:string};
type Warning={code:string;severity:"error"|"warning";message:string;employee_id:string;shift_id?:string;work_date?:string};
type Data={employees:Employee[];shifts:Shift[];warnings:Warning[];locations:Array<{id:string;name:string}>;holidays:Array<{holiday_date:string;name:string}>;summary:{employee_count:number;shift_count:number;scheduled_minutes:number;error_count:number;warning_count:number}};

type MonthlyTotal={shiftCount:number;minutes:number};
const token=()=>localStorage.getItem("token")||localStorage.getItem("kleo_token")||"";
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const r=await fetch(withBase(path),{...init,credentials:"include",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`,...(init.headers||{})}});const text=await r.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{throw new Error(`A szerver nem JSON választ adott (HTTP ${r.status}).`)}if(!r.ok)throw Object.assign(new Error(body.error||`HTTP ${r.status}`),{details:body.warnings});return body}
const pad=(n:number)=>String(n).padStart(2,"0");
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const mins=(n:number)=>`${Math.floor(Number(n||0)/60)} ó${Number(n||0)%60?` ${Number(n||0)%60} p`:""}`;
const time=(value:string)=>new Date(value).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"});
const dayName=(d:Date)=>["V","H","K","Sze","Cs","P","Szo"][d.getDay()];
const monthLabel=(d:Date)=>d.toLocaleDateString("hu-HU",{year:"numeric",month:"long"});
function monthDays(anchor:Date){const y=anchor.getFullYear(),m=anchor.getMonth(),count=new Date(y,m+1,0).getDate();return Array.from({length:count},(_,i)=>new Date(y,m,i+1,12,0,0,0))}
function shiftMinutes(s:Shift){const start=new Date(s.starts_at).getTime(),end=new Date(s.ends_at).getTime();return Math.max(0,Math.round((end-start)/60000)-Number(s.break_minutes||0))}
const emptyShift={employee_id:"",location_id:"",work_date:"",start:"09:00",end:"17:00",break_minutes:20,shift_type:"regular",is_overtime:false,overtime_ordered:false,is_standby:false,is_on_call:false,is_training:false,note:"",legal_override_reason:""};

export default function TimetableUpdatePage(){
 const[anchor,setAnchor]=useState(()=>new Date());
 const days=useMemo(()=>monthDays(anchor),[anchor]);
 const from=iso(days[0]),to=iso(days[days.length-1]);
 const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[search,setSearch]=useState("");const[location,setLocation]=useState("");const[selected,setSelected]=useState<Employee|null>(null);const[profile,setProfile]=useState<any>(null);const[shiftModal,setShiftModal]=useState(false);const[shift,setShift]=useState<any>(emptyShift);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");
 const gridStyle=useMemo<CSSProperties>(()=>({gridTemplateColumns:`230px 86px repeat(${days.length},54px)`,minWidth:`${316+days.length*54}px`}),[days.length]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await api<Data>(`timetable/schedule?from=${from}&to=${to}${location?`&location_id=${location}`:""}`))}catch(e:any){setError(e.message)}finally{setLoading(false)}},[from,to,location]);
 useEffect(()=>{load()},[load]);
 const employees=useMemo(()=>data?.employees.filter(e=>!search.trim()||`${e.full_name} ${e.position_name||""}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 const shiftMap=useMemo(()=>{const m=new Map<string,Shift[]>();for(const s of data?.shifts||[]){if(s.status==="cancelled")continue;const key=`${s.employee_id}:${String(s.work_date).slice(0,10)}`;m.set(key,[...(m.get(key)||[]),s])}return m},[data]);
 const warningMap=useMemo(()=>{const m=new Map<string,Warning[]>();for(const w of data?.warnings||[]){const key=w.shift_id||`${w.employee_id}:${String(w.work_date||"").slice(0,10)}`;m.set(key,[...(m.get(key)||[]),w])}return m},[data]);
 const monthlyTotals=useMemo(()=>{const m=new Map<string,MonthlyTotal>();for(const s of data?.shifts||[]){if(s.status==="cancelled")continue;const v=m.get(s.employee_id)||{shiftCount:0,minutes:0};v.shiftCount+=1;v.minutes+=shiftMinutes(s);m.set(s.employee_id,v)}return m},[data]);
 const holidays=useMemo(()=>new Set((data?.holidays||[]).map(h=>String(h.holiday_date).slice(0,10))),[data]);
 const showNotice=(v:string)=>{setNotice(v);window.setTimeout(()=>setNotice(""),3000)};
 const editProfile=(e:Employee)=>{setSelected(e);setProfile({...e})};
 const openShift=(employee:Employee,date:string,current?:Shift)=>{setSelected(employee);setShift(current?{...current,start:time(current.starts_at),end:time(current.ends_at),work_date:String(current.work_date).slice(0,10)}:{...emptyShift,employee_id:employee.id,location_id:employee.location_id||location,work_date:date});setShiftModal(true)};
 const moveMonth=(delta:number)=>setAnchor(a=>new Date(a.getFullYear(),a.getMonth()+delta,1,12,0,0,0));
 const saveProfile=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setSaving(true);setError("");try{await api(`timetable/profiles/${selected.id}`,{method:"PUT",body:JSON.stringify(profile)});setSelected(null);showNotice("A munkaidőprofil mentése sikerült.");await load()}catch(x:any){setError(x.message)}finally{setSaving(false)}};
 const saveShift=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const payload={...shift,starts_at:`${shift.work_date}T${shift.start}:00`,ends_at:`${shift.work_date}T${shift.end}:00`};if(new Date(payload.ends_at)<=new Date(payload.starts_at))throw new Error("A befejezés legyen későbbi a kezdésnél.");await api(shift.id?`timetable/shifts/${shift.id}`:"timetable/shifts",{method:shift.id?"PATCH":"POST",body:JSON.stringify(payload)});setShiftModal(false);showNotice("A műszak mentése sikerült.");await load()}catch(x:any){setError(x.message)}finally{setSaving(false)}};
 const removeShift=async()=>{if(!shift.id||!window.confirm("Törli ezt a műszakot?"))return;setSaving(true);try{await api(`timetable/shifts/${shift.id}`,{method:"DELETE"});setShiftModal(false);showNotice("A műszak törölve.");await load()}catch(x:any){setError(x.message)}finally{setSaving(false)}};
 const publish=async()=>{if(!window.confirm("Közzéteszi a havi beosztást? A munkajogi hibák megakadályozzák a közzétételt."))return;setSaving(true);setError("");try{await api("timetable/publish",{method:"POST",body:JSON.stringify({from,to,location_id:location||null})});showNotice("A havi beosztás közzétéve.");await load()}catch(x:any){setError(x.message);if(x.details)setData(d=>d?{...d,warnings:x.details}:d)}finally{setSaving(false)}};
 const dayClass=(d:Date)=>{const parts=["ws-date-head"];if(d.getDay()===0||d.getDay()===6)parts.push("weekend");if(holidays.has(iso(d)))parts.push("holiday");if(iso(d)===iso(new Date()))parts.push("today");return parts.join(" ")};
 const cellClass=(d:Date)=>{const parts=["ws-month-day"];if(d.getDay()===0||d.getDay()===6)parts.push("weekend");if(holidays.has(iso(d)))parts.push("holiday");if(iso(d)===iso(new Date()))parts.push("today");return parts.join(" ")};
 return <main className="work-schedule-page">
  <header className="ws-hero"><div><span>CSAPAT ÉS HR</span><h1>Munkaidő és beosztás</h1><p>Havi, dolgozónkénti beosztástábla gyors műszakszerkesztéssel és munkajogi ellenőrzéssel.</p></div><button className="ws-publish" onClick={publish} disabled={saving||!data?.shifts.length}><Send/> Beosztás közzététele</button></header>
  {notice&&<div className="ws-notice"><CheckCircle2/>{notice}</div>}{error&&<div className="ws-error"><AlertTriangle/>{error}<button onClick={()=>setError("")}><X/></button></div>}
  <section className="ws-stats"><article><UsersRound/><div><small>Munkatársak</small><strong>{data?.summary.employee_count||0}</strong></div></article><article><CalendarDays/><div><small>Havi műszakok</small><strong>{data?.summary.shift_count||0}</strong></div></article><article><Clock3/><div><small>Beosztott idő</small><strong>{mins(data?.summary.scheduled_minutes||0)}</strong></div></article><article className={(data?.summary.error_count||0)>0?"danger":""}><AlertTriangle/><div><small>Jogi eltérések</small><strong>{data?.summary.error_count||0}</strong></div></article></section>
  <section className="ws-toolbar"><div className="ws-period-nav"><button onClick={()=>moveMonth(-1)} title="Előző hónap"><ChevronLeft/></button><button onClick={()=>setAnchor(new Date())}>Ma</button><button onClick={()=>moveMonth(1)} title="Következő hónap"><ChevronRight/></button><b>{monthLabel(anchor)}</b></div><div className="ws-toolbar-filters"><select value={location}onChange={e=>setLocation(e.target.value)}><option value="">Minden telephely</option>{data?.locations.map(l=><option key={l.id}value={l.id}>{l.name}</option>)}</select><input placeholder="Munkatárs keresése…"value={search}onChange={e=>setSearch(e.target.value)}/><button onClick={load}title="Frissítés"><RefreshCw className={loading?"spin":""}/></button><div className="ws-view-switch"><button className="active">Hónap</button></div></div></section>
  <section className="ws-board ws-month-board">
   <div className="ws-month-grid ws-month-head"style={gridStyle}><div className="ws-person-head">Munkatárs</div><div className="ws-total-head"><b>Összesen</b><span>{monthLabel(anchor).split(" ")[0]}</span></div>{days.map(d=><div key={iso(d)}className={dayClass(d)}><strong>{d.getDate()}</strong><small>{dayName(d)}</small></div>)}</div>
   {loading&&!data?<div className="ws-empty">Beosztás betöltése…</div>:employees.length===0?<div className="ws-empty">Nincs megjeleníthető munkatárs.</div>:employees.map(employee=>{const total=monthlyTotals.get(employee.id)||{shiftCount:0,minutes:0};return <div className="ws-month-grid ws-month-row"style={gridStyle}key={employee.id}><div className="ws-person"><div className="ws-avatar">{employee.full_name.charAt(0)}</div><div><strong>{employee.full_name}</strong><span>{employee.position_name||"Nincs munkakör"}{employee.location_name?` · ${employee.location_name}`:""}</span></div><button onClick={()=>editProfile(employee)}title="Munkaidőprofil"><Settings2/></button></div><div className="ws-total-cell"><b>{total.shiftCount}</b><span>{mins(total.minutes)}</span></div>{days.map(date=>{const key=`${employee.id}:${iso(date)}`,items=shiftMap.get(key)||[];return <div className={cellClass(date)}key={key}>{items.map(s=>{const warns=warningMap.get(s.id)||[];const type=s.is_training?"training":s.is_standby||s.is_on_call?"standby":s.is_overtime?"overtime":"regular";return <button key={s.id}className={`ws-mini-shift ${type} ${s.status} ${warns.length?"has-warning":""}`}onClick={()=>openShift(employee,iso(date),s)} title={`${time(s.starts_at)}–${time(s.ends_at)}${s.note?` · ${s.note}`:""}`}><b>{time(s.starts_at)}</b><span>{time(s.ends_at)}</span>{warns.length>0&&<AlertTriangle/>}</button>})}<button className="ws-cell-add"onClick={()=>openShift(employee,iso(date))}title="Műszak hozzáadása"><Plus/></button></div>})}</div>})}
  </section>
  <div className="ws-legend"><span><i className="regular"/>Rendes műszak</span><span><i className="overtime"/>Túlóra</span><span><i className="standby"/>Készenlét / ügyelet</span><span><i className="training"/>Képzés</span><span><i className="warning"/>Munkajogi jelzés</span></div>
  <section className="ws-compliance"><header><div><h2>Munkajogi ellenőrzések</h2><p>A rendszer a beosztás mentésekor és közzétételekor újraszámolja az eltéréseket.</p></div><span>{data?.warnings.length||0} jelzés</span></header>{!data?.warnings.length?<div className="ws-compliance-ok"><CheckCircle2/> A havi beosztásban nincs észlelt eltérés.</div>:<div>{data.warnings.map((w,i)=><article key={`${w.code}-${i}`}className={w.severity}><AlertTriangle/><div><b>{w.code}</b><p>{w.message}</p></div><span>{data.employees.find(e=>e.id===w.employee_id)?.full_name}</span></article>)}</div>}</section>
  {selected&&profile&&!shiftModal&&<div className="ws-modal-bg"><form className="ws-modal ws-profile-modal"onSubmit={saveProfile}><ModalHead title={`${selected.full_name} munkaidőprofilja`}close={()=>setSelected(null)}/><div className="ws-form-section"><h3>Alap munkaidő</h3><div className="ws-form-grid"><Field label="Munkarend"><select value={profile.schedule_type}onChange={e=>setProfile({...profile,schedule_type:e.target.value})}><option value="general">Általános</option><option value="uneven">Egyenlőtlen</option><option value="flexible">Rugalmas</option><option value="split">Osztott</option><option value="multi_shift">Több műszakos</option><option value="standby">Készenléti jellegű</option></select></Field><Num label="Heti munkaidő (perc)"k="weekly_minutes"/><Num label="Napi munkaidő (perc)"k="daily_minutes"/><Num label="Elszámolási időszak (hét)"k="settlement_period_weeks"/></div></div><div className="ws-form-section"><h3>Korlátok és pihenőidő</h3><div className="ws-form-grid"><Num label="Napi minimum (perc)"k="min_daily_minutes"/><Num label="Napi maximum (perc)"k="max_daily_minutes"/><Num label="Heti maximum (perc)"k="max_weekly_minutes"/><Num label="Napi pihenőidő (perc)"k="min_daily_rest_minutes"/><Num label="Heti pihenőidő (perc)"k="min_weekly_rest_minutes"/><Num label="Szünet 6 óra felett"k="break_after_six_hours"/><Num label="További szünet 9 óra felett"k="additional_break_after_nine_hours"/></div></div><div className="ws-form-section"><h3>Engedélyek és különleges munkarend</h3><div className="ws-check-grid">{[["allow_split_shift","Osztott munkaidő"],["allow_sunday","Vasárnapi munka"],["allow_public_holiday","Munkaszüneti napi munka"],["allow_night_work","Éjszakai munka"],["standby_position","Készenléti munkakör"],["multi_shift_activity","Több műszakos tevékenység"],["seasonal_activity","Idényjellegű tevékenység"],["uninterrupted_activity","Megszakítás nélküli tevékenység"],["voluntary_overtime_agreement","Önként vállalt túlmunka-megállapodás"]].map(([k,l])=><label key={k}><input type="checkbox"checked={Boolean(profile[k])}onChange={e=>setProfile({...profile,[k]:e.target.checked})}/><span/>{l}</label>)}</div><div className="ws-form-grid"><Num label="Éves rendkívüli munkaóra"k="annual_overtime_limit"/><Num label="Önként vállalt plusz óra"k="voluntary_overtime_limit"/></div></div><footer><button type="button"onClick={()=>setSelected(null)}>Mégse</button><button className="primary"disabled={saving}><Save/>{saving?"Mentés…":"Profil mentése"}</button></footer></form></div>}
  {shiftModal&&selected&&<div className="ws-modal-bg"><form className="ws-modal ws-shift-modal"onSubmit={saveShift}><ModalHead title={shift.id?"Műszak szerkesztése":"Új műszak"}subtitle={selected.full_name}close={()=>setShiftModal(false)}/><div className="ws-form-grid"><Field label="Munkanap"><input type="date"required value={shift.work_date}onChange={e=>setShift({...shift,work_date:e.target.value})}/></Field><Field label="Telephely"><select value={shift.location_id||""}onChange={e=>setShift({...shift,location_id:e.target.value})}><option value="">Dolgozó alaptelephelye</option>{data?.locations.map(l=><option key={l.id}value={l.id}>{l.name}</option>)}</select></Field><Field label="Kezdés"><input type="time"required value={shift.start}onChange={e=>setShift({...shift,start:e.target.value})}/></Field><Field label="Befejezés"><input type="time"required value={shift.end}onChange={e=>setShift({...shift,end:e.target.value})}/></Field><Field label="Munkaközi szünet (perc)"><input type="number"min="0"value={shift.break_minutes}onChange={e=>setShift({...shift,break_minutes:Number(e.target.value)})}/></Field><Field label="Műszaktípus"><select value={shift.shift_type}onChange={e=>setShift({...shift,shift_type:e.target.value})}><option value="regular">Rendes munkaidő</option><option value="overtime">Rendkívüli munkaidő</option><option value="standby">Készenlét</option><option value="on_call">Ügyelet</option><option value="training">Oktatás</option></select></Field></div><div className="ws-check-grid compact">{[["is_overtime","Túlórának minősül"],["overtime_ordered","Írásban elrendelt"],["is_standby","Készenlét"],["is_on_call","Ügyelet"],["is_training","Képzés"]].map(([k,l])=><label key={k}><input type="checkbox"checked={Boolean(shift[k])}onChange={e=>setShift({...shift,[k]:e.target.checked})}/><span/>{l}</label>)}</div><Field label="Megjegyzés"><textarea value={shift.note||""}onChange={e=>setShift({...shift,note:e.target.value})}/></Field><Field label="Jogi eltérés indoka (csak dokumentált kivételnél)"><textarea value={shift.legal_override_reason||""}onChange={e=>setShift({...shift,legal_override_reason:e.target.value})}/></Field><footer>{shift.id&&<button type="button"className="danger"onClick={removeShift}><Trash2/> Törlés</button>}<span/><button type="button"onClick={()=>setShiftModal(false)}>Mégse</button><button className="primary"disabled={saving}><Save/>{saving?"Mentés…":"Műszak mentése"}</button></footer></form></div>}
 </main>;
 function Num({label,k}:{label:string;k:string}){return <Field label={label}><input type="number"min="0"value={profile[k]??""}onChange={e=>setProfile({...profile,[k]:Number(e.target.value)})}/></Field>}
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="ws-field"><span>{label}</span>{children}</label>}
function ModalHead({title,subtitle,close}:{title:string;subtitle?:string;close:()=>void}){return <header className="ws-modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button type="button"onClick={close}><X/></button></header>}
