import React,{useCallback,useEffect,useMemo,useState}from'react';
import{AlertTriangle,BellRing,CheckCircle2,Clock3,Database,Download,FileCheck2,Fingerprint,Gauge,GitBranch,History,Network,RefreshCw,Search,ShieldAlert,ShieldCheck,ShieldX,Workflow}from'lucide-react';
import api from'../api';
import'./TransactionTracePage.css';

type RootType='work_order'|'purchase_order'|'booking'|'invoice';
type Stage={key:string;label:string;status:'ok'|'warning'|'critical';evidence_count:number;detail:string};
type EventRow={event_id:string;sequence:number;event_type:string;entity_type:string;entity_id:string;module_key:string;action:string;occurred_at:string;actor_key?:string|null;source:string;previous_hash?:string|null;event_hash:string;evidence:Record<string,any>;metadata:Record<string,any>};
type Forensic={risk_score:number;risk_level:'ok'|'warning'|'critical';signature:any;sla:{limit_minutes:number;age_minutes:number;inactive_minutes:number;breached:boolean};counts:{events:number;entities:number;anomalies:number};anomalies:Array<{severity:'warning'|'critical';code:string;title:string;detail:string;points:number}>};
type TraceDetail={trace:any;proof:any;signature?:any;forensics?:Forensic;stages:Stage[];events:EventRow[];entities:any[];verifications:any[];audit_events:any[];proof_model:any};
type Health={hmac_configured:boolean;sla_minutes:number;counts:{total:number;complete:number;incomplete:number;verified:number;broken:number;evented:number;unsigned_current:number;open_alerts:number;critical_alerts:number};recent_attention:any[];generated_at:string};
type Graph={nodes:Array<{id:string;type:string;label:string;module:string;status?:string;relation?:string}>;edges:Array<{from:string;to:string;type:string;label:string}>};
const BASE='/api/transactions/notifications/reconciliation/trace';
const typeName:Record<RootType,string>={work_order:'Munkalap',purchase_order:'Beszerzési rendelés',booking:'Foglalás',invoice:'Számla'};
const moduleName:Record<string,string>={booking:'Foglalás',workorder:'Munkalap',finance:'Pénzügy',procurement:'Beszerzés',inventory:'Készlet',root:'Gyökér'};
const statusName=(s:string)=>s==='ok'||s==='verified'||s==='complete'?'RENDBEN':s==='warning'||s==='stale'?'FIGYELEM':s==='broken'?'SÉRÜLT':'ELTÉRÉS';
const short=(v:unknown,n=18)=>{const s=String(v||'');return s.length>n?`${s.slice(0,n)}…`:s};
const fmt=(v:unknown)=>{try{return new Date(String(v)).toLocaleString('hu-HU')}catch{return String(v||'')}};

export default function TransactionTracePage(){
 const params=useMemo(()=>new URLSearchParams(window.location.search),[]);
 const[type,setType]=useState<RootType>((params.get('type') as RootType)||'work_order');
 const[id,setId]=useState(params.get('id')||'');
 const[data,setData]=useState<TraceDetail|null>(null),[health,setHealth]=useState<Health|null>(null),[graph,setGraph]=useState<Graph|null>(null),[recent,setRecent]=useState<any[]>([]),[results,setResults]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[backfilling,setBackfilling]=useState(false),[watching,setWatching]=useState(false),[exporting,setExporting]=useState(false),[notice,setNotice]=useState('');
 const locationId=localStorage.getItem('kleo_location_id')||'';
 const loadHealth=useCallback(async()=>{try{const p=new URLSearchParams({days:'30'});if(locationId)p.set('location_id',locationId);const r=await api.get(`${BASE}/health?${p}`);setHealth(r.data)}catch{}},[locationId]);
 const loadRecent=useCallback(async()=>{try{const p=new URLSearchParams({limit:'60'});if(locationId)p.set('location_id',locationId);const r=await api.get(`${BASE}/recent?${p}`);setRecent(r.data?.items||[])}catch{}},[locationId]);
 useEffect(()=>{void Promise.all([loadRecent(),loadHealth()])},[loadRecent,loadHealth]);
 useEffect(()=>{if(id)void load(type,id)},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function load(t:RootType=type,value:string=id){const clean=value.trim();if(!clean){setError('Add meg a tranzakció azonosítóját.');return}setLoading(true);setError('');setNotice('');try{const[r,g]=await Promise.all([api.get(`${BASE}/${encodeURIComponent(t)}/${encodeURIComponent(clean)}`),api.get(`${BASE}/${encodeURIComponent(t)}/${encodeURIComponent(clean)}/graph`)]);setData(r.data);setGraph(g.data);setType(t);setId(clean);window.history.replaceState(null,'',`/finance/transaction-trace?type=${encodeURIComponent(t)}&id=${encodeURIComponent(clean)}`);await Promise.all([loadRecent(),loadHealth()])}catch(e:any){setError(e?.response?.data?.message||'A tranzakció életútja nem tölthető be.')}finally{setLoading(false)}}
 async function verify(){if(!data)return;setLoading(true);setError('');try{const r=await api.post(`${BASE}/${encodeURIComponent(data.trace.root_type)}/${encodeURIComponent(data.trace.root_id)}/verify`);const ok=r.data?.proof?.result==='verified'&&r.data?.signature?.status==='verified';setNotice(ok?'A hash-lánc és a külső HMAC proof checkpoint is érvényes.':'A bizonyítási lánc ellenőrzést igényel.');await load(data.trace.root_type,data.trace.root_id)}catch(e:any){setError(e?.response?.data?.message||'Az ellenőrzés nem futtatható.')}finally{setLoading(false)}}
 async function search(){const clean=q.trim();if(clean.length<2){setResults([]);return}try{const r=await api.get(`${BASE}/search?q=${encodeURIComponent(clean)}&limit=40`);setResults(r.data?.items||[])}catch(e:any){setError(e?.response?.data?.message||'A keresés nem sikerült.')}}
 async function backfill(){setBackfilling(true);setError('');try{const r=await api.post(`${BASE}/backfill`,{days:30,limit:500});setNotice(`Backfill kész: ${r.data?.work_orders||0} munkalap, ${r.data?.purchase_orders||0} beszerzés, ${r.data?.verified||0} ellenőrzött trace, ${r.data?.broken||0} sérült.`);await Promise.all([loadRecent(),loadHealth()])}catch(e:any){setError(e?.response?.data?.message||'A backfill nem futtatható.')}finally{setBackfilling(false)}}
 async function watchdog(){setWatching(true);setError('');try{const r=await api.post(`${BASE}/watchdog`);setNotice(`Watchdog kész: ${r.data?.checked||0} trace ellenőrizve, ${r.data?.attention||0} eltérés, ${r.data?.critical||0} kritikus.`);await loadHealth()}catch(e:any){setError(e?.response?.data?.message||'A trace watchdog nem futtatható.')}finally{setWatching(false)}}
 async function exportProof(){if(!data)return;setExporting(true);setError('');try{const url=`${BASE}/${encodeURIComponent(data.trace.root_type)}/${encodeURIComponent(data.trace.root_id)}/proof-package`;const r=await api.get(url,{responseType:'blob'});const blob=new Blob([r.data],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`kleo-trace-${data.trace.root_type}-${String(data.trace.root_id).replace(/[^A-Za-z0-9._-]/g,'_')}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(href);setNotice('A kriptográfiailag ellenőrizhető bizonyítási csomag elkészült.')}catch(e:any){setError(e?.response?.data?.message||'A bizonyítási csomag nem exportálható.')}finally{setExporting(false)}}
 const proofOk=data?.proof?.result==='verified'&&data?.proof?.hash_chain_ok&&data?.proof?.sequence_ok;
 const signatureOk=data?.signature?.status==='verified';const forensic=data?.forensics;
 const groupedNodes=useMemo(()=>{const out=new Map<string,Graph['nodes']>();for(const node of graph?.nodes||[]){const key=node.module||'other';if(!out.has(key))out.set(key,[]);out.get(key)!.push(node)}return Array.from(out.entries())},[graph]);
 return <div className="trace-page">
  <header className="trace-hero"><div><span>PÉNZÜGYEK · TRANSACTION LIFECYCLE & FORENSICS</span><h1><GitBranch/> Tranzakció-életút</h1><p>Bizonyítható teljes üzleti életút, automatikus anomália- és SLA-felügyelet, append-only eseményledger, SHA-256 hash-chain, külső HMAC proof és exportálható auditcsomag.</p></div><div className="trace-hero-proof"><Fingerprint/><div><small>BIZONYÍTÁSI MODELL</small><b>Append-only · SHA-256 · HMAC</b><span>tamper-evident forensic ledger</span></div></div></header>
  {health&&<section className="trace-health"><article><Gauge/><div><small>30 NAPOS TRACE HEALTH</small><b>{health.counts.total-health.counts.broken-health.counts.incomplete}/{health.counts.total} tiszta</b><span>{health.counts.broken} sérült · {health.counts.incomplete} hiányos</span></div></article><article className={health.hmac_configured?'ok':'bad'}>{health.hmac_configured?<ShieldCheck/>:<ShieldX/>}<div><small>HMAC PROOF</small><b>{health.hmac_configured?'AKTÍV':'NINCS KONFIGURÁLVA'}</b><span>{health.counts.unsigned_current} aktuális aláíratlan trace</span></div></article><article className={health.counts.critical_alerts?'bad':'ok'}><BellRing/><div><small>TRACE WATCHDOG</small><b>{health.counts.open_alerts} nyitott riasztás</b><span>{health.counts.critical_alerts} kritikus</span></div></article><article><Clock3/><div><small>ÉLETÚT SLA</small><b>{health.sla_minutes} perc</b><span>automatikus breach detektálás</span></div></article></section>}
  <section className="trace-toolbar"><select value={type} onChange={e=>setType(e.target.value as RootType)}><option value="work_order">Munkalap</option><option value="purchase_order">Beszerzési rendelés</option><option value="booking">Foglalás</option><option value="invoice">Számla</option></select><input value={id} onChange={e=>setId(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()} placeholder="Azonosító / UUID"/><button className="primary" onClick={()=>load()} disabled={loading}><Search size={17}/>{loading?'Betöltés…':'Életút megnyitása'}</button><button onClick={watchdog} disabled={watching}><ShieldAlert size={17}/>{watching?'Watchdog…':'Watchdog futtatása'}</button><button onClick={backfill} disabled={backfilling}><Database size={17}/>{backfilling?'Backfill…':'30 nap backfill'}</button></section>
  <section className="trace-search"><div><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Keresés trace, rekord vagy kapcsolt entitás azonosítóra…"/><button onClick={search}>Keresés</button></div>{results.length>0&&<div className="trace-search-results">{results.map(x=><button key={x.trace_id} onClick={()=>load(x.root_type,x.root_id)}><b>{typeName[x.root_type as RootType]||x.root_type}</b><span>{x.root_id}</span><em className={x.integrity_status}>{statusName(x.integrity_status)}</em></button>)}</div>}</section>
  {error&&<div className="trace-error"><AlertTriangle/>{error}</div>}{notice&&<div className="trace-notice"><CheckCircle2/>{notice}</div>}
  {!data&&<section className="trace-empty"><Workflow/><h2>Válassz egy üzleti tranzakciót</h2><p>A rendszer a meglévő rekordokból is rekonstruálja a bizonyítási láncot, az új változásokat pedig automatikusan append-only eseményként rögzíti és watchdoggal ellenőrzi.</p></section>}
  {data&&<>
   <section className="trace-overview"><article><GitBranch/><div><small>TRACE ID</small><b title={data.trace.trace_id}>{short(data.trace.trace_id,24)}</b><span>{typeName[data.trace.root_type as RootType]||data.trace.root_type} · {data.trace.root_id}</span></div></article><article className={data.trace.lifecycle_status==='complete'?'ok':'bad'}>{data.trace.lifecycle_status==='complete'?<CheckCircle2/>:<AlertTriangle/>}<div><small>ÉLETÚT</small><b>{statusName(data.trace.lifecycle_status)}</b><span>{data.stages.filter(x=>x.status==='ok').length}/{data.stages.length} láncszem zöld</span></div></article><article className={proofOk&&signatureOk?'ok':'bad'}>{proofOk&&signatureOk?<ShieldCheck/>:<ShieldX/>}<div><small>KRIPTOGRÁFIAI BIZONYÍTÁS</small><b>{proofOk&&signatureOk?'TELJESEN HITELESÍTETT':'ELLENŐRZENDŐ'}</b><span>SHA-256: {proofOk?'OK':'HIBÁS'} · HMAC: {data.signature?.status||'nincs'}</span></div></article><article className={forensic?.risk_level==='ok'?'ok':forensic?'bad':''}><Gauge/><div><small>FORENSIC RISK SCORE</small><b>{forensic?`${forensic.risk_score}/100`:'—'}</b><span>{forensic?`${forensic.counts.anomalies} anomália · SLA ${forensic.sla.breached?'TÚLLÉPVE':'rendben'}`:'elemzés nincs'}</span></div></article></section>
   {forensic&&<section className={`trace-forensics ${forensic.risk_level}`}><div className="trace-risk"><Gauge/><div><small>AUTOMATIKUS FORENSIC ELEMZÉS</small><b>{forensic.risk_score}/100 · {forensic.risk_level==='ok'?'ALACSONY KOCKÁZAT':forensic.risk_level==='warning'?'VIZSGÁLANDÓ':'KRITIKUS'}</b><span>{forensic.counts.events} event · {forensic.counts.entities} entitás · {forensic.sla.age_minutes} perc életkor</span></div></div><div className="trace-forensic-actions"><button onClick={verify} disabled={loading}><ShieldCheck size={16}/> Teljes újraellenőrzés</button><button onClick={exportProof} disabled={exporting}><Download size={16}/>{exporting?'Export…':'Proof package export'}</button></div></section>}
   {forensic?.anomalies?.length?<section className="trace-card"><div className="trace-card-head"><div><h2><ShieldAlert/> Automatikusan észlelt anomáliák</h2><p>A watchdog ugyanilyen szabályok alapján riaszt; kritikus esetben vezetői e-mail is készül.</p></div><span className="trace-count">{forensic.anomalies.length}</span></div><div className="trace-anomalies">{forensic.anomalies.map(a=><article className={a.severity} key={a.code}><div><AlertTriangle/><b>{a.title}</b><em>+{a.points} kockázati pont</em></div><p>{a.detail}</p><code>{a.code}</code></article>)}</div></section>:null}
   <section className="trace-card"><div className="trace-card-head"><div><h2>Bizonyítható üzleti lánc</h2><p>Minden szakasz mögött konkrét rekord- és eseménybizonyíték található.</p></div><button onClick={verify} disabled={loading}><ShieldCheck size={16}/> Hash + HMAC újraellenőrzése</button></div><div className="trace-stage-flow">{data.stages.map((s,i)=><React.Fragment key={s.key}><article className={s.status}><div>{s.status==='ok'?<CheckCircle2/>:<AlertTriangle/>}</div><small>{i+1}. LÁNCSZEM</small><b>{s.label}</b><span>{s.detail}</span><em>{s.evidence_count} bizonyíték</em></article>{i<data.stages.length-1&&<div className="trace-arrow">→</div>}</React.Fragment>)}</div></section>
   <section className="trace-grid"><article className="trace-card trace-proof"><div className="trace-card-head"><div><h2><Fingerprint/> Proof of integrity</h2><p>Kettős bizonyítás: belső hash-chain + adatbázison kívüli secret kulccsal HMAC checkpoint.</p></div></div><dl><div><dt>Event algoritmus</dt><dd>SHA-256</dd></div><div><dt>Append-only</dt><dd>{data.proof_model?.append_only?'Igen':'Nem'}</dd></div><div><dt>Szekvencia</dt><dd className={data.proof?.sequence_ok?'oktxt':'badtxt'}>{data.proof?.sequence_ok?'Sértetlen':'Eltérés'}</dd></div><div><dt>Hash-lánc</dt><dd className={data.proof?.hash_chain_ok?'oktxt':'badtxt'}>{data.proof?.hash_chain_ok?'Sértetlen':'Eltérés'}</dd></div><div><dt>HMAC checkpoint</dt><dd className={signatureOk?'oktxt':'badtxt'}>{data.signature?.status||'nincs'}</dd></div><div><dt>HMAC key ID</dt><dd>{data.signature?.key_id||'—'}</dd></div><div><dt>Event count</dt><dd>{data.proof?.event_count||0}</dd></div><div><dt>Utolsó hash</dt><dd title={data.trace.last_hash}>{short(data.trace.last_hash,28)}</dd></div></dl></article><article className="trace-card"><div className="trace-card-head"><div><h2><Database/> Kapcsolt entitások</h2><p>A trace-hez bizonyíthatóan hozzárendelt adatbázis-rekordok.</p></div></div><div className="trace-entities">{data.entities.map((x:any)=><div key={`${x.entity_type}-${x.entity_id}`}><b>{x.entity_type}</b><span title={x.entity_id}>{short(x.entity_id,26)}</span><small>{fmt(x.first_seen_at)}</small></div>)}</div></article></section>
   {graph&&<section className="trace-card"><div className="trace-card-head"><div><h2><Network/> Függőségi gráf</h2><p>Modulonként mutatja a trace bizonyított rekordcsomópontjait és azok eseménysorrendi kapcsolatait.</p></div><span className="trace-count">{graph.nodes.length} node · {graph.edges.length} edge</span></div><div className="trace-graph">{groupedNodes.map(([module,nodes])=><article key={module}><header><b>{moduleName[module]||module}</b><span>{nodes.length} csomópont</span></header><div>{nodes.slice(0,24).map(node=><span key={node.id} title={node.id}><Network size={13}/><b>{node.type}</b><small>{short(node.label,24)}</small></span>)}</div></article>)}</div><details className="trace-edge-list"><summary>Eseménysorrendi kapcsolatok ({graph.edges.length})</summary>{graph.edges.slice(0,120).map((edge,i)=><div key={`${edge.from}-${edge.to}-${i}`}><code>{short(edge.from,30)}</code><b>→</b><code>{short(edge.to,30)}</code><span>{edge.label}</span></div>)}</details></section>}
   <section className="trace-card"><div className="trace-card-head"><div><h2><Clock3/> Eseménytimeline</h2><p>Időrendi, hash-láncolt eseménysor. A snapshot a régi adatból rekonstruált bizonyíték, a database-trigger az új automatikus esemény.</p></div><span className="trace-count">{data.events.length} esemény</span></div><div className="trace-timeline">{data.events.map(e=><article key={e.event_id}><div className="trace-dot">{e.sequence}</div><div className="trace-event-main"><div><b>{moduleName[e.module_key]||e.module_key} · {e.event_type}</b><span>{fmt(e.occurred_at)} · {e.source}{e.actor_key?` · ${e.actor_key}`:''}</span></div><p>{e.entity_type} · <code>{e.entity_id}</code></p><div className="trace-evidence">{Object.entries(e.evidence||{}).slice(0,10).map(([k,v])=><span key={k}><small>{k}</small><b>{String(v)}</b></span>)}</div><footer><Fingerprint size={13}/><code title={e.event_hash}>{short(e.event_hash,36)}</code></footer></div></article>)}</div></section>
   {data.audit_events?.length>0&&<section className="trace-card"><div className="trace-card-head"><div><h2><FileCheck2/> Emberi és rendszer-audit események</h2><p>A normál VIR auditlogból összekapcsolt, felhasználói kontextust tartalmazó műveletek.</p></div><span className="trace-count">{data.audit_events.length}</span></div><div className="trace-audit">{data.audit_events.slice(0,80).map((x:any)=><div key={x.id}><span>{fmt(x.occurred_at)}</span><b>{x.actor_name||x.actor_key||'rendszer'}</b><em>{x.module_key} · {x.action}</em><p>{x.summary}</p></div>)}</div></section>}
  </>}
  <aside className="trace-recent"><div><h2>Legutóbbi trace-ek</h2><button onClick={()=>void Promise.all([loadRecent(),loadHealth()])}><RefreshCw size={15}/></button></div><section>{recent.slice(0,30).map(x=><button key={x.trace_id} onClick={()=>load(x.root_type,x.root_id)}><div><b>{typeName[x.root_type as RootType]||x.root_type}</b><span>{short(x.root_id,24)}</span></div><em className={x.integrity_status}>{statusName(x.integrity_status)}</em><small>{x.event_count||0} event</small></button>)}</section></aside>
 </div>
}
