import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getLocations, LocationRow } from "../api/locations";
import { createVirAction, getVirActions, updateVirAction, VirActionItem, VirActionPriority, VirActionStatus } from "../api/virManagement";
import "./VirManagement.css";

const today=()=>new Date().toISOString().slice(0,10);
const priorityLabel:Record<VirActionPriority,string>={CRITICAL:"Kritikus",HIGH:"Magas",MEDIUM:"Közepes",LOW:"Alacsony"};
const statusLabel:Record<VirActionStatus,string>={OPEN:"Nyitott",IN_PROGRESS:"Folyamatban",BLOCKED:"Blokkolt",WAITING_APPROVAL:"Jóváhagyásra vár",DONE:"Kész"};
const statusClass:Record<VirActionStatus,string>={OPEN:"open",IN_PROGRESS:"progress",BLOCKED:"blocked",WAITING_APPROVAL:"approval",DONE:"done"};
const toLocalInput=(value?:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";

export default function VirActionCenterPage(){
 const navigate=useNavigate();
 const [locations,setLocations]=useState<LocationRow[]>([]);
 const [date,setDate]=useState(today());
 const [locationId,setLocationId]=useState("");
 const [status,setStatus]=useState<VirActionStatus|"">("");
 const [priority,setPriority]=useState<VirActionPriority|"">("");
 const [source,setSource]=useState("");
 const [items,setItems]=useState<VirActionItem[]>([]);
 const [loading,setLoading]=useState(false);
 const [error,setError]=useState("");
 const [savingId,setSavingId]=useState("");
 const [createOpen,setCreateOpen]=useState(false);
 const [draft,setDraft]=useState({title:"",description:"",priority:"MEDIUM" as VirActionPriority,source:"MANUAL",assignee_name:"",due_at:"",requires_approval:false});
 const [editors,setEditors]=useState<Record<string,{status:VirActionStatus;priority:VirActionPriority;assignee_name:string;due_at:string;evidence:string}>>({});
 useEffect(()=>{getLocations().then(setLocations).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const rows=await getVirActions({date,locationId:locationId||undefined,status,priority,source,limit:200});setItems(rows);setEditors(Object.fromEntries(rows.map(i=>[i.id,{status:i.status,priority:i.priority,assignee_name:i.assignee_name||"",due_at:toLocalInput(i.due_at),evidence:i.evidence||""}])));}catch(err:any){setError(err?.response?.data?.error||err?.message||"Az Akcióközpont nem tölthető be.");}finally{setLoading(false);}},[date,locationId,status,priority,source]);
 useEffect(()=>{load();},[load]);
 const counts=useMemo(()=>({open:items.filter(i=>i.status!=="DONE").length,critical:items.filter(i=>i.status!=="DONE"&&i.priority==="CRITICAL").length,approval:items.filter(i=>i.status==="WAITING_APPROVAL").length,done:items.filter(i=>i.status==="DONE").length}),[items]);
 const save=async(item:VirActionItem)=>{const editor=editors[item.id];if(!editor)return;setSavingId(item.id);setError("");try{await updateVirAction(item.id,{status:editor.status,priority:editor.priority,assignee_name:editor.assignee_name,due_at:editor.due_at?new Date(editor.due_at).toISOString():null,evidence:editor.evidence});await load();}catch(err:any){setError(err?.response?.data?.error||err?.message||"A feladat mentése sikertelen.");}finally{setSavingId("");}};
 const create=async()=>{if(!draft.title.trim())return;setSavingId("new");setError("");try{await createVirAction({title:draft.title.trim(),description:draft.description.trim(),priority:draft.priority,source:draft.source.trim()||"MANUAL",assignee_name:draft.assignee_name.trim()||null,due_at:draft.due_at?new Date(draft.due_at).toISOString():null,requires_approval:draft.requires_approval,location_id:locationId||null});setDraft({title:"",description:"",priority:"MEDIUM",source:"MANUAL",assignee_name:"",due_at:"",requires_approval:false});setCreateOpen(false);await load();}catch(err:any){setError(err?.response?.data?.error||err?.message||"A feladat létrehozása sikertelen.");}finally{setSavingId("");}};
 return <div className="vir-management-page">
  <div className="vir-management-header"><div><h1 className="vir-management-title">Egységes VIR Akcióközpont</h1><div className="vir-management-subtitle">HR, pénzügy, foglalás, minőség, készlet és vezetői jelzések egy közös munkasorban.</div></div><div className="vir-management-actions"><button className="vir-button secondary" onClick={()=>navigate("/admin/vir/cockpit")}>← Manager Cockpit</button><button className="vir-button" onClick={()=>setCreateOpen(v=>!v)}>{createOpen?"Bezárás":"+ Új feladat"}</button></div></div>
  {error&&<div className="vir-error">{error}</div>}
  <div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">Nyitott</div><div className="vir-kpi-value">{counts.open}</div></div><div className={counts.critical?"vir-kpi is-critical":"vir-kpi is-good"}><div className="vir-kpi-label">Kritikus</div><div className="vir-kpi-value">{counts.critical}</div></div><div className={counts.approval?"vir-kpi is-warning":"vir-kpi"}><div className="vir-kpi-label">Jóváhagyásra vár</div><div className="vir-kpi-value">{counts.approval}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Lezárt a listában</div><div className="vir-kpi-value">{counts.done}</div></div></div>
  {createOpen&&<section className="vir-panel vir-create-panel"><div className="vir-panel-header"><div className="vir-panel-title">Új vezetői feladat</div></div><div className="vir-create-grid"><input placeholder="Feladat címe" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as VirActionPriority})}><option value="CRITICAL">Kritikus</option><option value="HIGH">Magas</option><option value="MEDIUM">Közepes</option><option value="LOW">Alacsony</option></select><input placeholder="Forrás (pl. HR)" value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/><input placeholder="Felelős" value={draft.assignee_name} onChange={e=>setDraft({...draft,assignee_name:e.target.value})}/><textarea placeholder="Leírás / elvárt eredmény" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div><div className="vir-toolbar" style={{marginTop:10,marginBottom:0}}><label className="vir-field"><span>Határidő</span><input type="datetime-local" value={draft.due_at} onChange={e=>setDraft({...draft,due_at:e.target.value})}/></label><label style={{display:"flex",gap:8,alignItems:"center",fontSize:13}}><input type="checkbox" checked={draft.requires_approval} onChange={e=>setDraft({...draft,requires_approval:e.target.checked})}/> Jóváhagyást igényel</label><button className="vir-button" disabled={savingId==="new"||!draft.title.trim()} onClick={create}>Feladat létrehozása</button></div></section>}
  <section className="vir-panel"><div className="vir-toolbar"><label className="vir-field"><span>Dátum / jelzések</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="vir-field"><span>Státusz</span><select value={status} onChange={e=>setStatus(e.target.value as any)}><option value="">Mind</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="vir-field"><span>Prioritás</span><select value={priority} onChange={e=>setPriority(e.target.value as any)}><option value="">Mind</option>{Object.entries(priorityLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="vir-field"><span>Forrás</span><input value={source} placeholder="pl. HR" onChange={e=>setSource(e.target.value.toUpperCase())}/></label><button className="vir-button secondary" onClick={load}>Frissítés</button></div>
   {loading?<div className="vir-spinner">Akciók betöltése…</div>:<div className="vir-action-list">{items.length===0?<div className="vir-empty">Nincs a szűrésnek megfelelő feladat.</div>:items.map(item=>{const editor=editors[item.id];return <article key={item.id} className={`vir-action-card is-${item.priority.toLowerCase()}`}><div className="vir-action-card-head"><div><div className="vir-action-title">{item.title}</div><div className="vir-action-description">{item.description||"Nincs részletes leírás."}</div></div>{item.source_route&&<button className="vir-link-button" onClick={()=>navigate(item.source_route!)}>Forrás megnyitása →</button>}</div><div className="vir-badge-row"><span className={`vir-badge ${item.priority.toLowerCase()}`}>{priorityLabel[item.priority]}</span><span className={`vir-badge ${statusClass[item.status]}`}>{statusLabel[item.status]}</span><span className="vir-badge">{item.source}</span>{item.requires_approval&&<span className="vir-badge approval">Jóváhagyás szükséges</span>}{item.due_at&&<span className="vir-badge">Határidő: {new Date(item.due_at).toLocaleString("hu-HU")}</span>}</div>{editor&&<div className="vir-action-editor"><label><span>Státusz</span><select value={editor.status} onChange={e=>setEditors({...editors,[item.id]:{...editor,status:e.target.value as VirActionStatus}})}>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span>Prioritás</span><select value={editor.priority} onChange={e=>setEditors({...editors,[item.id]:{...editor,priority:e.target.value as VirActionPriority}})}>{Object.entries(priorityLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span>Felelős</span><input value={editor.assignee_name} onChange={e=>setEditors({...editors,[item.id]:{...editor,assignee_name:e.target.value}})}/></label><label><span>Határidő</span><input type="datetime-local" value={editor.due_at} onChange={e=>setEditors({...editors,[item.id]:{...editor,due_at:e.target.value}})}/></label><label className="wide"><span>Bizonyíték / megjegyzés</span><textarea value={editor.evidence} onChange={e=>setEditors({...editors,[item.id]:{...editor,evidence:e.target.value}})}/></label><div className="wide" style={{display:"flex",justifyContent:"flex-end"}}><button className="vir-button" disabled={savingId===item.id} onClick={()=>save(item)}>{savingId===item.id?"Mentés…":"Módosítás mentése"}</button></div></div>}</article>})}</div>}
  </section>
 </div>;
}
