import React,{useEffect,useMemo,useState}from"react";
import{Eye,History,LayoutDashboard,MonitorCog,Palette,RefreshCcw,Save,Settings2,ShieldCheck,SlidersHorizontal}from"lucide-react";
import api from"../api/api";
import{applyVirCustomization,type VirCustomization}from"../utils/virCustomization";
import{APPROVED_BRAND_COLORS,APPROVED_LOGO_ASSETS,DEFAULT_BRAND_ACCENT,DEFAULT_LOGO_ASSET,enforceBrandGuard}from"../utils/brandGuard";
import{useLanguage}from"../i18n/LanguageProvider";
import"./VirCustomizerPage.css";

type AuditRow={id:number;changed_at:string;changed_by?:string|null;before_config?:VirCustomization;after_config?:VirCustomization};
type Tab="brand"|"appearance"|"modules"|"labels"|"login"|"audit";
const MENU_KEYS=[
 ["dashboard","Irányítópult","Dashboard"],["appointments","Időpontok és foglalás","Appointments & booking"],["employees","Munkatársak / HR","Staff / HR"],["clients","Vendégek / CRM","Customers / CRM"],["finance","Pénzügy","Finance"],["warehouse","Raktár / beszerzés","Inventory / procurement"],["knowledge","Tudástár","Knowledge base"],["loyalty","Törzsvásárlói program","Loyalty program"],["marketing","Marketing","Marketing"],["webshop","Webshop","Webshop"],
] as const;
const FEATURE_LABELS:Record<string,[string,string]>={knowledge_base:["Tudástár","Knowledge base"],quiz:["Munkaköri vizsgák","Role exams"],loyalty:["Törzsvásárlói program","Loyalty program"],voice_booking:["Hangvezérelt foglalás","Voice booking"],wallboard:["WallBoard / TV","WallBoard / TV"],webshop:["Webshop","Webshop"]};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));

export default function VirCustomizerPage(){
 const{language,locale}=useLanguage();const L=(hu:string,en:string)=>language==="en"?en:hu;
 const err=(e:any)=>e?.response?.data?.message||e?.message||L("A művelet nem hajtható végre.","The operation could not be completed.");
 const[config,setConfig]=useState<VirCustomization|null>(null),[original,setOriginal]=useState<VirCustomization|null>(null),[audit,setAudit]=useState<AuditRow[]>([]),[tab,setTab]=useState<Tab>("brand"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const dirty=useMemo(()=>JSON.stringify(config)!==JSON.stringify(original),[config,original]);
 async function load(){setBusy(true);setMessage("");try{const[c,a]=await Promise.all([api.get("/transactions/knowledge-base/vir-customizer"),api.get("/transactions/knowledge-base/vir-customizer/audit")]);const next=enforceBrandGuard(c.data.config as VirCustomization);setConfig(clone(next));setOriginal(clone(next));setAudit(Array.isArray(a.data)?a.data:[]);applyVirCustomization(next)}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 function patch(section:keyof VirCustomization,key:string,value:any){setConfig(prev=>prev?({...prev,[section]:{...((prev as any)?.[section]||{}),[key]:value}}):prev)}
 async function save(){if(!config)return;setBusy(true);setMessage("");try{const guarded=enforceBrandGuard(config);const r=await api.put("/transactions/knowledge-base/vir-customizer",{config:guarded});const next=enforceBrandGuard(r.data.config as VirCustomization);setConfig(clone(next));setOriginal(clone(next));applyVirCustomization(next);setMessage(L("A VIR beállításai mentve és azonnal alkalmazva.","VIR settings were saved and applied immediately."));const a=await api.get("/transactions/knowledge-base/vir-customizer/audit");setAudit(Array.isArray(a.data)?a.data:[])}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function reset(){if(!window.confirm(L("Visszaállítja a teljes VIR megjelenést és modulbeállítást a központi alapértékekre?","Reset all VIR appearance and module settings to the central defaults?")))return;setBusy(true);setMessage("");try{const r=await api.post("/transactions/knowledge-base/vir-customizer/reset");const next=enforceBrandGuard(r.data.config as VirCustomization);setConfig(clone(next));setOriginal(clone(next));applyVirCustomization(next);setMessage(L("A VIR központi alapértékei visszaálltak.","Central VIR defaults were restored."));const a=await api.get("/transactions/knowledge-base/vir-customizer/audit");setAudit(Array.isArray(a.data)?a.data:[])}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 if(!config)return <main className="vir-customizer"><div className="vir-customizer-loading"><MonitorCog/><b>{L("VIR testreszabás betöltése…","Loading VIR customization…")}</b>{message&&<span>{message}</span>}</div></main>;
 const brand=config.brand||{},appearance=config.appearance||{},features=config.features||{},labels=config.labels||{},login=config.login||{},menu=config.menu_visibility||{};
 const previewAccent=String(brand.accent||DEFAULT_BRAND_ACCENT),logo=String(brand.logo_url||DEFAULT_LOGO_ASSET);
 return <main className="vir-customizer">
  <header className="vir-customizer-hero"><div><small>{L("ADMIN / KÖZPONTI KONFIGURÁCIÓ","ADMIN / CENTRAL CONFIGURATION")}</small><h1><SlidersHorizontal/>{L("VIR testreszabás","VIR customization")}</h1><p>{L("Arculat, megjelenés, modulok, menük és fő feliratok központi kezelése. A mentések auditnaplóba kerülnek.","Central management of branding, appearance, modules, menus and primary labels. Changes are audited.")}</p></div><div className="vir-customizer-actions"><button onClick={load} disabled={busy}><RefreshCcw/>{L("Frissítés","Refresh")}</button><button onClick={reset} disabled={busy}><RefreshCcw/>{L("Alapérték","Defaults")}</button><button className="primary" onClick={save} disabled={!dirty||busy}><Save/>{L("Mentés","Save")}</button></div></header>
  {message&&<div className="vir-customizer-message">{message}</div>}
  <section className="vir-customizer-security"><ShieldCheck/><div><b>{L("Központi, auditált és arculatvédett beállítás","Central, audited, brand-protected configuration")}</b><span>{L("A logó és a kiemelőszín csak az arculati kézikönyv engedélyezett elemei közül választható.","Logo and accent color can only be selected from approved brand-book assets.")}</span></div><strong>{dirty?L("Nem mentett módosítás","Unsaved changes"):L("Mentett állapot","Saved")}</strong></section>
  <div className="vir-customizer-layout">
   <aside className="vir-customizer-tabs">
    <button className={tab==="brand"?"active":""} onClick={()=>setTab("brand")}><Palette/>{L("Arculat","Brand")}</button>
    <button className={tab==="appearance"?"active":""} onClick={()=>setTab("appearance")}><Eye/>{L("Megjelenés","Appearance")}</button>
    <button className={tab==="modules"?"active":""} onClick={()=>setTab("modules")}><Settings2/>{L("Modulok és menük","Modules & menus")}</button>
    <button className={tab==="labels"?"active":""} onClick={()=>setTab("labels")}><LayoutDashboard/>{L("Feliratok","Labels")}</button>
    <button className={tab==="login"?"active":""} onClick={()=>setTab("login")}><MonitorCog/>{L("Belépőképernyő","Login screen")}</button>
    <button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}><History/>{L("Auditnapló","Audit log")}</button>
   </aside>
   <div className="vir-customizer-content">
    {tab==="brand"&&<section className="vir-customizer-card"><h2>{L("Arculati beállítások","Brand settings")}</h2><p>{L("A logó és a színválasztás kézikönyv-guard alatt áll; tetszőleges URL vagy HEX nem menthető.","Logo and color selection are protected by the brand guard; arbitrary URLs or HEX values cannot be saved.")}</p><div className="vir-form-grid"><label>{L("Rendszernév","System name")}<input value={String(brand.name||"")} onChange={e=>patch("brand","name",e.target.value)}/></label><label>{L("Rövid név","Short name")}<input value={String(brand.short_name||"")} onChange={e=>patch("brand","short_name",e.target.value)}/></label><label className="wide">{L("Jóváhagyott logó","Approved logo")}<select value={logo} onChange={e=>patch("brand","logo_url",e.target.value)}>{APPROVED_LOGO_ASSETS.map(asset=><option key={asset.value} value={asset.value}>{language==="en"?asset.labelEn:asset.labelHu}</option>)}</select></label><label>{L("Jóváhagyott kiemelőszín","Approved accent")}<select value={previewAccent} onChange={e=>patch("brand","accent",e.target.value)}>{APPROVED_BRAND_COLORS.map(color=><option key={color} value={color}>{color}</option>)}</select></label><label>{L("Lekerekítés (px)","Radius (px)")}<input type="number" min={4} max={32} value={Number(brand.radius||14)} onChange={e=>patch("brand","radius",Math.max(4,Math.min(32,Number(e.target.value)||14)))}/></label></div><div className="vir-color-input" aria-label={L("Engedélyezett arculati paletta","Approved brand palette")}>{APPROVED_BRAND_COLORS.map(color=><span key={color} title={color} style={{width:28,height:28,borderRadius:999,display:"inline-block",background:color,border:color===previewAccent?"3px solid currentColor":"1px solid #ddd",marginRight:6}}/>)}</div></section>}
    {tab==="appearance"&&<section className="vir-customizer-card"><h2>{L("Megjelenés","Appearance")}</h2><div className="vir-form-grid"><label>{L("Téma","Theme")}<select value={String(appearance.theme||"light")} onChange={e=>patch("appearance","theme",e.target.value)}><option value="light">{L("Világos","Light")}</option><option value="dark">{L("Sötét","Dark")}</option><option value="system">{L("Rendszerbeállítás követése","Follow system")}</option></select></label><label>{L("Felületi sűrűség","Density")}<select value={String(appearance.density||"comfortable")} onChange={e=>patch("appearance","density",e.target.value)}><option value="comfortable">{L("Kényelmes","Comfortable")}</option><option value="compact">{L("Kompakt","Compact")}</option></select></label><label>{L("Oldalsáv alapállapot","Default sidebar")}<select value={String(appearance.sidebar||"expanded")} onChange={e=>patch("appearance","sidebar",e.target.value)}><option value="expanded">{L("Kibontott","Expanded")}</option><option value="compact">{L("Kompakt","Compact")}</option></select></label><label className="wide">{L("Dashboard üdvözlés","Dashboard welcome")}<textarea rows={4} value={String(appearance.dashboard_welcome||"")} onChange={e=>patch("appearance","dashboard_welcome",e.target.value)}/></label></div></section>}
    {tab==="modules"&&<section className="vir-customizer-card"><h2>{L("Modulkapcsolók","Module switches")}</h2><p>{L("A kikapcsolt modulok a testreszabott menüből is elrejthetők.","Disabled modules can also be hidden from the customized menu.")}</p><div className="vir-toggle-grid">{Object.entries(features).map(([key,value])=><label className="vir-toggle" key={key}><span><b>{FEATURE_LABELS[key]?(language==="en"?FEATURE_LABELS[key][1]:FEATURE_LABELS[key][0]):key.replaceAll("_"," ")}</b><small>{key}</small></span><input type="checkbox" checked={Boolean(value)} onChange={e=>patch("features",key,e.target.checked)}/></label>)}</div><h2 className="section-gap">{L("Menü láthatóság","Menu visibility")}</h2><div className="vir-toggle-grid">{MENU_KEYS.map(([key,hu,en])=><label className="vir-toggle" key={key}><span><b>{language==="en"?en:hu}</b><small>{key}</small></span><input type="checkbox" checked={menu[key]!==false} onChange={e=>patch("menu_visibility",key,e.target.checked)}/></label>)}</div></section>}
    {tab==="labels"&&<section className="vir-customizer-card"><h2>{L("Fő feliratok","Primary labels")}</h2><p>{L("A kiemelt navigációs elnevezések központilag átírhatók.","Primary navigation labels can be changed centrally.")}</p><div className="vir-form-grid">{Object.entries(labels).map(([key,value])=><label key={key}>{key}<input value={String(value)} onChange={e=>patch("labels",key,e.target.value)}/></label>)}</div></section>}
    {tab==="login"&&<section className="vir-customizer-card"><h2>{L("Belépőképernyő","Login screen")}</h2><div className="vir-form-grid"><label className="wide">{L("Főcím","Headline")}<input value={String(login.headline||"")} onChange={e=>patch("login","headline",e.target.value)}/></label><label className="wide">{L("Alcím","Subtitle")}<textarea rows={5} value={String(login.subheadline||"")} onChange={e=>patch("login","subheadline",e.target.value)}/></label></div></section>}
    {tab==="audit"&&<section className="vir-customizer-card"><h2>{L("Utolsó konfigurációmódosítások","Recent configuration changes")}</h2><div className="vir-audit-list">{audit.length===0?<p>{L("Nincs naplózott módosítás.","No logged changes.")}</p>:audit.map(row=><article key={row.id}><History/><div><b>{row.changed_by||L("Ismeretlen felhasználó","Unknown user")}</b><span>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.changed_at))}</span></div><code>#{row.id}</code></article>)}</div></section>}
   </div>
   <aside className="vir-preview" style={{["--vir-preview-accent" as any]:previewAccent,borderRadius:Number(brand.radius||14)}}><div className="vir-preview-label"><Eye/>{L("Élő előnézet","Live preview")}</div><div className="vir-preview-window"><header><img src={logo} alt={L("Logó előnézet","Logo preview")}/><div><b>{String(brand.name||"Kleopátra VIR")}</b><small>{L("Admin felület","Admin workspace")}</small></div></header><nav><i/><strong>{String(labels.dashboard||L("Vezérlőpult","Dashboard"))}</strong></nav><nav><i/><strong>{String(labels.employees||L("Munkatársak","Staff"))}</strong></nav><nav><i/><strong>{String(labels.knowledge||L("Tudástár","Knowledge"))}</strong></nav><main><div className="vir-preview-kpi"><small>{L("Napi állapot","Daily status")}</small><b>98%</b></div><div className="vir-preview-box"><b>{String(appearance.dashboard_welcome||L("Üdvözlünk a Kleopátra VIR-ben!","Welcome to Kleopátra VIR!"))}</b><span>{L("A beállítások mentés után központilag érvényesülnek.","Settings take effect centrally after saving.")}</span></div></main></div></aside>
  </div>
 </main>;
}
