import React,{useEffect,useMemo,useState}from"react";
import{Eye,History,LayoutDashboard,MonitorCog,Palette,RefreshCcw,Save,Settings2,ShieldCheck,SlidersHorizontal}from"lucide-react";
import api from"../api/api";
import{applyVirCustomization,type VirCustomization}from"../utils/virCustomization";
import"./VirCustomizerPage.css";

type AuditRow={id:number;changed_at:string;changed_by?:string|null;before_config?:VirCustomization;after_config?:VirCustomization};
type Tab="brand"|"appearance"|"modules"|"labels"|"login"|"audit";
const MENU_KEYS=[
 ["dashboard","Irányítópult"],["appointments","Időpontok és foglalás"],["employees","Munkatársak / HR"],["clients","Vendégek / CRM"],["finance","Pénzügy"],["warehouse","Raktár / beszerzés"],["knowledge","Tudástár"],["loyalty","Törzsvásárlói program"],["marketing","Marketing"],["webshop","Webshop"],
] as const;
const FEATURE_LABELS:Record<string,string>={knowledge_base:"Tudástár",quiz:"Munkaköri vizsgák",loyalty:"Törzsvásárlói program",voice_booking:"Hangvezérelt foglalás",wallboard:"WallBoard / TV",webshop:"Webshop"};
const err=(e:any)=>e?.response?.data?.message||e?.message||"A művelet nem hajtható végre.";
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));

export default function VirCustomizerPage(){
 const[config,setConfig]=useState<VirCustomization|null>(null),[original,setOriginal]=useState<VirCustomization|null>(null),[audit,setAudit]=useState<AuditRow[]>([]),[tab,setTab]=useState<Tab>("brand"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const dirty=useMemo(()=>JSON.stringify(config)!==JSON.stringify(original),[config,original]);
 async function load(){setBusy(true);setMessage("");try{const[c,a]=await Promise.all([api.get("/transactions/knowledge-base/vir-customizer"),api.get("/transactions/knowledge-base/vir-customizer/audit")]);const next=c.data.config as VirCustomization;setConfig(clone(next));setOriginal(clone(next));setAudit(Array.isArray(a.data)?a.data:[]);applyVirCustomization(next)}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 function patch(section:keyof VirCustomization,key:string,value:any){setConfig(prev=>({...prev,[section]:{...((prev as any)?.[section]||{}),[key]:value}}))}
 async function save(){if(!config)return;setBusy(true);setMessage("");try{const r=await api.put("/transactions/knowledge-base/vir-customizer",{config});const next=r.data.config as VirCustomization;setConfig(clone(next));setOriginal(clone(next));applyVirCustomization(next);setMessage("A VIR beállításai mentve és azonnal alkalmazva.");const a=await api.get("/transactions/knowledge-base/vir-customizer/audit");setAudit(Array.isArray(a.data)?a.data:[])}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function reset(){if(!window.confirm("Visszaállítja a teljes VIR megjelenést és modulbeállítást a központi alapértékekre?"))return;setBusy(true);setMessage("");try{const r=await api.post("/transactions/knowledge-base/vir-customizer/reset");const next=r.data.config as VirCustomization;setConfig(clone(next));setOriginal(clone(next));applyVirCustomization(next);setMessage("A VIR központi alapértékei visszaálltak.");const a=await api.get("/transactions/knowledge-base/vir-customizer/audit");setAudit(Array.isArray(a.data)?a.data:[])}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 if(!config)return <main className="vir-customizer"><div className="vir-customizer-loading"><MonitorCog/><b>VIR testreszabás betöltése…</b>{message&&<span>{message}</span>}</div></main>;
 const brand=config.brand||{},appearance=config.appearance||{},features=config.features||{},labels=config.labels||{},login=config.login||{},menu=config.menu_visibility||{};
 const previewAccent=String(brand.accent||"#9b6b7a");
 return <main className="vir-customizer">
  <header className="vir-customizer-hero"><div><small>ADMIN / KÖZPONTI KONFIGURÁCIÓ</small><h1><SlidersHorizontal/>VIR testreszabás</h1><p>Arculat, megjelenés, modulok, menük és fő feliratok központi kezelése. A mentések auditnaplóba kerülnek.</p></div><div className="vir-customizer-actions"><button onClick={load} disabled={busy}><RefreshCcw/>Frissítés</button><button onClick={reset} disabled={busy}><RefreshCcw/>Alapérték</button><button className="primary" onClick={save} disabled={!dirty||busy}><Save/>Mentés</button></div></header>
  {message&&<div className="vir-customizer-message">{message}</div>}
  <section className="vir-customizer-security"><ShieldCheck/><div><b>Központi és auditált beállítás</b><span>A konfiguráció szerveroldalon tárolódik; a mentés után a megjelenés az aktuális munkamenetben is frissül.</span></div><strong>{dirty?"Nem mentett módosítás":"Mentett állapot"}</strong></section>
  <div className="vir-customizer-layout">
   <aside className="vir-customizer-tabs">
    <button className={tab==="brand"?"active":""} onClick={()=>setTab("brand")}><Palette/>Arculat</button>
    <button className={tab==="appearance"?"active":""} onClick={()=>setTab("appearance")}><Eye/>Megjelenés</button>
    <button className={tab==="modules"?"active":""} onClick={()=>setTab("modules")}><Settings2/>Modulok és menük</button>
    <button className={tab==="labels"?"active":""} onClick={()=>setTab("labels")}><LayoutDashboard/>Feliratok</button>
    <button className={tab==="login"?"active":""} onClick={()=>setTab("login")}><MonitorCog/>Belépőképernyő</button>
    <button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}><History/>Auditnapló</button>
   </aside>
   <div className="vir-customizer-content">
    {tab==="brand"&&<section className="vir-customizer-card"><h2>Arculati beállítások</h2><p>A fő név, logó, kiemelőszín és lekerekítés a VIR központi megjelenését vezérli.</p><div className="vir-form-grid"><label>Rendszernév<input value={String(brand.name||"")} onChange={e=>patch("brand","name",e.target.value)}/></label><label>Rövid név<input value={String(brand.short_name||"")} onChange={e=>patch("brand","short_name",e.target.value)}/></label><label className="wide">Logó URL<input placeholder="https://…" value={String(brand.logo_url||"")} onChange={e=>patch("brand","logo_url",e.target.value)}/></label><label>Kiemelőszín<div className="vir-color-input"><input type="color" value={previewAccent} onChange={e=>patch("brand","accent",e.target.value)}/><input value={previewAccent} onChange={e=>patch("brand","accent",e.target.value)}/></div></label><label>Lekerekítés (px)<input type="number" min={4} max={32} value={Number(brand.radius||14)} onChange={e=>patch("brand","radius",Math.max(4,Math.min(32,Number(e.target.value)||14)))}/></label></div></section>}
    {tab==="appearance"&&<section className="vir-customizer-card"><h2>Megjelenés</h2><div className="vir-form-grid"><label>Téma<select value={String(appearance.theme||"light")} onChange={e=>patch("appearance","theme",e.target.value)}><option value="light">Világos</option><option value="dark">Sötét</option><option value="system">Rendszerbeállítás követése</option></select></label><label>Felületi sűrűség<select value={String(appearance.density||"comfortable")} onChange={e=>patch("appearance","density",e.target.value)}><option value="comfortable">Kényelmes</option><option value="compact">Kompakt</option></select></label><label>Oldalsáv alapállapot<select value={String(appearance.sidebar||"expanded")} onChange={e=>patch("appearance","sidebar",e.target.value)}><option value="expanded">Kibontott</option><option value="compact">Kompakt</option></select></label><label className="wide">Dashboard üdvözlés<textarea rows={4} value={String(appearance.dashboard_welcome||"")} onChange={e=>patch("appearance","dashboard_welcome",e.target.value)}/></label></div></section>}
    {tab==="modules"&&<section className="vir-customizer-card"><h2>Modulkapcsolók</h2><p>A kikapcsolt modulok a testreszabott menüből is elrejthetők.</p><div className="vir-toggle-grid">{Object.entries(features).map(([key,value])=><label className="vir-toggle" key={key}><span><b>{FEATURE_LABELS[key]||key.replaceAll("_"," ")}</b><small>{key}</small></span><input type="checkbox" checked={Boolean(value)} onChange={e=>patch("features",key,e.target.checked)}/></label>)}</div><h2 className="section-gap">Menü láthatóság</h2><div className="vir-toggle-grid">{MENU_KEYS.map(([key,label])=><label className="vir-toggle" key={key}><span><b>{label}</b><small>{key}</small></span><input type="checkbox" checked={menu[key]!==false} onChange={e=>patch("menu_visibility",key,e.target.checked)}/></label>)}</div></section>}
    {tab==="labels"&&<section className="vir-customizer-card"><h2>Fő feliratok</h2><p>A kiemelt navigációs elnevezések központilag átírhatók.</p><div className="vir-form-grid">{Object.entries(labels).map(([key,value])=><label key={key}>{key}<input value={String(value)} onChange={e=>patch("labels",key,e.target.value)}/></label>)}</div></section>}
    {tab==="login"&&<section className="vir-customizer-card"><h2>Belépőképernyő</h2><div className="vir-form-grid"><label className="wide">Főcím<input value={String(login.headline||"")} onChange={e=>patch("login","headline",e.target.value)}/></label><label className="wide">Alcím<textarea rows={5} value={String(login.subheadline||"")} onChange={e=>patch("login","subheadline",e.target.value)}/></label></div></section>}
    {tab==="audit"&&<section className="vir-customizer-card"><h2>Utolsó konfigurációmódosítások</h2><div className="vir-audit-list">{audit.length===0?<p>Nincs naplózott módosítás.</p>:audit.map(row=><article key={row.id}><History/><div><b>{row.changed_by||"Ismeretlen felhasználó"}</b><span>{new Intl.DateTimeFormat("hu-HU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.changed_at))}</span></div><code>#{row.id}</code></article>)}</div></section>}
   </div>
   <aside className="vir-preview" style={{["--vir-preview-accent" as any]:previewAccent,borderRadius:Number(brand.radius||14)}}><div className="vir-preview-label"><Eye/>Élő előnézet</div><div className="vir-preview-window"><header>{brand.logo_url?<img src={String(brand.logo_url)} alt="Logó előnézet"/>:<span>{String(brand.short_name||"KLEO")}</span>}<div><b>{String(brand.name||"Kleopátra VIR")}</b><small>Admin felület</small></div></header><nav><i/><strong>{String(labels.dashboard||"Vezérlőpult")}</strong></nav><nav><i/><strong>{String(labels.employees||"Munkatársak")}</strong></nav><nav><i/><strong>{String(labels.knowledge||"Tudástár")}</strong></nav><main><div className="vir-preview-kpi"><small>Napi állapot</small><b>98%</b></div><div className="vir-preview-box"><b>{String(appearance.dashboard_welcome||"Üdvözlünk a Kleopátra VIR-ben!")}</b><span>A beállítások mentés után központilag érvényesülnek.</span></div></main></div></aside>
  </div>
 </main>;
}
