import React,{useEffect,useMemo,useState}from"react";
import{BarChart3,CalendarClock,RefreshCw,Repeat2,Target,TrendingUp,Users}from"lucide-react";
import api from"../api/api";
import"./VirReportExtras.css";

type HeatCell={weekday:number;hour:number;appointments:number;completed:number;no_show:number};
type Rebooking={eligible_visits:number;rebooked_visits:number;immediate_rebooked_visits:number;rebooking_rate_percent:number;immediate_rebooking_rate_percent:number;horizon_days:number;immediate_window_hours:number};
type StaffRow={employee_id:string;employee_name:string;revenue:number;workorders:number;paid_hours:number;service_hours:number;appointments:number;revenue_per_hour:number;utilization_percent:number|null;hour_source:string};
type BenchRow={location_id:string;name:string;appointments:number;completed:number;no_show:number;revenue:number;workorders:number;completion_rate_percent:number;no_show_rate_percent:number;rebooking_rate_percent:number;avg_ticket:number};
type BenchMetric={average:number;top_quartile:number};
type Payload={period:{from:string;to:string};heatmap:HeatCell[];rebooking:Rebooking;staff_revenue_hour:StaffRow[];benchmark:{current:BenchRow|null;network:Record<string,BenchMetric>;locations?:BenchRow[];location_count:number};source_status?:{ok:boolean;warnings:string[]}};

const weekdays=["H","K","Sze","Cs","P","Szo","V"];
const huf=(v:number)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
const num=(v:number)=>new Intl.NumberFormat("hu-HU",{maximumFractionDigits:1}).format(Number(v||0));
const pct=(v:number|null|undefined)=>v==null?"—":`${Number(v||0).toFixed(1)}%`;
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const monthStart=()=>{const d=new Date();return iso(new Date(d.getFullYear(),d.getMonth(),1))};
const tone=(value:number,avg:number,inverse=false)=>inverse?(value<=avg?"good":"watch"):(value>=avg?"good":"watch");

function Compare({label,value,average,top,format,inverse=false}:{label:string;value:number;average:number;top:number;format:(v:number)=>string;inverse?:boolean}){
 const delta=average?((value-average)/Math.abs(average))*100:0;
 return <article className={`vir-bi-compare ${tone(value,average,inverse)}`}><div><span>{label}</span><strong>{format(value)}</strong></div><div className="vir-bi-compare-lines"><p>Hálózati átlag <b>{format(average)}</b></p><p>Top 25% küszöb <b>{format(top)}</b></p><p className={inverse?delta<=0?"positive":"negative":delta>=0?"positive":"negative"}>{delta>=0?"+":""}{delta.toFixed(1)}% az átlaghoz képest</p></div></article>
}

export default function VirDecisionSupportPanel(){
 const[from,setFrom]=useState(monthStart()),[to,setTo]=useState(iso(new Date())),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const locationId=localStorage.getItem("kleo_location_id")||"";
 const load=async()=>{setLoading(true);setError("");try{const r=await api.get<Payload>("/transactions/cashier/management-summary/decision-support",{params:{from,to,location_id:locationId||undefined}});setData(r.data)}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||"A döntéstámogató BI adatok betöltése sikertelen.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[from,to,locationId]); // eslint-disable-line react-hooks/exhaustive-deps
 const heat=useMemo(()=>{const map=new Map<string,HeatCell>();for(const c of data?.heatmap||[])map.set(`${c.weekday}-${c.hour}`,c);return map},[data]);
 const hours=useMemo(()=>{const existing=(data?.heatmap||[]).map(x=>x.hour);const min=existing.length?Math.max(6,Math.min(...existing)):8,max=existing.length?Math.min(22,Math.max(...existing)):20;return Array.from({length:Math.max(1,max-min+1)},(_,i)=>min+i)},[data]);
 const maxHeat=Math.max(1,...(data?.heatmap||[]).map(x=>x.appointments));
 const rb=data?.rebooking,bench=data?.benchmark,current=bench?.current,network=bench?.network||{};
 const networkMetric=(key:string)=>network[key]||{average:0,top_quartile:0};
 return <section className="vir-bi-shell">
  <header className="vir-bi-header"><div><span className="vir-command-eyebrow"><BarChart3 size={13}/> DÖNTÉSTÁMOGATÓ BI</span><h2>Heatmap · Rebooking · Benchmark · Revenue/Hour</h2><p>A napi operációból közvetlenül döntéstámogató mutatók: mikor jön a kereslet, visszafoglal-e a vendég, hol áll a szalon a hálózathoz képest, és mennyi bevétel jut egy munkatársi órára.</p></div><div className="vir-bi-filter"><label>Kezdőnap<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Zárónap<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>void load()}><RefreshCw size={14}/>{loading?"Frissítés…":"Frissítés"}</button></div></header>
  {error&&<div className="vir-extra-alert">{error}</div>}
  {data?.source_status&&!data.source_status.ok&&<div className="vir-bi-warning">Néhány BI adatforrás részlegesen elérhető: {data.source_status.warnings.join(" · ")}</div>}

  <div className="vir-bi-grid">
   <section className="vir-command-card vir-bi-heatmap"><div className="vir-command-card-head"><div><span>KERESLETI MINTÁZAT</span><h2>Foglalási heatmap</h2><p>Foglalások sűrűsége hét napjai és órák szerint.</p></div><CalendarClock size={20}/></div><div className="vir-heatmap-wrap"><div className="vir-heatmap-grid" style={{gridTemplateColumns:`54px repeat(${hours.length},minmax(30px,1fr))`}}><div/>{hours.map(h=><div className="vir-heat-hour" key={h}>{h}:00</div>)}{weekdays.map((day,idx)=><React.Fragment key={day}><div className="vir-heat-day">{day}</div>{hours.map(h=>{const c=heat.get(`${idx+1}-${h}`),count=c?.appointments||0,intensity=count/maxHeat;return <div key={`${day}-${h}`} className="vir-heat-cell" title={`${day} ${h}:00 · ${count} foglalás · ${c?.completed||0} teljesített · ${c?.no_show||0} no-show`} style={{"--heat":String(intensity)} as React.CSSProperties}><strong>{count||""}</strong></div>})}</React.Fragment>)}</div></div><div className="vir-bi-footnote">Sötétebb cella = nagyobb foglalási sűrűség. A pontos cella fölé állva látható a teljesített és no-show darabszám is.</div></section>

   <section className="vir-command-card"><div className="vir-command-card-head"><div><span>VENDÉGMEGTARTÁS</span><h2>Rebooking</h2><p>A lezárt látogatások után van-e következő foglalás.</p></div><Repeat2 size={20}/></div><div className="vir-rebook-hero"><div className="vir-rebook-ring" style={{"--rb":`${Math.min(100,rb?.rebooking_rate_percent||0)*3.6}deg`} as React.CSSProperties}><div><strong>{pct(rb?.rebooking_rate_percent)}</strong><span>{rb?.rebooked_visits||0}/{rb?.eligible_visits||0}</span></div></div><div><small>90 napos rebooking arány</small><h3>{(rb?.rebooking_rate_percent||0)>=60?"Erős vendégmegtartás":(rb?.rebooking_rate_percent||0)>=40?"Fejleszthető":"Beavatkozást igényel"}</h3><p>A látogatás után {rb?.horizon_days||90} napon belül létrejövő következő foglalást számítjuk.</p></div></div><div className="vir-rebook-stats"><div><span>24 órán belüli újrafoglalás</span><b>{pct(rb?.immediate_rebooking_rate_percent)}</b></div><div><span>Újrafoglalt látogatások</span><b>{num(rb?.rebooked_visits||0)}</b></div><div><span>Értékelhető látogatások</span><b>{num(rb?.eligible_visits||0)}</b></div></div></section>
  </div>

  <div className="vir-bi-grid lower">
   <section className="vir-command-card"><div className="vir-command-card-head"><div><span>HÁLÓZATI ÖSSZEHASONLÍTÁS</span><h2>Benchmark</h2><p>{bench?.location_count||0} aktív szalon alapján számított hálózati átlag és top 25% küszöb.</p></div><Target size={20}/></div>{current?<div className="vir-bi-compare-grid"><Compare label="Bevétel" value={current.revenue} {...networkMetric("revenue")} average={networkMetric("revenue").average} top={networkMetric("revenue").top_quartile} format={huf}/><Compare label="Foglalások" value={current.appointments} average={networkMetric("appointments").average} top={networkMetric("appointments").top_quartile} format={v=>num(v)}/><Compare label="Teljesítési arány" value={current.completion_rate_percent} average={networkMetric("completion_rate_percent").average} top={networkMetric("completion_rate_percent").top_quartile} format={v=>pct(v)}/><Compare label="No-show arány" value={current.no_show_rate_percent} average={networkMetric("no_show_rate_percent").average} top={networkMetric("no_show_rate_percent").top_quartile} format={v=>pct(v)} inverse/><Compare label="Rebooking" value={current.rebooking_rate_percent} average={networkMetric("rebooking_rate_percent").average} top={networkMetric("rebooking_rate_percent").top_quartile} format={v=>pct(v)}/><Compare label="Átlagos kosár" value={current.avg_ticket} average={networkMetric("avg_ticket").average} top={networkMetric("avg_ticket").top_quartile} format={huf}/></div>:<div className="vir-bi-leaderboard"><div className="vir-bi-leaderboard-head"><Users size={16}/><b>Szalonrangsor</b></div><div className="vir-extra-table-wrap"><table className="vir-extra-table"><thead><tr><th>Szalon</th><th>Bevétel</th><th>Foglalás</th><th>Teljesülés</th><th>No-show</th><th>Rebooking</th></tr></thead><tbody>{(bench?.locations||[]).slice(0,12).map((x,i)=><tr key={x.location_id}><td><b>#{i+1} {x.name}</b></td><td>{huf(x.revenue)}</td><td>{num(x.appointments)}</td><td>{pct(x.completion_rate_percent)}</td><td>{pct(x.no_show_rate_percent)}</td><td>{pct(x.rebooking_rate_percent)}</td></tr>)}</tbody></table></div></div>}</section>

   <section className="vir-command-card"><div className="vir-command-card-head"><div><span>MUNKATÁRSI TERMELÉKENYSÉG</span><h2>Revenue / Hour</h2><p>Bevétel munkaórára vetítve, fizetett idő és szolgáltatási idő összevetésével.</p></div><TrendingUp size={20}/></div><div className="vir-extra-table-wrap"><table className="vir-extra-table vir-rph-table"><thead><tr><th>Munkatárs</th><th>Revenue / Hour</th><th>Bevétel</th><th>Fizetett óra</th><th>Szolgáltatási óra</th><th>Kihasználtság</th></tr></thead><tbody>{(data?.staff_revenue_hour||[]).slice(0,15).map((x,i)=><tr key={x.employee_id||i}><td><b>{x.employee_name}</b><small>{x.hour_source==="timesheet"?"Munkaidő-nyilvántartás":x.hour_source==="appointment_duration"?"Foglalási időből becsülve":"Nincs időadat"}</small></td><td><strong>{huf(x.revenue_per_hour)}</strong></td><td>{huf(x.revenue)}</td><td>{num(x.paid_hours)} h</td><td>{num(x.service_hours)} h</td><td><span className={`vir-rph-util ${(x.utilization_percent||0)>=70?"good":"watch"}`}>{pct(x.utilization_percent)}</span></td></tr>)}{!(data?.staff_revenue_hour||[]).length&&!loading&&<tr><td colSpan={6}>Nincs értékelhető munkatársi idő- és bevételadat az időszakban.</td></tr>}</tbody></table></div><div className="vir-bi-footnote">Elsődleges óraforrás a munkaidő-nyilvántartás. Ha nincs rögzített munkaidő, a rendszer a tényleges foglalási időből képez operatív Revenue/Hour becslést.</div></section>
  </div>
 </section>
}
