import React,{useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {getLocations,type LocationRow} from '../api/locations';
import {dismissP18Proposal,generateP18Proposals,getP18Proposals,getP18Status,promoteP18Proposal,type P18Proposal} from '../api/virP18';
import {useLanguage} from '../i18n/LanguageProvider';
import VirIntelligenceFlowNav from './VirIntelligenceFlowNav';
import './VirWorkspace.css';
export default function VirP18Page(){
 const{language}=useLanguage();const en=language==='en';const t=useCallback((hu:string,enText:string)=>en?enText:hu,[en]);const[status,setStatus]=useState<any>(null),[items,setItems]=useState<P18Proposal[]>([]),[locations,setLocations]=useState<LocationRow[]>([]),[locationId,setLocationId]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[lastRun,setLastRun]=useState<any>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[s,p]=await Promise.all([getP18Status(),getP18Proposals()]);setStatus(s);setItems(Array.isArray(p?.items)?p.items:[])}catch(e:any){setError(e?.response?.data?.error||e?.message||t('A döntési javaslatok nem tölthetők be.','Decision proposals could not be loaded.'))}finally{setLoading(false)}},[t]);useEffect(()=>{void load();void getLocations().then(setLocations).catch(()=>setLocations([]))},[load]);
 const generate=async()=>{setLoading(true);setError('');try{setLastRun(await generateP18Proposals({locationId:locationId||undefined}));await load()}catch(e:any){setError(e?.response?.data?.error||e?.message||'generate_failed')}finally{setLoading(false)}};const act=async(id:string,kind:'promote'|'dismiss')=>{setLoading(true);setError('');try{if(kind==='promote')await promoteP18Proposal(id);else await dismissP18Proposal(id);await load()}catch(e:any){setError(e?.response?.data?.error||e?.message||'proposal_action_failed')}finally{setLoading(false)}};
 return <div className="vir-workspace"><VirIntelligenceFlowNav current="proposals" en={en}/><header className="vir-workspace-hero"><h1>{t('Operatív döntési javaslatok','Operational decision proposals')}</h1><p>{t('A vezetői jelzésekből és operatív KPI-kból végrehajtható javaslatokat készít. A rendszer nem hajtja végre őket: a kiválasztott javaslat külön jóváhagyási folyamatba kerül.','Creates actionable proposals from executive signals and operational KPIs. The system does not execute them: selected proposals enter a separate approval workflow.')}</p></header>
  {status&&<div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Nyitott javaslat','Open proposals')}</span><strong>{status.counts?.proposed??0}</strong></div><div className="vir-stat-card"><span>{t('Jóváhagyásra elküldve','Sent for approval')}</span><strong>{status.counts?.promoted??0}</strong></div><div className="vir-stat-card"><span>{t('Közvetlen végrehajtás','Direct execution')}</span><strong>{t('TILTVA','BLOCKED')}</strong></div></div>}{error&&<div className="vir-error-friendly">{error}</div>}
  <section className="vir-panel"><h2>{t('Javaslatgenerálás','Proposal generation')}</h2><div className="vir-form-grid"><label>{t('Telephely','Location')}<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">{t('Összes telephely','All locations')}</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void generate()}>{t('Döntési javaslatok frissítése','Refresh decision proposals')}</button><Link className="vir-btn secondary" to="/admin/vir/p16">{t('Vezetői jelzések ellenőrzése','Review executive signals')}</Link></div>{lastRun&&<div className="vir-help">{t('Észlelt','Detected')}: {lastRun.generated??0} · {t('Új','New')}: {lastRun.created??0}</div>}</section>
  <section className="vir-panel"><h2>{t('Aktív javaslatok','Active proposals')}</h2>{items.length===0?<div className="vir-empty-state">{t('Jelenleg nincs aktív operatív javaslat.','There are no active operational proposals.')}</div>:<div className="vir-result-list">{items.map(x=><article key={x.id} className="vir-result-card"><span className={`vir-chip ${x.priority==='critical'?'danger':x.priority==='high'?'warning':''}`}>{x.priority.toUpperCase()} · {Math.round(Number(x.confidence||0)*100)}%</span><h4>{x.title}</h4><p>{x.reason}</p><small>{t('Forrás','Source')}: {x.source_type} · {t('Állapot','Status')}: {x.status}</small>{x.status==='proposed'&&<div className="vir-toolbar"><button className="vir-btn success" disabled={loading} onClick={()=>void act(x.id,'promote')}>{t('Jóváhagyásra küldés','Send for approval')}</button><button className="vir-btn danger" disabled={loading} onClick={()=>void act(x.id,'dismiss')}>{t('Elvetés','Dismiss')}</button></div>}{x.status==='promoted'&&<Link className="vir-btn secondary" to="/admin/vir/p17">{t('Jóváhagyási központ megnyitása','Open approval center')}</Link>}</article>)}</div>}</section>
  <div className="vir-help"><strong>{t('Irányítás:','Governance:')}</strong> {t('a rendszer önállóan nem módosít foglalást, beosztást, árat, kampányt vagy pénzügyi adatot.','the system never changes bookings, schedules, pricing, campaigns, or financial data by itself.')}</div></div>;
}