import React,{useCallback,useEffect,useState} from 'react';
import {getLocations,type LocationRow} from '../api/locations';
import {createP19Snapshot,getP19ExecutiveBrief,getP19Forecast,getP19Status,type P19Forecast} from '../api/virP19';
import {useLanguage} from '../i18n/LanguageProvider';
import VirP20P22Panel from './VirP20P22Panel';
import './VirWorkspace.css';

export default function VirP19Page(){
  const{language}=useLanguage();const en=language==='en';const t=useCallback((hu:string,enText:string)=>en?enText:hu,[en]);
  const[status,setStatus]=useState<any>(null),[forecast,setForecast]=useState<P19Forecast|null>(null),[brief,setBrief]=useState<any>(null),[locations,setLocations]=useState<LocationRow[]>([]),[locationId,setLocationId]=useState(''),[days,setDays]=useState<7|30|90>(30),[loading,setLoading]=useState(false),[error,setError]=useState('');
  useEffect(()=>{void getP19Status().then(setStatus).catch(()=>undefined);void getLocations().then(setLocations).catch(()=>setLocations([]));},[]);
  const run=useCallback(async()=>{setLoading(true);setError('');try{const r=await getP19Forecast({days,locationId:locationId||undefined});setForecast(r.forecast);}catch(e:any){setError(e?.response?.data?.error||e?.message||t('Az előrejelzés nem készíthető el.','Forecast could not be generated.'));}finally{setLoading(false);}},[days,locationId,t]);
  const snapshot=async()=>{setLoading(true);setError('');try{const r=await createP19Snapshot({days,locationId:locationId||undefined});setForecast(r.forecast);setStatus(await getP19Status());}catch(e:any){setError(e?.response?.data?.error||e?.message||'snapshot_failed');}finally{setLoading(false)}};
  const loadBrief=async()=>{setLoading(true);setError('');try{setBrief(await getP19ExecutiveBrief({locationId:locationId||undefined}));}catch(e:any){setError(e?.response?.data?.error||e?.message||'brief_failed');}finally{setLoading(false)}};
  const money=(n:number)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(n||0));
  return <div className="vir-workspace"><header className="vir-workspace-hero"><h1>{t('Prediktív és önoptimalizáló VIR · P19–P22','Predictive & Self-Optimizing VIR · P19–P22')}</h1><p>{t('P19 trend-előrejelzés, P20 validált modell, P21 AI döntéstámogatás és P22 visszacsatolt optimalizálás egy vezetői folyamatban.','P19 trend forecasting, P20 validated modeling, P21 AI decision support, and P22 feedback optimization in one executive workflow.')}</p></header>
    {status&&<div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('P19 mentett előrejelzések','P19 saved forecasts')}</span><strong>{status.counts?.snapshots??0}</strong></div><div className="vir-stat-card"><span>{t('Alapmodell','Base model')}</span><strong>Trend v1</strong></div><div className="vir-stat-card"><span>{t('Kontroll nélküli végrehajtás','Uncontrolled execution')}</span><strong>{t('TILTVA','BLOCKED')}</strong></div></div>}
    {error&&<div className="vir-error-friendly">{error}</div>}
    <section className="vir-panel"><h2>P19 · {t('Alap prediktív nézet','Base predictive view')}</h2><div className="vir-form-grid"><label>{t('Időtáv','Horizon')}<select value={days} onChange={e=>setDays(Number(e.target.value) as 7|30|90)}><option value={7}>7 {t('nap','days')}</option><option value={30}>30 {t('nap','days')}</option><option value={90}>90 {t('nap','days')}</option></select></label><label>{t('Telephely','Location')}<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">{t('Összes telephely','All locations')}</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void run()}>{t('P19 előrejelzés','P19 forecast')}</button><button className="vir-btn secondary" disabled={loading} onClick={()=>void snapshot()}>{t('P19 snapshot mentése','Save P19 snapshot')}</button><button className="vir-btn secondary" disabled={loading} onClick={()=>void loadBrief()}>{t('Vezetői prediktív brief','Predictive executive brief')}</button></div></section>
    {forecast&&<><div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Várható árbevétel','Forecast revenue')}</span><strong>{money(forecast.revenue_forecast)}</strong></div><div className="vir-stat-card"><span>{t('Várható foglalások','Forecast bookings')}</span><strong>{forecast.booking_forecast}</strong></div><div className="vir-stat-card"><span>No-show {t('kockázat','risk')}</span><strong>{forecast.no_show_risk_percent.toFixed(1)}%</strong></div><div className="vir-stat-card"><span>{t('Kapacitásnyomás','Capacity pressure')}</span><strong>{forecast.capacity_pressure}</strong></div><div className="vir-stat-card"><span>{t('Bizalmi szint','Confidence')}</span><strong>{Math.round(forecast.confidence*100)}%</strong></div></div><section className="vir-panel"><h2>{t('P19 fő hajtóerők','P19 key drivers')}</h2><div className="vir-result-list"><article className="vir-result-card"><h4>{t('Árbevételi trend','Revenue trend')}</h4><p>{forecast.drivers?.revenue_trend_percent??0}% · {t('friss napi átlag','recent daily average')}: {money(forecast.drivers?.recent_daily_revenue??0)}</p></article><article className="vir-result-card"><h4>{t('Foglalási trend','Booking trend')}</h4><p>{forecast.drivers?.booking_trend_percent??0}% · {t('következő 7 nap','next 7 days')}: {forecast.drivers?.future_bookings_7d??0}</p></article></div><div className="vir-help">{t('A P19 modell determinisztikus trend-előrejelzés; az eredmény nem garantált jövőbeni bevétel.','The P19 model is a deterministic trend forecast; results are not a guarantee of future revenue.')}</div></section></>}
    {brief&&<section className="vir-panel"><h2>{t('Vezetői prediktív brief','Predictive executive brief')}</h2><h3>{brief.headline}</h3><div className="vir-result-list">{Array.isArray(brief.alerts)&&brief.alerts.length?brief.alerts.map((a:any,i:number)=><article key={i} className="vir-result-card"><span className={`vir-chip ${a.priority==='high'?'warning':''}`}>{a.priority}</span><h4>{a.title}</h4><p>{a.reason}</p></article>):<div className="vir-help">{t('Nincs kiemelt prediktív riasztás.','No highlighted predictive alert.')}</div>}</div><details className="vir-json-details"><summary>{t('Technikai részletek','Technical details')}</summary><pre>{JSON.stringify(brief,null,2)}</pre></details></section>}
    <VirP20P22Panel locationId={locationId} days={days} en={en}/>
  </div>;
}
