import React,{useEffect,useState} from 'react';
import {getP9Campaigns,getP9Segments,getP9ChannelOptimizer,getP9Funnel,getP9Roi,getP9NextBestActions,getP9AbTests,getP9Attribution,getP9Suggestions,getP9Compliance} from '../api/virP9';
import {useLanguage} from '../i18n/LanguageProvider';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';
type Tab='campaigns'|'optimizer'|'funnel'|'roi'|'segments'|'nba'|'ab'|'attr'|'suggestions'|'compliance';
const TAB_LABELS:Record<Tab,{hu:string;en:string}>={campaigns:{hu:'51. Kampánykezelő',en:'51. Campaign Manager'},optimizer:{hu:'52. AI csatornaoptimalizáló 2.0',en:'52. AI Channel Optimizer 2.0'},funnel:{hu:'53. Konverziós tölcsér',en:'53. Conversion Funnel'},roi:{hu:'54. Kampány-megtérülés',en:'54. Campaign ROI'},segments:{hu:'55. Vendégszegmensek',en:'55. Customer Segments'},nba:{hu:'56. Következő legjobb akció',en:'56. Next Best Action'},ab:{hu:'57. A/B tesztelés',en:'57. A/B Testing'},attr:{hu:'58. Hozzárendelés 3.0',en:'58. Attribution 3.0'},suggestions:{hu:'59. Kampányjavaslatok',en:'59. Campaign Suggestions'},compliance:{hu:'60. Megfelelőségi központ',en:'60. Compliance Center'}};
const COLUMN_LABELS:Record<string,{hu:string;en:string}>={name:{hu:'Név',en:'Name'},objective:{hu:'Cél',en:'Objective'},segment_key:{hu:'Szegmens',en:'Segment'},status:{hu:'Állapot',en:'Status'},recipients:{hu:'Címzettek',en:'Recipients'},created_at:{hu:'Létrehozva',en:'Created'},client_id:{hu:'Vendégazonosító',en:'Customer ID'},client_name:{hu:'Vendég',en:'Customer'},recommended_channel:{hu:'Ajánlott csatorna',en:'Recommended channel'},campaign:{hu:'Kampány',en:'Campaign'},channel:{hu:'Csatorna',en:'Channel'},messages:{hu:'Üzenetek',en:'Messages'},delivered:{hu:'Kézbesítve',en:'Delivered'},opened:{hu:'Megnyitva',en:'Opened'},clicked:{hu:'Kattintások',en:'Clicked'},bookings:{hu:'Foglalások',en:'Bookings'},work_orders:{hu:'Munkalapok',en:'Work orders'},paid_revenue:{hu:'Fizetett bevétel',en:'Paid revenue'},campaign_id:{hu:'Kampányazonosító',en:'Campaign ID'},communication_cost:{hu:'Kommunikációs költség',en:'Communication cost'},roi:{hu:'Megtérülés',en:'ROI'},revenue_per_message:{hu:'Bevétel/üzenet',en:'Revenue/message'},days_since_visit:{hu:'Utolsó látogatás óta',en:'Days since visit'},visits:{hu:'Látogatások',en:'Visits'},segments:{hu:'Szegmensek',en:'Segments'},action:{hu:'Akció',en:'Action'},offer:{hu:'Ajánlat',en:'Offer'},timing:{hu:'Időzítés',en:'Timing'},rationale:{hu:'Indoklás',en:'Rationale'},variant:{hu:'Változat',en:'Variant'},clicks:{hu:'Kattintások',en:'Clicks'},touches:{hu:'Érintések',en:'Touches'},attributed_paid_revenue:{hu:'Hozzárendelt fizetett bevétel',en:'Attributed paid revenue'},transactional_consent:{hu:'Tranzakciós hozzájárulás',en:'Transactional consent'},marketing_consent:{hu:'Marketing-hozzájárulás',en:'Marketing consent'},lawful_basis:{hu:'Jogalap',en:'Lawful basis'},opted_out_at:{hu:'Leiratkozás',en:'Opted out'},communication_blocked:{hu:'Kommunikáció tiltva',en:'Communication blocked'},block_reason:{hu:'Tiltás oka',en:'Block reason'}};
const fmt=(v:any,locale:string)=>Number(v||0).toLocaleString(locale);
export default function VirP9Page(){const{language}=useLanguage();const en=language==='en';const lang=en?'en':'hu';const t=(hu:string,enText:string)=>en?enText:hu;const[tab,setTab]=useState<Tab>('campaigns');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[err,setErr]=useState('');const[locationId,setLocationId]=useState('');useEffect(()=>{let alive=true;setLoading(true);setErr('');const p={locationId:locationId||undefined};const fn=tab==='campaigns'?getP9Campaigns:tab==='optimizer'?getP9ChannelOptimizer:tab==='funnel'?getP9Funnel:tab==='roi'?getP9Roi:tab==='segments'?getP9Segments:tab==='nba'?getP9NextBestActions:tab==='ab'?getP9AbTests:tab==='attr'?getP9Attribution:tab==='suggestions'?getP9Suggestions:getP9Compliance;fn(p).then(x=>alive&&setData(x)).catch(e=>alive&&setErr(e?.response?.data?.message||e?.response?.data?.error||e?.message||t('Betöltési hiba','Loading error'))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[tab,locationId,en]);const rows=data?.items||data?.gaps||[];return <div className="vir-workspace"><header className="vir-workspace-hero"><h1>{t('Marketing- és kommunikációautomatizálás','Marketing & Communication Automation')}</h1><p>{t('Többcsatornás kampányok, fizetett bevétel-alapú optimalizálás és megfelelőség egy helyen. A tényleges kiküldés Előnézet → Jóváhagyás → Végrehajtás kontroll alatt marad.','Omnichannel campaigns, paid revenue optimization and compliance in one place. Actual sending remains under Preview → Approval → Execute control.')}</p></header><section className="vir-panel"><h2>{t('Telephely szűrés','Location filter')}</h2><p className="vir-panel-subtitle">{t('Keress szalonnév alapján; üresen a teljes hálózatot látod.','Search by salon name; leave empty for the full network.')}</p><VirSearchSelect kind="locations" label={t('Telephely','Location')} value={locationId} onChange={setLocationId} optional placeholder={t('Szalon keresése...','Search location...')}/></section><div className="vir-tabs">{(Object.keys(TAB_LABELS) as Tab[]).map(k=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{TAB_LABELS[k][lang]}</button>)}</div>{loading&&<div className="vir-help">{t('Betöltés…','Loading…')}</div>}{err&&<div className="vir-error-friendly">{err}</div>}
{tab==='campaigns'&&<Panel title={t('Többcsatornás kampánykezelő','Omnichannel Campaign Manager')} text={t('Viber, Messenger, e-mail, SMS és push kampányok közös életciklusa. A kampány előnézhető és vezetőileg jóváhagyható; közvetlen szolgáltatói kiküldés nincs.','Shared lifecycle for Viber, Messenger, email, SMS and push campaigns. Campaigns can be previewed and approved; there is no direct provider sending.')}><SimpleTable rows={rows} keys={['name','objective','segment_key','status','recipients','created_at']} en={en}/></Panel>}
{tab==='optimizer'&&<Panel title={t('AI csatornaoptimalizáló 2.0','AI Channel Optimizer 2.0')} text={t('Kézbesítés, olvasás, kattintás, válasz, foglalás, fizetett bevétel, költség és hozzájárulás alapján rangsorolja a csatornákat. Automatikus küldés nincs.','Ranks channels using delivery, read, click, response, booking, paid revenue, cost and consent. Automatic sending is disabled.')}><SimpleTable rows={rows} keys={['client_id','recommended_channel']} en={en}/></Panel>}
{tab==='funnel'&&<Panel title={t('Konverziós tölcsér','Conversion Funnel')} text={t('Üzenet → kézbesítés → megnyitás → kattintás → foglalás → munkalap → tényleges fizetés.','Message → delivery → open → click → booking → work order → actual payment.')}><SimpleTable rows={rows} keys={['campaign','channel','messages','delivered','opened','clicked','bookings','work_orders','paid_revenue']} en={en}/></Panel>}
{tab==='roi'&&<Panel title={t('Kampány-megtérülési irányítópult','Campaign ROI Dashboard')}><SimpleTable rows={rows} keys={['campaign_id','name','channel','messages','communication_cost','bookings','paid_revenue','roi','revenue_per_message']} en={en}/></Panel>}
{tab==='segments'&&<Panel title={t('Automatikus vendégszegmensek','Automatic Customer Segments')} text={t('30/60/90 napos inaktivitás, lemorzsolódási jelzés, VIP, rendszeres újrafoglaló és árazási érzékenység-proxy.','30/60/90-day inactivity, churn signal, VIP, regular rebooker and price-sensitivity proxy.')}><SimpleTable rows={rows} keys={['client_name','days_since_visit','visits','paid_revenue','segments']} en={en}/></Panel>}
{tab==='nba'&&<Panel title={t('Következő legjobb akció','Next Best Action')} text={t('Ajánlott akció, csatorna, ajánlat, időzítés és magyarázat. Végrehajtás csak jóváhagyással.','Recommended action, channel, offer, timing and rationale. Execution only after approval.')}><SimpleTable rows={rows} keys={['client_name','recommended_channel','action','offer','timing','rationale']} en={en}/></Panel>}
{tab==='ab'&&<Panel title={t('A/B tesztelés','A/B Testing')} text={t('Szöveg, ajánlat, CTA, időzítés és csatorna összehasonlítása tényleges fizetett bevétel alapján.','Compare copy, offer, CTA, timing and channel based on actually paid revenue.')}><SimpleTable rows={rows} keys={['campaign','variant','channel','messages','clicks','bookings','paid_revenue']} en={en}/></Panel>}
{tab==='attr'&&<Panel title={t('Marketing-hozzárendelés 3.0','Marketing Attribution 3.0')} text={`${data?.model||'multi_touch_linear_paid_ledger_attribution_v3'} — ${t('14 napos többérintéses, lineáris kredit. Fizetési főkönyv alapú, de nem állít kauzalitást.','14-day multi-touch linear credit. Paid-ledger based, but does not claim causality.')}`}><SimpleTable rows={rows} keys={['channel','campaign_id','touches','attributed_paid_revenue']} en={en}/></Panel>}
{tab==='suggestions'&&<Panel title={t('Automatikus kampányjavaslatok','Automatic Campaign Suggestions')} text={data?.suggestion||t('Telephely kiválasztása után az üres idősávokra kampányjavaslat készül.','After selecting a location, campaign suggestions are generated for empty slots.')}><div className="vir-help"><b>{t('Automatikus kiküldés: NEM. Vezetői jóváhagyás szükséges.','Automatic sending: NO. Management approval is required.')}</b></div></Panel>}
{tab==='compliance'&&<Panel title={t('Kommunikációs megfelelőségi központ','Communication Compliance Center')} text={t('Marketing/tranzakciós hozzájárulás, jogalap, leiratkozás és kommunikációs tiltás. A tiltás mindig felülírja a hozzájárulást.','Marketing/transactional consent, lawful basis, opt-out and communication blocking. A block always overrides consent.')}><SimpleTable rows={rows} keys={['client_id','channel','transactional_consent','marketing_consent','lawful_basis','opted_out_at','communication_blocked','block_reason']} en={en}/></Panel>}</div>}
function Panel({title,text,children}:{title:string;text?:string;children?:React.ReactNode}){return <section className="vir-panel"><h2>{title}</h2>{text&&<p className="vir-panel-subtitle">{text}</p>}{children}</section>}
function SimpleTable({rows,keys,en}:{rows:any[];keys:string[];en:boolean}){const locale=en?'en-US':'hu-HU';return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{keys.map(k=><th key={k} style={{textAlign:'left',borderBottom:'1px solid rgba(148,163,184,.35)',padding:10}}>{COLUMN_LABELS[k]?.[en?'en':'hu']||k}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((r,i)=><tr key={r.id||r.client_id||r.campaign_id||i}>{keys.map(k=><td key={k} style={{borderBottom:'1px solid rgba(148,163,184,.18)',padding:10}}>{Array.isArray(r[k])?r[k].join(', '):typeof r[k]==='number'?fmt(r[k],locale):String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div>}
