import React,{useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {dismissP21Decision,evaluateP22Cycle,generateP21Decisions,getP20Status,getP21Decisions,getP21Status,getP22Cycles,getP22Policy,getP22Status,promoteP21Decision,runP20Model,syncP22Cycles,type P20Forecast,type P21Decision,type P22Cycle} from '../api/virP19';

type Props={locationId:string;days:7|30|90;en:boolean};
const tone=(p:string)=>p==='critical'?'danger':p==='high'?'warning':p==='positive'?'success':p==='negative'?'danger':'';

export default function VirP20P22Panel({locationId,days,en}:Props){
  const t=useCallback((hu:string,enText:string)=>en?enText:hu,[en]);
  const[p20,setP20]=useState<P20Forecast|null>(null),[p20Status,setP20Status]=useState<any>(null),[p21Status,setP21Status]=useState<any>(null),[p22Status,setP22Status]=useState<any>(null),[decisions,setDecisions]=useState<P21Decision[]>([]),[cycles,setCycles]=useState<P22Cycle[]>([]),[policy,setPolicy]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const refresh=useCallback(async()=>{const [a,b,c,d,e]=await Promise.allSettled([getP20Status(),getP21Status(),getP21Decisions(),getP22Status(),getP22Cycles()]);if(a.status==='fulfilled')setP20Status(a.value);if(b.status==='fulfilled')setP21Status(b.value);if(c.status==='fulfilled')setDecisions(c.value.items||[]);if(d.status==='fulfilled')setP22Status(d.value);if(e.status==='fulfilled')setCycles(e.value.items||[]);getP22Policy().then(r=>setPolicy(r.items||[])).catch(()=>undefined);},[]);
  useEffect(()=>{void refresh();},[refresh]);
  const guarded=async(fn:()=>Promise<void>)=>{setLoading(true);setError('');try{await fn();}catch(e:any){setError(e?.response?.data?.error||e?.message||t('A művelet nem hajtható végre.','Operation could not be completed.'));}finally{setLoading(false)}};
  const runModel=()=>guarded(async()=>{const r=await runP20Model({days,locationId:locationId||undefined});setP20(r.forecast);await refresh();});
  const generate=()=>guarded(async()=>{const r=await generateP21Decisions({locationId:locationId||undefined});setDecisions(r.items||[]);await refresh();});
  const promote=(id:string)=>guarded(async()=>{await promoteP21Decision(id);await refresh();});
  const dismiss=(id:string)=>guarded(async()=>{await dismissP21Decision(id);await refresh();});
  const sync=()=>guarded(async()=>{await syncP22Cycles();await refresh();});
  const evaluate=(id:string)=>guarded(async()=>{await evaluateP22Cycle(id);await refresh();});
  const money=(n:number)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(n||0));
  return <>
    <section className="vir-panel"><h2>P20 · {t('Validált prediktív modell','Validated predictive model')}</h2><p>{t('Lineáris trend + heti szezonalitás + rövid távú momentum, holdout backtesttel és becslési intervallummal.','Linear trend + weekly seasonality + short-term momentum with holdout backtesting and prediction intervals.')}</p><div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Modellfuttatások','Model runs')}</span><strong>{p20Status?.counts?.runs??0}</strong></div><div className="vir-stat-card"><span>{t('Átlagos MAPE','Average MAPE')}</span><strong>{Number(p20Status?.counts?.avg_mape||0).toFixed(1)}%</strong></div><div className="vir-stat-card"><span>{t('Backtest','Backtest')}</span><strong>{t('AKTÍV','ON')}</strong></div></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void runModel()}>{t('P20 modell futtatása','Run P20 model')}</button></div>{p20&&<div className="vir-result-list"><article className="vir-result-card"><h4>{t('Validált előrejelzés','Validated forecast')}</h4><p>{money(p20.revenue_forecast)} · {p20.booking_forecast} {t('foglalás','bookings')}</p><small>{t('90%-os becslési sáv','90% prediction interval')}: {money(p20.revenue_lower)} – {money(p20.revenue_upper)}</small></article><article className="vir-result-card"><h4>{t('Modellhiba','Model error')}</h4><p>MAPE {p20.metrics.mape_percent.toFixed(1)}% · MAE {money(p20.metrics.mae)}</p><small>{t('Holdout napok','Holdout days')}: {p20.metrics.holdout_days} · {t('bizalom','confidence')}: {Math.round(p20.confidence*100)}%</small></article></div>}</section>

    <section className="vir-panel"><h2>P21 · {t('AI vezetői döntéstámogatás','AI executive decision support')}</h2><p>{t('A P20 jeleit, az operatív KPI-kat és a P22 korábbi eredményeit pontozza. Minden javaslat indoklással, alternatívával és kockázattal készül.','Scores P20 signals, operational KPIs, and previous P22 outcomes. Every recommendation includes rationale, alternatives, and risks.')}</p><div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Nyitott AI-javaslat','Open AI recommendations')}</span><strong>{p21Status?.counts?.proposed??0}</strong></div><div className="vir-stat-card"><span>{t('P17-be küldve','Promoted to P17')}</span><strong>{p21Status?.counts?.promoted??0}</strong></div><div className="vir-stat-card"><span>{t('Közvetlen végrehajtás','Direct execution')}</span><strong>{t('TILTVA','BLOCKED')}</strong></div></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void generate()}>{t('AI-javaslatok generálása','Generate AI recommendations')}</button><Link className="vir-btn secondary" to="/admin/vir/p17">{t('P17 jóváhagyási központ','P17 approval center')}</Link></div><div className="vir-result-list">{decisions.slice(0,12).map(d=><article className="vir-result-card" key={d.id}><span className={`vir-chip ${tone(d.priority)}`}>{d.priority} · {Math.round(Number(d.score||0))}/100</span><h4>{d.title}</h4><p>{d.rationale}</p><small>{t('Bizalom','Confidence')}: {Math.round(Number(d.confidence||0)*100)}% · {t('tanulási minta','learning samples')}: {Number((d.learning as any)?.samples||0)}</small>{d.status==='proposed'&&<div className="vir-toolbar"><button className="vir-btn success" disabled={loading} onClick={()=>void promote(d.id)}>{t('P17 jóváhagyásra küldés','Send to P17 approval')}</button><button className="vir-btn danger" disabled={loading} onClick={()=>void dismiss(d.id)}>{t('Elvetés','Dismiss')}</button></div>}{d.status==='promoted'&&<div className="vir-help">{t('P17 művelet','P17 operation')}: {d.promoted_operation_id}</div>}</article>)}</div></section>

    <section className="vir-panel"><h2>P22 · {t('Zárt visszacsatolású optimalizálás','Closed-loop optimization')}</h2><p>{t('Csak végrehajtott/ellenőrzött P17 műveletből tanul. A before/after eredményt pontozza, és ezt a következő P21 javaslatok súlyozásába adja vissza.','Learns only from executed/verified P17 operations. It scores before/after outcomes and feeds that signal into future P21 recommendation weighting.')}</p><div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Megfigyelés alatt','Observing')}</span><strong>{p22Status?.counts?.observing??0}</strong></div><div className="vir-stat-card"><span>{t('Kiértékelve','Evaluated')}</span><strong>{p22Status?.counts?.evaluated??0}</strong></div><div className="vir-stat-card"><span>{t('Pozitív eredmény','Positive outcomes')}</span><strong>{p22Status?.counts?.positive??0}</strong></div></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void sync()}>{t('Végrehajtott P17 műveletek szinkronja','Sync executed P17 operations')}</button></div><div className="vir-result-list">{cycles.slice(0,12).map(c=><article className="vir-result-card" key={c.id}><span className={`vir-chip ${tone(c.outcome_class||'')}`}>{c.status}{c.outcome_class?` · ${c.outcome_class}`:''}</span><h4>{c.decision_title||c.operation_type}</h4><p>{t('Megfigyelési ablak','Observation window')}: {c.observation_days} {t('nap','days')} · P17: {c.operation_status||'—'}</p>{c.optimization_score!=null&&<small>{t('Optimalizációs pontszám','Optimization score')}: {Number(c.optimization_score).toFixed(1)}</small>}{c.status==='observing'&&c.operation_status==='verified'&&<div className="vir-toolbar"><button className="vir-btn secondary" disabled={loading} onClick={()=>void evaluate(c.id)}>{t('Eredmény kiértékelése','Evaluate outcome')}</button></div>}</article>)}</div>{policy.length>0&&<details className="vir-json-details"><summary>{t('Tanult P22 policy-súlyok','Learned P22 policy weights')}</summary><pre>{JSON.stringify(policy,null,2)}</pre></details>}<div className="vir-help"><strong>{t('Biztonsági korlát:','Safety boundary:')}</strong> {t('P22 nem ír át önállóan foglalást, árat, beosztást vagy pénzügyi adatot; csak a következő P21 ajánlás pontszámát módosítja.','P22 does not autonomously change bookings, pricing, schedules, or financial data; it only adjusts future P21 recommendation scores.')}</div></section>
    {error&&<div className="vir-error-friendly">{error}</div>}
  </>;
}
