import React,{useEffect,useState} from 'react';
import {getP13LoyaltyHealth,getP13Status,previewP13Protection,previewP13SaveOffer} from '../api/virP13';
import {useLanguage} from '../i18n/LanguageProvider';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';
const friendlyError=(e:any,en:boolean)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||(en?'The data could not be loaded.':'Az adatokat most nem sikerült betölteni.');
export default function VirP13Page(){
 const{language}=useLanguage();const en=language==='en';const[clientId,setClientId]=useState('');const[data,setData]=useState<any>(null);const[status,setStatus]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{void getP13Status().then(setStatus).catch(e=>setError(friendlyError(e,en)))},[en]);
 const run=async(kind:'protect'|'loyalty'|'save')=>{setLoading(true);setError('');try{setData(kind==='protect'?await previewP13Protection({client_id:clientId||undefined}):kind==='loyalty'?await getP13LoyaltyHealth(clientId):await previewP13SaveOffer({client_id:clientId}))}catch(e:any){setError(friendlyError(e,en))}finally{setLoading(false)}};
 return <div className="vir-workspace"><header className="vir-workspace-hero"><h1>{en?'Revenue Protection & Loyalty':'Bevételvédelem és törzsvásárlói kapcsolat'}</h1><p>{en?'Review no-show risk, loyalty health and retention offers. Charges and discounts are never applied automatically.':'No-show kockázat, törzsvásárlói állapot és megtartási ajánlat egy helyen. Terhelés és kedvezmény soha nem történik automatikusan.'}</p></header>
 {status&&<div className="vir-workspace-grid"><div className="vir-stat-card"><span>{en?'No-shows in 30 days':'No-show 30 nap'}</span><strong>{status.counts?.no_shows_30d??0}</strong></div><div className="vir-stat-card"><span>{en?'Cancellations':'Lemondások'}</span><strong>{status.counts?.cancellations_30d??0}</strong></div></div>}
 <section className="vir-panel"><h2>{en?'Customer selection':'Vendég kiválasztása'}</h2><p className="vir-panel-subtitle">{en?'Search by name, phone or email instead of entering an identifier.':'Név, telefonszám vagy e-mail alapján keress, azonosítót nem kell kézzel beírni.'}</p><div className="vir-toolbar"><VirSearchSelect kind="clients" label={en?'Customer':'Vendég'} value={clientId} onChange={setClientId}/><button className="vir-btn" onClick={()=>void run('protect')} disabled={loading}>{en?'Protection preview':'Bevételvédelmi előnézet'}</button><button className="vir-btn secondary" onClick={()=>void run('loyalty')} disabled={loading||!clientId}>{en?'Loyalty health':'Hűségállapot'}</button><button className="vir-btn secondary" onClick={()=>void run('save')} disabled={loading||!clientId}>{en?'Save offer':'Megtartási ajánlat'}</button></div></section>
 {error&&<div className="vir-error-friendly">{error}</div>}{loading&&<div className="vir-help">{en?'Loading…':'Betöltés…'}</div>}
 <section className="vir-panel"><h2>{en?'Recommendation':'Javaslat'}</h2>{data?<><div className="vir-help">{data?.recommendation?.reason||data?.health||data?.model||(en?'Analysis ready.':'Az elemzés elkészült.')}</div><details className="vir-json-details"><summary>{en?'Technical details':'Technikai részletek'}</summary><pre>{JSON.stringify(data,null,2)}</pre></details></>:<div className="vir-empty-state">{en?'Choose a customer and a function above.':'Válassz vendéget és egy funkciót fent.'}</div>}</section>
 </div>;
}
