import React,{useCallback,useEffect,useState}from"react";
import{useSearchParams}from"react-router-dom";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirChurnRadar,getVirMembershipIntelligence,getVirNextVisit,getVirSmartPricing}from"../api/virP3";
import{useLanguage}from"../i18n/LanguageProvider";
import"./VirManagement.css";

type Tab="churn"|"next-visit"|"pricing"|"membership";
export default function VirP3Page(){
 const{language}=useLanguage();const en=language==='en';const t=(hu:string,enText:string)=>en?enText:hu;const money=(v:unknown)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(v||0));const date=(v:unknown)=>v?new Intl.DateTimeFormat(en?'en-US':'hu-HU').format(new Date(String(v))):"—";
 const[sp,setSp]=useSearchParams();const tab=(sp.get('tab')||'churn')as Tab;const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[horizonDays,setHorizonDays]=useState(30);const[pricingDays,setPricingDays]=useState(14);
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const common={locationId:locationId||undefined};const result=tab==='churn'?await getVirChurnRadar(common):tab==='next-visit'?await getVirNextVisit({...common,horizonDays}):tab==='pricing'?await getVirSmartPricing({...common,days:pricingDays}):await getVirMembershipIntelligence(common);setData(result);}catch(e:any){setError(e?.response?.data?.error||e?.message||(en?'Loading error':'Betöltési hiba'));}finally{setLoading(false);}},[tab,locationId,horizonDays,pricingDays,en]);
 useEffect(()=>{void load();},[load]);
 const tabs:[Tab,string][]=[['churn',t('15. Lemorzsolódási radar','15. Churn Radar')],['next-visit',t('16. Következő látogatás motor','16. Next Visit Engine')],['pricing',t('17. Intelligens árképzés','17. Smart Pricing')],['membership',t('18. Tagsági intelligencia','18. Membership Intelligence')]];
 return <div className="vir-management-page">
  <div className="vir-management-header"><div><h1 className="vir-management-title">{t('Bevétel- és vendégmegtartási intelligencia','Revenue & Retention Intelligence')}</h1><div className="vir-management-subtitle">{t('Vendégmegtartás, következő látogatás, keresletalapú árjavaslat és tagsági potenciál. Minden eredmény döntéstámogató javaslat, automatikus végrehajtás nélkül.','Customer retention, next visit prediction, demand-based pricing suggestions and membership potential. All outputs are decision-support recommendations without automatic execution.')}</div></div><div className="vir-management-actions"><label className="vir-field"><span>{t('Telephely','Location')}</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">{t('Összes telephely','All locations')}</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{tab==='next-visit'&&<label className="vir-field"><span>{t('Előrejelzési ablak','Forecast window')}</span><select value={horizonDays} onChange={e=>setHorizonDays(Number(e.target.value))}><option value={14}>{t('14 nap','14 days')}</option><option value={30}>{t('30 nap','30 days')}</option><option value={60}>{t('60 nap','60 days')}</option><option value={90}>{t('90 nap','90 days')}</option></select></label>}{tab==='pricing'&&<label className="vir-field"><span>{t('Árjavaslati időszak','Pricing period')}</span><select value={pricingDays} onChange={e=>setPricingDays(Number(e.target.value))}><option value={7}>{t('7 nap','7 days')}</option><option value={14}>{t('14 nap','14 days')}</option><option value={30}>{t('30 nap','30 days')}</option></select></label>}</div></div>
  <div className="vir-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'is-active':''} onClick={()=>setSp({tab:k})}>{l}</button>)}</div>
  {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">{t('Elemzés frissítése…','Refreshing analysis…')}</div>}
  {!loading&&tab==='churn'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">{t('Kritikus lemorzsolódás','Critical churn')}</div><div className="vir-kpi-value">{data.summary.critical}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">{t('Magas kockázat','High risk')}</div><div className="vir-kpi-value">{data.summary.high}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Kockázatos ügyfélérték','Customer value at risk')}</div><div className="vir-kpi-value">{money(data.summary.revenue_at_risk)}</div></div></div><section className="vir-panel"><div className="vir-panel-muted">{t('Magyarázható pontszám a saját látogatási ciklus, eltelt idő, no-show, lemondás, aktivitás és ügyfélérték alapján. Nem küld automatikus üzenetet.','Explainable score based on visit cycle, recency, no-shows, cancellations, activity and customer value. It does not send automatic messages.')}</div><table className="vir-source-table"><thead><tr><th>{t('Vendég','Customer')}</th><th>{t('Kockázat','Risk')}</th><th>{t('Pontszám','Score')}</th><th>{t('Utolsó látogatás','Last visit')}</th><th>{t('Ciklus','Cycle')}</th><th>{t('Eltelt nap','Days elapsed')}</th><th>LTV</th><th>{t('Indok','Reason')}</th></tr></thead><tbody>{data.items?.map((x:any)=><tr key={x.client_id}><td>{x.client_name}</td><td><span className="vir-badge">{x.risk}</span></td><td><strong>{x.churn_score}</strong></td><td>{date(x.last_visit)}</td><td>{x.avg_cycle_days} {t('nap','days')}</td><td>{x.recency_days}</td><td>{money(x.lifetime_value)}</td><td>{x.reason}</td></tr>)}</tbody></table></section></>}
  {!loading&&tab==='next-visit'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">{t('Lejárt ciklus','Overdue cycle')}</div><div className="vir-kpi-value">{data.summary.overdue}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">{t('7 napon belül esedékes','Due within 7 days')}</div><div className="vir-kpi-value">{data.summary.due_7d}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Összes jelölt','Total candidates')}</div><div className="vir-kpi-value">{data.summary.due}</div></div></div><section className="vir-panel"><div className="vir-panel-muted">{t('Vendég × szolgáltatás visszatérési ciklusból becsült következő optimális látogatás. A megkeresés külön jóváhagyást igényel.','Estimated next optimal visit from the customer × service return cycle. Outreach requires separate approval.')}</div><table className="vir-source-table"><thead><tr><th>{t('Vendég','Customer')}</th><th>{t('Szolgáltatás','Service')}</th><th>{t('Utolsó','Last')}</th><th>{t('Átl. ciklus','Avg. cycle')}</th><th>{t('Becsült következő','Predicted next')}</th><th>{t('Eltérés','Delta')}</th><th>{t('Állapot','Status')}</th></tr></thead><tbody>{data.items?.map((x:any,i:number)=><tr key={`${x.client_id}-${x.service_id}-${i}`}><td>{x.client_name}</td><td>{x.service_name}</td><td>{date(x.last_visit)}</td><td>{x.avg_cycle_days} {t('nap','days')}</td><td>{x.predicted_next_visit}</td><td>{x.days_until_due} {t('nap','days')}</td><td><span className="vir-badge">{x.status}</span></td></tr>)}</tbody></table></section></>}
  {!loading&&tab==='pricing'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-warning"><div className="vir-kpi-label">{t('Kedvezmény-jelölt','Discount candidates')}</div><div className="vir-kpi-value">{data.summary.discount_candidates}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Védendő ársáv','Protected price slots')}</div><div className="vir-kpi-value">{data.summary.protected_slots}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Elemzett sáv','Analyzed slots')}</div><div className="vir-kpi-value">{data.summary.slots}</div></div></div><section className="vir-panel"><div className="vir-panel-muted">{t('90 napos historikus kereslet és aktuális előfoglaltság alapján. A rendszer csak árat javasol; automatikus árátírás nincs.','Based on 90-day historical demand and current forward bookings. The system only suggests prices; there is no automatic repricing.')}</div><table className="vir-source-table"><thead><tr><th>{t('Nap','Day')}</th><th>{t('Óra','Hour')}</th><th>{t('Foglalás','Bookings')}</th><th>{t('Keresleti index','Demand index')}</th><th>{t('Átl. ár','Avg. price')}</th><th>{t('Javaslat','Recommendation')}</th><th>{t('Kedvezmény','Discount')}</th><th>{t('Javasolt ár','Suggested price')}</th></tr></thead><tbody>{data.items?.map((x:any,i:number)=><tr key={`${x.day}-${x.hour}-${i}`}><td>{date(x.day)}</td><td>{String(x.hour).padStart(2,'0')}:00</td><td>{x.booked}</td><td>{x.demand_index}</td><td>{money(x.avg_price)}</td><td>{x.recommendation}</td><td>{x.suggested_discount_percent}%</td><td>{money(x.suggested_price)}</td></tr>)}</tbody></table></section></>}
  {!loading&&tab==='membership'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">{t('Tagsági jelölt','Membership candidates')}</div><div className="vir-kpi-value">{data.summary.candidates}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">Gold</div><div className="vir-kpi-value">{data.summary.gold}</div></div><div className="vir-kpi is-critical"><div className="vir-kpi-label">VIP</div><div className="vir-kpi-value">{data.summary.vip}</div></div></div><section className="vir-panel"><div className="vir-panel-muted">{t('12 havi látogatási gyakoriság és költés alapján tagsági illeszkedési javaslat. Automatikus beléptetés nincs.','Membership-fit recommendation based on 12-month visit frequency and spend. There is no automatic enrollment.')}</div><table className="vir-source-table"><thead><tr><th>{t('Vendég','Customer')}</th><th>{t('Látogatás / 12 hó','Visits / 12 mo')}</th><th>{t('Költés / 12 hó','Spend / 12 mo')}</th><th>{t('Átl. kosár','Avg. basket')}</th><th>{t('Javasolt csomag','Recommended plan')}</th><th>{t('Illeszkedési pontszám','Fit score')}</th><th>{t('Indok','Reason')}</th></tr></thead><tbody>{data.items?.map((x:any)=><tr key={x.client_id}><td>{x.client_name}</td><td>{x.visits_12m}</td><td>{money(x.spend_12m)}</td><td>{money(x.avg_basket)}</td><td><span className="vir-badge">{x.recommended_plan}</span></td><td><strong>{x.membership_fit_score}</strong></td><td>{x.rationale}</td></tr>)}</tbody></table></section></>}
 </div>;
}
