import React,{useEffect,useState} from 'react';
import {decideP16,getP16DecisionInbox,getP16ExceptionBrief,getP16MorningBrief,getP16Status,syncP16DecisionInbox} from '../api/virP16';
import './VirWorkspace.css';
const friendlyError=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'Az adatokat most nem sikerült betölteni.';
const priorityClass=(p:string)=>p==='CRITICAL'?'danger':p==='HIGH'?'warning':'';
const priorityHu=(p:string)=>({CRITICAL:'Kritikus',HIGH:'Magas',MEDIUM:'Közepes',LOW:'Alacsony'} as Record<string,string>)[p]||p;
export default function VirP16Page(){
 const[status,setStatus]=useState<any>(null);const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{void getP16Status().then(setStatus).catch(e=>setError(friendlyError(e)))},[]);
 const run=async(kind:'brief'|'morning'|'sync'|'inbox')=>{setLoading(true);setError('');try{setData(kind==='brief'?await getP16ExceptionBrief():kind==='morning'?await getP16MorningBrief():kind==='sync'?await syncP16DecisionInbox():await getP16DecisionInbox())}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}};
 const decide=async(id:string,s:'accepted'|'dismissed')=>{setLoading(true);setError('');try{await decideP16(id,s);setData(await getP16DecisionInbox())}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}};
 const items=Array.isArray(data?.items)?data.items:Array.isArray(data?.top_decisions)?data.top_decisions:Array.isArray(data?.decisions)?data.decisions:[];
 return <div className="vir-workspace">
  <header className="vir-workspace-hero"><h1>Vezetői döntési központ</h1><p>A rendszer nem újabb riportokat halmoz: kiemeli azt a néhány ügyet, amely ma tényleges vezetői döntést igényel, és egy helyen kezeli az elfogadást vagy elvetést.</p></header>
  <div className="vir-workspace-grid"><div className="vir-stat-card"><span>Nyitott döntések</span><strong>{status?.counts?.open??0}</strong></div><div className="vir-stat-card"><span>Elfogadott</span><strong>{status?.counts?.accepted??0}</strong></div><div className="vir-stat-card"><span>Elvetett</span><strong>{status?.counts?.dismissed??0}</strong></div><div className="vir-stat-card"><span>Automatikus végrehajtás</span><strong>NEM</strong></div></div>
  <section className="vir-panel"><h2>Mit szeretnél látni?</h2><p className="vir-panel-subtitle">A reggeli összefoglaló a legfontosabb döntéseket hozza előre, a döntési lista pedig a teljes nyitott sort mutatja.</p><div className="vir-toolbar"><button className="vir-btn" title="Reggeli vezetői brief" disabled={loading} onClick={()=>void run('morning')}>Reggeli vezetői összefoglaló</button><button className="vir-btn secondary" title="Exception brief" disabled={loading} onClick={()=>void run('brief')}>Kiemelt problémák</button><button className="vir-btn secondary" title="Decision Inbox frissítése" disabled={loading} onClick={()=>void run('sync')}>Döntési lista frissítése</button><button className="vir-btn secondary" title="Decision Inbox" disabled={loading} onClick={()=>void run('inbox')}>Döntési lista</button></div></section>
  {error&&<div className="vir-error-friendly"><strong>Nem sikerült:</strong> {error}</div>}
  <section className="vir-panel"><h2>Döntést igénylő ügyek</h2>{items.length===0?<div className="vir-empty-state">Nincs megjeleníthető döntés. Frissítsd a döntési listát vagy nyisd meg a reggeli összefoglalót.</div>:<div className="vir-result-list">{items.map((x:any,i:number)=><article key={x.id||x.key||i} className="vir-result-card"><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><span className={`vir-chip ${priorityClass(x.priority)}`}>{priorityHu(x.priority)}</span><span className="vir-chip">{x.area||'Vezetői ügy'}</span></div><h4 style={{marginTop:10}}>{x.title}</h4><p>{x.reason}</p>{x.status&&<small>Állapot: <strong>{x.status}</strong></small>}{x.status==='open'&&x.id&&<div className="vir-toolbar" style={{marginTop:10}}><button className="vir-btn success" onClick={()=>void decide(x.id,'accepted')} disabled={loading}>Elfogadom</button><button className="vir-btn danger" onClick={()=>void decide(x.id,'dismissed')} disabled={loading}>Elvetem</button></div>}</article>)}</div>}{data&&<details className="vir-json-details"><summary>Technikai részletek</summary><pre>{JSON.stringify(data,null,2)}</pre></details>}</section>
  <div className="vir-help"><strong>Governance:</strong> a döntés rögzítése nem indít automatikus foglalást, kampányt, kedvezményt, pénzügyi műveletet vagy beosztásmódosítást.</div>
 </div>;
}
