import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirCompetitorIntelligence,getVirDigitalTwin,getVirLocationExpansion,postVirActionPreview,postVirGoalAction}from"../api/virP5";
import{useLanguage}from"../i18n/LanguageProvider";
import"./VirManagement.css";

type Tab="26"|"27"|"28"|"31"|"32";
export default function VirP5Page(){
 const{language}=useLanguage();const en=language==='en';const t=(hu:string,enText:string)=>en?enText:hu;const money=(v:unknown)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(v)||0);
 const tabs:[Tab,string][]=[["26",t('Digitális iker','Digital Twin')],["27",t('Cél → Akció AI','Goal → Action AI')],["28",t('Autonóm akció előnézet','Autonomous Action Preview')],["31",t('Versenyhelyzet-intelligencia','Competitor Intelligence')],["32",t('Telephely-bővítési intelligencia','Location Expansion Intelligence')]];
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[tab,setTab]=useState<Tab>('26');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const[revenueChange,setRevenueChange]=useState(10);const[priceChange,setPriceChange]=useState(0);const[utilChange,setUtilChange]=useState(5);const[goal,setGoal]=useState('revenue_growth');const[target,setTarget]=useState(10);const[horizon,setHorizon]=useState(30);const[actionType,setActionType]=useState('CAPACITY');const[impact,setImpact]=useState(5);const[cost,setCost]=useState(2);const[candidate,setCandidate]=useState('Új telephely');const[appointments,setAppointments]=useState(300);const[avgTicket,setAvgTicket]=useState(12000);const[rent,setRent]=useState(1200000);const[startup,setStartup]=useState(25000000);
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{let r:any;if(tab==='26')r=await getVirDigitalTwin({locationId:locationId||undefined,revenue_change:revenueChange,price_change:priceChange,utilization_change:utilChange});else if(tab==='27')r=await postVirGoalAction({locationId:locationId||undefined,goal,target_percent:target,horizon_days:horizon});else if(tab==='28')r=await postVirActionPreview({locationId:locationId||undefined,action_type:actionType,expected_revenue_change_percent:impact,expected_cost_change_percent:cost});else if(tab==='31')r=await getVirCompetitorIntelligence({locationId:locationId||undefined,days:horizon});else r=await getVirLocationExpansion({candidate_name:candidate,expected_monthly_appointments:appointments,avg_ticket:avgTicket,monthly_rent:rent,startup_cost:startup});setData(r);}catch(e:any){setError(e?.response?.data?.error||e?.message||(en?'Loading error':'Betöltési hiba'));}finally{setLoading(false);}},[tab,locationId,revenueChange,priceChange,utilChange,goal,target,horizon,actionType,impact,cost,candidate,appointments,avgTicket,rent,startup,en]);
 useEffect(()=>{void load();},[load]);
 return <div className="vir-management-page"><div className="vir-management-header"><div><h1 className="vir-management-title">{t('Fejlett vezetői intelligencia','Advanced Management Intelligence')}</h1><div className="vir-management-subtitle">{t('Szimuláció, cél→akció tervezés, végrehajtás előtti előnézet, versenyhelyzet-proxy és telephely-bővítési döntéstámogatás. Automatikus üzleti végrehajtás nélkül.','Simulation, goal-to-action planning, pre-execution preview, competitive-position proxy and location-expansion decision support. No automatic business execution.')}</div></div><div className="vir-management-actions"><label className="vir-field"><span>{t('Telephely','Location')}</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">{t('Összes telephely','All locations')}</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div></div>
 <div className="vir-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'is-active':''} onClick={()=>setTab(id)}>{id}. {label}</button>)}</div>
 {tab==='26'&&<div className="vir-management-actions"><label className="vir-field"><span>{t('Árbevétel %','Revenue %')}</span><input type="number" value={revenueChange} onChange={e=>setRevenueChange(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Ár %','Price %')}</span><input type="number" value={priceChange} onChange={e=>setPriceChange(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Kihasználtság %','Utilization %')}</span><input type="number" value={utilChange} onChange={e=>setUtilChange(Number(e.target.value))}/></label></div>}
 {tab==='27'&&<div className="vir-management-actions"><label className="vir-field"><span>{t('Cél','Goal')}</span><select value={goal} onChange={e=>setGoal(e.target.value)}><option value="revenue_growth">{t('Árbevétel-növekedés','Revenue growth')}</option><option value="margin_growth">{t('Árrés-növekedés','Margin growth')}</option><option value="capacity">{t('Kihasználtság','Utilization')}</option></select></label><label className="vir-field"><span>{t('Cél %','Target %')}</span><input type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Időtáv','Horizon')}</span><select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={30}>{t('30 nap','30 days')}</option><option value={60}>{t('60 nap','60 days')}</option><option value={90}>{t('90 nap','90 days')}</option></select></label></div>}
 {tab==='28'&&<div className="vir-management-actions"><label className="vir-field"><span>{t('Akció','Action')}</span><select value={actionType} onChange={e=>setActionType(e.target.value)}><option>CAPACITY</option><option>PRICING</option><option>RETENTION</option><option>MARKETING</option></select></label><label className="vir-field"><span>{t('Árbevételhatás %','Revenue impact %')}</span><input type="number" value={impact} onChange={e=>setImpact(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Költséghatás %','Cost impact %')}</span><input type="number" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label></div>}
 {tab==='32'&&<div className="vir-management-actions"><label className="vir-field"><span>{t('Jelölt helyszín','Candidate location')}</span><input value={candidate} onChange={e=>setCandidate(e.target.value)}/></label><label className="vir-field"><span>{t('Havi időpont','Monthly appointments')}</span><input type="number" value={appointments} onChange={e=>setAppointments(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Átlagkosár','Average ticket')}</span><input type="number" value={avgTicket} onChange={e=>setAvgTicket(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Havi bérlet','Monthly rent')}</span><input type="number" value={rent} onChange={e=>setRent(Number(e.target.value))}/></label><label className="vir-field"><span>{t('Induló beruházás','Startup investment')}</span><input type="number" value={startup} onChange={e=>setStartup(Number(e.target.value))}/></label></div>}
 {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">{t('Vezetői intelligencia számítása…','Calculating management intelligence…')}</div>}
 {!loading&&tab==='26'&&<section className="vir-panel"><div className="vir-panel-muted">{t('Determinisztikus mi-történik-ha modell a kanonikus profitmotor alapján. Csak szimuláció, automatikus írás nélkül.','Deterministic what-if model based on the canonical profit engine. Simulation only, with no automatic writes.')}</div><table className="vir-source-table"><thead><tr><th>{t('Telephely','Location')}</th><th>{t('Alap árbevétel','Baseline revenue')}</th><th>{t('Szimulált árbevétel','Simulated revenue')}</th><th>{t('Δ árbevétel','Δ revenue')}</th><th>{t('Alap profit','Baseline profit')}</th><th>{t('Szimulált profit','Simulated profit')}</th><th>{t('Δ profit','Δ profit')}</th></tr></thead><tbody>{data?.items?.map((x:any)=><tr key={x.location_id}><td>{x.location_name}</td><td>{money(x.baseline.revenue)}</td><td>{money(x.scenario.revenue)}</td><td>{money(x.delta.revenue)}</td><td>{money(x.baseline.gross_profit)}</td><td>{money(x.scenario.gross_profit)}</td><td>{money(x.delta.gross_profit)}</td></tr>)}</tbody></table></section>}
 {!loading&&tab==='27'&&<section className="vir-panel"><div className="vir-panel-muted">{t('A célból végrehajtási jelölteket készít vezetői AI-jelzések és profitadatok alapján. Jóváhagyás szükséges, automatikus akció nincs.','Creates execution candidates from the goal using executive AI signals and profit data. Approval is required and no automatic action is performed.')}</div>{data?.items?.map((x:any)=><article className="vir-action-card" key={x.location_id}><div className="vir-action-title">{x.location_name}</div>{x.actions?.map((a:any,i:number)=><div key={i} className="vir-stat-line"><span>{a.type}: {a.action}</span><strong>{a.priority}</strong></div>)}</article>)}</section>}
 {!loading&&tab==='28'&&<section className="vir-panel"><div className="vir-panel-muted">{t('Az Előnézet → Jóváhagyás → Végrehajtás elv első lépése. A modul nem hajt végre műveletet.','First step of the Preview → Approval → Execute principle. The module does not execute operations.')}</div><table className="vir-source-table"><thead><tr><th>{t('Telephely','Location')}</th><th>{t('Akció','Action')}</th><th>{t('Előtte profit','Profit before')}</th><th>{t('Előnézeti profit','Preview profit')}</th><th>Δ profit</th><th>{t('Kockázat','Risk')}</th></tr></thead><tbody>{data?.previews?.map((x:any)=><tr key={x.location_id}><td>{x.location_name}</td><td>{x.action_type}</td><td>{money(x.before.gross_profit)}</td><td>{money(x.preview_after.gross_profit)}</td><td>{money(x.delta.gross_profit)}</td><td>{x.risk}</td></tr>)}</tbody></table></section>}
 {!loading&&tab==='31'&&<section className="vir-panel"><div className="vir-panel-muted">{data?.warning}</div><table className="vir-source-table"><thead><tr><th>{t('Telephely','Location')}</th><th>{t('Árbevétel','Revenue')}</th><th>{t('Időpont','Appointments')}</th><th>{t('Peer árbevétel eltérés','Peer revenue delta')}</th><th>{t('Peer időpont eltérés','Peer appointment delta')}</th><th>{t('Pozíció','Position')}</th></tr></thead><tbody>{data?.items?.map((x:any)=><tr key={x.location_id}><td>{x.location_name}</td><td>{money(x.revenue)}</td><td>{x.appointments}</td><td>{x.revenue_vs_peer_pct}%</td><td>{x.appointments_vs_peer_pct}%</td><td><span className="vir-badge">{x.competitive_position}</span></td></tr>)}</tbody></table></section>}
 {!loading&&tab==='32'&&<section className="vir-panel"><div className="vir-panel-muted">{data?.warning}</div>{data?.candidate&&<div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">{t('Bővítési pontszám','Expansion score')}</div><div className="vir-kpi-value">{data.candidate.expansion_score}/100</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Projektált havi árbevétel','Projected monthly revenue')}</div><div className="vir-kpi-value">{money(data.candidate.projected_monthly_revenue)}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Bérlet / árbevétel','Rent / revenue')}</div><div className="vir-kpi-value">{data.candidate.rent_to_revenue_percent}%</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Egyszerű megtérülés','Simple payback')}</div><div className="vir-kpi-value">{data.candidate.simple_payback_months} {t('hó','mo')}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Ajánlás','Recommendation')}</div><div className="vir-kpi-value">{data.candidate.recommendation}</div></div></div>}</section>}
 </div>;
}
