import React,{useCallback,useEffect,useState} from 'react';
import {analyzeP11Complaint,getP11Complaints,getP11ConversationMemory,getP11Status,previewP11Reception} from '../api/virP11';
import {useLanguage} from '../i18n/LanguageProvider';

type Tab='reception'|'memory'|'complaints';
const labels:Record<Tab,{hu:string;en:string}>={reception:{hu:'56. Teljes AI-recepciós',en:'56. Full AI Receptionist'},memory:{hu:'57. AI beszélgetési memória',en:'57. AI Conversation Memory'},complaints:{hu:'58. AI panaszasszisztens',en:'58. AI Complaint Assistant'}};
export default function VirP11Page(){
 const {language}=useLanguage();const en=language==='en';
 const [tab,setTab]=useState<Tab>('reception');const [locationId,setLocationId]=useState('');const [data,setData]=useState<any>(null);const [status,setStatus]=useState<any>(null);const [loading,setLoading]=useState(false);
 const [text,setText]=useState('Holnap délután szeretnék időpontot hajvágásra.');const [clientId,setClientId]=useState('');const [complaint,setComplaint]=useState('');const [workOrderId,setWorkOrderId]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const params=locationId?{locationId}:{};setStatus(await getP11Status(params));if(tab==='memory'){setData(clientId?await getP11ConversationMemory(clientId,params):{ok:true,info:en?'Enter a customer UUID to view conversation memory.':'Adj meg vendég UUID-t a memória megtekintéséhez.'});}else if(tab==='complaints'){setData(await getP11Complaints(params));}else setData({ok:true,info:en?'Describe the customer request, then create a booking preview.':'Írd le a vendég kérését, majd készíts foglalási előnézetet.'});}finally{setLoading(false)}},[clientId,en,locationId,tab]);
 useEffect(()=>{void load()},[load]);
 const preview=async()=>{setLoading(true);try{setData(await previewP11Reception({text,client_id:clientId||undefined,locationId:locationId||undefined}))}finally{setLoading(false)}};
 const analyze=async()=>{setLoading(true);try{setData(await analyzeP11Complaint({summary:complaint,client_id:clientId||undefined,work_order_id:workOrderId||undefined,locationId:locationId||undefined}))}finally{setLoading(false)}};
 return <div style={{padding:24,maxWidth:1500,margin:'0 auto'}}><h1>{en?'AI Reception & Customer Journey':'AI-recepció és vendégút'}</h1><p>{en?'AI-assisted reception decision support, first-party conversation memory and complaint assistance. No automatic booking, refunds or compensation.':'AI-alapú recepciós döntéstámogatás, saját forrású beszélgetési memória és panaszasszisztens. Automatikus foglalás, pénzvisszatérítés vagy kompenzáció nincs.'}</p>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'16px 0'}}>{(Object.keys(labels) as Tab[]).map(k=><button key={k} onClick={()=>setTab(k)} style={{fontWeight:tab===k?800:500}}>{labels[k][en?'en':'hu']}</button>)}</div>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}><input value={locationId} onChange={e=>setLocationId(e.target.value)} placeholder={en?'Location UUID (optional)':'Telephely UUID (opcionális)'} style={{minWidth:320}}/><input value={clientId} onChange={e=>setClientId(e.target.value)} placeholder={en?'Customer UUID (for memory)':'Vendég UUID (memóriához)'} style={{minWidth:320}}/><button onClick={()=>void load()} disabled={loading}>{loading?(en?'Loading...':'Betöltés...'):(en?'Refresh':'Frissítés')}</button></div>
 {status&&<div style={{marginBottom:16,padding:12,border:'1px solid #ddd',borderRadius:10}}>{en?'Open conversations':'Nyitott beszélgetések'}: <strong>{status.counts?.open_conversations??0}</strong> · {en?'Human handoffs':'Emberi átadások'}: <strong>{status.counts?.open_handoffs??0}</strong> · {en?'Complaints':'Panaszok'}: <strong>{status.counts?.open_complaints??0}</strong></div>}
 {tab==='reception'&&<section style={{marginBottom:16}}><textarea value={text} onChange={e=>setText(e.target.value)} rows={4} style={{width:'100%'}}/><button onClick={()=>void preview()} disabled={loading||!text.trim()}>{en?'Create booking preview':'Foglalási előnézet készítése'}</button><p><strong>{en?'Control:':'Kontroll:'}</strong> {en?'the preview does not write a booking; customer confirmation and, where required, human approval are needed.':'az előnézet nem ír foglalást; vendégmegerősítés és szükség szerint emberi jóváhagyás kell.'}</p></section>}
 {tab==='memory'&&<p>{en?'Memory uses only first-party operational history: previous conversations, visits and communication identities. No sensitive profiling is performed.':'A memória kizárólag saját operatív előzményekből dolgozik: korábbi beszélgetések, látogatások és kommunikációs azonosítók. Érzékeny profilkövetkeztetés nincs.'}</p>}
 {tab==='complaints'&&<section style={{marginBottom:16}}><textarea value={complaint} onChange={e=>setComplaint(e.target.value)} rows={4} placeholder={en?'Complaint summary':'Panasz összefoglalása'} style={{width:'100%'}}/><input value={workOrderId} onChange={e=>setWorkOrderId(e.target.value)} placeholder={en?'Work order UUID (optional)':'Munkalap UUID (opcionális)'} style={{minWidth:320}}/><button onClick={()=>void analyze()} disabled={loading||!complaint.trim()}>{en?'Analyze complaint and create human handoff':'Panasz elemzése és emberi átadás'}</button><p><strong>{en?'Control:':'Kontroll:'}</strong> {en?'automatic compensation and refunds: NO.':'automatikus kompenzáció és pénzvisszatérítés: NEM.'}</p></section>}
 <section style={{background:'var(--surface,#fff)',border:'1px solid #ddd',borderRadius:12,padding:16}}><pre style={{whiteSpace:'pre-wrap',wordBreak:'break-word',margin:0}}>{data?JSON.stringify(data,null,2):(en?'No data.':'Nincs adat.')}</pre></section>
 </div>
}
