import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirCompetitorIntelligence,getVirDigitalTwin,getVirLocationExpansion,postVirActionPreview,postVirGoalAction}from"../api/virP5";
import"./VirManagement.css";

type Tab="26"|"27"|"28"|"31"|"32";
const tabs:[Tab,string][]=[["26","Digital Twin"],["27","Goal → Action AI"],["28","Autonomous Action Preview"],["31","Competitor Intelligence"],["32","Location Expansion Intelligence"]];
const money=(v:unknown)=>new Intl.NumberFormat("hu-HU",{maximumFractionDigits:0}).format(Number(v)||0)+" Ft";
export default function VirP5Page(){
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[tab,setTab]=useState<Tab>('26');
 const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const[revenueChange,setRevenueChange]=useState(10);const[priceChange,setPriceChange]=useState(0);const[utilChange,setUtilChange]=useState(5);
 const[goal,setGoal]=useState('revenue_growth');const[target,setTarget]=useState(10);const[horizon,setHorizon]=useState(30);
 const[actionType,setActionType]=useState('CAPACITY');const[impact,setImpact]=useState(5);const[cost,setCost]=useState(2);
 const[candidate,setCandidate]=useState('Új telephely');const[appointments,setAppointments]=useState(300);const[avgTicket,setAvgTicket]=useState(12000);const[rent,setRent]=useState(1200000);const[startup,setStartup]=useState(25000000);
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{let r:any;if(tab==='26')r=await getVirDigitalTwin({locationId:locationId||undefined,revenue_change:revenueChange,price_change:priceChange,utilization_change:utilChange});else if(tab==='27')r=await postVirGoalAction({locationId:locationId||undefined,goal,target_percent:target,horizon_days:horizon});else if(tab==='28')r=await postVirActionPreview({locationId:locationId||undefined,action_type:actionType,expected_revenue_change_percent:impact,expected_cost_change_percent:cost});else if(tab==='31')r=await getVirCompetitorIntelligence({locationId:locationId||undefined,days:horizon});else r=await getVirLocationExpansion({candidate_name:candidate,expected_monthly_appointments:appointments,avg_ticket:avgTicket,monthly_rent:rent,startup_cost:startup});setData(r);}catch(e:any){setError(e?.response?.data?.error||e?.message||'Betöltési hiba');}finally{setLoading(false);}},[tab,locationId,revenueChange,priceChange,utilChange,goal,target,horizon,actionType,impact,cost,candidate,appointments,avgTicket,rent,startup]);
 useEffect(()=>{void load();},[load]);
 return <div className="vir-management-page"><div className="vir-management-header"><div><h1 className="vir-management-title">VIR P5 · Advanced Management Intelligence</h1><div className="vir-management-subtitle">Szimuláció, cél→akció tervezés, végrehajtás előtti preview, versenyhelyzet-proxy és telephely-bővítési döntéstámogatás. Automatikus üzleti végrehajtás nélkül.</div></div><div className="vir-management-actions"><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div></div>
 <div className="vir-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'is-active':''} onClick={()=>setTab(id)}>{id}. {label}</button>)}</div>
 {tab==='26'&&<div className="vir-management-actions"><label className="vir-field"><span>Árbevétel %</span><input type="number" value={revenueChange} onChange={e=>setRevenueChange(Number(e.target.value))}/></label><label className="vir-field"><span>Ár %</span><input type="number" value={priceChange} onChange={e=>setPriceChange(Number(e.target.value))}/></label><label className="vir-field"><span>Kihasználtság %</span><input type="number" value={utilChange} onChange={e=>setUtilChange(Number(e.target.value))}/></label></div>}
 {tab==='27'&&<div className="vir-management-actions"><label className="vir-field"><span>Cél</span><select value={goal} onChange={e=>setGoal(e.target.value)}><option value="revenue_growth">Árbevétel-növekedés</option><option value="margin_growth">Margin-növekedés</option><option value="capacity">Kihasználtság</option></select></label><label className="vir-field"><span>Cél %</span><input type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label className="vir-field"><span>Horizont</span><select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={30}>30 nap</option><option value={60}>60 nap</option><option value={90}>90 nap</option></select></label></div>}
 {tab==='28'&&<div className="vir-management-actions"><label className="vir-field"><span>Akció</span><select value={actionType} onChange={e=>setActionType(e.target.value)}><option>CAPACITY</option><option>PRICING</option><option>RETENTION</option><option>MARKETING</option></select></label><label className="vir-field"><span>Árbevételhatás %</span><input type="number" value={impact} onChange={e=>setImpact(Number(e.target.value))}/></label><label className="vir-field"><span>Költséghatás %</span><input type="number" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label></div>}
 {tab==='32'&&<div className="vir-management-actions"><label className="vir-field"><span>Jelölt helyszín</span><input value={candidate} onChange={e=>setCandidate(e.target.value)}/></label><label className="vir-field"><span>Havi időpont</span><input type="number" value={appointments} onChange={e=>setAppointments(Number(e.target.value))}/></label><label className="vir-field"><span>Átlagkosár</span><input type="number" value={avgTicket} onChange={e=>setAvgTicket(Number(e.target.value))}/></label><label className="vir-field"><span>Havi bérlet</span><input type="number" value={rent} onChange={e=>setRent(Number(e.target.value))}/></label><label className="vir-field"><span>Induló beruházás</span><input type="number" value={startup} onChange={e=>setStartup(Number(e.target.value))}/></label></div>}
 {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">P5 intelligence számítása…</div>}
 {!loading&&tab==='26'&&<section className="vir-panel"><div className="vir-panel-title">26. Digital Twin</div><div className="vir-panel-muted">Determinista what-if modell a kanonikus profit engine alapján. simulation_only=true, automatic_writes=false.</div><table className="vir-source-table"><thead><tr><th>Telephely</th><th>Alap árbevétel</th><th>Szimulált árbevétel</th><th>Δ árbevétel</th><th>Alap profit</th><th>Szimulált profit</th><th>Δ profit</th></tr></thead><tbody>{data?.items?.map((x:any)=><tr key={x.location_id}><td>{x.location_name}</td><td>{money(x.baseline.revenue)}</td><td>{money(x.scenario.revenue)}</td><td>{money(x.delta.revenue)}</td><td>{money(x.baseline.gross_profit)}</td><td>{money(x.scenario.gross_profit)}</td><td>{money(x.delta.gross_profit)}</td></tr>)}</tbody></table></section>}
 {!loading&&tab==='27'&&<section className="vir-panel"><div className="vir-panel-title">27. Goal → Action AI</div><div className="vir-panel-muted">A célból végrehajtási jelölteket készít Executive AI jelzések és profitadatok alapján. approval_required=true, automatic_actions=false.</div>{data?.items?.map((x:any)=><article className="vir-action-card" key={x.location_id}><div className="vir-action-title">{x.location_name}</div>{x.actions?.map((a:any,i:number)=><div key={i} className="vir-stat-line"><span>{a.type}: {a.action}</span><strong>{a.priority}</strong></div>)}</article>)}</section>}
 {!loading&&tab==='28'&&<section className="vir-panel"><div className="vir-panel-title">28. Autonomous Action Preview</div><div className="vir-panel-muted">Preview → Approval → Execute elv első lépése. A modul nem hajt végre műveletet; execution_enabled=false.</div><table className="vir-source-table"><thead><tr><th>Telephely</th><th>Akció</th><th>Előtte profit</th><th>Preview profit</th><th>Δ profit</th><th>Kockázat</th></tr></thead><tbody>{data?.previews?.map((x:any)=><tr key={x.location_id}><td>{x.location_name}</td><td>{x.action_type}</td><td>{money(x.before.gross_profit)}</td><td>{money(x.preview_after.gross_profit)}</td><td>{money(x.delta.gross_profit)}</td><td>{x.risk}</td></tr>)}</tbody></table></section>}
 {!loading&&tab==='31'&&<section className="vir-panel"><div className="vir-panel-title">31. Competitor Intelligence</div><div className="vir-panel-muted">{data?.warning}</div><table className="vir-source-table"><thead><tr><th>Telephely</th><th>Árbevétel</th><th>Időpont</th><th>Peer árbevétel eltérés</th><th>Peer időpont eltérés</th><th>Pozíció</th></tr></thead><tbody>{data?.items?.map((x:any)=><tr key={x.location_id}><td>{x.location_name}</td><td>{money(x.revenue)}</td><td>{x.appointments}</td><td>{x.revenue_vs_peer_pct}%</td><td>{x.appointments_vs_peer_pct}%</td><td><span className="vir-badge">{x.competitive_position}</span></td></tr>)}</tbody></table></section>}
 {!loading&&tab==='32'&&<section className="vir-panel"><div className="vir-panel-title">32. Location Expansion Intelligence</div><div className="vir-panel-muted">{data?.warning}</div>{data?.candidate&&<div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">Expansion score</div><div className="vir-kpi-value">{data.candidate.expansion_score}/100</div></div><div className="vir-kpi"><div className="vir-kpi-label">Projektált havi árbevétel</div><div className="vir-kpi-value">{money(data.candidate.projected_monthly_revenue)}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Bérlet / árbevétel</div><div className="vir-kpi-value">{data.candidate.rent_to_revenue_percent}%</div></div><div className="vir-kpi"><div className="vir-kpi-label">Egyszerű megtérülés</div><div className="vir-kpi-value">{data.candidate.simple_payback_months} hó</div></div><div className="vir-kpi"><div className="vir-kpi-label">Ajánlás</div><div className="vir-kpi-value">{data.candidate.recommendation}</div></div></div>}</section>}
 </div>;
}
