import React,{useEffect,useState} from 'react';
import {approveP15ActionPlan,getP15ActionPlans,getP15CommandCenter,getP15Status,previewP15ActionPlan} from '../api/virP15';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';
const friendlyError=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'Az adatokat most nem sikerült betölteni.';
export default function VirP15Page(){
 const[data,setData]=useState<any>(null);const[status,setStatus]=useState<any>(null);const[title,setTitle]=useState('Nyitott vezetői akció');const[reason,setReason]=useState('VIR jelzés alapján kontrollált beavatkozás szükséges.');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[actionType,setActionType]=useState('MANAGEMENT_FOLLOWUP');const[locationId,setLocationId]=useState('');
 useEffect(()=>{void getP15Status().then(setStatus).catch(e=>setError(friendlyError(e)))},[]);
 const run=async(kind:'command'|'list'|'preview')=>{setLoading(true);setError('');try{setData(kind==='command'?await getP15CommandCenter():kind==='list'?await getP15ActionPlans():await previewP15ActionPlan({title,reason,action_type:actionType,location_id:locationId||undefined,proposal:{source:'P15_UI'}}))}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}};
 const approve=async(id:string)=>{setLoading(true);setError('');try{await approveP15ActionPlan(id);setData(await getP15ActionPlans())}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}};
 const plans=Array.isArray(data?.items)?data.items:data?.item?[data.item]:[];
 return <div className="vir-workspace">
  <header className="vir-workspace-hero"><h1>Vezetői akciótervek és jóváhagyás</h1><p>Összegyűjti a vezetői döntést igénylő helyzeteket, strukturált akciótervet készít belőlük, és auditált jóváhagyási folyamatot biztosít.</p></header>
  <div className="vir-workspace-grid"><div className="vir-stat-card"><span>Előnézeti tervek</span><strong>{status?.counts?.preview_plans??0}</strong></div><div className="vir-stat-card"><span>Jóváhagyott tervek</span><strong>{status?.counts?.approved_plans??0}</strong></div><div className="vir-stat-card"><span>Automatikus végrehajtás</span><strong>NEM</strong></div></div>
  <section className="vir-panel"><h2>Vezetői nézetek</h2><div className="vir-toolbar"><button className="vir-btn" onClick={()=>void run('command')} disabled={loading}>Vezetői összkép</button><button className="vir-btn secondary" onClick={()=>void run('list')} disabled={loading}>Akciótervek listája</button></div></section>
  <section className="vir-panel"><h2>Új akcióterv előkészítése</h2><p className="vir-panel-subtitle">Töltsd ki érthetően a célt és az indokot. A telephely kereshető listából választható.</p><div className="vir-form-row"><VirSearchSelect kind="locations" label="Telephely" value={locationId} onChange={setLocationId} optional placeholder="Telephely keresése..."/><div className="vir-field"><label>Akció típusa</label><select value={actionType} onChange={e=>setActionType(e.target.value)}><option value="MANAGEMENT_FOLLOWUP">Vezetői utánkövetés</option><option value="CUSTOMER_RECOVERY">Vendég visszanyerése</option><option value="REVENUE_PROTECTION">Bevételvédelem</option><option value="CAPACITY_ADJUSTMENT">Kapacitás módosítása</option></select></div></div><div className="vir-field" style={{marginTop:12}}><label>Akcióterv címe</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Pl. Holnapi kapacitáshiány kezelése"/></div><div className="vir-field" style={{marginTop:12}}><label>Miért van rá szükség?</label><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4}/></div><button className="vir-btn" style={{marginTop:12}} onClick={()=>void run('preview')} disabled={loading||!title.trim()||!reason.trim()}>Akcióterv előnézet készítése</button><div className="vir-help" style={{marginTop:12}}>Jóváhagyás után sincs automatikus végrehajtás. <strong>Kontroll:</strong> az approval kizárólag auditált státuszváltás; execution_enabled=false.</div></section>
  {error&&<div className="vir-error-friendly"><strong>Nem sikerült:</strong> {error}</div>}
  <section className="vir-panel"><h2>Akciótervek</h2>{plans.length===0?<div className="vir-empty-state">Nincs megjeleníthető akcióterv. Nyisd meg a listát vagy készíts előnézetet.</div>:<div className="vir-result-list">{plans.map((x:any)=><article className="vir-result-card" key={x.id}><h4>{x.title}</h4><p>{x.reason}</p><span className={`vir-chip ${x.status==='approved'?'success':'warning'}`}>{x.status==='approved'?'Jóváhagyott':'Előnézet'}</span>{x.status==='preview'&&<button className="vir-btn success" style={{marginLeft:10}} onClick={()=>void approve(x.id)} disabled={loading}>Jóváhagyom</button>}</article>)}</div>}{data&&<details className="vir-json-details"><summary>Technikai részletek</summary><pre>{JSON.stringify(data,null,2)}</pre></details>}</section>
 </div>;
}
