import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirCannibalization,getVirEmployeeRevenueCoach,getVirServicePortfolio,getVirSmartShiftGenerator,getVirWorkforceOptimizer}from"../api/virP4";
import{useLanguage}from"../i18n/LanguageProvider";
import"./VirManagement.css";

type Tab="21"|"22"|"23"|"24"|"25";
export default function VirP4Page(){
 const{language}=useLanguage();const en=language==='en';const t=(hu:string,enText:string)=>en?enText:hu;const fmtDate=(v:unknown)=>v?new Intl.DateTimeFormat(en?'en-US':'hu-HU').format(new Date(String(v))):"—";const money=(v:unknown)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(v)||0);
 const tabs:[Tab,string][]=[["21",t('Munkaerő-optimalizáló','Workforce Optimizer')],["22",t('Intelligens műszaktervező','Smart Shift Generator')],["23",t('Munkatársi bevételi coach','Employee Revenue Coach')],["24",t('Szolgáltatásportfólió-optimalizáló','Service Portfolio Optimizer')],["25",t('Kannibalizációfigyelő','Cannibalization Detector')]];
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[days,setDays]=useState(30);const[tab,setTab]=useState<Tab>("21");const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const p={locationId:locationId||undefined,days};const result=tab==="21"?await getVirWorkforceOptimizer(p):tab==="22"?await getVirSmartShiftGenerator(p):tab==="23"?await getVirEmployeeRevenueCoach(p):tab==="24"?await getVirServicePortfolio(p):await getVirCannibalization(p);setData(result);}catch(e:any){setError(e?.response?.data?.error||e?.message||(en?'Loading error':'Betöltési hiba'));}finally{setLoading(false);}},[locationId,days,tab,en]);
 useEffect(()=>{void load();},[load]);
 return <div className="vir-management-page">
  <div className="vir-management-header"><div><h1 className="vir-management-title">{t('Működési intelligencia','Operations Intelligence')}</h1><div className="vir-management-subtitle">{t('Munkaerő-, műszak-, munkatársi bevétel-, szolgáltatásportfólió- és hálózati kannibalizációs döntéstámogatás.','Decision support for workforce, shifts, staff revenue, service portfolio and cross-network cannibalization.')}</div></div><div className="vir-management-actions"><label className="vir-field"><span>{t('Telephely','Location')}</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">{t('Összes telephely','All locations')}</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="vir-field"><span>{t('Időablak','Time window')}</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={14}>{t('14 nap','14 days')}</option><option value={30}>{t('30 nap','30 days')}</option><option value={60}>{t('60 nap','60 days')}</option><option value={90}>{t('90 nap','90 days')}</option></select></label></div></div>
  <div className="vir-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}>{id}. {label}</button>)}</div>
  {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">{t('Működési intelligencia számítása…','Calculating operations intelligence…')}</div>}
  {!loading&&tab==="21"&&<section className="vir-panel"><div className="vir-panel-title">21. {t('Munkaerő-optimalizáló','Workforce Optimizer')}</div><div className="vir-panel-muted">{t('Publikált műszakok + aktuális foglalások + 56 napos historikus terhelés. Automatikus beosztás nélkül; a rendszer nem módosít műszakot.','Published shifts + current bookings + 56-day historical demand. Advisory only; the system does not modify shifts.')}</div><table className="vir-source-table"><thead><tr><th>{t('Telephely','Location')}</th><th>{t('Nap','Day')}</th><th>{t('Várható perc','Demand minutes')}</th><th>{t('Beosztott','Scheduled')}</th><th>{t('Szükséges','Required')}</th><th>{t('Hiány','Gap')}</th><th>{t('Kihasználtság','Utilization')}</th><th>{t('Készségblokk','Skill block')}</th><th>{t('Állapot','Status')}</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.location_name}</td><td>{fmtDate(x.day)}</td><td>{x.demand_minutes}</td><td>{x.scheduled_staff}</td><td>{x.required_staff}</td><td>{x.staff_gap}</td><td>{x.utilization_percent==null?'—':`${x.utilization_percent}%`}</td><td>{x.skill_coverage?.blocked_skill_rows||0}</td><td><span className="vir-badge">{x.status}</span></td></tr>)}</tbody></table></section>}
  {!loading&&tab==="22"&&<section className="vir-panel"><div className="vir-panel-title">22. {t('Intelligens műszaktervező','Smart Shift Generator')}</div><div className="vir-panel-muted">{t('Csak műszakjavaslat. Minden változtatás vezetői jóváhagyást igényel; a rendszer nem ír a műszaktáblába.','Shift proposal only. Every change requires management approval; the system does not write to the shift table.')}</div><table className="vir-source-table"><thead><tr><th>{t('Telephely','Location')}</th><th>{t('Nap','Day')}</th><th>{t('Hiány','Gap')}</th><th>{t('Javasolt műszak','Suggested shift')}</th><th>{t('Jelöltek','Candidates')}</th><th>{t('Státusz','Status')}</th></tr></thead><tbody>{data?.proposals?.map((x:any,i:number)=><tr key={i}><td>{x.location_name}</td><td>{fmtDate(x.day)}</td><td>+{x.staff_gap}</td><td>{x.suggested_shift?.start_local}–{x.suggested_shift?.end_local}</td><td>{x.candidates?.map((c:any)=>c.employee_name).join(', ')||t('Nincs szabad jelölt','No available candidate')}</td><td><span className="vir-badge">{t('JÓVÁHAGYÁS KELL','APPROVAL REQUIRED')}</span></td></tr>)}</tbody></table></section>}
  {!loading&&tab==="23"&&<section className="vir-panel"><div className="vir-panel-title">23. {t('Munkatársi bevételi coach','Employee Revenue Coach')}</div><div className="vir-panel-muted">{t('Nem büntető teljesítménytámogatás: visszafoglalás, bevétel/óra, szolgáltatásérték és kapacitás alapján ad fejlesztési javaslatot. Nincs automatikus HR-intézkedés.','Non-punitive performance support using rebooking, revenue/hour, service value and capacity. No automatic HR action is taken.')}</div><table className="vir-source-table"><thead><tr><th>{t('Munkatárs','Staff member')}</th><th>{t('Telephely','Location')}</th><th>{t('Időpont','Appointments')}</th><th>{t('Visszafoglalás','Rebooking')}</th><th>{t('Bevétel','Revenue')}</th><th>{t('Bevétel/óra','Revenue/hour')}</th><th>{t('Coach pontszám','Coach score')}</th><th>{t('Javaslat','Recommendation')}</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.employee_name}</td><td>{x.location_name}</td><td>{x.appointments}</td><td>{x.rebook_rate_percent}%</td><td>{money(x.revenue)}</td><td>{money(x.revenue_per_booked_hour)}</td><td>{x.coach_score}/100</td><td>{x.recommendations?.join(' ')}</td></tr>)}</tbody></table></section>}
  {!loading&&tab==="24"&&<section className="vir-panel"><div className="vir-panel-title">24. {t('Szolgáltatásportfólió-optimalizáló','Service Portfolio Optimizer')}</div><div className="vir-panel-muted">{t('Kereslet × időarányos bevétel alapján növelés / átárazás / tartás / felülvizsgálat döntéstámogatás. Nem módosít automatikusan szolgáltatást vagy árat.','Demand × time-adjusted revenue based GROW / REPRICE / HOLD / REVIEW decision support. It does not automatically modify services or prices.')}</div><table className="vir-source-table"><thead><tr><th>{t('Szolgáltatás','Service')}</th><th>{t('Foglalás','Bookings')}</th><th>{t('Vendég','Customers')}</th><th>{t('Átlagár','Average price')}</th><th>{t('Bevétel/óra','Revenue/hour')}</th><th>{t('Ajánlás','Recommendation')}</th><th>{t('Indok','Reason')}</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.service_name}</td><td>{x.bookings}</td><td>{x.clients}</td><td>{money(x.avg_price)}</td><td>{money(x.revenue_per_hour)}</td><td><span className="vir-badge">{x.recommendation}</span></td><td>{x.rationale}</td></tr>)}</tbody></table></section>}
  {!loading&&tab==="25"&&<section className="vir-panel"><div className="vir-panel-title">25. {t('Kannibalizációfigyelő','Cannibalization Detector')}</div><div className="vir-panel-muted">{t('Telephelyek közötti vendégáramlási jelzés. Az átfedés önmagában nem bizonyít kannibalizációt; kampány- és nyitási kontextussal kell értelmezni.','Signals customer movement between locations. Overlap alone does not prove cannibalization and must be interpreted with campaign and opening context.')}</div><table className="vir-source-table"><thead><tr><th>{t('Forrás szalon','Source salon')}</th><th>{t('Cél szalon','Destination salon')}</th><th>{t('Átfedő vendég','Shared customers')}</th><th>{t('Céloldali bevétel','Destination revenue')}</th><th>{t('Jelzés','Signal')}</th><th>{t('Értelmezés','Interpretation')}</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.source_location_name}</td><td>{x.destination_location_name}</td><td>{x.shared_clients}</td><td>{money(x.destination_revenue)}</td><td><span className="vir-badge">{x.signal}</span></td><td>{x.interpretation}</td></tr>)}</tbody></table></section>}
 </div>;
}
