import React,{useEffect,useState} from 'react';
import {getP9Campaigns,getP9Segments,getP9ChannelOptimizer,getP9Funnel,getP9Roi,getP9NextBestActions,getP9AbTests,getP9Attribution,getP9Suggestions,getP9Compliance} from '../api/virP9';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';

type Tab='campaigns'|'optimizer'|'funnel'|'roi'|'segments'|'nba'|'ab'|'attr'|'suggestions'|'compliance';
const tabs:[Tab,string][]=[['campaigns','51. Kampánykezelő'],['optimizer','52. AI Channel Optimizer 2.0'],['funnel','53. Conversion Funnel'],['roi','54. Campaign ROI'],['segments','55. Vendégszegmensek'],['nba','56. Next Best Action'],['ab','57. A/B tesztelés'],['attr','58. Attribution 3.0'],['suggestions','59. Kampányjavaslatok'],['compliance','60. Compliance Center']];
const fmt=(v:any)=>Number(v||0).toLocaleString('hu-HU');
const friendlyError=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'Betöltési hiba';
export default function VirP9Page(){const[tab,setTab]=useState<Tab>('campaigns');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[err,setErr]=useState('');const[locationId,setLocationId]=useState('');
useEffect(()=>{let alive=true;setLoading(true);setErr('');const p={locationId:locationId||undefined};const fn=tab==='campaigns'?getP9Campaigns:tab==='optimizer'?getP9ChannelOptimizer:tab==='funnel'?getP9Funnel:tab==='roi'?getP9Roi:tab==='segments'?getP9Segments:tab==='nba'?getP9NextBestActions:tab==='ab'?getP9AbTests:tab==='attr'?getP9Attribution:tab==='suggestions'?getP9Suggestions:getP9Compliance;fn(p).then(x=>alive&&setData(x)).catch(e=>alive&&setErr(friendlyError(e))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[tab,locationId]);
const rows=data?.items||data?.gaps||[];return <div className="vir-workspace"><header className="vir-workspace-hero"><h1>Marketing- és kommunikációs automatizálás</h1><p>Omnichannel kampányok, fizetett bevétel-alapú optimalizálás és compliance egy helyen. <b>A tényleges kiküldés továbbra is Preview → Approval → Execute kontroll alatt marad.</b></p></header><div className="vir-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div><section className="vir-panel"><h2>Telephely szűrés</h2><p className="vir-panel-subtitle">Keress szalonnév alapján; üresen a teljes hálózatot látod.</p><VirSearchSelect kind="locations" label="Telephely" value={locationId} onChange={setLocationId} optional placeholder="Szalon keresése..."/></section>{loading&&<div className="vir-help">Betöltés…</div>}{err&&<div className="vir-error-friendly">{err}</div>}
{tab==='campaigns'&&<section className="vir-panel"><h2>Omnichannel Campaign Manager</h2><p>Viber, Messenger, e-mail, SMS és push kampányok közös életciklusa. A kampány előnézhető és vezetőileg jóváhagyható; közvetlen provider-küldés nincs.</p><SimpleTable rows={rows} keys={['name','objective','segment_key','status','recipients','created_at']}/></section>}
{tab==='optimizer'&&<section className="vir-panel"><h2>AI Channel Optimizer 2.0</h2><p>Delivery + read + click + response + booking + <b>paid revenue</b> + költség + consent alapján vendégenként rangsorolja a csatornákat. Automatikus küldés nincs.</p><SimpleTable rows={rows} keys={['client_id','recommended_channel']}/></section>}
{tab==='funnel'&&<section className="vir-panel"><h2>Conversion Funnel</h2><p>Üzenet → kézbesítés → megnyitás → kattintás → foglalás → munkalap → tényleges fizetés.</p><SimpleTable rows={rows} keys={['campaign','channel','messages','delivered','opened','clicked','bookings','work_orders','paid_revenue']}/></section>}
{tab==='roi'&&<section className="vir-panel"><h2>Campaign ROI Dashboard</h2><SimpleTable rows={rows} keys={['campaign_id','name','channel','messages','communication_cost','bookings','paid_revenue','roi','revenue_per_message']}/></section>}
{tab==='segments'&&<section className="vir-panel"><h2>Automatikus vendégszegmensek</h2><p>30/60/90 napos inaktivitás, churn-jelzés, VIP, rendszeres újrafoglaló és árazási érzékenység-proxy. Az árérzékenység nem személyiségprofil.</p><SimpleTable rows={rows} keys={['client_name','days_since_visit','visits','paid_revenue','segments']}/></section>}
{tab==='nba'&&<section className="vir-panel"><h2>Next Best Action</h2><p>Ajánlott akció, csatorna, ajánlat, időzítés és magyarázat. Végrehajtás csak jóváhagyással.</p><SimpleTable rows={rows} keys={['client_name','recommended_channel','action','offer','timing','rationale']}/></section>}
{tab==='ab'&&<section className="vir-panel"><h2>A/B tesztelés</h2><p>Szöveg, ajánlat, CTA, időzítés és csatorna összehasonlítása a ténylegesen kifizetett bevétel alapján.</p><SimpleTable rows={rows} keys={['campaign','variant','channel','messages','clicks','bookings','paid_revenue']}/></section>}
{tab==='attr'&&<section className="vir-panel"><h2>Marketing Attribution 3.0</h2><p><b>{data?.model||'multi_touch_linear_paid_ledger_attribution_v3'}</b> — 14 napos multi-touch, lineáris kredit. Paid ledger alapú, de nem állít kauzalitást.</p><SimpleTable rows={rows} keys={['channel','campaign_id','touches','attributed_paid_revenue']}/></section>}
{tab==='suggestions'&&<section className="vir-panel"><h2>Automatikus kampányjavaslatok</h2><p>{data?.suggestion||'Telephely kiválasztása után az üres idősávokra kampányjavaslat készül.'}</p><p>Elérhető vendégek csatornánként: {(data?.reachable_by_channel||[]).map((x:any)=>`${x.channel}: ${x.clients}`).join(' · ')||'—'}</p><div className="vir-help"><b>Automatikus kiküldés: NEM. Vezetői jóváhagyás szükséges.</b></div></section>}
{tab==='compliance'&&<section className="vir-panel"><h2>Communication Compliance Center</h2><p>Marketing/transactional consent, jogalap, opt-out és kommunikációs tiltás. A tiltás mindig felülírja a consentet.</p><SimpleTable rows={rows} keys={['client_id','channel','transactional_consent','marketing_consent','lawful_basis','opted_out_at','communication_blocked','block_reason']}/></section>}
</div>}
function SimpleTable({rows,keys}:{rows:any[];keys:string[]}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{keys.map(k=><th key={k} style={{textAlign:'left',borderBottom:'1px solid rgba(148,163,184,.35)',padding:10}}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((r,i)=><tr key={r.id||r.client_id||r.campaign_id||i}>{keys.map(k=><td key={k} style={{borderBottom:'1px solid rgba(148,163,184,.18)',padding:10}}>{Array.isArray(r[k])?r[k].join(', '):typeof r[k]==='number'?fmt(r[k]):String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div>}
