import React,{useCallback,useEffect,useState} from 'react';
import {getP10DynamicOffers,getP10EmptySlotAutopilot,getP10RevenueGuard,getP10NextBestOffers,simulateP10Promotion} from '../api/virP10';
import {useLanguage} from '../i18n/LanguageProvider';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';
type Tab='offers'|'slots'|'guard'|'next'|'sim';
const tabLabels:Record<Tab,{hu:string;en:string}>={offers:{hu:'51. Dinamikus ajánlatmotor',en:'51. Dynamic Offer Engine'},slots:{hu:'52. Üres idősáv autopilóta 2.0',en:'52. Empty Slot Autopilot 2.0'},guard:{hu:'53. Bevételvédelem',en:'53. Revenue Guard'},next:{hu:'54. Következő legjobb ajánlat',en:'54. Next Best Offer'},sim:{hu:'55. Promóciós profitszimulátor',en:'55. Promotion Profit Simulator'}};
const simLabels:Record<string,{hu:string;en:string}>={audience:{hu:'Célközönség',en:'Audience'},expected_response_percent:{hu:'Várt válaszarány (%)',en:'Expected response (%)'},avg_ticket:{hu:'Átlagos kosárérték',en:'Average ticket'},discount_percent:{hu:'Kedvezmény (%)',en:'Discount (%)'},communication_cost:{hu:'Kommunikációs költség',en:'Communication cost'}};
export default function VirP10Page(){const{language}=useLanguage();const lang=language==='en'?'en':'hu';const en=lang==='en';const[tab,setTab]=useState<Tab>('offers');const[locationId,setLocationId]=useState('');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[sim,setSim]=useState({audience:100,expected_response_percent:8,avg_ticket:15000,discount_percent:10,communication_cost:0});const load=useCallback(async()=>{setLoading(true);setError('');try{const p=locationId?{locationId}:{};setData(tab==='offers'?await getP10DynamicOffers(p):tab==='slots'?await getP10EmptySlotAutopilot(p):tab==='guard'?await getP10RevenueGuard(p):tab==='next'?await getP10NextBestOffers(p):await simulateP10Promotion({...sim,locationId:locationId||undefined}))}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||(en?'Loading error':'Betöltési hiba'))}finally{setLoading(false)}},[locationId,sim,tab,en]);useEffect(()=>{void load()},[load]);return <div className="vir-workspace"><header className="vir-workspace-hero"><h1>{en?'Revenue Autopilot':'Bevételi autopilóta'}</h1><p>{en?'Revenue-growth decision support without automatic discounts, bookings or campaign launches. Every executable action requires approval.':'Bevételnövelő döntéstámogatás automatikus kedvezmény, foglalás vagy kampányindítás nélkül. Minden végrehajtható akció jóváhagyást igényel.'}</p></header><div className="vir-tabs">{(Object.keys(tabLabels) as Tab[]).map(k=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{tabLabels[k][lang]}</button>)}</div><section className="vir-panel"><h2>{en?'Filters':'Szűrés'}</h2><div className="vir-toolbar"><VirSearchSelect kind="locations" label={en?'Location':'Telephely'} value={locationId} onChange={setLocationId} optional placeholder={en?'Search location...':'Telephely keresése...'}/><button className="vir-btn" onClick={()=>void load()} disabled={loading}>{en?'Refresh':'Frissítés'}</button></div></section>{tab==='sim'&&<section className="vir-panel"><h2>{en?'Promotion simulation':'Promóciós szimuláció'}</h2><div className="vir-form-row">{Object.entries(sim).map(([k,v])=><label className="vir-field" key={k}><label>{simLabels[k]?.[lang]||k}</label><input type="number" value={v} onChange={e=>setSim(s=>({...s,[k]:Number(e.target.value)}))}/></label>)}</div><button className="vir-btn" onClick={()=>void load()}>{en?'Simulate':'Szimuláció'}</button></section>}{error&&<div className="vir-error-friendly">{error}</div>}{loading&&<div className="vir-help">{en?'Loading…':'Betöltés…'}</div>}<section className="vir-panel"><h2>{en?'Result':'Eredmény'}</h2>{data?<details className="vir-json-details" open><summary>{en?'Analysis details':'Elemzés részletei'}</summary><pre>{JSON.stringify(data,null,2)}</pre></details>:<div className="vir-empty-state">{en?'No data.':'Nincs adat.'}</div>}</section></div>}
