import React,{useEffect,useState} from 'react';
import {getP12Journey,getP12NextStep,getP12RecoveryQueue,getP12Status} from '../api/virP12';
import {useLanguage} from '../i18n/LanguageProvider';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';
const friendlyError=(e:any,en:boolean)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||(en?'The data could not be loaded.':'Az adatokat most nem sikerült betölteni.');
export default function VirP12Page(){
 const{language}=useLanguage();const en=language==='en';const[clientId,setClientId]=useState('');const[data,setData]=useState<any>(null);const[status,setStatus]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{void getP12Status().then(setStatus).catch(e=>setError(friendlyError(e,en)))},[en]);
 const run=async(kind:'journey'|'next'|'queue')=>{setLoading(true);setError('');try{setData(kind==='queue'?await getP12RecoveryQueue():kind==='journey'?await getP12Journey(clientId):await getP12NextStep(clientId))}catch(e:any){setError(friendlyError(e,en))}finally{setLoading(false)}};
 return <div className="vir-workspace"><header className="vir-workspace-hero"><h1>{en?'Customer Journey Orchestration':'Vendégút-vezérlés'}</h1><p>{en?'See the customer journey, the next recommended step and recovery opportunities without automatic profile changes or outreach.':'Egy helyen látható a vendég előzménye, a következő javasolt lépés és a visszaszerzési lehetőség. Automatikus profilátírás vagy megkeresés nincs.'}</p></header>
 {status&&<div className="vir-workspace-grid"><div className="vir-stat-card"><span>{en?'Open handoffs':'Nyitott átadások'}</span><strong>{status.counts?.open_handoffs??0}</strong></div><div className="vir-stat-card"><span>{en?'Complaints':'Panaszok'}</span><strong>{status.counts?.open_complaints??0}</strong></div></div>}
 <section className="vir-panel"><h2>{en?'Customer selection':'Vendég kiválasztása'}</h2><p className="vir-panel-subtitle">{en?'Search by name, phone or email; no UUID needs to be typed.':'Keress név, telefonszám vagy e-mail alapján; UUID-t nem kell beírni.'}</p><div className="vir-toolbar"><VirSearchSelect kind="clients" label={en?'Customer':'Vendég'} value={clientId} onChange={setClientId} placeholder={en?'Start typing a name, phone or email...':'Kezdj el nevet, telefonszámot vagy e-mailt írni...'}/><button className="vir-btn" onClick={()=>void run('journey')} disabled={loading||!clientId}>{en?'Journey':'Ügyfélút'}</button><button className="vir-btn secondary" onClick={()=>void run('next')} disabled={loading||!clientId}>{en?'Next best step':'Következő javasolt lépés'}</button><button className="vir-btn secondary" onClick={()=>void run('queue')} disabled={loading}>{en?'Recovery queue':'Helyreállítási lista'}</button></div></section>
 {error&&<div className="vir-error-friendly">{error}</div>}{loading&&<div className="vir-help">{en?'Loading…':'Betöltés…'}</div>}
 <section className="vir-panel"><h2>{en?'Result':'Eredmény'}</h2>{!data?<div className="vir-empty-state">{en?'Select a customer or open the recovery queue.':'Válassz vendéget, vagy nyisd meg a helyreállítási listát.'}</div>:Array.isArray(data?.items)?<div className="vir-result-list">{data.items.slice(0,80).map((x:any,i:number)=><article className="vir-result-card" key={x.id||i}><h4>{x.type||x.action||x.full_name||x.client_name||`${en?'Item':'Elem'} ${i+1}`}</h4><p>{x.detail||x.reason||x.label||'—'}</p></article>)}</div>:<div className="vir-help">{data?.recommendation?.reason||data?.model|| (en?'Analysis ready.':'Az elemzés elkészült.')}</div>} {data&&<details className="vir-json-details"><summary>{en?'Technical details':'Technikai részletek'}</summary><pre>{JSON.stringify(data,null,2)}</pre></details>}</section>
 </div>;
}
