import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirWorkforceOptimizer}from"../api/virP4";
import"./VirManagement.css";

const date=(v:unknown)=>v?new Intl.DateTimeFormat("hu-HU").format(new Date(String(v))):"—";
export default function VirP4Page(){
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[days,setDays]=useState(14);
 const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await getVirWorkforceOptimizer({locationId:locationId||undefined,days}));}catch(e:any){setError(e?.response?.data?.error||e?.message||'Betöltési hiba');}finally{setLoading(false);}},[locationId,days]);
 useEffect(()=>{void load();},[load]);
 return <div className="vir-management-page">
  <div className="vir-management-header"><div><h1 className="vir-management-title">VIR P4 · Operational Intelligence</h1><div className="vir-management-subtitle">21. Workforce Optimizer — kereslet, publikált műszakok és szakmai kompetenciák alapján vezetői létszám-kapacitás javaslat. Automatikus beosztás nélkül.</div></div><div className="vir-management-actions"><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="vir-field"><span>Tervezési ablak</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 nap</option><option value={14}>14 nap</option><option value={21}>21 nap</option><option value={30}>30 nap</option></select></label></div></div>
  {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">Munkaerő-kapacitás elemzése…</div>}
  {!loading&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">Kritikus nap</div><div className="vir-kpi-value">{data.summary.critical_days}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">Létszámhiányos nap</div><div className="vir-kpi-value">{data.summary.shortage_days}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Összes kapacitáshiány</div><div className="vir-kpi-value">{data.summary.total_staff_gap} fő-nap</div></div><div className="vir-kpi"><div className="vir-kpi-label">30 napon belül lejáró képesítés</div><div className="vir-kpi-value">{data.summary.expiring_qualifications}</div></div></div>
  <section className="vir-panel"><div className="vir-panel-title">21. Workforce Optimizer</div><div className="vir-panel-muted">A nagyobb értéket veszi a már lekötött és az 56 napos historikus napi terhelésből, majd összeveti a publikált műszak kapacitásával. Ez döntéstámogatás: a rendszer nem módosít műszakot és nem értékeli büntető jelleggel a munkatársakat.</div><table className="vir-source-table"><thead><tr><th>Telephely</th><th>Nap</th><th>Foglalás</th><th>Várható perc</th><th>Beosztott</th><th>Szükséges</th><th>Gap</th><th>Kihasználtság</th><th>Skill blokk</th><th>Állapot / javaslat</th></tr></thead><tbody>{data.items?.map((x:any,i:number)=><tr key={`${x.location_id}-${x.day}-${i}`}><td>{x.location_name}</td><td>{date(x.day)}</td><td>{x.booked_count}</td><td>{x.demand_minutes}</td><td>{x.scheduled_staff}</td><td><strong>{x.required_staff}</strong></td><td>{x.staff_gap>0?`+${x.staff_gap}`:x.staff_gap}</td><td>{x.utilization_percent==null?'—':`${x.utilization_percent}%`}</td><td>{x.skill_coverage?.blocked_skill_rows||0}</td><td><span className="vir-badge">{x.status}</span><div className="vir-panel-muted">{x.rationale}</div></td></tr>)}</tbody></table></section></>}
 </div>;
}
