import React,{useCallback,useEffect,useState}from"react";
import{useSearchParams}from"react-router-dom";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirChurnRadar,getVirMembershipIntelligence,getVirNextVisit,getVirSmartPricing}from"../api/virP3";
import"./VirManagement.css";

type Tab="churn"|"next-visit"|"pricing"|"membership";
const money=(v:unknown)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
const date=(v:unknown)=>v?new Intl.DateTimeFormat("hu-HU").format(new Date(String(v))):"—";

export default function VirP3Page(){
 const[sp,setSp]=useSearchParams();const tab=(sp.get('tab')||'churn')as Tab;
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');
 const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const[horizonDays,setHorizonDays]=useState(30);const[pricingDays,setPricingDays]=useState(14);
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const common={locationId:locationId||undefined};const result=tab==='churn'?await getVirChurnRadar(common):tab==='next-visit'?await getVirNextVisit({...common,horizonDays}):tab==='pricing'?await getVirSmartPricing({...common,days:pricingDays}):await getVirMembershipIntelligence(common);setData(result);}catch(e:any){setError(e?.response?.data?.error||e?.message||'Betöltési hiba');}finally{setLoading(false);}},[tab,locationId,horizonDays,pricingDays]);
 useEffect(()=>{void load();},[load]);
 const tabs:[Tab,string][]=[['churn','15. Churn Radar'],['next-visit','16. Next Visit Engine'],['pricing','17. Smart Pricing'],['membership','18. Membership Intelligence']];
 return <div className="vir-management-page">
  <div className="vir-management-header"><div><h1 className="vir-management-title">VIR P3 · Revenue & Retention Intelligence</h1><div className="vir-management-subtitle">Vendégmegtartás, következő látogatás, keresletalapú árjavaslat és membership-potenciál. Minden eredmény döntéstámogató javaslat, automatikus végrehajtás nélkül.</div></div><div className="vir-management-actions"><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{tab==='next-visit'&&<label className="vir-field"><span>Előrejelzési ablak</span><select value={horizonDays} onChange={e=>setHorizonDays(Number(e.target.value))}><option value={14}>14 nap</option><option value={30}>30 nap</option><option value={60}>60 nap</option><option value={90}>90 nap</option></select></label>}{tab==='pricing'&&<label className="vir-field"><span>Árjavaslati időszak</span><select value={pricingDays} onChange={e=>setPricingDays(Number(e.target.value))}><option value={7}>7 nap</option><option value={14}>14 nap</option><option value={30}>30 nap</option></select></label>}</div></div>
  <div className="vir-management-actions" style={{marginBottom:18}}>{tabs.map(([k,l])=><button key={k} className={`vir-button ${tab===k?'':'secondary'}`} onClick={()=>setSp({tab:k})}>{l}</button>)}</div>
  {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">P3 elemzés frissítése…</div>}
  {!loading&&tab==='churn'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">Kritikus churn</div><div className="vir-kpi-value">{data.summary.critical}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">Magas kockázat</div><div className="vir-kpi-value">{data.summary.high}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Kockázatos ügyfélérték</div><div className="vir-kpi-value">{money(data.summary.revenue_at_risk)}</div></div></div><section className="vir-panel"><div className="vir-panel-title">15. Client Churn Radar</div><div className="vir-panel-muted">Magyarázható pontszám a saját látogatási ciklus, recency, no-show, lemondás, aktivitás és ügyfélérték alapján. Nem küld automatikus üzenetet.</div><table className="vir-source-table"><thead><tr><th>Vendég</th><th>Risk</th><th>Score</th><th>Utolsó látogatás</th><th>Ciklus</th><th>Eltelt nap</th><th>LTV</th><th>Indok</th></tr></thead><tbody>{data.items?.map((x:any)=><tr key={x.client_id}><td>{x.client_name}</td><td><span className="vir-badge">{x.risk}</span></td><td><strong>{x.churn_score}</strong></td><td>{date(x.last_visit)}</td><td>{x.avg_cycle_days} nap</td><td>{x.recency_days}</td><td>{money(x.lifetime_value)}</td><td>{x.reason}</td></tr>)}</tbody></table></section></>}
  {!loading&&tab==='next-visit'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">Lejárt ciklus</div><div className="vir-kpi-value">{data.summary.overdue}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">7 napon belül esedékes</div><div className="vir-kpi-value">{data.summary.due_7d}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Összes jelölt</div><div className="vir-kpi-value">{data.summary.due}</div></div></div><section className="vir-panel"><div className="vir-panel-title">16. Next Visit Engine</div><div className="vir-panel-muted">Vendég × szolgáltatás visszatérési ciklusból becsült következő optimális látogatás. A megkeresés külön jóváhagyást igényel.</div><table className="vir-source-table"><thead><tr><th>Vendég</th><th>Szolgáltatás</th><th>Utolsó</th><th>Átl. ciklus</th><th>Becsült következő</th><th>Eltérés</th><th>Állapot</th></tr></thead><tbody>{data.items?.map((x:any,i:number)=><tr key={`${x.client_id}-${x.service_id}-${i}`}><td>{x.client_name}</td><td>{x.service_name}</td><td>{date(x.last_visit)}</td><td>{x.avg_cycle_days} nap</td><td>{x.predicted_next_visit}</td><td>{x.days_until_due} nap</td><td><span className="vir-badge">{x.status}</span></td></tr>)}</tbody></table></section></>}
  {!loading&&tab==='pricing'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-warning"><div className="vir-kpi-label">Kedvezmény-jelölt</div><div className="vir-kpi-value">{data.summary.discount_candidates}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Védendő ársáv</div><div className="vir-kpi-value">{data.summary.protected_slots}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Elemzett sáv</div><div className="vir-kpi-value">{data.summary.slots}</div></div></div><section className="vir-panel"><div className="vir-panel-title">17. Smart Pricing</div><div className="vir-panel-muted">90 napos historikus kereslet és aktuális előfoglaltság alapján. A rendszer csak árat javasol; automatikus árátírás nincs.</div><table className="vir-source-table"><thead><tr><th>Nap</th><th>Óra</th><th>Foglalás</th><th>Demand index</th><th>Átl. ár</th><th>Javaslat</th><th>Kedvezmény</th><th>Javasolt ár</th></tr></thead><tbody>{data.items?.map((x:any,i:number)=><tr key={`${x.day}-${x.hour}-${i}`}><td>{date(x.day)}</td><td>{String(x.hour).padStart(2,'0')}:00</td><td>{x.booked}</td><td>{x.demand_index}</td><td>{money(x.avg_price)}</td><td>{x.recommendation}</td><td>{x.suggested_discount_percent}%</td><td>{money(x.suggested_price)}</td></tr>)}</tbody></table></section></>}
  {!loading&&tab==='membership'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">Membership jelölt</div><div className="vir-kpi-value">{data.summary.candidates}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">Gold</div><div className="vir-kpi-value">{data.summary.gold}</div></div><div className="vir-kpi is-critical"><div className="vir-kpi-label">VIP</div><div className="vir-kpi-value">{data.summary.vip}</div></div></div><section className="vir-panel"><div className="vir-panel-title">18. Membership Intelligence</div><div className="vir-panel-muted">12 havi látogatási gyakoriság és költés alapján membership-fit javaslat. Automatikus beléptetés nincs.</div><table className="vir-source-table"><thead><tr><th>Vendég</th><th>Látogatás / 12 hó</th><th>Költés / 12 hó</th><th>Átl. kosár</th><th>Javasolt csomag</th><th>Fit score</th><th>Indok</th></tr></thead><tbody>{data.items?.map((x:any)=><tr key={x.client_id}><td>{x.client_name}</td><td>{x.visits_12m}</td><td>{money(x.spend_12m)}</td><td>{money(x.avg_basket)}</td><td><span className="vir-badge">{x.recommended_plan}</span></td><td><strong>{x.membership_fit_score}</strong></td><td>{x.rationale}</td></tr>)}</tbody></table></section></>}
 </div>;
}
