import React,{useCallback,useEffect,useState} from 'react';
import {getP10DynamicOffers,getP10EmptySlotAutopilot,getP10RevenueGuard,getP10NextBestOffers,simulateP10Promotion} from '../api/virP10';
import VirSearchSelect from '../components/VirSearchSelect';
import './VirWorkspace.css';

type Tab='offers'|'slots'|'guard'|'next'|'sim';
const tabs:[Tab,string,string][]=[['offers','Dinamikus ajánlatok','51. Dynamic Offer Engine'],['slots','Üres idősávok','52. Empty Slot Autopilot 2.0'],['guard','Bevételvédelem','53. Revenue Guard'],['next','Következő legjobb ajánlat','54. Next Best Offer'],['sim','Promóciós szimulátor','55. Promotion Profit Simulator']];
const friendlyError=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'Az adatokat most nem sikerült betölteni.';
export default function VirP10Page(){
 const[tab,setTab]=useState<Tab>('offers');const[locationId,setLocationId]=useState('');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const[sim,setSim]=useState({audience:100,expected_response_percent:8,avg_ticket:15000,discount_percent:10,communication_cost:0});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const p=locationId?{locationId}:{};const d=tab==='offers'?await getP10DynamicOffers(p):tab==='slots'?await getP10EmptySlotAutopilot(p):tab==='guard'?await getP10RevenueGuard(p):tab==='next'?await getP10NextBestOffers(p):await simulateP10Promotion({...sim,locationId:locationId||undefined});setData(d)}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}},[locationId,sim,tab]);
 useEffect(()=>{void load()},[load]);
 const rows=Array.isArray(data?.items)?data.items:Array.isArray(data?.opportunities)?data.opportunities:[];
 return <div className="vir-workspace">
  <header className="vir-workspace-hero"><h1>Bevételnövelő automatizálási előnézetek</h1><p>Megkeresi a kihasználatlan bevételi lehetőségeket, ajánlatot és időzítést javasol, majd a promóció várható eredményét is kiszámítja. Minden végrehajtható akció jóváhagyást igényel.</p></header>
  <div className="vir-tabs">{tabs.map(([k,label,title])=><button key={k} title={title} className={tab===k?'active':''} onClick={()=>setTab(k)}>{label}</button>)}</div>
  <section className="vir-panel"><h2>Telephely</h2><p className="vir-panel-subtitle">Keresd ki a szalont név alapján. Üresen hagyva hálózati összesítést kapsz, ahol az adott funkció ezt támogatja.</p><div className="vir-toolbar"><VirSearchSelect kind="locations" label="Telephely" value={locationId} onChange={setLocationId} optional placeholder="Szalon keresése..."/><button className="vir-btn secondary" onClick={()=>void load()} disabled={loading}>{loading?'Betöltés...':'Frissítés'}</button></div></section>
  {tab==='sim'&&<section className="vir-panel"><h2>Promóciós szimuláció</h2><div className="vir-form-row"><div className="vir-field"><label>Célközönség (fő)</label><input type="number" min="0" value={sim.audience} onChange={e=>setSim(s=>({...s,audience:Number(e.target.value)}))}/></div><div className="vir-field"><label>Várható reakció (%)</label><input type="number" min="0" max="100" value={sim.expected_response_percent} onChange={e=>setSim(s=>({...s,expected_response_percent:Number(e.target.value)}))}/></div><div className="vir-field"><label>Átlagos kosár (Ft)</label><input type="number" min="0" value={sim.avg_ticket} onChange={e=>setSim(s=>({...s,avg_ticket:Number(e.target.value)}))}/></div><div className="vir-field"><label>Kedvezmény (%)</label><input type="number" min="0" max="100" value={sim.discount_percent} onChange={e=>setSim(s=>({...s,discount_percent:Number(e.target.value)}))}/></div><div className="vir-field"><label>Kommunikációs költség (Ft)</label><input type="number" min="0" value={sim.communication_cost} onChange={e=>setSim(s=>({...s,communication_cost:Number(e.target.value)}))}/></div></div><button className="vir-btn" style={{marginTop:12}} onClick={()=>void load()} disabled={loading}>Szimuláció futtatása</button></section>}
  {error&&<div className="vir-error-friendly"><strong>Nem sikerült:</strong> {error}</div>}
  <section className="vir-panel"><h2>Eredmény</h2>{!data?<div className="vir-empty-state">Nincs betöltött adat.</div>:<>{rows.length>0&&<div className="vir-result-list">{rows.slice(0,40).map((x:any,i:number)=><article className="vir-result-card" key={x.client_id||x.id||x.gap?.start||i}><h4>{x.client_name||x.name||x.offer||x.action||'Lehetőség'}</h4><p>{x.rationale||x.reason||x.recommendation?.reason||''}</p>{x.estimated_recovered_value!==undefined&&<span className="vir-chip success">Várható visszanyert érték: {Number(x.estimated_recovered_value).toLocaleString('hu-HU')} Ft</span>}</article>)}</div>}<details className="vir-json-details"><summary>Technikai részletek</summary><pre>{JSON.stringify(data,null,2)}</pre></details></>}</section>
 </div>;
}
