import React,{useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {dismissP21Decision,evaluateP22Cycle,generateP21Decisions,getP20Status,getP21Decisions,getP21Status,getP22Cycles,getP22Policy,getP22Status,promoteP21Decision,runP20Model,syncP22Cycles,type P20Forecast,type P21Decision,type P22Cycle} from '../api/virP19';

type Props={locationId:string;days:7|30|90;en:boolean};
const tone=(p:string)=>p==='critical'?'danger':p==='high'?'warning':p==='positive'?'success':p==='negative'?'danger':'';
export default function VirP20P22Panel({locationId,days,en}:Props){
 const t=useCallback((hu:string,enText:string)=>en?enText:hu,[en]);const[p20,setP20]=useState<P20Forecast|null>(null),[p20Status,setP20Status]=useState<any>(null),[p21Status,setP21Status]=useState<any>(null),[p22Status,setP22Status]=useState<any>(null),[decisions,setDecisions]=useState<P21Decision[]>([]),[cycles,setCycles]=useState<P22Cycle[]>([]),[policy,setPolicy]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const refresh=useCallback(async()=>{const[a,b,c,d,e]=await Promise.allSettled([getP20Status(),getP21Status(),getP21Decisions(),getP22Status(),getP22Cycles()]);if(a.status==='fulfilled')setP20Status(a.value);if(b.status==='fulfilled')setP21Status(b.value);if(c.status==='fulfilled')setDecisions(c.value.items||[]);if(d.status==='fulfilled')setP22Status(d.value);if(e.status==='fulfilled')setCycles(e.value.items||[]);getP22Policy().then(r=>setPolicy(r.items||[])).catch(()=>undefined)},[]);useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{setP20(null)},[locationId,days]);
 const guarded=async(fn:()=>Promise<void>)=>{setLoading(true);setError('');try{await fn()}catch(e:any){setError(e?.response?.data?.error||e?.message||t('A művelet nem hajtható végre.','Operation could not be completed.'))}finally{setLoading(false)}};
 const runModel=()=>guarded(async()=>{const r=await runP20Model({days,locationId:locationId||undefined});setP20(r.forecast);await refresh()});const generate=()=>guarded(async()=>{const r=await generateP21Decisions({locationId:locationId||undefined});setDecisions(r.items||[]);await refresh()});const promote=(id:string)=>guarded(async()=>{await promoteP21Decision(id);await refresh()});const dismiss=(id:string)=>guarded(async()=>{await dismissP21Decision(id);await refresh()});const sync=()=>guarded(async()=>{await syncP22Cycles();await refresh()});const evaluate=(id:string)=>guarded(async()=>{await evaluateP22Cycle(id);await refresh()});const money=(n:number)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(n||0));
 return <>
  <section className="vir-panel vir-stage-panel"><div className="vir-stage-heading"><div><span className="vir-chip">{t('Validáció','Validation')}</span><h2>{t('Validált prediktív modell','Validated predictive model')}</h2><p className="vir-panel-subtitle">{t('Trend + heti szezonalitás + momentum, visszaméréssel és becslési intervallummal.','Trend + weekly seasonality + momentum with backtesting and prediction intervals.')}</p></div><strong className="vir-health-value">MAPE {Number(p20Status?.counts?.avg_mape||0).toFixed(1)}%</strong></div><div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Modellfuttatások','Model runs')}</span><strong>{p20Status?.counts?.runs??0}</strong></div><div className="vir-stat-card"><span>{t('Backtest','Backtest')}</span><strong>{t('AKTÍV','ON')}</strong></div><div className="vir-stat-card"><span>{t('Éles automatikus végrehajtás','Automatic production execution')}</span><strong>{t('TILTVA','BLOCKED')}</strong></div></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void runModel()}>{t('Validált modell futtatása','Run validated model')}</button></div>{p20&&<div className="vir-compare-grid"><article className="vir-result-card"><h4>{t('Validált előrejelzés','Validated forecast')}</h4><p>{money(p20.revenue_forecast)} · {p20.booking_forecast} {t('foglalás','bookings')}</p><small>{t('90%-os becslési sáv','90% prediction interval')}: {money(p20.revenue_lower)} – {money(p20.revenue_upper)}</small></article><article className="vir-result-card"><h4>{t('Modellhiba','Model error')}</h4><p>MAPE {p20.metrics.mape_percent.toFixed(1)}% · MAE {money(p20.metrics.mae)}</p><small>{t('Bizalom','Confidence')}: {Math.round(p20.confidence*100)}%</small></article></div>}</section>
  <section className="vir-panel vir-stage-panel"><div className="vir-stage-heading"><div><span className="vir-chip">{t('Ajánlás','Recommendation')}</span><h2>{t('AI vezetői döntéstámogatás','AI executive decision support')}</h2><p className="vir-panel-subtitle">{t('A prediktív jeleket, operatív KPI-kat és korábbi visszamért eredményeket pontozza; minden javaslat indoklással és kockázattal készül.','Scores predictive signals, operational KPIs and measured past outcomes; every recommendation includes rationale and risk.')}</p></div><strong className="vir-health-value">{p21Status?.counts?.proposed??0} {t('nyitott','open')}</strong></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void generate()}>{t('AI-javaslatok frissítése','Refresh AI recommendations')}</button><Link className="vir-btn secondary" to="/admin/vir/p17">{t('Jóváhagyási központ','Approval center')}</Link></div><div className="vir-result-list">{decisions.slice(0,12).map(d=><article className="vir-result-card" key={d.id}><span className={`vir-chip ${tone(d.priority)}`}>{d.priority} · {Math.round(Number(d.score||0))}/100</span><h4>{d.title}</h4><p>{d.rationale}</p><small>{t('Bizalom','Confidence')}: {Math.round(Number(d.confidence||0)*100)}% · {t('tanulási minták','learning samples')}: {Number((d.learning as any)?.samples||0)}</small>{d.status==='proposed'&&<div className="vir-toolbar"><button className="vir-btn success" disabled={loading} onClick={()=>void promote(d.id)}>{t('Jóváhagyásra küldés','Send for approval')}</button><button className="vir-btn danger" disabled={loading} onClick={()=>void dismiss(d.id)}>{t('Elvetés','Dismiss')}</button></div>}{d.status==='promoted'&&<div className="vir-help">{t('Kontrollált művelet','Governed operation')}: {d.promoted_operation_id}</div>}</article>)}</div></section>
  <section className="vir-panel vir-stage-panel"><div className="vir-stage-heading"><div><span className="vir-chip">{t('Visszamérés','Feedback')}</span><h2>{t('Zárt visszacsatolású tanulás','Closed-loop learning')}</h2><p className="vir-panel-subtitle">{t('Csak végrehajtott és ellenőrzött kontrollált műveletből tanul; a before/after eredményt a következő ajánlások súlyozásába adja vissza.','Learns only from executed and verified governed operations; measured before/after outcomes feed future recommendation weighting.')}</p></div><strong className="vir-health-value">{p22Status?.counts?.evaluated??0} {t('kiértékelt','evaluated')}</strong></div><div className="vir-toolbar"><button className="vir-btn" disabled={loading} onClick={()=>void sync()}>{t('Ellenőrzött műveletek szinkronja','Sync verified operations')}</button></div><div className="vir-result-list">{cycles.slice(0,12).map(c=><article className="vir-result-card" key={c.id}><span className={`vir-chip ${tone(c.outcome_class||'')}`}>{c.status}{c.outcome_class?` · ${c.outcome_class}`:''}</span><h4>{c.decision_title||c.operation_type}</h4><p>{t('Megfigyelési ablak','Observation window')}: {c.observation_days} {t('nap','days')} · {t('művelet','operation')}: {c.operation_status||'—'}</p>{c.optimization_score!=null&&<small>{t('Optimalizációs pontszám','Optimization score')}: {Number(c.optimization_score).toFixed(1)}</small>}{c.status==='observing'&&c.operation_status==='verified'&&<div className="vir-toolbar"><button className="vir-btn secondary" disabled={loading} onClick={()=>void evaluate(c.id)}>{t('Eredmény kiértékelése','Evaluate outcome')}</button></div>}</article>)}</div>{policy.length>0&&<details className="vir-json-details"><summary>{t('Tanult döntési súlyok','Learned decision weights')}</summary><pre>{JSON.stringify(policy,null,2)}</pre></details>}<div className="vir-help"><strong>{t('Biztonsági korlát:','Safety boundary:')}</strong> {t('a tanuló réteg csak a későbbi ajánlások pontszámát módosítja; éles üzleti adatot nem ír át.','the learning layer only adjusts future recommendation scores; it does not mutate production business data.')}</div></section>
  {error&&<div className="vir-error-friendly">{error}</div>}
 </>;
}