import React,{useCallback,useEffect,useState}from"react";
import{useSearchParams}from"react-router-dom";
import{getLocations,type LocationRow}from"../api/locations";
import{askVirCopilot,getVirAnomalies,getVirBenchmark,getVirSummaries}from"../api/virP2";
import"./VirManagement.css";
type Tab="copilot"|"anomalies"|"summaries"|"benchmark";
const money=(v:unknown)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
export default function VirP2Page(){
 const[sp,setSp]=useSearchParams();const tab=(sp.get('tab')||'copilot')as Tab;const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[question,setQuestion]=useState('Mi igényel ma vezetői figyelmet?');const[days,setDays]=useState(30);
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{if(tab==='copilot')return;setLoading(true);setError('');try{const result=tab==='anomalies'?await getVirAnomalies({locationId:locationId||undefined}):tab==='summaries'?await getVirSummaries({locationId:locationId||undefined}):await getVirBenchmark({days,locationId:locationId||undefined});setData(result);}catch(e:any){setError(e?.response?.data?.error||e?.message||'Betöltési hiba');}finally{setLoading(false);}},[tab,locationId,days]);
 useEffect(()=>{void load();},[load]);
 const ask=async()=>{setLoading(true);setError('');try{setData(await askVirCopilot({question,locationId:locationId||undefined}));}catch(e:any){setError(e?.response?.data?.error||e?.message||'A Copilot nem válaszolt.');}finally{setLoading(false);}};
 return <div className="vir-management-page"><div className="vir-management-header"><div><h1 className="vir-management-title">VIR P2 Intelligence</h1><div className="vir-management-subtitle">AI Copilot, anomáliafelismerés, automatikus vezetői összefoglalók és szalonbenchmark.</div></div><div className="vir-management-actions"><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{tab==='benchmark'&&<label className="vir-field"><span>Időszak</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 nap</option><option value={30}>30 nap</option><option value={90}>90 nap</option></select></label>}</div></div>
 <div className="vir-management-actions" style={{marginBottom:18}}>{([['copilot','VIR AI Copilot'],['anomalies','Anomáliák'],['summaries','Vezetői összefoglalók'],['benchmark','Szalon benchmark']]as[Tab,string][]).map(([k,l])=><button key={k} className={`vir-button ${tab===k?'':'secondary'}`} onClick={()=>setSp({tab:k})}>{l}</button>)}</div>{error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">P2 elemzés frissítése…</div>}
 {!loading&&tab==='copilot'&&<section className="vir-panel"><div className="vir-panel-title">11. VIR AI Copilot</div><div className="vir-panel-muted">A meglévő Executive AI determinisztikus VIR-jelzéseire épül. Nem hajt végre autonóm üzleti műveletet.</div><div className="vir-management-actions" style={{marginTop:14}}><input style={{minWidth:420,flex:1}} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask();}}/><button className="vir-button" onClick={()=>void ask()}>Kérdezés</button></div>{data?.answer&&<div className="vir-action-card" style={{marginTop:16}}><div className="vir-action-title">Copilot válasz</div><div className="vir-action-description" style={{whiteSpace:'pre-wrap'}}>{data.answer}</div><div className="vir-badge-row"><span className="vir-badge">{data.ai_used?'AI narratíva':'Determinista fallback'}</span><span className="vir-badge">{data.mode||'executive-ai'}</span></div></div>}</section>}
 {!loading&&tab==='anomalies'&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">Kritikus anomália</div><div className="vir-kpi-value">{data.summary.critical}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">Figyelmeztetés</div><div className="vir-kpi-value">{data.summary.warning}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Érintett szalon</div><div className="vir-kpi-value">{data.summary.affected_locations}</div></div></div><section className="vir-panel"><div className="vir-panel-title">12. Anomáliafelismerés</div>{data.items?.map((x:any,i:number)=><article className={`vir-action-card is-${x.severity==='critical'?'critical':'high'}`} key={`${x.location_id}-${x.key}-${i}`}><div className="vir-action-title">{x.location_name} · {x.label}</div><div className="vir-action-description">{x.headline}</div><div className="vir-panel-muted">Javaslat: {x.recommendation}</div>{x.delta_pct!=null&&<span className="vir-badge">Eltérés: {x.delta_pct}%</span>}</article>)}</section></>}
 {!loading&&tab==='summaries'&&data?.summaries&&<section className="vir-panel"><div className="vir-panel-header"><div><div className="vir-panel-title">13. Automatikus vezetői összefoglalók</div><div className="vir-panel-muted">Automatika: {data.automation?.runs?.join(' · ')} · {data.automation?.timezone}. Az automata brief nem végez önálló üzleti beavatkozást.</div></div></div>{data.summaries.map((x:any)=><article className="vir-action-card" key={x.location_id}><div className="vir-action-title">{x.location_name} · {x.status}</div><div className="vir-action-description" style={{whiteSpace:'pre-wrap'}}>{x.narrative}</div><div className="vir-badge-row">{x.recommendations?.slice(0,4).map((r:string)=><span className="vir-badge" key={r}>{r}</span>)}</div></article>)}</section>}
 {!loading&&tab==='benchmark'&&data?.locations&&<section className="vir-panel"><div className="vir-panel-title">14. Szalonok közötti benchmarking</div><div className="vir-panel-muted">{data.days} napos összehasonlítás. A score árbevétel, átlagos foglalási érték, teljesítési arány és no-show alapján relatív hálózati index.</div><table className="vir-source-table"><thead><tr><th>#</th><th>Szalon</th><th>Score</th><th>Árbevétel</th><th>Hálózathoz képest</th><th>Átl. foglalás</th><th>Teljesítés</th><th>No-show</th></tr></thead><tbody>{data.locations.map((x:any)=><tr key={x.location_id}><td>{x.rank}</td><td>{x.location_name}</td><td><strong>{x.benchmark_score}</strong></td><td>{money(x.revenue)}</td><td>{x.revenue_vs_network_pct}%</td><td>{money(x.avg_booking)}</td><td>{x.completion_rate}%</td><td>{x.no_show_rate}%</td></tr>)}</tbody></table></section>}
 </div>;
}
