import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirCannibalization,getVirEmployeeRevenueCoach,getVirServicePortfolio,getVirSmartShiftGenerator,getVirWorkforceOptimizer}from"../api/virP4";
import"./VirManagement.css";

const fmtDate=(v:unknown)=>v?new Intl.DateTimeFormat("hu-HU").format(new Date(String(v))):"—";
const money=(v:unknown)=>new Intl.NumberFormat("hu-HU",{maximumFractionDigits:0}).format(Number(v)||0)+" Ft";
type Tab="21"|"22"|"23"|"24"|"25";
const tabs:[Tab,string][]=[["21","Workforce Optimizer"],["22","Smart Shift Generator"],["23","Employee Revenue Coach"],["24","Service Portfolio Optimizer"],["25","Cannibalization Detector"]];

export default function VirP4Page(){
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[days,setDays]=useState(30);const[tab,setTab]=useState<Tab>("21");
 const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const p={locationId:locationId||undefined,days};const result=tab==="21"?await getVirWorkforceOptimizer(p):tab==="22"?await getVirSmartShiftGenerator(p):tab==="23"?await getVirEmployeeRevenueCoach(p):tab==="24"?await getVirServicePortfolio(p):await getVirCannibalization(p);setData(result);}catch(e:any){setError(e?.response?.data?.error||e?.message||'Betöltési hiba');}finally{setLoading(false);}},[locationId,days,tab]);
 useEffect(()=>{void load();},[load]);
 return <div className="vir-management-page">
  <div className="vir-management-header"><div><h1 className="vir-management-title">VIR P4 · Operational Intelligence</h1><div className="vir-management-subtitle">Munkaerő-, műszak-, munkatársi bevétel-, szolgáltatásportfólió- és hálózati kannibalizációs döntéstámogatás.</div></div><div className="vir-management-actions"><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="vir-field"><span>Időablak</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={14}>14 nap</option><option value={30}>30 nap</option><option value={60}>60 nap</option><option value={90}>90 nap</option></select></label></div></div>
  <div className="vir-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}>{id}. {label}</button>)}</div>
  {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">P4 intelligence számítása…</div>}
  {!loading&&tab==="21"&&<section className="vir-panel"><div className="vir-panel-title">21. Workforce Optimizer</div><div className="vir-panel-muted">Publikált műszakok + aktuális foglalások + 56 napos historikus terhelés. Automatikus beosztás nélkül; a rendszer nem módosít műszakot.</div><table className="vir-source-table"><thead><tr><th>Telephely</th><th>Nap</th><th>Várható perc</th><th>Beosztott</th><th>Szükséges</th><th>Gap</th><th>Kihasználtság</th><th>Állapot</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.location_name}</td><td>{fmtDate(x.day)}</td><td>{x.demand_minutes}</td><td>{x.scheduled_staff}</td><td>{x.required_staff}</td><td>{x.staff_gap}</td><td>{x.utilization_percent==null?'—':`${x.utilization_percent}%`}</td><td><span className="vir-badge">{x.status}</span></td></tr>)}</tbody></table></section>}
  {!loading&&tab==="22"&&<section className="vir-panel"><div className="vir-panel-title">22. Smart Shift Generator</div><div className="vir-panel-muted">Csak műszakjavaslat. Minden változtatás vezetői jóváhagyást igényel; a rendszer nem ír a work_shifts táblába.</div><table className="vir-source-table"><thead><tr><th>Telephely</th><th>Nap</th><th>Gap</th><th>Javasolt műszak</th><th>Jelöltek</th><th>Státusz</th></tr></thead><tbody>{data?.proposals?.map((x:any,i:number)=><tr key={i}><td>{x.location_name}</td><td>{fmtDate(x.day)}</td><td>+{x.staff_gap}</td><td>{x.suggested_shift?.start_local}–{x.suggested_shift?.end_local}</td><td>{x.candidates?.map((c:any)=>c.employee_name).join(', ')||'Nincs szabad jelölt'}</td><td><span className="vir-badge">JÓVÁHAGYÁS KELL</span></td></tr>)}</tbody></table></section>}
  {!loading&&tab==="23"&&<section className="vir-panel"><div className="vir-panel-title">23. Employee Revenue Coach</div><div className="vir-panel-muted">Nem büntető teljesítmény-támogatás: visszafoglalás, bevétel/óra, szolgáltatásérték és kapacitás alapján ad fejlesztési javaslatot. Nincs automatikus HR-intézkedés.</div><table className="vir-source-table"><thead><tr><th>Munkatárs</th><th>Telephely</th><th>Időpont</th><th>Visszafoglalás</th><th>Bevétel</th><th>Bevétel/óra</th><th>Coach score</th><th>Javaslat</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.employee_name}</td><td>{x.location_name}</td><td>{x.appointments}</td><td>{x.rebook_rate_percent}%</td><td>{money(x.revenue)}</td><td>{money(x.revenue_per_booked_hour)}</td><td>{x.coach_score}/100</td><td>{x.recommendations?.join(' ')}</td></tr>)}</tbody></table></section>}
  {!loading&&tab==="24"&&<section className="vir-panel"><div className="vir-panel-title">24. Service Portfolio Optimizer</div><div className="vir-panel-muted">Kereslet × időarányos bevétel alapján GROW / REPRICE / HOLD / REVIEW döntéstámogatás. Nem módosít automatikusan szolgáltatást vagy árat.</div><table className="vir-source-table"><thead><tr><th>Szolgáltatás</th><th>Foglalás</th><th>Vendég</th><th>Átlagár</th><th>Bevétel/óra</th><th>Ajánlás</th><th>Indok</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.service_name}</td><td>{x.bookings}</td><td>{x.clients}</td><td>{money(x.avg_price)}</td><td>{money(x.revenue_per_hour)}</td><td><span className="vir-badge">{x.recommendation}</span></td><td>{x.rationale}</td></tr>)}</tbody></table></section>}
  {!loading&&tab==="25"&&<section className="vir-panel"><div className="vir-panel-title">25. Cannibalization Detector</div><div className="vir-panel-muted">Telephelyek közötti vendégáramlási jelzés. Az átfedés önmagában nem bizonyít kannibalizációt; kampány- és nyitási kontextussal kell értelmezni.</div><table className="vir-source-table"><thead><tr><th>Forrás szalon</th><th>Cél szalon</th><th>Átfedő vendég</th><th>Céloldali bevétel</th><th>Jelzés</th><th>Értelmezés</th></tr></thead><tbody>{data?.items?.map((x:any,i:number)=><tr key={i}><td>{x.source_location_name}</td><td>{x.destination_location_name}</td><td>{x.shared_clients}</td><td>{money(x.destination_revenue)}</td><td><span className="vir-badge">{x.signal}</span></td><td>{x.interpretation}</td></tr>)}</tbody></table></section>}
 </div>;
}
