import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getAgentGatewayAvailability,getAgentGatewayCapabilities,getBookingRecovery,getExternalCompetitorIntelligence,getIntelligentScheduling,postAiReceptionistPreview,postConsultationPreview}from"../api/virP6";
import{useLanguage}from"../i18n/LanguageProvider";
import"./VirManagement.css";

type Tab="33"|"34"|"35"|"36"|"37"|"38";
export default function VirP6Page(){
 const{language}=useLanguage();const en=language==='en';const t=(hu:string,enText:string)=>en?enText:hu;const money=(v:unknown)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(v)||0);const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString(en?'en-US':'hu-HU'):"—";
 const tabs:[Tab,string][]=[["33",t('AI-recepciós','AI Receptionist')],["34",t('Intelligens időpontkiosztás 2.0','Intelligent Scheduling 2.0')],["35",t('Foglalás-visszaszerző motor','Booking Recovery Engine')],["36",t('AI-natív foglalási átjáró','AI-native Booking Gateway')],["37",t('Külső versenytárs-intelligencia 2.0','External Competitor Intelligence 2.0')],["38",t('AI-konzultáció / szépségvizualizáló','AI Consultation / Beauty Visualizer')]];
 const[locations,setLocations]=useState<LocationRow[]>([]);const[locationId,setLocationId]=useState('');const[tab,setTab]=useState<Tab>('33');const[days,setDays]=useState(14);const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('Szombaton délután szeretnék hajvágást 4 után.');const[concern,setConcern]=useState('új frizura és hajszín');
 useEffect(()=>{getLocations().then(rows=>{setLocations(rows);if(rows.length)setLocationId(String(rows[0].id));}).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{let r:any;const p={locationId:locationId||undefined,days};if(tab==='33')r=await postAiReceptionistPreview({locationId:locationId||undefined,message});else if(tab==='34')r=await getIntelligentScheduling(p);else if(tab==='35')r=await getBookingRecovery(p);else if(tab==='36'){const cap=await getAgentGatewayCapabilities({locationId:locationId||undefined});const av=locationId?await getAgentGatewayAvailability({locationId,days:Math.min(days,14)}):null;r={capabilities:cap,availability:av};}else if(tab==='37')r=await getExternalCompetitorIntelligence({locationId:locationId||undefined});else r=await postConsultationPreview({locationId,concern});setData(r);}catch(e:any){setError(e?.response?.data?.error||e?.message||(en?'Loading error':'Betöltési hiba'));}finally{setLoading(false);}},[tab,locationId,days,message,concern,en]);
 useEffect(()=>{if(tab==='38'&&!locationId)return;void load();},[load,tab,locationId]);
 return <div className="vir-management-page"><div className="vir-management-header"><div><h1 className="vir-management-title">{t('Automatikus bevételnövelés és vendégélmény','Autonomous Revenue & Guest Experience')}</h1><div className="vir-management-subtitle">{t('Vendégszerzés, kapacitáskitöltés és AI-natív foglalási infrastruktúra üzembiztos előnézeti/tanácsadó módban.','Customer acquisition, capacity filling and AI-native booking infrastructure in production-safe preview/advisory mode.')}</div></div><div className="vir-management-actions"><label className="vir-field"><span>{t('Telephely','Location')}</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">{t('Összes telephely','All locations')}</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="vir-field"><span>{t('Időtáv','Horizon')}</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>{t('7 nap','7 days')}</option><option value={14}>{t('14 nap','14 days')}</option><option value={30}>{t('30 nap','30 days')}</option></select></label></div></div>
 <div className="vir-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'is-active':''} onClick={()=>setTab(id)}>{id}. {label}</button>)}</div>
 {tab==='33'&&<div className="vir-management-actions"><label className="vir-field" style={{minWidth:420}}><span>{t('Vendég üzenete','Customer message')}</span><input value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="vir-button" onClick={()=>void load()}>{t('Értelmezés','Interpret')}</button></div>}
 {tab==='38'&&<div className="vir-management-actions"><label className="vir-field" style={{minWidth:420}}><span>{t('Stílus / kezelési cél','Style / treatment goal')}</span><input value={concern} onChange={e=>setConcern(e.target.value)}/></label><button className="vir-button" onClick={()=>void load()} disabled={!locationId}>{t('Konzultáció','Consultation')}</button></div>}
 {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">{t('Elemzés számítása…','Calculating analysis…')}</div>}
 {!loading&&tab==='33'&&data&&<section className="vir-panel"><div className="vir-panel-title">33. {t('AI-recepciós','AI Receptionist')}</div><div className="vir-panel-muted">{t('Webchat/kioszk/mobil szándékértelmezés + szolgáltatás- és elérhetőségi előnézet. Telefon/SMS szolgáltató még nincs bekötve; automatikus foglalásírás nincs.','Webchat/kiosk/mobile intent plus service and availability preview. Phone/SMS providers are not connected yet; automatic booking write is disabled.')}</div>{data.results?.map((r:any)=><article className="vir-action-card" key={r.location_id}><div className="vir-action-title">{r.location_name}</div><div className="vir-stat-line"><span>{t('Top szolgáltatások','Top services')}</span><strong>{r.service_candidates?.slice(0,3).map((x:any)=>x.name).join(' · ')||'—'}</strong></div><div className="vir-stat-line"><span>{t('Elérhető jelöltek','Available candidates')}</span><strong>{r.availability?.length||0}</strong></div></article>)}</section>}
 {!loading&&tab==='34'&&data&&<section className="vir-panel"><div className="vir-panel-title">34. {t('Intelligens időpontkiosztás 2.0','Intelligent Scheduling 2.0')}</div><div className="vir-panel-muted">{t('A kanonikus naptári rés motorra épül; publikált műszak esetén magasabb a megbízhatóság. Automatikus beosztásírás nincs.','Built on the canonical calendar-gap engine; confidence is higher for published shifts. Automatic schedule writes are disabled.')}</div><div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">{t('Lehetőség','Opportunities')}</div><div className="vir-kpi-value">{data.summary?.opportunities||0}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Nyitott kapacitásérték','Open capacity value')}</div><div className="vir-kpi-value">{money(data.summary?.estimated_open_capacity_value)}</div></div></div><table className="vir-source-table"><thead><tr><th>{t('Telephely','Location')}</th><th>{t('Munkatárs','Staff member')}</th><th>{t('Kezdet','Start')}</th><th>{t('Perc','Minutes')}</th><th>{t('Érték','Value')}</th><th>{t('Javaslat','Recommendation')}</th></tr></thead><tbody>{data.items?.slice(0,80).map((x:any,i:number)=><tr key={i}><td>{x.location_name}</td><td>{x.employee_name}</td><td>{dt(x.start)}</td><td>{x.minutes}</td><td>{money(x.estimated_value)}</td><td>{x.recommendation}</td></tr>)}</tbody></table></section>}
 {!loading&&tab==='35'&&data&&<section className="vir-panel"><div className="vir-panel-title">35. {t('Foglalás-visszaszerző motor','Booking Recovery Engine')}</div><div className="vir-panel-muted">{t('Várólista-kitöltés + no-show megelőzés. Automatikus megkeresés és újrafoglalás nincs; emberi jóváhagyás szükséges.','Waitlist fill plus no-show prevention. Automatic outreach and rebooking are disabled; human approval is required.')}</div><div className="vir-kpi-grid"><div className="vir-kpi"><div className="vir-kpi-label">{t('Visszatölthető idősáv','Recoverable slots')}</div><div className="vir-kpi-value">{data.summary?.waitlist_recovery_opportunities||0}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('Becsült menthető bevétel','Estimated recoverable revenue')}</div><div className="vir-kpi-value">{money(data.summary?.estimated_recoverable_value)}</div></div><div className="vir-kpi"><div className="vir-kpi-label">{t('No-show kockázat','No-show risk')}</div><div className="vir-kpi-value">{data.summary?.elevated_no_show_risks||0}</div></div></div></section>}
 {!loading&&tab==='36'&&data&&<section className="vir-panel"><div className="vir-panel-title">36. {t('AI-natív foglalási átjáró','AI-native Booking Gateway')}</div><div className="vir-panel-muted">{t('Belső, hitelesített, csak olvasható ügynöki átjáró. Külső ügynök-hitelesítés és nyilvános végpont még nincs engedélyezve.','Internal authenticated read-only agent gateway. External agent authentication and a public endpoint are not enabled yet.')}</div><div className="vir-stat-line"><span>{t('Átjáró','Gateway')}</span><strong>{data.capabilities?.gateway}</strong></div><div className="vir-stat-line"><span>{t('Nyilvános végpont','Public endpoint')}</span><strong>{String(data.capabilities?.public_endpoint_enabled)}</strong></div><div className="vir-stat-line"><span>{t('Foglalásírás','Booking write')}</span><strong>{String(data.capabilities?.booking_write_enabled)}</strong></div><div className="vir-stat-line"><span>{t('Képességek','Capabilities')}</span><strong>{data.capabilities?.capabilities?.join(' · ')}</strong></div>{data.availability&&<div className="vir-stat-line"><span>{t('Csak olvasható elérhetőség','Read-only availability')}</span><strong>{data.availability?.availability?.length||0} {t('idősáv','slots')}</strong></div>}</section>}
 {!loading&&tab==='37'&&data&&<section className="vir-panel"><div className="vir-panel-title">37. {t('Külső versenytárs-intelligencia 2.0','External Competitor Intelligence 2.0')}</div><div className="vir-panel-muted">{data.warning||t('Külső adatadapter állapota.','External data adapter status.')}</div><div className="vir-stat-line"><span>{t('Külső adatkapcsolat','External data connection')}</span><strong>{data.external_data_connected?t('AKTÍV','ACTIVE'):t('NINCS BEKÖTVE','NOT CONNECTED')}</strong></div><div className="vir-stat-line"><span>{t('Szintetikus adat','Synthetic data')}</span><strong>{data.synthetic_data_used?t('IGEN','YES'):t('NEM','NO')}</strong></div><div className="vir-stat-line"><span>{t('Megfigyelések','Observations')}</span><strong>{data.items?.length||0}</strong></div></section>}
 {!loading&&tab==='38'&&data&&<section className="vir-panel"><div className="vir-panel-title">38. {t('AI-konzultáció / szépségvizualizáló','AI Consultation / Beauty Visualizer')}</div><div className="vir-panel-muted">{t('Katalógusalapú konzultációs előnézet. Nem diagnózis; vizuális képszolgáltató jelenleg nincs bekötve és vendég-hozzájárulás szükséges.','Catalog-based consultation preview. Not a diagnosis; no visual image provider is currently connected and customer consent is required.')}</div><table className="vir-source-table"><thead><tr><th>{t('Szolgáltatás','Service')}</th><th>{t('Idő','Duration')}</th><th>{t('Ár','Price')}</th><th>{t('Egyezés','Match')}</th></tr></thead><tbody>{data.suggestions?.map((x:any)=><tr key={x.id}><td>{x.name}</td><td>{x.duration_minutes} {t('perc','min')}</td><td>{money(x.price)}</td><td>{x.match_score}</td></tr>)}</tbody></table></section>}
 </div>;
}
