import React,{useEffect,useState} from 'react';
import {getP14CapacityGaps,getP14ServiceBottlenecks,getP14Status,getP14WorkforcePressure,previewP14ShiftPlan} from '../api/virP14';
import './VirWorkspace.css';
const friendlyError=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'Az adatokat most nem sikerült betölteni.';
export default function VirP14Page(){
 const[data,setData]=useState<any>(null);const[status,setStatus]=useState<any>(null);const[loading,setLoading]=useState(false);const[days,setDays]=useState(7);const[error,setError]=useState('');
 useEffect(()=>{void getP14Status().then(setStatus).catch(e=>setError(friendlyError(e)))},[]);
 const run=async(kind:'pressure'|'gaps'|'services'|'shift')=>{setLoading(true);setError('');try{setData(kind==='pressure'?await getP14WorkforcePressure():kind==='gaps'?await getP14CapacityGaps():kind==='services'?await getP14ServiceBottlenecks():await previewP14ShiftPlan({days}))}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}};
 const items=Array.isArray(data?.items)?data.items:Array.isArray(data?.preview)?data.preview:[];
 return <div className="vir-workspace">
  <header className="vir-workspace-hero"><h1>Kapacitás és munkaerő optimalizálás</h1><p>Megmutatja, hol túlterhelt vagy kihasználatlan a csapat, mely szolgáltatások okoznak szűk keresztmetszetet, és előnézetet készít a szükséges műszak-kapacitásról.</p></header>
  <div className="vir-workspace-grid"><div className="vir-stat-card"><span>Mai foglalás</span><strong>{status?.counts?.appointments_today??0}</strong></div><div className="vir-stat-card"><span>Ma foglalt munkatárs</span><strong>{status?.counts?.booked_staff_today??0}</strong></div><div className="vir-stat-card"><span>Automatikus beosztásmódosítás</span><strong>NEM</strong></div></div>
  <section className="vir-panel"><h2>Mit szeretnél elemezni?</h2><p className="vir-panel-subtitle">Válassz egy nézetet. A műszakterv csak előnézetet készít, nem írja át a beosztást.</p><div className="vir-toolbar"><button className="vir-btn" onClick={()=>void run('pressure')} disabled={loading}>Munkatársi terhelés</button><button className="vir-btn secondary" onClick={()=>void run('gaps')} disabled={loading}>Kapacitásrések</button><button className="vir-btn secondary" onClick={()=>void run('services')} disabled={loading}>Szolgáltatási szűk keresztmetszet</button><div className="vir-field" style={{minWidth:180}}><label>Tervezési időszak</label><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 nap</option><option value={14}>14 nap</option><option value={21}>21 nap</option><option value={30}>30 nap</option></select></div><button className="vir-btn secondary" onClick={()=>void run('shift')} disabled={loading}>Műszakterv előnézet</button></div><div className="vir-help" style={{marginTop:12}}>Automatikus beosztásmódosítás: NEM.</div></section>
  {error&&<div className="vir-error-friendly"><strong>Nem sikerült:</strong> {error}</div>}
  <section className="vir-panel"><h2>Eredmény</h2>{!data?<div className="vir-empty-state">Válassz egy elemzést.</div>:<>{items.length>0&&<div className="vir-result-list">{items.slice(0,40).map((x:any,i:number)=><article className="vir-result-card" key={x.employee_id||x.service_id||x.day||i}><h4>{x.full_name||x.name||x.day||'Kapacitásadat'}</h4><p>{x.pressure&&<>Terhelés: <strong>{x.pressure}</strong></>}{x.capacity_signal&&<>Kapacitás: <strong>{x.capacity_signal}</strong></>}{x.bottleneck_risk&&<>Kockázat: <strong>{x.bottleneck_risk}</strong></>}</p>{x.suggested_extra_staff!==undefined&&<span className="vir-chip warning">Javasolt plusz létszám: {x.suggested_extra_staff}</span>}</article>)}</div>}<details className="vir-json-details"><summary>Technikai részletek</summary><pre>{JSON.stringify(data,null,2)}</pre></details></>}</section>
 </div>;
}
