import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {createDigitalTwinSnapshot,getDigitalTwin,getP23Status,getP24Status,getP25Status,optimizeBusiness,promoteOptimization,simulateBusinessScenario,type DigitalTwin,type OptimizerResult,type ScenarioLevers,type ScenarioSimulation} from '../api/virP23P25';

type Props={locationId:string;en:boolean};
const defaultLevers:ScenarioLevers={price_delta_percent:0,staff_hours_delta_percent:0,promotion_discount_percent:0,no_show_reduction_percent:10,stock_availability_delta_percent:0,demand_delta_percent:0};
const defaultWeights={revenue:22,profit:28,utilization:14,retention:14,staff_balance:12,stock_resilience:10};
const defaultConstraints={max_price_change_percent:10,max_discount_percent:15,max_staff_change_percent:20,min_margin_percent:20};
export default function VirP23P25Panel({locationId,en}:Props){
 const t=useCallback((hu:string,enText:string)=>en?enText:hu,[en]);const[twin,setTwin]=useState<DigitalTwin|null>(null),[scenario,setScenario]=useState<ScenarioSimulation|null>(null),[optimizer,setOptimizer]=useState<OptimizerResult|null>(null),[optimizerRunId,setOptimizerRunId]=useState(''),[promotedOperationId,setPromotedOperationId]=useState(''),[status,setStatus]=useState<any>({}),[loading,setLoading]=useState(''),[error,setError]=useState(''),[scenarioName,setScenarioName]=useState(''),[levers,setLevers]=useState<ScenarioLevers>(defaultLevers),[weights,setWeights]=useState<Record<string,number>>(defaultWeights),[limits,setLimits]=useState<Record<string,number>>(defaultConstraints);
 const money=(n:number)=>new Intl.NumberFormat(en?'en-US':'hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(n||0));
 const refreshStatus=useCallback(async()=>{const r=await Promise.allSettled([getP23Status(),getP24Status(),getP25Status()]);setStatus({twin:r[0].status==='fulfilled'?r[0].value:null,scenario:r[1].status==='fulfilled'?r[1].value:null,optimizer:r[2].status==='fulfilled'?r[2].value:null});},[]);
 useEffect(()=>{void refreshStatus();},[refreshStatus]);
 useEffect(()=>{setTwin(null);setScenario(null);setOptimizer(null);setOptimizerRunId('');setPromotedOperationId('');},[locationId]);
 const guarded=async(key:string,fn:()=>Promise<void>)=>{setLoading(key);setError('');try{await fn();}catch(e:any){setError(e?.response?.data?.error||e?.message||t('A művelet nem hajtható végre.','Operation could not be completed.'));}finally{setLoading('')}};
 const loadTwin=()=>guarded('twin',async()=>{const r=await getDigitalTwin({locationId:locationId||undefined});setTwin(r.twin);setScenario(null);setOptimizer(null);await refreshStatus();});
 const saveTwin=()=>guarded('snapshot',async()=>{const r=await createDigitalTwinSnapshot({locationId:locationId||undefined});setTwin(r.twin);await refreshStatus();});
 const runScenario=()=>guarded('scenario',async()=>{if(!twin)throw new Error(t('Előbb frissítsd a digitális ikert.','Refresh the digital twin first.'));const r=await simulateBusinessScenario({locationId:locationId||undefined,scenario_name:scenarioName||undefined,levers});setScenario(r.simulation);await refreshStatus();});
 const runOptimizer=()=>guarded('optimizer',async()=>{if(!twin)throw new Error(t('Előbb frissítsd a digitális ikert.','Refresh the digital twin first.'));const normalized=Object.fromEntries(Object.entries(weights).map(([k,v])=>[k,Number(v)/100]));const r=await optimizeBusiness({locationId:locationId||undefined,objective_weights:normalized,constraints:limits});setOptimizer(r.optimizer);setOptimizerRunId(String(r.item?.id||''));setPromotedOperationId('');await refreshStatus();});
 const promote=()=>guarded('promote',async()=>{if(!optimizerRunId)return;const r=await promoteOptimization(optimizerRunId);setPromotedOperationId(String(r.promoted_operation_id||''));await refreshStatus();});
 const coverage=useMemo(()=>twin?Object.entries(twin.coverage||{}):[],[twin]);
 const setLever=(key:keyof ScenarioLevers,value:number)=>setLevers(v=>({...v,[key]:value}));const setWeight=(key:string,value:number)=>setWeights(v=>({...v,[key]:value}));const setLimit=(key:string,value:number)=>setLimits(v=>({...v,[key]:value}));
 return <>
  <section className="vir-panel vir-stage-panel"><div className="vir-stage-heading"><div><span className="vir-chip success">{t('1. Modell','1. Model')}</span><h2>{t('Digitális üzleti iker','Business digital twin')}</h2><p className="vir-panel-subtitle">{t('Valós VIR adatokból friss virtuális állapotot készít: kereslet, előrejelzés, személyzet, kapacitás, profit, készlet és no-show kockázat.','Builds a live virtual state from VIR data: demand, forecast, staffing, capacity, profitability, inventory and no-show risk.')}</p></div><strong className="vir-health-value">{twin?`${Math.round(twin.completeness*100)}%`:t('nincs frissítve','not refreshed')}</strong></div>
   <div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('Mentett ikerállapotok','Saved twin snapshots')}</span><strong>{status.twin?.counts?.snapshots??0}</strong></div><div className="vir-stat-card"><span>{t('Automatikus éles módosítás','Automatic production mutation')}</span><strong>{t('TILTVA','BLOCKED')}</strong></div><div className="vir-stat-card"><span>{t('Modellfrissesség','Model freshness')}</span><strong>{twin?new Date(twin.generated_at).toLocaleTimeString(en?'en-GB':'hu-HU',{hour:'2-digit',minute:'2-digit'}):'—'}</strong></div></div>
   <div className="vir-toolbar"><button className="vir-btn" disabled={!!loading} onClick={()=>void loadTwin()}>{loading==='twin'?t('Frissítés…','Refreshing…'):t('Digitális iker frissítése','Refresh digital twin')}</button><button className="vir-btn secondary" disabled={!!loading||!twin} onClick={()=>void saveTwin()}>{t('Állapot mentése','Save snapshot')}</button></div>
   {twin&&<><div className="vir-workspace-grid"><div className="vir-stat-card"><span>{t('30 napos bevételi forecast','30-day revenue forecast')}</span><strong>{money(twin.demand.forecast_30d.revenue)}</strong></div><div className="vir-stat-card"><span>{t('Aktív munkatárs','Active staff')}</span><strong>{twin.capacity.active_staff}</strong></div><div className="vir-stat-card"><span>{t('Szabad kapacitás · 14 nap','Open capacity · 14 days')}</span><strong>{Math.round(twin.capacity.open_minutes_14d/60)} h</strong></div><div className="vir-stat-card"><span>{t('Közvetlen fedezet','Direct margin')}</span><strong>{twin.financial.margin_percent.toFixed(1)}%</strong></div><div className="vir-stat-card"><span>{t('Magas no-show kockázat','High no-show risk')}</span><strong>{twin.customer_risk.high_no_show_risk_14d}</strong></div><div className="vir-stat-card"><span>{t('Alacsony / kifogyott készlet','Low / out-of-stock')}</span><strong>{twin.inventory.low_stock+twin.inventory.out_of_stock}</strong></div></div><div className="vir-coverage-row">{coverage.map(([k,v])=><span key={k} className={`vir-chip ${v?'success':'warning'}`}>{k}: {v?'OK':'N/A'}</span>)}</div></>}
  </section>

  <section className="vir-panel vir-stage-panel"><div className="vir-stage-heading"><div><span className="vir-chip">{t('2. Szimuláció','2. Simulation')}</span><h2>{t('Mi történik, ha?','What-if scenario')}</h2><p className="vir-panel-subtitle">{t('A csúszkák csak a digitális ikert módosítják. Egyetlen foglalást, árat, műszakot vagy készletet sem írnak át.','The controls modify only the digital twin. They never change a live booking, price, schedule or stock balance.')}</p></div><strong className="vir-health-value">{status.scenario?.counts?.runs??0} {t('futtatás','runs')}</strong></div>
   <div className="vir-form-row"><label className="vir-field"><span>{t('Szcenárió neve','Scenario name')}</span><input value={scenarioName} onChange={e=>setScenarioName(e.target.value)} placeholder={t('pl. őszi kapacitásnövelés','e.g. autumn capacity lift')}/></label>{([
    ['price_delta_percent',t('Árváltozás %','Price change %'),-15,20],['staff_hours_delta_percent',t('Munkaóra változás %','Staff hours change %'),-20,25],['promotion_discount_percent',t('Promóciós kedvezmény %','Promotion discount %'),0,25],['no_show_reduction_percent',t('No-show csökkentési cél %','No-show reduction target %'),0,50],['stock_availability_delta_percent',t('Készletelérhetőség változás %','Stock availability change %'),-20,20],['demand_delta_percent',t('Keresleti sokk %','Demand shock %'),-20,30],] as Array<[keyof ScenarioLevers,string,number,number]>).map(([k,label,min,max])=><label className="vir-field" key={k}><span>{label}: <strong>{levers[k]}%</strong></span><input type="range" min={min} max={max} step={1} value={levers[k]} onChange={e=>setLever(k,Number(e.target.value))}/></label>)}</div>
   <div className="vir-toolbar"><button className="vir-btn" disabled={!!loading||!twin} onClick={()=>void runScenario()}>{loading==='scenario'?t('Szimuláció…','Simulating…'):t('Szcenárió futtatása','Run scenario')}</button>{!twin&&<span className="vir-help-inline">{t('Előfeltétel: friss digitális iker.','Prerequisite: fresh digital twin.')}</span>}</div>
   {scenario&&<div className="vir-compare-grid"><div className="vir-result-card"><h4>{t('Alapállapot','Baseline')}</h4><p>{money(Number(scenario.baseline.revenue||0))} · {Number(scenario.baseline.bookings||0)} {t('foglalás','bookings')}</p><small>{t('Margin','Margin')}: {Number(scenario.baseline.margin_percent||0).toFixed(1)}%</small></div><div className="vir-result-card"><h4>{t('Szimulált eredmény','Simulated outcome')}</h4><p>{money(Number(scenario.result.revenue||0))} · {Number(scenario.result.bookings||0)} {t('foglalás','bookings')}</p><small>{t('Profit változás','Profit delta')}: {money(Number(scenario.delta.profit||0))} · {t('bizalom','confidence')} {Math.round(scenario.confidence*100)}%</small></div></div>}
  </section>

  <section className="vir-panel vir-stage-panel"><div className="vir-stage-heading"><div><span className="vir-chip">{t('3. Optimalizáció','3. Optimization')}</span><h2>{t('Többcélú üzleti optimalizáció','Multi-objective business optimization')}</h2><p className="vir-panel-subtitle">{t('Korlátozott jelölteket hasonlít össze bevétel, profit, kihasználtság, megtartás, dolgozói terhelés és készletbiztonság alapján.','Compares bounded candidates across revenue, profit, utilization, retention, staff load and inventory resilience.')}</p></div><strong className="vir-health-value">{status.optimizer?.counts?.recommended??0} {t('nyitott ajánlás','open recommendations')}</strong></div>
   <div className="vir-form-row">{Object.entries({revenue:t('Bevétel','Revenue'),profit:t('Profit','Profit'),utilization:t('Kihasználtság','Utilization'),retention:t('Vendégmegtartás','Retention'),staff_balance:t('Dolgozói egyensúly','Staff balance'),stock_resilience:t('Készletbiztonság','Stock resilience')}).map(([k,label])=><label className="vir-field" key={k}><span>{label}: <strong>{weights[k]}%</strong></span><input type="range" min={0} max={60} step={1} value={weights[k]} onChange={e=>setWeight(k,Number(e.target.value))}/></label>)}</div>
   <details className="vir-json-details"><summary>{t('Optimalizációs korlátok','Optimization constraints')}</summary><div className="vir-form-row">{Object.entries({max_price_change_percent:t('Max. árváltozás %','Max price change %'),max_discount_percent:t('Max. kedvezmény %','Max discount %'),max_staff_change_percent:t('Max. munkaóra változás %','Max staff-hours change %'),min_margin_percent:t('Minimum margin %','Minimum margin %')}).map(([k,label])=><label className="vir-field" key={k}><span>{label}</span><input type="number" value={limits[k]} onChange={e=>setLimit(k,Number(e.target.value))}/></label>)}</div></details>
   <div className="vir-toolbar"><button className="vir-btn" disabled={!!loading||!twin} onClick={()=>void runOptimizer()}>{loading==='optimizer'?t('Optimalizálás…','Optimizing…'):t('Legjobb kombináció keresése','Find best combination')}</button></div>
   {optimizer&&<><article className="vir-result-card vir-champion-card"><span className="vir-chip success">{t('Ajánlott kombináció','Recommended combination')} · {optimizer.champion.score.toFixed(1)}/100</span><h4>{t('Várható eredmény','Expected outcome')}</h4><p>{money(Number(optimizer.champion.result.revenue||0))} · {t('profit','profit')} {money(Number(optimizer.champion.result.profit||0))} · {t('margin','margin')} {Number(optimizer.champion.result.margin_percent||0).toFixed(1)}%</p><div className="vir-coverage-row">{Object.entries(optimizer.champion.levers).filter(([,v])=>Number(v)!==0).map(([k,v])=><span className="vir-chip" key={k}>{k}: {Number(v)>0?'+':''}{v}%</span>)}</div><div className="vir-toolbar"><button className="vir-btn success" disabled={!!loading||!!promotedOperationId} onClick={()=>void promote()}>{promotedOperationId?t('Jóváhagyásra elküldve','Sent for approval'):t('Jóváhagyási központba küldés','Send to approval center')}</button><Link className="vir-btn secondary" to="/admin/vir/p17">{t('Jóváhagyási központ megnyitása','Open approval center')}</Link></div>{promotedOperationId&&<div className="vir-help">{t('Kontrollált művelet azonosító','Governed operation ID')}: {promotedOperationId}</div>}</article>{optimizer.alternatives.length>0&&<details className="vir-json-details"><summary>{t('Alternatív megoldások','Alternative solutions')}</summary><div className="vir-result-list">{optimizer.alternatives.map((a,i)=><article className="vir-result-card" key={i}><strong>#{i+2} · {a.score.toFixed(1)}/100</strong><p>{money(Number(a.result.revenue||0))} · {t('profit','profit')} {money(Number(a.result.profit||0))}</p></article>)}</div></details>}</>}
   <div className="vir-help"><strong>{t('Végrehajtási korlát:','Execution boundary:')}</strong> {t('az optimalizáló csak ajánlást készít. A kiválasztott kombináció P17 jóváhagyásra kerül, önálló éles végrehajtás nincs.','the optimizer only creates a recommendation. The selected combination is sent to P17 approval; there is no autonomous production execution.')}</div>
  </section>
  {error&&<div className="vir-error-friendly">{error}</div>}
 </>;
}