import React,{useCallback,useEffect,useState}from"react";
import{getLocations,type LocationRow}from"../api/locations";
import{getVirRevenueLeakage}from"../api/virRevenueLeakage";
import"./VirManagement.css";
const money=(v:unknown)=>new Intl.NumberFormat('hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(Number(v||0));
const labels:Record<string,string>={COMPLETED_UNPAID:'Lezárt, de nincs teljesen kifizetve',ZERO_VALUE_COMPLETED:'Nulla értékű lezárt munkalap',HEADER_ITEM_MISMATCH:'Munkalapfej és tételek eltérése',COMPLETED_WITHOUT_ITEMS:'Lezárt munkalap tételek nélkül',APPOINTMENT_WITHOUT_WORKORDER:'Teljesített időpont munkalap nélkül'};
export default function VirRevenueLeakagePage(){
 const[locations,setLocations]=useState<LocationRow[]>([]),[locationId,setLocationId]=useState(''),[days,setDays]=useState(30),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{getLocations().then(setLocations).catch(()=>setLocations([]));},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await getVirRevenueLeakage({locationId:locationId||undefined,days}));}catch(e:any){setError(e?.response?.data?.error||e?.message||'A revenue leakage elemzés nem tölthető be.');}finally{setLoading(false);}},[locationId,days]);
 useEffect(()=>{void load();},[load]);
 return <div className="vir-management-page"><div className="vir-management-header"><div><h1 className="vir-management-title">Revenue Leakage Detector</h1><div className="vir-management-subtitle">Bizonyíték-alapú bevételkiesés és adminisztrációs eltérések. A modul csak jelez, nem módosít adatot.</div></div><div className="vir-management-actions"><label className="vir-field"><span>Telephely</span><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes telephely</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="vir-field"><span>Időszak</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 nap</option><option value={30}>30 nap</option><option value={90}>90 nap</option></select></label></div></div>
 {error&&<div className="vir-error">{error}</div>}{loading&&<div className="vir-spinner">Bevételkiesések ellenőrzése…</div>}
 {!loading&&data?.summary&&<><div className="vir-kpi-grid"><div className="vir-kpi is-critical"><div className="vir-kpi-label">Becsült kitettség</div><div className="vir-kpi-value">{money(data.summary.estimated_loss)}</div></div><div className="vir-kpi"><div className="vir-kpi-label">Találatok</div><div className="vir-kpi-value">{data.summary.findings}</div></div><div className="vir-kpi is-critical"><div className="vir-kpi-label">Kritikus</div><div className="vir-kpi-value">{data.summary.critical}</div></div><div className="vir-kpi is-warning"><div className="vir-kpi-label">Magas</div><div className="vir-kpi-value">{data.summary.high}</div></div></div><section className="vir-panel"><div className="vir-panel-title">20. Revenue Leakage Detector</div><div className="vir-panel-muted">A becsült veszteség döntéstámogató érték; minden találathoz forrásadat tartozik.</div>{data.items?.length===0?<div className="vir-empty">A kiválasztott időszakban nincs észlelt bevételi eltérés.</div>:data.items?.map((x:any)=><article className={`vir-action-card is-${x.severity==='CRITICAL'?'critical':'high'}`} key={`${x.leakage_type}-${x.entity_id}`}><div className="vir-action-card-head"><div><div className="vir-action-title">{labels[x.leakage_type]||x.leakage_type}</div><div className="vir-action-description">{x.location_name} · {x.title}</div></div><strong>{money(x.estimated_loss)}</strong></div><div className="vir-badge-row"><span className="vir-badge">{x.severity}</span><span className="vir-badge">{x.entity_type}</span><span className="vir-badge">{new Date(x.event_time).toLocaleString('hu-HU')}</span></div><pre style={{whiteSpace:'pre-wrap',fontSize:12,opacity:.75}}>{JSON.stringify(x.details,null,2)}</pre></article>)}</section></>}
 </div>;
}
