import React,{useCallback,useEffect,useState}from"react";
import axios from"axios";
import{CheckCircle2,CloudCog,KeyRound,Mail,RefreshCw,Save,ServerCog,ShieldCheck}from"lucide-react";
import"./VirRuntimeSettingsPanel.css";

type Props={API_BASE:string;auth:()=>any};
type FormState=Record<string,string>;
const defaults:FormState={
 COMPLAINT_EMAIL:'vendegpanasz@kleoszalon.hu',COMPLAINT_IMAP_HOST:'',COMPLAINT_IMAP_PORT:'993',COMPLAINT_IMAP_USER:'',COMPLAINT_IMAP_PASS:'',COMPLAINT_IMAP_MAILBOX:'INBOX',COMPLAINT_IMAP_SENT_MAILBOX:'Sent',COMPLAINT_IMAP_POLL_SECONDS:'120',COMPLAINT_IMAP_MAX_PER_RUN:'25',COMPLAINT_SLA_DAYS:'5',
 IMAP_HOST:'',IMAP_PORT:'993',IMAP_USER:'',IMAP_PASS:'',IMAP_SENT_MAILBOX:'Sent',IMAP_SENT_SYNC:'1',IMAP_TLS_REJECT_UNAUTHORIZED:'1',
 VIR_GITHUB_TOKEN:'',VIR_GITHUB_OWNER:'kleopatraszalon',VIR_GITHUB_REPOS:'kleoszalon-api,kleoszalon-frontend',VIR_GITHUB_ENVIRONMENT:'production-manual-approval',VIR_GITHUB_REVIEWER:'kleopatraszalon',VIR_GITHUB_PREVENT_SELF_REVIEW:'0',
 VIR_RENDER_API_KEY:'',VIR_RENDER_SERVICE_ID:'',VIR_RENDER_POSTGRES_ID:'',VIR_RENDER_TARGET_INSTANCES:'2',VIR_RENDER_ENABLE_DB_HA:'1'
};
const secretKeys=['COMPLAINT_IMAP_PASS','IMAP_PASS','VIR_GITHUB_TOKEN','VIR_RENDER_API_KEY'];

export default function VirRuntimeSettingsPanel({API_BASE,auth}:Props){
 const[form,setForm]=useState<FormState>(defaults),[snapshot,setSnapshot]=useState<any>({}),[render,setRender]=useState<any>(null),[mailbox,setMailbox]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const base=`${API_BASE}/signage/runtime-settings`;
 const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await axios.get(base,auth());const s=r.data?.settings||{};const next={...defaults};Object.keys(next).forEach(k=>{if(!s[k]?.secret&&s[k]?.value!==undefined&&s[k]?.value!==null&&String(s[k].value)!=='')next[k]=String(s[k].value)});setForm(next);setSnapshot(s);setRender(r.data?.render||null);setMailbox(r.data?.mailbox||null)}catch(e:any){setError(e?.response?.status===403?'A rendszerkonfiguráció csak adminisztrátori jogosultsággal módosítható.':e?.response?.data?.message||e?.response?.data?.error||e?.message||'Konfigurációs hiba.')}finally{setBusy(false)}},[auth,base]);
 useEffect(()=>{void load()},[load]);
 const set=(key:string,value:any)=>setForm(p=>({...p,[key]:String(value)}));
 async function save(silent=false){setBusy(true);setError('');if(!silent)setMessage('');try{const payload:any={...form};secretKeys.forEach(k=>{if(!payload[k])delete payload[k]});const r=await axios.put(base,{settings:payload},auth());setSnapshot(r.data?.settings||snapshot);setRender(r.data?.render||render);setMailbox(r.data?.mailbox||mailbox);setForm(p=>({...p,COMPLAINT_IMAP_PASS:'',IMAP_PASS:'',VIR_GITHUB_TOKEN:'',VIR_RENDER_API_KEY:''}));if(!silent)setMessage('A VIR rendszerkonfiguráció mentve. A titkos adatok titkosítva kerültek az adatbázisba.');return true}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||'Mentési hiba.');return false}finally{setBusy(false)}}
 async function applyGithub(){if(!await save(true))return;setBusy(true);setError('');setMessage('');try{const r=await axios.post(`${base}/github/apply`,{},auth());setMessage(`GitHub release-gate kész: ${r.data?.environment||form.VIR_GITHUB_ENVIRONMENT}; reviewer: ${r.data?.reviewer||form.VIR_GITHUB_REVIEWER}.`)}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||'GitHub beállítási hiba.')}finally{setBusy(false)}}
 async function verifyRender(){if(!await save(true))return;setBusy(true);setError('');try{const r=await axios.post(`${base}/render/verify`,{},auth());setRender(r.data);setMessage(r.data?.ready_for_single_instance_failure?'A Render HA ellenőrzés PASS.':'A Render kapcsolat működik, de a teljes failover még nem igazolt.')}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||'Render ellenőrzési hiba.')}finally{setBusy(false)}}
 async function applyRender(){if(!await save(true))return;setBusy(true);setError('');setMessage('');try{const r=await axios.post(`${base}/render/apply`,{},auth());setRender(r.data?.status||null);setMessage(r.data?.status?.ready_for_single_instance_failure?'Render HA alkalmazva és ellenőrizve: PASS.':'A Render módosítás elküldve. Az infrastruktúra még átállhat; ellenőrizze újra a státuszt.')}catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||'Render HA alkalmazási hiba.')}finally{setBusy(false)}}
 const configured=(k:string)=>!!snapshot?.[k]?.configured;
 return <section className="vrs-panel">
  <div className="vrs-head"><div><h2>Rendszerkonfiguráció</h2><p>IMAP, Outlook Sent, GitHub production approval és Render magas rendelkezésre állás közvetlenül a VIR-ből. A jelszavak és API-tokenek nem olvashatók vissza.</p></div><button className="vrs-button" onClick={load} disabled={busy}><RefreshCw size={15}/>Státusz frissítése</button></div>
  {error&&<div className="vrs-error">{error}</div>}{message&&<div className="vrs-ok"><CheckCircle2 size={17}/>{message}</div>}
  <div className="vrs-status"><Status label="Panasz IMAP" ok={!!mailbox?.enabled} text={mailbox?.enabled?`${mailbox.host} / ${mailbox.user}`:'nincs beállítva'}/><Status label="Render instance" ok={(render?.instance_count||0)>=2} text={render?.instance_count==null?'nincs élő adat':`${render.instance_count} / cél ${render.target_instances||form.VIR_RENDER_TARGET_INSTANCES}`}/><Status label="PostgreSQL HA" ok={render?.database_ha_enabled===true} text={render?.database_ha_enabled===true?'bekapcsolva':render?.database_ha_enabled===false?'kikapcsolva':'nincs igazolva'}/><Status label="Teljes failover" ok={!!render?.ready_for_single_instance_failure} text={render?.ready_for_single_instance_failure?'PASS':'teendő'}/></div>

  <div className="vrs-grid">
   <Card icon={Mail} title="Vendégpanasz postaláda" note="A dedikált vendegpanasz@kleoszalon.hu Inbox beolvasása.">
    <Field label="Panasz e-mail cím"><input value={form.COMPLAINT_EMAIL} onChange={e=>set('COMPLAINT_EMAIL',e.target.value)}/></Field><Field label="IMAP host"><input value={form.COMPLAINT_IMAP_HOST} onChange={e=>set('COMPLAINT_IMAP_HOST',e.target.value)} placeholder="imap.szerver.hu"/></Field><Field label="Port"><input type="number" value={form.COMPLAINT_IMAP_PORT} onChange={e=>set('COMPLAINT_IMAP_PORT',e.target.value)}/></Field><Field label="Felhasználó"><input value={form.COMPLAINT_IMAP_USER} onChange={e=>set('COMPLAINT_IMAP_USER',e.target.value)}/></Field><Secret label="Jelszó" configured={configured('COMPLAINT_IMAP_PASS')} value={form.COMPLAINT_IMAP_PASS} onChange={v=>set('COMPLAINT_IMAP_PASS',v)}/><Field label="Inbox mappa"><input value={form.COMPLAINT_IMAP_MAILBOX} onChange={e=>set('COMPLAINT_IMAP_MAILBOX',e.target.value)}/></Field><Field label="Lekérdezés / mp"><input type="number" min="60" value={form.COMPLAINT_IMAP_POLL_SECONDS} onChange={e=>set('COMPLAINT_IMAP_POLL_SECONDS',e.target.value)}/></Field><Field label="Panasz SLA / nap"><input type="number" min="1" value={form.COMPLAINT_SLA_DAYS} onChange={e=>set('COMPLAINT_SLA_DAYS',e.target.value)}/></Field>
   </Card>

   <Card icon={Mail} title="Outlook / IMAP Sent" note="A VIR-ből kiküldött e-mailek az Outlook Sent mappában is megjelennek.">
    <Field label="IMAP host"><input value={form.IMAP_HOST} onChange={e=>set('IMAP_HOST',e.target.value)} placeholder="outlook.office365.com"/></Field><Field label="Port"><input type="number" value={form.IMAP_PORT} onChange={e=>set('IMAP_PORT',e.target.value)}/></Field><Field label="Felhasználó"><input value={form.IMAP_USER} onChange={e=>set('IMAP_USER',e.target.value)}/></Field><Secret label="Jelszó / app password" configured={configured('IMAP_PASS')} value={form.IMAP_PASS} onChange={v=>set('IMAP_PASS',v)}/><Field label="Sent mappa"><input value={form.IMAP_SENT_MAILBOX} onChange={e=>set('IMAP_SENT_MAILBOX',e.target.value)} placeholder="Sent Items"/></Field><Toggle label="Sent szinkron engedélyezve" checked={form.IMAP_SENT_SYNC!=='0'} onChange={v=>set('IMAP_SENT_SYNC',v?'1':'0')}/>
   </Card>

   <Card icon={ShieldCheck} title="GitHub production-manual-approval" note="Az API és frontend repository production environment required reviewer szabálya.">
    <Secret label="GitHub admin token" configured={configured('VIR_GITHUB_TOKEN')} value={form.VIR_GITHUB_TOKEN} onChange={v=>set('VIR_GITHUB_TOKEN',v)}/><Field label="Tulajdonos"><input value={form.VIR_GITHUB_OWNER} onChange={e=>set('VIR_GITHUB_OWNER',e.target.value)}/></Field><Field label="Repository-k, vesszővel"><input value={form.VIR_GITHUB_REPOS} onChange={e=>set('VIR_GITHUB_REPOS',e.target.value)}/></Field><Field label="Environment"><input value={form.VIR_GITHUB_ENVIRONMENT} onChange={e=>set('VIR_GITHUB_ENVIRONMENT',e.target.value)}/></Field><Field label="Required reviewer"><input value={form.VIR_GITHUB_REVIEWER} onChange={e=>set('VIR_GITHUB_REVIEWER',e.target.value)}/></Field><Toggle label="Saját deployment önjóváhagyása tiltott" checked={form.VIR_GITHUB_PREVENT_SELF_REVIEW==='1'} onChange={v=>set('VIR_GITHUB_PREVENT_SELF_REVIEW',v?'1':'0')}/><button className="vrs-button primary" type="button" onClick={applyGithub} disabled={busy}><ShieldCheck size={15}/>GitHub release-gate alkalmazása</button>
   </Card>

   <Card icon={ServerCog} title="Render HA" note="A VIR API legalább két példányra skálázása és a Render PostgreSQL High Availability bekapcsolása.">
    <Secret label="Render API key" configured={configured('VIR_RENDER_API_KEY')} value={form.VIR_RENDER_API_KEY} onChange={v=>set('VIR_RENDER_API_KEY',v)}/><Field label="API service ID"><input value={form.VIR_RENDER_SERVICE_ID} onChange={e=>set('VIR_RENDER_SERVICE_ID',e.target.value)} placeholder="srv-..."/></Field><Field label="Postgres ID"><input value={form.VIR_RENDER_POSTGRES_ID} onChange={e=>set('VIR_RENDER_POSTGRES_ID',e.target.value)} placeholder="dpg-..."/></Field><Field label="API példányszám"><input type="number" min="2" max="20" value={form.VIR_RENDER_TARGET_INSTANCES} onChange={e=>set('VIR_RENDER_TARGET_INSTANCES',e.target.value)}/></Field><Toggle label="PostgreSQL High Availability bekapcsolása" checked={form.VIR_RENDER_ENABLE_DB_HA!=='0'} onChange={v=>set('VIR_RENDER_ENABLE_DB_HA',v?'1':'0')}/><div className="vrs-actions"><button className="vrs-button" type="button" onClick={verifyRender} disabled={busy}><CloudCog size={15}/>Render ellenőrzése</button><button className="vrs-button danger" type="button" onClick={applyRender} disabled={busy}><ServerCog size={15}/>2+ instance + DB HA alkalmazása</button></div>
   </Card>
  </div>
  <div className="vrs-footer"><div><KeyRound size={16}/><span>A titkok AES-256-GCM titkosítással PostgreSQL-ben vannak; a böngésző csak „beállítva / nincs beállítva” állapotot kap.</span></div><button className="vrs-button primary" onClick={()=>save(false)} disabled={busy}><Save size={15}/>{busy?'Mentés…':'Konfiguráció mentése'}</button></div>
 </section>
}
function Card({icon:I,title,note,children}:{icon:any,title:string,note:string,children:React.ReactNode}){return <article className="vrs-card"><header><I size={20}/><div><h3>{title}</h3><p>{note}</p></div></header><div className="vrs-fields">{children}</div></article>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="vrs-field"><span>{label}</span>{children}</label>}
function Secret({label,configured,value,onChange}:{label:string,configured:boolean,value:string,onChange:(v:string)=>void}){return <label className="vrs-field"><span>{label} {configured&&<em>• beállítva</em>}</span><input type="password" autoComplete="new-password" value={value} onChange={e=>onChange(e.target.value)} placeholder={configured?'••••••••  (üresen hagyva változatlan)':'adja meg a titkos értéket'}/></label>}
function Toggle({label,checked,onChange}:{label:string,checked:boolean,onChange:(v:boolean)=>void}){return <label className="vrs-toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function Status({label,ok,text}:{label:string,ok:boolean,text:string}){return <div className={`vrs-state ${ok?'ok':'warn'}`}><span>{ok?<CheckCircle2 size={16}/>:<CloudCog size={16}/>}</span><div><b>{label}</b><small>{text}</small></div></div>}
