import React,{useEffect,useMemo,useRef,useState}from"react";
import axios from"axios";
import{Archive,CheckCircle2,CloudCog,Download,FileSpreadsheet,FileText,Mail,MonitorPlay,RefreshCw,Save,ShieldCheck,Star,Upload,Users}from"lucide-react";
import"./VirSpecParityPage.css";
import VirRuntimeSettingsPanel from"./VirRuntimeSettingsPanel";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const auth=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
const parity=(path:string)=>`${API_BASE}/vir/spec-parity${path}`;
const tabs=[['complaints','Panasz + IMAP',Mail],['wallboard','WallBoard',MonitorPlay],['reports','Jelentésszerkesztő',FileSpreadsheet],['evaluation','2018 értékelés',Users],['reviews','Facebook moderáció',Star],['documents','Dokumentumszerkesztő',FileText],['configuration','Rendszerkonfiguráció',CloudCog],['quality','HA + release gate',ShieldCheck]] as const;
const fmt=(v:any)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const humanBytes=(v:any)=>{const n=Number(v||0);return n<1024?`${n} B`:n<1024*1024?`${(n/1024).toFixed(1)} kB`:`${(n/1024/1024).toFixed(1)} MB`};

export default function VirSpecParityPage(){
 const[tab,setTab]=useState<string>('complaints'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const[overview,setOverview]=useState<any>(null),[complaints,setComplaints]=useState<any[]>([]),[reportData,setReportData]=useState<any>({definitions:[],sources:[]}),[legacy,setLegacy]=useState<any>({monthly_summary:[],guest_summary:[],detail:[]}),[reviews,setReviews]=useState<any[]>([]),[documents,setDocuments]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]);
 const[year,setYear]=useState(new Date().getFullYear()),[point,setPoint]=useState<any>({employee_id:'',point_type:'black',point_count:1,reason:'',evaluation_month:new Date().toISOString().slice(0,7)});
 const[reportForm,setReportForm]=useState<any>({name:'',description:'',source_key:'complaints',columns:'title,status,due_at,created_at',default_format:'xlsx'});
 const[releaseForm,setReleaseForm]=useState<any>({release_ref:'',tester_name:'',result:'pass',notes:''});
 const[docId,setDocId]=useState(''),[docTitle,setDocTitle]=useState(''),[docStatus,setDocStatus]=useState('draft'),[docVersion,setDocVersion]=useState(0);const editorRef=useRef<HTMLDivElement>(null);
 const wallboardBase=`${API_BASE}/signage/wallboard`;
 const pendingReviews=useMemo(()=>reviews.filter(x=>x.moderation_status==='pending'),[reviews]);
 async function loadAll(silent=false){if(!silent)setLoading(true);setError('');try{
   const cfg=auth();const [o,c,r,l,rv,d]=await Promise.all([
    axios.get(parity('/overview'),cfg),axios.get(parity('/complaints'),cfg),axios.get(parity('/reports'),cfg),axios.get(parity(`/legacy-evaluations?year=${year}`),cfg),axios.get(parity('/review-moderation'),cfg),axios.get(parity('/documents'),cfg)
   ]);setOverview(o.data);setComplaints(c.data||[]);setReportData(r.data||{definitions:[],sources:[]});setLegacy(l.data||{});setReviews(rv.data||[]);setDocuments(d.data||[]);
   try{const e=await axios.get(`${API_BASE}/employees`,cfg);const rows=Array.isArray(e.data)?e.data:Array.isArray(e.data?.employees)?e.data.employees:[];setEmployees(rows)}catch{}
 }catch(e:any){setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||'Betöltési hiba.')}finally{setLoading(false)}}
 useEffect(()=>{void loadAll()},[year]);
 async function syncMailbox(){setLoading(true);setError('');try{await axios.post(parity('/complaints/sync'),{},auth());await loadAll(true)}catch(e:any){setError(e?.response?.data?.message||e?.message)}finally{setLoading(false)}}
 async function uploadComplaintFiles(id:string,files:FileList|null){if(!files?.length)return;const fd=new FormData();Array.from(files).forEach(f=>fd.append('files',f));setLoading(true);try{const cfg:any=auth();cfg.headers={...(cfg.headers||{}),'Content-Type':'multipart/form-data'};await axios.post(parity(`/complaints/${id}/attachments`),fd,cfg);await loadAll(true)}catch(e:any){setError(e?.response?.data?.message||e?.message)}finally{setLoading(false)}}
 async function downloadAttachment(a:any){const r=await axios.get(parity(`/complaint-attachments/${a.id}`),{...auth(),responseType:'blob'});downloadBlob(r.data,a.filename||'csatolmany')}
 function downloadBlob(blob:any,name:string){const url=URL.createObjectURL(blob instanceof Blob?blob:new Blob([blob]));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function exportReport(def:any,format:'pdf'|'xlsx'){try{const r=await axios.get(parity(`/reports/${def.id}/export?format=${format}`),{...auth(),responseType:'blob'});downloadBlob(r.data,`${String(def.name||'riport').replace(/[^a-z0-9áéíóöőúüű -]/gi,'_')}.${format}`)}catch(e:any){setError(e?.response?.data?.message||e?.message)}}
 async function createReport(e:React.FormEvent){e.preventDefault();try{await axios.post(parity('/reports'),{...reportForm,columns:String(reportForm.columns||'').split(',').map((x:string)=>x.trim()).filter(Boolean),filters:{}},auth());setReportForm({...reportForm,name:'',description:''});await loadAll(true)}catch(err:any){setError(err?.response?.data?.message||err?.message)}}
 async function addPoint(e:React.FormEvent){e.preventDefault();try{await axios.post(parity('/legacy-evaluations/points'),point,auth());setPoint({...point,reason:''});await loadAll(true)}catch(err:any){setError(err?.response?.data?.message||err?.message)}}
 async function moderate(id:string,action:'approve'|'reject',publishNow=false){try{await axios.post(parity(`/review-moderation/${id}/${action}`),action==='approve'?{publish_now:publishNow}:{},auth());await loadAll(true)}catch(err:any){setError(err?.response?.data?.message||err?.message)}}
 async function openDocument(id:string){try{const r=await axios.get(parity(`/documents/${id}`),auth());const d=r.data;setDocId(d.id);setDocTitle(d.title||'');setDocStatus(d.status||'draft');setDocVersion(Number(d.version||0));setTimeout(()=>{if(editorRef.current)editorRef.current.innerHTML=d.content_html||''},0)}catch(e:any){setError(e?.response?.data?.message||e?.message)}}
 function newDocument(){setDocId('');setDocTitle('');setDocStatus('draft');setDocVersion(0);if(editorRef.current)editorRef.current.innerHTML='<h1>Új dokumentum</h1><p>Kezdje el a szerkesztést…</p>'}
 function exec(command:string,value?:string){document.execCommand(command,false,value);editorRef.current?.focus()}
 async function saveDocument(publish=false){const title=docTitle.trim();if(!title){setError('A dokumentum címe kötelező.');return}const body={title,content_html:editorRef.current?.innerHTML||'',status:publish?'published':docStatus};try{const r=docId?await axios.patch(parity(`/documents/${docId}`),body,auth()):await axios.post(parity('/documents'),body,auth());setDocId(r.data.id);setDocStatus(r.data.status);setDocVersion(r.data.version);await loadAll(true)}catch(e:any){setError(e?.response?.data?.message||e?.message)}}
 async function signRelease(e:React.FormEvent){e.preventDefault();const checklist={unit:true,integration:true,e2e:true,automated_smoke:true,manual_uat:true};try{await axios.post(parity('/release-gate/signoffs'),{...releaseForm,checklist,environment:'production'},auth());setReleaseForm({...releaseForm,release_ref:'',notes:''});await loadAll(true)}catch(err:any){setError(err?.response?.data?.message||err?.message)}}
 const employeeName=(id:string)=>{const e=employees.find((x:any)=>String(x.id)===String(id));return e?.full_name||e?.name||id};
 return <div className="vsp-page">
  <header className="vsp-hero"><div><div className="vsp-eyebrow">VIR • EREDETI SPECIFIKÁCIÓ KIEGÉSZÍTÉSEI</div><h1>Specifikáció-megfelelőségi központ</h1><p>Panasz mailbox, IMAP, WallBoard, régi riport/értékelés, review-moderáció, dokumentumszerkesztő, dolgozói app és release/HA kontroll egy helyen.</p></div><button className="vsp-button" onClick={()=>loadAll()} disabled={loading}><RefreshCw size={16}/>{loading?'Frissítés…':'Minden frissítése'}</button></header>
  {error&&<div className="vsp-error">{error}</div>}
  <section className="vsp-kpis"><Kpi icon={Mail} label="Nyitott panasz" value={overview?.complaints?.open??'—'} sub={`${overview?.complaints?.overdue??0} SLA-n túl`}/><Kpi icon={Star} label="Moderációra vár" value={overview?.reviews?.pending??'—'} sub="vendégértékelés"/><Kpi icon={FileText} label="Dokumentum" value={overview?.documents?.total??'—'} sub={`${overview?.documents?.published??0} publikált`}/><Kpi icon={CloudCog} label="HA állapot" value={overview?.ha?.ready_for_single_instance_failure?'Kész':'Teendő'} sub={`${overview?.ha?.instance_count??1} API példány`}/></section>
  <nav className="vsp-tabs">{tabs.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={16}/>{label}</button>)}</nav>

  {tab==='complaints'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>Panaszbeérkező e-mail automatizálása</h2><p><b>{overview?.mailbox?.complaintAddress||'vendegpanasz@kleoszalon.hu'}</b> → automatikus panaszrekord, SLA és DB-ben tárolt csatolmány.</p></div><button className="vsp-button" onClick={syncMailbox}><RefreshCw size={15}/>IMAP szinkron most</button></div>
   <div className="vsp-status-grid"><Status label="IMAP" ok={overview?.mailbox?.enabled} text={overview?.mailbox?.enabled?`${overview?.mailbox?.host} / ${overview?.mailbox?.inbox}`:'Nincs konfigurálva'}/><Status label="Utolsó sikeres beolvasás" ok={!!overview?.mailbox?.lastSuccessAt} text={fmt(overview?.mailbox?.lastSuccessAt)}/><Status label="IMAP Sent" ok={overview?.mailbox?.enabled} text={overview?.mailbox?.sent||'Sent'}/></div>
   <div className="vsp-list">{complaints.map(c=><article className="vsp-row" key={c.id}><div className="vsp-grow"><b>{c.title}</b><p>{c.description||'—'}</p><small>{fmt(c.created_at)} • SLA: {fmt(c.due_at)} • {c.metadata?.sender_email||c.metadata?.source||'kézi rögzítés'}</small><div className="vsp-attachments">{(c.attachments||[]).map((a:any)=><button key={a.id} onClick={()=>downloadAttachment(a)}><Download size={13}/>{a.filename} ({humanBytes(a.byte_size)})</button>)}</div></div><span className={`vsp-badge ${c.status}`}>{c.status}</span><label className="vsp-upload"><Upload size={14}/>Fájl<input type="file" multiple hidden onChange={e=>uploadComplaintFiles(c.id,e.target.files)}/></label></article>)}</div>
  </section>}

  {tab==='wallboard'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>WallBoard / TV napi akció adapter</h2><p>Ugyanaz az aktív napi akció kerül a vendégappba és a TV feedbe. Három kompatibilis kimenet áll rendelkezésre.</p></div></div><div className="vsp-link-cards"><a href={`${wallboardBase}/daily-action.json`} target="_blank" rel="noreferrer">JSON feed</a><a href={`${wallboardBase}/daily-action.xml`} target="_blank" rel="noreferrer">XML feed</a><a href={wallboardBase} target="_blank" rel="noreferrer">iframe / teljes képernyő</a></div><div className="vsp-tv"><iframe src={wallboardBase} title="Kleopátra WallBoard preview"/></div><p className="vsp-note">WallBoard URL: <code>{wallboardBase}</code> • automatikus frissítés: 60 mp</p></section>}

  {tab==='reports'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>Konfigurálható jelentésszerkesztő</h2><p>Előre definiált és saját riportok, biztonságosan engedélyezett adatforrásokkal, PDF és Excel kimenettel.</p></div></div><div className="vsp-report-grid">{(reportData.definitions||[]).map((r:any)=><article className="vsp-report" key={r.id}><div><b>{r.name}</b><p>{r.description||r.source_key}</p><small>{r.source_key} • {(r.columns||[]).join(', ')}</small></div><div><button onClick={()=>exportReport(r,'pdf')}><FileText size={14}/>PDF</button><button onClick={()=>exportReport(r,'xlsx')}><FileSpreadsheet size={14}/>Excel</button></div></article>)}</div><form className="vsp-form" onSubmit={createReport}><h3>Új riportdefiníció</h3><input required placeholder="Riport neve" value={reportForm.name} onChange={e=>setReportForm({...reportForm,name:e.target.value})}/><input placeholder="Leírás" value={reportForm.description} onChange={e=>setReportForm({...reportForm,description:e.target.value})}/><select value={reportForm.source_key} onChange={e=>setReportForm({...reportForm,source_key:e.target.value})}>{(reportData.sources||[]).map((s:string)=><option key={s}>{s}</option>)}</select><input placeholder="Oszlopok vesszővel" value={reportForm.columns} onChange={e=>setReportForm({...reportForm,columns:e.target.value})}/><button className="vsp-button" type="submit"><Save size={14}/>Riport mentése</button></form></section>}

  {tab==='evaluation'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>Eredeti dolgozói értékelési logika</h2><p>Havi fekete/piros pont, piros X, vendég-tabletes pontszám és éves összesítés. A pontsúlyok környezeti változóval finomhangolhatók a történeti algoritmushoz.</p></div><input className="vsp-year" type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></div><div className="vsp-weight">Fekete: {legacy.weights?.black??1} • Piros: {legacy.weights?.red??-1} • Piros X: {legacy.weights?.red_x??-3}</div><form className="vsp-form inline" onSubmit={addPoint}><select required value={point.employee_id} onChange={e=>setPoint({...point,employee_id:e.target.value})}><option value="">Dolgozó kiválasztása</option>{employees.map((e:any)=><option key={e.id} value={e.id}>{e.full_name||e.name||e.email||e.id}</option>)}</select><input type="month" value={point.evaluation_month} onChange={e=>setPoint({...point,evaluation_month:e.target.value})}/><select value={point.point_type} onChange={e=>setPoint({...point,point_type:e.target.value})}><option value="black">Fekete pont</option><option value="red">Piros pont</option><option value="red_x">Piros X</option></select><input placeholder="Indoklás" value={point.reason} onChange={e=>setPoint({...point,reason:e.target.value})}/><button className="vsp-button" type="submit">Rögzítés</button></form><div className="vsp-table-wrap"><table><thead><tr><th>Dolgozó</th><th>Hónap</th><th>Fekete</th><th>Piros</th><th>Piros X</th><th>Összpont</th><th>Vendégátlag</th></tr></thead><tbody>{(legacy.monthly_summary||[]).map((r:any,i:number)=>{const g=(legacy.guest_summary||[]).find((x:any)=>String(x.employee_id)===String(r.employee_id)&&Number(x.month)===Number(r.month));return <tr key={`${r.employee_id}-${r.month}-${i}`}><td>{employeeName(r.employee_id)}</td><td>{r.month}.</td><td>{r.black_points||0}</td><td>{r.red_points||0}</td><td>{r.red_x||0}</td><td><b>{r.score}</b></td><td>{g?.guest_rating??'—'} {g?`(${g.guest_ratings})`:''}</td></tr>})}</tbody></table></div></section>}

  {tab==='reviews'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>Vendégértékelés → Facebook moderáció</h2><p>A tabletről érkező értékelés alapból <b>pending</b>. Facebook kampány csak moderátori jóváhagyás után jöhet létre.</p></div><a className="vsp-button link" href="/vendeg-ertekeles" target="_blank"><Star size={14}/>Tablet nézet</a></div><div className="vsp-list">{reviews.map(r=><article className="vsp-row" key={r.id}><div className="vsp-grow"><b>{'★'.repeat(Number(r.rating))}{'☆'.repeat(5-Number(r.rating))} {r.client_name||'Névtelen vendég'}</b><p>{r.review_text||'Szöveges megjegyzés nélkül'}</p><small>{fmt(r.created_at)} • {r.location_id||'nincs telephely'} {r.employee_id?`• ${employeeName(r.employee_id)}`:''}</small></div><span className={`vsp-badge ${r.moderation_status}`}>{r.moderation_status}</span>{r.moderation_status==='pending'&&<div className="vsp-actions"><button onClick={()=>moderate(r.id,'approve',false)}>Jóváhagyás</button><button onClick={()=>moderate(r.id,'approve',true)}>Jóváhagy + FB</button><button className="danger" onClick={()=>moderate(r.id,'reject')}>Elutasít</button></div>}</article>)}</div>{!pendingReviews.length&&<div className="vsp-empty"><CheckCircle2/>Nincs moderációra váró értékelés.</div>}</section>}

  {tab==='documents'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>Elektronikus dokumentumszerkesztő</h2><p>WYSIWYG szerkesztés, automatikus H1–H3 tartalomjegyzék, verziózás és draft/published állapot.</p></div><button className="vsp-button" onClick={newDocument}>+ Új dokumentum</button></div><div className="vsp-doc-layout"><aside>{documents.map(d=><button className={docId===d.id?'active':''} key={d.id} onClick={()=>openDocument(d.id)}><b>{d.title}</b><small>v{d.version} • {d.status}</small></button>)}</aside><div className="vsp-editor-shell"><div className="vsp-editor-meta"><input placeholder="Dokumentum címe" value={docTitle} onChange={e=>setDocTitle(e.target.value)}/><span>{docVersion?`v${docVersion}`:'új'}</span></div><div className="vsp-toolbar"><button onClick={()=>exec('bold')}><b>B</b></button><button onClick={()=>exec('italic')}><i>I</i></button><button onClick={()=>exec('formatBlock','H1')}>H1</button><button onClick={()=>exec('formatBlock','H2')}>H2</button><button onClick={()=>exec('formatBlock','H3')}>H3</button><button onClick={()=>exec('insertUnorderedList')}>• Lista</button><button onClick={()=>exec('insertOrderedList')}>1. Lista</button></div><div ref={editorRef} className="vsp-editor" contentEditable suppressContentEditableWarning/><div className="vsp-editor-actions"><select value={docStatus} onChange={e=>setDocStatus(e.target.value)}><option value="draft">Piszkozat</option><option value="published">Publikált</option></select><button className="vsp-button" onClick={()=>saveDocument(false)}><Save size={14}/>Mentés</button><button className="vsp-button primary" onClick={()=>saveDocument(true)}>Mentés + publikálás</button></div></div></div></section>}

  {tab==='configuration'&&<VirRuntimeSettingsPanel API_BASE={API_BASE} auth={auth}/>}

  {tab==='quality'&&<section className="vsp-panel"><div className="vsp-section-head"><div><h2>Nagy rendelkezésre állás + formális release minőségkapu</h2><p>Az alkalmazás csatolmányai DB-ben vannak, ezért API-példányhoz nem kötődnek. A valódi failover státuszt a hosting példányszám és DB HA alapján külön ellenőrizzük.</p></div></div><div className="vsp-status-grid"><Status label="API példányok" ok={(overview?.ha?.instance_count||1)>=2} text={String(overview?.ha?.instance_count||1)}/><Status label="Database HA" ok={overview?.ha?.database_ha_enabled} text={overview?.ha?.database_ha_enabled?'bekapcsolva':'nincs igazolva'}/><Status label="1 szerver kiesése" ok={overview?.ha?.ready_for_single_instance_failure} text={overview?.ha?.ready_for_single_instance_failure?'kész':'Render beállítás szükséges'}/></div><div className="vsp-quality-grid"><article><h3>Release gate</h3><ul><li>Unit teszt</li><li>Integration teszt</li><li>E2E teszt</li><li>Automatikus smoke</li><li><b>Manuális UAT sign-off</b></li></ul></article><article><h3>Külön dolgozói mobilapp</h3><p>A dolgozói self-service backend külön mobil-PWA felületet kapott, elkülönített manifesttel és telepítési scope-pal.</p><a className="vsp-button link" href="/employee-app" target="_blank">Dolgozói app megnyitása</a></article></div><form className="vsp-form" onSubmit={signRelease}><h3>Manuális release jóváhagyás</h3><input required placeholder="Release / commit / verzió" value={releaseForm.release_ref} onChange={e=>setReleaseForm({...releaseForm,release_ref:e.target.value})}/><input required placeholder="Tesztelő neve" value={releaseForm.tester_name} onChange={e=>setReleaseForm({...releaseForm,tester_name:e.target.value})}/><select value={releaseForm.result} onChange={e=>setReleaseForm({...releaseForm,result:e.target.value})}><option value="pass">PASS – kiadható</option><option value="fail">FAIL – nem adható ki</option></select><textarea placeholder="Megjegyzés" value={releaseForm.notes} onChange={e=>setReleaseForm({...releaseForm,notes:e.target.value})}/><button className="vsp-button" type="submit"><Archive size={14}/>Sign-off rögzítése</button></form><div className="vsp-list">{(overview?.release_signoffs||[]).map((s:any)=><article className="vsp-row" key={s.id}><div className="vsp-grow"><b>{s.release_ref}</b><p>{s.tester_name} • {fmt(s.created_at)}</p><small>{s.notes||'Megjegyzés nélkül'}</small></div><span className={`vsp-badge ${s.result}`}>{s.result.toUpperCase()}</span></article>)}</div></section>}
 </div>
}
function Kpi({icon:I,label,value,sub}:{icon:any,label:string,value:any,sub:string}){return <article className="vsp-kpi"><I size={20}/><div><small>{label}</small><b>{value}</b><span>{sub}</span></div></article>}
function Status({label,ok,text}:{label:string,ok:boolean,text:string}){return <article className={`vsp-status ${ok?'ok':'warn'}`}><span>{ok?<CheckCircle2 size={17}/>:<CloudCog size={17}/>}</span><div><b>{label}</b><small>{text}</small></div></article>}
