import React,{useEffect,useMemo,useState}from"react";
import{Area,AreaChart,ResponsiveContainer,Tooltip}from"recharts";
import{Activity,AlertTriangle,ArrowDownRight,ArrowUpRight,CalendarDays,CircleDollarSign,Gauge,Repeat2,ShoppingBag,Sparkles,Target,Users,WalletCards}from"lucide-react";
import api from"../api/api";
import{getVirDashboard,getVirRevenueSeries,type VirDashboardSummary,type VirRevenueRow}from"../api/vir";
import{useCapabilities}from"../hooks/useCapabilities";
import VirTopMetricsPage from"./VirTopMetricsPage";
import VirDecisionSupportPanel from"./VirDecisionSupportPanel";
import"./VirReportExtras.css";

type StaffMetric={employee_id:string|null;employee_name:string;workorder_count:number;revenue:number;avg_ticket:number};
type ManagementSummary={
 revenue:{gross_revenue:number;service_revenue:number;product_revenue:number;closed_workorders:number};
 stock:{low_stock_count:number;out_of_stock_count:number;stocked_products:number};
 crm:{unique_guests:number;new_guests:number;returning_guests:number;inactive_guests:number;visits:number};
 staff:StaffMetric[];
};
type FinanceDashboard={totals?:{income?:number;expense?:number;net?:number}};
type ExecutiveDashboard={stats?:{averageCapacity?:number}};
type Insight={tone:"good"|"warning"|"critical"|"info";title:string;text:string};

const huf=(v:number)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
const num=(v:number)=>new Intl.NumberFormat("hu-HU").format(Number(v||0));
const pct=(v:number)=>`${Number(v||0).toFixed(1)}%`;
const ratio=(a:number,b:number)=>b>0?a/b*100:0;
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const change=(current:number,previous:number)=>previous?((current-previous)/Math.abs(previous))*100:null;
const previousPeriod=(from:string,to:string)=>{const a=new Date(`${from}T12:00:00`),b=new Date(`${to}T12:00:00`),days=Math.max(1,Math.round((b.getTime()-a.getTime())/86400000)+1),prevTo=new Date(a);prevTo.setDate(prevTo.getDate()-1);const prevFrom=new Date(prevTo);prevFrom.setDate(prevFrom.getDate()-days+1);return{from:iso(prevFrom),to:iso(prevTo)}};

function Trend({value}:{value:number|null}){if(value===null)return <span className="vir-command-trend neutral">nincs összehasonlítás</span>;const up=value>=0;return <span className={`vir-command-trend ${up?"up":"down"}`}>{up?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {Math.abs(value).toFixed(1)}%</span>}
function Metric({icon:Icon,label,value,note,trend,tone}:{icon:any;label:string;value:string;note:string;trend?:number|null;tone?:string}){return <article className={`vir-command-metric ${tone||""}`}><div className="vir-command-metric-top"><span className="vir-command-icon"><Icon size={17}/></span>{trend!==undefined&&<Trend value={trend??null}/>}</div><small>{label}</small><strong>{value}</strong><p>{note}</p></article>}
function Progress({label,value,target,caption,inverse=false}:{label:string;value:number;target:string;caption:string;inverse?:boolean}){const display=clamp(value);const ok=inverse?value<=Number(target.replace(/[^0-9.]/g,"")):value>=Number(target.replace(/[^0-9.]/g,""));return <div className="vir-command-progress"><div className="vir-command-progress-head"><span>{label}</span><b className={ok?"ok":"watch"}>{pct(value)}</b></div><div className="vir-command-progress-track"><i style={{width:`${display}%`}}/></div><div className="vir-command-progress-foot"><span>{caption}</span><em>Irányadó cél: {target}</em></div></div>}

export default function VirTopMetricsExtendedPage(){
 const{menu}=useCapabilities();
 const canFinancial=menu("analytics.main","can_view_financial");
 const today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),1),from=iso(start),to=iso(today),prev=previousPeriod(from,to),days=Math.max(1,today.getDate());
 const[data,setData]=useState<ManagementSummary|null>(null),[summary,setSummary]=useState<VirDashboardSummary|null>(null),[series,setSeries]=useState<VirRevenueRow[]>([]),[finance,setFinance]=useState<FinanceDashboard|null>(null),[executive,setExecutive]=useState<ExecutiveDashboard|null>(null),[previousData,setPreviousData]=useState<ManagementSummary|null>(null),[previousSummary,setPreviousSummary]=useState<VirDashboardSummary|null>(null),[,setError]=useState("");
 useEffect(()=>{let active=true;const locationId=localStorage.getItem("kleo_location_id")||undefined;(async()=>{setError("");try{const core=await Promise.all([getVirDashboard({from,to,locationId}),getVirRevenueSeries({from,to,locationId}),api.get<ManagementSummary>("/transactions/cashier/management-summary",{params:{from,to,location_id:locationId}}).then(r=>r.data)]);if(!active)return;setSummary(core[0]);setSeries(core[1]);setData(core[2]);const extra=await Promise.allSettled([api.get<FinanceDashboard>("/transactions/finance-v5/dashboard",{params:{from,to,location_id:locationId}}).then(r=>r.data),api.get<ExecutiveDashboard>("/dashboard",{params:{from,to,location_id:locationId}}).then(r=>r.data),getVirDashboard({...prev,locationId}),api.get<ManagementSummary>("/transactions/cashier/management-summary",{params:{...prev,location_id:locationId}}).then(r=>r.data)]);if(!active)return;setFinance(extra[0].status==="fulfilled"?extra[0].value:null);setExecutive(extra[1].status==="fulfilled"?extra[1].value:null);setPreviousSummary(extra[2].status==="fulfilled"?extra[2].value:null);setPreviousData(extra[3].status==="fulfilled"?extra[3].value:null)}catch(e:any){if(active)setError(e?.response?.data?.message||e?.response?.data?.error||e?.message||"A vezetői összesítés nem frissíthető.")}})();return()=>{active=false}},[from,to,prev.from,prev.to]);

 const values=useMemo(()=>{const appointments=Number(summary?.appointments_count||0),completed=Number(summary?.completed_count||0),cancelled=Number(summary?.cancelled_count||0),noShowCount=Number(summary?.no_show_count||0),noShow=Number(summary?.no_show_rate_percent||0),cancellation=Number(summary?.cancellation_rate_percent||0),paid=Number(summary?.paid_total||0),revenue=Number(data?.revenue?.gross_revenue||0),service=Number(data?.revenue?.service_revenue||0),product=Number(data?.revenue?.product_revenue||0),guests=Number(data?.crm?.unique_guests||0),returning=Number(data?.crm?.returning_guests||0),newGuests=Number(data?.crm?.new_guests||0),stocked=Number(data?.stock?.stocked_products||0),alerts=Number(data?.stock?.low_stock_count||0)+Number(data?.stock?.out_of_stock_count||0),completion=ratio(completed,appointments),retention=ratio(returning,guests),collection=ratio(paid,revenue),retailRatio=ratio(product,service),utilization=executive?.stats?.averageCapacity==null?null:Number(executive.stats.averageCapacity),net=Number(finance?.totals?.net||0),income=Number(finance?.totals?.income||0),margin=ratio(net,income);return{appointments,completed,cancelled,noShowCount,noShow,cancellation,paid,revenue,service,product,guests,returning,newGuests,stocked,alerts,completion,retention,collection,retailRatio,utilization,net,margin}},[summary,data,finance,executive]);
 const prevRevenue=Number(previousData?.revenue?.gross_revenue||0),prevAppointments=Number(previousSummary?.appointments_count||0),prevGuests=Number(previousData?.crm?.unique_guests||0);
 const health=useMemo(()=>{const retentionScore=clamp(values.retention/60*100),completionScore=clamp(values.completion/90*100),noShowScore=clamp((10-values.noShow)/5*100),collectionScore=values.revenue?clamp(values.collection/95*100):100,stockRisk=values.stocked?values.alerts/values.stocked*100:0,stockScore=clamp(100-stockRisk*4),utilScore=values.utilization==null?80:values.utilization>=70&&values.utilization<=85?100:values.utilization<70?clamp(values.utilization/70*100):clamp((100-values.utilization)/15*100);return Math.round(retentionScore*.22+completionScore*.22+noShowScore*.17+collectionScore*.14+stockScore*.1+utilScore*.15)},[values]);
 const insights=useMemo<Insight[]>(()=>{const out:Insight[]=[];if(values.noShow>5)out.push({tone:"critical",title:"No-show veszteség",text:`A meg nem jelenési arány ${pct(values.noShow)}. A napi kontroll és automatikus emlékeztetők elsődleges beavatkozási pontok.`});if(values.cancellation>10)out.push({tone:"warning",title:"Magas lemondási arány",text:`A lemondási arány ${pct(values.cancellation)}. Érdemes forrás, napszak és szolgáltatás szerint lefúrni.`});if(values.retention<60&&values.guests>0)out.push({tone:"warning",title:"Vendégmegtartás fejleszthető",text:`A visszatérési arány ${pct(values.retention)}. A következő fejlesztési cél a kohorsz- és új/meglévő vendég retention legyen.`});if(values.utilization!=null&&values.utilization<60)out.push({tone:"warning",title:"Kihasználatlan kapacitás",text:`A foglaltság ${pct(values.utilization)}. Műszak-, napszak- és szolgáltatás-heatmap segíthet a kapacitást a kereslethez igazítani.`});if(values.utilization!=null&&values.utilization>90)out.push({tone:"warning",title:"Túlterhelt kapacitás",text:`A foglaltság ${pct(values.utilization)}. Ez csúcsidős erőforráshiányt jelezhet.`});if(values.alerts>0)out.push({tone:"warning",title:"Készletkockázat",text:`${num(values.alerts)} termék kritikus vagy kifogyott készleten van; az utánrendelési javaslatokat érdemes megnyitni.`});if(canFinancial&&values.revenue>0&&values.collection<95)out.push({tone:"warning",title:"Beszedési rés",text:`A fizetett / lezárt bevétel aránya ${pct(values.collection)}. Ellenőrizd a nyitott, függő vagy később rendezett tételeket.`});if(!out.length)out.push({tone:"good",title:"Nincs kritikus vezetői riasztás",text:"A legfontosabb működési mutatók jelenleg az irányadó sávban vannak. A trendek és lokációk közti eltérések továbbra is figyelendők."});return out.slice(0,4)},[values,canFinancial]);
 const spark=series.map(r=>({day:String(r.day||"").slice(5),revenue:Number(r.revenue_total||0)}));
 const staff=(data?.staff||[]).slice(0,5);
 const serviceShare=ratio(values.service,values.revenue),productShare=ratio(values.product,values.revenue),returningShare=ratio(values.returning,Math.max(1,values.newGuests+values.returning)),newShare=ratio(values.newGuests,Math.max(1,values.newGuests+values.returning));

 return <>
  <section className="vir-command-shell">
   <header className="vir-command-hero">
    <div className="vir-command-copy"><span className="vir-command-eyebrow"><Sparkles size={13}/> VIR EXECUTIVE INTELLIGENCE</span><h1>Vezetői irányítópult</h1><p>Egy képernyőn a bevétel, kapacitás, vendégmegtartás, foglalásminőség és készletkockázat. A részletes VIR-riportok lejjebb változatlanul elérhetők.</p><div className="vir-command-period"><CalendarDays size={14}/>{from} – {to}<span>·</span>{days} nap</div></div>
    <div className="vir-health"><div className="vir-health-ring" style={{"--score":`${health*3.6}deg`} as React.CSSProperties}><div><strong>{health}</strong><span>/100</span></div></div><div><small>Üzleti egészség</small><b>{health>=85?"Kiemelkedő":health>=70?"Stabil":health>=55?"Figyelendő":"Beavatkozást igényel"}</b><p>6 vezetői dimenzió összesített állapota</p></div></div>
   </header>

   <div className="vir-command-grid">
    {canFinancial&&<Metric icon={CircleDollarSign} label="Lezárt bevétel" value={huf(values.revenue)} note={`${huf(values.revenue/days)} / nap`} trend={change(values.revenue,prevRevenue)}/>}<Metric icon={CalendarDays} label="Foglalások" value={num(values.appointments)} note={`${num(values.completed)} teljesített`} trend={change(values.appointments,prevAppointments)}/><Metric icon={Users} label="Egyedi vendégek" value={num(values.guests)} note={`${num(values.newGuests)} új vendég`} trend={change(values.guests,prevGuests)}/><Metric icon={Repeat2} label="Visszatérési arány" value={pct(values.retention)} note={`${num(values.returning)} visszatérő vendég`} tone={values.retention<60?"watch":"good"}/><Metric icon={Gauge} label="Kapacitás / foglaltság" value={values.utilization==null?"—":pct(values.utilization)} note={values.utilization==null?"Nincs kapacitásadat":"Irányadó működési sáv: 70–85%"} tone={values.utilization!=null&&(values.utilization<60||values.utilization>90)?"watch":""}/>{canFinancial&&<Metric icon={WalletCards} label="Pénzügyi eredmény" value={finance?.totals?huf(values.net):"—"} note={finance?.totals?`${pct(values.margin)} nettó pénzforgalmi marzs`:"Pénzügyi V5 adat nem érkezett"}/>}<Metric icon={Activity} label="No-show" value={pct(values.noShow)} note={`${num(values.noShowCount)} meg nem jelenés`} tone={values.noShow>5?"danger":"good"}/><Metric icon={ShoppingBag} label="Retail / szolgáltatás" value={pct(values.retailRatio)} note={`${pct(productShare)} termékbevétel-rész`}/>
   </div>

   <div className="vir-command-layout">
    <section className="vir-command-card trend-card"><div className="vir-command-card-head"><div><span>TREND</span><h2>Bevételi pulzus</h2><p>Napi VIR árbevétel az aktuális hónapban.</p></div>{canFinancial&&<b>{huf(values.revenue)}</b>}</div><div className="vir-command-chart">{canFinancial?<ResponsiveContainer width="100%" height="100%"><AreaChart data={spark}><defs><linearGradient id="virRevenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8c62ea" stopOpacity={.28}/><stop offset="100%" stopColor="#8c62ea" stopOpacity={.02}/></linearGradient></defs><Tooltip formatter={(v:any)=>huf(Number(v||0))}/><Area type="monotone" dataKey="revenue" stroke="#7658df" strokeWidth={3} fill="url(#virRevenueFill)" dot={false}/></AreaChart></ResponsiveContainer>:<div className="vir-command-empty">Pénzügyi jogosultság szükséges.</div>}</div></section>
    <section className="vir-command-card"><div className="vir-command-card-head"><div><span>VEZETŐI FIGYELEM</span><h2>Mit kell most nézni?</h2><p>Automatikus, szabályalapú figyelmeztetések a kritikus KPI-kból.</p></div><AlertTriangle size={20}/></div><div className="vir-insight-list">{insights.map((x,i)=><article className={`vir-insight ${x.tone}`} key={`${x.title}-${i}`}><i/><div><b>{x.title}</b><p>{x.text}</p></div></article>)}</div></section>
   </div>

   <div className="vir-command-layout lower">
    <section className="vir-command-card"><div className="vir-command-card-head"><div><span>CÉLOK</span><h2>Operatív kontrollsávok</h2><p>Gyors összevetés irányadó szépségipari működési célokkal.</p></div><Target size={20}/></div><div className="vir-command-progress-list"><Progress label="Vendég-visszatérés" value={values.retention} target="60%+" caption="Visszatérő / egyedi vendég"/><Progress label="Foglalások teljesülése" value={values.completion} target="90%+" caption="Teljesített / összes foglalás"/><Progress label="No-show" value={values.noShow} target="5% alatt" caption="Alacsonyabb érték a jobb" inverse/><Progress label="Beszedési arány" value={values.collection} target="95%+" caption="Fizetett / lezárt bevétel"/>{values.utilization!=null&&<Progress label="Kapacitáskihasználás" value={values.utilization} target="70%+" caption="Ideális vezetői sáv: 70–85%"/>}</div></section>
    <section className="vir-command-card"><div className="vir-command-card-head"><div><span>ÜZLETI MIX</span><h2>Mi hajtja a forgalmat?</h2><p>Bevételi és vendégösszetétel gyors értelmezéshez.</p></div></div><div className="vir-mix-block"><div className="vir-mix-head"><span>Szolgáltatás</span><b>{pct(serviceShare)}</b></div><div className="vir-mix-track"><i style={{width:`${clamp(serviceShare)}%`}}/></div><div className="vir-mix-head"><span>Termék / retail</span><b>{pct(productShare)}</b></div><div className="vir-mix-track retail"><i style={{width:`${clamp(productShare)}%`}}/></div></div><div className="vir-mix-divider"/><div className="vir-mix-block"><div className="vir-mix-head"><span>Visszatérő vendég</span><b>{pct(returningShare)}</b></div><div className="vir-mix-track guests"><i style={{width:`${clamp(returningShare)}%`}}/></div><div className="vir-mix-head"><span>Új vendég</span><b>{pct(newShare)}</b></div><div className="vir-mix-track new"><i style={{width:`${clamp(newShare)}%`}}/></div></div></section>
   </div>

   <section className="vir-command-card vir-command-staff"><div className="vir-command-card-head"><div><span>CSAPAT</span><h2>Top munkatársi teljesítmény</h2><p>A kiválasztott havi időszak lezárt munkalapjai alapján.</p></div></div><div className="vir-command-staff-grid">{staff.map((s,i)=><article key={`${s.employee_id||"staff"}-${i}`}><span className="rank">{i+1}</span><div><b>{s.employee_name}</b><small>{num(s.workorder_count)} lezárt munkalap</small></div>{canFinancial&&<strong>{huf(s.revenue)}</strong>}</article>)}{!staff.length&&<div className="vir-command-empty">Nincs munkatársi teljesítményadat ebben az időszakban.</div>}</div></section>
  </section>

  <VirDecisionSupportPanel/>
  <div className="vir-detail-divider"><span>RÉSZLETES ELEMZÉS</span><h2>Teljes VIR kimutatás</h2><p>Időszak- és szalonszűréssel, részletes pénzügyi, vendég-, készlet- és munkatársi blokkokkal.</p></div>
  <VirTopMetricsPage/>
 </>;
}
