import React,{useEffect,useMemo,useState}from"react";
import{Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from"recharts";
import api from"../api/api";
import{getCurrentUser,type CurrentUser}from"../api/me";
import{getLocations}from"../api/locations";
import{getVirDashboard,getVirRevenueSeries,type VirDashboardSummary,type VirRevenueRow}from"../api/vir";
import{useCapabilities}from"../hooks/useCapabilities";
import ManagementToolsPage from"./ManagementToolsPage";
import"./VirTopMetricsPage.css";

type LocationRow={id:string|number;name:string};
type PeriodKey="today"|"week"|"month"|"custom";
type StaffMetric={employee_id:string|null;employee_name:string;workorder_count:number;revenue:number;avg_ticket:number};
type ManagementSummary={
 revenue:{service_revenue:number;product_revenue:number;gross_revenue:number;discounts:number;tips:number;closed_workorders:number;service_quantity:number;product_quantity:number;avg_service_price:number;avg_product_price:number;service_share_percent:number;product_share_percent:number};
 stock:{inventory_value:number;low_stock_count:number;out_of_stock_count:number;stocked_products:number};
 crm:{visits:number;unique_guests:number;guest_revenue:number;avg_guest_spend:number;new_guests:number;returning_guests:number;inactive_guests:number;inactive_after_days:number};
 staff:StaffMetric[];
 financial_redacted?:boolean;
};
type ExecutiveDashboard={stats?:{averageCapacity?:number};chartData?:Array<{date:string;revenue:number;service_revenue:number;product_revenue:number;completed:number}>};

const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const periodDates=(period:Exclude<PeriodKey,"custom">)=>{const end=new Date(),start=new Date(end);if(period==="today")return{from:iso(end),to:iso(end)};if(period==="week")start.setDate(end.getDate()-6);else start.setDate(1);return{from:iso(start),to:iso(end)}};
const huf=(v?:number|null)=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(Number(v||0));
const num=(v?:number|null)=>new Intl.NumberFormat("hu-HU").format(Number(v||0));
const pct=(v?:number|null)=>`${Number(v||0).toFixed(1)}%`;
const safeRatio=(a?:number|null,b?:number|null)=>Number(b||0)>0?Number(a||0)/Number(b||0)*100:0;
const dateSpan=(from:string,to:string)=>Math.max(1,Math.round((new Date(`${to}T12:00:00`).getTime()-new Date(`${from}T12:00:00`).getTime())/86400000)+1);
const previousPeriod=(from:string,to:string)=>{const start=new Date(`${from}T12:00:00`),end=new Date(`${to}T12:00:00`),days=dateSpan(from,to);const prevTo=new Date(start);prevTo.setDate(prevTo.getDate()-1);const prevFrom=new Date(prevTo);prevFrom.setDate(prevFrom.getDate()-days+1);return{from:iso(prevFrom),to:iso(prevTo)}};
const change=(current?:number|null,previous?:number|null)=>{const c=Number(current||0),p=Number(previous||0);if(!Number.isFinite(c)||!Number.isFinite(p)||p===0)return null;return(c-p)/Math.abs(p)*100};

function Card({title,value,sub,state,delta}:{title:string;value:string;sub:string;state?:"warning"|"critical";delta?:number|null}){return <article className={`topmetrics-card ${state||""}`}><small>{title}</small><strong>{value}</strong><em>{sub}</em>{delta!==undefined&&delta!==null&&<span className={`topmetrics-delta ${delta<0?"down":"up"}`}>{delta>=0?"+":""}{delta.toFixed(1)}% előző időszakhoz</span>}</article>}
function Restricted(){return <div className="topmetrics-status" style={{margin:"12px 0"}}>A pénzügyi mutatók megtekintéséhez külön pénzügyi jogosultság szükséges.</div>}

function TopMetricsContent(){
 const{menu}=useCapabilities();
 const canFinancial=menu("analytics.main","can_view_financial");
 const initial=periodDates("month");
 const[period,setPeriod]=useState<PeriodKey>("month"),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[locationId,setLocationId]=useState("");
 const[user,setUser]=useState<CurrentUser|null>(null),[locations,setLocations]=useState<LocationRow[]>([]);
 const[summary,setSummary]=useState<VirDashboardSummary|null>(null),[series,setSeries]=useState<VirRevenueRow[]>([]),[management,setManagement]=useState<ManagementSummary|null>(null),[executive,setExecutive]=useState<ExecutiveDashboard|null>(null);
 const[previousSummary,setPreviousSummary]=useState<VirDashboardSummary|null>(null),[previousManagement,setPreviousManagement]=useState<ManagementSummary|null>(null);
 const[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{getCurrentUser().then(x=>setUser(x||null)).catch(()=>setUser(null));getLocations().then((rows:any[])=>setLocations((rows||[]).map(x=>({id:x.id,name:x.name})))).catch(()=>setLocations([]))},[]);
 useEffect(()=>{if(period==="custom")return;const p=periodDates(period);setFrom(p.from);setTo(p.to)},[period]);
 useEffect(()=>{if(!user)return;const effective=user.role==="admin"?(locationId||undefined):(user.location_id?String(user.location_id):undefined);(async()=>{setLoading(true);setError("");try{const params={from,to,locationId:effective},prev=previousPeriod(from,to);const[s,ser,m]=await Promise.all([getVirDashboard(params),getVirRevenueSeries(params),api.get<ManagementSummary>("/transactions/cashier/management-summary",{params:{from,to,location_id:effective}}).then(r=>r.data)]);setSummary(s);setSeries(ser);setManagement(m);const[pS,pM,exec]=await Promise.allSettled([getVirDashboard({...prev,locationId:effective}),api.get<ManagementSummary>("/transactions/cashier/management-summary",{params:{...prev,location_id:effective}}).then(r=>r.data),api.get<ExecutiveDashboard>("/dashboard",{params:{from,to,location_id:effective}}).then(r=>r.data)]);setPreviousSummary(pS.status==="fulfilled"?pS.value:null);setPreviousManagement(pM.status==="fulfilled"?pM.value:null);setExecutive(exec.status==="fulfilled"?exec.value:null)}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||e?.message||"A kimutatások betöltése sikertelen.")}finally{setLoading(false)}})()},[user,from,to,locationId]);
 const chartData=useMemo(()=>series.map(r=>({day:r.day?.slice(5)||"",revenue:Number(r.revenue_total||0),paid:Number(r.paid_total||0),appointments:Number(r.appointments_count||0)})),[series]);
 const altegioSales=useMemo(()=>executive?.chartData?.length?executive.chartData.map(r=>({day:String(r.date||"").slice(5),total:Number(r.revenue||0),service:Number(r.service_revenue||0),product:Number(r.product_revenue||0)})):chartData.map(r=>({day:r.day,total:r.revenue,service:0,product:0})),[executive,chartData]);
 const staffData=useMemo(()=>(management?.staff||[]).slice(0,10).map(x=>({name:x.employee_name,revenue:Number(x.revenue||0),workorders:Number(x.workorder_count||0)})),[management]);
 const appointments=Number(summary?.appointments_count||0),completed=Number(summary?.completed_count||0),cancelled=Number(summary?.cancelled_count||0),noShow=Number(summary?.no_show_count||0),days=dateSpan(from,to);
 const completion=safeRatio(completed,appointments),cancellation=Number(summary?.cancellation_rate_percent||0),noShowRate=Number(summary?.no_show_rate_percent||0);
 const revenue=management?.revenue,stock=management?.stock,crm=management?.crm,prevRevenue=previousManagement?.revenue,prevCrm=previousManagement?.crm;
 const bookingAverage=appointments?Number(revenue?.gross_revenue||0)/appointments:0,prevBookingAverage=Number(previousSummary?.appointments_count||0)?Number(prevRevenue?.gross_revenue||0)/Number(previousSummary?.appointments_count||0):0;
 const returningRate=safeRatio(crm?.returning_guests,crm?.unique_guests),newGuestRate=safeRatio(crm?.new_guests,crm?.unique_guests);
 const guestMix=[{name:"Új vendég",value:Number(crm?.new_guests||0)},{name:"Visszatérő",value:Number(crm?.returning_guests||0)},{name:"Elveszett / inaktív",value:Number(crm?.inactive_guests||0)}];
 const bookingMix=[{name:"Befejezett",value:completed},{name:"Lemondott",value:cancelled},{name:"No-show",value:noShow}];
 return <main className="topmetrics-page">
  <section className="topmetrics-hero"><div><span className="topmetrics-eyebrow">KIMUTATÁSOK / VEZETŐI DASHBOARD</span><h1>Legfőbb mutatók</h1><p>Pénzügyi, vendég-, működési, készlet- és munkatársi KPI-k valós rendszeradatokból, Altegio-paritással.</p></div><div className="topmetrics-filter"><div className="topmetrics-presets"><button className={period==="today"?"active":""} onClick={()=>setPeriod("today")}>Ma</button><button className={period==="week"?"active":""} onClick={()=>setPeriod("week")}>7 nap</button><button className={period==="month"?"active":""} onClick={()=>setPeriod("month")}>Hónap</button></div><label>Kezdőnap<input type="date" value={from} onChange={e=>{setPeriod("custom");setFrom(e.target.value)}}/></label><label>Zárónap<input type="date" value={to} onChange={e=>{setPeriod("custom");setTo(e.target.value)}}/></label>{user?.role==="admin"&&<label>Szalon<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Összes</option>{locations.map(l=><option key={String(l.id)} value={String(l.id)}>{l.name}</option>)}</select></label>}</div></section>
  {loading&&<div className="topmetrics-status loading">Adatok frissítése…</div>}{error&&<div className="topmetrics-status error">{error}</div>}

  <section className="topmetrics-section"><header><div><span>PÉNZÜGY</span><h2>Értékesítés és pénzügyi teljesítmény</h2><p>Csak a ténylegesen lezárt és rögzített munkalapokból számolt mutatók.</p></div></header>{canFinancial?<><div className="topmetrics-grid">
   <Card title="Összes lezárt értékesítés" value={huf(revenue?.gross_revenue)} sub={`${num(revenue?.closed_workorders)} lezárt munkalap`} delta={change(revenue?.gross_revenue,prevRevenue?.gross_revenue)}/><Card title="Szolgáltatásbevétel" value={huf(revenue?.service_revenue)} sub={`${pct(revenue?.service_share_percent)} bevételrész`} delta={change(revenue?.service_revenue,prevRevenue?.service_revenue)}/><Card title="Termékbevétel" value={huf(revenue?.product_revenue)} sub={`${pct(revenue?.product_share_percent)} bevételrész`} delta={change(revenue?.product_revenue,prevRevenue?.product_revenue)}/><Card title="Átlagos kosárérték" value={huf(summary?.avg_basket)} sub={`${num(appointments)} foglalás alapján`} delta={change(summary?.avg_basket,previousSummary?.avg_basket)}/><Card title="Szolgáltatások átlagára" value={huf(revenue?.avg_service_price)} sub={`${num(revenue?.service_quantity)} értékesített tétel`} delta={change(revenue?.avg_service_price,prevRevenue?.avg_service_price)}/><Card title="Termékek átlagára" value={huf(revenue?.avg_product_price)} sub={`${num(revenue?.product_quantity)} értékesített tétel`} delta={change(revenue?.avg_product_price,prevRevenue?.avg_product_price)}/><Card title="Kedvezmények" value={huf(revenue?.discounts)} sub="Lezárt munkalapokon"/><Card title="Borravaló" value={huf(revenue?.tips)} sub="Lezárt munkalapokon"/><Card title="Fizetett összeg" value={huf(summary?.paid_total)} sub="Kimutatási időszak" delta={change(summary?.paid_total,previousSummary?.paid_total)}/><Card title="Lezárt munkalapok" value={num(revenue?.closed_workorders)} sub="Pénzügyi zárással" delta={change(revenue?.closed_workorders,prevRevenue?.closed_workorders)}/>
  </div><div className="topmetrics-chart-grid"><div className="topmetrics-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip formatter={(v:any)=>huf(Number(v||0))}/><Legend/><Line type="monotone" dataKey="revenue" name="Árbevétel" stroke="#7558dd" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="paid" name="Fizetett" stroke="#2f9ea0" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><div className="topmetrics-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="appointments" name="Foglalások" fill="#8a70e4" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div></>:<Restricted/>}</section>

  <section className="topmetrics-section altegio-parity"><header><div><span>ALTEGIO-PARITÁS</span><h2>Értékesítés, látogatók és foglaltsági mutatók</h2><p>Az Altegio „Legfőbb mutatók” nézetének VIR-ben értelmezhető elemei, meglévő rendszeradatokból.</p></div><div className="topmetrics-badge">Összehasonlítás: előző azonos hosszúságú időszak</div></header>{canFinancial&&<><div className="topmetrics-grid"><Card title="Értékesítések összesen" value={huf(revenue?.gross_revenue)} sub={`${num(revenue?.closed_workorders)} lezárt munkalap`} delta={change(revenue?.gross_revenue,prevRevenue?.gross_revenue)}/><Card title="Szolgáltatások" value={huf(revenue?.service_revenue)} sub={`${pct(revenue?.service_share_percent)} bevételrész`} delta={change(revenue?.service_revenue,prevRevenue?.service_revenue)}/><Card title="Termékek" value={huf(revenue?.product_revenue)} sub={`${pct(revenue?.product_share_percent)} bevételrész`} delta={change(revenue?.product_revenue,prevRevenue?.product_revenue)}/><Card title="Foglalás átlagos értéke" value={huf(bookingAverage)} sub={`${num(appointments)} bejegyzésre vetítve`} delta={change(bookingAverage,prevBookingAverage)}/></div><div className="topmetrics-chart topmetrics-wide-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={altegioSales}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip formatter={(v:any)=>huf(Number(v||0))}/><Legend/><Line type="monotone" dataKey="total" name="Összes értékesítés" stroke="#7558dd" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="service" name="Szolgáltatások" stroke="#d28743" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="product" name="Termékek" stroke="#6eb9dd" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></>}
  <div className="topmetrics-subtitle">Látogatók</div><div className="topmetrics-grid"><Card title="Ügyfelek / egyedi vendégek" value={num(crm?.unique_guests)} sub="Az időszakban" delta={change(crm?.unique_guests,prevCrm?.unique_guests)}/><Card title="Látogatások" value={num(crm?.visits)} sub={`${num(crm?.unique_guests)} egyedi vendég`} delta={change(crm?.visits,prevCrm?.visits)}/><Card title="Bejegyzések / foglalások" value={num(appointments)} sub={`${(appointments/days).toFixed(1)} / nap`} delta={change(appointments,previousSummary?.appointments_count)}/><Card title="Új vendégek" value={num(crm?.new_guests)} sub={`${pct(newGuestRate)} az egyedi vendégekből`} delta={change(crm?.new_guests,prevCrm?.new_guests)}/><Card title="Visszatérő vendégek" value={num(crm?.returning_guests)} sub={`${pct(returningRate)} visszatérési arány`} delta={change(crm?.returning_guests,prevCrm?.returning_guests)}/><Card title="Elveszett / inaktív vendégek" value={num(crm?.inactive_guests)} sub={`${num(crm?.inactive_after_days||60)}+ napja nem tértek vissza`} state={Number(crm?.inactive_guests||0)>0?"warning":undefined} delta={change(crm?.inactive_guests,prevCrm?.inactive_guests)}/><Card title="Átlagos látogatás / nap" value={(Number(crm?.visits||0)/days).toFixed(1)} sub={`${days} napos időszak`}/><Card title="Átlagos foglalás / nap" value={(appointments/days).toFixed(1)} sub={`${days} napos időszak`}/></div><div className="topmetrics-chart-grid"><div className="topmetrics-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={guestMix}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="Vendégek" fill="#8063df" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="topmetrics-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={bookingMix}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="Bejegyzések" fill="#d8a52d" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div>
  <div className="topmetrics-subtitle">Foglaltsági és teljesülési mutatók</div><div className="topmetrics-grid"><Card title="Befejezett bejegyzések" value={num(completed)} sub={`${pct(completion)} teljesítési arány`} delta={change(completed,previousSummary?.completed_count)}/><Card title="Lemondott bejegyzések" value={num(cancelled)} sub={`${pct(cancellation)} lemondási arány`} state={cancellation>10?"warning":undefined} delta={change(cancelled,previousSummary?.cancelled_count)}/><Card title="Meg nem jelent / no-show" value={num(noShow)} sub={`${pct(noShowRate)} no-show arány`} state={noShowRate>5?"critical":undefined} delta={change(noShow,previousSummary?.no_show_count)}/><Card title="Átlagos foglaltság" value={executive?.stats?.averageCapacity==null?"—":pct(executive.stats.averageCapacity)} sub={executive?.stats?.averageCapacity==null?"Kapacitásadat nem érkezett":"Munkaidő-kapacitás alapján"}/><Card title="Teljesítési arány" value={pct(completion)} sub={`${num(completed)} / ${num(appointments)}`}/><Card title="Lemondási arány" value={pct(cancellation)} sub={`${num(cancelled)} lemondás`} state={cancellation>10?"warning":undefined}/><Card title="No-show arány" value={pct(noShowRate)} sub={`${num(noShow)} meg nem jelenés`} state={noShowRate>5?"critical":undefined}/><Card title="Bejegyzés / lezárt munkalap" value={Number(revenue?.closed_workorders||0)?(appointments/Number(revenue?.closed_workorders||1)).toFixed(2):"—"} sub="Foglalási terhelés és pénzügyi zárás viszonya"/></div></section>

  <section className="topmetrics-section"><header><div><span>VENDÉG ÉS MŰKÖDÉS</span><h2>Részletes CRM és időpont-minőség</h2></div></header><div className="topmetrics-grid"><Card title="CRM látogatások" value={num(crm?.visits)} sub={`${num(crm?.unique_guests)} egyedi vendég`}/>{canFinancial&&<Card title="CRM vendégbevétel" value={huf(crm?.guest_revenue)} sub={`Átlag: ${huf(crm?.avg_guest_spend)}`}/>} {canFinancial&&<Card title="Átlagos vendégköltés" value={huf(crm?.avg_guest_spend)} sub="CRM látogatások alapján"/>}<Card title="Egyedi vendégek" value={num(crm?.unique_guests)} sub="Az időszakban"/><Card title="Új vendégek" value={num(crm?.new_guests)} sub="Első látogatás az időszakban"/><Card title="Visszatérő vendégek" value={num(crm?.returning_guests)} sub="Korábbi és aktuális látogatással"/><Card title="Inaktív vendégek" value={num(crm?.inactive_guests)} sub={`${num(crm?.inactive_after_days||60)}+ napja nem tértek vissza`} state={Number(crm?.inactive_guests||0)>0?"warning":undefined}/><Card title="Foglalások" value={num(appointments)} sub={`${num(completed)} teljesített`}/><Card title="Teljesítési arány" value={pct(completion)} sub={`${num(completed)} / ${num(appointments)}`}/><Card title="Lemondási arány" value={pct(cancellation)} sub={`${num(cancelled)} lemondás`} state={cancellation>10?"warning":undefined}/><Card title="No-show arány" value={pct(noShowRate)} sub={`${num(noShow)} meg nem jelenés`} state={noShowRate>5?"critical":undefined}/><Card title="Vendég-visszatérési arány" value={pct(returningRate)} sub={`${num(crm?.returning_guests)} visszatérő / ${num(crm?.unique_guests)} egyedi`}/></div></section>

  <section className="topmetrics-section"><header><div><span>RAKTÁR</span><h2>Készletállapot és érték</h2></div></header><div className="topmetrics-grid">{canFinancial&&<Card title="Készletérték" value={huf(stock?.inventory_value)} sub="Aktuális bekerülési értéken"/>}<Card title="Készletezett termékek" value={num(stock?.stocked_products)} sub="Aktív készletegyenleg"/><Card title="Alacsony készlet" value={num(stock?.low_stock_count)} sub="Minimum szinten vagy alatta" state={Number(stock?.low_stock_count||0)>0?"warning":undefined}/><Card title="Kifogyott termék" value={num(stock?.out_of_stock_count)} sub="Nulla vagy negatív készlet" state={Number(stock?.out_of_stock_count||0)>0?"critical":undefined}/></div>{canFinancial&&<p className="topmetrics-source-note">A készletérték csak azoknál a termékeknél pontos, amelyekhez a unit_cost mező fel van töltve.</p>}</section>

  <section className="topmetrics-section"><header><div><span>MUNKATÁRSAK</span><h2>Teljesítmény {canFinancial?"és lezárt bevétel":""}</h2></div></header>{canFinancial?<div className="topmetrics-chart-grid"><div className="topmetrics-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={staffData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip formatter={(v:any)=>huf(Number(v||0))}/><Bar dataKey="revenue" name="Lezárt bevétel" fill="#7558dd" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="topmetrics-table-wrap"><table className="topmetrics-table"><thead><tr><th>Munkatárs</th><th>Lezárt munkalap</th><th>Bevétel</th><th>Átlagos kosár</th></tr></thead><tbody>{(management?.staff||[]).map((r,i)=><tr key={`${r.employee_id||"x"}-${i}`}><td><strong>{r.employee_name}</strong></td><td>{num(r.workorder_count)}</td><td>{huf(r.revenue)}</td><td>{huf(r.avg_ticket)}</td></tr>)}{!management?.staff?.length&&<tr><td colSpan={4}><div className="topmetrics-empty">Nincs munkatársi adat a kiválasztott időszakban.</div></td></tr>}</tbody></table></div></div>:<div className="topmetrics-table-wrap"><table className="topmetrics-table"><thead><tr><th>Munkatárs</th><th>Lezárt munkalap</th></tr></thead><tbody>{(management?.staff||[]).map((r,i)=><tr key={`${r.employee_id||"x"}-${i}`}><td><strong>{r.employee_name}</strong></td><td>{num(r.workorder_count)}</td></tr>)}{!management?.staff?.length&&<tr><td colSpan={2}><div className="topmetrics-empty">Nincs munkatársi adat a kiválasztott időszakban.</div></td></tr>}</tbody></table></div>}</section>
 </main>
}

export default function VirTopMetricsPage(){return window.location.pathname==="/reports/management-tools"?<ManagementToolsPage/>:<TopMetricsContent/>}
