import React,{useEffect,useMemo,useRef,useState}from"react";
import axios from"axios";
import{CheckCircle2,ExternalLink,ImagePlus,MonitorPlay,Plus,RefreshCw,Save,Send,Smartphone,Sparkles,Undo2}from"lucide-react";
import"./WallBoardDailyActionPage.css";

const API_BASE=window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:5000/api':'https://kleoszalon-api-1.onrender.com/api';
const API=`${API_BASE}/transactions/daily-actions`;
const AUTO=`${API}/auto-selector`;
const WALLBOARD=`${API_BASE}/signage/wallboard`;
const auth=()=>{const token=localStorage.getItem('kleo_token')||localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
const localDate=(d:Date)=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)};
const today=()=>localDate(new Date()).slice(0,10);
const emptyForm=()=>{const now=new Date(),end=new Date(now.getTime()+24*60*60*1000);return{id:'',name:`WallBoard napi akció – ${now.toLocaleDateString('hu-HU')}`,headline:'',description_html:'',discount_text:'',image_url:'',cta_label:'Foglalok',cta_url:'/foglalas',valid_from:localDate(now),valid_until:localDate(end),channels:['app'],audience:{type:'all'},status:'draft'} as any};
const strip=(html:string)=>String(html||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim();

type AutoCandidate={serviceId:string;name:string;price:number;durationMinutes:number;bookingsToday:number;avgDailyBookings28d:number;bookedMinutesToday:number;avgDailyBookedMinutes28d:number;demandGapPct:number;locationOccupancyPct:number;recentCampaigns:number;score:number;suggestedDiscountPct:number;reason:string;headline:string;description:string};
type AutoResult={date:string;locationId?:string|null;locationOccupancyPct:number;scheduledMinutes:number;bookedMinutes:number;aiMode:'openai'|'fallback';recommended:AutoCandidate|null;candidates:AutoCandidate[]};
type Location={id:string;name:string;city?:string|null};
type ActionService={id:string;name:string;is_active?:boolean|null;daily_action_enabled?:boolean|null;duration_minutes?:number|null;list_price?:number|null;base_price?:number|null};

export default function WallBoardDailyActionPage(){
 const[form,setForm]=useState<any>(emptyForm()),[campaigns,setCampaigns]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[frameKey,setFrameKey]=useState(0);
 const[autoDate,setAutoDate]=useState(today()),[autoLocation,setAutoLocation]=useState(''),[autoResult,setAutoResult]=useState<AutoResult|null>(null),[autoLoading,setAutoLoading]=useState(false),[autoError,setAutoError]=useState(''),[locations,setLocations]=useState<Location[]>([]);
 const[actionServices,setActionServices]=useState<ActionService[]>([]),[serviceFilter,setServiceFilter]=useState(''),[serviceSaving,setServiceSaving]=useState('');
 const active=useMemo(()=>campaigns.find(c=>c.status==='published'&&new Date(c.valid_from)<=new Date()&&new Date(c.valid_until)>=new Date())||null,[campaigns]);
 const filteredActionServices=useMemo(()=>{const q=serviceFilter.trim().toLowerCase();return actionServices.filter(s=>!q||s.name.toLowerCase().includes(q))},[actionServices,serviceFilter]);
 async function load(selectId?:string){setLoading(true);setError('');try{const r=await axios.get(API,auth());const rows=Array.isArray(r.data?.campaigns)?r.data.campaigns:[];setCampaigns(rows);if(selectId){const found=rows.find((x:any)=>String(x.id)===String(selectId));if(found)setFromCampaign(found)}}catch(e:any){setError(e?.response?.data?.message||e?.message||'A napi akciók betöltése nem sikerült.')}finally{setLoading(false)}}
 async function loadLocations(){try{const r=await axios.get(`${API_BASE}/locations`,auth());const rows=Array.isArray(r.data)?r.data:Array.isArray(r.data?.locations)?r.data.locations:[];setLocations(rows.map((x:any)=>({id:String(x.id),name:String(x.name||x.city||'Telephely'),city:x.city||null})))}catch{setLocations([])}}
 async function loadAuto(){setAutoLoading(true);setAutoError('');try{const r=await axios.get(`${AUTO}/recommendation`,{...auth(),params:{date:autoDate,location_id:autoLocation||undefined}});setAutoResult(r.data as AutoResult)}catch(e:any){setAutoResult(null);setAutoError(e?.response?.data?.message||e?.message||'Az automatikus napi akció javaslat nem tölthető be.')}finally{setAutoLoading(false)}}
 async function loadActionServices(){try{const r=await axios.get(`${API_BASE}/services?include_inactive=1`,auth());const rows=Array.isArray(r.data)?r.data:[];setActionServices(rows.map((x:any)=>({...x,id:String(x.id),name:String(x.name||'Szolgáltatás')})).sort((a:ActionService,b:ActionService)=>a.name.localeCompare(b.name,'hu')))}catch{setActionServices([])}}
 const initialLoadRef=useRef(load);
 const initialLoadAutoRef=useRef(loadAuto);
 useEffect(()=>{void initialLoadRef.current();void loadLocations();void(async()=>{await initialLoadAutoRef.current();await loadActionServices()})()},[]);
 function setFromCampaign(c:any){setForm({...c,valid_from:localDate(new Date(c.valid_from)),valid_until:localDate(new Date(c.valid_until)),channels:Array.isArray(c.channels)&&c.channels.length?c.channels:['app'],audience:c.audience||{type:'all'}});setMessage('');setError('')}
 function fresh(){setForm(emptyForm());setMessage('');setError('')}
 function payload(){return{name:form.name,headline:form.headline,description_html:form.description_html,image_url:form.image_url||null,cta_label:form.cta_label||'Foglalok',cta_url:form.cta_url||'/foglalas',discount_text:form.discount_text||null,valid_from:new Date(form.valid_from).toISOString(),valid_until:new Date(form.valid_until).toISOString(),channels:['app'],audience:{type:'all'}}}
 async function save(publish=false){if(!form.headline.trim()||!strip(form.description_html)){setError('A főcím és az akció leírása kötelező.');return}setLoading(true);setError('');setMessage('');try{let id=form.id;let saved;if(id){saved=(await axios.patch(`${API}/${id}`,payload(),auth())).data}else{saved=(await axios.post(API,payload(),auth())).data;id=saved.id}if(publish){await axios.post(`${API}/${id}/publish`,{},auth());setMessage('Az akció publikálva. A vendégapp/push és a WallBoard ugyanebből a kampányból frissül.')}else setMessage('Piszkozat mentve. Értesítés még nem került kiküldésre.');await load(id);setFrameKey(k=>k+1)}catch(e:any){setError(e?.response?.data?.message||e?.message||'A mentés nem sikerült.')}finally{setLoading(false)}}
 function imageFile(file?:File){if(!file)return;if(file.size>5*1024*1024){setError('A WallBoard kép legfeljebb 5 MB legyen.');return}const reader=new FileReader();reader.onload=()=>setForm((p:any)=>({...p,image_url:String(reader.result||'')}));reader.readAsDataURL(file)}
 function applyRecommendation(c:AutoCandidate){const base=emptyForm();const now=new Date();const start=autoDate===today()?localDate(now):`${autoDate}T09:00`;const end=`${autoDate}T23:59`;setForm({...base,name:`AI napi akció – ${autoDate} – ${c.name}`,headline:c.headline,description_html:c.description,discount_text:c.suggestedDiscountPct>0?`${c.suggestedDiscountPct}% kedvezmény`:'Kiemelt napi ajánlat',valid_from:start,valid_until:end,service_id:c.serviceId,auto_selector_meta:{score:c.score,reason:c.reason,location_id:autoLocation||null}});setMessage(`${c.name} betöltve a szerkesztőbe. A publikálás továbbra is kézi jóváhagyást igényel.`);setError('')}
 async function createAutoDraft(c?:AutoCandidate){const selected=c||autoResult?.recommended;if(!selected)return;setAutoLoading(true);setAutoError('');setMessage('');try{const r=await axios.post(`${AUTO}/create-draft`,{date:autoDate,location_id:autoLocation||undefined,service_id:selected.serviceId},auth());const campaign=r.data?.campaign;if(campaign?.id){await load(String(campaign.id));setMessage(`AI-támogatott piszkozat elkészült: ${selected.name}. Ellenőrizze, majd külön publikálja.`)}await loadAuto()}catch(e:any){setAutoError(e?.response?.data?.message||e?.message||'A napi akció piszkozat létrehozása nem sikerült.')}finally{setAutoLoading(false)}}
 async function toggleActionService(service:ActionService,enabled:boolean){setServiceSaving(service.id);setAutoError('');try{await axios.patch(`${AUTO}/service/${service.id}/eligibility`,{enabled},auth());setActionServices(prev=>prev.map(s=>s.id===service.id?{...s,daily_action_enabled:enabled}:s));await loadAuto()}catch(e:any){setAutoError(e?.response?.data?.message||e?.message||'A szolgáltatás napi akció jelölése nem menthető.')}finally{setServiceSaving('')}}
 const desc=strip(form.description_html)||'Írja be az akció rövid leírását…';
 return <main className="wbd-page">
  <header className="wbd-hero"><div><div className="wbd-kicker">MARKETING • TV / WALLBOARD</div><h1>WallBoard / TV napi akció</h1><p>Külön szerkesztő a szalon TV-k napi ajánlatához. A publikált kampány ugyanabból az adatból jelenik meg a vendégappban és a WallBoardon.</p></div><div className="wbd-head-actions"><button onClick={fresh}><Plus size={16}/>Új akció</button><button onClick={()=>load(form.id)} disabled={loading}><RefreshCw size={16}/>Frissítés</button><a href={WALLBOARD} target="_blank" rel="noreferrer"><ExternalLink size={16}/>TV teljes képernyő</a></div></header>
  {error&&<div className="wbd-error">{error}</div>}{message&&<div className="wbd-ok"><CheckCircle2 size={17}/>{message}</div>}
  <section className="wbd-status"><article><MonitorPlay/><div><small>Aktív TV-akció</small><b>{active?.headline||'Nincs aktív publikált akció'}</b></div></article><article><Smartphone/><div><small>Vendégapp csatorna</small><b>Összekapcsolva</b></div></article><article><Send/><div><small>Publikálás</small><b>{form.status==='published'?'Publikált':'Piszkozat'}</b></div></article></section>

  <section className="wbd-ai">
   <div className="wbd-title"><div><h2><Sparkles size={20}/> AI-támogatott automatikus napi akció</h2><p>A rendszer kizárólag az aktív, <b>„Napi akciózásban szerepel”</b> jelölésű szolgáltatásokat vizsgálja. A rangsort a foglaltság, a 28 napos szolgáltatási trend és a közelmúltbeli akciók adják.</p></div><span>{autoResult?.aiMode==='openai'?'AI szövegjavaslat':'Biztonságos alapjavaslat'}</span></div>
   <div className="wbd-ai-controls"><label>Nap<input type="date" value={autoDate} min={today()} onChange={e=>setAutoDate(e.target.value)}/></label><label>Telephely<select value={autoLocation} onChange={e=>setAutoLocation(e.target.value)}><option value="">Összes telephely</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}{l.city?` – ${l.city}`:''}</option>)}</select></label><button type="button" onClick={loadAuto} disabled={autoLoading}><Sparkles size={16}/>{autoLoading?'Elemzés…':'Javaslat készítése'}</button><a href="/services">Teljes szolgáltatáslista</a></div>
   <details className="wbd-ai-services"><summary><span>„Napi akciózásban szerepel” szolgáltatások</span><b>{actionServices.filter(s=>s.daily_action_enabled&&s.is_active!==false).length} engedélyezve</b></summary><div className="wbd-ai-services-body"><input className="wbd-ai-service-search" placeholder="Szolgáltatás keresése…" value={serviceFilter} onChange={e=>setServiceFilter(e.target.value)}/><div className="wbd-ai-service-list">{filteredActionServices.slice(0,80).map(s=><label key={s.id} className={s.is_active===false?'inactive':''}><input type="checkbox" checked={!!s.daily_action_enabled} disabled={serviceSaving===s.id||s.is_active===false} onChange={e=>toggleActionService(s,e.target.checked)}/><span><b>{s.name}</b><small>{s.is_active===false?'inaktív szolgáltatás':s.daily_action_enabled?'részt vesz az automatikus napi akciózásban':'nem szerepel az automatikus napi akciózásban'}</small></span></label>)}</div>{filteredActionServices.length>80&&<p className="wbd-ai-service-more">Az első 80 találat látható; szűkítse a keresést.</p>}</div></details>
   {autoError&&<div className="wbd-error">{autoError}</div>}
   {autoResult&&<div className="wbd-ai-metrics"><div><small>Telephely foglaltság</small><b>{autoResult.scheduledMinutes>0?`${autoResult.locationOccupancyPct}%`:'nincs kapacitásadat'}</b><span>{autoResult.bookedMinutes.toLocaleString('hu-HU')} / {autoResult.scheduledMinutes.toLocaleString('hu-HU')} perc</span></div><div><small>Értékelt szolgáltatások</small><b>{autoResult.candidates.length}</b><span>csak engedélyezett szolgáltatás</span></div><div><small>AI mód</small><b>{autoResult.aiMode==='openai'?'OpenAI támogatás':'Determinista tartalék mód'}</b><span>a kiválasztási szabályok mindig ellenőrizhetők</span></div></div>}
   {autoResult?.recommended?<div className="wbd-ai-recommended"><div className="wbd-ai-score"><strong>{Math.round(autoResult.recommended.score)}</strong><span>pont</span></div><div className="wbd-ai-copy"><small>MAI ELSŐ SZÁMÚ JAVASLAT</small><h3>{autoResult.recommended.name}</h3><p>{autoResult.recommended.reason}</p><div className="wbd-ai-facts"><span>Ma: <b>{autoResult.recommended.bookingsToday}</b> foglalás</span><span>28 napos átlag: <b>{autoResult.recommended.avgDailyBookings28d}</b>/nap</span><span>Trendhiány: <b>{autoResult.recommended.demandGapPct}%</b></span><span>Javasolt kedvezmény: <b>{autoResult.recommended.suggestedDiscountPct}%</b></span></div><div className="wbd-ai-generated"><b>{autoResult.recommended.headline}</b><span>{autoResult.recommended.description}</span></div></div><div className="wbd-ai-actions"><button type="button" onClick={()=>applyRecommendation(autoResult.recommended!)}>Betöltés a szerkesztőbe</button><button className="primary" type="button" onClick={()=>createAutoDraft()} disabled={autoLoading}>AI piszkozat létrehozása</button></div></div>:autoResult&&!autoLoading?<div className="wbd-ai-empty">Nincs napi akcióra engedélyezett aktív szolgáltatás. Nyissa le fent a szolgáltatás-jelöléseket, és kapcsolja be a kívánt tételeknél a „Napi akciózásban szerepel” jelölést.</div>:null}
   {autoResult?.candidates&&autoResult.candidates.length>1?<div className="wbd-ai-alternatives"><h3>További jelöltek</h3><div>{autoResult.candidates.slice(1,5).map(c=><button key={c.serviceId} onClick={()=>applyRecommendation(c)}><b>{c.name}</b><span>{Math.round(c.score)} pont • ma {c.bookingsToday} • átlag {c.avgDailyBookings28d}/nap</span></button>)}</div></div>:null}
   <p className="wbd-ai-note">Az AI nem publikál automatikusan és nem írhatja felül a „Napi akciózásban szerepel” jogosultsági jelölést. A végső kedvezmény, szöveg és publikálás vezetői döntés.</p>
  </section>

  <div className="wbd-workspace">
   <section className="wbd-editor"><div className="wbd-title"><div><h2>Akció szerkesztése</h2><p>Mentés közben nincs kiküldés; csak a Publikálás indítja az app/push folyamatot.</p></div><span>{form.id?'Meglévő kampány':'Új kampány'}</span></div>
    <label>Kampány belső neve<input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>
    <label className="wide">TV főcím<input maxLength={180} value={form.headline||''} onChange={e=>setForm({...form,headline:e.target.value})} placeholder="Pl. Ma 20% kedvezmény a Hydrafacial kezelésre"/></label>
    <label className="wide">Leírás<textarea rows={5} value={form.description_html||''} onChange={e=>setForm({...form,description_html:e.target.value})} placeholder="Rövid, jól olvasható szöveg a TV képernyőre."/></label>
    <label>Kedvezmény / kiemelt szöveg<input value={form.discount_text||''} onChange={e=>setForm({...form,discount_text:e.target.value})} placeholder="-20% • CSAK MA"/></label>
    <label>CTA felirat<input value={form.cta_label||''} onChange={e=>setForm({...form,cta_label:e.target.value})}/></label>
    <label>CTA cél URL<input value={form.cta_url||''} onChange={e=>setForm({...form,cta_url:e.target.value})}/></label>
    <label>Kezdete<input type="datetime-local" value={form.valid_from||''} onChange={e=>setForm({...form,valid_from:e.target.value})}/></label>
    <label>Vége<input type="datetime-local" value={form.valid_until||''} onChange={e=>setForm({...form,valid_until:e.target.value})}/></label>
    <div className="wbd-image wide"><label>Kép URL<input value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://… vagy töltsön fel képet"/></label><label className="wbd-upload"><ImagePlus size={16}/>Kép feltöltése<input type="file" accept="image/*" hidden onChange={e=>imageFile(e.target.files?.[0])}/></label>{form.image_url&&<button type="button" onClick={()=>setForm({...form,image_url:''})}><Undo2 size={15}/>Kép törlése</button>}</div>
    <div className="wbd-save wide"><button type="button" onClick={()=>save(false)} disabled={loading}><Save size={16}/>{loading?'Mentés…':'Piszkozat mentése'}</button><button className="publish" type="button" onClick={()=>save(true)} disabled={loading}><Send size={16}/>Mentés és publikálás</button></div>
   </section>
   <section className="wbd-preview"><div className="wbd-title"><div><h2>Azonnali TV előnézet</h2><p>A szerkesztés közben azonnal változik.</p></div><span>16:9</span></div><div className={`wbd-screen ${form.image_url?'with-image':''}`}>{form.image_url&&<div className="wbd-screen-image" style={{backgroundImage:`url(${JSON.stringify(form.image_url).slice(1,-1)})`}}/>}<div className="wbd-screen-copy"><small>KLEOPÁTRA • NAPI AKCIÓ</small><h3>{form.headline||'A napi akció főcíme'}</h3><p>{desc}</p>{form.discount_text&&<strong>{form.discount_text}</strong>}</div></div><div className="wbd-links"><a href={`${WALLBOARD}/daily-action.json`} target="_blank" rel="noreferrer">JSON feed</a><a href={`${WALLBOARD}/daily-action.xml`} target="_blank" rel="noreferrer">XML feed</a></div>
   </section>
  </div>
  <section className="wbd-live"><div className="wbd-title"><div><h2>Éles WallBoard előnézet</h2><p>A jelenleg publikált, időben aktív akció látható. Publikálás után frissítse az előnézetet.</p></div><button onClick={()=>setFrameKey(k=>k+1)}><RefreshCw size={15}/>Előnézet frissítése</button></div><div className="wbd-live-frame"><iframe key={frameKey} src={`${WALLBOARD}?preview=${frameKey}`} title="Éles Kleopátra WallBoard"/></div></section>
  <section className="wbd-history"><div className="wbd-title"><div><h2>Korábbi és ütemezett akciók</h2><p>Kattintson egy kampányra a szerkesztéshez.</p></div></div><div className="wbd-list">{campaigns.map(c=><button key={c.id} onClick={()=>setFromCampaign(c)} className={String(form.id)===String(c.id)?'active':''}><div><b>{c.headline}</b><span>{c.name}</span><small>{new Date(c.valid_from).toLocaleString('hu-HU')} – {new Date(c.valid_until).toLocaleString('hu-HU')}</small></div><em className={c.status}>{c.status}</em></button>)}</div></section>
 </main>
}