import React, { useEffect, useMemo, useState } from "react";
import axios from "axios";
import "./WebsiteAdminPage.css";

const API_BASE = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1" ? "http://localhost:5000/api" : "https://kleoszalon-api-1.onrender.com/api";
const LIVE_SITE = "https://weblap-o3g6.onrender.com";

type PageKey = "salons"|"services"|"prices"|"loyalty"|"franchise"|"career"|"training"|"about"|"contact";
type PageContent = {eyebrow:string;titlePrefix:string;titleHighlight:string;titleSuffix:string;lead:string;imageUrl:string;sectionTitle:string;sectionLead:string};
const labels:Record<PageKey,{name:string;path:string}> = {
  salons:{name:"Szalonok",path:"/salons"}, services:{name:"Szolgáltatások",path:"/services"}, prices:{name:"Árlista",path:"/prices"}, loyalty:{name:"Hűségprogram",path:"/loyalty"}, franchise:{name:"Franchise",path:"/franchise"}, career:{name:"Karrier",path:"/career"}, training:{name:"Oktatás",path:"/training"}, about:{name:"Rólunk",path:"/about"}, contact:{name:"Kapcsolat",path:"/contact"}
};
const defaults:Record<PageKey,PageContent> = {
  salons:{eyebrow:"Szalonjaink",titlePrefix:"Jelenleg ",titleHighlight:"7 helyszínen",titleSuffix:" várunk",lead:"Budapesten és vidéki városokban is megtalálsz bennünket. Foglalhatsz online, de szalonjaink működésének fontos része a rugalmas, akár bejelentkezés nélküli vendégfogadás is.",imageUrl:"/images/szalonok.jpg",sectionTitle:"Válaszd ki a hozzád legközelebbi szalont",sectionLead:"A szalon adatlapján megtalálod az elérhető szolgáltatásokat, szakembereket és a foglaláshoz szükséges információkat."},
  services:{eyebrow:"Szolgáltatások",titlePrefix:"Minden, ami szépség – ",titleHighlight:"egy helyen",titleSuffix:"",lead:"A Kleopátra Szépségszalonok célja, hogy több szépségápolási területet egy helyen érj el, rugalmas időpontfoglalással és szalononként összeállított szolgáltatáskínálattal.",imageUrl:"/images/szolgaltatasok.jpg",sectionTitle:"Válaszd ki, mire van szükséged",sectionLead:"A pontos kínálat és az elérhető szakemberek szalononként eltérhetnek; a foglalási rendszer mindig az aktuális lehetőségeket mutatja."},
  prices:{eyebrow:"Árlista",titlePrefix:"Aktuális szolgáltatások és ",titleHighlight:"árak",titleSuffix:"",lead:"Válaszd ki a szalont, és nézd meg az ott elérhető szolgáltatásokat, időtartamokat és árakat.",imageUrl:"/images/szolgaltatasok.jpg",sectionTitle:"Árlista szalononként",sectionLead:"Az árak forintban értendők; az időszakos ajánlatok feltételei eltérhetnek."},
  loyalty:{eyebrow:"Hűségprogram",titlePrefix:"Több előny a ",titleHighlight:"visszatérő vendégeknek",titleSuffix:"",lead:"A Kleopátra hűségvilága kártyákat, kuponokat, bérleteket, vendégszámlát és időszakos ajánlatokat fog össze.",imageUrl:"/images/husegprogram.png",sectionTitle:"Egy rendszerben a kedvezmények és vendégelőnyök",sectionLead:"Az egyes kedvezmények feltételei kampányonként eltérhetnek."},
  franchise:{eyebrow:"Franchise",titlePrefix:"Építs szépségszalont ",titleHighlight:"biztosabb rendszerrel",titleSuffix:"",lead:"A Kleopátra franchise felépített márka- és működési hátteret kínál partnereinek.",imageUrl:"/images/franchise.jpg",sectionTitle:"Négy tipikus belépési helyzet",sectionLead:"A program befektetőknek, karrierváltóknak, szakembereknek és működő szalonok tulajdonosainak is szólhat."},
  career:{eyebrow:"Kleo Team Karrier",titlePrefix:"A te sikered a ",titleHighlight:"mi sikerünk is",titleSuffix:"",lead:"Olyan szakembereket és ügyfélközpontú kollégákat keresünk, akik hosszú távon szeretnének fejlődni.",imageUrl:"/images/rolunk.jpg",sectionTitle:"Folyamatosan bővülő csapat",sectionLead:"A konkrét nyitott helyek szalononként változhatnak."},
  training:{eyebrow:"KLEO ACADEMY",titlePrefix:"Tanulj, fejlődj, építs ",titleHighlight:"szépségipari karriert",titleSuffix:"",lead:"A KLEO ACADEMY célja a gyakorlatban használható tudás átadása.",imageUrl:"/images/oktatas.jpg",sectionTitle:"Gyakorlatorientált szakmai tanfolyamok",sectionLead:"A pontos indulási időpontok és feltételek képzésenként változhatnak."},
  about:{eyebrow:"Rólunk",titlePrefix:"Több mint szalon: ",titleHighlight:"Kleopátra élmény",titleSuffix:"",lead:"Több mint három évtizede azon dolgozunk, hogy a vendégek minél több szépségápolási szolgáltatást érjenek el egy helyen.",imageUrl:"/images/rolunk.jpg",sectionTitle:"Egyszerűbbé tenni a szépségápolást",sectionLead:"Olyan szépségszalon-hálózatot építünk, ahol a vendég több szolgáltatáshoz és szakemberhez fér hozzá egy helyen."},
  contact:{eyebrow:"Kapcsolat",titlePrefix:"Miben segíthetünk ",titleHighlight:"Neked?",titleSuffix:"",lead:"Időpontfoglalás, szolgáltatás, franchise, karrier, oktatás vagy vendégvisszajelzés – válaszd ki a témát.",imageUrl:"/images/home.png",sectionTitle:"Lépj velünk kapcsolatba",sectionLead:"Add meg a legfontosabb adatokat és válaszd ki, milyen témában keresel bennünket."}
};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));

function Field({label,value,onChange,textarea=false}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean}){
  return <div className="wa-field"><label>{label}</label>{textarea?<textarea value={value||""} onChange={e=>onChange(e.target.value)}/>:<input value={value||""} onChange={e=>onChange(e.target.value)}/>}</div>;
}

export default function WebsitePagesAdminPage(){
  const [config,setConfig]=useState<any>(null); const [selected,setSelected]=useState<PageKey>("salons"); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const token=localStorage.getItem("kleo_token")||localStorage.getItem("token");
  const http=useMemo(()=>axios.create({baseURL:API_BASE,withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}),[token]);
  useEffect(()=>{let alive=true;http.get("/admin/website/config").then(r=>{if(!alive)return;const next=clone(r.data.draft||{});next.pages=next.pages||{};(Object.keys(defaults) as PageKey[]).forEach(k=>{next.pages[k]={...defaults[k],...(next.pages[k]||{})}});setConfig(next)}).catch((e:any)=>setError(e?.response?.data?.error||"A weboldal tartalma nem tölthető be.")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[http]);
  const current:PageContent=config?.pages?.[selected]||defaults[selected];
  const setField=(field:keyof PageContent,value:string)=>setConfig((prev:any)=>{const next=clone(prev);next.pages=next.pages||{};next.pages[selected]={...defaults[selected],...(next.pages[selected]||{}),[field]:value};return next});
  async function save(publish=false){if(!config)return;setSaving(true);setError("");setMessage("");try{await http.put("/admin/website/config",{config});if(publish)await http.post("/admin/website/publish");setMessage(publish?"A tartalom elmentve és publikálva.":"A tartalom piszkozatként elmentve.")}catch(e:any){setError(e?.response?.data?.error||"A mentés nem sikerült.")}finally{setSaving(false)}}
  if(loading)return <div className="website-admin"><p>Weboldal tartalom betöltése…</p></div>;
  if(!config)return <div className="website-admin"><div className="website-admin__status website-admin__status--error">{error||"Nincs konfiguráció."}</div></div>;
  return <div className="website-admin">
    <div className="website-admin__head"><div><p className="website-admin__eyebrow">VIR · WEBOLDAL · TARTALOM</p><h1>Publikus oldalak szerkesztése</h1><p>Itt a fő publikus aloldalak címe, kiemelt szövege, bevezetője, képe és első tartalmi blokkja módosítható. A módosítás csak publikálás után jelenik meg az éles oldalon.</p></div><div className="website-admin__actions"><button className="wa-btn" onClick={()=>window.open(`${LIVE_SITE}${labels[selected].path}`,"_blank")}>Oldal megnyitása</button><button className="wa-btn wa-btn--gold" disabled={saving} onClick={()=>save(false)}>Piszkozat mentése</button><button className="wa-btn wa-btn--primary" disabled={saving} onClick={()=>save(true)}>Mentés és publikálás</button></div></div>
    {(message||error)&&<div className={"website-admin__status"+(error?" website-admin__status--error":"")}>{error||message}</div>}
    <div className="website-admin__layout"><section className="website-admin__panel"><div className="website-admin__tabs">{(Object.keys(labels) as PageKey[]).map(k=><button key={k} className={"website-admin__tab"+(selected===k?" is-active":"")} onClick={()=>setSelected(k)}>{labels[k].name}</button>)}</div><div className="website-admin__form"><div className="website-admin__section"><h2>{labels[selected].name} – kiemelt tartalom</h2><div className="wa-grid"><Field label="Felső felirat" value={current.eyebrow} onChange={v=>setField("eyebrow",v)}/><Field label="Kép URL" value={current.imageUrl} onChange={v=>setField("imageUrl",v)}/><Field label="Cím eleje" value={current.titlePrefix} onChange={v=>setField("titlePrefix",v)}/><Field label="Kiemelt címrész" value={current.titleHighlight} onChange={v=>setField("titleHighlight",v)}/><Field label="Cím vége" value={current.titleSuffix} onChange={v=>setField("titleSuffix",v)}/><div className="wa-field wa-field--full"><Field label="Bevezető szöveg" value={current.lead} onChange={v=>setField("lead",v)} textarea/></div><div className="wa-field wa-field--full"><Field label="Első tartalmi blokk címe" value={current.sectionTitle} onChange={v=>setField("sectionTitle",v)}/></div><div className="wa-field wa-field--full"><Field label="Első tartalmi blokk bevezetője" value={current.sectionLead} onChange={v=>setField("sectionLead",v)} textarea/></div></div></div></div></section>
      <aside className="website-admin__preview"><div className="wa-preview" style={{borderRadius:18}}><div className="wa-preview__hero"><small>{current.eyebrow}</small><h2>{current.titlePrefix}<span>{current.titleHighlight}</span>{current.titleSuffix}</h2><p>{current.lead}</p></div><div className="wa-preview__section"><b>{current.sectionTitle}</b><p>{current.sectionLead}</p></div></div><p className="wa-note">Ez tartalmi előnézet. A teljes oldal elrendezését az „Oldal megnyitása” gombbal ellenőrizd.</p></aside>
    </div>
  </div>;
}
