import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ArrowLeft,Archive,Building2,CheckCircle2,ClipboardCheck,CreditCard,LockKeyhole,Minus,PackageCheck,PackagePlus,Play,Plus,RefreshCw,Save,Search,Trash2,UserCheck,UserRound,Users,XCircle}from'lucide-react';
import{useNavigate,useParams}from'react-router-dom';
import{apiFetch}from'../utils/api';
import WorkOrderGuestContextPanel from'./workorders/WorkOrderGuestContextPanel';
import WorkOrderLoyaltyPanel,{LoyaltySelection}from'./workorders/WorkOrderLoyaltyPanel';
import WorkOrderItemPickerModal,{PickerProduct,PickerService}from'./workorders/WorkOrderItemPickerModal';
import WorkOrderReviewPanel from'./workorders/WorkOrderReviewPanel';
import WorkOrderPaymentPanel,{PaymentDraft,PaymentMethod}from'./workorders/WorkOrderPaymentPanel';
import WorkOrderClosePanel from'./workorders/WorkOrderClosePanel';
import type{WorkOrderMaterial}from'./workorders/WorkOrderMaterialsPanel';
import'./WorkOrderDetail.css';

type WorkOrderItem={id:string;item_type?:string;service_id?:string|null;product_id?:string|null;item_name?:string;quantity?:number|string;unit_price?:number|string;discount_amount?:number|string;line_total?:number|string;duration_minutes?:number|string};
type Payment={id:string;payment_method?:string;amount?:number|string;paid_at?:string;note?:string};
type WorkOrder={id:string;work_order_number?:string;title?:string;notes?:string;status?:string;created_at?:string;updated_at?:string;started_at?:string;completed_at?:string;cancelled_at?:string;locked_at?:string|null;locked_reason?:string|null;archived_at?:string|null;archive_hash?:string|null;location_id?:string|null;location_name?:string|null;client_id?:string|null;client_name?:string|null;client_phone?:string|null;client_email?:string|null;employee_id?:string|null;employee_name?:string|null;fully_paid?:boolean;note_for_another_visitor?:boolean;can_edit?:boolean;items?:WorkOrderItem[];payments?:Payment[];total_gross?:number|string;gross_total?:number|string;total?:number|string;payment_status?:string;financial_closed_at?:string|null;financial_closed_by?:string|null;amount_due?:number|string;amount_paid?:number|string;discount_amount?:number|string;tip_amount?:number|string;invoice_status?:string};
type Draft={title:string;notes:string;employee_id:string;client_id:string;client_name:string;client_phone:string;client_email:string;note_for_another_visitor:boolean};
type CatalogItem={id:string;name:string;price?:number|string|null;duration_minutes?:number|string|null;category_name?:string|null;unit?:string|null;available_stock?:number|string|null;service_type_id?:string|null;service_type_name?:string|null;product_group_id?:string|null;product_category_id?:string|null;brand?:string|null;line_name?:string|null;is_retail?:boolean|null;is_service_material?:boolean|null};
type Catalog={services:CatalogItem[];products:CatalogItem[]};
type Employee={id:string;full_name?:string|null};
type Client={id:string;name:string;phone?:string|null;email?:string|null};
type EditorOptions={scope?:{is_admin?:boolean;location_id?:string|null};location?:{id:string;name:string}|null;locations?:Array<{id:string;name:string}>;employees:Employee[];clients:Client[];services:CatalogItem[];products:CatalogItem[]};
type ArchiveData={id?:string;work_order_id?:string;work_order_number?:string;archived_at?:string;terminal_status?:string;snapshot?:unknown;snapshot_hash?:string};
type ItemEdit={quantity:string;discount:string};

const statusHu=(s?:string)=>({waiting:'Új / várakozik',arrived:'Megérkezett',in_progress:'Folyamatban',completed:'Lezárt',cancelled:'Lemondott',no_show:'Nem jelent meg'}as Record<string,string>)[s||'']||s||'—';
const paymentHu=(s?:string)=>({unpaid:'Fizetendő',partial:'Részben fizetve',paid:'Fizetve'}as Record<string,string>)[s||'']||s||'Fizetendő';
const paymentMethodHu=(s?:string)=>({cash:'Készpénz',card:'Bankkártya',transfer:'Átutalás',voucher:'Utalvány',other:'Egyéb'}as Record<string,string>)[String(s||'').toLowerCase()]||s||'—';
const money=(v:unknown)=>`${Number(v||0).toLocaleString('hu-HU',{maximumFractionDigits:0})} Ft`;
const dateTime=(v?:string|null)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const emptyDraft:Draft={title:'',notes:'',employee_id:'',client_id:'',client_name:'',client_phone:'',client_email:'',note_for_another_visitor:false};
const emptyLoyalty:LoyaltySelection={walletAmount:0,pointsToSpend:0,couponCode:'',couponDiscount:0,voucherCode:'',voucherAmount:0,estimatedPayable:0,passUsages:[]};
const blankPayment=(id=1):PaymentDraft=>({id,payment_method:'cash',amount:'',note:'',destination:'Szaloni készpénzpénztár'});
const itemEditMap=(items?:WorkOrderItem[])=>Object.fromEntries((items||[]).map(x=>[x.id,{quantity:String(Number(x.quantity||1)),discount:String(Number(x.discount_amount||0))}])) as Record<string,ItemEdit>;

export default function WorkOrderDetail(){
 const{id}=useParams();const navigate=useNavigate();
 const[data,setData]=useState<WorkOrder|null>(null);const[catalog,setCatalog]=useState<Catalog>({services:[],products:[]});const[editor,setEditor]=useState<EditorOptions|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[itemEdits,setItemEdits]=useState<Record<string,ItemEdit>>({});
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[actionSaving,setActionSaving]=useState(false);const[itemSaving,setItemSaving]=useState(false);const[paymentSaving,setPaymentSaving]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const[itemType,setItemType]=useState<'service'|'product'>('service');const[itemId,setItemId]=useState('');const[itemQty,setItemQty]=useState(1);const[itemDiscount,setItemDiscount]=useState(0);const[itemPickerOpen,setItemPickerOpen]=useState(false);const[clientSearch,setClientSearch]=useState('');
 const[loyalty,setLoyalty]=useState<LoyaltySelection>(emptyLoyalty);const[manualDiscount,setManualDiscount]=useState(0);const[tip,setTip]=useState(0);const[invoiceStatus,setInvoiceStatus]=useState('not_requested');const[newPayments,setNewPayments]=useState<PaymentDraft[]>([blankPayment()]);const[reviewReady,setReviewReady]=useState(false);
 const[archive,setArchive]=useState<ArchiveData|null>(null);const[archiveLoading,setArchiveLoading]=useState(false);

 const loadEditor=useCallback(async(locationId:string,employeeId:string,fallback:Catalog)=>{try{const p=new URLSearchParams();if(locationId)p.set('location_id',locationId);if(employeeId)p.set('employee_id',employeeId);const o=await apiFetch<EditorOptions>(`/api/transactions/workorder-editor/options?${p.toString()}`);setEditor(o);setCatalog({services:Array.isArray(o.services)?o.services:fallback.services,products:Array.isArray(o.products)?o.products:fallback.products});return o}catch{setEditor(null);setCatalog(fallback);return null}},[]);
 const load=useCallback(async(resetDraft=true)=>{if(!id)return;setLoading(true);if(resetDraft)setError('');try{const[result,cat]=await Promise.all([apiFetch<WorkOrder>(`/api/workorders/${encodeURIComponent(id)}`),apiFetch<Catalog>(`/api/workorders/${encodeURIComponent(id)}/catalog`).catch(()=>({services:[],products:[]}))]);setData(result);setCatalog(cat);setItemEdits(itemEditMap(result.items));if(resetDraft){setDraft({title:String(result.title||''),notes:String(result.notes||''),employee_id:String(result.employee_id||''),client_id:String(result.client_id||''),client_name:String(result.client_name||''),client_phone:String(result.client_phone||''),client_email:String(result.client_email||''),note_for_another_visitor:Boolean(result.note_for_another_visitor)});setClientSearch(String(result.client_name||''));setManualDiscount(Number(result.discount_amount||0));setTip(Number(result.tip_amount||0));setInvoiceStatus(String(result.invoice_status||'not_requested'));setNewPayments([blankPayment()]);setLoyalty(emptyLoyalty)}if(result.can_edit&&result.location_id&&!result.locked_at&&!result.archived_at&&!result.financial_closed_at)await loadEditor(String(result.location_id),String(result.employee_id||''),cat);else setEditor(null)}catch(e:any){setError(e?.message||'A munkalap nem tölthető be.')}finally{setLoading(false)}},[id,loadEditor]);
 useEffect(()=>{void load(true)},[load]);

 const locked=Boolean(data?.locked_at||data?.archived_at);const financiallyClosed=Boolean(data?.financial_closed_at);const canEdit=Boolean(data?.can_edit)&&!locked;const canEditBase=canEdit&&!financiallyClosed;const canEditItems=canEditBase;const canRecordPayments=canEditBase&&data?.status==='in_progress';
 const itemTotal=useMemo(()=>Number(data?.items?.reduce((sum,item)=>sum+Number(item.line_total||0),0)||data?.total_gross||data?.gross_total||data?.total||0),[data]);
 const paidTotal=useMemo(()=>Number(data?.payments?.reduce((sum,p)=>sum+Number(p.amount||0),0)||data?.amount_paid||0),[data]);
 const serviceItems=useMemo(()=>(data?.items||[]).filter(x=>x.item_type==='service'),[data?.items]);const productItems=useMemo(()=>(data?.items||[]).filter(x=>x.item_type==='product'),[data?.items]);
 const selectedServices=useMemo(()=>serviceItems.map(x=>({id:String(x.service_id||x.id),name:String(x.item_name||'Szolgáltatás'),price:Number(x.unit_price||0),duration_minutes:Number(x.duration_minutes||0)})),[serviceItems]);
 const materials=useMemo<WorkOrderMaterial[]>(()=>productItems.map(x=>{const meta=(editor?.products||[]).find(p=>String(p.id)===String(x.product_id||''));return{productId:String(x.product_id||x.id),name:String(x.item_name||'Termék'),quantity:Number(x.quantity||0),unit:meta?.unit||'db',unitPrice:Number(x.unit_price||0),availableStock:meta?.available_stock==null?null:Number(meta.available_stock)}}),[productItems,editor?.products]);
 const serviceIds=useMemo(()=>Array.from(new Set(serviceItems.map(x=>String(x.service_id||'')).filter(Boolean))),[serviceItems]);const productIds=useMemo(()=>Array.from(new Set(productItems.map(x=>String(x.product_id||'')).filter(Boolean))),[productItems]);
 const passCredit=useMemo(()=>loyalty.passUsages.reduce((n,u)=>{const item=serviceItems.find(x=>String(x.service_id||'')===String(u.service_id));return n+Number(item?.unit_price||0)*Math.max(1,Number(u.quantity||1))},0),[loyalty.passUsages,serviceItems]);
 const couponDiscount=Math.max(0,Number(loyalty.couponDiscount||0));const pointsDiscount=Math.max(0,Number(loyalty.pointsToSpend||0));const loyaltyDiscount=Math.min(itemTotal,Math.max(0,couponDiscount+passCredit+pointsDiscount));const loyaltyTender=Math.max(0,Number(loyalty.walletAmount||0))+Math.max(0,Number(loyalty.voucherAmount||0));
 const draftPaid=useMemo(()=>newPayments.reduce((n,p)=>n+Math.max(0,Number(p.amount||0)),0),[newPayments]);const calculatedDue=Math.max(0,itemTotal-Math.max(0,manualDiscount)-loyaltyDiscount+Math.max(0,tip));const amountDue=financiallyClosed?Number(data?.amount_due??calculatedDue):calculatedDue;const remaining=Math.max(0,amountDue-paidTotal);const paymentDifference=Math.round((paidTotal+loyaltyTender+draftPaid-amountDue)*100)/100;const paid=String(data?.payment_status||'')==='paid'||Boolean(data?.fully_paid)||paidTotal+.009>=amountDue;
 const actualLoyaltyUsage=Boolean(loyalty.couponCode||loyalty.voucherCode||loyalty.walletAmount||loyalty.pointsToSpend||loyalty.passUsages.length);const useLoyaltySettlement=Boolean(loyalty.accountId||actualLoyaltyUsage);const loyaltyUsageBlocked=paidTotal>0&&!financiallyClosed;const paymentReady=canRecordPayments&&reviewReady&&Math.abs(paymentDifference)<.01;const closeReady=!locked&&(financiallyClosed?Boolean(paid&&data?.status==='in_progress'):paymentReady);
 const availableItems=itemType==='service'?catalog.services:catalog.products;const selectedItem=availableItems.find(x=>String(x.id)===itemId)||null;const clients=editor?.clients||[];const employees=editor?.employees||[];
 const filteredClients=useMemo(()=>{const q=clientSearch.trim().toLocaleLowerCase('hu-HU');return q?clients.filter(c=>[c.name,c.phone,c.email].some(v=>String(v||'').toLocaleLowerCase('hu-HU').includes(q))):clients},[clients,clientSearch]);
 const handleLoyaltyChange=useCallback((value:LoyaltySelection)=>setLoyalty(value),[]);

 const clearMessages=()=>{setError('');setNotice('')};
 const save=async()=>{if(!id||!canEditBase)return;if(!draft.title.trim()){setError('A munkalap címe nem lehet üres.');return}setSaving(true);clearMessages();try{await apiFetch(`/api/workorders/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,title:draft.title.trim(),employee_id:draft.employee_id||null,client_id:draft.client_id||null})});setNotice('A munkalap alapadatai és vendégadatai mentve.');await load(false)}catch(e:any){setError(e?.message||'A munkalap módosítása nem sikerült.')}finally{setSaving(false)}};
 const changeEmployee=async(employeeId:string)=>{setDraft(v=>({...v,employee_id:employeeId}));if(data?.location_id)await loadEditor(String(data.location_id),employeeId,catalog)};
 const selectClient=(clientId:string)=>{const c=clients.find(x=>String(x.id)===String(clientId));if(c){setDraft(v=>({...v,client_id:String(c.id),client_name:c.name||'',client_phone:c.phone||'',client_email:c.email||''}));setClientSearch(c.name||'')}else setDraft(v=>({...v,client_id:'',client_name:'',client_phone:'',client_email:''}))};
 const handleCustomerCreated=(client:Client)=>{setEditor(o=>o?{...o,clients:[client,...(o.clients||[]).filter(x=>String(x.id)!==String(client.id))]}:o);setDraft(v=>({...v,client_id:String(client.id),client_name:client.name||'',client_phone:client.phone||'',client_email:client.email||''}));setClientSearch(client.name||'')};
 const changeStatus=async(status:string)=>{if(!id||!canEdit||status===data?.status)return;setActionSaving(true);clearMessages();try{await apiFetch(`/api/workorders/${encodeURIComponent(id)}/lifecycle`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setNotice(`Munkalap állapota: ${statusHu(status)}.`);await load(false)}catch(e:any){setError(e?.message||'Az állapotváltás nem sikerült.')}finally{setActionSaving(false)}};

 const addItemPayload=async(kind:'service'|'product',refId:string,quantity:number,discount:number,showNotice=true)=>{if(!id||!canEditItems||!refId)return;setItemSaving(true);clearMessages();try{await apiFetch(`/api/workorders/${encodeURIComponent(id)}/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_type:kind,item_id:refId,quantity,discount_amount:discount})});if(showNotice)setNotice('A tétel hozzáadva a munkalaphoz.');await load(false)}catch(e:any){setError(e?.message||'A tétel hozzáadása nem sikerült.')}finally{setItemSaving(false)}};
 const addItem=async()=>{if(!itemId)return;await addItemPayload(itemType,itemId,Number(itemQty||1),Number(itemDiscount||0));setItemId('');setItemQty(1);setItemDiscount(0)};
 const removeItem=async(item:WorkOrderItem,confirm=true)=>{if(!id||!canEditItems)return;if(confirm&&!window.confirm(`Eltávolítja a munkalapról: ${item.item_name||'tétel'}?`))return;setItemSaving(true);clearMessages();try{await apiFetch(`/api/workorders/${encodeURIComponent(id)}/items/${encodeURIComponent(item.id)}`,{method:'DELETE'});setNotice('A tétel eltávolítva.');await load(false)}catch(e:any){setError(e?.message||'A tétel törlése nem sikerült.')}finally{setItemSaving(false)}};
 const updateItem=async(item:WorkOrderItem,changes:{quantity?:number;discount_amount?:number})=>{if(!id||!canEditItems)return;setItemSaving(true);clearMessages();try{await apiFetch(`/api/workorders/${encodeURIComponent(id)}/items/${encodeURIComponent(item.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(changes)});setNotice('A tétel mennyisége/kedvezménye módosítva.');await load(false)}catch(e:any){setError(e?.message||'A tétel módosítása nem sikerült.');setItemEdits(itemEditMap(data?.items))}finally{setItemSaving(false)}};
 const saveItemEdit=(item:WorkOrderItem,key:'quantity'|'discount')=>{const edit=itemEdits[item.id];if(!edit)return;const value=Number(edit[key]||0);const original=Number(key==='quantity'?item.quantity:item.discount_amount||0);if(!Number.isFinite(value)||Math.abs(value-original)<.0001)return;void updateItem(item,key==='quantity'?{quantity:value}:{discount_amount:value})};
 const nudgeQuantity=(item:WorkOrderItem,direction:number)=>{const step=item.item_type==='product'?.01:1;const current=Number(itemEdits[item.id]?.quantity??item.quantity??1);const next=Math.max(step,Math.round((current+direction*step)*100)/100);setItemEdits(v=>({...v,[item.id]:{quantity:String(next),discount:v[item.id]?.discount??String(Number(item.discount_amount||0))}}));void updateItem(item,{quantity:next})};
 const togglePickerService=async(service:PickerService)=>{const rows=(data?.items||[]).filter(x=>x.item_type==='service'&&String(x.service_id||'')===String(service.id));if(rows.length){for(const row of rows)await removeItem(row,false);return}await addItemPayload('service',String(service.id),1,0)};
 const togglePickerProduct=async(product:PickerProduct)=>{const rows=(data?.items||[]).filter(x=>x.item_type==='product'&&String(x.product_id||'')===String(product.id));if(rows.length){for(const row of rows)await removeItem(row,false);return}await addItemPayload('product',String(product.id),1,0)};

 const addPaymentRow=()=>setNewPayments(v=>[...v,blankPayment(Math.max(0,...v.map(x=>x.id))+1)]);const updatePayment=(pid:number,key:keyof PaymentDraft,value:string)=>setNewPayments(v=>v.map(p=>p.id===pid?{...p,[key]:value}:p));const removePaymentRow=(pid:number)=>setNewPayments(v=>v.length===1?[blankPayment(pid+1)]:v.filter(p=>p.id!==pid));
 const fillRemaining=()=>{const other=newPayments.slice(1).reduce((n,p)=>n+Math.max(0,Number(p.amount||0)),0);const value=Math.max(0,Math.round((amountDue-paidTotal-loyaltyTender-other)*100)/100);setNewPayments(v=>{const base=v.length?v:[blankPayment()];return base.map((p,i)=>i===0?{...p,amount:value?String(value):''}:p)})};
 const normalPayments=()=>newPayments.filter(p=>Number(p.amount)>0).map(p=>({payment_method:p.payment_method,amount:Number(p.amount),note:[p.destination?`Pénztár/terminál: ${p.destination}`:'',p.note||''].filter(Boolean).join(' · ')||null}));
 const settlementBody=(closeFinancially:boolean)=>({discount_amount:Math.max(0,manualDiscount),tip_amount:Math.max(0,tip),invoice_status:invoiceStatus||'not_requested',close_financially:closeFinancially,payments:normalPayments()});
 const performSettlement=async(closeFinancially:boolean)=>{if(!id)return;if(useLoyaltySettlement){await apiFetch(`/api/transactions/loyalty-cashier/workorders/${encodeURIComponent(id)}/settle`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...settlementBody(closeFinancially),account_id:loyalty.accountId||null,customer_id:loyalty.customerId||draft.client_id||null,wallet_amount:Number(loyalty.walletAmount||0),points_to_spend:Number(loyalty.pointsToSpend||0),coupon_code:loyalty.couponCode||null,voucher_code:loyalty.voucherCode||null,voucher_amount:Number(loyalty.voucherAmount||0),pass_usages:loyalty.passUsages})})}else await apiFetch(`/api/transactions/cashier/workorders/${encodeURIComponent(id)}/settle`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settlementBody(closeFinancially))})};
 const savePartialPayment=async()=>{if(!id||!canRecordPayments)return;if(actualLoyaltyUsage){setError('Wallet, pont, kupon, utalvány vagy bérlet használatakor az elszámolást a végleges pénzügyi záráskor kell rögzíteni.');return}setPaymentSaving(true);clearMessages();try{await apiFetch(`/api/transactions/cashier/workorders/${encodeURIComponent(id)}/settle`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settlementBody(false))});setNewPayments([blankPayment()]);setNotice('A részfizetés és a pénzügyi adatok mentve.');await load(false)}catch(e:any){setError(e?.message||'A részfizetés rögzítése nem sikerült.')}finally{setPaymentSaving(false)}};
 const financialClose=async()=>{if(!paymentReady)return;setPaymentSaving(true);clearMessages();try{await performSettlement(true);setNewPayments([blankPayment()]);setNotice('A fizetés kiegyenlítve, a munkalap pénzügyileg lezárva.');await load(false)}catch(e:any){setError(e?.message||'A pénzügyi zárás nem sikerült.')}finally{setPaymentSaving(false)}};
 const finalize=async()=>{if(!id||locked||!closeReady)return;if(!window.confirm(financiallyClosed?'A munkalap végleges lezárása készletmozgást, könyvelést, jutalékeseményt és archiválást végez. Folytatja?':'A fizetés és a munkalap végleges lezárása után a dokumentum zárolásra kerül. Folytatja?'))return;setActionSaving(true);clearMessages();try{if(!financiallyClosed)await performSettlement(true);await apiFetch(`/api/transactions/workorder-finalization/workorders/${encodeURIComponent(id)}/finalize`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});setNewPayments([blankPayment()]);setNotice('A munkalap véglegesen lezárva és archiválva.');await load(false)}catch(e:any){setError(e?.message||'A végleges lezárás nem sikerült.')}finally{setActionSaving(false)}};
 const loadArchive=async()=>{if(!id)return;setArchiveLoading(true);clearMessages();try{setArchive(await apiFetch<ArchiveData>(`/api/workorders/${encodeURIComponent(id)}/archive`));setNotice('Az archivált munkalappéldány betöltve.')}catch(e:any){setError(e?.message||'Az archív munkalap nem tölthető be.')}finally{setArchiveLoading(false)}};

 if(loading&&!data)return <main className="wo-detail"><div className="wo-detail__state"><RefreshCw className="spin"/> Munkalap betöltése…</div></main>;
 if(error&&!data)return <main className="wo-detail"><button className="wo-detail__button" onClick={()=>navigate('/workorders')}><ArrowLeft size={16}/> Vissza</button><div className="wo-detail__error">{error}</div></main>;
 if(!data)return null;
 return <main className="wo-detail">
  <header className="wo-detail__hero"><div><button className="wo-detail__button" onClick={()=>navigate('/workorders')}><ArrowLeft size={16}/> Munkalapok</button><span className="wo-detail__eyebrow">MUNKALAP · OPERATÍV FOLYAMAT</span><h1>{data.work_order_number||data.id}</h1><p>{data.location_name||'Nincs szalon megadva'} · {statusHu(data.status)}</p></div><div className="wo-detail__hero-actions">{locked?<span className="wo-detail__pill is-locked"><LockKeyhole size={14}/> LEZÁRT · ARCHIVÁLT</span>:canEdit?<span className="wo-detail__pill is-edit"><CheckCircle2 size={14}/> SZERKESZTHETŐ</span>:<span className="wo-detail__pill">CSAK OLVASHATÓ</span>}<button className="wo-detail__button" onClick={()=>void load(false)}><RefreshCw size={16}/> Frissítés</button></div></header>
  {error&&<div className="wo-detail__error">{error}</div>}{notice&&<div className="wo-detail__success">{notice}</div>}

  <section className="wo-detail__workflow">
   <div className="wo-detail__section-head"><div><span>ÁLLAPOT</span><h2>Munkafolyamat</h2></div><strong>{statusHu(data.status)}</strong></div>
   <div className="wo-detail__status-steps"><span className={['waiting','arrived','in_progress','completed'].includes(String(data.status))?'is-done':''}>1. Új</span><span className={['arrived','in_progress','completed'].includes(String(data.status))?'is-done':''}>2. Megérkezett</span><span className={['in_progress','completed'].includes(String(data.status))?'is-done':''}>3. Folyamatban</span><span className={financiallyClosed||locked?'is-done':''}>4. Fizetve</span><span className={locked&&data.status==='completed'?'is-done':''}>5. Lezárt</span></div>
   {canEdit&&!locked&&<div className="wo-detail__actions">{data.status==='waiting'&&<><button className="is-primary" disabled={actionSaving} onClick={()=>void changeStatus('arrived')}><UserCheck/> Vendég megérkezett</button><button disabled={actionSaving} onClick={()=>void changeStatus('in_progress')}><Play/> Munka azonnali indítása</button><button className="is-danger" disabled={actionSaving} onClick={()=>void changeStatus('no_show')}><XCircle/> Nem jelent meg</button></>}{data.status==='arrived'&&<button className="is-primary" disabled={actionSaving} onClick={()=>void changeStatus('in_progress')}><Play/> Munka elkezdése</button>}{data.status==='in_progress'&&!financiallyClosed&&<button className="is-pay" disabled={actionSaving} onClick={()=>document.getElementById('workorder-payment-step')?.scrollIntoView({behavior:'smooth'})}><CreditCard/> Fizetés</button>}{['waiting','arrived','in_progress'].includes(String(data.status))&&<button className="is-danger" disabled={actionSaving||financiallyClosed} onClick={()=>void changeStatus('cancelled')}><XCircle/> Lemondás</button>}</div>}
  </section>

  <section id="workorder-guest-step" className="wo-detail__section">
   <div className="wo-detail__section-head"><div><span>1. LÉPÉS</span><h2><Users/> Vendég, szalon és munkatárs</h2><p>A meglévő munkalap alapadatai, felelőse és vendégkapcsolata.</p></div>{canEditBase&&<button className="wo-detail__button is-primary" disabled={saving} onClick={()=>void save()}><Save/>{saving?'Mentés…':'Adatok mentése'}</button>}</div>
   <div className="wo-detail__grid3">
    <article className="wo-detail__card"><div className="wo-detail__card-title"><Building2/> Szalon és munkatárs</div><label>Szalon<input value={data.location_name||'—'} disabled/></label><label>Munkatárs<select value={draft.employee_id} disabled={!canEditBase||saving||!employees.length} onChange={e=>void changeEmployee(e.target.value)}><option value="">Nincs kiválasztva</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name||x.id}</option>)}</select></label><label>Munkalap címe<input value={draft.title} disabled={!canEditBase||saving} onChange={e=>setDraft(v=>({...v,title:e.target.value}))}/></label><label>Belső megjegyzés<textarea value={draft.notes} disabled={!canEditBase||saving} onChange={e=>setDraft(v=>({...v,notes:e.target.value}))}/></label></article>
    <article className="wo-detail__card"><div className="wo-detail__card-title"><UserRound/> Vendég</div>{clients.length>0&&<><label className="wo-detail__search"><Search/><input value={clientSearch} disabled={!canEditBase} onChange={e=>setClientSearch(e.target.value)} placeholder="Keresés név, telefon vagy e-mail alapján"/></label><label>Törzsvendég<select value={draft.client_id} disabled={!canEditBase} onChange={e=>selectClient(e.target.value)}><option value="">Kézi vendégadatok</option>{filteredClients.slice(0,200).map(c=><option key={c.id} value={c.id}>{c.name}{c.phone?` · ${c.phone}`:''}</option>)}</select></label></>}<label>Név<input value={draft.client_name} disabled={!canEditBase||Boolean(draft.client_id)} onChange={e=>setDraft(v=>({...v,client_name:e.target.value}))}/></label><div className="wo-detail__grid2"><label>Telefon<input value={draft.client_phone} disabled={!canEditBase||Boolean(draft.client_id)} onChange={e=>setDraft(v=>({...v,client_phone:e.target.value}))}/></label><label>E-mail<input value={draft.client_email} disabled={!canEditBase||Boolean(draft.client_id)} onChange={e=>setDraft(v=>({...v,client_email:e.target.value}))}/></label></div><label className="wo-detail__check"><input type="checkbox" checked={draft.note_for_another_visitor} disabled={!canEditBase} onChange={e=>setDraft(v=>({...v,note_for_another_visitor:e.target.checked}))}/> Bejegyzés egy másik látogató számára</label></article>
    <article className="wo-detail__card"><div className="wo-detail__card-title"><ClipboardCheck/> Munkalap összesítő</div><div className="wo-detail__summary"><div><span>Azonosító</span><b>{data.work_order_number||data.id}</b></div><div><span>Létrehozva</span><b>{dateTime(data.created_at)}</b></div><div><span>Módosítva</span><b>{dateTime(data.updated_at)}</b></div><div><span>Kezdés</span><b>{dateTime(data.started_at)}</b></div><div><span>Tételek</span><b>{data.items?.length||0}</b></div><div><span>Bruttó érték</span><b>{money(itemTotal)}</b></div></div>{locked&&<div className="wo-detail__archive-note"><LockKeyhole/><span><b>Archivált munkalap</b><small>Lezárva: {dateTime(data.locked_at||data.archived_at)}{data.locked_reason?` · ${data.locked_reason}`:''}</small></span></div>}</article>
   </div>
  </section>

  <div id="workorder-history-step"><WorkOrderGuestContextPanel customerId={draft.client_id||undefined} locationId={String(data.location_id||'')||undefined} disabled={!canEditBase} onCustomerCreated={handleCustomerCreated}/><WorkOrderLoyaltyPanel grossTotal={itemTotal} customerId={draft.client_id||undefined} serviceIds={serviceIds} productIds={productIds} disabled={!canRecordPayments||loyaltyUsageBlocked} onChange={handleLoyaltyChange}/>{loyaltyUsageBlocked&&<div className="wo-detail__info">A munkalapon már van rögzített fizetés. Új wallet-, pont-, kupon-, utalvány- vagy bérletfelhasználás ezért nem módosítható úgy, hogy a korábbi pénztári tétel túlfizetést okozhasson.</div>}</div>

  <section id="workorder-items-step" className="wo-detail__section">
   <div className="wo-detail__section-head"><div><span>3. LÉPÉS</span><h2><PackagePlus/> Szolgáltatások és termékek</h2><p>Tételek hozzáadása, eltávolítása, mennyiség- és kedvezménymódosítás.</p></div>{canEditItems&&<button className="wo-detail__button is-primary" disabled={itemSaving} onClick={()=>setItemPickerOpen(true)}><Plus/> Tételek kiválasztása</button>}</div>
   {canEditItems&&<div className="wo-detail__quick-add"><label>Típus<select value={itemType} onChange={e=>{setItemType(e.target.value as 'service'|'product');setItemId('')}}><option value="service">Szolgáltatás</option><option value="product">Termék</option></select></label><label className="is-wide">Tétel<select value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Válasszon…</option>{availableItems.map(x=><option key={x.id} value={x.id}>{x.category_name?`${x.category_name} · `:''}{x.name} — {money(x.price)}</option>)}</select></label><label>Mennyiség<input type="number" min={itemType==='product'?.01:1} step={itemType==='product'?.01:1} value={itemQty} onChange={e=>setItemQty(Number(e.target.value))}/></label><label>Kedvezmény (Ft)<input type="number" min={0} value={itemDiscount} onChange={e=>setItemDiscount(Number(e.target.value))}/></label><button className="wo-detail__button is-primary" disabled={!itemId||itemSaving} onClick={()=>void addItem()}><PackagePlus/>{itemSaving?'Mentés…':'Hozzáadás'}</button>{selectedItem&&<small className="wo-detail__quick-preview">Kiválasztva: <b>{selectedItem.name}</b> · {money(selectedItem.price)}{selectedItem.duration_minutes?` · ${selectedItem.duration_minutes} perc`:''}</small>}</div>}
   <div className="wo-detail__table-wrap"><table className="wo-detail__table"><thead><tr><th>Típus</th><th>Megnevezés</th><th>Mennyiség</th><th>Egységár</th><th>Kedvezmény</th><th>Összesen</th>{canEditItems&&<th>Művelet</th>}</tr></thead><tbody>{(data.items||[]).map(item=>{const edit=itemEdits[item.id]||{quantity:String(Number(item.quantity||1)),discount:String(Number(item.discount_amount||0))};return <tr key={item.id}><td>{item.item_type==='service'?'Szolgáltatás':item.item_type==='product'?'Termék':item.item_type||'—'}</td><td><b>{item.item_name||'—'}</b>{item.duration_minutes?<small>{item.duration_minutes} perc</small>:null}</td><td>{canEditItems?<div className="wo-detail__qty"><button disabled={itemSaving} onClick={()=>nudgeQuantity(item,-1)}><Minus/></button><input type="number" min={item.item_type==='product'?.01:1} step={item.item_type==='product'?.01:1} value={edit.quantity} disabled={itemSaving} onChange={e=>setItemEdits(v=>({...v,[item.id]:{...edit,quantity:e.target.value}}))} onBlur={()=>saveItemEdit(item,'quantity')}/><button disabled={itemSaving} onClick={()=>nudgeQuantity(item,1)}><Plus/></button></div>:Number(item.quantity||0).toLocaleString('hu-HU')}</td><td>{money(item.unit_price)}</td><td>{canEditItems?<input className="wo-detail__money-input" type="number" min="0" value={edit.discount} disabled={itemSaving} onChange={e=>setItemEdits(v=>({...v,[item.id]:{...edit,discount:e.target.value}}))} onBlur={()=>saveItemEdit(item,'discount')}/>:money(item.discount_amount)}</td><td><b>{money(item.line_total)}</b></td>{canEditItems&&<td><button className="wo-detail__icon-danger" disabled={itemSaving} onClick={()=>void removeItem(item)} title="Tétel eltávolítása"><Trash2/></button></td>}</tr>})}{!data.items?.length&&<tr><td colSpan={canEditItems?7:6} className="wo-detail__empty">Nincs rögzített tétel.</td></tr>}</tbody></table></div>
  </section>

  <section id="workorder-material-step" className="wo-detail__section">
   <div className="wo-detail__section-head"><div><span>4. LÉPÉS</span><h2><PackageCheck/> Anyagfelhasználás és készlet</h2><p>A munkalapon szereplő termékek tényleges felhasználása és az elérhető szalonkészlet.</p></div>{canEditItems&&<button className="wo-detail__button" onClick={()=>setItemPickerOpen(true)}><PackagePlus/> Termékhasználat módosítása</button>}</div>
   {materials.length?<div className="wo-detail__materials">{materials.map(m=>{const stock=m.availableStock==null?null:Number(m.availableStock);const remainingStock=stock==null?null:stock-m.quantity;const warning=remainingStock!=null&&remainingStock<0;return <article className={warning?'is-warning':''} key={String(m.productId)}><PackageCheck/><div><b>{m.name}</b><span>Felhasználás: {m.quantity.toLocaleString('hu-HU')} {m.unit||'db'} · {money(Number(m.unitPrice||0)*m.quantity)}</span><small>{stock==null?'Készletadat nem érhető el':warning?`Készlethiány: ${Math.abs(remainingStock||0).toLocaleString('hu-HU')} ${m.unit||'db'}`:`Készlet: ${stock.toLocaleString('hu-HU')} ${m.unit||'db'} · marad: ${Math.max(0,remainingStock||0).toLocaleString('hu-HU')} ${m.unit||'db'}`}</small></div></article>})}</div>:<div className="wo-detail__empty-box"><PackageCheck/> Nincs termék- vagy anyagfelhasználás rögzítve.</div>}
  </section>

  <section id="workorder-review-step" className="wo-detail__review-wrap"><div className="wo-detail__section-head"><div><span>5. LÉPÉS</span><h2><ClipboardCheck/> Összesítő és ellenőrzés</h2></div></div><WorkOrderReviewPanel locationId={String(data.location_id||'')} employeeName={employees.find(x=>String(x.id)===draft.employee_id)?.full_name||data.employee_name} clientName={draft.client_name} clientPhone={draft.client_phone} clientEmail={draft.client_email} title={draft.title} services={selectedServices} materials={materials} grossTotal={itemTotal} loyaltyUsed={actualLoyaltyUsage||Boolean(loyalty.accountId)} onReadyChange={setReviewReady} disabled={locked}/></section>

  <section id="workorder-payment-step" className="wo-detail__section">
   <div className="wo-detail__section-head"><div><span>6. LÉPÉS</span><h2><CreditCard/> Fizetés és pénzügyi zárás</h2><p>Részfizetés, kevert fizetés, kedvezmény, borravaló és bizonylati állapot.</p></div>{data.status==='in_progress'&&!locked&&!financiallyClosed&&<button className="wo-detail__button" onClick={()=>navigate(`/finance?workorder=${encodeURIComponent(data.id)}`)}><CreditCard/> Központi pénztár</button>}</div>
   <div className="wo-detail__finance-grid"><label>Munkalap kedvezmény (Ft)<input type="number" min="0" value={manualDiscount} disabled={!canRecordPayments} onChange={e=>setManualDiscount(Math.max(0,Number(e.target.value||0)))}/></label><label>Borravaló (Ft)<input type="number" min="0" value={tip} disabled={!canRecordPayments} onChange={e=>setTip(Math.max(0,Number(e.target.value||0)))}/></label><label>Bizonylati állapot<select value={invoiceStatus} disabled={!canRecordPayments} onChange={e=>setInvoiceStatus(e.target.value)}><option value="not_requested">Nem kért számlát</option><option value="requested">Számla kért</option><option value="issued">Számla kiállítva</option></select></label><div className="wo-detail__finance-stat"><span>Fizetendő</span><b>{money(amountDue)}</b><small>Hátralék: {money(remaining)}</small></div></div>
   <div className="wo-detail__existing-payments"><h3>Korábban rögzített fizetések</h3><div className="wo-detail__table-wrap"><table className="wo-detail__table"><thead><tr><th>Mód</th><th>Összeg</th><th>Időpont</th><th>Megjegyzés</th></tr></thead><tbody>{(data.payments||[]).map(p=><tr key={p.id}><td>{paymentMethodHu(p.payment_method)}</td><td><b>{money(p.amount)}</b></td><td>{dateTime(p.paid_at)}</td><td>{p.note||'—'}</td></tr>)}{!data.payments?.length&&<tr><td colSpan={4} className="wo-detail__empty">Nincs fizetés rögzítve.</td></tr>}</tbody></table></div></div>
   {financiallyClosed?<div className="wo-detail__closed-finance"><CheckCircle2/><span><b>A munkalap pénzügyileg lezárt.</b><small>{dateTime(data.financial_closed_at)} · {paymentHu(data.payment_status)} · fizetve {money(paidTotal)}</small></span></div>:data.status!=='in_progress'?<div className="wo-detail__info">A fizetés és pénzügyi zárás a munkalap <b>Folyamatban</b> állapotában érhető el.</div>:<><WorkOrderPaymentPanel grossTotal={itemTotal} payableTotal={amountDue} loyaltyCredit={Math.max(0,manualDiscount)+loyaltyDiscount} payments={newPayments} alreadyPaid={paidTotal} loyaltyTender={loyaltyTender} disabled={!canRecordPayments} onAdd={addPaymentRow} onChange={updatePayment} onRemove={removePaymentRow}/><div className="wo-detail__payment-actions"><button className="wo-detail__button" disabled={!canRecordPayments||paymentSaving} onClick={fillRemaining}>Hátralék kitöltése</button><button className="wo-detail__button" disabled={!canRecordPayments||paymentSaving||actualLoyaltyUsage} onClick={()=>void savePartialPayment()}>{paymentSaving?'Mentés…':'Részfizetés / pénzügyi adatok mentése'}</button><button className="wo-detail__button is-primary" disabled={!paymentReady||paymentSaving} onClick={()=>void financialClose()}>{paymentSaving?'Zárás…':'Fizetés pénzügyi lezárása'}</button></div></>}
  </section>

  <section id="workorder-close-step" className="wo-detail__close-wrap"><WorkOrderClosePanel ready={closeReady} saving={actionSaving||paymentSaving} workOrderNumber={data.work_order_number} financiallyClosed={financiallyClosed} locked={locked} onFinalize={()=>void finalize()}/>{locked&&<div className="wo-detail__archive-panel"><div><Archive/><span><b>Archivált példány</b><small>A végleges snapshot auditálható és visszanézhető.</small></span></div><button className="wo-detail__button" disabled={archiveLoading} onClick={()=>void loadArchive()}>{archiveLoading?'Betöltés…':'Archív snapshot betöltése'}</button>{archive&&<div className="wo-detail__archive-data"><span>Archiválva: <b>{dateTime(archive.archived_at)}</b></span><span>Terminális állapot: <b>{archive.terminal_status||'—'}</b></span><span>Hash: <code>{archive.snapshot_hash||data.archive_hash||'—'}</code></span>{archive.snapshot!=null&&<details><summary>Archivált adatok megjelenítése</summary><pre>{JSON.stringify(archive.snapshot,null,2)}</pre></details>}</div>}</div>}</section>

  <WorkOrderItemPickerModal open={itemPickerOpen} disabled={!canEditItems||itemSaving} services={catalog.services as PickerService[]} products={catalog.products as PickerProduct[]} selectedServiceIds={serviceIds} selectedProductIds={productIds} onToggleService={s=>void togglePickerService(s)} onToggleProduct={p=>void togglePickerProduct(p)} onClose={()=>setItemPickerOpen(false)}/>
 </main>
}
