import React,{useEffect,useMemo,useState}from"react";
import{RefreshCw,Settings2}from"lucide-react";
import api from"../api/api";
import AlertRuleEditor from"./AlertRuleEditor";
type K="supplier_expiry"|"employee_document"|"complaint_sla";
export default function AlertRuleManagementPanel(){
 const[data,setData]=useState<any>({rules:[],catalog:[],locations:[],escalation_flow:[],audit:[]}),[scope,setScope]=useState<"global"|"location">("global"),[locationId,setLocationId]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await api.get("/transactions/notifications/alert-rules/rules");setData(r.data||{})}catch(e:any){setError(e?.response?.data?.message||e?.message||"A szabályok betöltése sikertelen.")}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 const globals=useMemo(()=>new Map((data.rules||[]).filter((x:any)=>x.scope_type==="global").map((x:any)=>[x.rule_key,x])),[data.rules]);
 const effective=(k:K)=>scope==="location"&&locationId?(data.rules||[]).find((x:any)=>x.rule_key===k&&x.scope_type==="location"&&String(x.scope_id)===locationId)||globals.get(k):globals.get(k);
 return <section className="notify-rule-panel"><header><div><small>RIASZTÁSI SZABÁLYMOTOR</small><h2><Settings2/>Szabályok és eszkaláció</h2><p>Központi és szalononkénti lejárati/SLA szabályok.</p></div><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/>Frissítés</button></header>{error&&<div className="notify-error">{error}</div>}<div className="notify-rule-toolbar"><label>Hatókör<select value={scope} onChange={e=>setScope(e.target.value as any)}><option value="global">Központi</option><option value="location">Szalon</option></select></label>{scope==="location"&&<label>Szalon<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Válassz…</option>{(data.locations||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<div className="notify-flow"><b>Eszkaláció:</b>{(data.escalation_flow||[]).map((x:any)=><span key={x.level}>L{x.level} {x.label}</span>)}</div></div>{scope==="location"&&!locationId?<p className="notify-admin-empty">Válassz szalont a felülíráshoz.</p>:<div className="notify-rule-grid">{(data.catalog||[]).map((c:any)=>{const r=effective(c.key);return <article key={c.key}><h3>{c.title}</h3><p>{c.description}</p>{r&&<AlertRuleEditor rule={r} scopeType={scope} scopeId={locationId} unit={c.warning_unit} onSaved={load}/>}</article>})}</div>}<div className="notify-rule-audit"><h3>Utolsó módosítások</h3>{(data.audit||[]).slice(0,8).map((x:any)=><div key={x.id}><b>{x.rule_key}</b><span>{x.scope_type==="global"?"Központi":x.scope_id}</span><span>{x.action}</span><span>{x.actor||"—"}</span></div>)}</div></section>;
}
