import React,{FormEvent,useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,BellRing,CheckCircle2,FileWarning,Mail,PackagePlus,Pencil,Play,RefreshCw,Save,ShieldAlert,Smartphone,Trash2,Truck,XCircle}from"lucide-react";
import api from"../api/api";

type AnyRow=Record<string,any>;
type Preferences={email?:string|null;email_enabled:boolean;push_enabled:boolean;critical_only:boolean;supplier_expiry:boolean;employee_document:boolean;complaint_sla:boolean;push_subscription_count:number;vapid_public_key:string};
type Summary={total:number;critical:number;supplier_expiry:number;employee_document:number;complaint_sla:number};
type Tab="channels"|"documents"|"supplier";

const emptyPrefs:Preferences={email:null,email_enabled:false,push_enabled:false,critical_only:false,supplier_expiry:true,employee_document:true,complaint_sla:true,push_subscription_count:0,vapid_public_key:""};
const emptyDoc={employee_id:"",document_type:"Képesítés",document_name:"",document_number:"",issued_at:"",valid_from:"",valid_until:"",file_url:"",warning_days:"",note:"",active:true};
const emptyBatch={supplier_id:"",product_id:"",location_id:"",lot_number:"",received_at:new Date().toISOString().slice(0,10),expires_at:"",quantity:"",note:"",active:true};
const err=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||"A művelet nem sikerült.";
const rows=(data:any):AnyRow[]=>Array.isArray(data)?data:Array.isArray(data?.items)?data.items:Array.isArray(data?.rows)?data.rows:Array.isArray(data?.employees)?data.employees:Array.isArray(data?.products)?data.products:Array.isArray(data?.locations)?data.locations:[];
const label=(row:AnyRow)=>String(row.full_name||row.name||row.title||row.internal_code||row.code||row.id||"");
const date=(v:any)=>v?String(v).slice(0,10):"—";
const b64ToBytes=(base64:string)=>{const pad="=".repeat((4-base64.length%4)%4),normalized=(base64+pad).replace(/-/g,"+").replace(/_/g,"/"),raw=window.atob(normalized),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out};

export default function OperationalAlertAdminConsole(){
 const[tab,setTab]=useState<Tab>("channels"),[prefs,setPrefs]=useState<Preferences>(emptyPrefs),[summary,setSummary]=useState<Summary|null>(null);
 const[docs,setDocs]=useState<AnyRow[]>([]),[batches,setBatches]=useState<AnyRow[]>([]),[employees,setEmployees]=useState<AnyRow[]>([]),[suppliers,setSuppliers]=useState<AnyRow[]>([]),[products,setProducts]=useState<AnyRow[]>([]),[locations,setLocations]=useState<AnyRow[]>([]);
 const[docForm,setDocForm]=useState<any>(emptyDoc),[batchForm,setBatchForm]=useState<any>(emptyBatch),[editingDoc,setEditingDoc]=useState<string|null>(null),[editingBatch,setEditingBatch]=useState<string|null>(null);
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[management,setManagement]=useState(true);
 const pushSupported=typeof window!=="undefined"&&"serviceWorker"in navigator&&"PushManager"in window&&"Notification"in window;
 const permission=typeof Notification!=="undefined"?Notification.permission:"unsupported";

 const loadPreferences=useCallback(async()=>{const r=await api.get("/transactions/notifications/preferences");setPrefs({...emptyPrefs,...r.data});},[]);
 const loadSummary=useCallback(async()=>{try{const r=await api.get("/transactions/notifications/automation/summary");setSummary(r.data);setManagement(true)}catch(e:any){if(e?.response?.status===403){setManagement(false);setSummary(null);return}throw e}},[]);
 const loadReferenceData=useCallback(async()=>{
  const reqs=await Promise.allSettled([
   api.get("/employees"),api.get("/transactions/masterdata/suppliers",{params:{include_inactive:1}}),api.get("/products"),api.get("/locations")
  ]);
  if(reqs[0].status==="fulfilled")setEmployees(rows(reqs[0].value.data));
  if(reqs[1].status==="fulfilled")setSuppliers(rows(reqs[1].value.data));
  if(reqs[2].status==="fulfilled")setProducts(rows(reqs[2].value.data));
  if(reqs[3].status==="fulfilled")setLocations(rows(reqs[3].value.data));
 },[]);
 const loadManagementData=useCallback(async()=>{
  if(!management)return;
  const[d,b]=await Promise.all([api.get("/transactions/notifications/automation/employee-documents"),api.get("/transactions/notifications/automation/supplier-expiry-batches")]);
  setDocs(rows(d.data));setBatches(rows(b.data));
 },[management]);
 const loadAll=useCallback(async()=>{setLoading(true);setError("");try{await Promise.all([loadPreferences(),loadSummary()]);await Promise.all([loadReferenceData(),loadManagementData()])}catch(e){setError(err(e))}finally{setLoading(false)}},[loadPreferences,loadSummary,loadReferenceData,loadManagementData]);
 useEffect(()=>{void loadAll()},[loadAll]);

 async function savePreferences(){setSaving(true);setError("");setNotice("");try{const r=await api.put("/transactions/notifications/preferences",{email_enabled:prefs.email_enabled,push_enabled:prefs.push_enabled,critical_only:prefs.critical_only,supplier_expiry:prefs.supplier_expiry,employee_document:prefs.employee_document,complaint_sla:prefs.complaint_sla});setPrefs(p=>({...p,...r.data}));setNotice("Az értesítési beállítások elmentve.")}catch(e){setError(err(e))}finally{setSaving(false)}}
 async function enablePush(){
  if(!pushSupported){setError("Ez a böngésző nem támogatja a webes push értesítéseket.");return}
  setSaving(true);setError("");setNotice("");
  try{
   const allowed=await Notification.requestPermission();if(allowed!=="granted")throw new Error("A böngészőben nem engedélyezted az értesítéseket.");
   const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();
   if(!subscription){if(!prefs.vapid_public_key)throw new Error("A szerver VAPID nyilvános kulcsa nem érhető el.");subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToBytes(prefs.vapid_public_key)})}
   const r=await api.post("/transactions/notifications/push-subscriptions",{subscription:subscription.toJSON()});setPrefs(p=>({...p,...r.data,push_enabled:true}));setNotice("A VIR push értesítések engedélyezve ezen az eszközön.");
  }catch(e){setError(err(e))}finally{setSaving(false)}
 }
 async function disablePush(){setSaving(true);setError("");setNotice("");try{const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription){await api.delete("/transactions/notifications/push-subscriptions",{data:{endpoint:subscription.endpoint}});await subscription.unsubscribe()}else await api.delete("/transactions/notifications/push-subscriptions");setPrefs(p=>({...p,push_enabled:false,push_subscription_count:0}));setNotice("A push értesítések kikapcsolva ezen az eszközön.")}catch(e){setError(err(e))}finally{setSaving(false)}}
 async function runNow(){setRunning(true);setError("");try{await api.post("/transactions/notifications/automation/run");await Promise.all([loadSummary(),loadManagementData()]);setNotice("Az automatikus ellenőrzés lefutott.")}catch(e){setError(err(e))}finally{setRunning(false)}}

 function editDoc(row:AnyRow){setEditingDoc(String(row.id));setDocForm({employee_id:row.employee_id||"",document_type:row.document_type||"Egyéb",document_name:row.document_name||"",document_number:row.document_number||"",issued_at:date(row.issued_at)==="—"?"":date(row.issued_at),valid_from:date(row.valid_from)==="—"?"":date(row.valid_from),valid_until:date(row.valid_until)==="—"?"":date(row.valid_until),file_url:row.file_url||"",warning_days:row.warning_days??"",note:row.note||"",active:row.active!==false});setTab("documents")}
 async function saveDoc(e:FormEvent){e.preventDefault();setSaving(true);setError("");setNotice("");try{if(editingDoc)await api.patch(`/transactions/notifications/automation/employee-documents/${editingDoc}`,docForm);else await api.post("/transactions/notifications/automation/employee-documents",docForm);setEditingDoc(null);setDocForm(emptyDoc);await Promise.all([loadManagementData(),loadSummary()]);setNotice("A dolgozói dokumentum elmentve.")}catch(x){setError(err(x))}finally{setSaving(false)}}
 async function deactivateDoc(id:string){if(!window.confirm("Biztosan inaktiválod ezt a dokumentumot?"))return;setSaving(true);try{await api.delete(`/transactions/notifications/automation/employee-documents/${id}`);await Promise.all([loadManagementData(),loadSummary()])}catch(e){setError(err(e))}finally{setSaving(false)}}

 function editBatch(row:AnyRow){setEditingBatch(String(row.id));setBatchForm({supplier_id:row.supplier_id||"",product_id:row.product_id||"",location_id:row.location_id||"",lot_number:row.lot_number||"",received_at:date(row.received_at)==="—"?"":date(row.received_at),expires_at:date(row.expires_at)==="—"?"":date(row.expires_at),quantity:row.quantity??"",note:row.note||"",active:row.active!==false});setTab("supplier")}
 async function saveBatch(e:FormEvent){e.preventDefault();setSaving(true);setError("");setNotice("");try{const body={...batchForm,supplier_id:batchForm.supplier_id||null,location_id:batchForm.location_id||null,expires_at:batchForm.expires_at||null};if(editingBatch)await api.patch(`/transactions/notifications/automation/supplier-expiry-batches/${editingBatch}`,body);else await api.post("/transactions/notifications/automation/supplier-expiry-batches",body);setEditingBatch(null);setBatchForm(emptyBatch);await Promise.all([loadManagementData(),loadSummary()]);setNotice("A beszállítói lejárati tétel elmentve.")}catch(x){setError(err(x))}finally{setSaving(false)}}
 async function deactivateBatch(id:string){if(!window.confirm("Biztosan inaktiválod ezt a lejárati tételt?"))return;setSaving(true);try{await api.delete(`/transactions/notifications/automation/supplier-expiry-batches/${id}`);await Promise.all([loadManagementData(),loadSummary()])}catch(e){setError(err(e))}finally{setSaving(false)}}

 const activeDocs=useMemo(()=>docs.filter(x=>x.active!==false),[docs]),activeBatches=useMemo(()=>batches.filter(x=>x.active!==false),[batches]);
 const field=(name:string,value:any,setter:(v:any)=>void,type="text",required=false)=><input type={type} value={value??""} required={required} onChange={e=>setter(e.target.value)}/>;

 return <section className="notify-console">
  <header className="notify-console-head"><div><small>AUTOMATIZÁLÁS ÉS KIKÜLDÉSI CSATORNÁK</small><h2><BellRing/>Operatív értesítések</h2><p>Lejáratok, panasz SLA, e-mail és mobil/böngésző push egy központi kezelőfelületen.</p></div><div className="notify-console-actions"><button onClick={()=>void loadAll()} disabled={loading}><RefreshCw className={loading?"spin":""}/>Frissítés</button>{management&&<button onClick={()=>void runNow()} disabled={running}><Play className={running?"spin":""}/>{running?"Ellenőrzés…":"Ellenőrzés most"}</button>}</div></header>
  {error&&<div className="notify-error"><AlertTriangle/>{error}</div>}{notice&&<div className="notify-console-ok"><CheckCircle2/>{notice}</div>}
  {summary&&<div className="notify-automation-grid"><article className={summary.supplier_expiry?"warn":""}><Truck/><div><span>Beszállítói lejárat</span><b>{summary.supplier_expiry}</b></div></article><article className={summary.employee_document?"warn":""}><FileWarning/><div><span>Dolgozói dokumentum</span><b>{summary.employee_document}</b></div></article><article className={summary.complaint_sla?"warn":""}><ShieldAlert/><div><span>Panasz SLA</span><b>{summary.complaint_sla}</b></div></article><article className={summary.critical?"critical":""}><AlertTriangle/><div><span>Kritikus</span><b>{summary.critical}</b></div></article></div>}
  <div className="notify-console-tabs"><button className={tab==="channels"?"active":""} onClick={()=>setTab("channels")}><Mail/>Csatornák</button>{management&&<><button className={tab==="documents"?"active":""} onClick={()=>setTab("documents")}><FileWarning/>Dolgozói dokumentumok</button><button className={tab==="supplier"?"active":""} onClick={()=>setTab("supplier")}><Truck/>Beszállítói lejáratok</button></>}</div>

  {tab==="channels"&&<div className="notify-console-panel">
   <div className="notify-channel-grid"><article><div className="notify-channel-title"><Mail/><div><b>E-mail értesítés</b><small>{prefs.email||"A belépett felhasználó e-mail-címe"}</small></div></div><label className="notify-switch"><input type="checkbox" checked={!!prefs.email_enabled} onChange={e=>setPrefs(p=>({...p,email_enabled:e.target.checked}))}/><span/>Bekapcsolva</label></article><article><div className="notify-channel-title"><Smartphone/><div><b>Push értesítés</b><small>{prefs.push_subscription_count||0} aktív eszköz · böngésző: {String(permission)}</small></div></div><div className="notify-push-actions">{prefs.push_subscription_count>0?<button onClick={()=>void disablePush()} disabled={saving}><XCircle/>Kikapcsolás ezen az eszközön</button>:<button onClick={()=>void enablePush()} disabled={saving||!pushSupported}><BellRing/>Push engedélyezése</button>}</div></article></div>
   <div className="notify-pref-box"><h3>Milyen eseményekről kérsz értesítést?</h3><label><input type="checkbox" checked={!!prefs.supplier_expiry} onChange={e=>setPrefs(p=>({...p,supplier_expiry:e.target.checked}))}/>Beszállítói / termék lejáratok</label><label><input type="checkbox" checked={!!prefs.employee_document} onChange={e=>setPrefs(p=>({...p,employee_document:e.target.checked}))}/>Dolgozói dokumentum- és szerződéslejáratok</label><label><input type="checkbox" checked={!!prefs.complaint_sla} onChange={e=>setPrefs(p=>({...p,complaint_sla:e.target.checked}))}/>Panaszkezelési SLA</label><label><input type="checkbox" checked={!!prefs.critical_only} onChange={e=>setPrefs(p=>({...p,critical_only:e.target.checked}))}/>Csak kritikus események</label><button className="notify-primary" onClick={()=>void savePreferences()} disabled={saving}><Save/>Beállítások mentése</button></div>
  </div>}

  {management&&tab==="documents"&&<div className="notify-console-panel notify-admin-grid"><form className="notify-admin-form" onSubmit={saveDoc}><h3><FileWarning/>{editingDoc?"Dokumentum szerkesztése":"Új dolgozói dokumentum"}</h3><label>Munkatárs<select required value={docForm.employee_id} onChange={e=>setDocForm((p:any)=>({...p,employee_id:e.target.value}))}><option value="">Válassz…</option>{employees.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select></label><label>Dokumentumtípus<select value={docForm.document_type} onChange={e=>setDocForm((p:any)=>({...p,document_type:e.target.value}))}><option>Képesítés</option><option>Orvosi alkalmasság</option><option>Engedély</option><option>Tanúsítvány</option><option>Bizonyítvány</option><option>Egyéb</option></select></label><label>Dokumentum neve{field("document_name",docForm.document_name,v=>setDocForm((p:any)=>({...p,document_name:v})),"text",true)}</label><label>Dokumentumszám{field("document_number",docForm.document_number,v=>setDocForm((p:any)=>({...p,document_number:v})))}</label><div className="notify-form-row"><label>Érvényesség kezdete{field("valid_from",docForm.valid_from,v=>setDocForm((p:any)=>({...p,valid_from:v})),"date")}</label><label>Lejárat{field("valid_until",docForm.valid_until,v=>setDocForm((p:any)=>({...p,valid_until:v})),"date")}</label></div><div className="notify-form-row"><label>Kiállítás{field("issued_at",docForm.issued_at,v=>setDocForm((p:any)=>({...p,issued_at:v})),"date")}</label><label>Egyedi figyelmeztetés (nap){field("warning_days",docForm.warning_days,v=>setDocForm((p:any)=>({...p,warning_days:v})),"number")}</label></div><label>Dokumentum URL{field("file_url",docForm.file_url,v=>setDocForm((p:any)=>({...p,file_url:v})),"url")}</label><label>Megjegyzés<textarea value={docForm.note} onChange={e=>setDocForm((p:any)=>({...p,note:e.target.value}))}/></label><div className="notify-form-actions">{editingDoc&&<button type="button" onClick={()=>{setEditingDoc(null);setDocForm(emptyDoc)}}>Mégse</button>}<button className="notify-primary" disabled={saving}><Save/>{editingDoc?"Módosítás mentése":"Dokumentum rögzítése"}</button></div></form><div className="notify-admin-list"><h3>Aktív dokumentumok <span>{activeDocs.length}</span></h3>{activeDocs.map(row=><article key={row.id}><div><b>{row.full_name||"Munkatárs"} · {row.document_name}</b><p>{row.document_type}{row.document_number?` · ${row.document_number}`:""}</p><small>Lejárat: {date(row.valid_until)}{row.warning_days!=null?` · ${row.warning_days} napos figyelmeztetés`:""}</small></div><div><button onClick={()=>editDoc(row)} title="Szerkesztés"><Pencil/></button><button onClick={()=>void deactivateDoc(String(row.id))} title="Inaktiválás"><Trash2/></button></div></article>)}{!activeDocs.length&&<p className="notify-admin-empty">Nincs aktív dokumentum.</p>}</div></div>}

  {management&&tab==="supplier"&&<div className="notify-console-panel notify-admin-grid"><form className="notify-admin-form" onSubmit={saveBatch}><h3><PackagePlus/>{editingBatch?"Lejárati tétel szerkesztése":"Új beszállítói lejárati tétel"}</h3><label>Termék<select required value={batchForm.product_id} onChange={e=>setBatchForm((p:any)=>({...p,product_id:e.target.value}))}><option value="">Válassz…</option>{products.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select></label><label>Beszállító<select value={batchForm.supplier_id} onChange={e=>setBatchForm((p:any)=>({...p,supplier_id:e.target.value}))}><option value="">Nincs megadva</option>{suppliers.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select></label><label>Szalon / telephely<select value={batchForm.location_id} onChange={e=>setBatchForm((p:any)=>({...p,location_id:e.target.value}))}><option value="">Központi / nincs megadva</option>{locations.map(x=><option key={x.id} value={x.id}>{label(x)}</option>)}</select></label><div className="notify-form-row"><label>LOT / sarzs{field("lot_number",batchForm.lot_number,v=>setBatchForm((p:any)=>({...p,lot_number:v})))}</label><label>Mennyiség{field("quantity",batchForm.quantity,v=>setBatchForm((p:any)=>({...p,quantity:v})),"number")}</label></div><div className="notify-form-row"><label>Beérkezés{field("received_at",batchForm.received_at,v=>setBatchForm((p:any)=>({...p,received_at:v})),"date",true)}</label><label>Lejárat{field("expires_at",batchForm.expires_at,v=>setBatchForm((p:any)=>({...p,expires_at:v})),"date")}</label></div><small className="notify-form-help">Ha a lejárat üres, a rendszer a beszállító törzsében beállított szavatossági időből számolja.</small><label>Megjegyzés<textarea value={batchForm.note} onChange={e=>setBatchForm((p:any)=>({...p,note:e.target.value}))}/></label><div className="notify-form-actions">{editingBatch&&<button type="button" onClick={()=>{setEditingBatch(null);setBatchForm(emptyBatch)}}>Mégse</button>}<button className="notify-primary" disabled={saving}><Save/>{editingBatch?"Módosítás mentése":"Tétel rögzítése"}</button></div></form><div className="notify-admin-list"><h3>Aktív lejárati tételek <span>{activeBatches.length}</span></h3>{activeBatches.map(row=><article key={row.id}><div><b>{row.product_name||"Termék"}{row.lot_number?` · ${row.lot_number}`:""}</b><p>{row.supplier_name||"Nincs beszállító"}{row.location_name?` · ${row.location_name}`:""}</p><small>Lejárat: {date(row.expires_at)}{row.quantity!=null?` · mennyiség: ${Number(row.quantity).toLocaleString("hu-HU")}`:""}</small></div><div><button onClick={()=>editBatch(row)} title="Szerkesztés"><Pencil/></button><button onClick={()=>void deactivateBatch(String(row.id))} title="Inaktiválás"><Trash2/></button></div></article>)}{!activeBatches.length&&<p className="notify-admin-empty">Nincs aktív lejárati tétel.</p>}</div></div>}
 </section>
}
