import React,{useEffect,useMemo,useRef,useState}from'react';
import{CreditCard,Radio,ScanLine,Settings2,UserCheck,UserMinus,Wifi,WifiOff}from'lucide-react';
import api from'../api/api';

type Location={id:string;name:string};
type Presence={employee_id:string;full_name:string;position_name?:string|null;clock_in?:string|null;clock_out?:string|null;present:boolean;uid_last4?:string|null;card_label?:string|null};
type Terminal={id:string;location_id:string;name:string;adapter_type:string;terminal_reference?:string|null;bridge_url?:string|null;currency:string;active:boolean;is_default:boolean;secret_configured?:boolean};
const time=(v?:string|null)=>v?new Date(v).toLocaleTimeString('hu-HU',{hour:'2-digit',minute:'2-digit'}):'—';

export default function ReceptionDeviceControlPanel(){
 const[locations,setLocations]=useState<Location[]>([]);const[locationId,setLocationId]=useState('');
 const[presence,setPresence]=useState<Presence[]>([]);const[terminals,setTerminals]=useState<Terminal[]>([]);
 const[scan,setScan]=useState('');const[scanMode,setScanMode]=useState<'attendance'|'assign'>('attendance');const[assignEmployee,setAssignEmployee]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
 const[terminalMessage,setTerminalMessage]=useState('');const[terminalBusy,setTerminalBusy]=useState(false);const[form,setForm]=useState({name:'Recepciós bankkártya terminál',adapter_type:'SIMULATOR',terminal_reference:'',bridge_url:'',secret_env_key:'',currency:'HUF',is_default:true});
 const scanRef=useRef<HTMLInputElement|null>(null);
 useEffect(()=>{void(async()=>{try{const r=await api.get('/transactions/workorder-editor/options');const ls=Array.isArray(r.data?.locations)?r.data.locations:[];setLocations(ls);setLocationId(String(r.data?.location?.id||r.data?.scope?.location_id||ls[0]?.id||''))}catch{}})()},[]);
 async function reload(){if(!locationId)return;try{const[p,t]=await Promise.all([api.get('/vir/device-control/rfid/presence',{params:{location_id:locationId}}),api.get('/vir/device-control/payment-terminals',{params:{location_id:locationId}})]);setPresence(Array.isArray(p.data)?p.data:[]);setTerminals(Array.isArray(t.data)?t.data:[])}catch(e:any){setMessage(e?.response?.data?.message||'Az eszközadatok nem tölthetők be.')}}
 useEffect(()=>{void reload()},[locationId]);
 useEffect(()=>{const id=window.setInterval(()=>{if(!document.hidden)void reload()},30000);return()=>window.clearInterval(id)},[locationId]);
 const presentCount=useMemo(()=>presence.filter(x=>x.present).length,[presence]);
 async function processScan(){const uid=scan.trim();if(!uid||!locationId)return;setBusy(true);setMessage('RFID feldolgozás…');try{if(scanMode==='assign'){if(!assignEmployee)throw new Error('Válassza ki, melyik munkatárshoz rendeli a kártyát.');const r=await api.post('/vir/device-control/rfid/cards',{location_id:locationId,employee_id:assignEmployee,uid,label:'Recepciós RFID'});setMessage(`${r.data?.full_name||'Munkatárs'} RFID-kártyája hozzárendelve.`);setScanMode('attendance')}else{const r=await api.post('/vir/device-control/rfid/scan',{location_id:locationId,uid});const action=r.data?.event_type==='CHECK_IN'?'beléptetve':r.data?.event_type==='CHECK_OUT'?'kiléptetve':'azonosítva';setMessage(`${r.data?.employee?.full_name||'Munkatárs'} ${action}.`)}setScan('');await reload()}catch(e:any){setMessage(e?.response?.data?.message||e?.message||'Az RFID művelet nem sikerült.')}finally{setBusy(false);window.setTimeout(()=>scanRef.current?.focus(),50)}}
 async function saveTerminal(){if(!locationId)return;setTerminalBusy(true);setTerminalMessage('Terminálbeállítás mentése…');try{const r=await api.post('/vir/device-control/payment-terminals',{...form,location_id:locationId});setTerminalMessage(`${r.data?.name||'Terminál'} beállítva (${r.data?.adapter_type}).`);await reload()}catch(e:any){setTerminalMessage(e?.response?.data?.message||e?.message||'A terminál nem állítható be.')}finally{setTerminalBusy(false)}}
 async function testBridge(t:Terminal){if(t.adapter_type==='SIMULATOR'){setTerminalMessage(`${t.name}: teszt adapter elérhető a VIR-en belül.`);return}if(!t.bridge_url){setTerminalMessage(`${t.name}: nincs bridge URL beállítva.`);return}setTerminalMessage(`${t.name}: helyi kapcsolat ellenőrzése…`);try{const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),4000);const r=await fetch(`${String(t.bridge_url).replace(/\/$/,'')}/health`,{signal:controller.signal});window.clearTimeout(timeout);if(!r.ok)throw new Error(`HTTP ${r.status}`);setTerminalMessage(`${t.name}: a helyi bridge elérhető.`)}catch(e:any){setTerminalMessage(`${t.name}: a bridge nem érhető el ebből a recepciós gépből (${e?.message||'kapcsolati hiba'}).`)}}
 return <section style={wrap}>
  <div style={head}><div><span style={eyebrow}>ESZKÖZVEZÉRLÉS</span><h2 style={{margin:'4px 0 0'}}>RFID jelenlét és bankkártya terminál</h2></div>{locations.length>1&&<label style={field}>Szalon<select style={input} value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}</div>
  <div style={grid}>
   <div style={card}>
    <div style={cardHead}><div><ScanLine size={20}/><div><b>RFID munkatársi jelenlét</b><span>{presentCount} fő jelenleg bent</span></div></div><div style={{display:'flex',gap:6}}><button style={smallButton} type="button" onClick={()=>{setScanMode('attendance');setMessage('Belépés/kilépés mód.');scanRef.current?.focus()}}>Jelenlét</button><button style={smallButton} type="button" onClick={()=>{setScanMode('assign');setMessage('Kártya-hozzárendelési mód.');scanRef.current?.focus()}}>Kártya rendelés</button></div></div>
    {scanMode==='assign'&&<label style={{...field,marginBottom:8}}>Munkatárs<select style={input} value={assignEmployee} onChange={e=>setAssignEmployee(e.target.value)}><option value="">Válasszon…</option>{presence.map(p=><option key={p.employee_id} value={p.employee_id}>{p.full_name}{p.position_name?` · ${p.position_name}`:''}</option>)}</select></label>}
    <label style={field}>{scanMode==='assign'?'Olvassa le a hozzárendelendő RFID-kártyát':'RFID olvasó aktív'}<input ref={scanRef} autoFocus style={{...input,fontFamily:'monospace',letterSpacing:1}} value={scan} disabled={busy} onChange={e=>setScan(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void processScan()}}} placeholder="Érintse a kártyát az olvasóhoz…"/></label>
    <p style={helper}>USB keyboard-wedge olvasónál a kártya UID + Enter kerül ide. A VIR csak a kártya hashét tárolja, a nyers UID-t nem.</p>
    {message&&<div style={notice}>{message}</div>}
    <div style={people}>{presence.map(p=><div key={p.employee_id} style={{...person,borderColor:p.present?'#86d3a3':'#e5e7eb'}}><div style={{display:'flex',alignItems:'center',gap:8}}>{p.present?<UserCheck size={18}/>:<UserMinus size={18}/>}<div><b>{p.full_name}</b><small>{p.position_name||'Munkatárs'}</small></div></div><div style={{textAlign:'right'}}><b>{p.present?'BENT':'NINCS BENT'}</b><small>{p.clock_in?`Be: ${time(p.clock_in)}`:'Még nem érkezett'}{p.clock_out?` · Ki: ${time(p.clock_out)}`:''}</small><small>{p.uid_last4?`RFID: ••••${p.uid_last4}`:'Nincs kártya'}</small></div></div>)}</div>
   </div>
   <div style={card}>
    <div style={cardHead}><div><CreditCard size={20}/><div><b>Bankkártya terminál</b><span>{terminals.length?`${terminals.length} konfigurált eszköz`:'Nincs konfigurálva'}</span></div></div><Settings2 size={18}/></div>
    <div style={terminalList}>{terminals.map(t=><div key={t.id} style={terminalRow}><div style={{display:'flex',gap:8,alignItems:'center'}}>{t.adapter_type==='SIMULATOR'?<Radio size={17}/>:t.bridge_url?<Wifi size={17}/>:<WifiOff size={17}/>}<div><b>{t.name}{t.is_default?' · alapértelmezett':''}</b><small>{t.adapter_type} · {t.currency}{t.terminal_reference?` · ${t.terminal_reference}`:''}</small></div></div><button type="button" style={smallButton} onClick={()=>void testBridge(t)}>Kapcsolat teszt</button></div>)}</div>
    <h3 style={{margin:'14px 0 8px'}}>Terminál hozzáadása / beállítása</h3><div style={formGrid}><label style={field}>Név<input style={input} value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label style={field}>Adapter<select style={input} value={form.adapter_type} onChange={e=>setForm(v=>({...v,adapter_type:e.target.value}))}><option value="SIMULATOR">SIMULATOR – teszt</option><option value="LOCAL_BRIDGE">LOCAL_BRIDGE – helyi terminál</option><option value="CLOUD_API">CLOUD_API – szolgáltatói API</option></select></label><label style={field}>Terminál azonosító<input style={input} value={form.terminal_reference} onChange={e=>setForm(v=>({...v,terminal_reference:e.target.value}))} placeholder="pl. POS-RECEP-01"/></label><label style={field}>Pénznem<input style={input} value={form.currency} maxLength={3} onChange={e=>setForm(v=>({...v,currency:e.target.value.toUpperCase()}))}/></label><label style={{...field,gridColumn:'1/-1'}}>Bridge / API URL<input style={input} value={form.bridge_url} onChange={e=>setForm(v=>({...v,bridge_url:e.target.value}))} placeholder="http://127.0.0.1:8787 vagy helyi LAN cím"/></label><label style={{...field,gridColumn:'1/-1'}}>Szerver oldali titok környezeti változó neve<input style={input} value={form.secret_env_key} onChange={e=>setForm(v=>({...v,secret_env_key:e.target.value}))} placeholder="pl. KLEO_TERMINAL_SECRET_RECEP"/></label></div>
    <label style={{display:'flex',gap:8,alignItems:'center',fontSize:13,marginTop:8}}><input type="checkbox" checked={form.is_default} onChange={e=>setForm(v=>({...v,is_default:e.target.checked}))}/> Alapértelmezett terminál ezen a telephelyen</label>
    <button type="button" style={primary} disabled={terminalBusy||!locationId} onClick={()=>void saveTerminal()}>{terminalBusy?'Mentés…':'Terminálbeállítás mentése'}</button>
    {terminalMessage&&<div style={notice}>{terminalMessage}</div>}<p style={helper}>Fizikai terminálnál a helyi bridge fordítja le a VIR parancsát a banki terminál gyártójának ECR/SDK protokolljára. A konkrét bridge adapterhez a terminál márkája és típusa szükséges.</p>
   </div>
  </div>
 </section>
}
const wrap:React.CSSProperties={margin:'0 24px 16px',border:'1px solid #eadfe4',borderRadius:18,background:'#fff',padding:16,boxShadow:'0 8px 24px rgba(52,35,44,.05)'};const head:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'end',flexWrap:'wrap',marginBottom:12};const eyebrow:React.CSSProperties={color:'#9c2d65',fontWeight:900,fontSize:11,letterSpacing:'.09em'};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:12};const card:React.CSSProperties={border:'1px solid #eee5e9',borderRadius:14,padding:13,minWidth:0};const cardHead:React.CSSProperties={display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:10};const field:React.CSSProperties={display:'grid',gap:5,fontSize:12,fontWeight:800};const input:React.CSSProperties={height:39,border:'1px solid #d9cdd3',borderRadius:9,padding:'0 9px',width:'100%',boxSizing:'border-box'};const helper:React.CSSProperties={fontSize:11,color:'#76676e',lineHeight:1.45};const notice:React.CSSProperties={padding:'9px 10px',borderRadius:9,background:'#f7f4f6',fontSize:12,marginTop:8};const people:React.CSSProperties={display:'grid',gap:6,maxHeight:320,overflow:'auto',marginTop:10};const person:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',border:'1px solid',borderRadius:10,padding:'8px 9px'};const terminalList:React.CSSProperties={display:'grid',gap:6};const terminalRow:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',padding:'8px 9px',border:'1px solid #ece6e9',borderRadius:10};const smallButton:React.CSSProperties={border:'1px solid #dfd3d9',background:'#fff',borderRadius:8,padding:'7px 9px',cursor:'pointer',fontWeight:750,fontSize:12};const formGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'1fr 1fr',gap:8};const primary:React.CSSProperties={width:'100%',marginTop:10,border:0,borderRadius:10,padding:'10px 12px',background:'#2d2227',color:'#fff',fontWeight:900,cursor:'pointer'};
