import type { Language } from '../i18n/LanguageProvider';

const HU_ALIASES: Record<string, string> = {
  'Check listák': 'Ellenőrzőlisták',
  'Tudástár': 'Tudásbázis',
  'Időpontok és jelenlét': 'Időpontok és beosztás',
  'Beszerzési dashboard': 'Beszerzési áttekintés',
  'Jóváhagyásra vár': 'Jóváhagyásra váró tételek',
  'Készlet áttekintés': 'Készletáttekintés',
  'Sarzs és lejárat (FEFO)': 'Sarzsok és lejáratok (FEFO)',
  'Nyugta / NAV adatszolgáltatás': 'Nyugta és NAV-adatszolgáltatás',
  'Bér és járulék': 'Bérszámfejtés és járulékok',
  'Munkatársak és bérforrások': 'Munkatársak és bérezési adatok',
  'Ügyfelek / vevők': 'Ügyfelek és vevők',
  'Telephelyek / költséghelyek': 'Telephelyek és költséghelyek',
  'Könyvelési tudástár': 'Könyvelési tudásbázis',
  'VIR Admin': 'VIR adminisztráció',
  'VIR specifikáció': 'VIR megfelelőségi ellenőrzés',
  'WallBoard / TV napi akció': 'TV napi akciók (WallBoard)',
  'SaaS / Franchise központ': 'SaaS és franchise központ',
  'Öltözőszekrények – 20 rekesz': 'Öltözőszekrények',
  'Importálás és duplikációkezelés': 'Munkatárs-import és duplikációkezelés',
  'Besorolás ellenőrzése': 'Termékbesorolás ellenőrzése',
  'Social Hub': 'Közösségi média',
  'Franchise funnel / Mailchimp': 'Franchise érdeklődők és Mailchimp',
  'Kampánylink / UTM': 'Kampánylink és UTM',
  'Marketing ROI Dashboard': 'Marketing ROI',
  'Rendszerellenőrzés': 'Rendszerállapot',
  'UAT tesztközpont': 'Átvételi tesztközpont (UAT)',
  'Audit és rendszeresemény-napló': 'Audit- és rendszeresemény-napló',
  'Dolgozói értékelések': 'Munkatársi értékelések',
};

const EN: Record<string, string> = {
  'Irányítópult': 'Dashboard',
  'Időpontfoglalás': 'Book appointment',
  'Saját munkalapjaim': 'My work orders',
  'Saját beosztás': 'My schedule',
  'Saját munkalapok': 'My work orders',
  'Ellenőrzőlisták': 'Checklists',
  'Tudásbázis': 'Knowledge base',
  'Munkaköri teszt': 'Job knowledge test',
  'Időpontok és beosztás': 'Appointments & schedule',
  'Időpontnaptár': 'Appointment calendar',
  'Munkalapok': 'Work orders',
  'Raktár és készlet': 'Inventory',
  'Készlet': 'Stock',
  'Termékek': 'Products',
  'Sarzsok és lejáratok (FEFO)': 'Batches & expiry (FEFO)',
  'Beszerzés': 'Procurement',
  'Pénzügyek': 'Finance',
  'Pénzügyi áttekintés': 'Finance overview',
  'NAV Online Számla': 'NAV Online Invoice',
  'Nyugta és NAV-adatszolgáltatás': 'Receipts & NAV reporting',
  'Számlák és bizonylatok': 'Invoices & documents',
  'Pénzügyi ellenőrzés': 'Financial control',
  'Bérszámfejtés és járulékok': 'Payroll & contributions',
  'Beszerzési áttekintés': 'Procurement overview',
  'Jóváhagyások': 'Approvals',
  'Jóváhagyásra váró tételek': 'Items awaiting approval',
  'Rendelések': 'Orders',
  'Beszerzési rendelések': 'Purchase orders',
  'Beszállítók': 'Suppliers',
  'Készletáttekintés': 'Inventory overview',
  'Készletműveletek': 'Inventory operations',
  'Könyvelési adatok': 'Accounting data',
  'Lezárt munkalapok': 'Closed work orders',
  'Munkatársak és bérezési adatok': 'Staff & compensation data',
  'Ügyfelek és vevők': 'Customers & clients',
  'Beszállítói törzs': 'Supplier master data',
  'Telephelyek és költséghelyek': 'Locations & cost centers',
  'Fizetési módok': 'Payment methods',
  'Pénzügyi tranzakciótípusok': 'Financial transaction types',
  'Raktárak': 'Warehouses',
  'Riportok és kimutatások': 'Reports & statements',
  'Könyvelési tudásbázis': 'Accounting knowledge base',
  'VIR megfelelőségi ellenőrzés': 'ERP specification compliance',
  'TV napi akciók (WallBoard)': 'TV daily deals (WallBoard)',
  'SaaS és franchise központ': 'SaaS & franchise center',
  'VIR adminisztráció': 'ERP administration',
  'Fitnesz – Gyöngyös': 'Fitness – Gyöngyös',
  'Áttekintés és bérletek': 'Overview & passes',
  'Öltözőszekrények': 'Lockers',
  'Munkatárs-import és duplikációkezelés': 'Staff import & duplicate handling',
  'Termékbesorolás ellenőrzése': 'Product classification review',
  'Közösségi média': 'Social media',
  'Franchise érdeklődők és Mailchimp': 'Franchise leads & Mailchimp',
  'Kampánylink és UTM': 'Campaign link & UTM',
  'Marketing ROI': 'Marketing ROI',
  'Rendszerállapot': 'System status',
  'Átvételi tesztközpont (UAT)': 'Acceptance test center (UAT)',
  'Audit- és rendszeresemény-napló': 'Audit & system event log',
  'Munkatársi értékelések': 'Staff evaluations',
  'Beállítások és adminisztráció': 'Settings & administration',
  'Rendszerbeállítások': 'System settings',
};

export function canonicalMenuLabel(label: string): string {
  const clean = String(label || '').trim();
  return HU_ALIASES[clean] || clean;
}

export function menuLabel(label: string, language: Language): string {
  const canonical = canonicalMenuLabel(label);
  return language === 'en' ? EN[canonical] || canonical : canonical;
}
