import React,{useMemo,useState}from'react';
import{AlertTriangle,BookOpen,Calculator,CalendarClock,CheckCircle2,ExternalLink,FileSpreadsheet,Landmark,ReceiptText,Scale,Search}from'lucide-react';

type Deadline={title:string;date:string;kind:string;note:string};
const deadlines:Deadline[]=[
 {title:'Havi 08-as bevallás és közterhek',date:'2026-09-14',kind:'Bér / járulék',note:'Kifizetésekkel, juttatásokkal összefüggő havi bevallás és befizetés.'},
 {title:'ÁFA bevallás és befizetés',date:'2026-08-24',kind:'ÁFA',note:'A 2665 nyomtatvány NAV szerinti következő havi esedékessége.'},
 {title:'Következő ÁFA határidő',date:'2026-09-21',kind:'ÁFA',note:'Következő NAV szerinti havi bevallási/befizetési határidő.'},
 {title:'TAO-előleg – negyedéves általános szabály',date:'2026-09-10',kind:'TAO',note:'Érintettséget és tényleges előlegkötelezettséget adófolyószámla alapján ellenőrizni kell.'},
];
const sources=[
 {title:'Számviteli törvény – 2000. évi C. törvény',url:'https://njt.hu/jogszabaly/2000-100-00-00',tag:'Jogszabály'},
 {title:'NAV – 2665 ÁFA bevallás',url:'https://nav.gov.hu/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvanykitolto_programok_nav/2665',tag:'NAV'},
 {title:'NAV – 2608 havi járulékbevallás',url:'https://nav.gov.hu/nyomtatvanyok/letoltesek/nyomtatvanykitolto_programok/nyomtatvanykitolto_programok_nav/2608',tag:'NAV'},
 {title:'NAV – eÁFA Tool és kézikönyv',url:'https://nav.gov.hu/sajtoszoba/hirek/gyorsabb-es-egyszerubb-bevallas-elokeszites-erkezik-az-eafa-tool',tag:'Segédlet'},
];
const tasks=['Bejövő számlák teljességének ellenőrzése','NAV Online Számla eltérések ellenőrzése','Bank és pénztár egyeztetése','Lezárt munkalapok és számlák egyeztetése','ÁFA analitika ellenőrzése','Szállítói és vevői nyitott tételek ellenőrzése','Bér/járulék feladás ellenőrzése','Havi zárási checklist lezárása'];
const fmt=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString('hu-HU',{year:'numeric',month:'short',day:'numeric'});
export default function AccountingWorkspaceV2(){const[done,setDone]=useState<Record<string,boolean>>({});const[q,setQ]=useState('');const today='2026-08-14';const ordered=useMemo(()=>[...deadlines].sort((a,b)=>a.date.localeCompare(b.date)),[]);const filtered=sources.filter(x=>(x.title+x.tag).toLowerCase().includes(q.toLowerCase()));return <div style={{display:'grid',gap:18,marginBottom:22}}>
 <section style={hero}><div><span style={eyebrow}>KÖNYVELŐI MUNKATÉR</span><h2 style={{margin:'4px 0 5px'}}>Határidők és aktuális teendők</h2><p style={muted}>A határidők tájékoztató jellegűek; a cég tényleges adózási gyakoriságát és kötelezettségét a NAV törzsadat/adófolyószámla alapján kell ellenőrizni.</p></div><CalendarClock size={34}/></section>
 <section style={grid2}><article style={card}><h3 style={title}><CalendarClock size={18}/> Következő határidők</h3>{ordered.map(d=>{const days=Math.ceil((new Date(d.date+'T12:00:00').getTime()-new Date(today+'T12:00:00').getTime())/86400000);return <div key={d.title} style={row}><span><b>{d.title}</b><small style={muted}>{d.kind} · {d.note}</small></span><span style={{...badge,background:days<=10?'#fff0f0':'#fff8e8',color:days<=10?'#a72d2d':'#805b18'}}>{fmt(d.date)} · {days} nap</span></div>})}</article>
 <article style={card}><h3 style={title}><CheckCircle2 size={18}/> Havi zárási teendők</h3>{tasks.map(t=><label key={t} style={check}><input type='checkbox' checked={!!done[t]} onChange={()=>setDone(v=>({...v,[t]:!v[t]}))}/><span style={done[t]?{textDecoration:'line-through',opacity:.55}:{}}>{t}</span></label>)}</article></section>
 <section style={card}><h3 style={title}><Calculator size={18}/> Könyvelői segédalkalmazások és kimutatások</h3><div style={tools}>
  <Tool icon={<ReceiptText/>} title='ÁFA kontroll' text='Fizetendő/levonható ÁFA, eltérések, hiányzó bizonylatok és NAV-egyezőség.' href='/finance?section=control'/>
  <Tool icon={<Landmark/>} title='Bank–pénztár egyeztetés' text='Napi és havi pénzmozgások, kasszazárások és eltérések.' href='/finance'/>
  <Tool icon={<FileSpreadsheet/>} title='Vevő–szállító analitika' text='Nyitott tételek, lejárt követelések, kötelezettségek és korosítás.' href='/finance?section=control'/>
  <Tool icon={<Calculator/>} title='Havi zárás' text='Bevétel, költség, eredmény, ÁFA és telephelyi bontás ellenőrző nézet.' href='/finance'/>
  <Tool icon={<AlertTriangle/>} title='Eltérésfigyelő' text='Munkalap–számla–fizetés eltérések és hiányzó kapcsolatok.' href='/finance?section=control'/>
  <Tool icon={<FileSpreadsheet/>} title='Export központ' text='Könyvelési Excel/CSV exportok és időszaki kimutatások előkészítése.' href='/finance'/>
 </div></section>
 <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><h3 style={title}><BookOpen size={18}/> Könyvelési tudástár – hivatalos források</h3><label style={search}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Keresés a tudástárban…'/></label></div><div style={tools}>{filtered.map(s=><a key={s.url} href={s.url} target='_blank' rel='noreferrer' style={source}><Scale size={18}/><span><b>{s.title}</b><small style={muted}>{s.tag} · hivatalos forrás</small></span><ExternalLink size={15}/></a>)}</div><p style={{...muted,marginTop:12}}>A tudástárban jogszabályszöveg helyett a mindenkori hivatalos NJT/NAV forrásra mutató hivatkozás szerepel, így nem rögzítünk elavuló jogszabálymásolatot.</p></section>
 </div>}
function Tool({icon,title,text,href}:{icon:React.ReactNode;title:string;text:string;href:string}){return <a href={href} style={tool}><span style={toolIcon}>{icon}</span><span><b>{title}</b><small style={muted}>{text}</small></span></a>}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e8dfd7',borderRadius:16,padding:17,boxShadow:'0 5px 18px rgba(43,33,24,.05)'};const hero:React.CSSProperties={...card,display:'flex',justifyContent:'space-between',gap:15,alignItems:'center',background:'linear-gradient(135deg,#fff,#f7f0e9)'};const eyebrow:React.CSSProperties={fontSize:11,fontWeight:900,letterSpacing:'.1em',color:'#8a6b4d'};const muted:React.CSSProperties={display:'block',fontSize:12,color:'#667085',lineHeight:1.45,marginTop:4};const title:React.CSSProperties={display:'flex',alignItems:'center',gap:7,margin:'0 0 12px',fontSize:16};const grid2:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:14};const row:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,padding:'10px 0',borderBottom:'1px solid #f0e8e1',alignItems:'center'};const badge:React.CSSProperties={fontSize:11,fontWeight:900,padding:'5px 8px',borderRadius:999,whiteSpace:'nowrap'};const check:React.CSSProperties={display:'flex',gap:9,alignItems:'center',padding:'8px 0',fontSize:13,fontWeight:700};const tools:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10};const tool:React.CSSProperties={display:'flex',gap:10,textDecoration:'none',color:'#2b2118',border:'1px solid #eee4dc',borderRadius:12,padding:12,background:'#fcfaf8'};const toolIcon:React.CSSProperties={display:'grid',placeItems:'center',width:36,height:36,borderRadius:10,background:'#f2e9df',color:'#6d5139',flex:'0 0 auto'};const source:React.CSSProperties={...tool,alignItems:'center'};const search:React.CSSProperties={display:'flex',alignItems:'center',gap:6,border:'1px solid #ddd3ca',borderRadius:9,padding:'7px 9px'};