import React,{useCallback,useEffect,useMemo,useState}from"react";
import{ArrowLeftRight,Calculator,Landmark,PlusCircle,RefreshCw}from"lucide-react";
import api from"../../api";
import"./CashierAltegioOperationsPanel.css";

type Account={id:string;name:string;account_type?:string;allow_cash?:boolean;allow_cashless?:boolean;current_balance?:number|string};
type DocType={code:string;name:string;direction?:string};
type Partner={id:string|number;name:string};
type Shift={id:string|number;status:string;business_date?:string;opening_cash?:number|string;current_cashier?:string};
type Count={id:string|number;count_type:string;counted_cash:number|string;expected_cash:number|string;difference:number|string;created_at?:string;created_by?:string};
type Props={disabled?:boolean;onChanged?:()=>void};
const DENOMS=[20000,10000,5000,2000,1000,500,200,100,50,20,10,5];
const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const localDate=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const emptyDenoms=()=>Object.fromEntries(DENOMS.map(v=>[String(v),0])) as Record<string,number>;

export default function CashierAltegioOperationsPanel({disabled,onChanged}:Props){
 const locationId=localStorage.getItem("kleo_location_id")||"";
 const[accounts,setAccounts]=useState<Account[]>([]),[types,setTypes]=useState<DocType[]>([]),[partners,setPartners]=useState<Partner[]>([]),[shift,setShift]=useState<Shift|null>(null),[counts,setCounts]=useState<Count[]>([]),[previous,setPrevious]=useState<Count|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const[denoms,setDenoms]=useState<Record<string,number>>(emptyDenoms),[countNote,setCountNote]=useState("");
 const[direction,setDirection]=useState<"income"|"expense">("expense"),[accountId,setAccountId]=useState(""),[amount,setAmount]=useState(0),[docType,setDocType]=useState(""),[partnerId,setPartnerId]=useState(""),[employeeId,setEmployeeId]=useState(""),[referenceNo,setReferenceNo]=useState(""),[note,setNote]=useState("");
 const[fromAccount,setFromAccount]=useState(""),[toAccount,setToAccount]=useState(""),[transferAmount,setTransferAmount]=useState(0),[transferRef,setTransferRef]=useState(""),[transferNote,setTransferNote]=useState("");
 const counted=useMemo(()=>DENOMS.reduce((sum,v)=>sum+v*Number(denoms[String(v)]||0),0),[denoms]);
 const qs=locationId?`?location_id=${encodeURIComponent(locationId)}`:"";
 const load=useCallback(async()=>{if(!locationId)return;setBusy(true);setError("");try{const[a,t,p,s]=await Promise.all([api.get(`/api/transactions/cashier/altegio/accounts${qs}`),api.get(`/api/transactions/cashier/altegio/document-types${qs}`),api.get(`/api/transactions/cashier/altegio/partners${qs}`),api.get(`/api/transactions/cashier/shift/current${qs}`)]);setAccounts(Array.isArray(a.data)?a.data:[]);setTypes(Array.isArray(t.data)?t.data:[]);setPartners(Array.isArray(p.data)?p.data:[]);const current=s.data?.shift||s.data||null;setShift(current?.status==="open"?current:null);if(current?.id){const[c,prev]=await Promise.all([api.get(`/api/transactions/cashier/shift/${current.id}/counts${qs}`),api.get(`/api/transactions/cashier/shift/previous-count${qs}&date=${localDate()}`).catch(()=>({data:null}))]);setCounts(Array.isArray(c.data)?c.data:[]);setPrevious(prev.data||null)}else{setCounts([]);setPrevious(null)}setAccountId(v=>v||String(a.data?.[0]?.id||""))}catch(e:any){setError(e?.response?.data?.message||"Az Altegio pénztári kiegészítő adatok nem tölthetők be.")}finally{setBusy(false)}},[locationId,qs]);
 useEffect(()=>{void load()},[load]);
 const done=async(msg:string)=>{setNotice(msg);setError("");await load();onChanged?.()};
 async function saveCount(countType:"check"|"handover"|"closing"){if(!shift)return;setBusy(true);try{await api.post(`/api/transactions/cashier/shift/${shift.id}/count`,{location_id:locationId,count_type:countType,denominations:denoms,counted_cash:counted,note:countNote||null});setDenoms(emptyDenoms());setCountNote("");await done(countType==="check"?"A köztes címletszámolás elmentve.":countType==="handover"?"Az átadás előtti címletszámolás elmentve.":"A záró címletszámolás elmentve.")}catch(e:any){setError(e?.response?.data?.message||"A címletszámolás nem menthető.")}finally{setBusy(false)}}
 async function manualOperation(){if(!accountId||amount<=0||!docType)return;setBusy(true);try{await api.post("/api/transactions/cashier/manual-operation",{location_id:locationId,account_id:accountId,direction,amount,document_type_code:docType,partner_id:partnerId||null,employee_id:employeeId||null,reference_no:referenceNo||null,note:note||null});setAmount(0);setReferenceNo("");setNote("");await done("A manuális pénzügyi tranzakció rögzítve.")}catch(e:any){setError(e?.response?.data?.message||"A manuális tranzakció nem menthető.")}finally{setBusy(false)}}
 async function transfer(){if(!fromAccount||!toAccount||fromAccount===toAccount||transferAmount<=0)return;setBusy(true);try{await api.post("/api/transactions/cashier/account-transfer",{location_id:locationId,source_account_id:fromAccount,destination_account_id:toAccount,amount:transferAmount,reference_no:transferRef||null,note:transferNote||null});setTransferAmount(0);setTransferRef("");setTransferNote("");await done("A pénztárak/számlák közötti átvezetés rögzítve.")}catch(e:any){setError(e?.response?.data?.message||"Az átvezetés nem sikerült.")}finally{setBusy(false)}}
 return <section className="cashier-altegio-panel cashier-card"><div className="cashier-altegio-panel__head"><div><span className="eyebrow">ALTEGIO PÉNZTÁRI FUNKCIÓK</span><h2><Landmark size={20}/> Pénztárak, számlák és ellenőrzés</h2><p>Több pénzügyi számla, címletszámolás, manuális bevétel/kiadás és átvezetés.</p></div><button onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Frissítés</button></div>{error&&<div className="cashier-altegio-panel__message is-error">{error}</div>}{notice&&<div className="cashier-altegio-panel__message is-ok">{notice}</div>}
 <div className="cashier-altegio-panel__accounts">{accounts.map(a=><article key={a.id}><span>{a.account_type==="cash"?"Készpénzes pénztár":"Készpénz nélküli számla"}</span><b>{a.name}</b><strong>{fmt(a.current_balance)}</strong></article>)}{!accounts.length&&<p>Nincs aktív pénzügyi számla.</p>}</div>
 <div className="cashier-altegio-panel__grid"><div className="cashier-altegio-panel__box"><h3><Calculator size={17}/> Címletszámolás</h3>{previous&&<div className="cashier-altegio-panel__previous">Előző záró: <b>{fmt(previous.counted_cash)}</b> · eltérés {fmt(previous.difference)}</div>}<div className="cashier-altegio-panel__denoms">{DENOMS.map(v=><label key={v}><span>{v.toLocaleString("hu-HU")} Ft</span><input type="number" min="0" step="1" value={denoms[String(v)]||0} onChange={e=>setDenoms(d=>({...d,[String(v)]:Math.max(0,Math.floor(Number(e.target.value||0)))}))}/><small>{fmt(v*Number(denoms[String(v)]||0))}</small></label>)}</div><div className="cashier-altegio-panel__count-total"><span>Megszámolt készpénz</span><b>{fmt(counted)}</b></div><label>Megjegyzés<input value={countNote} onChange={e=>setCountNote(e.target.value)} placeholder="Eltérés oka / átadási megjegyzés"/></label><div className="cashier-altegio-panel__buttons"><button disabled={disabled||busy||!shift} onClick={()=>void saveCount("check")}>Köztes ellenőrzés</button><button disabled={disabled||busy||!shift} onClick={()=>void saveCount("handover")}>Átadás előtti számolás</button><button disabled={disabled||busy||!shift} onClick={()=>void saveCount("closing")}>Záró számolás</button></div>{counts.length>0&&<div className="cashier-altegio-panel__history"><b>Mai számolások</b>{counts.slice(0,6).map(c=><span key={String(c.id)}>{c.count_type} · {fmt(c.counted_cash)} · eltérés {fmt(c.difference)}</span>)}</div>}</div>
 <div className="cashier-altegio-panel__side"><div className="cashier-altegio-panel__box"><h3><PlusCircle size={17}/> Manuális bevétel / kiadás</h3><div className="cashier-altegio-panel__toggle"><button className={direction==="income"?"active":""} onClick={()=>setDirection("income")}>Bevétel</button><button className={direction==="expense"?"active":""} onClick={()=>setDirection("expense")}>Kiadás</button></div><label>Pénztár / számla<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Válasszon…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Tranzakció típusa<select value={docType} onChange={e=>setDocType(e.target.value)}><option value="">Válasszon…</option>{types.filter(t=>!t.direction||t.direction==="both"||t.direction===direction).map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></label><label>Összeg<input type="number" min="0" value={amount} onChange={e=>setAmount(Number(e.target.value||0))}/></label><label>Partner<select value={partnerId} onChange={e=>setPartnerId(e.target.value)}><option value="">Nincs / válasszon…</option>{partners.map(p=><option key={String(p.id)} value={String(p.id)}>{p.name}</option>)}</select></label><label>Alkalmazott azonosító<input value={employeeId} onChange={e=>setEmployeeId(e.target.value)} placeholder="Opcionális"/></label><label>Hivatkozási / bizonylatszám<input value={referenceNo} onChange={e=>setReferenceNo(e.target.value)}/></label><label>Megjegyzés<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="is-primary" disabled={disabled||busy||!accountId||amount<=0||!docType} onClick={()=>void manualOperation()}>Tranzakció rögzítése</button></div>
 <div className="cashier-altegio-panel__box"><h3><ArrowLeftRight size={17}/> Pénztár / számla átvezetés</h3><label>Forrás<select value={fromAccount} onChange={e=>setFromAccount(e.target.value)}><option value="">Válasszon…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Cél<select value={toAccount} onChange={e=>setToAccount(e.target.value)}><option value="">Válasszon…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Összeg<input type="number" min="0" value={transferAmount} onChange={e=>setTransferAmount(Number(e.target.value||0))}/></label><label>Hivatkozási szám<input value={transferRef} onChange={e=>setTransferRef(e.target.value)}/></label><label>Megjegyzés<input value={transferNote} onChange={e=>setTransferNote(e.target.value)}/></label><button disabled={disabled||busy||!fromAccount||!toAccount||fromAccount===toAccount||transferAmount<=0} onClick={()=>void transfer()}>Átvezetés rögzítése</button></div></div></div></section>;
}
