import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ArrowDownToLine,ArrowLeftRight,ArrowUpFromLine,Banknote,Calculator,CheckCircle2,LockKeyhole,Plus,RefreshCw,Store,UserRoundCheck}from'lucide-react';
import api from'../../api';
import'./CashRegisterSessionPanel.css';

type Register={id:string|number;name:string;register_type?:'cash'|'cashless';opening_balance?:number|string;comment?:string;open_session_id?:string|number;opened_by?:string;shift_no?:number};
type Movement={id:string|number;direction:'in'|'out';amount:number|string;reason:string;movement_type?:string;reference_no?:string;created_by?:string;created_at?:string};
type Session={id:string|number;register_id:string|number;status:'open'|'closed';opening_cash:number|string;opened_at?:string;opened_by?:string;closed_at?:string;closed_by?:string;counted_cash?:number|string;expected_cash?:number|string;difference?:number|string;shift_no?:number};
type Count={id:string|number;count_type:'opening'|'check'|'handover'|'closing';counted_cash:number|string;expected_cash:number|string;difference:number|string;handed_to?:string;created_by?:string;created_at?:string};
type RegisterState={business_date:string;location_id:string;register:Register;registers:Register[];session?:Session|null;movements?:Movement[];counts?:Count[];cash_sales?:number;cash_in?:number;cash_out?:number;expected_cash?:number};
type History={previous_closing_count?:Count&{business_date?:string}|null;counts?:Count[];sessions?:Session[]};
type Props={onChanged?:()=>void};

const DENOMS=[20000,10000,5000,2000,1000,500,200,100,50,20,10,5];
const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString('hu-HU')} Ft`;
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dt=(v?:string)=>v?new Date(v).toLocaleString('hu-HU'):'—';
const emptyDenoms=()=>Object.fromEntries(DENOMS.map(x=>[String(x),0])) as Record<string,number>;

export default function CashRegisterSessionPanel({onChanged}:Props){
 const[state,setState]=useState<RegisterState|null>(null),[history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[selectedRegister,setSelectedRegister]=useState(''),[denoms,setDenoms]=useState<Record<string,number>>(emptyDenoms),[manualCount,setManualCount]=useState('');
 const[openingCash,setOpeningCash]=useState(0),[openNote,setOpenNote]=useState('');
 const[direction,setDirection]=useState<'in'|'out'>('in'),[movementAmount,setMovementAmount]=useState(0),[movementReason,setMovementReason]=useState(''),[movementType,setMovementType]=useState('manual'),[referenceNo,setReferenceNo]=useState('');
 const[checkNote,setCheckNote]=useState(''),[handedTo,setHandedTo]=useState('');
 const[transferTo,setTransferTo]=useState(''),[transferAmount,setTransferAmount]=useState(0),[transferNote,setTransferNote]=useState('');
 const[newName,setNewName]=useState(''),[newType,setNewType]=useState<'cash'|'cashless'>('cash'),[newOpening,setNewOpening]=useState(0),[showNew,setShowNew]=useState(false);
 const locationId=localStorage.getItem('kleo_location_id')||'',locationName=localStorage.getItem('kleo_location_name')||'Kiválasztott szalon',today=localDate();
 const register=state?.register,session=state?.session||null,isOpen=session?.status==='open',isCash=(register?.register_type||'cash')==='cash';
 const denominationTotal=useMemo(()=>DENOMS.reduce((sum,v)=>sum+v*Number(denoms[String(v)]||0),0),[denoms]);
 const countedValue=isCash?denominationTotal:Number(manualCount||0),differencePreview=countedValue-Number(state?.expected_cash||0);
 const otherOpenRegisters=(state?.registers||[]).filter(r=>String(r.id)!==String(register?.id)&&r.open_session_id);

 const load=useCallback(async(registerId?:string)=>{if(!locationId){setState(null);setError('A pénztár használatához előbb válasszon telephelyet.');return}setLoading(true);setError('');try{const rid=registerId||selectedRegister;const q=`date=${today}&location_id=${encodeURIComponent(locationId)}${rid?`&register_id=${encodeURIComponent(rid)}`:''}`;const r=await api.get(`/api/transactions/cashier/register-state?${q}`);setState(r.data);const actual=String(r.data?.register?.id||'');if(actual&&actual!==selectedRegister)setSelectedRegister(actual);if(actual){const h=await api.get(`/api/transactions/cashier/register-history?date=${today}&location_id=${encodeURIComponent(locationId)}&register_id=${encodeURIComponent(actual)}`);setHistory(h.data||null)}}catch(e:any){setError(e?.response?.data?.message||'A pénztár állapota nem tölthető be.')}finally{setLoading(false)}},[locationId,today,selectedRegister]);
 useEffect(()=>{void load()},[]);
 const changed=async(message:string,registerId?:string)=>{setNotice(message);setDenoms(emptyDenoms());setManualCount('');await load(registerId);onChanged?.()};
 async function chooseRegister(id:string){setSelectedRegister(id);setNotice('');setError('');setDenoms(emptyDenoms());setManualCount('');await load(id)}
 async function createRegister(){if(!newName.trim())return;setLoading(true);setError('');try{const r=await api.post('/api/transactions/cashier/registers',{location_id:locationId,name:newName.trim(),register_type:newType,opening_balance:Number(newOpening||0)});setShowNew(false);setNewName('');setNewOpening(0);await changed('Az új pénztár létrejött.',String(r.data?.id||''))}catch(e:any){setError(e?.response?.data?.message||'A pénztár létrehozása nem sikerült.')}finally{setLoading(false)}}
 async function openRegister(){if(!register)return;setLoading(true);setError('');try{await api.post('/api/transactions/cashier/sessions/open',{business_date:today,location_id:locationId,register_id:register.id,opening_cash:isCash?(denominationTotal||Number(openingCash||0)):Number(openingCash||0),denominations:isCash?denoms:{},note:openNote||null});setOpenNote('');await changed('A pénztár megnyitva, a nyitó állás rögzítve.',String(register.id))}catch(e:any){setError(e?.response?.data?.message||'A pénztárnyitás nem sikerült.')}finally{setLoading(false)}}
 async function addMovement(){if(!session)return;setLoading(true);setError('');try{await api.post('/api/transactions/cashier/cash-movements',{session_id:session.id,location_id:locationId,direction,amount:Number(movementAmount||0),reason:movementReason,movement_type:movementType,reference_no:referenceNo||null});setMovementAmount(0);setMovementReason('');setReferenceNo('');await changed(direction==='in'?'A bevétel rögzítve.':'A kiadás rögzítve.',String(register?.id||''))}catch(e:any){setError(e?.response?.data?.message||'A pénztármozgás nem menthető.')}finally{setLoading(false)}}
 async function saveCheck(kind:'check'|'handover'){if(!session)return;if(kind==='handover'&&!handedTo.trim()){setError('Adja meg az átvevő pénztárost.');return}setLoading(true);setError('');try{await api.post(`/api/transactions/cashier/sessions/${session.id}/check`,{location_id:locationId,count_type:kind,denominations:isCash?denoms:{},counted_cash:countedValue,note:checkNote||null,handed_to:kind==='handover'?handedTo.trim():null});setCheckNote('');setHandedTo('');await changed(kind==='handover'?'A pénztár átadva; új műszak megnyitva az átvevőnek.':'A köztes pénztárellenőrzés elmentve.',String(register?.id||''))}catch(e:any){setError(e?.response?.data?.message||'A pénztárellenőrzés nem sikerült.')}finally{setLoading(false)}}
 async function transfer(){if(!register||!transferTo||transferAmount<=0)return;setLoading(true);setError('');try{await api.post('/api/transactions/cashier/transfers',{location_id:locationId,from_register_id:register.id,to_register_id:transferTo,amount:transferAmount,note:transferNote||'Pénztárközi átvezetés'});setTransferAmount(0);setTransferNote('');await changed('A pénztárközi átvezetés megtörtént.',String(register.id))}catch(e:any){setError(e?.response?.data?.message||'Az átvezetés nem sikerült.')}finally{setLoading(false)}}
 async function closeRegister(){if(!session||!register)return;if(!window.confirm(`A(z) ${register.name} napi zárása ${fmt(countedValue)} megszámolt állással. Folytatja?`))return;setLoading(true);setError('');try{await api.post('/api/transactions/cashier/register-daily-close',{business_date:today,location_id:locationId,register_id:register.id,counted_cash:countedValue,denominations:isCash?denoms:{},note:checkNote||null});await changed('A napi pénztárzárás elkészült.',String(register.id))}catch(e:any){setError(e?.response?.data?.message||'A napi pénztárzárás nem sikerült.')}finally{setLoading(false)}}

 return <section className="cash-register-panel cashier-card">
  <div className="cash-register-panel__head"><div><span className="eyebrow">ALTEGIO-SZINTŰ KASSZA</span><h2><Store/> Pénztárak és műszakok</h2><p>{locationName} · {today}</p></div><div className="cash-register-panel__head-actions"><select value={selectedRegister} onChange={e=>void chooseRegister(e.target.value)}>{(state?.registers||[]).map(r=><option key={String(r.id)} value={String(r.id)}>{r.name} · {r.register_type==='cashless'?'készpénz nélküli':'készpénz'} {r.open_session_id?'· NYITVA':''}</option>)}</select><button type="button" onClick={()=>setShowNew(x=>!x)}><Plus size={16}/> Új pénztár</button><button type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/> Frissítés</button></div></div>
  {error&&<div className="cash-register-panel__message is-error">{error}</div>}{notice&&<div className="cash-register-panel__message is-ok">{notice}</div>}
  {showNew&&<div className="cash-register-panel__new"><label>Név<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Pl. Recepció 2 / Bankkártya"/></label><label>Típus<select value={newType} onChange={e=>setNewType(e.target.value as any)}><option value="cash">Készpénzes kassza</option><option value="cashless">Készpénz nélküli számla</option></select></label><label>Kezdő egyenleg<input type="number" value={newOpening} onChange={e=>setNewOpening(Number(e.target.value||0))}/></label><button className="is-primary" onClick={()=>void createRegister()} disabled={!newName.trim()||loading}>Létrehozás</button></div>}
  {register&&<div className="cash-register-panel__register-strip"><div><b>{register.name}</b><span>{register.register_type==='cashless'?'Készpénz nélküli pénzügyi számla':'Fizikai készpénztár'}</span></div><span className={`cash-register-panel__status ${isOpen?'is-open':''}`}>{isOpen?`Nyitva · ${session?.shift_no||1}. műszak`:'Zárva'}</span>{history?.previous_closing_count&&<small>Előző záró: <b>{fmt(history.previous_closing_count.counted_cash)}</b> · eltérés {fmt(history.previous_closing_count.difference)}</small>}</div>}
  {register&&!isOpen&&<div className="cash-register-panel__open"><div><Banknote/><h3>Pénztárnyitás</h3><p>{isCash?'Adja meg a nyitó címleteket; a rendszer automatikusan összeadja.':'Adja meg a nyitó számlaegyenleget.'}</p></div>{!isCash&&<label>Nyitó egyenleg<input type="number" min="0" value={openingCash} onChange={e=>setOpeningCash(Number(e.target.value||0))}/></label>}<label>Megjegyzés<input value={openNote} onChange={e=>setOpenNote(e.target.value)} placeholder="Műszakkezdés"/></label><button className="is-primary" type="button" disabled={loading} onClick={()=>void openRegister()}>Pénztár megnyitása</button></div>}
  {isOpen&&<><div className="cash-register-panel__kpis"><article><span>Nyitó állás</span><b>{fmt(session?.opening_cash)}</b></article><article><span>Készpénzes forgalom</span><b>{fmt(state?.cash_sales)}</b></article><article><span>Bevét</span><b>{fmt(state?.cash_in)}</b></article><article><span>Kivét</span><b>-{fmt(state?.cash_out)}</b></article><article className="is-primary"><span>Várt állás</span><b>{fmt(state?.expected_cash)}</b></article></div>
   <div className="cash-register-panel__stage13-grid">
    <div className="cash-register-panel__count"><h3><Calculator/> Címletszámolás és ellenőrzés</h3>{isCash?<div className="cash-register-panel__denoms">{DENOMS.map(v=><label key={v}><span>{v.toLocaleString('hu-HU')} Ft</span><input type="number" min="0" step="1" value={denoms[String(v)]||0} onChange={e=>setDenoms(d=>({...d,[String(v)]:Math.max(0,Math.floor(Number(e.target.value||0)))}))}/><small>{fmt(v*Number(denoms[String(v)]||0))}</small></label>)}</div>:<label>Aktuális egyenleg<input type="number" min="0" value={manualCount} onChange={e=>setManualCount(e.target.value)}/></label>}<div className="cash-register-panel__count-total"><span>Megszámolt / megadott állás</span><b>{fmt(countedValue)}</b><span>Várt eltérés</span><b className={Math.abs(differencePreview)<1?'is-ok':'is-warning'}>{fmt(differencePreview)}</b></div><label>Ellenőrzési megjegyzés<input value={checkNote} onChange={e=>setCheckNote(e.target.value)} placeholder="Eltérés oka, átadás megjegyzése…"/></label><div className="cash-register-panel__count-actions"><button onClick={()=>void saveCheck('check')} disabled={loading}><CheckCircle2/> Köztes ellenőrzés</button><div><input value={handedTo} onChange={e=>setHandedTo(e.target.value)} placeholder="Átvevő pénztáros neve / e-mail"/><button onClick={()=>void saveCheck('handover')} disabled={loading||!handedTo.trim()}><UserRoundCheck/> Pénztár átadása</button></div><button className="is-primary" onClick={()=>void closeRegister()} disabled={loading}><LockKeyhole/> Napi zárás</button></div></div>
    <div className="cash-register-panel__side-stack"><div className="cash-register-panel__movement"><h3>Kiadás / bevétel</h3><div className="cash-register-panel__toggle"><button type="button" className={direction==='in'?'active':''} onClick={()=>setDirection('in')}><ArrowDownToLine/> Bevétel</button><button type="button" className={direction==='out'?'active':''} onClick={()=>setDirection('out')}><ArrowUpFromLine/> Kiadás</button></div><label>Összeg<input type="number" min="0" value={movementAmount} onChange={e=>setMovementAmount(Number(e.target.value||0))}/></label><label>Tranzakció típusa<select value={movementType} onChange={e=>setMovementType(e.target.value)}><option value="manual">Egyéb pénztármozgás</option><option value="change_money">Váltópénz</option><option value="bank_deposit">Banki befizetés</option><option value="bank_withdrawal">Banki felvét</option><option value="expense">Kiadás / költség</option><option value="income">Egyéb bevétel</option></select></label><label>Indok<input value={movementReason} onChange={e=>setMovementReason(e.target.value)} placeholder="Kötelező indok"/></label><label>Hivatkozási / bizonylatszám<input value={referenceNo} onChange={e=>setReferenceNo(e.target.value)}/></label><button type="button" disabled={loading||movementAmount<=0||movementReason.trim().length<3} onClick={()=>void addMovement()}>Tranzakció rögzítése</button></div>
     <div className="cash-register-panel__movement"><h3><ArrowLeftRight/> Pénztárközi átvezetés</h3><label>Célpénztár<select value={transferTo} onChange={e=>setTransferTo(e.target.value)}><option value="">Válasszon…</option>{otherOpenRegisters.map(r=><option key={String(r.id)} value={String(r.id)}>{r.name}</option>)}</select></label><label>Összeg<input type="number" min="0" value={transferAmount} onChange={e=>setTransferAmount(Number(e.target.value||0))}/></label><label>Megjegyzés<input value={transferNote} onChange={e=>setTransferNote(e.target.value)}/></label><button onClick={()=>void transfer()} disabled={loading||!transferTo||transferAmount<=0}>Átvezetés</button>{!otherOpenRegisters.length&&<small>Átvezetéshez egy másik pénztárnak is nyitva kell lennie.</small>}</div></div>
   </div>
   <div className="cash-register-panel__audit"><div><h3>Mai ellenőrzések / átadások</h3>{(state?.counts||[]).length?(state?.counts||[]).map(c=><p key={String(c.id)}><b>{c.count_type==='opening'?'Nyitás':c.count_type==='check'?'Köztes ellenőrzés':c.count_type==='handover'?'Átadás':'Zárás'}</b><span>{fmt(c.counted_cash)} · eltérés {fmt(c.difference)}</span><small>{dt(c.created_at)} {c.handed_to?`→ ${c.handed_to}`:''}</small></p>):<span>Még nincs köztes ellenőrzés.</span>}</div><div><h3>Mai pénztármozgások</h3>{(state?.movements||[]).length?(state?.movements||[]).map(m=><p key={String(m.id)}><b className={m.direction==='in'?'is-in':'is-out'}>{m.direction==='in'?'Bevét':'Kivét'} {m.direction==='out'?'-':''}{fmt(m.amount)}</b><span>{m.reason}</span><small>{m.reference_no?`${m.reference_no} · `:''}{dt(m.created_at)}</small></p>):<span>Nincs külön pénztármozgás.</span>}</div></div>
  </>}
 </section>
}
