import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ArrowDownToLine,ArrowUpFromLine,Banknote,CheckCircle2,LockKeyhole,RefreshCw,Store}from'lucide-react';
import api from'../../api';
import'./CashRegisterSessionPanel.css';

type Movement={id:string|number;direction:'in'|'out';amount:number|string;reason:string;created_by?:string;created_at?:string};
type Session={id:string|number;status:'open'|'closed';opening_cash:number|string;opened_at?:string;opened_by?:string;closed_at?:string;closed_by?:string;counted_cash?:number|string;expected_cash?:number|string;difference?:number|string};
type RegisterState={business_date:string;location_id:string;register?:{id:string|number;name?:string}|null;session?:Session|null;movements?:Movement[];cash_in?:number;cash_out?:number;expected_cash?:number;sales?:{cash_sales?:number};closing?:{difference?:number|string;counted_cash?:number|string;expected_cash?:number|string;closed_at?:string}|null};
type Props={onChanged?:()=>void};

const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString('hu-HU')} Ft`;
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dt=(v?:string)=>v?new Date(v).toLocaleString('hu-HU'):'—';

export default function CashRegisterSessionPanel({onChanged}:Props){
 const[state,setState]=useState<RegisterState|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[openingCash,setOpeningCash]=useState(0),[openNote,setOpenNote]=useState('');
 const[direction,setDirection]=useState<'in'|'out'>('in'),[movementAmount,setMovementAmount]=useState(0),[movementReason,setMovementReason]=useState('');
 const[countedCash,setCountedCash]=useState(''),[closeNote,setCloseNote]=useState('');
 const locationId=localStorage.getItem('kleo_location_id')||'',locationName=localStorage.getItem('kleo_location_name')||'Kiválasztott szalon',today=localDate();
 const session=state?.session||null,isOpen=session?.status==='open',isClosed=session?.status==='closed',hasCountedCash=countedCash.trim()!=='';
 const differencePreview=useMemo(()=>hasCountedCash?Number(countedCash)-Number(state?.expected_cash||0):0,[countedCash,hasCountedCash,state?.expected_cash]);
 const load=useCallback(async()=>{if(!locationId){setState(null);setError('A pénztár használatához előbb válasszon telephelyet.');return}setLoading(true);setError('');try{const r=await api.get(`/api/transactions/cashier/register-state?date=${today}&location_id=${encodeURIComponent(locationId)}`);setState(r.data||null)}catch(e:any){setError(e?.response?.data?.message||'A pénztár állapota nem tölthető be.')}finally{setLoading(false)}},[locationId,today]);
 useEffect(()=>{void load()},[load]);
 const changed=async(message:string)=>{setNotice(message);await load();onChanged?.()};
 async function openRegister(){if(!locationId)return;setLoading(true);setError('');setNotice('');try{await api.post('/api/transactions/cashier/sessions/open',{business_date:today,location_id:locationId,opening_cash:Number(openingCash||0),note:openNote||null});await changed('A pénztár megnyitva, a nyitó készpénz rögzítve.')}catch(e:any){setError(e?.response?.data?.message||'A pénztárnyitás nem sikerült.')}finally{setLoading(false)}}
 async function addMovement(){if(!session)return;setLoading(true);setError('');setNotice('');try{await api.post('/api/transactions/cashier/cash-movements',{session_id:session.id,location_id:locationId,direction,amount:Number(movementAmount||0),reason:movementReason});setMovementAmount(0);setMovementReason('');await changed(direction==='in'?'A készpénzbevét rögzítve.':'A készpénzkivét rögzítve.')}catch(e:any){setError(e?.response?.data?.message||'A készpénzmozgás nem menthető.')}finally{setLoading(false)}}
 async function closeRegister(){if(!session||!hasCountedCash)return;if(!window.confirm(`Napi pénztárzárás ${fmt(Number(countedCash))} ténylegesen megszámolt készpénzzel. Folytatja?`))return;setLoading(true);setError('');setNotice('');try{await api.post('/api/transactions/cashier/register-daily-close',{business_date:today,location_id:locationId,counted_cash:Number(countedCash),note:closeNote||null});await changed('A napi pénztárzárás elkészült, a kasszaműszak lezárva.')}catch(e:any){setError(e?.response?.data?.message||'A napi pénztárzárás nem sikerült.')}finally{setLoading(false)}}
 return <section className="cash-register-panel cashier-card">
  <div className="cash-register-panel__head"><div><span className="eyebrow">FIZIKAI KASSZA</span><h2><Store/> Pénztárműszak</h2><p>{locationName} · {today}</p></div><div className="cash-register-panel__head-actions"><span className={`cash-register-panel__status ${isOpen?'is-open':isClosed?'is-closed':''}`}>{isOpen?'Nyitva':isClosed?'Lezárva':'Nincs megnyitva'}</span><button type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/> Frissítés</button></div></div>
  {error&&<div className="cash-register-panel__message is-error">{error}</div>}{notice&&<div className="cash-register-panel__message is-ok">{notice}</div>}
  {!session&&<div className="cash-register-panel__open"><div><Banknote/><h3>Pénztárnyitás</h3><p>Rögzítse a kasszában lévő nyitó készpénzt. Ez lesz a napi készpénzegyeztetés alapja.</p></div><label>Nyitó készpénz<input type="number" min="0" value={openingCash} onChange={e=>setOpeningCash(Number(e.target.value||0))}/></label><label>Megjegyzés<input value={openNote} onChange={e=>setOpenNote(e.target.value)} placeholder="Pl. műszakkezdés"/></label><button className="is-primary" type="button" disabled={loading||!locationId} onClick={()=>void openRegister()}>Pénztár megnyitása</button></div>}
  {session&&<><div className="cash-register-panel__kpis"><article><span>Nyitó készpénz</span><b>{fmt(session.opening_cash)}</b></article><article><span>Készpénzes forgalom</span><b>{fmt(state?.sales?.cash_sales)}</b></article><article><span>Készpénz bevét</span><b>{fmt(state?.cash_in)}</b></article><article><span>Készpénz kivét</span><b>-{fmt(state?.cash_out)}</b></article><article className="is-primary"><span>Várt kassza</span><b>{fmt(state?.expected_cash)}</b></article></div>
  {isOpen&&<div className="cash-register-panel__workspace"><div className="cash-register-panel__movement"><h3>Készpénz be / ki</h3><div className="cash-register-panel__toggle"><button type="button" className={direction==='in'?'active':''} onClick={()=>setDirection('in')}><ArrowDownToLine/> Bevét</button><button type="button" className={direction==='out'?'active':''} onClick={()=>setDirection('out')}><ArrowUpFromLine/> Kivét</button></div><label>Összeg<input type="number" min="0" value={movementAmount} onChange={e=>setMovementAmount(Number(e.target.value||0))}/></label><label>Ok / bizonylat<input value={movementReason} onChange={e=>setMovementReason(e.target.value)} placeholder="Pl. váltópénz, banki befizetés"/></label><button type="button" disabled={loading||movementAmount<=0||movementReason.trim().length<3} onClick={()=>void addMovement()}>Mozgás rögzítése</button></div>
  <div className="cash-register-panel__close"><h3><LockKeyhole/> Napi zárás</h3><label>Megszámolt készpénz<input type="number" min="0" value={countedCash} onChange={e=>setCountedCash(e.target.value)} placeholder="A ténylegesen megszámolt összeg"/></label>{hasCountedCash?<div className={`cash-register-panel__difference ${Math.abs(differencePreview)<1?'is-ok':'is-warning'}`}><span>Várható eltérés</span><b>{fmt(differencePreview)}</b></div>:<div className="cash-register-panel__difference"><span>Eltérés</span><b>Adja meg a megszámolt összeget</b></div>}<label>Zárási megjegyzés<input value={closeNote} onChange={e=>setCloseNote(e.target.value)} placeholder="Eltérés oka, átadás…"/></label><button className="is-primary" type="button" disabled={loading||!hasCountedCash} onClick={()=>void closeRegister()}><CheckCircle2/> Napi pénztárzárás</button></div></div>}
  {isClosed&&<div className="cash-register-panel__closed"><CheckCircle2/><div><b>A pénztár erre a napra lezárva.</b><span>Megszámolt: {fmt(session.counted_cash||state?.closing?.counted_cash)} · Várt: {fmt(session.expected_cash||state?.closing?.expected_cash)} · Eltérés: {fmt(session.difference||state?.closing?.difference)}</span><small>{dt(session.closed_at||state?.closing?.closed_at)} · {session.closed_by||'—'}</small></div></div>}
  <div className="cash-register-panel__history"><h3>Mai kasszamozgások</h3>{(state?.movements||[]).length?(state?.movements||[]).map(m=><div key={String(m.id)}><span className={m.direction==='in'?'is-in':'is-out'}>{m.direction==='in'?<ArrowDownToLine/>:<ArrowUpFromLine/>}{m.direction==='in'?'Bevét':'Kivét'}</span><b>{m.direction==='out'?'-':''}{fmt(m.amount)}</b><span>{m.reason}</span><small>{dt(m.created_at)}</small></div>):<p>Nincs külön készpénzbevét vagy -kivét rögzítve.</p>}</div></>}
 </section>
}
