import React,{useEffect,useState}from"react";
import{AlertTriangle,CheckCircle2,FileWarning,Landmark,RefreshCw,Scale,WalletCards}from"lucide-react";
import api from"../../api";
import"./FinanceControlCenter.css";

type Summary={month:string;issue_count:number;invoices:any;journals:any;cash:any;payroll:any;period_close:any};
type Issue={id:string;entity_type:string;reference:string;partner_name?:string;issue_type:string;amount:number;due_date?:string;issue_date?:string;status:string};
const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const labels:Record<string,string>={overdue:"Lejárt számla",unpaid:"Kiegyenlítetlen",unposted:"Nincs főkönyvben",missing_invoice_no:"Hiányzó számlaszám",amount_mismatch:"Összegeltérés",vat_review:"ÁFA ellenőrzendő"};
export default function FinanceControlCenter(){const[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[summary,setSummary]=useState<Summary|null>(null),[issues,setIssues]=useState<Issue[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const locationId=localStorage.getItem("kleo_location_id")||"";
async function load(){setLoading(true);setError("");try{const q=`?month=${encodeURIComponent(month)}${locationId?`&location_id=${encodeURIComponent(locationId)}`:""}`;const[s,i]=await Promise.all([api.get(`/api/transactions/finance-control/summary${q}`),api.get(`/api/transactions/finance-control/issues${q}`)]);setSummary(s.data);setIssues(i.data||[])}catch(e:any){setError(e?.response?.data?.message||"A pénzügyi ellenőrzések nem tölthetők be.")}finally{setLoading(false)}}
useEffect(()=>{void load()},[month]);
async function closeMonth(){if(!summary)return;const forced=summary.issue_count>0;if(forced&&!window.confirm(`Még ${summary.issue_count} ellenőrzési tétel van. Biztosan kényszerítve zárod a hónapot?`))return;try{await api.post("/api/transactions/finance-control/period-close",{month,location_id:locationId||null,force:forced,note:forced?"Kényszerített havi zárás ellenőrzési tételekkel":"Havi pénzügyi zárás"});await load()}catch(e:any){setError(e?.response?.data?.message||"A havi zárás sikertelen.")}}
return <section className="finance-control"><header><div><span>PÉNZÜGYI KONTROLL</span><h2>Adó- és könyvelési ellenőrző központ</h2><p>Lejárt és kiegyenlítetlen számlák, ÁFA-ellenőrzés, főkönyvi hiányok, kasszaeltérések és havi zárás.</p></div><div className="finance-control-head-actions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={load} disabled={loading}><RefreshCw size={16}/>Frissítés</button></div></header>{error&&<div className="finance-control-error">{error}</div>}{summary&&<><div className="finance-control-kpis"><article className={summary.issue_count?"warn":"ok"}><AlertTriangle/><div><small>Összes ellenőrzési tétel</small><b>{summary.issue_count}</b></div></article><article><FileWarning/><div><small>Lejárt számlák</small><b>{summary.invoices?.overdue_count||0}</b><em>{fmt(summary.invoices?.overdue_total)}</em></div></article><article><WalletCards/><div><small>Kiegyenlítetlen</small><b>{summary.invoices?.unpaid_count||0}</b><em>{fmt(summary.invoices?.unpaid_total)}</em></div></article><article><Landmark/><div><small>Nem könyvelt</small><b>{Number(summary.invoices?.unposted_count||0)+Number(summary.payroll?.unposted_payroll_count||0)}</b></div></article><article><Scale/><div><small>Kasszaeltérés</small><b>{summary.cash?.difference_count||0}</b><em>{fmt(summary.cash?.difference_total)}</em></div></article></div><div className="finance-control-status"><div><b>Számlaszám hiány:</b> {summary.invoices?.missing_invoice_no_count||0}</div><div><b>Összegeltérés:</b> {summary.invoices?.amount_mismatch_count||0}</div><div><b>ÁFA ellenőrzés:</b> {summary.invoices?.vat_review_count||0}</div><div><b>Kiegyensúlyozatlan főkönyvi tétel:</b> {summary.journals?.unbalanced_count||0}</div><div><b>Nem könyvelt bérszámfejtés:</b> {summary.payroll?.unposted_payroll_count||0}</div><div className="month-close"><span>{summary.period_close?.status==="closed"?<><CheckCircle2 size={16}/> Hónap lezárva</>:"Hónap nyitva"}</span>{summary.period_close?.closed_at&&<small>{new Date(summary.period_close.closed_at).toLocaleString("hu-HU")}</small>}<button onClick={closeMonth} disabled={summary.period_close?.status==="closed"}>Havi zárás</button></div></div></>}<div className="finance-control-table"><table><thead><tr><th>Probléma</th><th>Hivatkozás</th><th>Partner</th><th>Határidő</th><th>Összeg</th><th>Állapot</th></tr></thead><tbody>{issues.map(x=><tr key={`${x.id}-${x.issue_type}`}><td><span className="issue-pill">{labels[x.issue_type]||x.issue_type}</span></td><td>{x.reference}</td><td>{x.partner_name||"—"}</td><td>{x.due_date||"—"}</td><td><b>{fmt(x.amount)}</b></td><td>{x.status}</td></tr>)}</tbody></table>{!issues.length&&!loading&&<div className="finance-control-empty"><CheckCircle2/> Nincs ellenőrzést igénylő számlatétel ebben a hónapban.</div>}</div></section>}
