import React,{useEffect,useMemo,useState}from"react";
import{CheckCircle2,FilePlus2,Landmark,RefreshCw,WalletCards,XCircle}from"lucide-react";
import api from"../../api";
import"./FinanceInvoicesPanel.css";

type Invoice={id:string;direction:"incoming"|"outgoing";invoice_no?:string;partner_name?:string;issue_date:string;due_date:string;net_total:number;vat_total:number;gross_total:number;status:string;journal_entry_id?:string;payment_account_name?:string};
type Account={id:string;name:string;current_balance:number};
const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const today=()=>new Date().toISOString().slice(0,10);
export default function FinanceInvoicesPanel(){
 const[items,setItems]=useState<Invoice[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const[form,setForm]=useState<any>({direction:"incoming",invoice_no:"",partner_name:"",partner_tax_no:"",issue_date:today(),performance_date:today(),due_date:today(),net_total:0,vat_total:0,gross_total:0});
 const locationId=localStorage.getItem("kleo_location_id")||"";
 const openTotal=useMemo(()=>items.filter(x=>["approved","overdue"].includes(x.status)).reduce((s,x)=>s+Number(x.gross_total||0),0),[items]);
 async function load(){setLoading(true);setError("");try{const q=locationId?`?location_id=${encodeURIComponent(locationId)}`:"";const[i,a]=await Promise.all([api.get(`/api/transactions/finance-operations/invoices${q}`),api.get(`/api/transactions/finance-operations/accounts${q}`)]);setItems(i.data||[]);setAccounts(a.data||[]);}catch(e:any){setError(e?.response?.data?.message||"A számlák nem tölthetők be.");}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(){setLoading(true);setError("");try{await api.post("/api/transactions/finance-operations/invoices",{...form,location_id:locationId||null});setForm((x:any)=>({...x,invoice_no:"",partner_name:"",partner_tax_no:"",net_total:0,vat_total:0,gross_total:0}));await load();}catch(e:any){setError(e?.response?.data?.message||"A számla nem menthető.");}finally{setLoading(false)}}
 async function action(id:string,type:"approve"|"ledger"|"cancel"|"pay"){setLoading(true);setError("");try{if(type==="approve")await api.post(`/api/transactions/finance-operations/invoices/${id}/approve`);if(type==="ledger")await api.post(`/api/transactions/finance-operations/invoices/${id}/post-to-ledger`);if(type==="cancel"){const reason=window.prompt("Sztornó indoka:");if(!reason)return;await api.post(`/api/transactions/finance-operations/invoices/${id}/cancel`,{reason});}if(type==="pay"){const account=accounts[0]?.id;if(!account)throw new Error("Nincs pénzügyi számla/pénztár.");await api.post(`/api/transactions/finance-operations/invoices/${id}/pay`,{account_id:account});}await load();}catch(e:any){setError(e?.response?.data?.message||e?.message||"A művelet sikertelen.");}finally{setLoading(false)}}
 return <section className="fin-invoices"><header><div><span>PÉNZÜGY 2.0</span><h2>Bejövő és kimenő számlák</h2><p>Jóváhagyás, fizetés, sztornó és főkönyvi feladás egy folyamatban.</p></div><button onClick={load}><RefreshCw size={16}/>Frissítés</button></header>
 <div className="fin-invoice-kpis"><article><FilePlus2/><div><small>Számlák</small><b>{items.length}</b></div></article><article><WalletCards/><div><small>Nyitott összeg</small><b>{fmt(openTotal)}</b></div></article><article><Landmark/><div><small>Könyvelt</small><b>{items.filter(x=>x.journal_entry_id).length}</b></div></article></div>
 {error&&<div className="fin-invoice-error">{error}</div>}
 <div className="fin-invoice-create"><select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="incoming">Bejövő</option><option value="outgoing">Kimenő</option></select><input placeholder="Számlaszám" value={form.invoice_no} onChange={e=>setForm({...form,invoice_no:e.target.value})}/><input placeholder="Partner" value={form.partner_name} onChange={e=>setForm({...form,partner_name:e.target.value})}/><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/><input type="number" placeholder="Nettó" value={form.net_total} onChange={e=>setForm({...form,net_total:Number(e.target.value)})}/><input type="number" placeholder="ÁFA" value={form.vat_total} onChange={e=>setForm({...form,vat_total:Number(e.target.value)})}/><input type="number" placeholder="Bruttó" value={form.gross_total} onChange={e=>setForm({...form,gross_total:Number(e.target.value)})}/><button className="primary" onClick={create} disabled={loading}><FilePlus2 size={15}/>Új számla</button></div>
 <div className="fin-invoice-table"><table><thead><tr><th>Irány</th><th>Számla</th><th>Partner</th><th>Határidő</th><th>Összeg</th><th>Állapot</th><th>Műveletek</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.direction==="incoming"?"Bejövő":"Kimenő"}</td><td>{x.invoice_no||"—"}</td><td>{x.partner_name||"—"}</td><td>{x.due_date}</td><td><b>{fmt(x.gross_total)}</b></td><td><span className={`fin-status ${x.status}`}>{x.status}</span></td><td><div className="fin-actions">{x.status==="draft"&&<button onClick={()=>action(x.id,"approve")}><CheckCircle2 size={14}/>Jóváhagyás</button>}{["approved","overdue"].includes(x.status)&&<button onClick={()=>action(x.id,"pay")}>Fizetés</button>}{["approved","overdue","paid"].includes(x.status)&&!x.journal_entry_id&&<button onClick={()=>action(x.id,"ledger")}>Főkönyv</button>}{x.status!=="paid"&&x.status!=="cancelled"&&<button onClick={()=>action(x.id,"cancel")}><XCircle size={14}/>Sztornó</button>}</div></td></tr>)}</tbody></table>{!items.length&&<div className="fin-empty">Még nincs rögzített számla.</div>}</div>
 </section>;
}