import React,{useCallback,useEffect,useMemo,useState}from"react";
import{AlertTriangle,Banknote,Building2,CalendarDays,ChartNoAxesColumnIncreasing,CircleDollarSign,CreditCard,RefreshCw,ReceiptText,UsersRound,WalletCards}from"lucide-react";
import api from"../../api";
import"./FinanceDailyDashboard.css";

type Dashboard={business_date:string;scope:{is_admin:boolean;location_id:string|null};kpis:any;payments:Array<{method:string;label:string;amount:number}>;locations:any[];staff:any[];commissions:any[];closings:any[];trend:any[]};
type Props={refreshKey?:number};
const fmt=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const today=()=>new Date().toISOString().slice(0,10);

export default function FinanceDailyDashboard({refreshKey=0}:Props){
 const[date,setDate]=useState(today()),[data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const locationId=localStorage.getItem("kleo_location_id")||"";
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({date});if(locationId)q.set("location_id",locationId);const r=await api.get(`/api/transactions/finance-dashboard?${q.toString()}`);setData(r.data)}catch(e:any){setError(e?.response?.data?.message||"A napi pénzügyi dashboard nem tölthető be.")}finally{setLoading(false)}},[date,locationId]);
 useEffect(()=>{void load()},[load,refreshKey]);
 const paymentMax=useMemo(()=>Math.max(1,...(data?.payments||[]).map(x=>Number(x.amount||0))),[data]);
 const trendMax=useMemo(()=>Math.max(1,...(data?.trend||[]).map(x=>Number(x.revenue||0))),[data]);
 const openCommission=useMemo(()=>data?.commissions?.reduce((sum,x)=>sum+Number(x.base_amount||0)+Number(x.tip_amount||0),0)||0,[data]);
 const alerts=useMemo(()=>{if(!data)return[];const a:string[]=[];if(Number(data.kpis.unpaid_workorders)>0)a.push(`${data.kpis.unpaid_workorders} munkalapon összesen ${fmt(data.kpis.unpaid_total)} kintlévőség van.`);if(Number(data.kpis.open_workorders)>0)a.push(`${data.kpis.open_workorders} munkalap még nincs lezárva.`);if(Number(data.kpis.refund_total)>0)a.push(`A napi visszatérítés összege ${fmt(data.kpis.refund_total)}.`);if(data.locations.length>0&&data.closings.length<data.locations.length)a.push(`A napi kasszazárás még nem készült el minden érintett szalonban.`);return a},[data]);
 return <section className="finance-daily-dashboard">
  <header className="fdd-head"><div><span>NAPI PÉNZÜGYI IRÁNYÍTÓPULT</span><h2>Bevétel, kassza és teljesítmény</h2><p>A pénztár, munkalapok, jutalékok és napi zárások közös operatív nézete.</p></div><div className="fdd-head-actions"><label><CalendarDays size={16}/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={load} disabled={loading}><RefreshCw size={16}/>{loading?"Frissítés…":"Frissítés"}</button></div></header>
  {error&&<div className="fdd-error">{error}</div>}
  {data&&<>
   <div className="fdd-kpis"><article><CircleDollarSign/><small>Napi bevétel</small><b>{fmt(data.kpis.collected_total)}</b><em>Nettó: {fmt(data.kpis.net_collected)}</em></article><article><ReceiptText/><small>Fizetett munkalap</small><b>{data.kpis.paid_workorders||0}</b><em>Átlag: {fmt(data.kpis.avg_ticket)}</em></article><article><Banknote/><small>Kintlévőség</small><b>{fmt(data.kpis.unpaid_total)}</b><em>{data.kpis.unpaid_workorders||0} munkalap</em></article><article><UsersRound/><small>Nyitott jutalékalap</small><b>{fmt(openCommission)}</b><em>{data.commissions.reduce((s,x)=>s+Number(x.event_count||0),0)} esemény</em></article><article><WalletCards/><small>Borravaló / kedvezmény</small><b>{fmt(data.kpis.tips)}</b><em>Kedvezmény: {fmt(data.kpis.discounts)}</em></article></div>
   {alerts.length>0&&<div className="fdd-alerts"><AlertTriangle size={18}/><div>{alerts.map(x=><p key={x}>{x}</p>)}</div></div>}
   <div className="fdd-grid">
    <article className="fdd-card"><header><div><span>FIZETÉSI MÓDOK</span><h3>Napi megoszlás</h3></div><CreditCard size={20}/></header><div className="fdd-bars">{data.payments.map(p=><div key={p.method}><div className="fdd-bar-label"><span>{p.label}</span><b>{fmt(p.amount)}</b></div><div className="fdd-bar-track"><i style={{width:`${Math.max(2,Number(p.amount||0)/paymentMax*100)}%`}}/></div></div>)}</div></article>
    <article className="fdd-card"><header><div><span>7 NAPOS TREND</span><h3>Bevételi lefutás</h3></div><ChartNoAxesColumnIncreasing size={20}/></header><div className="fdd-trend">{data.trend.map(t=><div key={t.business_date} title={`${t.business_date}: ${fmt(t.revenue)}`}><div className="fdd-trend-bar"><i style={{height:`${Math.max(5,Number(t.revenue||0)/trendMax*100)}%`}}/></div><small>{new Date(`${t.business_date}T12:00:00`).toLocaleDateString("hu-HU",{month:"2-digit",day:"2-digit"})}</small><b>{Math.round(Number(t.revenue||0)/1000)}e</b></div>)}</div></article>
   </div>
   {data.scope.is_admin&&<article className="fdd-card fdd-table-card"><header><div><span>SZALONOK</span><h3>Telephelyi bevétel</h3></div><Building2 size={20}/></header><div className="fdd-table-wrap"><table><thead><tr><th>Szalon</th><th>Munkalap</th><th>Bevétel</th><th>Készpénz</th><th>Kártya</th><th>Átutalás</th><th>Utalvány / egyéb</th></tr></thead><tbody>{data.locations.map(x=><tr key={x.location_id||x.location_name}><td><b>{x.location_name}</b></td><td>{x.workorders}</td><td><b>{fmt(x.revenue)}</b></td><td>{fmt(x.cash)}</td><td>{fmt(x.card)}</td><td>{fmt(x.transfer)}</td><td>{fmt(Number(x.voucher||0)+Number(x.other||0))}</td></tr>)}</tbody></table>{!data.locations.length&&<div className="fdd-empty">Erre a napra nincs szalonbevétel.</div>}</div></article>}
   <div className="fdd-grid fdd-grid-bottom">
    <article className="fdd-card fdd-table-card"><header><div><span>MUNKATÁRSAK</span><h3>Napi teljesítmény</h3></div><UsersRound size={20}/></header><div className="fdd-table-wrap"><table><thead><tr><th>Munkatárs</th><th>Munkalap</th><th>Bevétel</th><th>Átlag</th><th>Borravaló</th></tr></thead><tbody>{data.staff.map(x=><tr key={x.employee_id||x.employee_name}><td><b>{x.employee_name}</b></td><td>{x.workorders}</td><td><b>{fmt(x.revenue)}</b></td><td>{fmt(x.avg_ticket)}</td><td>{fmt(x.tips)}</td></tr>)}</tbody></table>{!data.staff.length&&<div className="fdd-empty">Nincs napi munkatársi pénzügyi adat.</div>}</div></article>
    <article className="fdd-card fdd-table-card"><header><div><span>JUTALÉK</span><h3>Nyitott jutalékelőkészítés</h3></div><CircleDollarSign size={20}/></header><div className="fdd-table-wrap"><table><thead><tr><th>Munkatárs</th><th>Esemény</th><th>Alap</th><th>Borravaló</th></tr></thead><tbody>{data.commissions.map(x=><tr key={x.employee_id||x.employee_name}><td><b>{x.employee_name}</b></td><td>{x.event_count}</td><td>{fmt(x.base_amount)}</td><td>{fmt(x.tip_amount)}</td></tr>)}</tbody></table>{!data.commissions.length&&<div className="fdd-empty">Nincs nyitott jutalékesemény.</div>}</div></article>
   </div>
   <article className="fdd-card fdd-closing-card"><header><div><span>KASSZAZÁRÁS</span><h3>Napi zárási állapot</h3></div><Banknote size={20}/></header><div className="fdd-closing-list">{data.closings.map(c=><div key={String(c.id)}><span><b>{c.location_name}</b><small>{c.closed_at?new Date(c.closed_at).toLocaleString("hu-HU"):data.business_date}</small></span><span>Várt: <b>{fmt(c.expected_cash)}</b></span><span>Számolt: <b>{fmt(c.counted_cash)}</b></span><span className={Math.abs(Number(c.difference||0))>.01?"bad":"good"}>Eltérés: <b>{fmt(c.difference)}</b></span></div>)}{!data.closings.length&&<div className="fdd-empty">Ehhez a naphoz még nincs rögzített kasszazárás.</div>}</div></article>
  </>}
 </section>
}
