import React,{useEffect,useMemo,useState}from"react";
import{useLocation,useNavigate}from"react-router-dom";
import{Area,AreaChart,Bar,BarChart,CartesianGrid,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from"recharts";
import{ArrowLeftRight,Banknote,BarChart3,Building2,CircleDollarSign,CreditCard,FileText,Landmark,Link2,Plus,Receipt,RefreshCw,Search,Settings2,Users,WalletCards,XCircle}from"lucide-react";
import api from"../../api";
import{hasStoredRole}from"../../utils/roles";
import"./FinanceWorkspacePage.css";

type Row=Record<string,any>;
type Tab="overview"|"accounts"|"partners"|"categories"|"transactions"|"documents"|"online"|"reports"|"payments"|"settings";
const BASE="/api/transactions/finance-v5";
const money=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("hu-HU")} Ft`;
const num=(v:any)=>Number(v||0);
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)};
const tabFromPath=(path:string):Tab=>path.includes("/accounts")?"accounts":path.includes("/partners")?"partners":path.includes("/categories")?"categories":path.includes("/transactions")?"transactions":path.includes("/documents")?"documents":path.includes("/online-payments")?"online":path.includes("/reports")?"reports":path.includes("/payment-methods")?"payments":path.includes("/settings")?"settings":"overview";
const tabPath:Record<Tab,string>={overview:"/finance",accounts:"/finance/accounts",partners:"/finance/partners",categories:"/finance/categories",transactions:"/finance/transactions",documents:"/finance/documents",online:"/finance/online-payments",reports:"/finance/reports",payments:"/finance/payment-methods",settings:"/finance/settings"};
const tabs:{key:Tab;label:string;icon:any}[]=[
 {key:"overview",label:"Áttekintés",icon:BarChart3},{key:"accounts",label:"Számlák és pénztárak",icon:Landmark},{key:"partners",label:"Partnerek",icon:Users},{key:"categories",label:"Bizonylat típusok",icon:Receipt},{key:"transactions",label:"Pénzügyi műveletek",icon:ArrowLeftRight},{key:"documents",label:"Dokumentumok",icon:FileText},{key:"online",label:"Online fizetés",icon:Link2},{key:"reports",label:"Jelentések",icon:BarChart3},{key:"payments",label:"Fizetési módok és díjak",icon:CreditCard},{key:"settings",label:"Beállítások",icon:Settings2}
];
function q(params:Record<string,any>){const s=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&String(v)!=="")s.set(k,String(v))});return s.toString()?`?${s}`:""}
function csv(name:string,rows:Row[]){if(!rows.length)return;const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));const esc=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`;const data="\ufeff"+[keys.map(esc).join(";"),...rows.map(r=>keys.map(k=>esc(r[k])).join(";"))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

export default function FinanceWorkspacePage(){
 const location=useLocation(),navigate=useNavigate(),tab=tabFromPath(location.pathname),canConfig=hasStoredRole(["admin","manager","location_manager"]);
 const locationId=localStorage.getItem("kleo_location_id")||"",locationName=localStorage.getItem("kleo_location_name")||"Összes engedélyezett telephely";
 const[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[dashboard,setDashboard]=useState<Row>({}),[accounts,setAccounts]=useState<Row[]>([]),[partners,setPartners]=useState<Row[]>([]),[categories,setCategories]=useState<Row[]>([]),[methods,setMethods]=useState<Row[]>([]),[movements,setMovements]=useState<Row[]>([]),[documents,setDocuments]=useState<Row[]>([]),[pl,setPl]=useState<Row>({months:[],categories:[]}),[dailyCash,setDailyCash]=useState<Row[]>([]),[settings,setSettings]=useState<Row>({});
 const[search,setSearch]=useState(""),[direction,setDirection]=useState(""),[accountFilter,setAccountFilter]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[partnerFilter,setPartnerFilter]=useState(""),[methodFilter,setMethodFilter]=useState("");
 const[modal,setModal]=useState<string|null>(null),[form,setForm]=useState<Row>({}),[tick,setTick]=useState(0);
 const scoped={location_id:locationId||undefined};
 const refresh=()=>setTick(x=>x+1);

 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError("");try{
   const common=await Promise.all([api.get(`${BASE}/accounts${q(scoped)}`),api.get(`${BASE}/partners${q(scoped)}`),api.get(`${BASE}/categories${q(scoped)}`),api.get(`${BASE}/payment-methods${q(scoped)}`)]);
   if(!active)return;setAccounts(common[0].data||[]);setPartners(common[1].data||[]);setCategories(common[2].data||[]);setMethods(common[3].data||[]);
   if(tab==="overview"){const r=await api.get(`${BASE}/dashboard${q({...scoped,from,to})}`);if(active)setDashboard(r.data||{})}
   if(tab==="transactions"){const r=await api.get(`${BASE}/movements${q({...scoped,from,to,account_id:accountFilter,category_id:categoryFilter,partner_id:partnerFilter,payment_method_id:methodFilter,direction,q:search})}`);if(active)setMovements(r.data||[])}
   if(tab==="documents"){const r=await api.get(`${BASE}/documents${q(scoped)}`);if(active)setDocuments(r.data||[])}
   if(tab==="reports"){const[r,d]=await Promise.all([api.get(`${BASE}/reports/pl${q({...scoped,from,to})}`),api.get(`${BASE}/reports/daily-cash${q({...scoped,date:to})}`)]);if(active){setPl(r.data||{});setDailyCash(d.data||[])}}
   if(tab==="settings"||tab==="online"){const r=await api.get(`${BASE}/settings${q(scoped)}`);if(active)setSettings(r.data||{})}
  }catch(e:any){if(active)setError(e?.response?.data?.message||"A pénzügyi adatok betöltése nem sikerült.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[tab,tick,from,to,accountFilter,categoryFilter,partnerFilter,methodFilter,direction,search]);

 const filteredPartners=useMemo(()=>partners.filter(p=>`${p.name||""} ${p.company_name||""} ${p.tax_number||""} ${p.email||""}`.toLowerCase().includes(search.toLowerCase())),[partners,search]);
 const filteredDocs=useMemo(()=>documents.filter(d=>`${d.document_number||""} ${d.partner_display_name||d.partner_name||""} ${d.document_type||""}`.toLowerCase().includes(search.toLowerCase())),[documents,search]);
 const closeModal=()=>{setModal(null);setForm({})};
 async function submit(kind:string){setLoading(true);setError("");setNotice("");try{
   if(kind==="account")await api.post(`${BASE}/accounts`,{...form,location_id:locationId||null});
   if(kind==="transfer")await api.post(`${BASE}/transfers`,form);
   if(kind==="partner")await api.post(`${BASE}/partners`,{...form,location_id:locationId||null});
   if(kind==="category")await api.post(`${BASE}/categories`,{...form,location_id:locationId||null});
   if(kind==="payment")await api.post(`${BASE}/payment-methods`,{...form,location_id:locationId||null});
   if(kind==="movement")await api.post(`${BASE}/movements`,form);
   if(kind==="document")await api.post(`${BASE}/documents`,{...form,location_id:locationId||null});
   setNotice("A pénzügyi adat mentése sikeres.");closeModal();refresh();
  }catch(e:any){setError(e?.response?.data?.message||"A mentés nem sikerült.")}finally{setLoading(false)}}
 async function cancelMovement(id:string){const reason=window.prompt("Sztornó indoka:","Téves pénzügyi művelet");if(!reason)return;try{await api.post(`${BASE}/movements/${id}/cancel`,{reason});setNotice("A művelet auditált sztornója elkészült.");refresh()}catch(e:any){setError(e?.response?.data?.message||"A sztornó nem sikerült.")}}
 async function syncSuppliers(){try{const r=await api.post(`${BASE}/partners/sync-suppliers`,{});setNotice(`${Number(r.data?.synced||0)} beszállító partnerfrissítése elkészült.`);refresh()}catch(e:any){setError(e?.response?.data?.message||"A beszállítók szinkronja nem sikerült.")}}
 async function saveSettings(){try{await api.patch(`${BASE}/settings${q(scoped)}`,settings);setNotice("A pénzügyi beállítások mentve.");refresh()}catch(e:any){setError(e?.response?.data?.message||"A beállítások mentése nem sikerült.")}}

 const totals=dashboard.totals||{},trend=dashboard.trend||[],mix=dashboard.payment_mix||[];
 return <div className="fin5-page">
  <header className="fin5-header"><div><span className="fin5-eyebrow">PÉNZÜGYEK · V5</span><h1>Pénzügyi központ</h1><p>{locationName} · pénztárak, partnerek, tranzakciók, dokumentumok és vezetői riportok egy helyen.</p></div><div className="fin5-header-actions"><button className="ghost" onClick={refresh}><RefreshCw size={16}/>{loading?"Betöltés…":"Frissítés"}</button><button className="primary" onClick={()=>{setForm({direction:"income",occurred_at:new Date().toISOString().slice(0,16)});setModal("movement")}}><Plus size={16}/> Új tranzakció</button></div></header>
  <nav className="fin5-tabs">{tabs.map(t=>{const I=t.icon;return <button key={t.key} className={tab===t.key?"active":""} onClick={()=>navigate(tabPath[t.key])}><I size={15}/>{t.label}</button>})}</nav>
  <div className="fin5-period"><label>Időszak<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span>–</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/>{["partners","transactions","documents"].includes(tab)&&<div className="fin5-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Keresés…"/></div>}<div className="spacer"/><button className="ghost" onClick={()=>csv(`penzugy-${tab}-${today()}.csv`,tab==="transactions"?movements:tab==="partners"?filteredPartners:tab==="documents"?filteredDocs:accounts)}>Excel/CSV export</button></div>
  {error&&<div className="fin5-alert error">{error}</div>}{notice&&<div className="fin5-alert ok">{notice}</div>}

  {tab==="overview"&&<>
   <section className="fin5-kpis"><article><div className="icon income"><CircleDollarSign/></div><span>Bevétel</span><b>{money(totals.income)}</b><small>{from} – {to}</small></article><article><div className="icon expense"><Receipt/></div><span>Kiadás</span><b>{money(totals.expense)}</b><small>anyag, bér, rezsi, díjak</small></article><article><div className="icon profit"><BarChart3/></div><span>Eredmény</span><b>{money(totals.net)}</b><small>bevétel − kiadás</small></article><article><div className="icon neutral"><WalletCards/></div><span>Pénzügyi művelet</span><b>{Number(totals.movement_count||0).toLocaleString("hu-HU")}</b><small>auditált tranzakció</small></article></section>
   <div className="fin5-grid two"><section className="fin5-card"><div className="card-head"><div><h2>Pénzforgalom</h2><p>Bevétel és kiadás havi alakulása.</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" tickFormatter={(v)=>String(v).slice(0,7)}/><YAxis tickFormatter={(v)=>`${Math.round(v/1000)}k`}/><Tooltip formatter={(v:any)=>money(v)}/><Legend/><Area type="monotone" dataKey="income" name="Bevétel" stroke="#14b8a6" fill="#99f6e4"/><Area type="monotone" dataKey="expense" name="Kiadás" stroke="#f59e0b" fill="#fde68a"/></AreaChart></ResponsiveContainer></div></section><section className="fin5-card"><div className="card-head"><div><h2>Fizetési mix</h2><p>Bevételek fizetési mód szerint.</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={mix} dataKey="amount" nameKey="payment_method" outerRadius={100} label/><Tooltip formatter={(v:any)=>money(v)}/><Legend/></PieChart></ResponsiveContainer></div></section></div>
   <div className="fin5-grid two"><section className="fin5-card"><div className="card-head"><div><h2>Számlák és pénztárak</h2><p>Aktuális egyenlegek.</p></div><button onClick={()=>navigate("/finance/accounts")}>Részletek</button></div><Table columns={["Név","Típus","Egyenleg"]} rows={(dashboard.accounts||[]).slice(0,8).map((a:Row)=>[a.name,a.account_type,money(a.current_balance)])}/></section><section className="fin5-card"><div className="card-head"><div><h2>Partner-egyenlegek</h2><p>Legnagyobb követelés/tartozás jellegű egyenlegek.</p></div><button onClick={()=>navigate("/finance/partners")}>Partnerek</button></div><Table columns={["Partner","Típus","Egyenleg"]} rows={(dashboard.partner_balances||[]).map((p:Row)=>[p.name,p.partner_type,money(p.balance)])}/></section></div>
  </>}

  {tab==="accounts"&&<section className="fin5-card"><div className="card-head"><div><h2>Számlák és pénztárak</h2><p>Készpénz, bank, kártya, online és utalvány egyenlegek.</p></div><div>{canConfig&&<button onClick={()=>{setForm({account_type:"cash",currency:"HUF",opening_balance:0});setModal("account")}}><Plus size={15}/> Pénztár hozzáadása</button>}<button onClick={()=>{setForm({});setModal("transfer")}}><ArrowLeftRight size={15}/> Átvezetés</button></div></div><div className="fin5-account-grid">{accounts.map(a=><article key={a.id}><div className="account-icon">{a.account_type==="cash"?<Banknote/>:a.account_type==="bank"?<Building2/>:<CreditCard/>}</div><div><span>{a.account_type}</span><h3>{a.name}</h3><b>{money(a.current_balance)}</b><small>{a.currency} · {a.movement_count||0} művelet</small></div></article>)}</div></section>}

  {tab==="partners"&&<section className="fin5-card"><div className="card-head"><div><h2>Partnerek</h2><p>Beszállítók és egyéb pénzügyi partnerek, élő egyenleggel.</p></div><div>{canConfig&&<button onClick={syncSuppliers}>Beszállítók szinkronja</button>}<button onClick={()=>{setForm({partner_type:"supplier",country_code:"HU",opening_balance:0});setModal("partner")}}><Plus size={15}/> Partner hozzáadása</button></div></div><Table columns={["Név","Elérhetőség","Cégadatok","Cím","Egyenleg"]} rows={filteredPartners.map(p=>[<b>{p.name}</b>,[p.email,p.phone].filter(Boolean).join(" · ")||"—",p.tax_number||p.company_name||"—",[p.postal_code,p.city,p.address].filter(Boolean).join(" ")||"—",<span className={num(p.balance)<0?"negative":"positive"}>{money(p.balance)}</span>])}/></section>}

  {tab==="categories"&&<section className="fin5-card"><div className="card-head"><div><h2>Pénztárbizonylat típusok</h2><p>Bevételi, kiadási és vegyes pénzügyi kategóriák.</p></div>{canConfig&&<button onClick={()=>{setForm({direction:"expense",sort_order:100});setModal("category")}}><Plus size={15}/> Bizonylattípus</button>}</div><Table columns={["Név","Irány","Csoport","Kód"]} rows={categories.map(c=>[<b>{c.name}</b>,c.direction==="income"?"Bevétel":c.direction==="expense"?"Kiadás":"Vegyes",c.category_group||"—",c.system_key||c.code||"—"])}/></section>}

  {tab==="transactions"&&<section className="fin5-card"><div className="card-head"><div><h2>Pénzügyi műveletek</h2><p>Részletes, szűrhető pénzmozgás-napló; sztornó törlés helyett.</p></div><button className="primary" onClick={()=>{setForm({direction:"income",occurred_at:new Date().toISOString().slice(0,16)});setModal("movement")}}><Plus size={15}/> Új tranzakció</button></div><div className="fin5-filters"><select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">Összes pénztár</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Összes bizonylattípus</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={partnerFilter} onChange={e=>setPartnerFilter(e.target.value)}><option value="">Összes partner</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={methodFilter} onChange={e=>setMethodFilter(e.target.value)}><option value="">Összes fizetési mód</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">Bevétel + kiadás</option><option value="income">Bevétel</option><option value="expense">Kiadás</option></select></div><div className="fin5-table-wrap"><table><thead><tr><th>Dátum</th><th>Bizonylat / hivatkozás</th><th>Partner</th><th>Pénztár</th><th>Kategória</th><th>Fizetési mód</th><th>Összeg</th><th>Állapot</th><th></th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.occurred_at).toLocaleString("hu-HU")}</td><td>{m.document_number||m.reference_id||m.reference_type||"—"}</td><td>{m.partner_name||m.counterparty||"—"}</td><td>{m.account_name}</td><td>{m.category_name||"—"}</td><td>{m.payment_method_name||"—"}</td><td className={m.direction==="expense"?"negative":"positive"}>{m.direction==="expense"?"−":"+"}{money(m.amount)}</td><td><Status value={m.payment_status}/></td><td>{m.payment_status==="posted"&&<button className="icon-button danger" title="Sztornó" onClick={()=>cancelMovement(m.id)}><XCircle size={16}/></button>}</td></tr>)}</tbody></table></div></section>}

  {tab==="documents"&&<section className="fin5-card"><div className="card-head"><div><h2>Dokumentumok</h2><p>Számlák és pénzügyi bizonylatok egységes dokumentumjegyzéke.</p></div><button onClick={()=>{setForm({document_type:"receipt",direction:"neutral",document_date:today(),currency:"HUF",status:"active"});setModal("document")}}><Plus size={15}/> Dokumentum</button></div><Table columns={["Dátum","Típus","Szám","Partner / ügyfél","Összeg","Állapot"]} rows={filteredDocs.map(d=>[d.document_date,d.document_type,d.document_number||"—",d.partner_display_name||d.partner_name||"—",money(d.gross_total),<Status value={d.status}/>])}/></section>}

  {tab==="online"&&<><section className="fin5-online-grid"><FeatureCard icon={<Link2/>} title="Fizetés linken keresztül" text="Fizetési link vagy QR-kód küldése foglaláshoz és egyedi fizetéshez." enabled={settings.payment_link_enabled}/><FeatureCard icon={<CreditCard/>} title="Előrefizetés online foglalásnál" text="Kötelező vagy opcionális előleg a foglalási folyamatban." enabled={settings.online_booking_prepayment}/><FeatureCard icon={<WalletCards/>} title="Bérletek és utalványok online" text="Bérletek és ajándékutalványok online értékesítésének kapcsolója." enabled={settings.online_sale_memberships}/></section><section className="fin5-card"><div className="card-head"><div><h2>Online fizetési csatornák</h2><p>Az online fizetésekhez rendelt pénztárak és díjak.</p></div><button onClick={()=>navigate("/finance/payment-methods")}>Fizetési módok</button></div><Table columns={["Fizetési mód","Pénztár","Díj","Jóváírás"]} rows={methods.filter(m=>m.online).map(m=>[m.name,m.account_name||"Nincs hozzárendelve",`${num(m.fee_percent)}% + ${money(m.fee_fixed)}`,`${m.processing_days||0} nap`])}/></section></>}

  {tab==="reports"&&<><div className="fin5-grid two"><section className="fin5-card"><div className="card-head"><div><h2>Nyereség és veszteség (P&L)</h2><p>Havi bevétel, kiadás és eredmény.</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={pl.months||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" tickFormatter={(v)=>String(v).slice(0,7)}/><YAxis tickFormatter={(v)=>`${Math.round(v/1000)}k`}/><Tooltip formatter={(v:any)=>money(v)}/><Legend/><Bar dataKey="income" name="Bevétel" fill="#14b8a6"/><Bar dataKey="expense" name="Kiadás" fill="#f59e0b"/><Bar dataKey="profit" name="Eredmény" fill="#64748b"/></BarChart></ResponsiveContainer></div></section><section className="fin5-card"><div className="card-head"><div><h2>Napi kasszariport</h2><p>{to} pénztáranként.</p></div></div><Table columns={["Pénztár","Bevétel","Kiadás","Záró egyenleg"]} rows={dailyCash.map(r=>[r.name,money(r.income),money(r.expense),money(r.closing_balance)])}/></section></div><section className="fin5-card"><div className="card-head"><div><h2>Kategóriaelemzés</h2><p>Bevételi és kiadási tételek megoszlása.</p></div></div><Table columns={["Irány","Kategória","Csoport","Összeg"]} rows={(pl.categories||[]).map((r:Row)=>[r.direction,r.name||"Nincs kategória",r.category_group||"Egyéb",money(r.amount)])}/></section></>}

  {tab==="payments"&&<section className="fin5-card"><div className="card-head"><div><h2>Fizetési módok és díjak</h2><p>Készpénz, bankkártya, átutalás és egyedi módok pénztár-hozzárendeléssel.</p></div>{canConfig&&<button onClick={()=>{setForm({method_type:"custom",fee_percent:0,fee_fixed:0,processing_days:0,rounding_step:0,online:false});setModal("payment")}}><Plus size={15}/> Fizetési mód</button>}</div><div className="fin5-payment-grid">{methods.map(m=><article key={m.id}><div className="payment-title"><CreditCard/><div><span>{m.method_type}</span><h3>{m.name}</h3></div></div><dl><div><dt>Pénztár</dt><dd>{m.account_name||"Nincs hozzárendelve"}</dd></div><div><dt>Tranzakciós díj</dt><dd>{num(m.fee_percent)}% + {money(m.fee_fixed)}</dd></div><div><dt>Feldolgozás</dt><dd>{m.processing_days||0} nap</dd></div><div><dt>Kerekítés</dt><dd>{money(m.rounding_step)}</dd></div></dl>{m.online&&<span className="badge">Online</span>}</article>)}</div></section>}

  {tab==="settings"&&<section className="fin5-settings-grid"><section className="fin5-card"><div className="card-head"><div><h2>Online fizetés</h2><p>Kapcsolók és szolgáltatói állapot; titkos API-kulcsot ez az oldal nem jelenít meg.</p></div></div><Toggle label="Online fizetés engedélyezve" value={!!settings.online_payment_enabled} onChange={v=>setSettings({...settings,online_payment_enabled:v})}/><Toggle label="Fizetési link / QR" value={!!settings.payment_link_enabled} onChange={v=>setSettings({...settings,payment_link_enabled:v})}/><Toggle label="Foglalási előrefizetés" value={!!settings.online_booking_prepayment} onChange={v=>setSettings({...settings,online_booking_prepayment:v})}/><Toggle label="Bérlet és utalvány online értékesítés" value={!!settings.online_sale_memberships} onChange={v=>setSettings({...settings,online_sale_memberships:v})}/><label className="fin5-field">Online szolgáltató<input value={settings.online_payment_provider||""} onChange={e=>setSettings({...settings,online_payment_provider:e.target.value})} placeholder="pl. Stripe / SimplePay"/></label></section><section className="fin5-card"><div className="card-head"><div><h2>Számlázás és kassza</h2><p>NAV/Billingo integrációt megtartó központi beállítások.</p></div></div><label className="fin5-field">Számlázó<select value={settings.invoicing_provider||"billingo"} onChange={e=>setSettings({...settings,invoicing_provider:e.target.value})}><option value="billingo">Billingo</option><option value="szamlazz">Számlázz.hu</option><option value="manual">Egyéb / manuális</option></select></label><label className="fin5-field">Készpénzes kerekítés<input type="number" min="0" value={settings.cash_rounding_step||0} onChange={e=>setSettings({...settings,cash_rounding_step:Number(e.target.value)})}/></label><Toggle label="Kiadásnál partner kötelező" value={!!settings.require_partner_on_expense} onChange={v=>setSettings({...settings,require_partner_on_expense:v})}/><button className="ghost" onClick={()=>navigate("/finance/nav-online-invoice")}>NAV Online Számla beállítás</button></section>{canConfig&&<div className="fin5-settings-save"><button className="primary" onClick={saveSettings}>Beállítások mentése</button></div>}</section>}

  {modal&&<Modal title={modalTitle(modal)} onClose={closeModal}><ModalForm kind={modal} form={form} setForm={setForm} accounts={accounts} partners={partners} categories={categories} methods={methods} onSave={()=>submit(modal)}/></Modal>}
 </div>
}

function Table({columns,rows}:{columns:string[];rows:React.ReactNode[][]}){return <div className="fin5-table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={columns.length} className="empty">Nincs megjeleníthető adat.</td></tr>}</tbody></table></div>}
function Status({value}:{value:any}){const v=String(value||"active");return <span className={`fin5-status ${v}`}>{v==="posted"?"Könyvelt":v==="cancelled"?"Sztornó":v==="reversal"?"Sztornó tétel":v==="active"?"Aktív":v}</span>}
function FeatureCard({icon,title,text,enabled}:{icon:React.ReactNode;title:string;text:string;enabled:any}){return <article className="fin5-feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p><span className={enabled?"enabled":"disabled"}>{enabled?"Bekapcsolva":"Beállítás szükséges"}</span></article>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="fin5-toggle"><span>{label}</span><button type="button" className={value?"on":""} onClick={()=>onChange(!value)}><i/></button></label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fin5-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="fin5-modal"><header><h2>{title}</h2><button className="icon-button" onClick={onClose}>×</button></header>{children}</div></div>}
function modalTitle(k:string){return({account:"Új pénztár / számla",transfer:"Pénz átvezetése",partner:"Új partner",category:"Új bizonylattípus",payment:"Új fizetési mód",movement:"Új pénzügyi tranzakció",document:"Új pénzügyi dokumentum"}as Row)[k]||"Pénzügyi adat"}
function ModalForm({kind,form,setForm,accounts,partners,categories,methods,onSave}:{kind:string;form:Row;setForm:(v:Row)=>void;accounts:Row[];partners:Row[];categories:Row[];methods:Row[];onSave:()=>void}){const f=(k:string)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setForm({...form,[k]:e.target.type==="number"?Number(e.target.value):e.target.value});return <div className="fin5-form">
 {kind==="account"&&<><label>Név<input value={form.name||""} onChange={f("name")}/></label><label>Típus<select value={form.account_type||"cash"} onChange={f("account_type")}><option value="cash">Készpénz</option><option value="bank">Bankszámla</option><option value="card">Kártyaelszámolás</option><option value="online">Online</option><option value="voucher">Utalvány</option><option value="other">Egyéb</option></select></label><label>Nyitó egyenleg<input type="number" value={form.opening_balance||0} onChange={f("opening_balance")}/></label><label>Számlaszám<input value={form.account_number||""} onChange={f("account_number")}/></label></>}
 {kind==="transfer"&&<><label>Forrás<select value={form.source_account_id||""} onChange={f("source_account_id")}><option value="">Válassz</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.current_balance)}</option>)}</select></label><label>Cél<select value={form.destination_account_id||""} onChange={f("destination_account_id")}><option value="">Válassz</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Összeg<input type="number" min="0" value={form.amount||0} onChange={f("amount")}/></label></>}
 {kind==="partner"&&<><label>Név<input value={form.name||""} onChange={f("name")}/></label><label>Típus<select value={form.partner_type||"supplier"} onChange={f("partner_type")}><option value="supplier">Beszállító</option><option value="customer">Ügyfél</option><option value="employee">Munkatárs</option><option value="other">Egyéb</option></select></label><label>Adószám<input value={form.tax_number||""} onChange={f("tax_number")}/></label><label>E-mail<input value={form.email||""} onChange={f("email")}/></label><label>Telefon<input value={form.phone||""} onChange={f("phone")}/></label><label>Cím<input value={form.address||""} onChange={f("address")}/></label></>}
 {kind==="category"&&<><label>Név<input value={form.name||""} onChange={f("name")}/></label><label>Irány<select value={form.direction||"expense"} onChange={f("direction")}><option value="income">Bevétel</option><option value="expense">Kiadás</option><option value="both">Vegyes</option></select></label><label>Csoport<input value={form.category_group||""} onChange={f("category_group")}/></label></>}
 {kind==="payment"&&<><label>Név<input value={form.name||""} onChange={f("name")}/></label><label>Kód<input value={form.code||""} onChange={f("code")}/></label><label>Típus<select value={form.method_type||"custom"} onChange={f("method_type")}><option value="cash">Készpénz</option><option value="debit_card">Betéti kártya</option><option value="credit_card">Hitelkártya</option><option value="bank_transfer">Átutalás</option><option value="online">Online</option><option value="voucher">Utalvány</option><option value="custom">Egyedi</option></select></label><label>Pénztár<select value={form.account_id||""} onChange={f("account_id")}><option value="">Nincs</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Díj %<input type="number" min="0" step="0.01" value={form.fee_percent||0} onChange={f("fee_percent")}/></label><label>Fix díj<input type="number" min="0" value={form.fee_fixed||0} onChange={f("fee_fixed")}/></label><label>Feldolgozás nap<input type="number" min="0" value={form.processing_days||0} onChange={f("processing_days")}/></label></>}
 {kind==="movement"&&<><label>Pénztár<select value={form.account_id||""} onChange={f("account_id")}><option value="">Válassz</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Irány<select value={form.direction||"income"} onChange={f("direction")}><option value="income">Bevétel</option><option value="expense">Kiadás</option></select></label><label>Összeg<input type="number" min="0" value={form.amount||0} onChange={f("amount")}/></label><label>Dátum<input type="datetime-local" value={form.occurred_at||""} onChange={f("occurred_at")}/></label><label>Kategória<select value={form.category_id||""} onChange={f("category_id")}><option value="">Nincs</option>{categories.filter(c=>c.direction==="both"||c.direction===form.direction).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Partner<select value={form.partner_id||""} onChange={f("partner_id")}><option value="">Nincs</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Fizetési mód<select value={form.payment_method_id||""} onChange={f("payment_method_id")}><option value="">Nincs</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></>}
 {kind==="document"&&<><label>Típus<select value={form.document_type||"receipt"} onChange={f("document_type")}><option value="receipt">Bizonylat</option><option value="invoice">Számla</option><option value="credit_note">Jóváírás</option><option value="cash_voucher">Pénztárbizonylat</option><option value="other">Egyéb</option></select></label><label>Dokumentumszám<input value={form.document_number||""} onChange={f("document_number")}/></label><label>Dátum<input type="date" value={form.document_date||today()} onChange={f("document_date")}/></label><label>Partner<select value={form.partner_id||""} onChange={f("partner_id")}><option value="">Nincs</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Összeg<input type="number" value={form.gross_total||0} onChange={f("gross_total")}/></label></>}
 <label className="wide">Megjegyzés<textarea value={form.note||""} onChange={f("note")}/></label><div className="form-actions"><button className="primary" onClick={onSave}>Mentés</button></div></div>}
