import { Navigate, type RouteObject } from "react-router-dom";
import {
  ADMIN_ROLES as ADMIN,
  KIOSK_MANAGER_ROLES as KIOSK_MANAGERS,
  MANAGEMENT_ROLES as MANAGEMENT,
  RECEPTION_ROLES as RECEPTION,
  authenticated as A,
  roleProtected as R,
} from "./routeAccess";
import { VirHungarianPageGuide } from "../components/VirHungarianPageGuide";
import {
  AccessControlPage, ChecklistsPage, DailyActionsPage, GdprCenterPage, KioskAdmin, KnowledgeBasePage,
  LoyaltyAutomationPage, LoyaltyModulePage, LoyaltyPage, LoyaltyProgramPage, LoyaltySalesRulesPage,
  ManagementImprovementPage, MobileAppAdminPage, ModulePlaceholderPage, ModuleRoutesPage, NewsletterPage,
  OperationsQualityPage, SaasFranchiseAdminPage, SecuritySettingsPage, SignageAdmin, SignageAppearanceAdmin, SystemHealthPage,
  SystemSettingsPage, UatTestCenterPage, VirActionCenterPage, VirDashboardPage, VirIntelligencePage,
  VirManagerCockpitPage, VirP1Page, VirP2Page, VirP3Page, VirP4Page, VirP5Page, VirP6Page, VirP7Page,
  VirP8Page, VirP9Page, VirP10Page, VirP11Page, VirP12Page, VirP13Page, VirP14Page, VirP15Page, VirP16Page,
  ReceptionGuestActionsPage, VirRevenueLeakagePage, VirReportsAdminPage, VirServiceDetailPage,
  VirSpecParityPage, VirStaffDetailPage, WallBoardDailyActionPage, WebshopAdmin, WebsiteAdminPage,
  WebsitePagesAdminPage, MenuLayoutPage,
} from "./routePages";

const V = (page: Parameters<typeof VirHungarianPageGuide>[0]["page"], child: React.ReactNode) => (
  <VirHungarianPageGuide page={page}>{child}</VirHungarianPageGuide>
);

export const adminRoutes: RouteObject[] = [
  { path: "/admin/security-settings", element: R(ADMIN, <SecuritySettingsPage />) },
  { path: "/admin/system-health", element: R(MANAGEMENT, <SystemHealthPage />) },
  { path: "/admin/uat", element: R(MANAGEMENT, <UatTestCenterPage />) },
  { path: "/admin/saas", element: R(ADMIN, <SaasFranchiseAdminPage />) },
  { path: "/admin/menu-layout", element: R(ADMIN, <MenuLayoutPage />) },
  { path: "/admin/website", element: R(MANAGEMENT, <WebsiteAdminPage />) },
  { path: "/admin/website/pages", element: R(MANAGEMENT, <WebsitePagesAdminPage />) },
  { path: "/loyalty/sales-rules", element: A(<LoyaltySalesRulesPage />) },
  { path: "/loyalty/automation", element: A(<LoyaltyAutomationPage />) },
  { path: "/loyalty", element: A(<LoyaltyPage />) },
  { path: "/loyalty/*", element: A(<LoyaltyPage />) },
  { path: "/extra/tasks", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/operations/tasks", element: <Navigate to="/extra/tasks" replace /> },
  { path: "/spec/maintenance", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/operations/maintenance", element: <Navigate to="/spec/maintenance" replace /> },
  { path: "/extra/documents", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/operations/documents", element: <Navigate to="/extra/documents" replace /> },
  { path: "/spec/internal-email", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/operations/email", element: <Navigate to="/spec/internal-email" replace /> },
  { path: "/marketing/complaints", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/operations/complaints", element: <Navigate to="/marketing/complaints" replace /> },
  { path: "/operations/improvement", element: R(MANAGEMENT, <ManagementImprovementPage />) },
  { path: "/operations/audits", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/operations/incidents", element: R(MANAGEMENT, <OperationsQualityPage />) },
  { path: "/extra/chat", element: <Navigate to="/staff/chat" replace /> },
  { path: "/marketing/newsletter", element: R(MANAGEMENT, <NewsletterPage />) },
  { path: "/marketing/daily-deals", element: R(MANAGEMENT, <DailyActionsPage />) },
  { path: "/marketing/wallboard", element: R(MANAGEMENT, <WallBoardDailyActionPage />) },
  { path: "/admin/mobile-app", element: R(MANAGEMENT, <MobileAppAdminPage />) },
  { path: "/modules/customers/loyalty-program", element: R(MANAGEMENT, <LoyaltyProgramPage />) },
  { path: "/modules/loyalty/*", element: R(MANAGEMENT, <LoyaltyModulePage />) },
  { path: "/admin/access-control", element: R(ADMIN, <AccessControlPage />) },
  { path: "/modules/settings/audit-log", element: R(MANAGEMENT, <ModulePlaceholderPage />) },
  { path: "/modules/settings/chat-supervision", element: R(MANAGEMENT, <ModulePlaceholderPage />) },
  { path: "/admin/vir", element: R(MANAGEMENT, V("cockpit", <VirManagerCockpitPage />)) },
  { path: "/admin/vir/cockpit", element: R(MANAGEMENT, V("cockpit", <VirManagerCockpitPage />)) },
  { path: "/admin/vir/dashboard", element: R(MANAGEMENT, <VirDashboardPage />) },
  { path: "/admin/vir/actions", element: R(MANAGEMENT, V("actions", <VirActionCenterPage />)) },
  { path: "/admin/vir/intelligence", element: R(MANAGEMENT, V("p0", <VirIntelligencePage />)) },
  { path: "/admin/vir/p1", element: R(MANAGEMENT, V("p1", <VirP1Page />)) },
  { path: "/admin/vir/p2", element: R(MANAGEMENT, V("p2", <VirP2Page />)) },
  { path: "/admin/vir/p3", element: R(MANAGEMENT, V("p3", <VirP3Page />)) },
  { path: "/admin/vir/p3/revenue-leakage", element: R(MANAGEMENT, V("revenue-leakage", <VirRevenueLeakagePage />)) },
  { path: "/admin/vir/p4", element: R(MANAGEMENT, V("p4", <VirP4Page />)) },
  { path: "/admin/vir/p5", element: R(MANAGEMENT, V("p5", <VirP5Page />)) },
  { path: "/admin/vir/p6", element: R(MANAGEMENT, V("p6", <VirP6Page />)) },
  { path: "/admin/vir/p7", element: R(MANAGEMENT, V("p7", <VirP7Page />)) },
  { path: "/admin/vir/p8", element: R(MANAGEMENT, V("p8", <VirP8Page />)) },
  { path: "/admin/vir/p9", element: R(MANAGEMENT, V("p9", <VirP9Page />)) },
  { path: "/admin/vir/p10", element: R(MANAGEMENT, V("p10", <VirP10Page />)) },
  { path: "/admin/vir/p11", element: R(MANAGEMENT, V("p11", <VirP11Page />)) },
  { path: "/admin/vir/p12", element: R(MANAGEMENT, V("p12", <VirP12Page />)) },
  { path: "/admin/vir/p13", element: R(MANAGEMENT, V("p13", <VirP13Page />)) },
  { path: "/admin/vir/p14", element: R(MANAGEMENT, V("p14", <VirP14Page />)) },
  { path: "/admin/vir/p15", element: R(MANAGEMENT, V("p15", <VirP15Page />)) },
  { path: "/admin/vir/p16", element: R(MANAGEMENT, V("p16", <VirP16Page />)) },
  { path: "/admin/reception/guest-actions", element: R(RECEPTION, <ReceptionGuestActionsPage />) },
  { path: "/admin/finance", element: R(MANAGEMENT, <VirDashboardPage />) },
  { path: "/admin/reports", element: R(MANAGEMENT, <VirReportsAdminPage />) },
  { path: "/admin/vir/spec-parity", element: R(MANAGEMENT, <VirSpecParityPage />) },
  { path: "/admin/vir/staff/:id", element: R(MANAGEMENT, <VirStaffDetailPage />) },
  { path: "/admin/vir/services/:id", element: R(MANAGEMENT, <VirServiceDetailPage />) },
  { path: "/admin/vir/reports", element: R(MANAGEMENT, <VirReportsAdminPage />) },
  { path: "/signage", element: R(MANAGEMENT, <SignageAdmin />) },
  { path: "/signage/appearance", element: R(MANAGEMENT, <SignageAppearanceAdmin />) },
  { path: "/kiosk", element: R(KIOSK_MANAGERS, <KioskAdmin />) },
  { path: "/kiosk/admin", element: R(KIOSK_MANAGERS, <KioskAdmin />) },
  { path: "/webshop/admin", element: R(MANAGEMENT, <WebshopAdmin />) },
  { path: "/marketing", element: <Navigate to="/modules/marketing/campaigns" replace /> },
  { path: "/extras", element: <Navigate to="/extra/tasks" replace /> },
  { path: "/settings", element: R(MANAGEMENT, <SystemSettingsPage />) },
  { path: "/settings/security", element: <Navigate to="/admin/security-settings" replace /> },
  { path: "/settings/menu-order", element: <Navigate to="/admin/menu-layout" replace /> },
  { path: "/settings/system-health", element: <Navigate to="/admin/system-health" replace /> },
  { path: "/settings/uat", element: <Navigate to="/admin/uat" replace /> },
  { path: "/settings/gdpr", element: <Navigate to="/admin/gdpr" replace /> },
  { path: "/admin/gdpr", element: R(MANAGEMENT, <GdprCenterPage />) },
  { path: "/knowledge-base/checklists", element: A(<ChecklistsPage />) },
  { path: "/knowledge-base/library", element: A(<KnowledgeBasePage />) },
  { path: "/knowledge-base/processes", element: A(<KnowledgeBasePage />) },
  { path: "/knowledge-base/quiz", element: A(<KnowledgeBasePage />) },
  { path: "/knowledge-base", element: <Navigate to="/knowledge-base/library" replace /> },
  { path: "/spec/:moduleKey", element: A(<ModulePlaceholderPage />) },
  { path: "/modules/:moduleKey/*", element: A(<ModuleRoutesPage />) },
  { path: "*", element: <ModuleRoutesPage /> },
];