import { Navigate, type RouteObject } from "react-router-dom";
import {
  KIOSK_MANAGER_ROLES as KIOSK_MANAGERS,
  MANAGEMENT_ROLES as MANAGEMENT,
  authenticated as A,
  roleProtected as R,
} from "./routeAccess";
import {
  CentralMasterDataPage,
  CentralSupplyPage,
  InventoryLotsPage,
  InventoryOperationsPage,
  Logisztika,
  ProductTaxonomyReviewPage,
  ProductsList,
  ServicesList,
} from "./routePages";

export const inventoryRoutes: RouteObject[] = [
  { path: "/logisztika", element: A(<Logisztika />) },
  { path: "/warehouse", element: A(<Logisztika />) },
  { path: "/warehouse/list", element: A(<Logisztika />) },
  { path: "/warehouse/operations", element: R(KIOSK_MANAGERS, <InventoryOperationsPage />) },
  { path: "/warehouse/lots", element: R(KIOSK_MANAGERS, <InventoryLotsPage />) },
  { path: "/masterdata", element: R(MANAGEMENT, <CentralMasterDataPage />) },
  { path: "/masterdata/salons", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="salons" />) },
  { path: "/masterdata/departments", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="departments" />) },
  { path: "/masterdata/equipment-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="equipment-types" />) },
  { path: "/masterdata/assets", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="equipment" />) },
  { path: "/masterdata/equipment", element: <Navigate to="/masterdata/assets" replace /> },
  { path: "/masterdata/suppliers", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="suppliers" />) },
  { path: "/masterdata/warehouses", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="warehouses" />) },
  { path: "/masterdata/units", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="units" />) },
  { path: "/masterdata/price-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="price-types" />) },
  { path: "/masterdata/leave-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="leave-types" />) },
  { path: "/masterdata/movement-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="movement-types" />) },
  { path: "/masterdata/stock-movement-types", element: <Navigate to="/masterdata/movement-types" replace /> },
  { path: "/masterdata/payment-methods", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="payment-methods" />) },
  { path: "/masterdata/financial-transaction-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="financial-transaction-types" />) },
  { path: "/spec/warehouses", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="warehouses" />) },
  { path: "/spec/leave-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="leave-types" />) },
  { path: "/spec/financial-transaction-types", element: R(MANAGEMENT, <CentralMasterDataPage entityKey="financial-transaction-types" />) },
  { path: "/masterdata/products/taxonomy-review", element: R(MANAGEMENT, <ProductTaxonomyReviewPage />) },
  { path: "/warehouse/products", element: A(<ProductsList />) },
  { path: "/warehouse/products/*", element: A(<ProductsList />) },
  { path: "/products", element: A(<ProductsList />) },
  { path: "/products/*", element: A(<ProductsList />) },
  { path: "/masterdata/products", element: A(<ProductsList />) },
  { path: "/masterdata/products/*", element: A(<ProductsList />) },
  {
    path: "/inventory/products",
    element: <Navigate to="/warehouse/products" replace />,
  },
  { path: "/inventory", element: <Navigate to="/warehouse" replace /> },
  { path: "/inventory/*", element: <Navigate to="/warehouse" replace /> },
  { path: "/warehouse/central-supply", element: A(<CentralSupplyPage />) },
  {
    path: "/procurement",
    element: <Navigate to="/warehouse?view=procurement&section=dashboard" replace />,
  },
  {
    path: "/procurement/*",
    element: <Navigate to="/warehouse?view=procurement&section=dashboard" replace />,
  },
  {
    path: "/warehouse/procurement",
    element: <Navigate to="/warehouse?view=procurement&section=dashboard" replace />,
  },
  { path: "/masters", element: R(MANAGEMENT, <ServicesList />) },
  { path: "/masterdata/services", element: R(MANAGEMENT, <ServicesList />) },
  { path: "/masterdata/services/*", element: R(MANAGEMENT, <ServicesList />) },
  { path: "/services", element: R(MANAGEMENT, <ServicesList />) },
  { path: "/services/*", element: R(MANAGEMENT, <ServicesList />) },
  {
    path: "/spec/inventory-orders",
    element: <Navigate to="/warehouse/central-supply" replace />,
  },
];
