import React, { Suspense, lazy, type ReactElement } from "react";
import { createBrowserRouter, RouterProvider, Navigate } from "react-router-dom";
import EmployeeDetailsPage from "./pages/EmployeeDetails";
import ProductsList from "./pages/ProductsList";
import WebshopAdmin from "./pages/WebshopAdmin";
import "./styles/kleo-theme.css";
import AppLayout from "./layouts/AppLayout";
const AppointmentsCalendar=lazy(()=>import("./pages/AppointmentsCalendar"));const Login=lazy(()=>import("./pages/Login"));const Home=lazy(()=>import("./pages/Home"));const Bejelentkezesek=lazy(()=>import("./pages/Bejelentkezesek"));const Munkalapok=lazy(()=>import("./pages/Munkalapok"));const Penzugy=lazy(()=>import("./pages/Penzugy"));const Logisztika=lazy(()=>import("./pages/Logisztika"));const Register=lazy(()=>import("./pages/Register"));const WorkOrdersList=lazy(()=>import("./pages/WorkOrdersList"));const WorkOrderNew=lazy(()=>import("./pages/WorkOrderNew"));const EmployeesList=lazy(()=>import("./pages/EmployeesList"));const ServicesList=lazy(()=>import("./pages/ServicesList"));const SignageAdmin=lazy(()=>import("./pages/SignageAdmin"));const KioskAdmin=lazy(()=>import("./pages/KioskAdmin"));const TimetableUpdatePage=lazy(()=>import("./pages/TimetableUpdatePage"));const HrAttendancePage=lazy(()=>import("./pages/HrAttendancePage"));const PayrollPage=lazy(()=>import("./pages/PayrollPage"));const AccessControlPage=lazy(()=>import("./pages/AccessControlPage"));const VirDashboardPage=lazy(()=>import("./pages/VirDashboardPage"));const VirStaffDetailPage=lazy(()=>import("./pages/VirStaffDetailPage"));const VirServiceDetailPage=lazy(()=>import("./pages/VirServiceDetailPage"));const VirReportsAdminPage=lazy(()=>import("./pages/VirReportsAdminPage"));const VirTopMetricsPage=lazy(()=>import("./pages/VirTopMetricsPage"));const ModulePlaceholderPage=lazy(()=>import("./pages/ModulePlaceholderPage"));const AppointmentsModulePage=lazy(()=>import("./pages/AppointmentsModulePage"));const ClientsCRMPage=lazy(()=>import("./pages/ClientsCRMPage"));const StaffImportPage=lazy(()=>import("./pages/StaffImportPage"));const SystemHealthPage=lazy(()=>import("./pages/SystemHealthPage"));
const HOME_PATH="/";function getToken(){try{return typeof window==="undefined"?null:localStorage.getItem("kleo_token")||localStorage.getItem("token")}catch{return null}}type GuardProps={children:ReactElement};function RequireAuth({children}:GuardProps){if(!getToken())return <Navigate to="/login" replace/>;const legacy=React.isValidElement(children)&&children.type==="div";return <AppLayout>{legacy?<ModulePlaceholderPage/>:children}</AppLayout>}function PublicOnly({children}:GuardProps){return getToken()?<Navigate to={HOME_PATH} replace/>:children}function FallbackRedirect(){return <Navigate to={getToken()?HOME_PATH:"/login"} replace/>}
const A=(el:ReactElement)=><RequireAuth>{el}</RequireAuth>;
const router=createBrowserRouter([
{path:"/login",element:<PublicOnly><Login/></PublicOnly>},{path:"/register",element:<PublicOnly><Register/></PublicOnly>},{path:"/",element:A(<Home/>)},{path:"/dashboard",element:A(<Home/>)},{path:"/dashboard/summary",element:A(<Home/>)},{path:"/dashboard/quick",element:A(<Home/>)},{path:"/dashboard/shift",element:A(<HrAttendancePage/>)},{path:"/admin/system-health",element:A(<SystemHealthPage/>)},
{path:"/modules/appointments/:view",element:A(<AppointmentsModulePage/>)},{path:"/modules/team/payroll",element:A(<PayrollPage/>)},{path:"/modules/team/roles",element:A(<AccessControlPage/>)},{path:"/admin/access-control",element:A(<AccessControlPage/>)},{path:"/hr/positions",element:A(<EmployeesList/>)},{path:"/modules/team/import",element:A(<StaffImportPage/>)},{path:"/modules/customers/:view",element:A(<ClientsCRMPage/>)},
{path:"/bejelentkezesek",element:A(<Bejelentkezesek/>)},{path:"/munkalapok",element:A(<Munkalapok/>)},{path:"/penzugy",element:A(<Penzugy/>)},{path:"/finance",element:A(<Penzugy/>)},{path:"/logisztika",element:A(<Logisztika/>)},{path:"/warehouse",element:A(<Logisztika/>)},{path:"/warehouse/list",element:A(<Logisztika/>)},{path:"/warehouse/products",element:A(<ProductsList/>)},{path:"/masters",element:A(<ServicesList/>)},{path:"/hr",element:A(<EmployeesList/>)},
{path:"/reports",element:<Navigate to="/reports/top-metrics" replace/>},{path:"/reports/top-metrics",element:A(<VirTopMetricsPage/>)},{path:"/appointments/calendar",element:A(<AppointmentsCalendar/>)},{path:"/workorders",element:A(<WorkOrdersList/>)},{path:"/workorders/list",element:A(<WorkOrdersList/>)},{path:"/workorders/new",element:A(<WorkOrderNew/>)},{path:"/employees",element:A(<EmployeesList/>)},{path:"/employees/:id",element:A(<EmployeeDetailsPage/>)},{path:"/services",element:A(<ServicesList/>)},
{path:"/modules/team/timetable",element:A(<TimetableUpdatePage/>)},{path:"/modules/team/attendance",element:A(<HrAttendancePage/>)},{path:"/admin/vir",element:A(<VirDashboardPage/>)},{path:"/admin/vir/staff/:id",element:A(<VirStaffDetailPage/>)},{path:"/admin/vir/services/:id",element:A(<VirServiceDetailPage/>)},{path:"/admin/vir/reports",element:A(<VirReportsAdminPage/>)},{path:"/signage",element:A(<SignageAdmin/>)},{path:"/kiosk",element:A(<KioskAdmin/>)},{path:"/webshop/admin",element:A(<WebshopAdmin/>)},
{path:"/marketing",element:<Navigate to="/modules/marketing/campaigns" replace/>},{path:"/extras",element:<Navigate to="/extra/tasks" replace/>},{path:"/finance/transaction",element:<Navigate to="/finance" replace/>},{path:"/finance/transactions",element:A(<Penzugy/>)},{path:"/finance/invoices/out",element:A(<Penzugy/>)},{path:"/finance/invoices/in",element:A(<Penzugy/>)},{path:"/settings",element:A(<ModulePlaceholderPage/>)},{path:"/knowledge-base",element:A(<ModulePlaceholderPage/>)},{path:"/spec/:moduleKey",element:A(<ModulePlaceholderPage/>)},{path:"/modules/:moduleKey/*",element:A(<ModulePlaceholderPage/>)},{path:"*",element:<FallbackRedirect/>}
]);
export default function App(){return <Suspense fallback={<div style={{padding:"2rem"}}>Betöltés…</div>}><RouterProvider router={router}/></Suspense>}
