import{requirementIdFor,summarizeTraceability,toRequirementTrace,traceabilityCsv}from'./requirements/traceability';

describe('requirements traceability',()=>{
 test('deterministic legacy requirement id is generated from UAT code',()=>{expect(requirementIdFor('UAT-FIN-001')).toBe('REQ-FIN-001')});
 test('backend requirement metadata overrides legacy fallback',()=>{const x=toRequirementTrace({code:'UAT-RBAC-001',title:'Jogosultság',expected_result:'Tiltott szerepkör 403 választ kap.',critical:true,status:'passed',catalog_requirement_id:'KLEO-FUN-AUTH-001',acceptance_criteria_id:'KLEO-FUN-AUTH-001-AC-02',external_test_case_id:'TC-KLEO-FUN-AUTH-001-AC-02',requirement_text:'Jogosultság nélküli üzlethez nem enged belépést.',acceptance_criteria:'403 választ ad.',priority:'must',verification_method:'security',evidence_required:true});expect(x.requirementId).toBe('KLEO-FUN-AUTH-001');expect(x.acceptanceCriteriaId).toBe('KLEO-FUN-AUTH-001-AC-02');expect(x.externalTestCaseId).toBe('TC-KLEO-FUN-AUTH-001-AC-02');expect(x.priority).toBe('P0');expect(x.verificationMethod).toBe('security')});
 test('release gate opens only with canonical mapping and full passing coverage',()=>{const rows=[toRequirementTrace({code:'UAT-AUTH-001',title:'Belépés',expected_result:'OK',critical:true,status:'passed',catalog_requirement_id:'KLEO-FUN-AUTH-001',acceptance_criteria_id:'KLEO-FUN-AUTH-001-AC-01',external_test_case_id:'TC-KLEO-FUN-AUTH-001-AC-01'}),toRequirementTrace({code:'UAT-BOOK-001',title:'Foglalás',expected_result:'OK',critical:true,status:'passed',catalog_requirement_id:'KLEO-FUN-BOOK-001',acceptance_criteria_id:'KLEO-FUN-BOOK-001-AC-01',external_test_case_id:'TC-KLEO-FUN-BOOK-001-AC-01'})];expect(summarizeTraceability(rows)).toMatchObject({coveragePercent:100,canonicalPercent:100,criticalOpen:0,releaseReady:true})});
 test('release gate blocks untested, failed or unmapped requirements',()=>{const rows=[toRequirementTrace({code:'UAT-SYS-001',title:'Rendszer',expected_result:'OK',critical:true,status:'not_tested'}),toRequirementTrace({code:'UAT-FIN-001',title:'Pénzügy',expected_result:'OK',critical:true,status:'failed'})];const s=summarizeTraceability(rows);expect(s.releaseReady).toBe(false);expect(s.criticalOpen).toBe(2);expect(s.canonicalPercent).toBe(0)});
 test('CSV export contains canonical traceability columns',()=>{const csv=traceabilityCsv([toRequirementTrace({code:'UAT-GDPR-001',title:'GDPR',expected_result:'Adatkérés teljesül.',status:'passed',catalog_requirement_id:'KLEO-NFR-SEC-001',acceptance_criteria_id:'KLEO-NFR-SEC-001-AC-01',external_test_case_id:'TC-KLEO-NFR-SEC-001-AC-01'})]);expect(csv).toContain('Requirement ID');expect(csv).toContain('Acceptance criterion ID');expect(csv).toContain('KLEO-NFR-SEC-001');expect(csv).toContain('External test case ID')});
});
