import React,{useEffect,useMemo,useState}from"react";
import api from"../../api";

type Req={id:string;location_id:string;location_name:string;product_id:string;product_name:string;requested_quantity:number|string;approved_quantity?:number|string|null;supplied_quantity:number|string;status:string;central_quantity:number|string;salon_quantity:number|string;purchase_order_id?:string|number|null;created_at:string};
type Transfer={id:string;request_id?:string|null;product_name:string;destination_name:string;quantity:number|string;status:string;created_at:string};
type Discrepancy={id:string;transfer_id:string;destination_name:string;product_name:string;expected_quantity:number|string;received_quantity:number|string;shortage_quantity:number|string;created_at:string};
const arr=<T,>(v:any):T[]=>Array.isArray(v)?v:[];const q=(v:any)=>Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:3});
export default function CentralSupplyPanel({locationId,onChanged}:{locationId:string;onChanged?:()=>void}){const[requests,setRequests]=useState<Req[]>([]),[transfers,setTransfers]=useState<Transfer[]>([]),[discrepancies,setDiscrepancies]=useState<Discrepancy[]>([]),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const query=locationId?`?location_id=${encodeURIComponent(locationId)}`:"";async function load(){setError("");try{const[r,t,d]=await Promise.all([api.get(`/api/transactions/central-supply/requests${query}`),api.get(`/api/transactions/central-supply/transfers${query}`),api.get(`/api/transactions/central-supply/discrepancies`)]);setRequests(arr<Req>(r.data));setTransfers(arr<Transfer>(t.data));setDiscrepancies(arr<Discrepancy>(d.data))}catch(e:any){setError(e?.response?.data?.message||"A központi ellátási folyamat nem tölthető be.")}}
 useEffect(()=>{void load()},[locationId]);
 const open=useMemo(()=>requests.filter(r=>!["supplied","cancelled"].includes(r.status)),[requests]);
 async function approve(r:Req){try{await api.post(`/api/transactions/central-supply/requests/${r.id}/approve`,{approved_quantity:Number(r.requested_quantity)});setSuccess("Az igény jóváhagyva.");await load()}catch(e:any){setError(e?.response?.data?.message||"A jóváhagyás nem sikerült.")}}
 async function allocate(r:Req){try{await api.post(`/api/transactions/central-supply/requests/${r.id}/allocate`,{});setSuccess("A központi készletből átadás készült.");await load()}catch(e:any){if(e?.response?.data?.can_procure)setError("A központi készlet nem elegendő. Indíts beszállítói rendelést.");else setError(e?.response?.data?.message||"Az allokáció nem sikerült.")}}
 async function procure(r:Req){try{const x=await api.post(`/api/transactions/central-supply/requests/${r.id}/procure`,{});setSuccess(`Beszállítói rendelés létrejött: #${x.data?.purchase_order?.id}. Jóváhagyás után rendelhető.`);await load()}catch(e:any){setError(e?.response?.data?.message||"A beszállítói rendelés nem hozható létre.")}}
 async function dispatch(t:Transfer){try{await api.post(`/api/transactions/central-supply/transfers/${t.id}/dispatch`,{});setSuccess("Az áru elküldve a szalonba.");await load();onChanged?.()}catch(e:any){setError(e?.response?.data?.message||"A kiküldés nem sikerült.")}}
 async function receive(t:Transfer){const raw=window.prompt("Ténylegesen átvett mennyiség:",String(t.quantity));if(raw==null)return;try{const x=await api.post(`/api/transactions/central-supply/transfers/${t.id}/receive`,{received_quantity:Number(raw)});setSuccess(Number(x.data?.shortage)>0?`Érkeztetve, ${q(x.data.shortage)} hiány eltérésként rögzítve.`:"A szalon érkeztetése megtörtént.");await load();onChanged?.()}catch(e:any){setError(e?.response?.data?.message||"Az érkeztetés nem sikerült.")}}
 return <section className="proc-card"><header><div><span>KÖZPONTI ELLÁTÁS</span><h2>Szalonigény → központ → beszállító/szalon</h2><p>A rendszer először a központi készletet használja; hiány esetén preferált beszállítóból beszerzési rendelést képez.</p></div><button onClick={load}>Frissítés</button></header>{error&&<div className="proc-alert error">{error}</div>}{success&&<div className="proc-alert success">{success}</div>}
 <div className="proc-kpis"><div><strong>{open.length}</strong><span>Nyitott szalonigény</span></div><div><strong>{transfers.filter(t=>t.status==='prepared').length}</strong><span>Előkészített átadás</span></div><div><strong>{transfers.filter(t=>t.status==='dispatched').length}</strong><span>Úton a szalonba</span></div><div><strong>{discrepancies.length}</strong><span>Nyitott készleteltérés</span></div></div>
 <div className="proc-table"><table><thead><tr><th>Szalon</th><th>Termék</th><th>Igény</th><th>Központ</th><th>Szalon készlet</th><th>Státusz</th><th></th></tr></thead><tbody>{requests.map(r=>{const remaining=Number(r.approved_quantity||r.requested_quantity)-Number(r.supplied_quantity||0),enough=Number(r.central_quantity)>=remaining;return <tr key={r.id}><td>{r.location_name}</td><td><b>{r.product_name}</b></td><td>{q(r.requested_quantity)}</td><td>{q(r.central_quantity)}</td><td>{q(r.salon_quantity)}</td><td>{r.status}{r.purchase_order_id?` · PO #${r.purchase_order_id}`:""}</td><td>{r.status==='requested'?<button onClick={()=>approve(r)}>Jóváhagyás</button>:['approved','partially_supplied'].includes(r.status)?enough?<button onClick={()=>allocate(r)}>Központból kiadás</button>:r.purchase_order_id?<span>Beszerzés folyamatban</span>:<button onClick={()=>procure(r)}>Beszállítói rendelés</button>:null}</td></tr>})}{!requests.length&&<tr><td colSpan={7} className="proc-empty">Nincs szalon készletigény.</td></tr>}</tbody></table></div>
 <h3 style={{marginTop:24}}>Központ → szalon átadások</h3><div className="proc-table"><table><thead><tr><th>Szalon</th><th>Termék</th><th>Mennyiség</th><th>Státusz</th><th></th></tr></thead><tbody>{transfers.map(t=><tr key={t.id}><td>{t.destination_name}</td><td><b>{t.product_name}</b></td><td>{q(t.quantity)}</td><td>{t.status}</td><td>{t.status==='prepared'?<button onClick={()=>dispatch(t)}>Kiküldés</button>:t.status==='dispatched'?<button onClick={()=>receive(t)}>Érkeztetés</button>:null}</td></tr>)}{!transfers.length&&<tr><td colSpan={5} className="proc-empty">Nincs központi átadás.</td></tr>}</tbody></table></div>
 {discrepancies.length>0&&<><h3 style={{marginTop:24}}>Érkeztetési eltérések</h3><div className="proc-table"><table><thead><tr><th>Szalon</th><th>Termék</th><th>Elküldve</th><th>Átvéve</th><th>Hiány</th></tr></thead><tbody>{discrepancies.map(d=><tr key={d.id}><td>{d.destination_name}</td><td>{d.product_name}</td><td>{q(d.expected_quantity)}</td><td>{q(d.received_quantity)}</td><td><b>{q(d.shortage_quantity)}</b></td></tr>)}</tbody></table></div></>}
 </section>}
