import React,{useEffect,useMemo,useState}from"react";
import api from"../../api";

type Row={id:string|number;warehouse_id:string|number;warehouse_name:string;product_name:string;internal_code?:string|null;brand?:string|null;quantity:number|string;min_quantity:number|string;optimal_quantity:number|string};
type Props={locationId:string;refreshKey?:number;onChanged?:()=>void};
const arr=<T,>(v:any):T[]=>Array.isArray(v)?v:Array.isArray(v?.items)?v.items:[];
const q=(v:unknown)=>Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:3});

export default function InventoryStockLevelSettings({locationId,refreshKey=0,onChanged}:Props){
 const[rows,setRows]=useState<Row[]>([]);const[search,setSearch]=useState("");const[warehouse,setWarehouse]=useState("");const[edit,setEdit]=useState<string|number|null>(null);const[form,setForm]=useState({min_quantity:"",optimal_quantity:""});const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 async function load(){try{const r=await api.get(`/api/transactions/inventory/ops/balances?location_id=${encodeURIComponent(locationId)}`);setRows(arr<Row>(r.data))}catch(e:any){setError(e?.response?.data?.message||"A készletszintek nem tölthetők be.")}}
 useEffect(()=>{void load()},[locationId,refreshKey]); // eslint-disable-line react-hooks/exhaustive-deps
 const warehouses=useMemo(()=>Array.from(new Map(rows.map(r=>[String(r.warehouse_id),r.warehouse_name])).entries()),[rows]);
 const filtered=useMemo(()=>{const s=search.trim().toLowerCase();return rows.filter(r=>(!warehouse||String(r.warehouse_id)===warehouse)&&(!s||`${r.product_name} ${r.internal_code||""} ${r.brand||""}`.toLowerCase().includes(s)))},[rows,search,warehouse]);
 function start(r:Row){setEdit(r.id);setForm({min_quantity:String(r.min_quantity??0),optimal_quantity:String(r.optimal_quantity??0)});setError("")}
 async function save(r:Row){const min=Number(form.min_quantity),opt=Number(form.optimal_quantity);if(!Number.isFinite(min)||min<0||!Number.isFinite(opt)||opt<0)return setError("A készletszintek nem lehetnek negatívak.");if(opt>0&&opt<min)return setError("Az optimális készletszint nem lehet kisebb a kritikusnál.");setSaving(true);setError("");try{await api.patch(`/api/transactions/inventory/ops/balances/${r.id}/settings`,{min_quantity:min,optimal_quantity:opt});setEdit(null);await load();onChanged?.()}catch(e:any){setError(e?.response?.data?.message||"A készletszintek mentése nem sikerült.")}finally{setSaving(false)}}
 return <section className="invops-card"><header><div><h2>Kritikus és optimális készletszintek</h2><p>Raktárankénti minimum és kívánt feltöltési szint az automatikus utánrendeléshez.</p></div></header><div className="invops-report-filters"><input placeholder="Termék keresése" value={search} onChange={e=>setSearch(e.target.value)}/><select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Összes raktár</option>{warehouses.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div>{error&&<div className="invops-alert error" style={{margin:12}}>{error}</div>}<div className="invops-table-wrap"><table className="invops-table"><thead><tr><th>Raktár</th><th>Termék</th><th>Aktuális</th><th>Kritikus minimum</th><th>Optimális szint</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.warehouse_name}</td><td><b>{r.product_name}</b><small>{[r.brand,r.internal_code].filter(Boolean).join(" · ")}</small></td><td>{q(r.quantity)}</td><td>{edit===r.id?<input className="invops-count-input" type="number" step="0.001" min="0" value={form.min_quantity} onChange={e=>setForm(x=>({...x,min_quantity:e.target.value}))}/>:q(r.min_quantity)}</td><td>{edit===r.id?<input className="invops-count-input" type="number" step="0.001" min="0" value={form.optimal_quantity} onChange={e=>setForm(x=>({...x,optimal_quantity:e.target.value}))}/>:q(r.optimal_quantity)}</td><td>{edit===r.id?<div className="invops-actions"><button disabled={saving} className="invops-button primary" onClick={()=>save(r)}>Mentés</button><button className="invops-button" onClick={()=>setEdit(null)}>Mégse</button></div>:<button className="invops-button" onClick={()=>start(r)}>Szerkesztés</button>}</td></tr>)}{!filtered.length&&<tr><td className="invops-empty" colSpan={6}>Nincs megjeleníthető készletegyenleg.</td></tr>}</tbody></table></div></section>
}
