import React,{useEffect,useMemo,useState}from"react";
import api from"../../api";
import{useLanguage}from"../../i18n/LanguageProvider";

type Row={id:string|number;warehouse_id:string|number;warehouse_name:string;product_name:string;internal_code?:string|null;brand?:string|null;quantity:number|string;min_quantity:number|string;max_quantity?:number|string;optimal_quantity:number|string};
type Props={locationId:string;refreshKey?:number;onChanged?:()=>void};
const arr=<T,>(v:any):T[]=>Array.isArray(v)?v:Array.isArray(v?.items)?v.items:[];
const q=(v:unknown,locale="hu-HU")=>Number(v||0).toLocaleString(locale,{maximumFractionDigits:3});

export default function InventoryStockLevelSettings({locationId,refreshKey=0,onChanged}:Props){
 const{language,locale}=useLanguage();
 const L=(hu:string,en:string)=>language==="en"?en:hu;
 const[rows,setRows]=useState<Row[]>([]);const[search,setSearch]=useState("");const[warehouse,setWarehouse]=useState("");const[edit,setEdit]=useState<string|number|null>(null);const[form,setForm]=useState({min_quantity:"",max_quantity:""});const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 async function load(){try{const r=await api.get(`/api/transactions/inventory/ops/balances?location_id=${encodeURIComponent(locationId)}`);setRows(arr<Row>(r.data))}catch(e:any){setError(e?.response?.data?.message||L("A készletszintek nem tölthetők be.","Stock levels could not be loaded."))}}
 useEffect(()=>{void load()},[locationId,refreshKey]); // eslint-disable-line react-hooks/exhaustive-deps
 const warehouses=useMemo(()=>Array.from(new Map(rows.map(r=>[String(r.warehouse_id),r.warehouse_name])).entries()),[rows]);
 const filtered=useMemo(()=>{const s=search.trim().toLowerCase();return rows.filter(r=>(!warehouse||String(r.warehouse_id)===warehouse)&&(!s||`${r.product_name} ${r.internal_code||""} ${r.brand||""}`.toLowerCase().includes(s)))},[rows,search,warehouse]);
 const rowMax=(r:Row)=>r.max_quantity??r.optimal_quantity??0;
 function start(r:Row){setEdit(r.id);setForm({min_quantity:String(r.min_quantity??0),max_quantity:String(rowMax(r))});setError("")}
 async function save(r:Row){const min=Number(form.min_quantity),max=Number(form.max_quantity);if(!Number.isFinite(min)||min<0||!Number.isFinite(max)||max<0)return setError(L("A készletszintek nem lehetnek negatívak.","Stock levels cannot be negative."));if(max>0&&max<min)return setError(L("A maximum készletszint nem lehet kisebb a minimumnál.","Maximum stock cannot be below minimum stock."));setSaving(true);setError("");try{await api.patch(`/api/transactions/inventory/ops/balances/${r.id}/settings`,{min_quantity:min,max_quantity:max,optimal_quantity:max});setEdit(null);await load();onChanged?.()}catch(e:any){setError(e?.response?.data?.message||L("A készletszintek mentése nem sikerült.","Stock levels could not be saved."))}finally{setSaving(false)}}
 return <section className="invops-card"><header><div><h2>{L("Minimum és maximum készletszintek","Minimum and maximum stock levels")}</h2><p>{L("Raktárankénti minimum és maximum feltöltési szint az automatikus min/max utánrendeléshez.","Warehouse-level minimum and maximum targets for automatic min/max replenishment.")}</p></div></header><div className="invops-report-filters"><input placeholder={L("Termék keresése","Search product")} value={search} onChange={e=>setSearch(e.target.value)}/><select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">{L("Összes raktár","All warehouses")}</option>{warehouses.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div>{error&&<div className="invops-alert error" style={{margin:12}}>{error}</div>}<div className="invops-table-wrap"><table className="invops-table"><thead><tr><th>{L("Raktár","Warehouse")}</th><th>{L("Termék","Product")}</th><th>{L("Aktuális","Current")}</th><th>{L("Minimum","Minimum")}</th><th>{L("Maximum","Maximum")}</th><th>{L("Művelet","Action")}</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.warehouse_name}</td><td><b>{r.product_name}</b><small>{[r.brand,r.internal_code].filter(Boolean).join(" · ")}</small></td><td>{q(r.quantity,locale)}</td><td>{edit===r.id?<input className="invops-count-input" type="number" step="0.001" min="0" value={form.min_quantity} onChange={e=>setForm(x=>({...x,min_quantity:e.target.value}))}/>:q(r.min_quantity,locale)}</td><td>{edit===r.id?<input className="invops-count-input" type="number" step="0.001" min="0" value={form.max_quantity} onChange={e=>setForm(x=>({...x,max_quantity:e.target.value}))}/>:q(rowMax(r),locale)}</td><td>{edit===r.id?<div className="invops-actions"><button disabled={saving} className="invops-button primary" onClick={()=>save(r)}>{L("Mentés","Save")}</button><button className="invops-button" onClick={()=>setEdit(null)}>{L("Mégse","Cancel")}</button></div>:<button className="invops-button" onClick={()=>start(r)}>{L("Szerkesztés","Edit")}</button>}</td></tr>)}{!filtered.length&&<tr><td className="invops-empty" colSpan={6}>{L("Nincs megjeleníthető készletegyenleg.","No stock balance to display.")}</td></tr>}</tbody></table></div></section>
}
