import React, { useEffect, useMemo, useState } from "react";
import api from "../../api";
import { useCapabilities } from "../../hooks/useCapabilities";
import SupplierIntelligencePanel from "./SupplierIntelligencePanel";
import "./ProcurementPanel.css";

type Suggestion = {balance_id:string|number;product_id:string;product_name:string;internal_code?:string|null;brand?:string|null;location_id?:string|null;current_quantity:number|string;min_quantity:number|string;unit_cost:number|string;suggested_quantity:number|string;expected_cost:number|string;supplier_id?:number|null;supplier_name?:string|null;minimum_order_quantity?:number|string|null;lead_time_days?:number|null;preferred?:boolean};
type Order = {id:string|number;location_id?:string|null;supplier_id?:number|null;supplier_name:string;supplier_display_name?:string;status:string;expected_at?:string|null;note?:string|null;expected_total:number|string;received_total:number|string;item_count:number|string;created_at:string;approval_status?:string;approval_requested_by?:string|null;approved_by?:string|null;rejection_reason?:string|null;document_number?:string|null};
type OrderItem={id:string|number;product_name:string;ordered_quantity:number|string;received_quantity:number|string;unit_cost:number|string;actual_unit_cost?:number|string|null};
type OrderDetail=Order&{items:OrderItem[]};
type Props={locationId:string;section?:string;onInventoryChanged?:()=>void};
const statusLabels:Record<string,string>={draft:"Piszkozat",ordered:"Megrendelve",partially_received:"Részben beérkezett",received:"Beérkezett",cancelled:"Visszavonva"};
const approvalLabels:Record<string,string>={not_requested:"Nincs bekérve",pending:"Jóváhagyásra vár",approved:"Jóváhagyva",auto_approved:"Automatikusan jóváhagyva",rejected:"Elutasítva"};
const huf=(v:unknown)=>`${Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:0})} Ft`;
const qty=(v:unknown)=>Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:3});
const arr=<T,>(v:any):T[]=>Array.isArray(v)?v:Array.isArray(v?.items)?v.items:[];

export default function ProcurementPanel({locationId,section="dashboard",onInventoryChanged}:Props){
 const caps=useCapabilities();
 const canSuggestions=caps.menu("procurement.suggestions","can_view");
 const canOrdersView=caps.menu("procurement.orders","can_view");
 const canOrdersCreate=caps.menu("procurement.orders","can_create");
 const canOrdersEdit=caps.menu("procurement.orders","can_edit");
 const canExport=caps.menu("procurement.orders","can_export");
 const[suggestions,setSuggestions]=useState<Suggestion[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[detail,setDetail]=useState<OrderDetail|null>(null);
 const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
 const[supplier,setSupplier]=useState("");const[selected,setSelected]=useState<Record<string,boolean>>({});const[expectedAt,setExpectedAt]=useState("");
 const[receive,setReceive]=useState<Record<string,string>>({});const[receiveCost,setReceiveCost]=useState<Record<string,string>>({});
 const query=locationId?`?location_id=${encodeURIComponent(locationId)}`:"";
 async function load(){setLoading(true);setError("");try{const jobs:Promise<any>[]=[];const keys:string[]=[];if(canSuggestions){jobs.push(api.get(`/api/transactions/procurement/suggestions${query}`));keys.push("s")};if(canOrdersView){jobs.push(api.get(`/api/transactions/procurement/orders${query}`));keys.push("o")};const result=await Promise.all(jobs);result.forEach((r,i)=>keys[i]==="s"?setSuggestions(arr<Suggestion>(r.data)):setOrders(arr<Order>(r.data)))}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A beszerzési adatok betöltése nem sikerült.")}finally{setLoading(false)}}
 useEffect(()=>{if(!caps.loading)void load()},[locationId,caps.loading]); // eslint-disable-line react-hooks/exhaustive-deps
 const selectedSuggestions=useMemo(()=>suggestions.filter(s=>selected[String(s.balance_id)]),[suggestions,selected]);
 const selectedCost=useMemo(()=>selectedSuggestions.reduce((a,s)=>a+Number(s.expected_cost||0),0),[selectedSuggestions]);
 async function createOrder(){if(!canOrdersCreate)return;setError("");setSuccess("");if(!supplier.trim())return setError("Add meg a beszállítót.");if(!selectedSuggestions.length)return setError("Válassz legalább egy utánrendelési javaslatot.");try{await api.post("/api/transactions/procurement/orders",{location_id:locationId||null,supplier_name:supplier.trim(),expected_at:expectedAt||null,note:"Manuálisan összeállított utánrendelési javaslatokból",items:selectedSuggestions.map(s=>({product_id:s.product_id,ordered_quantity:Number(s.suggested_quantity),unit_cost:Number(s.unit_cost)}))});setSuccess("A beszerzési rendelés elkészült. Küldd jóváhagyásra a rendelés részleteinél.");setSelected({});setSupplier("");setExpectedAt("");await load()}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A rendelés létrehozása nem sikerült.")}}
 async function status(id:string|number,newStatus:string){if(!canOrdersEdit)return;try{await api.patch(`/api/transactions/procurement/orders/${id}/status`,{status:newStatus});await load();if(detail?.id===id)await open(id)}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A státusz módosítása nem sikerült.")}}
 async function open(id:string|number){if(!canOrdersView)return;try{const r=await api.get(`/api/transactions/procurement/orders/${id}`);setDetail(r.data);const q:Record<string,string>={};const c:Record<string,string>={};(r.data.items||[]).forEach((x:OrderItem)=>{q[String(x.id)]=String(Math.max(0,Number(x.ordered_quantity)-Number(x.received_quantity)));c[String(x.id)]=String(x.actual_unit_cost??x.unit_cost??0)});setReceive(q);setReceiveCost(c)}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A rendelés nem tölthető be.")}}
 async function requestApproval(){if(!detail||!canOrdersEdit)return;try{const r=await api.post(`/api/transactions/procurement-workflow/orders/${detail.id}/request-approval`,{});setSuccess(r.data?.approval_status==="auto_approved"?"A rendelés értékhatár alatt van, automatikusan jóváhagyva.":"A rendelés vezetői jóváhagyásra elküldve.");await open(detail.id);await load()}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A jóváhagyási kérés nem sikerült.")}}
 async function pdf(){if(!detail||!canExport)return;try{const r=await api.get(`/api/transactions/procurement-workflow/orders/${detail.id}/document.pdf`,{responseType:"blob"});const url=URL.createObjectURL(r.data);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A PDF bizonylat nem készíthető el.")}}
 async function receiveOrder(){if(!detail||!canOrdersEdit)return;const items=detail.items.map(i=>({item_id:i.id,received_quantity:Number(receive[String(i.id)]||0),unit_cost:Number(receiveCost[String(i.id)]||i.unit_cost||0)})).filter(x=>x.received_quantity>0);if(!items.length)return setError("Adj meg legalább egy pozitív bevételezendő mennyiséget.");try{await api.post(`/api/transactions/procurement/orders/${detail.id}/receive`,{items});setSuccess("A bevételezés megtörtént, a készlet és a beszállítói utolsó ár frissült.");await open(detail.id);await load();onInventoryChanged?.()}catch(e:any){setError(e?.response?.data?.error||e?.response?.data?.message||"A bevételezés nem sikerült.")}}
 const showDashboard=section==="dashboard";const showSuggestions=section==="suggestions";const showOrders=section==="orders";const showSupplierModule=["dashboard","suggestions","suppliers","prices"].includes(section);const showOwnContent=showDashboard||showSuggestions||showOrders;
 if(caps.loading)return <div className="procurement"><div className="proc-empty">Jogosultságok betöltése…</div></div>;
 return <div className="procurement">
  {showSupplierModule&&<SupplierIntelligencePanel section={section} locationId={locationId} onChanged={()=>{void load();onInventoryChanged?.()}}/>}
  {showOwnContent&&error&&<div className="proc-alert error">{error}</div>}{showOwnContent&&success&&<div className="proc-alert success">{success}</div>}
  {showDashboard&&<div className="proc-kpis"><div><strong>{canSuggestions?suggestions.length:0}</strong><span>Utánrendelendő termék</span></div><div><strong>{canOrdersView?orders.filter(o=>!["received","cancelled"].includes(o.status)).length:0}</strong><span>Nyitott rendelés</span></div><div><strong>{canSuggestions?huf(suggestions.reduce((a,s)=>a+Number(s.expected_cost||0),0)):"—"}</strong><span>Javasolt beszerzési érték</span></div><div><strong>{canOrdersView?orders.filter(o=>o.approval_status==="pending").length:0}</strong><span>Jóváhagyásra vár</span></div></div>}
  {(showDashboard||showSuggestions)&&canSuggestions&&<section className="proc-card"><header><div><span>UTÁNRENDELÉS</span><h2>Beszerzési javaslatok</h2><p>Minimum készlet, preferált beszállító, MOQ, ár és lead time alapján.</p></div><button onClick={load}>Frissítés</button></header>{canOrdersCreate&&<div className="proc-orderbar"><input placeholder="Beszállító neve (kézi rendeléshez)" value={supplier} onChange={e=>setSupplier(e.target.value)}/><input type="date" value={expectedAt} onChange={e=>setExpectedAt(e.target.value)}/><strong>{selectedSuggestions.length} tétel · {huf(selectedCost)}</strong><button onClick={createOrder}>Kézi rendelés</button></div>}<div className="proc-table"><table><thead><tr><th></th><th>Termék</th><th>Beszállító</th><th>Készlet</th><th>Minimum</th><th>MOQ</th><th>Javasolt</th><th>Egységár</th><th>Lead time</th><th>Költség</th></tr></thead><tbody>{suggestions.map(s=><tr key={String(s.balance_id)}><td>{canOrdersCreate&&<input type="checkbox" checked={!!selected[String(s.balance_id)]} onChange={e=>setSelected(x=>({...x,[String(s.balance_id)]:e.target.checked}))}/>}</td><td><b>{s.product_name}</b><small>{[s.brand,s.internal_code].filter(Boolean).join(" · ")}</small></td><td>{s.supplier_name||"—"}{s.preferred&&<small>Preferált</small>}</td><td>{qty(s.current_quantity)}</td><td>{qty(s.min_quantity)}</td><td>{s.minimum_order_quantity?qty(s.minimum_order_quantity):"—"}</td><td><b>{qty(s.suggested_quantity)}</b></td><td>{huf(s.unit_cost)}</td><td>{s.lead_time_days==null?"—":`${s.lead_time_days} nap`}</td><td><b>{huf(s.expected_cost)}</b></td></tr>)}{!loading&&!suggestions.length&&<tr><td colSpan={10} className="proc-empty">Nincs minimum alatti készlet.</td></tr>}</tbody></table></div></section>}
  {(showDashboard||showOrders)&&canOrdersView&&<section className="proc-card"><header><div><span>BESZERZÉSI FOLYAMAT</span><h2>Beszerzési rendelések</h2><p>Piszkozat → jóváhagyás → megrendelve → részben/teljesen beérkezett.</p></div><button onClick={load}>Frissítés</button></header><div className="proc-table"><table><thead><tr><th>#</th><th>Beszállító</th><th>Státusz</th><th>Jóváhagyás</th><th>Tétel</th><th>Várható érték</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={String(o.id)}><td>#{o.id}</td><td><b>{o.supplier_display_name||o.supplier_name}</b></td><td><span className={`proc-status ${o.status}`}>{statusLabels[o.status]||o.status}</span></td><td>{approvalLabels[o.approval_status||"not_requested"]||o.approval_status||"—"}</td><td>{o.item_count}</td><td>{huf(o.expected_total)}</td><td><button onClick={()=>open(o.id)}>Megnyitás</button></td></tr>)}{!loading&&!orders.length&&<tr><td colSpan={7} className="proc-empty">Még nincs beszerzési rendelés.</td></tr>}</tbody></table></div></section>}
  {detail&&<div className="proc-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setDetail(null)}}><div className="proc-modal"><header><div><span>BESZERZÉSI RENDELÉS #{detail.id}</span><h2>{detail.supplier_display_name||detail.supplier_name}</h2><p>{statusLabels[detail.status]||detail.status} · {approvalLabels[detail.approval_status||"not_requested"]||detail.approval_status}</p>{detail.rejection_reason&&<p>Elutasítás oka: {detail.rejection_reason}</p>}</div><button onClick={()=>setDetail(null)}>×</button></header><div className="proc-detail-actions">{canOrdersEdit&&detail.status==="draft"&&["not_requested","rejected",undefined].includes(detail.approval_status as any)&&<button onClick={requestApproval}>Jóváhagyás kérése</button>}{canOrdersEdit&&detail.status==="draft"&&["approved","auto_approved"].includes(detail.approval_status||"")&&<button onClick={()=>status(detail.id,"ordered")}>Rendelésre küldés</button>}{canExport&&<button className="secondary" onClick={pdf}>PDF bizonylat</button>}{canOrdersEdit&&!["received","cancelled"].includes(detail.status)&&<button className="danger" onClick={()=>status(detail.id,"cancelled")}>Visszavonás</button>}</div><div className="proc-table"><table><thead><tr><th>Termék</th><th>Rendelt</th><th>Beérkezett</th><th>Most bevételez</th><th>Tényleges egységár</th></tr></thead><tbody>{detail.items.map(i=>{const remain=Math.max(0,Number(i.ordered_quantity)-Number(i.received_quantity));const canReceive=canOrdersEdit&&["ordered","partially_received"].includes(detail.status);return <tr key={String(i.id)}><td><b>{i.product_name}</b></td><td>{qty(i.ordered_quantity)}</td><td>{qty(i.received_quantity)}</td><td><input type="number" step="0.001" min="0" max={remain} disabled={!canReceive||remain<=0} value={receive[String(i.id)]||""} onChange={e=>setReceive(x=>({...x,[String(i.id)]:e.target.value}))}/></td><td><input type="number" step="1" min="0" disabled={!canReceive||remain<=0} value={receiveCost[String(i.id)]||""} onChange={e=>setReceiveCost(x=>({...x,[String(i.id)]:e.target.value}))}/></td></tr>})}</tbody></table></div>{canOrdersEdit&&["ordered","partially_received"].includes(detail.status)&&<footer><button onClick={receiveOrder}>Bevételezés és készletfrissítés</button></footer>}</div></div>}
 </div>
}
