import React, { useEffect, useMemo, useState } from "react";
import api from "../../api";
import "./SupplierIntelligencePanel.css";

type Supplier={id:number;name:string;email?:string|null;phone?:string|null;contact_name?:string|null;payment_terms_days:number;default_lead_time_days:number;active:boolean;product_count:number;open_order_count:number};
type Product={id:string;name:string;internal_code?:string|null;brand?:string|null};
type Term={id:number;product_id:string;product_name:string;internal_code?:string|null;brand?:string|null;supplier_product_code?:string|null;unit_price:number|string;minimum_order_quantity:number|string;lead_time_days:number;preferred:boolean;active:boolean;last_purchase_price:number|string;average_purchase_price:number|string;last_received_at?:string|null};
type GroupItem={balance_id:string|number;product_id:string;product_name:string;current_quantity:number|string;min_quantity:number|string;supplier_id?:number|null;supplier_name?:string|null;supplier_price?:number|string|null;minimum_order_quantity?:number|string|null;lead_time_days?:number|null;preferred?:boolean;suggested_quantity:number|string;expected_cost:number|string};
type Group={supplier_id?:number|null;supplier_name:string;total_expected_cost:number;items:GroupItem[]};
type Props={locationId:string;section?:string;onChanged?:()=>void};
const huf=(v:unknown)=>`${Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:0})} Ft`;
const q=(v:unknown)=>Number(v||0).toLocaleString("hu-HU",{maximumFractionDigits:3});
const rows=<T,>(v:any):T[]=>Array.isArray(v)?v:Array.isArray(v?.items)?v.items:[];

export default function SupplierIntelligencePanel({locationId,section="dashboard",onChanged}:Props){
 const[suppliers,setSuppliers]=useState<Supplier[]>([]),[products,setProducts]=useState<Product[]>([]),[terms,setTerms]=useState<Term[]>([]),[groups,setGroups]=useState<Group[]>([]);
 const[selectedSupplier,setSelectedSupplier]=useState<number|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const[supplierForm,setSupplierForm]=useState({name:"",contact_name:"",email:"",phone:"",payment_terms_days:"0",default_lead_time_days:"3"});
 const[termForm,setTermForm]=useState({product_id:"",supplier_product_code:"",unit_price:"",minimum_order_quantity:"1",lead_time_days:"3",preferred:false});
 const[expectedAt,setExpectedAt]=useState("");
 const activeSupplier=useMemo(()=>suppliers.find(s=>s.id===selectedSupplier)||null,[suppliers,selectedSupplier]);

 async function load(){setLoading(true);setError("");try{const qs=locationId?`?location_id=${encodeURIComponent(locationId)}`:"";const[s,p,g]=await Promise.all([api.get("/api/transactions/suppliers"),api.get("/api/products?include_inactive=1"),api.get(`/api/transactions/suppliers/intelligence/grouped-suggestions${qs}`)]);setSuppliers(rows<Supplier>(s.data));setProducts(rows<Product>(p.data));setGroups(rows<Group>(g.data));}catch(e:any){setError(e?.response?.data?.message||"A beszállítói adatok nem tölthetők be.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[locationId]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!selectedSupplier){setTerms([]);return;}api.get(`/api/transactions/suppliers/${selectedSupplier}/products`).then(r=>setTerms(rows<Term>(r.data))).catch((e:any)=>setError(e?.response?.data?.message||"A beszállítói termékek nem tölthetők be."))},[selectedSupplier]);
 async function createSupplier(){if(!supplierForm.name.trim())return setError("Add meg a beszállító nevét.");try{const r=await api.post("/api/transactions/suppliers",{...supplierForm,payment_terms_days:Number(supplierForm.payment_terms_days),default_lead_time_days:Number(supplierForm.default_lead_time_days)});setSuccess("A beszállító létrejött.");setSupplierForm({name:"",contact_name:"",email:"",phone:"",payment_terms_days:"0",default_lead_time_days:"3"});await load();setSelectedSupplier(Number(r.data.id))}catch(e:any){setError(e?.response?.data?.message||"A beszállító mentése nem sikerült.")}}
 async function saveTerm(){if(!selectedSupplier||!termForm.product_id)return setError("Válassz beszállítót és terméket.");try{await api.put(`/api/transactions/suppliers/${selectedSupplier}/products/${termForm.product_id}`,{...termForm,unit_price:Number(termForm.unit_price||0),minimum_order_quantity:Number(termForm.minimum_order_quantity||1),lead_time_days:Number(termForm.lead_time_days||0),active:true});setSuccess("A beszállítói kondíciók frissültek.");const r=await api.get(`/api/transactions/suppliers/${selectedSupplier}/products`);setTerms(rows<Term>(r.data));setTermForm({product_id:"",supplier_product_code:"",unit_price:"",minimum_order_quantity:"1",lead_time_days:activeSupplier?.default_lead_time_days?String(activeSupplier.default_lead_time_days):"3",preferred:false});await load()}catch(e:any){setError(e?.response?.data?.message||"A beszállítói kondíció mentése nem sikerült.")}}
 async function createGroupedOrder(group:Group){if(!group.supplier_id)return setError("A csoporthoz előbb rendelj beszállítót a termékekhez.");try{await api.post("/api/transactions/procurement/orders",{location_id:locationId||null,supplier_id:group.supplier_id,expected_at:expectedAt||null,note:"Beszállítói intelligencia alapján automatikusan csoportosítva",items:group.items.map(i=>({product_id:i.product_id,ordered_quantity:Number(i.suggested_quantity),unit_cost:Number(i.supplier_price||0)}))});setSuccess(`${group.supplier_name}: beszerzési rendelés létrejött.`);await load();onChanged?.()}catch(e:any){setError(e?.response?.data?.message||"A csoportos rendelés nem hozható létre.")}}

 const showSuppliers=section==="suppliers";
 const showPrices=section==="prices";
 const showGroups=section==="dashboard"||section==="suggestions";
 if(!showSuppliers&&!showPrices&&!showGroups)return null;

 return <section className="supplier-intel">
  <header><div><span>BESZERZÉSI INTELLIGENCIA</span><h2>{showSuppliers?"Beszállítói törzs":showPrices?"Beszállítói árak és kondíciók":"Automatikus beszállítói csoportosítás"}</h2><p>{showSuppliers?"Kapcsolattartók, fizetési és szállítási alapadatok egy helyen.":showPrices?"Termékenkénti ár, MOQ, lead time, utolsó és átlagos beszerzési ár.":"A rendszer preferált beszállító, ár, MOQ és szállítási idő alapján csoportosít."}</p></div><button onClick={load}>Frissítés</button></header>
  {error&&<div className="supplier-alert error">{error}</div>}{success&&<div className="supplier-alert success">{success}</div>}

  {showSuppliers&&<div className="supplier-layout">
   <div className="supplier-card"><h3>Új beszállító</h3><div className="supplier-form"><input placeholder="Beszállító neve *" value={supplierForm.name} onChange={e=>setSupplierForm({...supplierForm,name:e.target.value})}/><input placeholder="Kapcsolattartó" value={supplierForm.contact_name} onChange={e=>setSupplierForm({...supplierForm,contact_name:e.target.value})}/><input placeholder="E-mail" value={supplierForm.email} onChange={e=>setSupplierForm({...supplierForm,email:e.target.value})}/><input placeholder="Telefon" value={supplierForm.phone} onChange={e=>setSupplierForm({...supplierForm,phone:e.target.value})}/><label>Fizetési határidő (nap)<input type="number" min="0" value={supplierForm.payment_terms_days} onChange={e=>setSupplierForm({...supplierForm,payment_terms_days:e.target.value})}/></label><label>Alap szállítási idő (nap)<input type="number" min="0" value={supplierForm.default_lead_time_days} onChange={e=>setSupplierForm({...supplierForm,default_lead_time_days:e.target.value})}/></label><button onClick={createSupplier}>Beszállító létrehozása</button></div></div>
   <div className="supplier-card supplier-list"><h3>Beszállítók</h3>{suppliers.map(s=><button key={s.id} className={selectedSupplier===s.id?"active":""} onClick={()=>{setSelectedSupplier(s.id);setTermForm(x=>({...x,lead_time_days:String(s.default_lead_time_days)}))}}><b>{s.name}</b><small>{s.product_count} termék · {s.open_order_count} nyitott rendelés · {s.default_lead_time_days} nap</small></button>)}{!loading&&!suppliers.length&&<p>Nincs még beszállító.</p>}</div>
  </div>}

  {showPrices&&<>
   <div className="supplier-card supplier-list"><h3>Beszállító kiválasztása</h3>{suppliers.map(s=><button key={s.id} className={selectedSupplier===s.id?"active":""} onClick={()=>{setSelectedSupplier(s.id);setTermForm(x=>({...x,lead_time_days:String(s.default_lead_time_days)}))}}><b>{s.name}</b><small>{s.product_count} termék · {s.default_lead_time_days} nap</small></button>)}</div>
   {activeSupplier&&<div className="supplier-card"><div className="supplier-title"><div><span>TERMÉK–BESZÁLLÍTÓ KAPCSOLAT</span><h3>{activeSupplier.name}</h3></div></div><div className="supplier-term-form"><select value={termForm.product_id} onChange={e=>setTermForm({...termForm,product_id:e.target.value})}><option value="">Termék kiválasztása…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input placeholder="Beszállítói cikkszám" value={termForm.supplier_product_code} onChange={e=>setTermForm({...termForm,supplier_product_code:e.target.value})}/><label>Beszerzési ár<input type="number" min="0" value={termForm.unit_price} onChange={e=>setTermForm({...termForm,unit_price:e.target.value})}/></label><label>Minimum rendelés (MOQ)<input type="number" min="0.001" step="0.001" value={termForm.minimum_order_quantity} onChange={e=>setTermForm({...termForm,minimum_order_quantity:e.target.value})}/></label><label>Szállítási idő (nap)<input type="number" min="0" value={termForm.lead_time_days} onChange={e=>setTermForm({...termForm,lead_time_days:e.target.value})}/></label><label className="supplier-check"><input type="checkbox" checked={termForm.preferred} onChange={e=>setTermForm({...termForm,preferred:e.target.checked})}/> Preferált / alapértelmezett</label><button onClick={saveTerm}>Kondíció mentése</button></div><div className="supplier-table"><table><thead><tr><th>Termék</th><th>Aktuális ár</th><th>Utolsó ár</th><th>Átlagár</th><th>MOQ</th><th>Lead time</th><th>Preferált</th></tr></thead><tbody>{terms.map(t=><tr key={t.id}><td><b>{t.product_name}</b><small>{[t.brand,t.internal_code,t.supplier_product_code].filter(Boolean).join(" · ")}</small></td><td>{huf(t.unit_price)}</td><td>{huf(t.last_purchase_price)}</td><td>{huf(t.average_purchase_price)}</td><td>{q(t.minimum_order_quantity)}</td><td>{t.lead_time_days} nap</td><td>{t.preferred?<span className="preferred">Igen</span>:"—"}</td></tr>)}{!terms.length&&<tr><td colSpan={7}>Ehhez a beszállítóhoz még nincs termék-kondíció.</td></tr>}</tbody></table></div></div>}
  </>}

  {showGroups&&<div className="supplier-card"><div className="supplier-title"><div><span>AUTOMATIKUS CSOPORTOSÍTÁS</span><h3>Utánrendelés beszállítónként</h3><p>A rendszer először a preferált beszállítót választja, majd ár és szállítási idő alapján rangsorol.</p></div><label>Várható érkezés<input type="date" value={expectedAt} onChange={e=>setExpectedAt(e.target.value)}/></label></div><div className="supplier-groups">{groups.map(g=><article key={String(g.supplier_id||"none")} className={!g.supplier_id?"unassigned":""}><header><div><b>{g.supplier_name}</b><small>{g.items.length} tétel · {huf(g.total_expected_cost)}</small></div>{g.supplier_id&&<button onClick={()=>createGroupedOrder(g)}>Rendelés létrehozása</button>}</header><div className="supplier-table"><table><thead><tr><th>Termék</th><th>Készlet / min.</th><th>MOQ</th><th>Javasolt</th><th>Ár</th><th>Lead time</th><th>Költség</th></tr></thead><tbody>{g.items.map(i=><tr key={String(i.balance_id)}><td><b>{i.product_name}</b></td><td>{q(i.current_quantity)} / {q(i.min_quantity)}</td><td>{i.minimum_order_quantity?q(i.minimum_order_quantity):"—"}</td><td><b>{q(i.suggested_quantity)}</b></td><td>{huf(i.supplier_price)}</td><td>{i.lead_time_days==null?"—":`${i.lead_time_days} nap`}</td><td><b>{huf(i.expected_cost)}</b></td></tr>)}</tbody></table></div></article>)}{!loading&&!groups.length&&<div className="supplier-empty">Jelenleg nincs utánrendelési igény.</div>}</div></div>}
 </section>
}
