import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,History,Plus,RefreshCw,Tag,UserPlus,X}from'lucide-react';
import withBase from'../../utils/apiBase';

type ClientLite={id:string;name:string;phone?:string|null;email?:string|null};
type Detail={client:any;appointments:any[];notes:any[];tags:Array<{id:string;name:string;color?:string}>;forms:any[]};
type Props={customerId?:string;locationId?:string;disabled?:boolean;onCustomerCreated?:(client:ClientLite)=>void};
class RequestError extends Error{status:number;constructor(message:string,status:number){super(message);this.status=status}}
const token=()=>localStorage.getItem('token')||localStorage.getItem('kleo_token')||'';
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch(withBase(path),{...options,credentials:'include',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new RequestError(p.detail?`${p.error||'Hiba'}: ${p.detail}`:p.error||`HTTP ${r.status}`,r.status);return p;}
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('hu-HU',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';

export default function WorkOrderGuestContextPanel({customerId,locationId,disabled,onCustomerCreated}:Props){
 const[detail,setDetail]=useState<Detail|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[profileUnavailable,setProfileUnavailable]=useState(false);const[newOpen,setNewOpen]=useState(false);const[saving,setSaving]=useState(false);const[form,setForm]=useState({name:'',phone:'',email:'',birth_date:'',city:'',address:''});
 async function load(){if(!customerId){setDetail(null);setError('');setProfileUnavailable(false);return}setLoading(true);setError('');setProfileUnavailable(false);try{setDetail(await request<Detail>(`clients/${encodeURIComponent(customerId)}`))}catch(e:any){setDetail(null);if(Number(e?.status)===404){setProfileUnavailable(true);setError('')}else setError(e?.message||'A vendég előzményei nem tölthetők be.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[customerId]);
 const recent=useMemo(()=>Array.isArray(detail?.appointments)?detail!.appointments.slice(0,6):[],[detail]);
 async function createGuest(e:React.FormEvent){e.preventDefault();if(!form.name.trim())return;setSaving(true);setError('');try{const created=await request<{id:string}>('clients',{method:'POST',body:JSON.stringify({...form,name:form.name.trim(),location_id:locationId||undefined,source:'workorder'})});const client={id:String(created.id),name:form.name.trim(),phone:form.phone||null,email:form.email||null};onCustomerCreated?.(client);setNewOpen(false);setForm({name:'',phone:'',email:'',birth_date:'',city:'',address:''})}catch(e:any){setError(e?.message||'Az új vendég létrehozása nem sikerült.')}finally{setSaving(false)}}
 return <section style={box}>
  <div style={head}><div><div style={title}><History size={19}/> Előzmények és vendégadatok</div><p style={muted}>Korábbi látogatások, vendégcímkék és a munkalaphoz kapcsolódó kedvezményi háttér.</p></div><div style={actions}><button type="button" style={secondary} disabled={disabled} onClick={()=>setNewOpen(true)}><UserPlus size={15}/> Új vendég</button>{customerId&&<button type="button" style={iconBtn} onClick={()=>void load()} disabled={loading} title="Frissítés"><RefreshCw size={16}/></button>}</div></div>
  {!customerId?<div style={empty}>Válassz törzsvendéget a fenti Vendég blokkban. Ezután itt automatikusan megjelennek az előzmények, címkék és a kapcsolódó hűséginformációk.</div>:loading?<div style={empty}>Vendégadatok betöltése…</div>:detail?<div style={grid}>
   <article style={card}><div style={cardTitle}>Vendégprofil</div><b style={{fontSize:17}}>{detail.client?.display_name||detail.client?.name||'—'}</b><span>{detail.client?.phone||'Nincs telefon'}</span><span>{detail.client?.email||'Nincs e-mail'}</span><span>Születési dátum: <b>{detail.client?.birth_date?new Date(detail.client.birth_date).toLocaleDateString('hu-HU'):'—'}</b></span></article>
   <article style={card}><div style={cardTitle}><Tag size={15}/> Címkék / vendégfokozat</div><div style={tags}>{(detail.tags||[]).map(t=><span key={t.id}>{t.name}</span>)}{!detail.tags?.length&&<small>Nincs címke vagy vendégfokozat.</small>}</div><small style={muted}>A wallet, pont, bérlet, kupon és utalvány a következő kedvezményblokkban ehhez a vendéghez kapcsolódik.</small></article>
   <article style={{...card,gridColumn:'1 / -1'}}><div style={cardTitle}><CalendarDays size={15}/> Korábbi időpontok és kezelések</div>{recent.length?<div style={history}>{recent.map((a:any)=><div key={a.id} style={historyRow}><span><b>{a.title||'Szalon időpont'}</b><small>{a.employee_name||'Nincs munkatárs'} · {a.location_name||''}</small></span><time>{fmt(a.start_time)}</time><em>{a.status||'—'}</em></div>)}</div>:<small style={muted}>Nincs korábbi időpont vagy kezelés.</small>}</article>
  </div>:profileUnavailable?<div style={legacyInfo}><b>Régi / szalonhoz nem rendelt vendégprofil</b><span>A foglalásból átvett név, telefon és e-mail a munkalapon megmarad, ezért a munkalap és a fizetés folytatható. A CRM-előzmények csak akkor jelennek meg, ha a vendégprofil ehhez a szalonhoz is hozzá van rendelve.</span></div>:null}
  {error&&<div style={bad}>{error}</div>}
  {newOpen&&<div style={backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setNewOpen(false)}}><form style={modal} onSubmit={createGuest}><header style={modalHead}><div><b>Új vendég felvétele</b><small>Az új vendég mentés után azonnal kiválasztható a munkalapon.</small></div><button type="button" style={iconBtn} onClick={()=>setNewOpen(false)} disabled={saving}><X size={18}/></button></header><div style={formGrid}><label style={field}>Teljes név *<input required style={input} value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label style={field}>Telefonszám<input style={input} value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/></label><label style={field}>E-mail<input type="email" style={input} value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/></label><label style={field}>Születési dátum<input type="date" style={input} value={form.birth_date} onChange={e=>setForm(v=>({...v,birth_date:e.target.value}))}/></label><label style={field}>Város<input style={input} value={form.city} onChange={e=>setForm(v=>({...v,city:e.target.value}))}/></label><label style={field}>Cím<input style={input} value={form.address} onChange={e=>setForm(v=>({...v,address:e.target.value}))}/></label></div><footer style={footer}><button type="button" style={secondary} onClick={()=>setNewOpen(false)} disabled={saving}>Mégse</button><button type="submit" style={primary} disabled={saving}><Plus size={15}/>{saving?'Mentés…':'Vendég létrehozása'}</button></footer></form></div>}
 </section>
}
const box:React.CSSProperties={background:'#fff',borderRadius:16,padding:18,boxShadow:'0 8px 24px rgba(48,36,25,.08)',marginBottom:16};const head:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12,flexWrap:'wrap'};const title:React.CSSProperties={display:'flex',alignItems:'center',gap:7,fontSize:18,fontWeight:900};const muted:React.CSSProperties={fontSize:12,color:'#74675d',margin:'4px 0'};const actions:React.CSSProperties={display:'flex',gap:8};const secondary:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:6,border:'1px solid #d8cec4',borderRadius:10,padding:'9px 12px',background:'#fff',fontWeight:800,cursor:'pointer'};const iconBtn:React.CSSProperties={display:'grid',placeItems:'center',width:38,height:38,border:'1px solid #d8cec4',borderRadius:10,background:'#fff',cursor:'pointer'};const empty:React.CSSProperties={marginTop:12,padding:14,border:'1px dashed #d8cec4',borderRadius:10,color:'#74675d',fontSize:13};const legacyInfo:React.CSSProperties={display:'grid',gap:5,marginTop:12,padding:14,border:'1px solid #ead7a6',borderRadius:10,background:'#fff8e6',color:'#74551d',fontSize:12};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:10,marginTop:12};const card:React.CSSProperties={display:'grid',gap:6,padding:13,border:'1px solid #eee4dc',borderRadius:12,background:'#fcfaf8'};const cardTitle:React.CSSProperties={display:'flex',alignItems:'center',gap:6,fontWeight:900,fontSize:13};const tags:React.CSSProperties={display:'flex',gap:6,flexWrap:'wrap'};const history:React.CSSProperties={display:'grid',gap:7};const historyRow:React.CSSProperties={display:'grid',gridTemplateColumns:'minmax(0,1fr) auto auto',gap:10,alignItems:'center',padding:'8px 0',borderBottom:'1px solid #eee4dc',fontSize:12};const bad:React.CSSProperties={marginTop:10,padding:10,borderRadius:9,background:'#fef3f2',color:'#b42318'};const backdrop:React.CSSProperties={position:'fixed',inset:0,zIndex:2600,display:'grid',placeItems:'center',padding:16,background:'rgba(25,20,16,.5)'};const modal:React.CSSProperties={width:'min(680px,96vw)',background:'#fff',borderRadius:16,padding:18,boxShadow:'0 26px 70px rgba(20,15,10,.3)'};const modalHead:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'};const formGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:12};const field:React.CSSProperties={display:'grid',gap:6,fontSize:12,fontWeight:800};const input:React.CSSProperties={height:40,border:'1px solid #d8cec4',borderRadius:9,padding:'0 10px',boxSizing:'border-box',width:'100%'};const footer:React.CSSProperties={display:'flex',justifyContent:'flex-end',gap:9,marginTop:14};const primary:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:6,border:0,borderRadius:10,padding:'10px 14px',background:'#2b2118',color:'#fff',fontWeight:900,cursor:'pointer'};
