import React,{useEffect,useMemo,useRef,useState}from'react';
import{BadgePercent,CheckCircle2,ClipboardCheck,CreditCard,PackageCheck,Scissors,UserRound}from'lucide-react';

export type WorkOrderWorkflowStep={key:string;title:string;subtitle:string;icon:React.ReactNode;keywords:string[]};
export const WORK_ORDER_WORKFLOW_STEPS:WorkOrderWorkflowStep[]=[
 {key:'guest',title:'Vendég',subtitle:'Vendég, szalon, munkatárs és érkezés',icon:<UserRound size={17}/>,keywords:['Szalon és munkatárs','Vendég']},
 {key:'history',title:'Előzmények / kedvezmény',subtitle:'Bérlet, hűség, kedvezmény és korábbi adatok',icon:<BadgePercent size={17}/>,keywords:['Hűség','Bérlet','Loyalty','Kedvezmény']},
 {key:'items',title:'Szolgáltatás és termék',subtitle:'Szolgáltatások és értékesítési tételek',icon:<Scissors size={17}/>,keywords:['Szolgáltatások','Termékek / anyagfelhasználás']},
 {key:'materials',title:'Anyag / készlet',subtitle:'Anyagfelhasználás és készletellenőrzés',icon:<PackageCheck size={17}/>,keywords:['Anyagfelhasználás','Készlet','Termékek / anyagfelhasználás']},
 {key:'review',title:'Ellenőrzés',subtitle:'Összesítés és hiányzó adatok ellenőrzése',icon:<ClipboardCheck size={17}/>,keywords:['Összesítő','Bruttó érték']},
 {key:'payment',title:'Fizetés',subtitle:'Fizetési módok és részfizetések',icon:<CreditCard size={17}/>,keywords:['Fizetés']},
 {key:'close',title:'Lezárás',subtitle:'Mentés, lezárás és továbblépés',icon:<CheckCircle2 size={17}/>,keywords:['Munkalap létrehozása','Munkalap mentése','Mégse']},
];
function findTarget(root:HTMLElement,step:WorkOrderWorkflowStep){const candidates=Array.from(root.querySelectorAll<HTMLElement>('section,article,footer,header,div'));for(const keyword of step.keywords){const hit=candidates.find(el=>{const text=(el.innerText||'').trim();return text.startsWith(keyword)||text.includes(keyword)});if(hit)return hit}return null}
export default function WorkOrderWorkflowNavigator({scrollRoot}:{scrollRoot:React.RefObject<HTMLDivElement|null>}){const[active,setActive]=useState(0);const targets=useRef<Array<HTMLElement|null>>([]);const steps=useMemo(()=>WORK_ORDER_WORKFLOW_STEPS,[]);useEffect(()=>{const root=scrollRoot.current;if(!root)return;const refresh=()=>{targets.current=steps.map(step=>findTarget(root,step))};refresh();const observer=new MutationObserver(refresh);observer.observe(root,{childList:true,subtree:true});const onScroll=()=>{const top=root.scrollTop+140;let best=0;targets.current.forEach((el,i)=>{if(el&&el.offsetTop<=top)best=i});setActive(best)};root.addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>{observer.disconnect();root.removeEventListener('scroll',onScroll)}},[scrollRoot,steps]);const go=(index:number)=>{setActive(index);const root=scrollRoot.current,target=targets.current[index];if(root&&target)root.scrollTo({top:Math.max(0,target.offsetTop-16),behavior:'smooth'})};return <nav className="wo-workflow-nav" aria-label="Munkalap rögzítési folyamat">{steps.map((step,index)=><React.Fragment key={step.key}><button type="button" className={`wo-workflow-step ${index===active?'is-active':''} ${index<active?'is-done':''}`} onClick={()=>go(index)} aria-current={index===active?'step':undefined}><span className="wo-workflow-index">{index<active?'✓':index+1}</span><span className="wo-workflow-icon">{step.icon}</span><span className="wo-workflow-copy"><b>{step.title}</b><small>{step.subtitle}</small></span></button>{index<steps.length-1&&<span className={`wo-workflow-line ${index<active?'is-done':''}`} aria-hidden="true"/>}</React.Fragment>)}</nav>}
