import React,{useCallback,useEffect,useMemo,useState}from'react';
import{FileCheck2,FileDown,Mail,ReceiptText,RefreshCw}from'lucide-react';
import api from'../../api';

type Props={workOrderId:string};

export default function WorkOrderDocumentsPanel({workOrderId}:Props){
 const[workOrder,setWorkOrder]=useState<any>(null);const[invoice,setInvoice]=useState<any>(null);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const closed=useMemo(()=>Boolean(workOrder?.locked_at||workOrder?.archived_at||workOrder?.status==='completed'),[workOrder]);
 const paid=useMemo(()=>Boolean(workOrder?.fully_paid||workOrder?.payment_status==='paid'||workOrder?.financial_closed_at),[workOrder]);
 const refresh=useCallback(async(silent=false)=>{if(!workOrderId)return;if(!silent){setBusy('refresh');setError('')}try{const[w,i]=await Promise.all([api.get(`/api/workorders/${workOrderId}`),api.get(`/api/transactions/workorder-invoice/workorders/${workOrderId}`).catch(()=>({data:null}))]);setWorkOrder(w.data);setInvoice(i.data||null)}catch(e:any){if(!silent)setError(e?.response?.data?.message||'A dokumentumadatok nem tölthetők be.')}finally{if(!silent)setBusy('')}},[workOrderId]);
 useEffect(()=>{const t=setTimeout(()=>void refresh(true),900);return()=>clearTimeout(t)},[refresh]);
 useEffect(()=>{if(closed)return;const t=setInterval(()=>void refresh(true),5000);return()=>clearInterval(t)},[closed,refresh]);
 const download=async(url:string,filename:string,key:string)=>{setBusy(key);setError('');setNotice('');try{const r=await api.get(url,{responseType:'blob'});const href=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=href;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),60000);setNotice(`${filename} elkészült és letöltődött.`)}catch(e:any){const msg=e?.response?.data instanceof Blob?'A PDF nem készíthető el.':e?.response?.data?.message||'A PDF nem készíthető el.';setError(msg)}finally{setBusy('')}};
 const createInvoice=async()=>{setBusy('invoice');setError('');setNotice('');try{const r=await api.post(`/api/transactions/workorder-invoice/workorders/${workOrderId}/draft`,{});setInvoice(r.data);setNotice('A számlatervezet elkészült.')}catch(e:any){setError(e?.response?.data?.message||'A számlatervezet nem készíthető el.')}finally{setBusy('')}};
 const sendWorkOrder=async()=>{setBusy('mail');setError('');setNotice('');try{await api.post(`/api/transactions/workorder-finalization/workorders/${workOrderId}/email`,{});setNotice('A lezárt munkalap PDF e-mail küldése elindult.')}catch(e:any){setError(e?.response?.data?.message||'Az e-mail küldése nem sikerült.')}finally{setBusy('')}};
 const number=String(workOrder?.work_order_number||workOrderId);
 return <section style={box}><div style={head}><div><div style={kicker}><FileCheck2 size={15}/> DOKUMENTUMOK</div><h2 style={{margin:'4px 0 0'}}>Munkalap és számlatervezet PDF</h2><p style={desc}>A végleges lezárás után a munkalap PDF az archivált snapshotból készül. A számlatervezet külön belső pénzügyi bizonylat.</p></div><button style={secondary} disabled={busy==='refresh'} onClick={()=>void refresh()}><RefreshCw size={15}/>{busy==='refresh'?' Frissítés…':' Frissítés'}</button></div>{error&&<div style={bad}>{error}</div>}{notice&&<div style={ok}>{notice}</div>}<div style={grid}><div style={card}><FileDown size={22}/><div><b>Lezárt munkalap PDF</b><small>{closed?'A dokumentum letölthető.':'A végleges lezárás után válik elérhetővé.'}</small></div><button style={primary} disabled={!closed||!!busy} onClick={()=>void download(`/api/transactions/workorder-finalization/workorders/${workOrderId}/pdf`,`${number}.pdf`,'workorder-pdf')}>{busy==='workorder-pdf'?'Készítés…':'PDF letöltése'}</button></div><div style={card}><ReceiptText size={22}/><div><b>Számlatervezet PDF</b><small>{invoice?`${invoice.invoice_no||'Számlatervezet'} · ${Number(invoice.gross_total||0).toLocaleString('hu-HU')} Ft`:paid?'A számlatervezet elkészíthető.':'Teljes fizetés után készíthető el.'}</small></div>{invoice?<button style={primary} disabled={!!busy} onClick={()=>void download(`/api/transactions/workorder-invoice/invoices/${invoice.id}/pdf`,`${invoice.invoice_no||'szamlatervezet'}.pdf`,'invoice-pdf')}>{busy==='invoice-pdf'?'Készítés…':'PDF letöltése'}</button>:<button style={primary} disabled={!paid||!!busy} onClick={()=>void createInvoice()}>{busy==='invoice'?'Készítés…':'Számlatervezet készítése'}</button>}</div></div>{closed&&<div style={mailRow}><span>A lezárt munkalap PDF-je e-mailben is újraküldhető a rendszerben beállított címzetteknek.</span><button style={secondary} disabled={!!busy} onClick={()=>void sendWorkOrder()}><Mail size={15}/>{busy==='mail'?' Küldés…':' PDF e-mail küldése'}</button></div>}</section>
}

const box:React.CSSProperties={maxWidth:1040,margin:'0 auto 18px',background:'#fff',padding:18,borderRadius:16,boxShadow:'0 8px 30px rgba(48,36,25,.08)',border:'1px solid #eee5dc'};
const head:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap'};const kicker:React.CSSProperties={display:'flex',alignItems:'center',gap:6,fontSize:11,fontWeight:900,letterSpacing:'.08em',color:'#826f60'};const desc:React.CSSProperties={margin:'5px 0 0',fontSize:12,color:'#6f665f'};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:14};const card:React.CSSProperties={display:'grid',gridTemplateColumns:'auto 1fr',gap:10,alignItems:'center',padding:14,borderRadius:13,background:'#faf7f3',border:'1px solid #eadfd5'};const primary:React.CSSProperties={gridColumn:'1 / -1',border:0,borderRadius:9,padding:'10px 13px',background:'#2b2118',color:'#fff',fontWeight:900,cursor:'pointer'};const secondary:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:6,border:'1px solid #dfd3c8',borderRadius:9,padding:'9px 12px',background:'#f6f1ec',color:'#2b2118',fontWeight:800,cursor:'pointer'};const bad:React.CSSProperties={marginTop:10,padding:10,borderRadius:9,background:'#fff1f0',color:'#b42318',fontSize:12};const ok:React.CSSProperties={marginTop:10,padding:10,borderRadius:9,background:'#ecfdf3',color:'#067647',fontSize:12};const mailRow:React.CSSProperties={marginTop:12,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',fontSize:12,color:'#6f665f'};
